### ISSUE TITLE
Providers should disable controllers (not panic) when claim CRDs are not found

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1007]
### What problem are you facing?

Infrastructure stacks (AWS, GCP, Azure, etc) operate on resource claims. They contain controllers that expect the claims they operate on exist - if they don't the controller panics at setup time (i.e. when the stack's controller manager binary first starts). This means if one of the four claim kinds an infrastructure stack supports does not exist the entire stack is non-functional. 

### How could Crossplane help solve your problem?

Stacks should start successfully when a resource claim they operate on does not exist, but disable any controllers that require that claim until such time as it exists.

**Comment by soorena776** [comment]
@negz
- What is the scenario where a stack is installed but one of the claim kinds is not yet created? Are there any scenarios other than a faulty stack package?
- In this case, how do we go about clearly notifying that one of the controllers is disabled? Debugging might become very hard if this happens silently. Could we disable the entire stack instead?

**Comment by negz** [comment]
We removed support for the kinds of resource claim this issue refers to.
