### ISSUE TITLE
Support for KMS to encrypt Provider credentials at rest

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1009]
### What problem are you facing?

Currently we are storing the provider credentials as secrets in K8S. These credentials have long-term expiration which provide a big range of sensitive access policies in the target account. Despite this level of sensitivity, these secrets are not encrypted and can be accessed by any identity who has the right cluster roles (independent from the target provider account). Additionally, these credentials are stored in etcd without encryption at rest.

### How could Crossplane help solve your problem?

Crossplane should give the option for the users to encrypt their credentials, using a key from a KMS service. For this to happen, Crossplane could have a *core stack*, which extends its functionality and supports data encryption, by leveraging a third-party KMS like Hashicorp Vault.

**Comment by bassam** [comment]
do we need to do anything here beyond what Kubernetes does today for storing secrets in a KMS?

**Comment by muvaf** [comment]
Per https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/ this is related to how user configures their k8s cluster that they choose to run Crossplane. So, I feel like it's more of their responsibility to keep the secrets secure rather than the applications running in their cluster.

**Comment by muvaf** [comment]
It could be possible for users to use Vault to manage all of their `Secret`s via Vault by using its CSI driver, though I didn't dig into it much. Just leaving it here for reference https://github.com/kubevault/csi-driver

**Comment by gowrisankar22** [comment]
It would be great if crossplane provides the integration to any of the external credential management systems. Example: vault ,credhub etc ...

Also, it would be also interesting to publish credentials to respective providers kms service.

aws-provider -- aws kms service
azure-provider -- azure kms service
gcp-provider -- gcp kms service
Alibaba-provider -- alibaba kms service

**Comment by muvaf** [comment]
I think this issue can be closed because of the reasons listed in https://github.com/crossplane/crossplane/issues/1009#issuecomment-548388787

@gowrisankar22 https://github.com/crossplane/crossplane/issues/1424 is I believe what you're looking for. This was related to the backend of `Secret`s and how they are stored in the cluster.
