### ISSUE TITLE
Are there any issues preventing installation of multiple versions of a namespace stack?

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1014]
### What problem are you facing?
In a dev environment if working with different versions of the same stack, that they can be installed/uninstalled cleanly into different workspaces in the same environment, such that for 3 workspaces (jared, marques, and phil) we can each work in our own workspaces developing different versions of the CRD for the same stack (e.g. if marques is fixing a bug in an older version of an app stack, jared can be working on a newer version of the same stack with the same CRD names, but with a new version).

According to the [security/isolation design doc](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#multiple-versions), Namespace Stacks (`StackInstalls`) can have multiple instances installed per Crossplane cluster, and they can have different versions.

This has not actually been attempted so far, so we should try this scenario out and identify any issues that block this scenario from being reality.  What bugs are there that would cause this scenario to fail?

### How could Crossplane help solve your problem?

The stack manager should support this scenario of multiple instances of a namespace stack being installed.  Let's find the blocking issues that prevent this.

### Problem 1

Namespace Stacks (`StackInstalls`) can have multiple instances installed per Crossplane cluster.  Furthermore, they may also be at different versions from each other.  This is described in detail in the [security/isolation design doc](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#multiple-versions).

If an existing version of a Namespace Stack is already installed and a new version is attempted to be installed, the Stack Manager will currently see that the CRDs already exist and do nothing.  This means that any new versions of the CRD that are in the new version of the stack will be ignored and not installed.

The Stack Manager should be smarter about how it handles multiple versions of a namespace stack.  Instead of seeing that a CRD already exists and doing nothing, it should attempt to "update" the existing CRD with the new schema/versions in the new stack.  Example:

Stack `foo:v1` is installed which has CRD `bar.group.io/v1`.  If stack `foo:v2` gets installed which has CRD `bar.group.io/v2`, we should end up with a merged/updated CRD `bar.group.io` that has both versions `v1` and `v2`.

We'll need to think through this carefully, I'm sure there are plenty of pitfalls.

**Homework research problem**: what is the right behavior to do in general (upstream k8s) if a CRD is installed when an older version of it already exists? Is there upstream guidance on this?

**Comment by negz** [comment]
I believe we're currently planning to remove the concept of namespaced packages (fka stacks), so I think this can be closed. CC @hasheddan.

**Comment by hasheddan** [comment]
@negz that is my impression as well 👍
