### ISSUE TITLE
Stack should include a list of Claim types it consumes or creates

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1028]
### What problem are you facing?

Crossplane creates ClusterRoles (and Roles) for the dependent types needed for a Stack controller to operate.

As described in https://github.com/crossplaneio/crossplane/pull/1008, users of Crossplane may benefit from ClusterRoles that can be bound to users, groups, and serviceaccounts to offer access to use a Stack's types.

Some Stack's may require a Claim to be useful.  The process of generating ClusterRoles (per #1008) may be benefitted if the Stack's known claim types were defined in advance.

When the StackManager creates the ClusterRoles during a Stack install, users bound to this ClusterRole would be able to manage the Claim types needed to operate the Stack or administer the Stack's byproducts.

Stacks can have multiple relationships to claim types:
- A Stack can create claim records (Wordpress stack creating MysqlInstance records)
- A Stack can provide types that use claims as parameters (KubernetesApplication uses a KubernetesCluster label selectors and must list KubernetesCluster resources)

If Crossplane core itself should becomes a Stack, the Claim types provided should be identified so the appropriate clusterroles can be created. We could then add an extra Stack / claim type relationship:

- A Stack can provide claim types (no current examples of this, but we are under the pretense of Crossplane Core becoming a Stack. Crossplane-Core provides KubernetesCluster, MysqlInstance)

Claim types should also be defined within a Stack to benefit #899, the restriction of types that a Stack deployment can interact with (depending on the relationship, a Stack could need list/read, watch/read/update, or '*').

_Namespaced Stacks may want to provide claim types too (TODO: create an issue for this, link it).  Special roles will need to be assigned to watch these types._

### How could Crossplane help solve your problem?

Design or define how claim types can be consumed by Stacks.

If this is already possible with "dependsOn" and "owns" Stack mechanics, elaborate in existing documentation.  I don't believe this is the case today.

**Comment by negz** [comment]
I don't think this is relevant anymore given our move away from packaging applications that would in turn create claims, and given the deprecation of claims themselves.
