### ISSUE TITLE
Stacks should be able to provide predefined resource classes

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1029]
### What problem are you facing?

A Stack should be able to include predefined Crossplane resource classes.  A Foo Infra Stack could bundle resource classes matching generalized configurations.

A Stack should also be able to include ONLY predefined Crossplane resource classes.  This Stack would not need a controller.

### How could Crossplane help solve your problem?

#865, #1011, and the [ROADMAP for 0.5.0](https://github.com/crossplaneio/crossplane/blob/69c24e755d513841dde400761521aa7bc04639b9/ROADMAP.md#under-consideration-for-v050) mention "resource packs" in epic style, with no further definition of what this means.  Define what a resource pack is and how it can be used.

What benefit do these resource class CR bundles (resource packs) provide over a controller based stack that defines new resource types "OpinionatedFoo", where the controller has the benefit of setting default values and bundling additional resource types into an OpionatedFoo (for example, a special Foo with a preconfigured VPC).

How are these resource classes CRs deemed acceptable (and not abusive)?
* Does the existing Stack dependency management offer a means for the Stack Manager to assert that the CRDs for the resource class CRs exist? Should the SM check if the  CRDs are annotated as resource class types?  Is there a need for a new dependency list focused on resource class types?
  If a Bar Stack says it provides resource packs for CRD Foo, the Stack Manager can assure that Foo is installed and that Foo has been labeled as a resource class.

Is it acceptable for a Stack to not include a controller? A Stack may not need a controller if it only provides resource class CRs.  Would we prefer, at least initially, that the Stack responsible for the CRD is the only Stack providing resource class CRs for that Stack?

Should the ClusterStackInstall provide an option to omit the default resource classes?

**Comment by jbw976** [comment]
Is this essentially the same idea that has been floating around about "resource packs" or "class packs" @displague? Is there not already an issue opened on that idea?

**Comment by displague** [comment]
https://github.com/crossplaneio/crossplane/issues/865,  https://github.com/crossplaneio/crossplane/issues/1011, and https://github.com/crossplaneio/crossplane/blob/69c24e755d513841dde400761521aa7bc04639b9/ROADMAP.md#under-consideration-for-v050 mention "resource packs" in epic style, with no further definition of what this means.

This issue would track any progress or discussion on making these possible.  We can rename the issue if that helps.

**Comment by displague** [comment]
@jbw976 I updated the description of this issue to include 'resource pack' phrasing and references.

**Comment by displague** [comment]
This has effectively been implemented with the following examples:
* https://github.com/crossplane/stack-aws-sample
* https://github.com/crossplane/stack-gcp-sample
* https://github.com/crossplane/stack-azure-sample

I believe my original wording and thinking behind this was that we could offer CR instances of `FooClass`.  The sample stacks above achieve this dynamically with an added layer (offering a CRD) that is reconciled through the [templating controller](https://github.com/crossplane/templating-controller).
