### ISSUE TITLE
Package usage improvements through reusable Cluster, Namespace, and Package Roles

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1036]
### What problem are you facing?

Stack Isolation has been tackled before (#580) in terms of settling the environments (#958) and roles necessary to operate controllers (#663).

Crossplane Stacks do not however offer guidance, models, or tools for managing the usage of Stacks within their isolation environments.

How can users be granted the ability to install a Stack? List the Stacks they can manage?
Can these users interact with the side-effect resources or the required resources of the Stacks they can manage?  Do Stacks need to declare additional details so users can be afforded access to side-effect and required resources?

Who and how do administrators assign and manage these roles? What additional roles do these administrators possess? Where are the boundaries of these roles?

How does Crossplane itself manage these roles, including the identification of these roles so they may be managed over time.  What happens when a Stack is updated? How can users and administrators take advantage of these processes to accomplish similar goals?

#### What does it look like when its done?

* The Stack Isolation and Namespace environments design is updated to answer these concerns
* Users can install a stack using a predefined set of roles
* Some set of user personas are able to interact with the required and resultant resources
* Stacks Usage documentation covers the roles available, how they are (automatically) defined and refined, and how these roles may (manually) be assigned and used
* The Stacks format is extended to provide the necessary information
  * The Stack Manager is updated to process this information
  * The Crossplane CLI has been updated to gather this information
  * Existing Stacks have been updated to include the information

#### Related Issues 

_For a given design, a breakout is provided of the issues related to each sections of the design. Issues that have not been created yet should be indicated with an `(Issue: ...)` stub. Dependencies on Epics and Designs should be called out (bold) because they are traps until they are closed or can be mutually closed with this Epic._

* crossplaneio/crossplane#1008 **Design** Security Model & RBAC Roles
  * **"Discoverability of Scope"**
    * crossplaneio/crossplane#1015 CRD labelling for workspaces
  * **"Cluster stacks"**
    * #1048 CRDs should be labeled with their 'scope' (environment/workspace)
    * #1049 Create a reusable ClusterRole for the Stack deployments
    * crossplaneio/crossplane#981 ClusterStackInstall - Cluster scoped
       * [Implementation](https://github.com/crossplaneio/crossplane#1023)
  * **"Environment"**
    * #1050 Create a reusable (environment) ClusterRole for Stack admins, editors, and viewers
    * #1150 Restrict Cluster stacks to a single install
      * #1151 Stacks need a unique identifier (app.yaml: id)
  * **"Namespace Stacks"**
    * crossplaneio/crossplane#899 Restrict stack dependency types
      "Consume and build on functionality from cluster stacks in the form of resource claims"  
  * **"Cluster Stack Single Instance Version Limitation"**
    * #435 **EPIC:** Design to allow multiple versions of cluster stacks per control plane
  * **"Multiple Versions"**
    * https://github.com/crossplaneio/crossplane/issues/1014 What problems existing with multiple versions of the same namespaced stack?
    * #1051 Support multiple instances of the **same** StackInstall / Stack in different namespaces
    * #1052 Reject instances of a StackInstall that conflict with installed StackInstalls
    * #1013 instances of a newer StackInstall should update CRDs
  * **"Crossplane ClusterRoles / RBAC"** / **"Default ClusterRoles for aggregation"**
    * #1053 StackManager should ensure base ClusterRole exists for cluster admin, editor, viewer
    * #1111 Create `crossplane:master` group
  * **"Crossplane ClusterRoles / RBAC"** / **"ClusterRoles for a given (Cluster)Stack Install"**
    * #1099 ClusterStackInstalls should create stack+version specific clusterroles grant use on included CRD types
       (These are aggregated to cluster admin, editor, and viewer)
  * **"Crossplane ClusterRoles / RBAC"** / **"ClusterRoles for a given app namespace."**
    * crossplaneio/crossplane#1113 StackManager should create workspace specific clusterroles
    * crossplaneio/crossplane#1124 StackManager should manage workspace specific clusterroles for any properly labelled namespace
    * crossplaneio/crossplane#1099 Namespaced StackInstalls should create stack+version specific clusterroles including CRD types
    * crossplaneio/crossplane#1028 Stacks metadata should include Claim types
    * crossplaneio/crossplane#1010 Claim types should reflect resource status for users without access to the resource type

**Comment by prasek** [comment]
@displague can we close this out now that https://github.com/crossplaneio/crossplane/pull/1059 landed?

//cc @jbw976

**Comment by displague** [comment]
@prasek Right, the stragglers are why this has been kept open.  If we revisit this epic in a couple of sprints we'll find most of the stragglers (a result of the overarching scope of this epic as written) should be closed.

**Comment by negz** [comment]
I think we can close out this epic, as it doesn't represent our current thinking for Packages (neé Stacks).
