### ISSUE TITLE
Stack Manager should support configuring different Kubernetes API servers for CRs and controllers

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#1038]
### What problem are you facing?
Crossplane controllers only need Kubernetes api server to operate on Custom Resources. Having a full Kubernetes cluster (with scheduling capabilities) should not be mandatory for Crossplane as long as controllers running somewhere and configured against a Kubernetes Api Server instance.

### How could Crossplane help solve your problem?
Stack Manager should support configuring different Kubernetes API servers for running the install/controller pods and watching/acting on Custom resources. This will enable deploying multiple Crossplane instances watching different Kubernetes API servers (i.e. multiple API servers running in different namespaces) on a single Host Kubernetes cluster.

**Comment by prasek** [comment]
@displague @turkenh is anything left for this issue to get closed out?

**Comment by turkenh** [comment]
Resolved with #1139
