### ISSUE TITLE
Package Manager should redeploy package controllers if they do not exist

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#1042]
### What problem are you facing?
If a stack is deployed but its controller deployment no longer exists somehow, Stack Manager takes no action to bring system into working state again.

### How could Crossplane help solve your problem?
Stack Manager should redeploy stack controllers if they do not exist. 

This is a needed feature to be able restore a system from a backup for scenarios where [a separate host is configured in Stack Manager for running stack controllers](https://github.com/crossplaneio/crossplane/issues/1038).

**Comment by displague** [comment]
StackInstalls whose `Job` are deleted while `Ready` is `False`, fall into a `Synced` `False` state.

Should `StackInstall` records also recreate their `Job` resource? (relates somewhat to https://github.com/crossplaneio/crossplane/issues/1116)

**Comment by turkenh** [comment]
AFAIK, there is no reason to keep/depend on that `Job` once the corresponding `Stack` instance created (a.k.a. stack installed). If this is correct, I don't think that think we need to recreate it.

**Comment by jbw976** [comment]
agreed, i would treat jobs as ephemeral and only for the purpose of initially unpacking the stack during installation.  it would actually be nice if we deleted the jobs once they were completed, I've always been annoyed that they hang around until the entire stack is uninstalled.

**Comment by hasheddan** [comment]
This has been fixed in the new package manager :slightly_smiling_face:
