### ISSUE TITLE
Reject instances of a PackageInstall that conflict with installed PackageInstalls

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1052]
### Problem #1

Part of #1036

The [Stacks Security and Security Isolation One-Pager](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md) was updated and expanded requiring new Stack behaviors.

https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#multiple-versions: 

> The custom resource definitions themselves are always cluster scoped. If two versions of a namespace stack are installed in the control plane and they have identical CRD versions, there could be a conflict.
> 
> To illustrate this clearly, consider the following example:
> 
> Namespace Stack foo-v1.0 is installed along with its CRD that has version v1beta1
> * A minor update to namespace stack foo is released as version foo-v1.1
> * This update to the namespace stack adds a new field to the CRD but does not increment the CRD version
> * The control plane now has 2 versions of the namespace stack's controllers (foo-v1.0 and foo-v1.1), but only 1 version of the CRD (v1beta)
> 
> Which CRD schema should "win" in the control plane?
> 
> * The new CRD schema with the new field that the old controller doesn't understand?
> * The old CRD schema without the new field that the new controller wants to use?

To avoid unexpected errors and behaviors that have not been designed for, in support of #1051 with an awareness of #1014, block the installation of StackInstalls with conflicted CRDs.

### How could Crossplane help solve your problem?

Reject instances of a StackInstall that conflict with installed StackInstalls

### What problem are you facing?

Part of #1036, Counterpart of #1014

Cluster scoped stacks (installed using ClusterStackInstall resources) provide cluster scoped CRDs and ClusterRoles, just as namespace scoped stacks do (installed using StackInstall resources).

Cluster scoped stacks have the ability to create cluster scoped resources, such as infrastructure resources (`GKECluster`, `RDSInstance`).

Namespaced stacks have the ability to create namespaced scoped resources, such as application resources (`WordpressInstance`).  As expressed in #1014, a namespaced resource should be useable in many namespaces.  To support that the controller for these resources must be run in each namespace, and that requires a StackInstall and resultant Stack in each namespace.

Cluster scoped resources, however, should be managed by a single controller and only be represented once in a cluster.  This opinion is bolstered by the notion that infrastructure stacks have a relationship with external resources, for which cluster scoped resources can have a one to one mapping. 

(TODO: improve the argument for why this is and why there should be only one. Maybe this prologue is unnecessary?)

Nothing prevents a user from installing stack-gcp multiple times under different names.  The stack installer will ignore any errors from duplicated CRDs.  This creates an undefined parent labelling relationship and provides no user benefit.

(TODO: why is this a problem for clusterstackinstalls, but not stackinstalls)

### How could Crossplane help solve your problem?

Restrict Cluster stacks to a single install.  ClusterStackInstalls should fail if the CRDs are already present in the cluster, especially when a different owner is in place.

Do we need an issue to limit Stacks to a single occurrence per namespace?

**Comment by hasheddan** [comment]
This has been addressed in the new package manager :tada:
