### ISSUE TITLE
Crossplane helm chart: Crossplane installation using helm3 fails because `crd-install` hook is deprecated

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1062]
### What happened?

Installing Crossplane using helm3:

```bash
helm3 install crossplane  --namespace crossplane-system crossplane-alpha/crossplane 
```

Produces the output:

```bash
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: crossplane
LAST DEPLOYED: Wed Nov 13 20:39:46 2019
NAMESPACE: crossplane-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Release: crossplane

Chart Name: crossplane
Chart Description: Crossplane - Managed Cloud Resources Operator
Chart Version: 0.4.1
Chart Application Version: 0.4.1
```

However, running `kubectl get pods -A` results:

```bash
NAMESPACE           NAME                                         READY   STATUS             RESTARTS   AGE
crossplane-system   crossplane-6cf4c86df9-dcfh9                  1/1     Running            0          10s
crossplane-system   crossplane-stack-manager-59bb94f5d-nvfzt     0/1     CrashLoopBackOff   1          10s
```

After some digging, it turned out this is because two of the CRDs (`StackInstall` and `ClusterStackInstall`) that have [`helm.sh/hook: crd-install`](https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/crds/stacks.crossplane.io_stackinstalls.yaml#L5) annotation, are skipped from being created (because this hook is deprecated in [v3](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks)), hence causing the corresponding stack-manager controller to fail.

### Potential fix

Since helm v3 is now stable, and supports `crds/` folder, we can increase the minimum required version of helm to v3 in our [doc](https://github.com/crossplaneio/crossplane/blob/master/docs/install-crossplane.md#installation), and then remove this hook.

### What environment did it happen in?
Crossplane version: v0.4.1
helm version: v3.0.0

### Related
#839 
#1027

**Comment by displague** [comment]
Noting what the current experience looks like from the master channel:

```
$ kind create cluster --name foo
$ kubectl config set-context kind-foo
$ helm3 repo add crossplane-master  https://charts.crossplane.io/master/
$ helm3 repo update
$ kubectl create namespace crossplane-system
$ helm3 install crossplane crossplane-master/crossplane -n crossplane-system  --devel
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: crossplane
LAST DEPLOYED: Thu Jan 16 10:48:29 2020
NAMESPACE: crossplane-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Release: crossplane
Chart Name: crossplane
Chart Description: Crossplane - Managed Cloud Resources Operator
Chart Version: 0.6.0-rc.32.gc06433f
Chart Application Version: 0.6.0-rc.32.gc06433f
Kube Version: v1.16.3
```

**Comment by hasheddan** [comment]
These hooks no longer exist as we have dropped support for helm 3 :+1:
