### ISSUE TITLE
Support a minimum number of `kubebuilder:printcolumn` columns for all CRs

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1063]
### What problem are you facing?

While some CRs have a verbose number of fields to be printed (by using `kubebuilder:printcolumn` comment tags) when retrieved by `kubectl` (e.g. [GKECluster](https://github.com/crossplaneio/stack-gcp/blob/master/apis/compute/v1alpha3/gkecluster_types.go#L206)), some others do not have any (e.g. [Network](https://github.com/crossplaneio/stack-gcp/blob/master/apis/compute/v1alpha3/network_types.go#L43)). From the user perspective this is inconvenient and non consistent, especially there are popular statuses like `Ready` and `ReferencesResolved`.
### How could Crossplane help solve your problem?

Create a minimum set of columns to print for all CRs. This minimum set could be enforced (or at least the lack of them be warned) in integration tests.

**Comment by negz** [comment]
It also may be possible that we could solve this with code generation - we're already able to detect managed resources and resource claims by their shape and are able to manipulate comments.

**Comment by muvaf** [comment]
Most providers use our guides for implementation and code templates there include these comment tags. I think it's better to track this on per-provider basis.
