### ISSUE TITLE
AWS wordpress example works only in us-west-2 without manual intervention

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1065]
### What happened?

I am following stacks guide aws https://crossplane.io/docs/v0.4/stacks-guide-aws.html

The line that deploys the network configuration points to here https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/workloads/kubernetes/wordpress/aws/network-config

While all my resources are being deployed to the region that is given in my `Provider` resource, subnets.yaml has a hard-coded `us-west-2a,b,c` values as availability zones. If you don't edit that manually, it fails when you have a different region in your `Provider` resource.

### How can we reproduce it?

* Create an AWS `Provider` object with a region other than `us-west-2`.
* Follow stacks guide. Subnets will never come up.
### What environment did it happen in?
Crossplane version: 0.4

**Comment by soorena776** [comment]
@muvaf there is an issue to remove the region from `Provider` resource.
https://github.com/crossplaneio/stack-aws/issues/38

The idea is that the region should be tied to the individual resources, so I think editing the region of your choice is expected.

**Comment by muvaf** [comment]
Fixed by https://github.com/crossplane/provider-aws/pull/320
