### ISSUE TITLE
Support Installing Crossplane using `kubectl`

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1066]
### What problem are you facing?

Since  `kubectl` command now supports installing remote resources  by using

```bash
kubectl apply -f <remote folder>
```

It is possible to deploy Crossplane in a cluster using `kubectl` entirely. This is preferred over the current `helm` approach, since it doesn't introduce a dependency to an additional tool. 

### How could Crossplane help solve your problem?

Support installing Crossplane using `kubectl`.

**Comment by jbw976** [comment]
I like this idea a lot, and I suspect we could do it with `kubectl apply -k` that uses kustomize to apply configuration patches too.  Such as debug logging.

**Comment by soorena776** [comment]
Correct. A sample patch which covers a general case could be explained in the docs.

**Comment by negz** [comment]
I'm going to dedupe this in #252, which has the most discussion of a handful of issues around this topic.
