### ISSUE TITLE
Break API types into their own module

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1085]
### What problem are you facing?

This repository (and Go module) currently contains:

* The code required to build the "core" `crossplane` controller manager binary, which includes the stack manager and workload controllers.
* The API type definitions for all resource claims (e.g. `MySQLInstance`, `KubernetesCluster`, etc).

The workload controllers currently consume the `KubernetesCluster` resource claim API type, but otherwise the controllers in this repo no longer have any knowledge of the resource claim API type definitions. Infrastructure stacks on the other hand, are tightly coupled to them. Each infrastructure stack depends on a specific version of this Go module (only) in order to consume its resource claim API type definitions.

This is is not ideal because:

* It requires the API types defined by this module to be versioned and released in lock-step with the (almost entirely unrelated) core controllers defined by this module. Releasing a new or updated API type requires a new release of Crossplane, even though that type is almost certainly not used by the actual Crossplane controller manager.

* It means infrastructure stacks have both a direct and transitive (via this module) dependency on various `k8s.io` and `sigs.k8s.io` modules (controller-runtime, controller-tools, client-go, apimachinery, etc etc), forcing them to align with the dependencies controllers defined by this module unnecessarily.

### How could Crossplane help solve your problem?

The resource claim types defined by this module could be broken out into a new one (and thus most likely into a new module) that could be imported by stacks without taking a dependency on this module (and thus modules required by its controllers). I believe the "core" API types defined in the crossplane-runtime module should also live in this APIs module, though I'm less sure about the stacks and workloads API type definitions.

**Comment by muvaf** [comment]
In general, I feel like the less number of repositories we have, the better for maintenance and smooth navigation for users; browsing issues & PRs and also less syncronization overhead between modules and their versions.

I suggest that we move them to crossplane-runtime and let stacks consume only that repository. Though, in that case we define a new claim type, the user would have to update their crossplane-runtime dependency which is kind of overkill to get another type. However, this is not something happens frequently anyway.

In the case where we moved all claims and core apis(which I assume you mean `ResourceClaimSpec`, `ResourceSpec` etc.) to another standalone repository, we introduce yet another level in the dependency tree. In fact, stack will depend on crossplane-runtime(which does have k8s.io dependencies) and both stack and crossplane-runtime will depend on api repository and version of api repository that crossplane-runtime uses has to be compatible with stack's usage. In the end, I don't think we get rid of so much dependency problem but we pay the cost of synchronization of another dependency.

**Comment by displague** [comment]
It would be useful to have these types in a Stack so that we can bundle the appropriate metadata for the Core types.

https://github.com/crossplaneio/crossplane/issues/751#issuecomment-543285321

**Comment by negz** [comment]
I believe this should no longer be an issue once we remove resource claims and move the OAM appconfig controller out of core. At that point Crossplane (core) will only define types for which it actually has controllers, and providers will not need to import Crossplane core.
