### ISSUE TITLE
Tag Provider images for Crossplane compatibility

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1090]
### What problem are you facing?

We've broken Stacks out of Crossplane core, but we're maintaining a murky relationship between which versions of Crossplane core are compatible with which stacks. This makes it difficult for users to know which stack should be used with which Crossplane, and means Crossplane maintainers must search through docs replacing version strings as part of each release process.

### How could Crossplane help solve your problem?

I suggest we tag stack images for compatibility with Crossplane, e.g.:

```
crossplane/stack-gcp:latest-0.5  # Or something similar.
```

We might also consider actually versioning stacks in lock-step with Crossplane, e.g. skip to release 0.6 of Crossplane owned stacks when we release Crossplane 0.6. This would mean that if you're running Crossplane 0.6 you need to install stack-foo 0.6. Other project (e.g. Alpine Linux) model this by using different granularity semver tags:

```
crossplane/stack-gcp:0.6    # Installs the latest 0.6.x patch release
crossplane/stack-gcp:0.6.2  # Installs 0.6.2 specifically
```

That said, I would prefer us to move toward stacks being less coupled to Crossplane rather than more coupled.

**Comment by soorena776** [comment]
I have been thinking about this as well. My suggestion would be to make Core installation automatic, once a user wants to install a stack:
- Bob submits a command to install stack-gcp@v0.2
- stack-gcp@v0.2 has an internal manifest that requires Core@v0.4 
- if
    - Core is already installed
        - if Core version == v0.4, then good to go
        - otherwise print incompatibility error
    - Core is not installed, then automatically install Core@v0.4

**Comment by negz** [comment]
> [If] Core is not installed, then automatically install Core@v0.4

Is this possible? My understanding is that we install stacks using a `StackInstall`, which requires the stack-manager (part of core) to be installed already.

**Comment by soorena776** [comment]
You are right, just realized that it is not possible with the current `StackInstall` approach.

Beside Core version dependency, the other reason that this issue struck a chord with me was that as I have installed `stack-gcp` in a fresh cluster for several times, I had wondered why it is necessary for the user to manually install Crossplane beforehand, whereas the Crossplane dependency is implied and could be automatically resolved. One way to achieve this automation could be to put the `StackInstall` logic in a docker image, and make the install process create a pod and run this image which in turn checks for the conditions mentioned above and installs the required resources.

However, I realize that providing an alternative route for installing stacks could result in confusion, so this could be ignored for now.

**Comment by displague** [comment]
@soorena776 @negz I think #1154 complements this concern very well.

Because Stacks already have the intention of declaring their dependencies and versions, we could push this tagging concern off to dependency resolution.  #1154 suggests that the core claim and class types should exist within their own stack.

This approach would not help if your concern is that a specific version of stack-manager is required. This is outlined in #900.

Are there concerns that are not met by these open issues? Perhaps concerns that crossplane-runtime may change in some way that the Stacks (built on crossplane-runtime) interacting with one another should be aware of?

**Comment by displague** [comment]
The CRD version is one factor of compatibility, the version of the controller is perhaps another.

The Stack dependency design will need to make sure that it continues to honor the intention of allowing dependency specification by package name and version or CRD group/version.
