### ISSUE TITLE
Import existing external resources, as managed resources

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1093]
### What problem are you facing?

In some scenarios, it's desirable to control existing external resources with Crossplane. For instance, one might want to control an existing `gke-cluster` with Crossplane, without having to create one. This would allow the user to take advantage of Crossplane features like continuous reconciliation and resource abstraction.

### How could Crossplane help solve your problem?

Crossplane should allow importing existing external resources (like a GKE cluster). I would envision a syntax like below for this purpose:

`kubectl crossplane import <resource-uri> --object-name=<my-resource>`

where  `<resource-uri>` is the cloud provider uri for the resource and `object-name` is the K8S api object name.

**Comment by hasheddan** [comment]
@soorena776 I believe we are handling tracking of this functionality in https://github.com/crossplaneio/crossplane-runtime/issues/22, mind if I close this in favor of the existing issue?

**Comment by soorena776** [comment]
Thanks @hasheddan! I didn't find a related issue over here but didn't search it there. I am fine if you want to close this one, but I would also suggest we keep user-facing issues and features in Crossplane itself for visibility.

**Comment by hasheddan** [comment]
Will defer to @negz on this one

**Comment by soorena776** [comment]
To be clear, I'm suggesting porting crossplaneio/crossplane-runtime#22 to crossplaneio/crossplane.

**Comment by negz** [comment]
I moved https://github.com/crossplaneio/crossplane-runtime/issues/22 from this repo to crossplane-runtime because I feel it's best to track the issues in the repo closest to the code they relate to, and in this case that's crossplane-runtime.

I think this issue covers a slightly larger scope though - https://github.com/crossplaneio/crossplane-runtime/issues/22 covers supporting this from a controller/library perspective, while this issue also discusses a potential UX for importing resources via a CLI

Let's leave both issues open for now; this will likely become an epic when this work is prioritised.

**Comment by negz** [comment]
@muvaf and I were chatting about this yesterday, and realised that it should actually be possible at the moment for v1beta1 managed resources. I believe to import a managed resource into Crossplane:

1. Craft a YAML managed resource representation of the existing external resource. If you don't want Crossplane to modify the existing external resource you must ensure `.spec.forProvider` matches the current state.
1. Set the `crossplane.io/external-name` annotation to the name of the existing external resource.
1. Submit the YAML managed resource you created in step 1.

This should cause Crossplane to bring the external resource into its management. The `Observe` function will determine that the desired resource already exists and proceed to attempt to update it.

This may mean we have a foundation for importing existing resources without implementing anything at the controller-runtime level. External resources use the (randomly generated) name of their managed resource by default, so it's _quite unlikely_ that we'll accidentally adopt an existing resource unless the author sets the `crossplane.io/external-name` annotation on either the resource or claim. You could argue that if the author sets that annotation to the name of a resource that exists, they're asking for that resource to be imported to Crossplane. 🤔 

If we did take that position I think there's still a case for a `kubectl crossplane import <resource-uri> --object-name=<my-resource>` command that:

1. Reads the existing external resource.
1. Creates a managed resource YAML representing that resource.
1. Submits it to Crossplane.

**Comment by muvaf** [comment]
> kubectl crossplane import <resource-uri> --object-name=my-resource

I'd love that experience. Though I am not sure how much logic would have to be introduced into the CLI tool, especially authorization to provider and conversion from SDK object into our managed resource object mechanisms. The more we could delegate that work to corresponding stack, the better. But at the same time, there could be some code-sharing from stack's repo, so, it may not be a big deal after all.

**Comment by negz** [comment]
> The more we could delegate that work to corresponding stack, the better.

I agree the complexity of reading an existing resource and forming a managed resource would fit better with each stack rather than in a CLI. It might be nice to keep the import logic separate from the normal reconcile logic; perhaps in a webhook or separate controller?

```
crossplane import cloudsqlinstance.gcp.crossplaneio/v1beta1 <resource-uri> --name coolinstance
```

Perhaps the above CLI just creates something like this:

```yaml
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstanceImport
metadata:
  name: coolinstance
spec:
  resource-uri: foo
status:
  resourceRef:
    apiVersion: database.gcp.crossplane.io/v1beta1
    kind: CloudSQLInstance
    name: coolinstance
  conditions:
    type: Imported
    status: True
    # etc...
```

A little imperative, but it does create a nice record of the import action.

**Comment by muvaf** [comment]
I like that idea. The CLI could just create `CloudSQLInstanceImport` and watch its status and when it's ready just print a `kubectl get` command for user to see it.

**Comment by negz** [comment]
This issue is older, but https://github.com/crossplane/crossplane-cli/issues/66 duplicates it in the CLI repo, which I think is the right place for it. I'm going to close this issue and roll it into the new one.
