### ISSUE TITLE
Formalize design acceptance process

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1104]
### What problem are you facing?

As the Crossplane community grows, it is important to ensure that contributors have an opportunity to participate in design discussions. Currently, enhancements and complex architecture decisions are reflected in one-pagers and design documents. The process for accepting these proposals is not currently well-defined, and may vary based on the impact and complexity of the design.

### How could Crossplane help solve your problem?

A formal process should be established for creating, accepting, and implementing new proposals. It may be useful to take lessons from existing processes in other project such as Kafka [KIPs](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) and Kubernetes [KEPs](https://github.com/kubernetes/enhancements),

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/tree/09bc8/design#crossplane-design-documents

We have the beginnings of some guidance here, but I agree that more is needed.

**Comment by negz** [comment]
I feel like the process I mentioned in my last comment has actually been working pretty well. I suspect eventually we will need something a little more robust like KEPs, but for our current scale I think we're good. I'm going to close this until we start seeing pain here.
