### ISSUE TITLE
Allow infrastructure operators to define claim kinds

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1106]
### What problem are you facing?

In short, Crossplane's built in set of portable resource claims attempt to be applicable to all possible cloud providers, and this greatly reduces their potential to express configuration options.

Crossplane defines a handful of _resource claim_ kinds whose CRDs are installed by Helm along with the "core" Crossplane controllers. Infrastructure stacks define _managed resources_ that may satisfy these claims by binding to them. Most extant resource claims are _portable_ in that they can be satisfied by the managed resources of different providers. For example a `MySQLInstance` claim could be satisfied by a GCP `CloudSQLInstance` or an AWS `RDSInstance`. Claims may trigger the dynamic provisioning of the managed resource that will satisfy them. The managed resource is configured using the claim and a _resource class_ as inputs.

Portable resource claims are subject to the "lowest common denominator" problem of multi-cloud; when a claim may provide configuration inputs that may be used to either match or dynamically provision many kinds of managed resource it may support only the settings that apply to all managed resources. This is in part why Crossplane currently supports relatively few resource claim kinds. Meanwhile, it's possible that a particular infrastructure operator deploys Crossplane to provide an opinionated abstraction for the application operators in their organisation and that their organisation _only uses AWS_. This organisation values Crossplane's _separation of concern_ but does not need its portability. Why should this organisation's application operators be limited to submitting resource claims that could be satisfied by any cloud provider when they could expose more settings, knowing that their claims would always be satisfied by an RDS instance? Perhaps the organisation uses AWS and Azure, but not GCP. Why should their resource claims be constrained to features supported by GCP?

### How could Crossplane help solve your problem?

Crossplane could defer the task of defining resource claims to infrastructure operators; each organisation could define (and/or install via a stack) the set of resource claims most useful to them. This would include defining the schema of their new resource claims, as well as which managed resources those resource claims may bind to, and how they may be used to dynamically provision those managed resources.

**Comment by negz** [comment]
It's worth noting that this pattern is _possible_ today, but requires writing Go code. e.g.:

1. Create a new stack for your bespoke resource claim.
1. Define the API type for your claim.
1. Define a configurator function for each managed resource kind your claim may dynamically provision.
1. Instantiate claim binding, scheduling, and defaulting controllers for each managed resource kind your claim may bind to.

The vast majority of this code is boilerplate, but there is quite a lot of it.

**Comment by displague** [comment]
There are some other gaps to fill before Stacks can provide Class and Claim types that are not already known to Crossplane:
* the Stack Manager will not give the controller deployment rights to watch the namespaced class/claim CRD across namespaces (https://github.com/crossplaneio/crossplane/blob/v0.8.0-rc/pkg/controller/stacks/stack/stack.go#L419-L427)
* Namespace personas (`crossplane:ns:foo:admin`) will not receive rights to create these claim types unless stack-manager produces clusterroles that aggregate into the namespaced persona defaults (https://github.com/crossplaneio/crossplane/blob/v0.8.0-rc/cluster/charts/crossplane-types/templates/namespace-personas-clusterroles.yaml#L1-L125)
* ^ same for environment personas https://github.com/crossplaneio/crossplane/blob/v0.8.0-rc/cluster/charts/crossplane-types/templates/environment-personas-clusterroles.yaml#L19-L178

**Comment by displague** [comment]
It may also be useful to UI tools and the Stack Managers RBAC generation and persona aggregation to know the difference between owned resources, claim/class resources, and other dependent resources. https://github.com/crossplaneio/crossplane/issues/1028 is tracking that line of thinking.

**Comment by displague** [comment]
A `stack-core` would need the ability to create claim and class types, the existing Crossplane types. 
 This issue blocks https://github.com/crossplaneio/crossplane/issues/1154.
