### ISSUE TITLE
PackageInstall should expose Job backoffLimit and activeDeadlineSeconds options

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1116]
### What problem are you facing?
A StackInstall can enter a state where it will never succeed because the pod image is invalid or the pod can't be created for other reasons.  In this case the Job should fail which should cause the StackInstall to fail.

The current behavior leads to a StackInstall resources that remains in a `Ready: false`, `Synced: True` status that will never be overcome.

### How could Crossplane help solve your problem?

StackInstall (and ClusterInstall) resources should expose the `backoffLimit` and the `activeDeadlineSeconds` features of the `Job.` For `backoffLimit` to take effect, the Job will also need a `restartPolicy: OnFailure` rather than the current value (`Never`).

**Comment by negz** [comment]
We no longer have a Stack^HPackageInstall type, or use jobs in our package machinery. :)
