### ISSUE TITLE
Proposing update to SVG file type processing

### ISSUE THREAD

**Issue by rathpc** [crossplane/crossplane#1120]
### What problem are you facing?
Currently SVG images/icons are processed the same way as other(binary) images types and
converted into a base64 string.

There is nothing specifically wrong with this, but in almost every case a base64 version of an
SVG image will always result in a large file size. This does not seem very efficient and
fortunately due to the way a frontend can handle URIs along with an SVG being XML based, we 
can return this in almost a _raw_ fashion.

I am proposing that we specifically process SVG files in a different manner than other image
types.

**Assuming https://github.com/crossplaneio/crossplane/issues/1119 is approved and
implemented:**
We would currently expect an svg icon to be returned the following way:

```yaml
icon: data:image/svg;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLz4KBIWXMA
```

However by doing so, the file size is actually increased. There are multiple articles and
references on the web to back this up (https://css-tricks.com/probably-dont-base64-svg/,
https://codepen.io/tigt/post/optimizing-svgs-in-data-uris)

So ideally what we would want to return is something along the lines of this:

```yaml
icon: data:image/svg+xml,%3csvg xmlns='...
```

We are omitting `;base64` and passing in a string that has had some characters uri-encoded.
While we can absolutely uri-encode the entire contents of the SVG image, we don't need to
and can therefor save even more bytes in the process.

Here is a list of what needs to happen to the svg
(referenced from https://github.com/tigt/mini-svg-data-uri):

1. Optimize the svg with a tool like https://github.com/svg/svgo
2. Strip the Byte-Order Mark if the SVG has one (`0xfeff`)
3. Collapse any extra whitespace down to single spaces and trim
4. Replace certain hex color values with their text names (certain colors have text string names
that end up being shorter than their hex color code value, this list can be seen here:
https://github.com/tigt/mini-svg-data-uri/blob/master/shorter-css-color-names.js)
5. Replace all double quotes`"` with single quotes `'`
6. Process with URI encoding
7. Replace the following explicitly:
  a. `%20` -> ` ` _(space)_
  b. `%3D` -> `=`
  c. `%3A` => `:`
  d. `%2F` -> `/`
8. Convert the whole string to lower case
9. Return the processed string (PROCESSED_STRING) as
`data:image/svg+xml,PROCESSED_STRING`

The following library performs all of these tasks exactly as described here so it might be
worthwhile to port this over to GO for this usage if it hasn't been already:
https://github.com/tigt/mini-svg-data-uri

**Comment by suskin** [comment]
@rathpc is this something that would need to be changed on the parsing side, or just on the generating side? In general I support improving the representation of data.

To make it a little clearer what the gain would be, could you give us sample numbers for "a very large file" and the reduced size? Or some samples of a typical size reduction percentage? This will help with prioritizing. From skimming the articles it looks like it has **some** numbers, but ideally this ticket would have numbers for us, and the articles would be for reading more about the background and technical details.

**Comment by rathpc** [comment]
@suskin this would be a change purely for the generating side. The resulting string will be consumed exactly the same way as a binary image that was converted to base64.

this is an example provided from the tool I mentioned that we port using an svg that engineer was testing with.

| Compression | Base64    | `mini-svg-data-uri` |
|-------------|----------:|-----------------:|
| None        | 96.459 kB | 76.583 kB           |
| `gzip -9`   | 17.902 kB | 12.974 kB           |
| `brotli -Z` | 15.797 kB | 10.976 kB           |

It unfortunately does not show the original raw SVG file size but this still gets the point I am trying to make across
