### ISSUE TITLE
KubernetesApplicationResourceSpec type should support TemplateURL

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1125]
### What problem are you facing?

In scenarios where a `KubernetesApplication` is installing several objects (e.g. CRDs, configmaps, secrets, etc.), specifying these resources in `KubernetesApplicationResourceSpec.Template` could become too lengthy, and erroneous.

### How could Crossplane help solve your problem?

One possible way to alleviate this issue would be to add an additional field to `KubernetesApplicationResourceSpec` called `TemplateURL`. This field points to a url which presents the template in a textual format (json, yaml, etc.), which it gets downloaded and populate the existing `Template` field. This especially is useful for installing a set of CRDs in a remote cluster.

**Comment by negz** [comment]
We're planning to remove support for KubernetesApplication, so I think we can close this.
