### ISSUE TITLE
API Reference: Links to spec headers don't work

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1127]
### What happened?

In the API Reference, I was looking at the [section for stacks](https://crossplane.io/docs/master/api/crossplaneio/crossplane/stacks-crossplane-io-v1alpha1.html). I clicked on one of the links to a Spec object, but it didn't do anything. It appears that the links in the API Reference use `#CamelCase` for the headers, but the document is using `#lowercase` instead, so the existing links don't move the page cursor.

### How can we reproduce it?

1. Go to any API Reference page, such as [this stacks one](https://crossplane.io/docs/master/api/crossplaneio/crossplane/stacks-crossplane-io-v1alpha1.html). 
2. Click on a link to a Spec object.

### What environment did it happen in?

Crossplane version: `master`
Browser: Chrome

**Comment by suskin** [comment]
Assigning to @negz for triage so that it isn't unassigned.

**Comment by negz** [comment]
Will probably need a fix somewhere in https://github.com/negz/crossdocs.

**Comment by negz** [comment]
This will be fixed when we remove these API docs in favor of @hasheddan's new tool; https://github.com/crossplane/crossplane/issues/1295

**Comment by negz** [comment]
Per my previous comment, we moved these to doc.crds.dev which does not have this issue.
