### ISSUE TITLE
Add support for Kubernetes 'Kind' for testing 

### ISSUE THREAD

**Issue by lukeweber** [crossplane/crossplane#1148]
### What problem are you facing?

To support e2e testing scenarios, it would be great if Crossplane supported claiming and provisioning a local Kubernetes Cluster type

### How could Crossplane help solve your problem?

I would like a [Kind](https://github.com/kubernetes-sigs/kind)(Kubernetes in Docker) cluster as a supported Kubernetes Cluster in Crossplane, but I'm not sure about the feasibility of a Kind Operator. There does seem to be some discussion here https://github.com/kubernetes-sigs/kind/issues/303 about how to run kind in a pod so it's seems like it's worth further exploration.

**Comment by hasheddan** [comment]
@lukeweber this could be accomplished by using a `KubernetesTarget` and a kubeconfig secret to connect to Kind. This should be supported relatively soon with #1146. Do you think this will work for your use case?

**Comment by lukeweber** [comment]
We are actively using Crossplane to provision target clusters to host our content via the class/claim pattern, so I don't believe it would. I'm looking to make a claim against a KubernetesCluster of type `Kind` for local testing.

**Comment by displague** [comment]
This thinking and capability could potentially extend to `microk8s` (https://github.com/ubuntu/microk8s/issues/825#issuecomment-559159799), which provides a less vanilla experience.

There are probably more obstacles with MicroK8s.  A reliance on Snap/Multipass (if that truly is a dependency) would make this more difficult than a `kind` provisioner.

**Comment by muvaf** [comment]
We can have a stack like `stack-local` that includes types for `minikube`, `kind` and others. I think of three different ways:
* There could be an HTTP server in your local computer that managed resource controller talks to (usual cloud provider pattern) and that server could run the necessary commands in your computer, though this comes with a few caveats like you should expose its IP to your Crossplane cluster etc.
* You can have a k8s operator that managed controller talks to and creates the clusters in the cluster, which is something that those tools may not support but is the most secure way IMO.
* You can give direct SSH access to the managed resource controller and it'd run the commands on your local computer. Or have another operator as middleman(like rook) with SSH access that managed controller could talk to for provisioning.

The easiest is probably to implement managed controller with SSH access that runs commands in your computer. The most secure one would be to make sure these tools support k8s-in-k8s and write a managed controller that creates necessary deployment/statefulsets for them.

**Comment by negz** [comment]
I thiiink what this issue is going for is kind of a 'dummy' resource that can be used to test Crossplane, right? If so we've built https://github.com/crossplane-contrib/provider-nop for that.
