### ISSUE TITLE
Reduce the number of RBAC roles created when a stack is installed into multiple namespaces

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1151]
### What problem are you facing?

Part of #1036 

Multiple instances of a Stack should be able to reuse Cluster Scoped resources (CRD and ClusterRoles) that were installed.  Because Stacks are named after their StackInstall their names are arbitrary within a namespace or cluster.  It is therefore not easy (or possible) to share these resources without an identifier that is unique to a particular Stack.

### How could Crossplane help solve your problem?

Stacks need a unique identifier (app.yaml: id)

Stacks should have a unique identifier so that their sameness can be identified by the Stack Manager. 

This identifier could be derived from the Stack image, if possible, but could also be provided by an `app.yaml` `id` field.

How are names verified? What concerns are there in having entirely unrelated stack images use the same `app.yaml` `id`?

**Comment by displague** [comment]
With respect to https://github.com/crossplaneio/crossplane/issues/1089, for the Stack Manager Reconcile a Stack, fetching its and extracting the Stack Image and configuring the Deployment, a Stack would need some way to identify its source.  Currently, the source is provided by the StackInstall, where a package source is defined.  The package source is optional, however, because installation of a Stack based on CRD-lookup is also possible.  A Stack may have no way to identify where it came from, which is a necessary component of its reconciliation (if StackInstalls and Stacks merge).

The Stack identifier could be based on the source and package rather than an id embedded in app.yaml.  Does this make it a suitable replacement?

A single Stack could potentially be identified by various source and package combinations, while ultimately providing the same image (by hash), with the same set of CRDs and controller.  Even with a Stack source/package property, there is still a benefit for an app.yaml id.

**Comment by negz** [comment]
I believe this won't be relevant once we remove the concept of a namespaced stack.
