### ISSUE TITLE
One-pager for pluggable webhooks

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1152]
### What problem are you facing?

In Crossplane, we need validating and mutating webhooks in several places. But the certificate handling and the structure of webhooks have made it hard to get something working and extensible quickly. A one-pager that introduces a mechanism (possibly in crossplane-runtime) for developers to add their webhooks just like adding a new controller would help a lot.

The key point is the stack developers should be able to register their webhooks as easy as registration of a new controller. 

### How could Crossplane help solve your problem?

The first candidate use-cases that come to my mind:

Validating webhook:
* Reject modifications to fields marked `// +immutable`
* Validate objects in `spec.templates` array against their `kind`

Mutating webhook:
* All scheduling controllers could be mutating webhooks
  * defaulting resource class controller
  * generic resource class selector
  * KubernetesApplication scheduler

Related issues:
* https://github.com/crossplaneio/crossplane/issues/169 
* https://github.com/crossplaneio/crossplane/issues/950
* https://github.com/crossplaneio/crossplane/issues/967
* https://github.com/crossplaneio/crossplane/issues/727
* https://github.com/crossplaneio/crossplane/issues/427
* https://github.com/crossplane/crossplane/issues/1476
* https://github.com/crossplane/crossplane/issues/1497
* https://github.com/crossplane/crossplane/issues/1584

**Comment by muvaf** [comment]
Assigning to myself just to not lose track of the issue. There isn't a plan to implement this yet.

**Comment by displague** [comment]
I am also finding that this will be necessary to offer conversion webhooks to support Stack versioning. 

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#webhook-conversion

The stack-manager will need to manage the deployment of the webhook service and app.yaml will need ways to express this.

**Comment by displague** [comment]
A conversion webhook would resolve https://github.com/crossplaneio/crossplane/issues/533

**Comment by negz** [comment]
It seems like it's increasingly common for controller managers to include built in support for managing their own webhook certs - e.g. https://github.com/open-policy-agent/cert-controller.
