### ISSUE TITLE
Explicitly configure the "environment" namespace on crossplane install

### ISSUE THREAD

**Issue by lukeweber** [crossplane/crossplane#1153]
Following conceptual work in [security-isolation-design](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md) we have the concept of an infra owner who would work on globally scoped Crossplane CRDs/stacks that have been installed for the environment scope. 

Nominally we also have crossplane-system namespace as a default to install the stack-manager and potentially other system level components, that I would consider the domain of a cluster-admin, with more elevated permissions than just the environment admin, i.e can upgrade Crossplane, or modify the controller.

I propose the install of Crossplane Core (stack-manager) can configure and create its environment namespace(default=`crossplane-environment`) that would be the default location for secrets and other namespace scoped objects that are consumed by the cluster scoped objects like Provider. Crossplane install would RoleBind environment-{admin,edit,view} to the this namespace environment namespace as part of install to grant environment users access to the related namespace objects.

//cc @prasek @displague @negz

**Comment by displague** [comment]
> the default location for secrets and other namespace scoped objects that are consumed by the cluster scoped objects like Provider

As far as I know, there is no concept in Crossplane or any of the Stacks. The namespace for secrets must always be provided explicitly.  In a user setting, I imagine users would fashion their own namespaces to hold these resources.  The admin user could  then create a `stacks:ns:crossplane-environment:admin` `RoleBinding` for any users deemed worthy.  Does this differ from the roles you are considering?

I worry that a `crossplane-environment` namespace may go unused, adding installation clutter. What would our `helm delete` policy be on this namespace? I imagine we would leave it behind, creating clutter.  I could see us adding a `crossplane-masters` group `RoleBinding` into this namespace, so it wouldn't be completely empty.


Official documentation could suggest using the `crossplane-environment` namespace and suggest that it be deleted manually, but this seems like extra work for something that is highly opinionated and could be left to the user.

**Comment by lukeweber** [comment]
So environment admin will be able to modify the deployment of stack-installer, and since it can read the secret to this privileged component because it will have read/write on crossplane system, I assume It could escalate itself to cluster admin by reading the pod secret and get access to everything.

By separating the privileged running of crossplane logically from the environment scoped stacks and their resources you have a cleaner permission model that doesn’t exist if we put everything in crossplane system. If we don’t decide on supporting this separation then upbound as a consumer can manually plumb this concept as well, just seems incomplete currently.

**Comment by lukeweber** [comment]
Maybe the minimum bar is to be able to configure which namespace the environment persona manages and gets an RBAC role binding to. In a more secure config someone would configure a distinct namespace from the one where stack-manager is installed.

**Comment by prasek** [comment]
//cc @jbw976

**Comment by displague** [comment]
I now understand that we want to make sure that users do not use the `crossplane-system` namespace with the roles that we have provided.  Applying the edit or admin namespace persona rolebindings in this namespace will escalate privileges.

Offering a `crossplane-environment` namespace and binding is a way to sheperd users away from from `crossplane-system`.

I still think we have a choice to present this as forthright documentation with opinionated examples or installation artifacts, which may be hard to clean up properly.  I'm personally leaning towards documentation, at least to start. (TODO: create and link GH issue)

We could include the `crossplane-environment` namespace in installs later if the practices we prescribe becomes common.  By then we should understand what if any obstacles prevent a clean uninstall.

**Comment by negz** [comment]
I can see why it would make sense to separate `crossplane-system` (control plane infrastructure) from `crossplane-environment` (which I think would currently only contain secrets for providers and cluster scoped managed resources). I also strongly agree with @displague that we should not encode the existence of such a namespace at the Crossplane level, but rather suggest it as convention. Today there is no default here - every provider, managed resource, and resource class you author asks you what namespace should be used to store its secret.

**Comment by lukeweber** [comment]
Fine with not encoding this into Crossplane per se. Raised mainly as a privilege escalation issue and the need to separate in documentation probably on a move forward. I think adding a namespace that the helm chart conditionally installs with a default of `crossplane-environment`, and a environment RoleBinding for that particular namespace and adding to documentation would suffice.
