### ISSUE TITLE
Create a Stack for Crossplane core types and Workload controller

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1154]
### What problem are you facing?

This [crossplaneio/crossplane](https://github.com/crossplaneio/crossplane) repository currently serves a few different roles:
- provide the stack-manager controller executable (which watches Stack / StackInstall / ClusterStackInstall resources)
  - provide the executable which unpacks stack packages and outputs Kubernetes yaml
- provide the crossplane Workload controller which watches KubernetesApplication / KubernetesResource / KubernetesCluster resources, consuming Provider and Target resources
- provide CRDs for Crossplane Claim (RDSInstance) and Class (RDSInstanceClass) types 
- provide the base documentation and the generated stack documentation for crossplane.io

The diversity of these responsibilities is not being put under scrutiny here, but the overlap in Stack functionality is.

A Stack:
* contains CRDs for owned types, including both claim and class types
* contains a controller for owned/watched types
* includes metadata which informs Crossplane related tools about the resources provided by a Stack
* can take advantage of the `kubectl crossplane stack` build tools
* can be independently versioned and released

The Workload controller included in this crossplane repository does not get the benefits today that would come from being an independent Stack.

The core claim and class types do not get the benefit of stack build tools and UI metadata (#979).

The Workload controller, while beneficial, may not be needed in some settings.  If Crossplane is only being used to manage database and storage resources, or other managed resources, including KubernetesCluster resources, this controller may be unused adding unneeded overhead.

### How could Crossplane help solve your problem?

One possible solution would be to extract the Workload controller into its own stack repository.
Another would be to change the way this controller is built and installed to be more Stack-like.

Should the other core types be included in this extraction? I originally thought so, but it is less clear because doing this may conflict with https://github.com/crossplaneio/crossplane/issues/1085, so an independent crossplaneio/crossplane-types repository may be more suited for the claim and class types that Crossplane does not provide a controller for.  However, a crossplane-types repo would not be able to take advantage of the stack build tools since there is no stack image to be built.

The stack repository could be stack-workload or perhaps stack-core (stack-crossplane-core) which would make more sense as it would contain all of the core claim and class types and provide a shared controller for all future Crossplane core types.  I believe a stack-core could rely on crossplane-types, which could keep #1085 clean and provide the Stack metadata benefits.

Follow-up actions to this would include:
* gearing up the stack repository for CI/CD
* updating the documentation generation system to inspect this new stack as it does stack-gcp and others
* updating helm to include this stack, enabled by default

/cc @negz @lukeweber @hasheddan @turkenh

**Comment by displague** [comment]
If this is enacted, crossplane/crossplane is left with code that only operates the Stack Manager.

This has me wondering if it becomes useful to move stack-manager to its own repository, leaving crossplane/crossplane as the home of the helm charts, e2e tests, and docs (without citing particular projects, I would offer that this is not unheard of).

**Comment by displague** [comment]
Another  response to https://github.com/crossplaneio/crossplane/issues/1154#issuecomment-572165710 would be to keep the crossplane types in crossplane/crossplane and move the stack-workload and stack-manager related code out (crossplane/stacks? crossplane/stack-manager?).

A response to this issue that would take less code movement, would be to:
* reorganize core types and the workload controller into a layout that aligns with the crossplane-cli stack building tools.
* add stack metadata to this filetree
* update installation instructions (and helm) to include a `kubectl stack install -n crossplane-system --cluster crossplane/crossplane` step

**Comment by negz** [comment]
We should consider the proposed OAM architecture as part of this issue - https://docs.google.com/document/d/11AYNGhvry_B3l_tO3Yyv1f9tDoezZOpGIYV56oZwb5s/edit#heading=h.x458enhyy1sq

**Comment by negz** [comment]
We should also consider https://github.com/crossplane/crossplane/pull/1163. When that design (or something like it) lands:

* The core "resource claim" types will likely go away.
* The controllers that handle Crossplane infrastructure and application composition will need to live somewhere.

**Comment by negz** [comment]
Per my previous comment, I don't think we'll need to do this given that we're removing the core types. We're also planning to break all things OAM out into its own repo.
