### ISSUE TITLE
CRDs in Helm Chart Contain Status

### ISSUE THREAD

**Issue by srueg** [crossplane/crossplane#1157]
### What happened?
We use a GitOps approach to deploy Crossplane: We render the Helm chart and commit the rendered manifests to git. From there it will be applied by ArgoCD on the cluster.
Since the CRDs in the chart contain the `status` field, ArgoCD always sees changes from the version currently applied in the cluster and the version the GitOps repo (rendered Helm chart).

### How can we reproduce it?
The rendered Helm chart includes the CRDs with the `status` filed set.

### What environment did it happen in?
Crossplane version: v0.6.0

### Suggested Solution

Remove the `status` field from all CRDs in the Helm chart. I tried to come up with a PR myself, but I'm not sure if the CRDs in the Helm chart are somehow copied there or if I can just modify them?

**Comment by hasheddan** [comment]
@srueg thanks for opening this! This the empty `status` fields are actually a product of the generation from `controller-tools`. I noticed a comment regarding this situation [here](https://github.com/kubernetes-sigs/controller-tools/blob/0dd9d80ad4b98900d6066141dd4233354b25e3f3/pkg/crd/spec.go#L154) indicating that these fields must be explicitly be set to their zero-values due to missing `omitempty` tags, but I am not sure it is still accurate. I will investigate and see if I can drive a fix upstream.

**Comment by srueg** [comment]
Thanks for looking into it :+1: 
In the meantime I found a workaround by [ignoring the status field of CRDs in ArgoCD](https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration).

**Comment by srueg** [comment]
I also observed a similar issue with the `.spec.scope` field of the CRDs: The manifests in the Helm chart specify `scope: ''` (empty string) while once applied to the cluster it gets defaulted to `scope: Namespaced`.

**Comment by srueg** [comment]
For anyone coming across this. The workaround looks like this (in the `argo-cm` ConfigMap):
```
data:
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
          - /status
          - /spec/scope
```

**Comment by displague** [comment]
> The manifests in the Helm chart specify scope: '' (empty string) while once applied to the cluster it gets defaulted to scope: Namespaced.

This appears to be corrected in 6e0954d992492dd2836d06e3b2d0395b60071567 which should be included in the next (0.7.0) release.

**Comment by hasheddan** [comment]
@srueg just a quick update here. We have merged an upstream change that should trickle down to controller-tools and make it such that Status fields are not required when applying manifests. We’ll continue to keep you posted here! https://github.com/kubernetes/kubernetes/pull/87213

**Comment by srueg** [comment]
Great to hear and thanks for the effort! :+1:
