### ISSUE TITLE
Check that API Docs have been updated in Jenkins PR pipelines

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1166]
### What problem are you facing?

We have an encountered a few recent situations where API docs have not been regenerated when a new type has been added or an existing one has been updated.

### How could Crossplane help solve your problem?

We should check that generating API docs does not cause a dirty branch in our Jenkins PR pipelines when we run `check-diff`.

**Comment by negz** [comment]
We removed our hacky API doc generator in favour of doc.crds.dev.
