### ISSUE TITLE
template stacks experience: long-term contract, first phase

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1173]
### What problem are you facing?

We want to have the template stacks experience evolve over time while also having a solid plan for what the First Edition of it will do and look like.

This is a continuation of a discussion around [a gist](https://gist.github.com/suskin/a188b0eec7a62b96ef96054fb06f9eba); the discussion was happening on the gist and over email. I want to move it into an issue so it's easier for others to follow along.

### How could Crossplane help solve your problem?

Here's a [gist where the experience is being sketched and discussed](https://gist.github.com/suskin/a188b0eec7a62b96ef96054fb06f9eba).

The result of this issue is that the discussion will be settled down and there'll be a plan. Once we have a plan, there'll be more work to convert any existing template stacks to use the new contract.

### Related links

This is related to a separate [discussion about how to incorporate the kustomize engine](https://github.com/suskin/stack-template-engine/pull/4) into the template stacks experience; that discussion explores options for configuring the transformation of values from a CR to a rendered kustomization.

**Comment by suskin** [comment]
There were some additional discussions about supporting a single CRD per template stack, and I think I'm convinced now that going with that simplifies the concepts and experience. I've updated the gist to reflect this.

**Comment by negz** [comment]
We're planning to deprecate support for template stacks, so I think we can close this.
