### ISSUE TITLE
template stack controller: hardening

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1175]
### What problem are you facing?

As part of creating the template stack controller, we've integrated an early version of the controller with the stack manager. However, we'd like to have the controller be more robust and hardened before we consider it ready for general consumption. Currently, a user must explicitly enable it by hand if they want to use it.

### How could Crossplane help solve your problem?

I'm going to start by dropping a bunch of miscellaneous items in here, and then we can reorganize them or split them out in the future.

* [ ] I was noticing these in the logs recently when integration testing locally:
```
E0115 17:42:53.166691   54613 reflector.go:123] github.com/crossplaneio/crossplane/.work/pkg/pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```
* [ ] During integration testing I was noticing that the stack configuration doesn't always go away when the test is cleaned up. If this is because of something like an owner reference not being set, the owner reference should be set.
* [ ] Address all TODOs in the code by fixing them or turning them into issues to track the work

**Comment by muvaf** [comment]
@suskin The items listed here do not seem to be existing anymore. Could you take a second look and update the list or close the issue?

**Comment by jbw976** [comment]
@muvaf is that true for the TODO item even?

> Address all TODOs in the code by fixing them or turning them into issues to track the work

We don't have to fix them all, but doing a quick audit on them and opening up official issues to track the more scary ones would be great

**Comment by muvaf** [comment]
@jbw976 I've gone through them now. They are mostly exploration notes like `think about how we could do this better` rather than `blow this up after the first iteration`. @suskin might have some other things in mind though.

**Comment by muvaf** [comment]
Closing this for now. Feel free to reopen if you have some action items in mind.
