### ISSUE TITLE
template stacks: add integration testing

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1176]
### What problem are you facing?

As part of developing template stacks, we'll want to have automated integration testing set up. Testing should be happening as part of all of the work that we're doing, but I'm opening a separate ticket to track the initial set up because the research and initial spin-up work could take longer than the incremental improvements to the tests.

### How could Crossplane help solve your problem?

There's already a manual integration test, but we'll want it to be as automated as possible. This could mean using one of the existing end-to-end testing harnesses that we have in the repo. It could also involve using the kudo test framework.

Other suggested lines of research:

* [Test API Servers](https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/FAQ.md#q-how-should-i-write-tests--any-suggestions-for-getting-started) (controller-runtime)
* [Test clusters](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md) (sig-testing)

**Comment by negz** [comment]
We're planning to remove template stacks in favour of composition, so I think we can close this.
