### ISSUE TITLE
template stacks: migration from app.yaml to stack.yaml

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1178]
### What problem are you facing?

As part of the template stacks work, we want to migrate the app.yaml to a file named stack.yaml. The stack.yaml lives at the root of the stack resource folder. Or, for stacks which are just git repositories, it lives at the root of the repository.

### How could Crossplane help solve your problem?

We'll want to migrate this in a backwards-compatible way, so the phases will be something like this:

* Support both app.yaml and stack.yaml in the stack manager, but change all of tooling to generate stack.yaml, and change all of the documentation to talk about stack.yaml instead of app.yaml
* Change all of our stacks to use stack.yaml instead of app.yaml, and to build them into the right location in the stack
* Notify all of the stack owners that we know of that the migration is occurring
* Eventually, stop supporting app.yaml

**Comment by negz** [comment]
I don't believe this is relevant anymore, given we plan to remove support for template stacks.
