### ISSUE TITLE
template stack controller hardening: helper images

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1183]
### What problem are you facing?

Now that we have a first version of the template stack controller, we want to make it more robust so it can be consumed by more people. This ticket covers improvements to the helper images for the resource engines.

### How could Crossplane help solve your problem?

I'm gong to list several improvements.

* [ ] Improve management of image id tags in a way that works well for local testing and in production. `:latest` with no image pull policy sets the pull policy to `Always`, which isn't good for local development
* [ ] Use directories other than `/usr/share` as the helm2 engine working directories
* [ ] Helper image sizes are optimized (we may move this into a separate issue). For example, by using alpine instead of ubuntu.
* [ ] Parameterize helper images where used, as suggested [in this comment](https://github.com/crossplaneio/crossplane/pull/1131#discussion_r365272573)

**Comment by negz** [comment]
I believe we're planning to remove the template stack controller in favour of composition.
