### ISSUE TITLE
template stacks: expose status of rendered resources

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1201]
### What problem are you facing?

As a user creating a CR which is handled by a template stack, I want to be able to easily check the status of the resources I'm expecting to see in my cluster as a result.

### How could Crossplane help solve your problem?

To solve this, we'll need:

* A representation of the status of the child resources
* A place to expose the status

Options for the representation of the status of the child resources include:

* Whether or not all of the child resources have been created (e.g. the output of the job which is responsible for creating them, if it's a job)
* The statuses of all of the child resources

It seems like a natural place to expose the status would be in the `status` field of the CR.

**Comment by negz** [comment]
We're planning to deprecate and remove support for template stacks. This sounds like something we want for composition, but I'd like to track that in a distinct issue.
