### ISSUE TITLE
template stacks: add or ensure error reporting

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1203]
### What problem are you facing?

Now that we're hardening the template stack controller, we want to make sure all of its errors are reported properly so they can be observed and debugged.

### How could Crossplane help solve your problem?

Make sure we're reporting all actionable errors in the template stack controller. See [our document about this](https://github.com/crossplane/crossplane/blob/master/docs/observability-developer-guide.md) for recommendations on how to think about this.

**Comment by prasek** [comment]
@muvaf do you have this in flight?

**Comment by muvaf** [comment]
yes, it's been waiting for review https://github.com/crossplane/templating-controller/pull/10

**Comment by suskin** [comment]
Sorry about the delay on the review; that's my fault. I got sidetracked last week
