### ISSUE TITLE
template stacks: failure isolation from stack manager

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1204]
### What problem are you facing?

Now that we have a template stack controller running inside the stack manager, as part of hardening that we want to make sure that its failures don't crash the stack manager, where possible.

### How could Crossplane help solve your problem?

This most likely just involves properly handling errors that occur, so that they don't crash the whole process. (Especially initialization errors.)

**Comment by muvaf** [comment]
@suskin do you have specifics regarding this issue? I think we're handling errors wherever possible, so it should be isolated as much as other controllers.

**Comment by jbw976** [comment]
I agree @muvaf, I think our error handling isolation is OK with the final design we implemented.
