### ISSUE TITLE
pull requests: consider decentralized approval, document expectations

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1205]
### What problem are you facing?

This issue combines a few different ideas that have come up in recent retrospectives, around how to help pull requests flow through the software development apparatus more effectively.

### How could Crossplane help solve your problem?

There are two related but different ideas:

* Use a pull request review model which is closer to what Rook uses. The gist of it is that the maintainers with merge permissions don't necessarily need to do an in-depth line by line review if a Known Qualified Reviewer who does not have merge permissions has already done that. This helps us get more people involved in shepherding pull requests into a mergeable state so that we aren't unnecessarily creating a bottleneck.
* Create a document which explains development team expectations, such as turnaround time for pull requests. This helps us to set expectations and uphold our standards more effectively.

**Comment by negz** [comment]
I believe we've now added a few more maintainers under our new governance model, which has helped to decentralize approval.

**Comment by jbw976** [comment]
The expectations for maintainers are captured in https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#maintainers for further reading :)
