### ISSUE TITLE
API Reference docs have broken header links on crossplane.io

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1223]
The auto-generated links to section headers in the API Reference docs use capitalization, which breaks when the markdown is converted to HTML. For instance, https://crossplane.io/docs/v0.7/api/crossplaneio/stack-gcp/database-gcp-crossplane-io-v1beta1.html#cloudsqlinstancespec works but https://crossplane.io/docs/v0.7/api/crossplaneio/stack-gcp/database-gcp-crossplane-io-v1beta1.html#CloudSQLInstanceSpec does not. We should either correct how the mardown translation happens in https://github.com/crossplaneio/crossplaneio.github.io or generate lowercase markdown links in https://github.com/negz/crossdocs

**Comment by muvaf** [comment]
It's also really hard to browse even if the links worked. I wonder if we can have something like https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

**Comment by hasheddan** [comment]
We no longer use generated docs so I am going to go ahead and close this :+1:
