### ISSUE TITLE
Many-to-one relationship between claim and managed resource

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1229]
### What problem are you facing?

As an app stack, Wordpress instance needs a Kubernetes cluster. Until now, that declaration was done via claims, i.e. Wordpress controller would create a `KubernetesCluster` resource and wouldn't care where it is bound to. The infra operator is expected to create a class to satisfy that claim or have a managed resource waiting to be bound to that claim. This is the case in PVC and PV model, too. However, volumes are exclusive, in the sense that only one entity like `Deployment` or `StatefulSet` uses it. But kubernetes clusters are not, neither other claim types. More than one user can easily share the same Kubernetes cluster to deploy their own workloads to different namespaces.

This brought the case where for each app that requires a kubernetes cluster, Crossplane would provision a _new_ one. For kubernetes clusters specifically, Crossplane invented `KubernetesTarget` that would give you the possibility to bind to the same kubernetes cluster in the same or other namespaces. So, today, if an app says that it needs a kubernetes cluster, it will have two choices: create `KubernetesCluster` if it wants a fresh new one or `KubernetesTarget` if you are OK with using an existing one.

I think there are a few things that this model does not satisfy:
* As an app developer whose app requires only namespace scoped resources, I don't care whether the cluster is new or not. I only want a namespace in a cluster. But I have to make a decision about this during my development.
* There are many other claim types that are not exclusive as volumes. For example, `MySQLInstance`. The case where having a big DB instance cluster with different tables for different applications is not uncommon. But I don't think we'd want to introduce `MySQLInstanceTarget` type (and possibly `*Target` for other claims).

### How could Crossplane help solve your problem?

I think it should be possible to bind more than one `KubernetesCluster` to one managed kubernetes resource. Let's say I'm Wordpress stack developer who don't care whether the cluster is new or not. I only need a namespace. I can include a `KubernetesCluster` in my stack and not worry about whether it's new or not. Infra operator could mark some `GKECluster`s as shared ones and some not, maybe a scheduling could happen there. And this could go for other claims, too.

As next step, claims could expose more options. For example, `KubernetesCluster.spec.scope` could let developer to decide whether he only needs a `namespace` to work in. Or they can declare a set of RBACs. For `MySQLInstance`, it could be like give me `I want a MySQLInstance table with these properties`. Also, they can possibly specify whether the resource should be exclusive to them, like they could say `I am running a sensitive workload, give me a fresh new cluster that I do not share with anyone` through annotations.

There is an ongoing effort to enable binding more than one managed resource to one claim, which aims to help infra-operators. But this issue is completely different and aims to help app developers.

**Comment by negz** [comment]
It sounds like this is not the same as https://github.com/crossplaneio/crossplane/issues/1105, right? That issue tracks one claim to many managed resources. This issue seems to track one managed resource potentially satisfying many claims.

**Comment by jbw976** [comment]
Just to be clear, PersistentVolumes in upstream k8s are not exclusive to just one consumer, e.g. through the `ReadWriteMany` access mode.  We could consider a model similar to that for when we want many claims to all bind to a single underlying resource.

More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by negz** [comment]
> PersistentVolumes in upstream k8s

This models how pods consume PVCs though, right? i.e. There's one-to-one PVC-to-PV relationship, but if the PV is `ReadWriteMany` then a many-to-one pod-to-PVC relationship is allowed.

**Comment by jbw976** [comment]
Yes, good distinction to call out here @negz, thank you!

**Comment by jbw976** [comment]
Also, this looks related to https://github.com/crossplaneio/stack-gcp/issues/157

**Comment by muvaf** [comment]
> if the PV is ReadWriteMany then a many-to-one pod-to-PVC relationship is allowed.

In pod<>pvc<>pv consumption model, `ReadWriteMany` allows N<>1<>1 relationship while what I was investigating is more like N<>N<>1 where you have more than one claim to bind to one resource so that different apps only need to create a claim to say that it needs that kind of resource and not worry about other stuff. 

In pod consumption model, there is still one claim because in most of the cases, all consumers(pods) of that PVC are bundled together with the claim in the app bundle(helm chart for example). The sharing happens in the app's different components and when it's deleted, the claim is deleted, too. However, what we'd like to achieve is a sharing model across apps, which may not make so much sense for volumes but it possibly does for other resources because we don't want to treat some of the managed resources as cattle.

The first candidate that needs this is Kubernetes cluster; it's pretty common use-case to use one big cluster for different apps and teams. But IMO, it's clear that we'll need the same thing for other resources, too. In the world that I promise here, claims are still the way of declaration of a need of the application. It's just this will be their only meaning by default and users can add additional responsibilities related to lifecycle, like `I work across namespaces so this has to be exclusive to me` or `i only need a namespace and that is all`. Today, the default is you get a new cluster all the time or you need to create `KubernetesTarget`. So, you are forced to make a decision you don't need to and this will possibly happen in other kinds of resources, too.

There could be a field as part of `ResourceSpec`(managed resource common spec) named `SharingPolicy` that will enable infra-op to configure that environment. Also, `ResourceClaimSpec` could have a field like `ExclusivityPolicy` or an annotation that will allow developer to say whether the app needs a full cluster or not.

**Comment by muvaf** [comment]
> Also, this looks related to crossplaneio/stack-gcp#157

@jbw976 I opened this issue because of https://github.com/crossplaneio/sample-stack-wordpress/issues/26 but yes, that issue can also be fixed by many-to-one claim-to-resource proposal.

**Comment by negz** [comment]
Why do we need to share infrastructure at the managed resource level instead of at the resource claim level? I strongly prefer sharing at the resource claim level (which I believe is how persistent volumes work), because:

* You're logically choosing to share the claim that represents the imagery database instance, not some anonymous SQL instance that happens to also be some other team's super sensitive billing database instance.
* You're limited to sharing infrastructure within namespace boundaries, which frequently means team or environment boundaries.

**Comment by muvaf** [comment]
> Why do we need to share infrastructure at the managed resource level instead of at the resource claim level? I strongly prefer sharing at the resource claim level (which I believe is how persistent volumes work)

In persistent volumes case, `ReadWriteMany` is used to share the volume between different pods of the **same** application. Developers are able to bundle a `ReadWriteMany` PVC resource and refer to that in `Deployment`, `StatefulSet` etc. This is the default in our case because you can just have one `KubernetesCluster` in your app bundle and use its secret name in many pods. So, all this is possible today. You could even argue that `ReadWriteMany` would make it possible to share the volume **between applications** but that's possible only by custom logic like `--set useThisPVC=namepvc` and this is leaking the concern of the infra to the developer of the stack. It's also understandable that k8s maintainers chose to limit the sharing only to pods of the same application this way because it may not make much sense to share a volume between different applications.

In our case, it does make sense for different people or applications to share the same cloud resource because unlike volumes, some cloud resources do have different lifecycles than applications. This is one of the reasons we have `KubernetesTarget` today so that different apps or people can use the same cluster. However, as app developer, I have to incorporate a logic in my deployment flow to decide whether I should deploy a `KubernetesCluster` or expect a `KubernetesTarget` to exist in place and allow the deployer to put a label selector to schedule to that `KubernetesTarget` in order to make my app to be used in such case. This works but: 
* Infra-op concern is leaked into development.
* Infra-op cannot enforce a policy around use of the shared cluster if the app itself has `KubernetesCluster` type.
* Not feasible to implement `*Target` for every resource we want to be shared.

If we allow the app developer to only need to bundle a `KubernetesCluster` in the app to declare that this app needs a Kubernetes cluster and it doesn't care whether it's a fresh new cluster or an existing one, it'd be easier for infra-op to make the right decisions about where to put that app in the infrastructure. If the app requires exclusivity, they can include this in `KubernetesCluster` as a policy.

> You're logically choosing to share the claim that represents the imagery database instance, not some anonymous SQL instance that happens to also be some other team's super sensitive billing database instance.

I'm not proposing that to be the default, though. It's about making it possible for infra-ops to put some rules in place to enable such use-cases. There could be some scheduling that prioritizes the managed resources that are already bound to claims in the same namespace or some other rules of scheduling policy defined by the infra op, like `this managed resource can be shared only in one namespace` or `this managed resource cannot be shared`.

> You're limited to sharing infrastructure within namespace boundaries, which frequently means team or environment boundaries.

This doesn't have to change. We can limit the sharing to the same namespace by hard-coding it or allow infra-op to decide via a policy.

**Comment by negz** [comment]
> ReadWriteMany is used to share the volume between different pods of the same application

> It's also understandable that k8s maintainers chose to limit the sharing only to pods of the same application this way because it may not make much sense to share a volume between different applications.

Is there any documentation around this limitation? I was under the impression that a PVC could be shared by arbitrary applications/pods, with the main restriction being that a PV can only ever be attached to a particular host.

**Comment by negz** [comment]
We're planning to remove claims, and I don't think this applies to requirements (which proxy the state and schema of exactly one composite resource).
