### ISSUE TITLE
Versioning and Jenkins pipelines for new repositories

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1235]
### What problem are you facing?

The following repositories need their images to be pushed to Dockerhub but the process is currently manual:
* https://github.com/crossplaneio/stack-minimal-aws
* https://github.com/crossplaneio/stack-minimal-gcp
* https://github.com/crossplaneio/stack-minimal-azure
* https://github.com/crossplaneio/templating-controller

### How could Crossplane help solve your problem?

Set up Jenkins pipelines and mainstream the versioning.

**Comment by suskin** [comment]
The sample wordpress repo is also in this category:

* https://github.com/crossplaneio/sample-stack-wordpress

**Comment by suskin** [comment]
This is now in review for wordpress and the minimal gcp stack. After we've merged the open PRs for those two repos, we may need to adjust things and improve them based on what we find when we actually use the pipelines.

**Comment by prasek** [comment]
@suskin is this ready to close?

**Comment by suskin** [comment]
> @suskin is this ready to close?

We ended up talking about this in sprint planning, but this is paused and waiting for some work on #1308 to resolve before we get back to it. We'll also want to add some jobs to templating-controller which are similar to the other jobs for other controllers before this is considered complete.

**Comment by muvaf** [comment]
The PR https://github.com/crossplane/templating-controller/pull/9 by @suskin in templating-controller is the final PR to close this issue.

**Comment by suskin** [comment]
I ended up closing the previous PR and replacing it with a new one - https://github.com/crossplane/templating-controller/pull/12
