### ISSUE TITLE
Allow annotations to be passed from ClusterStackInstall to stack deployment's ServiceAccount

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1242]
### What problem are you facing?

Some managed Kubernetes providers allow for authentication by associating IAM roles with Kubernetes `ServiceAccounts`. This is usually done by enabling the functionality in the Kubernetes cluster, then annotating the `ServiceAccount`. There are examples of how to do so on [AWS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) and [GCP](https://cloud.google.com/blog/products/containers-kubernetes/introducing-workload-identity-better-authentication-for-your-gke-applications).

Currently, when a stack is installed with Crossplane, it is given a `ServiceAccount` and bound to appropriate `ClusterRole`. If a user wanted to provide an annotation on the `ServiceAccount`, they would need to manually access the cluster, provide the annotation, then potentially restart the pod that the stack controller is running in.

### How could Crossplane help solve your problem?

While this functionality is enabled through the steps outlined above, it would be useful to be able to pass down an annotation from the `ClusterStackInstall` to `ServiceAccount` that Crossplane creates for the stack. In clusters where this functionality is enabled, the stacks would be able to automatically authenticate to the provider without any additional credentials being required.

Ref: https://github.com/crossplaneio/stack-aws/pull/126

**Comment by displague** [comment]
This is also related to https://github.com/crossplaneio/crossplane/issues/974.  I think what we need at this point is a design to surface the surge of interest in providing Stack deployment (controller and SA) augmentations via (Cluster)StackInstall spec.

**Comment by muvaf** [comment]
@hasheddan Do those mechanisms work if the user manually annotates the `ServiceAccount` after its creation?

**Comment by displague** [comment]
@muvaf The service account is only created, not updated. (`processRBAC` is called from the `stack` controller `handler`'s `create` function, `update` is empty)

**Comment by hasheddan** [comment]
@muvaf yes, manual annotation will enable the functionality presently, but it also requires restarting the controller `Pod`, which can be done by `kubectl delete pod [pod name]` and letting the `Deployment` bring it back up 👍

**Comment by displague** [comment]
I'm working on this as part of #505.

The current thinking is:

```
kind: StackInstall
spec:
  serviceAccount:
    imagePullSecrets:
    - foo
```

These imagePullSecrets will be included in the Stack resource and the Stack unpack job.

I've not yet considered how these imagePullSecrets will make their way into `KubernetesApplication` resources, per #505.
