### ISSUE TITLE
Stack's controller image doesn't respect the StackInstall's image source

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1246]
### What happened?

When using an alternate image source in a `StackInstall`, for example to point to an alternate registry besides docker hub, this value will be honored to download the Stack image itself, but not the Stack's controller image.

Alternate image source example: https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/stacks/stackinstall.yaml#L6

Stack controller image example: https://github.com/crossplaneio/stack-gcp/blob/master/config/stack/manifests/install.yaml#L20

The stack controller will come from the hardcoded place in the `install.yaml`, regardless of what value was put in the `StackInstall.spec.source` field, leading to potentially mismatched versions of the stack image and the stack controller.

Related to #505 

### How can we reproduce it?

1. Install `StackInstall` with an value for the `spec.source` field
1. Observe the stack controller pod image is what is hard coded in the stack's `install.yaml`, which doesn't take into account the alternative image source

### What environment did it happen in?
Crossplane version: `v0.7.0`

**Comment by jbw976** [comment]
One simple suggestion could be for the stack manager to prepend the `StackInstall.spec.source` value to the stack controller deployment's image field (if it doesn't already have a fully qualified image path that already specifies an alternate registry).

**Comment by displague** [comment]
> (if it doesn't already have a fully qualified image path that already specifies an alternate registry)
I'm not sure if this can be determined because official images can be expressed as `ubuntu` with no slashes, so I assume (could be wrong) that `foo.bar/ubuntu` is not distinguishable from `foo/ubuntu`, so it would not be possible to determine if a repository hostname was provided unless there are three components (`foo.bar/ubuntu/ubuntu`)
