### ISSUE TITLE
Support for Spring Cloud / Steeltoe Connectors

### ISSUE THREAD

**Issue by macsux** [crossplane/crossplane#1252]
### What problem are you facing?
Connection information provided by the resource claim needs to be read by the application workload. Right now this is usually written as a secret via `writeConnectionSecretToRef` on the claim. Internally the app then needs to bootstrap it's internal objects with this configuration, such as creating MySqlConnectionFactory to configure MySqlConnection objects with connection string information when they are injected in the app code. 

This problem is tackled by [Spring Cloud Connectors](https://cloud.spring.io/spring-cloud-connectors/) and [.NET Steeltoe Connectors](https://steeltoe.io/docs/3-connectors). These projects were built primarily to integrate with similar "resource/claim" abstraction model that exists in Cloud Foundry, where service instances are "bound" to apps, resulting in the injection of connection information into the app as environmental variables. This connection information is standardized in a very specific format to allow connectors to process it. There is a single VCAP_SERVICES JSON block that describes all bindings (including service types, names, tags, etc) and their connection information. The connectors look for the presence of this variable and if found will automatically configure the internal factories, greatly simplifying developers' need to do configuration management. More details of VCAP_SERVICES structure can be found here: https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES
_Note that actual connection information is injected as a dictionary JSON property called  "credentials" for each bound service, and it's structure may vary based on service type, however most services attempt to standardize on passing connection information in URI format similar to the following:
mysql://username:password@host:port/dbName?connectionParameter=blah_

The proposal is to add the ability to inject VCAP_SERVICES block into workloads automatically for resource types supported by connectors. One option is to add `format: VCAP` under `writeConnectionSecretToRef`, however, I think adding this as part of the workload creation to transform the secret into VCAP env var format makes more sense. 

This would allow Spring & .NET apps to greatly benefit from running on CrossPlane.

**Comment by negz** [comment]
I wonder if this kind of functionality could be supported by a separate process that knew how to take a set of environment variables (i.e. those exposed by a Crossplane secret) and form them into the the VCAP format. For containerised workloads this would allow us to configure a sidecar container that handled this transformation without Crossplane workloads themselves needing any knowledge of Spring Cloud or Steeltoe.

**Comment by macsux** [comment]
I also thought about this today as there are many instances where you may
wanna run a precompiled image that expects configuration in very specific
format. Imo some kind of general purpose transformation controller would do
the trick, ex pushing input secret through a jq pipeline.

**Comment by nebhale** [comment]
Over in the CNCF [Cloud Native Buildpacks](https://buildpacks.io) project (the next generation of the Heroku and Cloud Foundry Buildpacks) we've been attempting to tackle this head on.  We've proposed a [specification](https://github.com/buildpacks/spec/blob/master/extensions/bindings.md) (internally for us, but as a proving ground for broader acceptance) that mounts metadata and secrets about a binding to the filesystem.  We feel that this gives the most flexibility and Kubernetes-native experience while still allowing the provisioners of services (e.g. Crossplane) to do what they need to do.

From there, Spring Cloud has also started up a new project [`spring-cloud-bindings`](https://github.com/spring-cloud/spring-cloud-bindings) that understands this format on the filesystem and transforms the properties into the appropriate Spring Boot configuration properties.  We're still exploring the best time to run this behavior (in-process, init container, etc.) but we intend to tie this all up and ship GA pretty quickly to help application developers consume this format.

Finally, there is a Kubernetes Service Binding WG meeting regularly to explore both the in-container projection of bindings as well as provisioning and linking specifications.  You can find them in the [#bindings-discuss](https://kubernetes.slack.com/archives/C012F2GPMTQ) Slack channel or check out the [Agenda](https://docs.google.com/document/d/1rR0qLpsjU38nRXxeich7F5QUy73RHJ90hnZiFIQ-JJ8/edit) from our meetings.  You'll notice both that we talked about this extensively today and that there was an Upbound representative participating as well.

**Comment by negz** [comment]
Anecdotally this isn't something I've seen any demand for yet within our community. I want to cross-link it to https://github.com/crossplane/crossplane/issues/2366 though - I could see us using that design to support this a connection details sink/plugin.
