### ISSUE TITLE
Manual testing steps for testing a managed resource

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1265]
### What problem are you facing?

When we make updates to implementations of managed resources, we often do manual testing. Although we have unit tests and integration tests in place, there are some scenarios that are like sanity checks that we humans are more capable of seeing.

### How could Crossplane help solve your problem?

I think if we write those scenarios down and check them especially during API version change, we could be more confident in our changes. As we go, we might be able to convert them into automated tests if possible but it's good to have such a list somewhere for new resources or PRs that change the resource's implementation dramatically.

**Comment by hasheddan** [comment]
@muvaf I think most of these could be written as periodic integration tests. The framework we are using on stack-gcp allows for creating resources, waiting for conditions, etc. I think even if we have manual tests written down that we will still miss a lot of things. If you have any features that you feel are not available in our integration testing framework let me know 👍

**Comment by hasheddan** [comment]
We do need to develop a criteria for introducing new tests / removing old ones / setting run frequency so that we don’t end up running a lot of low value tests.

**Comment by muvaf** [comment]
@hasheddan Yeah, my point is we should just make sure that if a big change on existing resource is introduced or a new resource is implemented, we know what to test either through integration test or manual test.

What we could do is to write down the main scenarios and require the author of the PR either write an integration test using the framework(definitely recommended) or confirm that they did the test manually. We could start with the following ones:
- Successful creation with the example YAML.
- Nothing unexpected happens when no change is made on the custom resource, such as unnecessary updates.
- Possible to connect to the resource via the information in connection secret, if exists.
- After the resource disappears in Crossplane cluster after deletion, it disappears in provider, too.
- Reconcile is not triggered when no change is made to custom resource, i.e. check whether something causes it go into infinite loop of calling `Reconcile` for some reason.

**Comment by hasheddan** [comment]
@muvaf I really like this. We could even create a PR check that says if a "sensitive" (i.e. API changing) part of the code is modified than an integration test must exist for it :+1:
