### ISSUE TITLE
template stacks: stacks should be able to specify controller version

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1291]
### What problem are you facing?

If I deploy a template stack, the version of the generic templating-controller image comes from the Crossplane helm chart. However, I might want my stack to be pinned to use a fork/master version/older version no matter what Crossplane version is deployed.

### How could Crossplane help solve your problem?

It should be possible to embed the templating-controller image in the template stack `.registry/behavior.yaml` and this should be used, if it doesn't exist, then Crossplane's value should be used as fallback.

**Comment by suskin** [comment]
> I might want my stack to be pinned to use a fork/master version/older version

Who is deciding which version to use? Is it a stack author, or the stack consumer? Would I want to be able to specify the image pull policy too?

**Comment by muvaf** [comment]
> Who is deciding which version to use? Is it a stack author, or the stack consumer?

It's the stack author.

> Would I want to be able to specify the image pull policy too?

I don't think that's very necessary at this point. Image pull policies are usually used either in dev mode to use the cached images or to save disk space in the cluster; for both cases our default `IfNotExists` should be sufficient IMO. If you have a use-case, would love to hear.
