### ISSUE TITLE
Remove API reference docs in favor of doc.crds.dev

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1295]
### What problem are you facing?

Currently our [API Reference docs](https://crossplane.io/docs/v0.8/api.html) are manually generated using [crossdocs](https://github.com/negz/crossdocs). This is not ideal for the following reasons:
- Crossdocs requires manual setup and configuration to pick up all relevant API types from every repo in the Crossplane ecosystem
- API types exist in many repositories, some of which are outside of the Crossplane org
- Adjusting the formatting or presentation of API docs requires regeneration of docs for all API types
 

### How could Crossplane help solve your problem?

Moving to using [doc.crds.dev](https://doc.crds.dev/), which dynamically generates documentation for CRDs provides the following benefits:
- Stack authors get docs immediately as soon as a CRD is pushed to Github
- Release process and api changes do not require manual updates to api reference docs
- If an improvement to generation is made, all stacks will immediately get the update, rather than each having to regenerate all of their docs again
- Since we would parse the CRD instead of the Go code, the infrastructure stacks could be written in any language and still get automatic API reference docs
- Update current API Reference with repo links to crd.docs.dev

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/1298.

**Comment by negz** [comment]
Whoops - closed the wrong issue.

**Comment by negz** [comment]
@hasheddan Some functionality I think we'd need to take a dependency on https://docs.crds.dev:

*  Reliably detect and list all CRDs within a repository, i.e. https://github.com/crdsdev/doc/issues/9.
*  Allow us to link to a particular git tag, so that older versions of the Crossplane docs can link to older versions of CRDs, i.e. https://github.com/crdsdev/doc/issues/5
* The ability to trust that the service will be up and working. This could either be in the form of a documented SLO for https://docs.crd.dev, or the ability for the Crossplane project to host our own instance of the service.

**Comment by hasheddan** [comment]
@negz I believe https://github.com/crdsdev/doc/issues/9 is now fixed 👍 I followed up with a comment there.

I agree on the other two. The reliability of doc.crds.dev is currently constrained by Github API rate limiting, but various caching strategies are being explored and tracked by https://github.com/crdsdev/doc/issues/13

**Comment by negz** [comment]
Could we have the CRD docs rendered expanded (i.e. not collapsed) by default?

**Comment by negz** [comment]
Also, (low prio) but a list of suggested repos to explore on the splash page would be nice.

**Comment by negz** [comment]
More nice to have / UX stuff: ideally the repo splash page like https://doc.crds.dev/github.com/crossplane/provider-gcp would use a friendlier identifier than the CRD filename. Perhaps something like:


* `cache.gcp.crossplane.io`
  * `v1beta1`
    * `CloudMemorystoreInstance`
    * `CloudMemorystoreInstanceClass`

**Comment by negz** [comment]
@hasheddan Should we consider this done now that https://crossplane.io is pointing at doc.crds.dev?

**Comment by hasheddan** [comment]
@negz I believe so 👍 Will track future improvements in https://github.com/crdsdev/doc
