### ISSUE TITLE
Docs 404 error for servicenetworking.gcp.crossplane.io/v1alpha3

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1296]
On https://crossplane.io/docs/v0.8/api.html, when you click [servicenetworking.gcp.crossplane.io/v1alpha3](https://crossplane.io/docs/v0.8/api/crossplaneio/stack-gcp/servicenetworking-gcp-crossplane-io-v1alpha3.md) it takes you to https://crossplane.io/docs/v0.8/api/crossplaneio/stack-gcp/servicenetworking-gcp-crossplane-io-v1alpha3.md which should be an html file.

![image](https://user-images.githubusercontent.com/284840/75082593-3904d880-54c9-11ea-89e9-b2f4e3d6f3ff.png)

You get a 404 error:
![image](https://user-images.githubusercontent.com/284840/75082625-6c476780-54c9-11ea-99a8-03e32c628c92.png)

Looks like there's an associated [v1beta1.md](https://crossplane.io/docs/v0.8/api/crossplaneio/stack-gcp/servicenetworking-gcp-crossplane-io-v1beta1.md) hanging out so maybe the docs need to be regenerated?

**Comment by hasheddan** [comment]
Unfortunately, this is a manually modified file, so it was not updated when we regenerated :disappointed: fix coming and see #1295 for future state :+1:

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/1298.
