### ISSUE TITLE
Update and clean up template stack UI schema files

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1297]
The ui schema files for the minimal stacks aren't up to date with the latest schema/format defined by the design doc(s):

* https://github.com/crossplane/crossplane/blob/master/design/one-pager-stack-ui-metadata.md#example-ui-schemayaml
* https://github.com/crossplane/crossplane/blob/master/design/design-doc-upbound-ui-spec.md#required-fields

Some possible issues to clean up:

* The `version` field isn't intended to be the version of the stack itself, but it looks like the minimal stacks are using it that way.  From the spec:
> A number formatted per semantic versioning spec https://semver.org/ for the version of the ui-schema.yaml file. This should be updated whenever the ui-schema.yaml file is updated.

* `printerColumns` has been removed from the ui schema, e.g. https://github.com/crossplane/stack-aws/pull/125

Direct links to ui-schema files we should clean up (there may be more, please be thorough about cleaning all stacks maintained by the crossplane community):

* https://github.com/crossplane/stack-minimal-gcp/blob/master/.registry/resources/minimalgcp.ui-schema.yaml
* https://github.com/crossplane/stack-minimal-aws/blob/master/.registry/resources/minimalaws.ui-schema.yaml
* https://github.com/crossplane/stack-minimal-azure/blob/master/.registry/resources/minimalazure.ui-schema.yaml
* https://github.com/crossplane/sample-stack-wordpress/blob/master/.registry/resources/wordpressinstance.ui-schema.yaml

**Comment by prasek** [comment]
@muvaf is this ready to close?

**Comment by muvaf** [comment]
Printer columns and other updates are done:
* Minimal AWS https://github.com/crossplane/stack-minimal-aws/pull/7
* Minimal Azure: https://github.com/crossplane/stack-minimal-azure/pull/7
* Minimal GCP has the fixes.
* Sample Wordpress has the fixes.

> The version field isn't intended to be the version of the stack itself, but it looks like the minimal stacks are using it that way.

@jbw976 do you think we should revert ui-schema versions back to 0.1.0 now or count from this point on?

**Comment by muvaf** [comment]
Closing this optimistically.
