### ISSUE TITLE
Delete provider objects after the objects that consume them

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1301]
This is a summary of some discussions around this topic.

### What problem are you facing?

As a Crossplane user who's deleting a bunch of resources and a provider, I'd like my provider to be deleted last. For example, let's say I install the minimal GCP stack, which also creates a provider for me. Let's say I then create a database in GCP, `D`. If I uninstall the stack, which deletes the provider, I want the provider to be around until all of the resources which need it (such as the database `D`) have been deleted. Otherwise, the provider may be deleted before the resources are, and I won't have a way to delete the resources anymore.

### How could Crossplane help solve your problem?

There are a couple options, but it seems like using finalizers could be a good pattern.

It seems like the part of the system which "binds" to a provider `P` when a resource `R` is being created is the best part to manage this. If I remember correctly, this is the controller which comes with the infrastructure stack.

The controller would add a finalizer to a provider `P` when a resource `R` is created, and would remove the finalizer when `R` is deleted. In a cascading delete scenario, using finalizers like this would keep `P` around for as long as its resources are around.

#### Example

Here is a slightly more concrete version. Let's look at the `finalizers` list of a provider `P`. Initially, it's empty (it wouldn't be shown in `kubectl` commands if it's empty, but we're showing it for clarity):

```yaml
finalizers: [ ]
```

Let's say a `CloudSQLInstance` named `mycloudsql` is created in the namespace `mynamespace`. The finalizers list on `P` would look like this:

```yaml
finalizers:
- finalizer.cloudsqlinstances.database.gcp.crossplane.io:mynamespace/mycloudsql
```

Then, when `mycloudsql` is deleted, the finalizer would be removed, and the finalizers list would be empty:

```yaml
finalizers: [ ]
```

#### Scaling

There are some scaling considerations around a finalizer-based approach, especially: at what point does contention on the finalizer block become a problem for the controllers interacting with a provider?

**Comment by negz** [comment]
I think this is a duplicate of https://github.com/crossplane/crossplane-runtime/issues/116.

**Comment by suskin** [comment]
@negz you are right - sounds like a duplicate. I'll close this one
