### ISSUE TITLE
Add packageType meta descriptor for stacks

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1302]
### What problem are you facing?
There are different types of packages in common usage including:

**Providers**: add infrastructure to a `Crossplane Instance`, so you can provision cloud services, cloud networking & security, and managed Kubernetes target clusters from the Crossplane API using tools like `kubectl` and `kustomize`.
 * [GCP provider](https://github.com/crossplane/stack-gcp)
 * [AWS provider](https://github.com/crossplane/stack-aws)
 * [Azure provider](https://github.com/crossplane/stack-azure)

**Stacks**: environment instance configurations (dev, stage, prod) that use one or more `Providers`, have a core environment config (nets, subnets, secure managed service connectivity, etc.), and define a self-service catalog (classes of service) that are defined to work together so `Applications` can consume the infrastructure using `Resource Claims` for dynamic provisioning. 

The use of `Stack` (as a `packageType`) to describe an environmental instance config (a collection of resources representing infrastructure) is more aligned with the colloquial usage.
 * [minimal GCP stack](https://github.com/crossplane/stack-minimal-gcp)
 * [minimal AWS stack](https://github.com/crossplane/stack-minimal-aws)
 * [minimal Azure stack](https://github.com/crossplane/stack-minimal-azure)

**Applications**: compose all resources needed for an application to run in a `namespace`, including infrastructure dependencies that are dynamically provisioned via `Resource Claims` from the Crossplane instances available classes of service.
 * [Wordpress application](https://github.com/crossplane/sample-stack-wordpress)

I would like to programmatically see the package type, by introspecting the package contents ideally by a `packageType` field in the `app.yaml`.

### How could Crossplane help solve your problem?
1. Add a new `packageType` field in app.yaml schema with supported values of [Provider, Stack, Application].
  * crossplane/crossplane#1300
  * crossplane/crossplane-cli#42
1. Update all of the packages (listed above and below) that are published to the https://hub.docker.com/u/crossplane that have the following `packageType`:
    * **Provider** - cloud provider
       * crossplane/stack-gcp#193
       * crossplane/stack-aws#140
       * crossplane/stack-azure#116
       * crossplane/stack-rook#44
    * **Stack** - environment config
       * crossplane/stack-minimal-gcp#28
       * crossplane/stack-minimal-aws#6
       * crossplane/stack-minimal-azure#6
    * **Application** - application with infrastructure dependencies expressed as claims
       * crossplane/sample-stack-wordpress#40

**Comment by displague** [comment]
Reopening until the various stack and CLI PRs are merged

**Comment by prasek** [comment]
done and done
