### ISSUE TITLE
Template Stacks: support for deploying resources to clusters provisioned by Crossplane

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1309]
### What problem are you facing?

Today, template stacks are used to bundle resources that are to be deployed into the cluster that Crossplane runs. While this is useful for cloud resources, the general application model of Crossplane works through `KubernetesApplication` which includes a list of resources to deploy to the cluster provisioned by Crossplane.

While it's possible to include all resources you want in a `KubernetesApplication` manually, what I'd like to have is to have the output of the templating (helm or kustomize) to be bundled into one `KubernetesApplication` resource.

### How could Crossplane help solve your problem?

There are a few options. We can let stack author specify a parameter in `StackDefinition.behavior` to indicate that the output should be bundled in a `KubernetesApplication`. Other approach could be that authors could annotate the resources in the stack file system with a special key to indicate that it should go to `KubernetesApplication`

**Comment by negz** [comment]
We're planning to remove KubernetesApplication, so I don't think we need to address this.
