### ISSUE TITLE
Investigate multiple controllers vs one controller per process/pod

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1312]
### What problem are you facing?

In Crossplane ecosystem, we generally have 1 manager and N controller registered to it in every stack. This 1 manager runs in 1 process which runs in 1 container that is contained in 1 pod.

We have continued to follow a similar in template stacks, too. A template stack author writes the stack YAMLs and then during installation, it uses a manager with a generic controller which runs in its own pod.

The initial thought on template stacks was that we'd have one manager and different controllers would be added/removed as the stacks get installed and uninstalled. However, as of right now, [controller-runtime doesn't support stopping](https://github.com/kubernetes-sigs/controller-runtime/issues/764) or removing controllers after the manager is started. This and other factors affected our decision to go with 1 pod/manager/controller per template stack. But we're at a position where we'll increasingly let users define their own kinds, i.e. flexible resource claims and OAM work.

Even though we are technically limited about stopping the controller, we can possibly consider investing in making it possible. However, we don't have much data around how much efficiency gains (cpu + memory wise) we'd get without much downside in terms of security.

### How could Crossplane help solve your problem?

We should do an analysis to compare two scenarios where N different kinds are to be reconciled:
* One manager and N different controllers running in one pod.
* N different pods each reconciling their own kind.

(I imagine N will be important, too, i.e. one might be more efficient only after 10 controller..)

Obviously, one can say that there is the overhead of having more pods, different processes etc. but we actually don't have data and the reason we need to have solid real insights is that RBAC is easily applied to one pod per kind scenario while for the other one there is one big pod with too many permissions, hence our decision should be backed by actual data so that compromises make sense for all and the effort is worth it.

So, the analysis will help us to make a decision:
* Way more costly to run 1 pod per kind, then invest in the ability to stop controllers and make the RBAC work somehow(probs with some hack) or
* Not worth the effort or more performant when they are run independently, then spawn a new pod for each new kind if there is a need to stop it and keep doing RBAC the way it's supposed to be done, i.e. limited service account for the pod.
* It becomes efficient to stack up the controllers after a certain number, then come up with a guideline about when to apply which pattern.

**Comment by negz** [comment]
I believe we're likely to settle on multiple controllers as part of our move to composition rather than the template controller.
