### ISSUE TITLE
Render OAM ContainerizedWorkload

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1313]
### What problem are you facing?

Per the [OAM Runtime Architecture document](https://docs.google.com/document/d/11AYNGhvry_B3l_tO3Yyv1f9tDoezZOpGIYV56oZwb5s/edit#heading=h.x458enhyy1sq) and subsequent [spec updates](https://github.com/oam-dev/spec/pull/316), the first core `Workload` type required by OAM is the `ContainerizedWorkload`. As an implementation of the OAM spec, Crossplane should support translating a `ContainerizedWorkload` into Kubernetes-native object(s).

### How could Crossplane help solve your problem?

For the first iteration, a controller should be implemented that watches for `ContainerizedWorkloads` created by the `ApplicationConfiguration` controller described in #1268, then translates it and any related traits into Kubernetes-native objects. The process for doing so is still being discussed in #1305.

**Comment by negz** [comment]
Cross linking the work on this in https://github.com/crossplane/stack-oam-kubernetes-remote/pull/1.
