### ISSUE TITLE
Copy imagePullSecrets to Crossplane Host environments

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1317]
## What problem are you facing?

`imagePullSecrets` can now be shared between StackInstall, Stack, and Deployment resources as needed to unpack packages and run the controller.

The named `imagePullSecrets` are not available in the host for host aware stack-manager installations.

## How could Crossplane help solve your problem?

These secrets will need to be given UUID names on the host side since tennant namespaces share a common controller namespace in this environment and we wouldn't want secrets from varying namespaces to be available outside of their intended namespace. In order for these renamed secrets to sync with their sources they will need to be labeled with the source name.

An alternative to using the UUID approach may be to use a simple namespace prefix, as I believe is done for other resources in the controller namespace.  The effort between these two approaches is similar, as all deep references to the secret name will need to be revised in either case.   With UUID names, we may suffice to replace imagePullSecret references.  With namespace prefixed secret names we will need to replace imagePullSecret, valueFrom, and other references.

The UUID approach is safer if any secret reference formats are missed.

## Related Issues

_Originally posted by @displague in https://github.com/crossplane/crossplane/issues/505#issuecomment-593449630_

**Comment by turkenh** [comment]
I agree what @displague states in description and with current implementation, UUID approach seems to be a good solution.

However, I have another point:

Users can only access host API Server (where controller-namespace lives) via deployment spec of controller. This is the only path they can use to access something on host cluster. 
Embedding whole controller deployment spec into stack definition is already a security issue because we can never make sure what a user could do with that. If we could somehow change this, we could be more confident. For example instead of embedding complete spec, just getting couple of params (e.g. image, command/args, imagepullsecret -which we would always override in host aware mode-) and always using a predefined deployment spec. Then we could go with namespace prefix just like we do for other resources to map tenant to host and we wouldn't need to implement a special path.

**Comment by displague** [comment]
> For example instead of embedding complete spec, just getting couple of params (e.g. image, command/args, imagepullsecret -which we would always override in host aware mode-) and always using a predefined deployment spec. Then we could go with namespace prefix just like we do for other resources to map tenant to host and we wouldn't need to implement a special path.

This is the direction we are headed by pushing the stackinstall tag into the controller (#1307) and forcing the StackInstall image to be the stack controller (#1308).  The remaining parameters are command line arguments and environment variables.

It is easy to lock this forceful behavior in for Stack resources created by StackInstall resources.  Since StackInstall resource handlers are the only thing that cares about `install.yaml`, we could even remove that file from Stack packages.

Removing these fields from Stack resources is a little harder. We currently have the template stack use-case which demands environment variables and command line arguments in the Stack resource.  The ability to access secrets using StackInstall resources (or install.yaml) is irrelevant while Stack resources embed DeploymentSpec.

Perhaps one approach is to use a custom type to replace `DeploymentSpec` in the Stack spec. We could limit environment variables and command line arguments to simple maps and slices that can not take advantage of `valueFrom`.  Additionally, we would want to remove support for initContainers and supplementary containers.

**Comment by displague** [comment]
Another thought: Instead of copying DeploymentSpec when creating the new Deployment resource, we could walk the Stack.Spec.Controller.Deployment (DeploymentSpec) and only pull out the pieces that we are interested in. We would not support complex environment variables.

**Comment by displague** [comment]
The secrets will need to be available on the host for either/both of:
* StackInstall resources that reference the imagePullSecret
  The unpack job needs imagePullSecrets to access the private image.
* Stack resources that reference the imagePullSecret
  The controller needs to prepare the secrets for the Deployment to run.

Syncing will have to take place in both StackInstall and the Stack controller.

Deletion of unused secrets will need to wait until there are no StackInstalls and no Stacks relying on the imagePullSecret.

A first pass at this could perhaps exclude Stack syncing of secrets, but that would ultimately be necessary.

**Comment by displague** [comment]
Another approach, far simpler to contend with, is to use a single parent label on a secret.  Either a StackInstall or a Stack will be the parent.  In general practice, the secret will be copied twice, once by the StackInstall controller, once by the Stack controller.

This duplication simplifies the ownership and deletion responsibility and makes the most sense for reusing the existing flow for host-aware resource handling.

**Comment by displague** [comment]
The owner of the synced StackInstall secrets can be the InstallJob.  When the InstallJob is created, the secrets will be synced. Deleting the installjob will result in the GC removal of the synced secret(s).

The owner of the synced Stack secret can be the deployment SA. When the Deployment SA is created, the secrets will be synced. Deleting the deployment SA will result in the GC removed of the synced secret(s). 

While looking at the existing code involved in syncing the deployment SA secrets, I notice that it would have been convenient for imagePullSecrets to have been bound to the SA instead of to the containers.  The reason this approach was not taken with imagePullSecrets is that the installjob does not run under a unique SA.  We may wish to rethink that in the future as a way to consolidate the instances and approaches to syncing secrets.

I also noticed that the names of the deployment SA secrets are predictable which goes against the thinking expressed earlier in this issue.  I will consider replacing those secret names in the PR to address imagePullSecret sync'ing, or spin off a new issue to address that concern.  It may be convenient to handle these concerns from the same PR because a method to generate UUID based secret names will be introduced.

**Comment by displague** [comment]
We current use the `default` SA of the `{tenant}-controllers` namespace on the host to run all of the stack controllers in a host-aware environment.

I supposed we might be able to leverage the ServiceAccount `imagePullSecrets` on the host to inject the secrets into the stack controller's pods.

What I discovered, with @turkenh's help, is that this approach...

1. We would want to create a new SA for each stack-controller
2. We could add the tenant synced API secret (from the tenant SA) to this new host SA
3. We would add the imagePullSecrets to the host SA

...while there are positives factors, is not possible because:

1. This should be a good thing. Each stack controller would run under its own SA on the host which could then be further restrictied. This separation would be needed to prevent the `default` SA from accumulating `imagePullSecrets` for all stacks in all namespaces.

2. Would avoid the need to `automountServiceAccountToken: false` and use a custom mount.  While the host SA would have access to the tenant API, it would still have a token, limited as it is, that could connect to the host API. It is not possible to create an SA without the default secret (or remove it after creation) because the token controller enforces its presence: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller
While we could prevent the secrets from being mounted, with `automountServiceAccountToken`, we would lose the advantage of having the tenant API token attached to the SA secrets.  (Investigating this introduced me to PodPresets, https://kubernetes.io/docs/concepts/configuration/secret/#automatic-mounting-of-manually-created-secrets which could be useful in template stacks to avoid some of the manual injection we do there).

3. The registry secrets listed in imagePullSecrets could be added to the host SA. They would need to be synced to the host first and their names would have to be UUID based (for the reasons stated earlier in this issue).   The owner reference (for garbage collection) for these secrets could be the host SA (or the deployment), this saves some manual cleanup later.  The host deployment would not need to have the containers walked with imagePullSecrets added to it manually.  There are no downsides to this step other than requiring the previous two steps which have downsides. (1. Create Host SA, 2. ..., 3. Profit, the devil was in the details of step 2.)
