### ISSUE TITLE
Support in workloads for images from private registries

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1318]
This issue is broken out from #505 

The Stack Manager now supports the scenario of installing a stack from a private registry, supplying the image pull secrets to the unpacking job and the stack's controller.

Another scenario that needs to be supported is for when the a workload is to be run on a remote k8s target and the container image for that workload comes from a private registry.   The image pull secrets for the private registry would need to be propagated to the remote k8s target along with the workload.

Some more comments from @displague can be found in https://github.com/crossplane/crossplane/issues/505#issuecomment-593441609

**Comment by negz** [comment]
I don't think we need to worry about this anymore given that we don't intend for packages to install workloads, or to support scheduling workloads in general.
