### ISSUE TITLE
Stack builds are overwriting crossplane builds in crossplane.releases bucket

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1320]
### What happened?

It looks like the stack repos are using setting up their builds with `S3_BUCKET ?= crossplane.releases`, which is causing their binary outputs to be published to the same S3 bucket where crossplane is published to.

Take for example https://releases.crossplane.io/build/release-0.6/v0.6.0/.  This **should** be from the main crossplane repo's v0.6 release, but it appears to be from one of the much more recent stack-aws repo's v0.6 release, meaning that the stack-aws release overwrote an older crossplane release.

**NOTE:** This is **not** the images that are being overwritten on dockerhub, this is only the binaries that are published to s3.  I'm not sure what/if those are really used anymore, so this may not be very severe.

### How can we reproduce it?

Run Jenkins build pipeline for any of the stack repos that are using the build submodule.

**Comment by muvaf** [comment]
Probably because of this https://github.com/crossplane/stack-aws/blob/master/Makefile#L17

**Comment by jbw976** [comment]
This has been fixed in all of the provider repos with the following PRs:
* https://github.com/crossplane/provider-gcp/pull/214
* https://github.com/crossplane/provider-aws/pull/190
* https://github.com/crossplane/provider-azure/pull/132
* https://github.com/crossplane/provider-rook/pull/54

I have verified in s3 that those repos are no longer publishing (and overwriting) builds on https://releases.crossplane.io/.
