### ISSUE TITLE
Add OAM local stack

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/crossplane#1324]
Main repo: https://github.com/crossplane/addon-oam-kubernetes-local
Owner: @ryanzhang-oss

This is the umbrella issue to track all progress on OAM local Stack:

* [ ] Containerized Workload
* [ ] ManualScalerTrait

**Comment by negz** [comment]
I don't think we'll package this as a stack (aka package) after all - we're happy with the current pattern of installing it via Helm. We're going to limit packages to installing Crossplane providers and "composition stuff" - i.e. composite resources etc.
