### ISSUE TITLE
Package images should not require a shell

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1325]
### What problem are you facing?

Crossplane packages are installed using an `initContainer` that runs `cp` to get package metadata into the container where the Stack Manager `unpack`  is run.   This `cp` command is run using a binary found in the stack package.

This `cp` command should not be trusted.

Secondarily, stacks, especially template stacks, should not require a base operating system in their packages.

### How could Crossplane help solve your problem?

The `unpack` process can take advantage of the stack-manager image to provide a trusted runtime environment. Paths /bin, /lib, /etc, /usr, and perhaps others needed or otherwise consulted at runtime within the initContainer can be volume mounted from volumes shared from the stack-manager container.

**Comment by hasheddan** [comment]
This issue is no longer relevant with the new package manager.
