### ISSUE TITLE
template stacks version cleanup

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1335]
### What problem are you facing?

We have released some versions of template stacks by hand in the past, and have recently switched to more automated releases.

However, the automated releases that run whenever changes are merged to master generate their own unique version, and they use the most recent tag on the branch to do that. When we were releasing by hand, we didn't necessarily always tag the releases, so some of the stacks could be generating versions that don't have a reference tag.

### How could Crossplane help solve your problem?

Go through all of the template stacks (`stack-minimal-*`, `sample-stack-wordpress`) and add a tag on master for the most recent release, if there isn't one already.

**Comment by jbw976** [comment]
Is it already part of the release process for each template stack repo to add a new tag, so subsequent builds from master will have a version based off that new latest release tag?

**Comment by negz** [comment]
Release experts @hasheddan and @jbw976, is this still relevant? We're planning to remove template stacks, but I presume we'll have them for at least a few more releases.

**Comment by hasheddan** [comment]
I am fairly certain this is handled by https://github.com/crossplane/cicd
