### ISSUE TITLE
Use of `v` prefix in versions in Crossplane ecosystem

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1352]
### What problem are you facing?

I would like to get to a consensus about using `v` prefix in the versions of the releases in Crosslane ecosystem. According to [SemVer](https://semver.org/), the spec does not include `v` prefix but it [doesn't restrict it either](https://github.com/semver/semver/issues/204). There are many instances of `v` prefix being used. Apparently, `v` prefix existed in earlier versions of SemVer but in 2.0, it's [been removed](https://stackoverflow.com/questions/37781073/why-github-suggest-prefix-your-version-names-with-the-letter-v) (not an official source).

### How could Crossplane help solve your problem?

AFAIK, all stacks and Crossplane use `v` prefix. I'd like to confirm this (or change) and save the decision in this issue to refer to later on when we introduce new components that have their own releases.

**Comment by displague** [comment]
https://github.com/crossplane/crossplane/pull/1288/files#diff-2685e3bc90b840b02487c9e329030a1cR93-R97 will need some updates however we change things.

**Comment by displague** [comment]
I would like to see us stick to one common convention in all of our uses, but I don't think that we should break convention of the greater communities. In Git repos it is possible to tag with a numeric "1" or "1.2.3", but in my experience this is very uncommon compared to using the "v" prefix.

I got the impression when reading the semver docs that "1.2.3" is the semantic version, whether or not a "v" is there.  "v" simply acts as a visual framing of the version.

https://semver.org/#is-v123-a-semantic-version
> Is “v1.2.3” a semantic version?
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

**Comment by hasheddan** [comment]
+1 for including "v" everywhere

**Comment by muvaf** [comment]
I think we have settled on `v` prefix as all new releases now include it.
