### ISSUE TITLE
Backup and Restore doc

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1353]
### What problem are you facing?

There is no instruction or assurance about Crossplane's ability to be backed up and restored. It has been one of the things that we have been careful implicitly while following Kubernetes API patterns but there is no testing done or any doc that describes how you'd do it.

### How could Crossplane help solve your problem?

Test dynamic and static provisioning of `v1beta1` resources to see how backup/restore would work or whether it works at all. Write a doc for instructions on what needs to be backed up and what can be skipped.

**Comment by displague** [comment]
The results of this could be linked from this document: https://github.com/crossplane/crossplane/pull/1288/files#diff-2685e3bc90b840b02487c9e329030a1cR27-R31

I think it is important to define the scope of the backup/restore.  For example, a complete restore (of etcd) will have less complications than a partial restore (of just the crossplane-system namespace, for example) because of the dependence on cluster scoped resources.  It is conceivable that Crossplane controllers would attempt to "heal" missing cluster scoped resources, but should this ever be in scope?

For example, a StackInstall could recognize that CRDs are missing and fetch and replace them.  A Stack could find that ClusterRoles have been removed and attempt to recreate them.

**Comment by displague** [comment]
I think for Stack Manager, the state is represented by a single cluster.

The more interesting (and fault prone) scenarios will involve how the Stack Manager handles host-aware backup/restore scenarios.  Can one side be restored without the other? How should you restore the tenant or the host alone? How does this affect the crossplane (KubernetesTarget) clusters?

On the Crossplane core side, the Workload controller is most interesting.  What would happen if you restored an older version of the workload while KubernetesApplicationResources had already been provisioned.  Would remote KARs created resources in a reverted local state be successfully deleted or would they be orphaned? Should they be deleted?

These "rollback" concerns are also interesting for provider and application packages.

**Comment by muvaf** [comment]
> I think it is important to define the scope of the backup/restore. For example, a complete restore (of etcd) will have less complications than a partial restore (of just the crossplane-system namespace, for example) because of the dependence on cluster scoped resources. It is conceivable that Crossplane controllers would attempt to "heal" missing cluster scoped resources, but should this ever be in scope? If backup/restore is "tar", should we also include "fsck" / "apt-get -f install".

>The more interesting (and fault prone) scenarios will involve how the Stack Manager handles host-aware backup/restore scenarios. Can one side be restored without the other? How should you restore the tenant or the host alone? How does this affect the crossplane (KubernetesTarget) clusters?


I think the best course of action would be to make CRDs that we reconcile in a way that they can be safely restored from scratch, i.e. I should be able to export all CR instances (or whatever we need) and when I `apply` them in a new cluster, I should get to the same state. So, I don't expect Crossplane to be aware of the backup or restore scenario and act on it, rather be idempotent and declarative enough that copy+paste of some resources will get you to the same state. I think we're close to be in this state.

The user can use `etcd` backup or velero or some simple script they wrote. What I'd like Crossplane to explain in a doc is what I should do to backup and then restore. For example, right now you have to back up some of the credentials secret, too, so that the resources that give you the creds only in creation time are handled.

> On the Crossplane core side, the Workload controller is most interesting. What would happen if you restored an older version of the workload while KubernetesApplicationResources had already been provisioned. Would remote KARs created resources in a reverted local state be successfully deleted or would they be orphaned? Should they be deleted?

There is the assumption that control cluster is the source of truth, so, I imagine it would reconcile whatever is in local.

**Comment by prasek** [comment]
@negz @muvaf @hasheddan will the doc for using `crossplane.io/external-name` annotation to support adopting existing external resources when CRs are restored from backup?

this looks fairly straight forward, just add `crossplane.io/external-name` to the managed resource or resource claim like the following:

<details><summary>Resource Claim</summary>

```
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  annotations:
    crossplane.io/external-name: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
  creationTimestamp: '2020-05-07T20:32:40Z'
  finalizers:
    - finalizer.resourceclaim.crossplane.io
  generation: 3
  labels:
    core.crossplane.io/parent-group: wordpress.apps.crossplane.io
    core.crossplane.io/parent-kind: WordpressInstance
    core.crossplane.io/parent-name: rebel-alliance-may7-azure2-ws1-wp1
    core.crossplane.io/parent-namespace: rebel-alliance-may7-azure2-ws1
    core.crossplane.io/parent-version: v1alpha1
  name: rebel-alliance-may7-azure2-ws1-wp1-sql
  namespace: rebel-alliance-may7-azure2-ws1
  ownerReferences:
    - apiVersion: wordpress.apps.crossplane.io/v1alpha1
      blockOwnerDeletion: true
      kind: WordpressInstance
      name: rebel-alliance-may7-azure2-ws1-wp1
      uid: e393d26e-6e9f-41f6-9022-574ffa29b302
  resourceVersion: '18529'
  selfLink: >-
    /apis/database.crossplane.io/v1alpha1/namespaces/rebel-alliance-may7-azure2-ws1/mysqlinstances/rebel-alliance-may7-azure2-ws1-wp1-sql
  uid: b7d5b87d-11d9-4d67-a0b9-442e89b47ed3
spec:
  classRef:
    apiVersion: database.azure.crossplane.io/v1beta1
    kind: SQLServerClass
    name: rebel-alliance-may7-azure2-sqlservermysql
    uid: 2672c84e-098d-42bc-b438-9e6e0963c468
  engineVersion: '5.7'
  resourceRef:
    apiVersion: database.azure.crossplane.io/v1beta1
    kind: MySQLServer
    name: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
    uid: 82a40725-5172-402c-9ca5-893556ce2478
  writeConnectionSecretToRef:
    name: sql
status:
  bindingPhase: Bound
  conditions:
    - lastTransitionTime: '2020-05-07T20:35:00Z'
      reason: Resource is available for use
      status: 'True'
      type: Ready
    - lastTransitionTime: '2020-05-07T20:32:41Z'
      reason: Successfully reconciled resource
      status: 'True'
      type: Synced
```

</details>

<details><summary>Managed Resource</summary>

```
apiVersion: database.azure.crossplane.io/v1beta1
kind: MySQLServer
metadata:
  annotations:
    crossplane.io/external-name: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
  creationTimestamp: '2020-05-07T20:32:41Z'
  finalizers:
    - finalizer.managedresource.crossplane.io
  generateName: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-ws1-wp1-sql-
  generation: 3
  name: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
  resourceVersion: '451736'
  selfLink: >-
    /apis/database.azure.crossplane.io/v1beta1/mysqlservers/rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
  uid: 82a40725-5172-402c-9ca5-893556ce2478
spec:
  claimRef:
    apiVersion: database.crossplane.io/v1alpha1
    kind: MySQLInstance
    name: rebel-alliance-may7-azure2-ws1-wp1-sql
    namespace: rebel-alliance-may7-azure2-ws1
    uid: b7d5b87d-11d9-4d67-a0b9-442e89b47ed3
  classRef:
    apiVersion: database.azure.crossplane.io/v1beta1
    kind: SQLServerClass
    name: rebel-alliance-may7-azure2-sqlservermysql
    uid: 2672c84e-098d-42bc-b438-9e6e0963c468
  forProvider:
    administratorLogin: myadmin
    location: West US
    resourceGroupName: rebel-alliance-may7-azure2-resourcegroup
    resourceGroupNameRef:
      name: rebel-alliance-may7-azure2-resourcegroup
    sku:
      capacity: 2
      family: Gen5
      tier: GeneralPurpose
    sslEnforcement: Disabled
    storageProfile:
      backupRetentionDays: 7
      geoRedundantBackup: Disabled
      storageAutogrow: Disabled
      storageMB: 8192
    version: '5.7'
  providerRef:
    name: rebel-alliance-may7-azure2-azure-provider
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: b7d5b87d-11d9-4d67-a0b9-442e89b47ed3
    namespace: crossplane-system
status:
  atProvider:
    fullyQualifiedDomainName: >-
      rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf.mysql.database.azure.com
    id: >-
      /subscriptions/038f2b7c-3265-43b8-8624-c9ad5da610a8/resourceGroups/rebel-alliance-may7-azure2-resourcegroup/providers/Microsoft.DBforMySQL/servers/rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
    lastOperation:
      errorMessage: >-
        Code="OperationIdNotFound" Message="The operation with Id:
        '9d38a42b-e805-4942-a6ce-f755c5f7f49c' does not exist."
      method: PUT
      pollingUrl: >-
        https://management.azure.com/subscriptions/038f2b7c-3265-43b8-8624-c9ad5da610a8/providers/Microsoft.DBforMySQL/locations/westus/azureAsyncOperation/9d38a42b-e805-4942-a6ce-f755c5f7f49c?api-version=2017-12-01
    name: rebel-alliance-may7-azure2-ws1-rebel-alliance-may7-azure2-t5rsf
    type: Microsoft.DBforMySQL/servers
    userVisibleState: Ready
  bindingPhase: Bound
  conditions:
    - lastTransitionTime: '2020-05-07T20:35:00Z'
      reason: Resource is available for use
      status: 'True'
      type: Ready
    - lastTransitionTime: '2020-05-08T16:59:59Z'
      reason: Successfully reconciled resource
      status: 'True'
      type: Synced
```

</details>

**Comment by negz** [comment]
I believe https://crossplane.io/docs/v0.12/introduction/managed-resources.html addresses this.
