### ISSUE TITLE
Package Crossplane for OperatorHub.io

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1362]
### What problem are you facing?

Crossplane is available for installation currently as a container published to dockerhub and a helm chart published to https://charts.crossplane.io/.  These are useful in a lot of environments, but do not natively integrate with OperatorHub.io and OpenShift.

### How could Crossplane help solve your problem?

Crossplane's functionality could provide a lot of value for OpenShift users to provision and manage infrastructure the Kubernetes way alongside their applications running on the OpenShift platform.  OperatorHub.io would make Crossplane able to reach new audiences and grow the community adoption.

### Details

Since Crossplane is already a controller-runtime based implementation and packaged in a container, the work required here would be limited to metadata and packaging only, no code or runtime logic changes should be needed. Essentially, we only need the Operator Framework packaging. The key essentials are `ClusterServiceVersion`, `CustomResourceDefinitions`, and a package definition.  Details about these elements can be found in https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#package-your-operator.

Other links:
* https://github.com/operator-framework/community-operators 
* https://github.com/operator-framework/getting-started 
* Example operator packaging: https://github.com/yard-turkey/awss3operator

**Comment by displague** [comment]
PR in progress at https://github.com/operator-framework/community-operators/pull/1461/

**Comment by displague** [comment]
The community-operators PR has also been merged: https://github.com/operator-framework/community-operators/pull/1515

The issue reported here https://github.com/crossplane/stack-aws-sample/issues/17 prevents the use of sample stacks in Openshift with https://github.com/crossplane/crossplane/pull/1400 proposing a fix.

For the next few Crossplane releases, manually updating the directories added in 1461 and 1515 should be viable:
* Any crossplane/crossplane README.md 
* Any new CRDs will need to be reflected in the RBAC permissions
* Any changes to the runtime arguments of the StackManager or Crossplane should be reflected in the ClusterServiceVersion file
* Any new CRDs or updated CRDs will need to reflected in the ClusterServiceVersion file as well as updating the CRD file
* The CRD files will need to have their leading `---` removed
