### ISSUE TITLE
Deprecate crd-install hook?

### ISSUE THREAD

**Issue by resouer** [crossplane/crossplane#1366]
### What happened?

This is a known issue: https://github.com/crossplane/crossplane/blob/569c75e30db93cf2f73eb028890ae976c37d1895/Makefile#L121

```
helm install crossplane --namespace crossplane-system crossplane-master/crossplane --version $version
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```

I suggest we can consider deprecating crd-install in Crossplane helm package.

### How can we reproduce it?

```
# helm v3.1.1
helm install crossplane --namespace crossplane-system crossplane-master/crossplane --version $version
```

### What environment did it happen in?
Crossplane version: 0.9.0-rc.20.g569c75e

**Comment by muvaf** [comment]
Hi @resouer !

We kept it in place [to be compatible with Helm 2](https://github.com/crossplane/crossplane/pull/1020). AFAIK, in Helm 3 you only get a warning and installation succeeds. Have you had a different experience?

**Comment by resouer** [comment]
@muvaf No, just warnings of course. I didn't know that Crossplane wants to keep compatibility with helm 2. Any upgrade plan may I ask?

**Comment by muvaf** [comment]
I think we want Crossplane to be compatible with both Helm2 and Helm3, which is the case right now. But this comes with its own challenges, especially around maintenance burden of making the same chart compatible with both.

So, in case we can't support both at the same time, we'd probably have two different charts for each version but in the foreseeable future, I don't see Crossplane dropping support for Helm2 and go all in with Helm3.

**Comment by resouer** [comment]
OK, I think it's clear now. Maybe you can add this plan in doc or somewhere. I will close this issue.
