### ISSUE TITLE
Use workload identity as provider

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1378]
### What problem are you facing?

Crossplane `Provider` resources refer to a `Secret` that contains credentials data for the given account that Crossplane will use to provision resources. However, cloud providers suggest that identity credentials should be used through a mechanism that will inject them into the pod that uses them. How it's enabled differs between providers but the general idea is that the Kubernetes `ServiceAccount` that the `Pod` uses is annotated by a special string and then cloud provider allows that pod to assume that role/account. Here is the list of guides on how to enable it:
* [GCP Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
  * A `DaemonSet` intercepts the requests to the GCE metadata service and redirects them to new GKE metadata service while passing in SA details.
* [Specifying an IAM Role for your Service Account ](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html)
  * Mutating webhook injects token file and env vars to refer to the file.
* [Azure Pod Identity](https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity#use-pod-identities) , actual [how-to](https://github.com/Azure/aad-pod-identity)
  * Intercepts all calls to Azure services.

### How could Crossplane help solve your problem?

There is an implementation in AWS Provider that lets provider-aws pod to assume a role in the EKS cluster. However, since it's authorizing the provider-aws pod itself, we can't have more than one `ServiceAccount` in one cluster as discussed [here](https://github.com/crossplane/provider-aws/pull/126#issuecomment-583312232).

What we'd like to have is a one-pager that describes how we can approach this auth mechanism in general and implement it for each provider. The following options seem viable:
* Create a pod per `Provider` object with the annotated service account that will be used as identity service. The actual stack pod will request the identity token in `Connect` and then will make a request to the cloud API with that token.
  * Instead of fetching `Secret`, we'll make a HTTPS request. It's possible to make this secure by using `mTLS` but I feel hesitant as we will always think about making it really secure as opposed to today where we just say `limit access to secrets with RBAC if you don't want to leak your creds to 3rd parties`.
* Create a `DaemonSet` to intercept the actual calls to metadata services and change the payload to point to the right `ServiceAccount`.
  * Let's just not do this and implement craziness for each platform.
* An actual stack `Deployment` per `Provider` that uses service account. There will be N `Deployment`s of cloud provider stack but each will filter the managed resources they reconcile by a label like `crossplane.io/provider-name`. So, each stack `Pod` will have the right `ServiceAccount` and will reconcile only the resources that have the right label for that `Provider`
  * I feel like this is the most plausible one between all. We don't do intercepts, identity server and all that. We essentially play by the books and let the actual `Pod` with identity make the requests. This is also easier than others since it's a higher level mechanism that relies on whatever the cloud provider provides as interface to their workload identity mechanism. It'll require a bit of machinery on our side but it should be doable.

**Comment by muvaf** [comment]
@hasheddan do you think we can close this?

**Comment by hasheddan** [comment]
@muvaf yep! I think this should be tracked on a per-provider basis :+1:
