### ISSUE TITLE
Allow Stack, StackInstall, StackDefinition to be backed up and restored

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1389]
### What problem are you facing?

Client-side backup and restore tools for Kubernetes, such as a Velero, typically recreate resources on restore.  The UID of these resources will differ from the original because UID is ignored on resource creation.

The StackManager and the resources it creates are not prepared to handle a change of UIDs in the resources that the StackManager creates and otherwise manages.

A mismatched UID could result in garbage collection by Kubernetes, or deletion (or other forms of disconnect) by the Stack Manager.

### How could Crossplane help solve your problem?

The stack manager moved away from owner references (which demand UID) for many of the object references, but UIDs are used in some of the label based approaches.  In some of the places where a OwnerReference (with UID) is used, we'll have to decide what action to take. The loss of an install job should not be a problem if the stack is fully installed.  We may want to clean those jobs up sooner ourselves.  The loss of a Deployment should be auto-recovered as an 'update' reconcile operation (but isn't), so we should make the stack-manager capable of handling that situation (and ignoring the UID for comparisons - possibly throwing the UID out or keeping the UID updated).

Since 0.8, CRDs installed from the stack manager should be immune to this, but restored Stack resources may be orphaned when their StackInstall is removed (because a UID in the parent labels is used for matching).

The ClusterRoles, ServiceAccounts, Roles, ClusterRoleBindings, and RoleBindings may also be lost on restore (check these).￼

Related to #1042, #1151

**Comment by negz** [comment]
@displague FWIW I haven't yet tested backup and restore of StackInstalls. I confirmed that Velero backs up owner references and resource statuses, but removes them during the restore phase. So owner references are gone, not mismatching as I originally thought.

The approach I've been taking is to remove UIDs from most references and instead reference only by (some subset of) GVK, name, and namespace. This isn't possible for controller references, which require a UID. In their case I've been following the pattern put forth by the controller ref design doc, and having my controllers "adopt" any orphaned (i.e. controller-ref-less) resources that they find.

https://github.com/kubernetes/community/blob/7d2ebad4/contributors/design-proposals/api-machinery/controller-ref.md#behavior

**Comment by prasek** [comment]
@displague is there a simple fix here we can get in by EOD today or early tomorrow AM so we can start using a newer Crossplane rc version on dev to test the stacks/packages that are being cut later today / tomorrow morning so we can test this as part of UbC v0.7?

**Comment by displague** [comment]
@prasek I can swing at it with https://github.com/crossplane/crossplane/pull/1407, but there are unknowns here.  

I'll start by fixing the things that I know will fail with a loss of UIDs (as considered in the PR description).  The definition of 'fix' here means making things more backup and restore tolerant while introducing different behaviors for other edge cases, hopefully justified and supported by the controller reference doc.

The loss of controller / owner references adds an unexpected complexity to the problem.

I don't like my chances of having this ready by tomorrow's stand-up, but I will have a better understanding by then.  I would like to give Velero a spin and perform similar backup/restore experiments to those Nic attempted.

**Comment by negz** [comment]
FWIW during my travels today I've stackinstalled myself a `stack-azure-sample`, and an `app-wordpress`, backed everything up with Velero, recreated my minikube, and restored. Nothing obviously and immediately broke as far as I can tell with regard to Stacks; Velero happily restored the templating controller deployments and things kept plugging along.

**Comment by displague** [comment]
I think in a full backup and restore, stack uninstall is where we will find pieces orphaned.
I'm running this scenario now.

---
I've also observed that a namespace level backup can not be supported because the CRDs that are stored by Velero in a namespace inclusive backup are only those in use. If a StackInstall installed CRDs that were not in use I think you will find these lost on restore.

`velero backup create crossplane-backup --include-namespaces crossplane-system,user-namespace`

For namespace inclusive backups, I think one solution to this would be to have the StackInstall controller take an 'update' reconcile path that compares CRDs stashed in a ConfigMap (which would be included in a Velero namespace level backup) to the installed CRDs and recreates (and relabels) these resources if they are missing, which would also help https://github.com/crossplane/crossplane/issues/1402.

**Comment by displague** [comment]
I've confirmed the stackinstall delete scenario leaves orphaned stacks.
The installjob seems to have been cleaned up correctly.

Deleting stacks (and stackdefinitions) by hand then orphans deployments, clusterroles, and rolebindings/clusterrolebindings.

Because the stackinstall resource was already removed, the CRDs are orphaned because the stack was never deleted which would have released its shared parentage label.

**Comment by displague** [comment]
I would have thought that most of these problems would be remedied with https://github.com/crossplane/crossplane/pull/1407, which removes UID from the parent labels but I'm now seeing that the StackInstall `finalizer` is not being restored with the resource.

I would expect that the stackinstall controller would re-add this on restore (create), but that isn't happening either.

**Comment by jbw976** [comment]
Thanks for the investigations and information @displague and @negz.  So it looks like the Stacks still seem "functional" after a backup/restore, e.g. the installed stack is still performing its job and its managed resources are accessible and healthy.  The only issue is that we can no longer garbage collect fully, so their resources will get orphaned and not cleaned up without manual intervention.

I am OK with that deficiency *for now*.  I recommend that we do not try to put in a last minute fix to remove UIDs from stack manager given that there are unknowns and risk of unexpected regressions in other functionality.  I do not want to take on that risk given that the backup/restore will result in a "functional" deployment that only requires manual cleanup.

**Comment by displague** [comment]
With regard to limited namespace backups, @nrb suggested:

> You could use `--include-cluster-resources` to capture them in that case, but that gets all cluster resources, which may or may not be too much. `--include-resources` could get all CRDs, but it would get only the CRDs.

And for a Crossplane or `StackInstall` specific set of backup plans, we could create a BackupAction plugin https://velero.io/docs/master/custom-plugins/#plugin-kinds.  Examples of some of the builtin plugins are here: https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/server/plugin/plugin.go#L38-L41.  A plugin could, for example, instruct Velero that that backup of a Stack resource should result in all owned and dependent CRDs being archived.

**Comment by nrb** [comment]
If anyone has questions on the plugin model, feel free to come to our community meetings. You can see more info [on our community page](https://velero.io/community/).

**Comment by hasheddan** [comment]
Thanks for letting us know @nrb :)
