### ISSUE TITLE
Remove golangci.com integration

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1411]
Unfortunately, it looks like golangci.com is shutting down its service on April 15th.  More details are available in this blog post: https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e

We should remove our integrations with golangci.com from our builds/PRs across all repos.

**Comment by negz** [comment]
We already run golangci-lint as part of our Jenkins build, so all the golangci Github integration does for us is provide a nice bot with comments and suggestions when there are linter errors. I've asked them if we can self-host such a bot per https://github.com/golangci/golangci/issues/53, but have no response just yet. We could consider switching to something like https://github.com/reviewdog/reviewdog or back to https://github.com/jenkinsci/violation-comments-to-github-plugin to replicate this functionality.

**Comment by negz** [comment]
We've removed this. I'd like to look into replacing it with Reviewdog, but I'll roll that into https://github.com/crossplane/crossplane/issues/1583.
