### ISSUE TITLE
Implement ApplicationDefinition and its reconciler

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1420]
### What problem are you facing?

Implementing #1163

### How could Crossplane help solve your problem?

* Implement ApplicationDefinition type
* Adopt common reconciler to cover ApplicationDefinition

**Comment by negz** [comment]
We're no longer planning to work on ApplicationDefinition any time soon.

**Comment by muvaf** [comment]
@negz Do you think we should update the composition design to remove `ApplicationDefinition`? Or maybe we can do that after renaming discussions are over.
