### ISSUE TITLE
[Data model] several owner references are not set properly

### ISSUE THREAD

**Issue by resouer** [crossplane/crossplane#1423]
Sample app comes from https://github.com/oam-dev/crossplane-oam-sample

```
kubectl tree applicationconfiguration.core.oam.dev example-appconfig
NAMESPACE  NAME                                                                READY  REASON              AGE
default    ApplicationConfiguration/example-appconfig                          -                          50s
default    ├─ContainerizedWorkload/example-appconfig-workload                  -                          49s
default    │ ├─Deployment/example-appconfig-workload-deployment                -                          31s
default    │ │ └─ReplicaSet/example-appconfig-workload-deployment-5c58cc9b54   -                          31s
default    │ │   ├─Pod/example-appconfig-workload-deployment-5c58cc9b54-5h5b2  True                       31s
default    │ │   ├─Pod/example-appconfig-workload-deployment-5c58cc9b54-6kvwd  False  ContainersNotReady  1s
default    │ │   └─Pod/example-appconfig-workload-deployment-5c58cc9b54-dx2nx  False  ContainersNotReady  1s
default    │ └─Service/example-appconfig-workload-deployment-service           -                          31s
default    └─ManualScalerTrait/example-appconfig-trait                         -                          49s
default      └─Deployment/example-appconfig-workload-deployment                -                          31s
default        └─ReplicaSet/example-appconfig-workload-deployment-5c58cc9b54   -                          31s
default          ├─Pod/example-appconfig-workload-deployment-5c58cc9b54-5h5b2  True                       31s
default          ├─Pod/example-appconfig-workload-deployment-5c58cc9b54-6kvwd  False  ContainersNotReady  1s
default          └─Pod/example-appconfig-workload-deployment-5c58cc9b54-dx2nx  False  ContainersNotReady  1s
```
1. Component is missing. Seems its owner reference is not set properly.
2. Trait owns deployment. This link should already be recorded by `workloadRef`, seems we don't need to set owner reference on deployment? Also, I think Trait could be owned by Component.
3. I'd suggest Workload always share the same name with Component.

/cc @ryanzhang-oss @negz @wonderflow correct me if I made mistake,

**Comment by negz** [comment]
1. Is intentional. The `kind: ApplicationConfiguration` does not own the `kind: Component`.
2. This doesn't fit with my mental model of what a `kind: Component` is.
3. That's not possible. There is a one-to-many `kind: Component`-to-workload relationship.

**Comment by resouer** [comment]
@negz If I understand correctly, I think you mean another `ApplicationConfiguration`  could reference existing `Component` and create different `Workload` CR. So in this mental model, `kind: Component` is a workload generator/template (model 1).

The alternative is `Component` is the 1:1 envelope of `Workload` to carry extra fields such as `parameters`. This makes implementation simpler to address `Workload` CR by given `Component` name (model 2).

I am not sure why do we want to go with model 1? i.e. what's benefit to share a `Component` object?

**Comment by vturecek** [comment]
Component is distinct from a component _instance_. The ApplicationConfiguration doesn't own the component, it owns an instantiation of the component, which is represented by a workload type. So that part seems right in the tree.

Similarly, a Component doesn't own a trait, but a component _instance_ does (or rather, a trait belongs to a specific component instance). The tree shows the ApplicationConfiguration is the direct parent of the manual scaler trait, but shouldn't parent of the trait be the ContainerizedWorkload to which the trait is applied?

**Comment by resouer** [comment]
> Component is distinct from a component instance

@vturecek For ownership issue, I believe we are in same picture. It's totally OK for me to let AppConfig to own Workload instead of Component. While for the `Component` part, there seems a gap.

Are you also suggesting that Component has 1:N mapping with Workload? i.e. it's a practice to reference same Component in different AppConfig? My opinion is we should not encourage that, it's problematic in large scale deploy.

**Comment by resouer** [comment]
A summary for current discussion to make sure everyone in the same pic:

- [x] AppConfig owns Workload instead of Component - all agree
- [ ] Workload owns Trait instead of the other way around - Lei, Vac agree
- [ ] Component Workload 1:1 mapping - proposed by Lei

**Comment by negz** [comment]
>  Component Workload 1:1 mapping - proposed by Lei

I don't think we should try to resolve this in this issue. Today in the spec and the implementation a `kind: Component` is a template used by many `kind: ApplicationConfiguration` to produce many workloads. Presumably changing that would require fairly fundamental changes to the spec, which seems like it warrants its own design issue.

**Comment by negz** [comment]
> Workload owns Trait instead of the other way around

The `kubectl tree` you posted does not know a workload owning a trait. It shows both the workload and the trait owning the output of the workload; the `kind: Deployment` and `kind: Service`. This feels appropriate to me because both the workload (`kind: ContainerizedWorkload`) and the trait (`kind: ManualScalerTrait`) orchestrate the `kind: Deployment` and `kind: Service`.

**Comment by resouer** [comment]
> Today in the spec and the implementation a kind: Component is a template used by many kind: ApplicationConfiguration

I am not sure where this implication comes from? and why fairly fundamental change is needed?

> The kubectl tree you posted does not know a workload owning a trait, or a trait owning a workload

Can we just set owner of Trait to corresponding Workload CR it applies to?

**Comment by resouer** [comment]
I see, it should because the assumption that `Component` in still considered as immutable in v1alpha2, xref: https://github.com/oam-dev/spec/pull/343

Can we open it up and allow developers to modify `Component`? In that case `Component` is an instance instead of "template", and 1:1 mapping to `Workload` CR.

**Comment by resouer** [comment]
@vturecek Yes I can understand the mental model you are describing. Though I don't think it's necessary in v1alpha2 spec and will cause confusion by sharing Component obj across AppConfigs, I will raise a discussion in oam side.

**Comment by wonderflow** [comment]
> If Component is an instance instead of a template, then the only way to produce a new version of a component is to produce a whole new component with a unique name. I would think this would make it more difficult to coordinate upgrade scenarios.

Not like that. Let's use K8s `deployment` as an example, `deployment` is an instance when it was deployed, but there are Controller Revisions created behind it. We could use controller revision to do rollback for `deployment`. So there's the same case for OAM Component upgrade scenarios when we treat Component as instance.  OAM implementation can record Component revision when Component is updated.

**Comment by negz** [comment]
As far as I can tell, Crossplane is setting sensible owner references according to the v1alpha1 OAM spec. This issue seems to have mostly diverged to discussing _changing_ the spec (i.e. to introduce "component instances" rather than ensuring Crossplane is compliant with the spec. I suggest we close this issue and track any potential improvements to the spec upstream.

**Comment by resouer** [comment]
Yes, please feel free to follow up on the mutable Component discussion: https://github.com/oam-dev/spec/issues/350
