### ISSUE TITLE
Add an entry point in README along with some documentation for OAM users

### ISSUE THREAD

**Issue by wonderflow** [crossplane/crossplane#1430]
Now we already have implemented OAM controller in Crossplane, in fact crossplane is an OAM implementation. But we can't find anything about OAM in README.

I suggest:

1. Add an entry point for OAM user in README, which can refer to some demo documentation.
2. Add `demo` / `get started` documentation for OAM app.

**Comment by negz** [comment]
We've removed OAM support from Crossplane and we recommend folks check out KubeVela instead. :)
