### ISSUE TITLE
install.yaml allows a full Deployment spec to be declared which can be problematic

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1441]
### What problem are you facing?

Currently, stack packages allow the author to specify an entire `Deployment` within their `install.yaml` file.  This is helpful for flexibility for the author to customize and provide additional configuration for their stack controller, but presents some security and reliability concerns, first described by @turkenh here: https://github.com/crossplane/crossplane/issues/1317#issuecomment-593832706

Perhaps we can limit the amount of config that authors can provide for their controller. @lukeweber suggests:

>  seems like we shouldn't allow people to set more than image, args, env, readiness probe, liveness probe

**Comment by negz** [comment]
This is no longer the case now that the OG package manager has been removed. We now have the opposite problem (temporarily), in that you can't. influence how a provider is run at all. :)
