### ISSUE TITLE
Enforced composition ref on the definition

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1470]
### What problem are you facing?

Currently, there is no way to enforce a specific `Composition` resource for the instances of `InfrastructureDefinition`. Without this, the permission of creation an instance of the definition (`MySQLRequirement` or `MySQL`) is a vague one since the referenced `Composition` could include anything.

### How could Crossplane help solve your problem?

Optionally, make it possible to refer to a `Composition` in the `InfrastructureDefinition` so that the resulting resources of instantiation of a composition are always known and RBAC permission of that instantiation resources can be given to a `ServiceAccount` with known limits.

**Comment by negz** [comment]
@muvaf Could you make sure the documentation reflects this new functionality?

**Comment by muvaf** [comment]
@negz done in https://github.com/crossplane/crossplane/pull/1607
