### ISSUE TITLE
Allow specifying a default composition in definition

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1471]
### What problem are you facing?

There is no way to mark a `Composition` as default of a given `InfrastructureDefinition`.

### How could Crossplane help solve your problem?

Enable users to specify a `Composition` as the default on the `InfrastructureDefinition` resource.

**Comment by negz** [comment]
@muvaf Could you make sure the documentation reflects this new functionality?

**Comment by muvaf** [comment]
@negz done in https://github.com/crossplane/crossplane/pull/1607
