### ISSUE TITLE
Unit tests for composite resource claim package

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1473]
### What problem are you facing?

Unit tests for definition and requirement packages are missing.

### How could Crossplane help solve your problem?

Implement those tests.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/pull/1970 adds tests for the claim (neé requirement) package. Tests for the definition package (which now includes the old publication package) were added a while back in https://github.com/crossplane/crossplane/pull/1588.
