### ISSUE TITLE
Deprecate resource claims and classes

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1479]
Ship Crossplane with a default set of `InfrastructureDefinition`s that will replace today's claims.

**Comment by resouer** [comment]
Do we have concrete plan or guide on this deprecation?

There some apps in the wild also need upgrade, for example: https://github.com/oam-dev/samples/tree/master/2.ServiceTracker_App

**Comment by muvaf** [comment]
We are shipping a set of commonly used `InfrastructureDefinition`s that will replace today's claims: https://github.com/crossplane/crossplane/tree/master/cluster/composition/definitions

Although they are not installed automatically in v0.11, they can be installed manually.

But we don't have a clear-cut release that will remove the claims from the codebase. I believe we'll keep the support for at least 2-3 releases.

**Comment by hasheddan** [comment]
Just noting here that the "auto target" controller should also be removed as part of this effort:https://github.com/crossplane/crossplane/blob/7d1ce57e4aff97bf17e13883b58c9be7fd53a5f7/pkg/controller/workload/kubernetes/target/target.go#L58

**Comment by negz** [comment]
I'm repurposing this existing issue to cover deprecating all resource claims and classes. Note that v1beta1 resource classes (e.g. `GKEClusterClass`) are in scope for this deprecation.
