### ISSUE TITLE
official chart release should include OAM workload/trait controllers

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/crossplane#1483]
Currently the chart release include only the *AppConfig* controller, but not OAM workload/traits.
If users want to deploy OAM apps, they need to do additional [cumbersome steps](https://github.com/crossplane/addon-oam-kubernetes-local#getting-started):

```
git clone git@github.com:crossplane/addon-oam-kubernetes-local.git

kubectl create namespace oam-system

helm install controller -n oam-system ./charts/oam-core-resources/ 
```

As discussed previously, we want to have the workload/trait controllers in the chart release too. This issue is created to discuss details and track progress.

**Comment by hongchaodeng** [comment]
cc @negz @hasheddan @ryanzhang-oss @resouer @wonderflow @artursouza

**Comment by resouer** [comment]
Yes, similar discussion was brought up in slack channel. 

Today, we have multiple entries to install Crossplane with OAM core controllers (addon-local/remote), it's painful to re-direct users across different orgs/repos.

We have:

1. https://github.com/oam-dev/crossplane-oam-sample
    1. this one is basically a one-line `helm install`, very simple
    2. as mentioned in its README, it's a temporary guidance and designed to be merged into crossplane org ASAP. But for now it seems nowhere to put in.
2. https://github.com/crossplane/addon-oam-kubernetes-local#getting-started
    1. this one is a "start from source code" version of (1), includes 3 steps of helm install.
3. https://github.com/crossplane/stack-oam
    1. this one is Stack based installation guide, while seems Crossplane and addon-local/remote still need to be installed by helm?

Ideally, it would be great to include addon-local/remote in Crossplane helm charts so the installation will be as simple as:

```
helm install --name crossplane --namespace crossplane-system crossplane-alpha/crossplane --set addon=local
```

**Comment by wonderflow** [comment]
I'm working on this, my plan is:
1. clean up charts files of [addon-oam-kubernetes-local](https://github.com/crossplane/addon-oam-kubernetes-local/pull/23)
2. make addon-oam-kubernetes-local as a sub module of crossplane
3. add helm charts files of addon-oam-kubernetes-local  to crossplane charts.
4. add charts for [addon-oam-kubernetes-remote](https://github.com/crossplane/addon-oam-kubernetes-remote) in crossplane repo.
5. make `addon-oam-kubernetes-local` and `addon-oam-kubernetes-remote` configurable by using helm values, `addon-oam-kubernetes-local` as default.

What about your ideas?

@negz  @hongchaodeng @resouer @ryanzhang-oss

**Comment by negz** [comment]
Per https://github.com/crossplane/oam-kubernetes-runtime/issues/55 we're planning to modularise this, so OAM controllers will be installable without the core Crossplane controllers and vice versa as distinct Helm charts.
