### ISSUE TITLE
Crossplane resources generated from Terraform modules

### ISSUE THREAD

**Issue by resouer** [crossplane/crossplane#1488]
### What problem are you facing?

There are 3036+ [Terraform modules]( https://registry.terraform.io/browse/modules)  today, and it will be great if Crossplane can leverage it automatically as underlying cloud resource provider.

### How could Crossplane help solve your problem?

I assume https://github.com/crossplane/crossplane/pull/1453 (i.e. code gen) could help solve the issue? And the user experience in my mind would be similar to Kubeform.

It will be a good start to on-board users, and building abstractions can be the follow up step.

**Comment by jbw976** [comment]
@resouer is this different from #262?

**Comment by resouer** [comment]
@jbw976 Seems very related, I will move discussion there.
