### ISSUE TITLE
Add support for Uniform Resource Connectivity

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#149]
We would like to maintain a generic approach when it comes down to connections to the managed resource. The challenge is that different cloud providers manage and secure resource access in different ways. 

For example RDS vs. CloudSQL resource
- RDS: security groups (for resources) and security group (w/ IP whitelisting)
- CloudSQL: authorized networks (for different networks w/in the project), authorized networks (w/ IP whitelisting), and cloudsql-proxy.

We need to come up with a "common denominator" for resource connectivity - per resource type (Mysql, Redis, etc), which allow client applications to consume (establish) resource connectivity in a **uniform** way to provide workload portability.

**Comment by prasek** [comment]
@negz @jbw976 will #149 and #115 be handled as part of #615 #616 #617

**Comment by negz** [comment]
@prasek No, those issues are related but separate.

This issue is discussing a _uniform_ way to connect to resources, which we do not yet have. #115 is more closely related to my resource usage one pager than our network connectivity work.

**Comment by negz** [comment]
We're not as focused on portability as we once were, though we do still support defining portable APIs. I'm going to close this - we may need to address it but I'd like to hear that from our community to help prioritise it.
