### ISSUE TITLE
Validate fieldpaths in the compositions

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1497]
### What problem are you facing?

In `Composition`, there are `patches` where you define `fromFieldPath`s and `toFieldPath`s. If there is a typo there, no error is propagated to user.

### How could Crossplane help solve your problem?

Crossplane actually knows the schema of both `to` and `from` resources since they are registered in the api-server. So, it'd be cool to reject or at least print error in the conditions.

**Comment by wonderflow** [comment]
Do we have an [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) to do this kind of validation?

**Comment by negz** [comment]
I'm going to dedupe this into https://github.com/crossplane/crossplane/issues/1476, as a general issue for validating compositions.
