### ISSUE TITLE
keep count of how many instances of the Class are created

### ISSUE THREAD

**Issue by arturrez** [crossplane/crossplane#1505]
### What problem are you facing?
I am trying to implement something similar to  https://www.terraform.io/docs/configuration/functions/cidrsubnet.html  
in regards to `GKECluster` to control `spec.forProvider.privateClusterConfig.masterIpv4CidrBlock`
This IP range has to be unique in the scope of VPC, so I need to keep a count of `GKEClusters` created using `GKEClusterClass` so I can divide and allocate ip range, for example http://jodies.de/ipcalc?host=192.168.0.1&mask1=24&mask2=28,  for every `GKECluster` provisioned using `GKEClusterClass`

### How could Crossplane help solve your problem?
keep count of instances of the class created and expose this information via some derictive similat to machinery `count.index` in terraform

**Comment by negz** [comment]
We don't have classes anymore - I suspect the use case called out in this issue is still valid though and would be approached by https://github.com/crossplane/crossplane/pull/1705.
