### ISSUE TITLE
Composite and Requirement resources lack printer columns

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1520]
### What problem are you facing?

Composite and Requirement resources lack printer columns.

### How could Crossplane help solve your problem?

We can implement some for better UX.

**Comment by prasek** [comment]
by default, should we be showing Ready: False and maybe the reason in the printer columns for:
`kubectl get mysqlinstancerequirement.database.example.org my-db`

Currently all I see is:
![image](https://user-images.githubusercontent.com/284840/82156566-9abab180-9830-11ea-94b0-29fc745b46e7.png)

also, is `bindingPhase: Bound` going away for the requirements?

maybe also the composition name, like we did for class name?
```
NAME                  STATUS   CLASS-KIND              CLASS-NAME                                  
my-cool-app-sql       Bound    CloudSQLInstanceClass   my-cool-stack-cloudsqlinstanceclass-mysql
```

**Comment by muvaf** [comment]
@prasek in the PR, composite resource has `READY`, `SYNCED` and `COMPOSITION` columns while requirement has `READY`, `SYNCED` and `CONNECTION-SECRET`. I was thinking of adding the name of the composite resource as column in requirement but it's not much useful since you can't query it without its kind. Connection secret sounded more useful at that consumption level.

> also, is bindingPhase: Bound going away for the requirements?

Yes.
