### ISSUE TITLE
The Provider "alibaba-provider" is invalid: spec.region: Required value

### ISSUE THREAD

**Issue by zzxwill** [crossplane/crossplane#1558]
### What happened?

Followed [install-configure](https://crossplane.io/docs/v0.11/getting-started/install-configure.html) to configure Alibaba Provider, it failed.
```
error: the server doesn't have a resource type "region"
```

### What environment did it happen in?
Crossplane version:

**Comment by zzxwill** [comment]
Per the Provider specification https://github.com/crossplane/provider-alibaba/blob/master/apis/v1alpha1/types.go#L30, the sample provider.yaml needs to be revised.

**Comment by hasheddan** [comment]
I believe you have fixed this in #1560 and it has been cherry picked in #1565 :+1:
