### ISSUE TITLE
Support serving multiple versions of a CR consecutively

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1584]
### What problem are you facing?

All of Crossplane's resources are Kubernetes custom resources, defined by CRDs. Custom resources are versioned (e.g. v1alpha1, v1beta1, etc). [Backward incompatible](https://github.com/kubernetes/community/blob/c64e24/contributors/devel/sig-architecture/api_changes.md) changes may not be made to a v1beta1 or above resource - they must be introduced as a new version of the same API resource. Kubernetes serves all extant versions of a defined custom resource simultaneously. One served version is blessed as the "storage" version - all other served versions must be converted to and from this storage version using a webhook.

* https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/
* https://book.kubebuilder.io/multiversion-tutorial/tutorial.html

Crossplane does not currently have an established pattern for writing, configuring, and serving conversion webhooks. This will likely become a problem if and when we need to make a breaking change to a v1beta1 custom resource.

### How could Crossplane help solve your problem?

Crossplane could establish a pattern for serving multiple versions of the same custom resource.

**Comment by muvaf** [comment]
It seems this depends on https://github.com/crossplane/crossplane/issues/1152 like many other features we'd like to implement.

**Comment by muvaf** [comment]
The [versioning approach](https://github.com/Azure/k8s-infra/blob/c4b4b811eb9da799bcc281824dd3699bb6dbdf12/hack/generator/spec/versioning.md) in ASO is worth digging. The storage version has all fields that ever came and go but it's never the served version, i.e. only a hub for conversion between various versions.

**Comment by muvaf** [comment]
This is now possible with conversion webhooks capabilities introduced by https://github.com/crossplane/crossplane/pull/2919
