### ISSUE TITLE
Move provider-template to Crossplane Org

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1599]
### What problem are you facing?

A number of users have shown interest in adding support for new Providers, but it can be difficult to get started. Generally advice amounts to "copy from existing providers", but I have been directing a few folks to https://github.com/crossplanebook/provider-template. It is a lightweight template for getting a Provider started, and it cuts down on some of the complexity in the build systems of current Providers maintained by the Crossplane org.

### How could Crossplane help solve your problem?

Folks may be more inclined to use `provider-template` if it were part of the Crossplane org. It would also encourage better maintenance as we strive to keep all repos in the Crossplane org up to date with later versions. It is possible that it could be duplicative with some of the Crossplane CLI functionality in the future, but I do not think they are mutually exclusive and we could always archive the `provider-template` in the future if we feel it is confusing / extraneous.

/cc @negz @muvaf @jbw976

**Comment by muvaf** [comment]
It doesn't have the upbound/build submodule which has very useful make targets like `make reviewable`. Do you think that should be integrated as well?

**Comment by hasheddan** [comment]
@muvaf from folks I have talked to, it is actually easier to get started without the `build` submodule. I definitely think that in a production setting that we should be doing the same checks that the `build` submodule provides, but for folks just starting a new provider not having the `build` submodule means that they can use whatever CI they like and add any checks without having to understand what is provided in `build`. If the provider was to eventually be supported by the Crossplane org, we could always incorporate the `build` submodule later.

**Comment by negz** [comment]
provider-template has lived in the crossplane org for a while now.
