### ISSUE TITLE
Decomposition for higher level abstractions

### ISSUE THREAD

**Issue by resouer** [crossplane/crossplane#1601]
### What problem are you facing?

So today, we have Composition to create higher level abstraction (i.e. a simpler version of original data). The idea is: 

```
{CRD 1, CRD 2, CRD 3} -> {a simpler CRD} (composed from 1,2,3)
```

This pattern actually applies to the other direction: 

```
{a complicated CRD} -> {simpler CRD 1, simpler CRD 2, simpler CRD 3} (decomposed from original one)
```

The second use cases exists widely in creating abstractions with separated concerns. For example, for a given [OpenKruise CRD](https://github.com/openkruise/kruise/blob/master/docs/concepts/cloneset/README.md#update-sequence), we can generate a `ContainerizedWorkload` and a `UpdateStrategyTrait`. We can even go step further:
```
ContainerizedWorkload + RollingUpdateStrategyTrait = Deployment
ContainerizedWorkload + InPlaceUpdateStrategyTrait = OpenKruise
```
/cc @wonderflow who is working on this.
### How could Crossplane help solve your problem?

Composition and Decomposition.

**Comment by muvaf** [comment]
This sounds interesting. Technically, the new CRDs would be used for `Patch` operations but they would have a schema for validation which can limit what they do as opposed to raw patch. Since it's on CRD level, RBAC could be applied. I guess OAM can be modeled like this to some extent, right?

**Comment by wonderflow** [comment]
@muvaf  Yes, they are exactly `Patch` on technical. Besides `RBAC` and `validation` benefits, user can also write custom operator to generate Patch for different scenarios, in another word we can reduce complex patch to simple CRD for end user.

**Comment by negz** [comment]
We haven't seen much demand for this functionality, so I am going to close this.
