### ISSUE TITLE
Kubernetes Application cannot schedule to the types defined via InfrastructureDefinition

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1605]
### What problem are you facing?

Kubernetes Application cannot schedule to the types defined via InfrastructureDefinition. This is required for [Wordpress](https://github.com/crossplane/app-wordpress) app to work with composition.

### How could Crossplane help solve your problem?

Allow `KubernetesApplication` or `KubernetesApplicationResource` to accept a secret to connect to the target cluster.

**Comment by negz** [comment]
I'm assuming we'll remove support for `KubernetesApplication` when we remove support for claims (around 0.14) - thus breaking support for the Wordpress app as it exists today.

**Comment by negz** [comment]
Per my previous comment, I believe we'll remove KubernetesApplication so I'm going to close this.
