### ISSUE TITLE
KubernetesApplicationResource should not submit resource if the additional secret is not ready

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1611]
### What happened?

If you create a `KubernetesApplicationResource` whose template is of kind `Deployment` that has a secret and you'd like that secret to be propagated to the target cluster, you'll see that the `Deployment` will be created in the target immediately even if the additional secret you supplied via `KubernetesApplicationResource.secrets` doesn't exist yet.

This causes unnecessary errors if that secret is mounted to that `Deployment` in the target cluster, which is the main use case of that field. I believe it should wait until the secret can be found and create secrets+template together at the same time to avoid that unnecessary backoff.

### How can we reproduce it?

Create a `KubernetesApplicationResource` with `Deployment` template which mount the secret that's given in `KubernetesApplicationResource.spec.secrets`

### What environment did it happen in?
Crossplane version: 0.12

**Comment by zzxwill** [comment]
FYI, here is a design from @hongchaodeng for this similar service dependency mechanism in OAM https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/resource-dependency.md

**Comment by negz** [comment]
I'd prefer to avoid doing this work given that our goal is to remove these controllers. Please reopen if you think we need to do this as an interim solution while we still support KubeApp.
