### ISSUE TITLE
Crossplane should grant permission to reconcile new types introduced via InfrastructureDefinition

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1619]
### What problem are you facing?

Today, if you create an `InfrastructureDefinition` a new CRD will be created and its instances will be reconciled by Crossplane pod. However, since it's a new API, Crossplane pod needs a `ClusterRole` to reconcile that API. In documentation, we have [a step](https://github.com/crossplane/crossplane/blob/master/docs/getting-started/publish-infrastructure.md#grant-rbac-permissions) to manually create that known `ClusterRole`. However, I think it's safe to assume that Crossplane should be able to reconcile the new API right away without explicit role grant.

### How could Crossplane help solve your problem?

Crossplane `InfrastructureDefinition` controller can create a `ClusterRole` to grant permission to reconcile this new CRD and bind it to Crossplane pod's `ServiceAccount`. It sounds a bit too much for an entity to create a `ClusterRole` and grant it to itself but in this case, it's a well-defined and known `ClusterRole`.

If Crossplane didn't have any `ClusterRole` and `ClusterRoleBinding` creation permissions, then it wouldn't be worth to ask users to grant that creation permissions to Crossplane; but it already has them because of package manager.

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/1728
