### ISSUE TITLE
Accelerate Provider Coverage

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1626]
### What problem are you facing?

Crossplane currently supports tens of managed resources - Kubernetes custom resources that correspond to cloud provider APIs. We'd like to accelerate our ability to support new managed resources, with a goal of supporting approximately 1,000 managed resources across AWS, Azure, and GCP.

### How could Crossplane help solve your problem?

Crossplane could make it possible to completely, or failing that partially, generate managed resource types and code. We're currently approaching this on two fronts:

* Wrapping Terraform providers.
* Generating the boilerplate parts of 'native' Crossplane managed resources.

We suspect wrapping Terraform providers will result in useful but imperfect managed resources, and thus we see this approach as a good way to bootstrap our ecosystem. We'll most likely continue to invest in making it easier to build 'native' Crossplane managed resources for the most popular APIs, or APIs where we find that wrapping Terraform is a poor fit.

**Comment by negz** [comment]
Related issues:

* https://github.com/crossplane/crossplane/issues/1623 - Analyze possible integration with Terraform based providers.
* https://github.com/crossplane/crossplane/issues/1624 - Design doc for generating Terraform based providers.

Note that the 'analysis' is mostly around determining what existing functionality would change if we wrapped Terraform. This is separate from the larger design because we want to communicate the impact of this decision without blocking on a full design.

**Comment by negz** [comment]
@kasey I think a few existing issues are ripe for deduplication here. Namely https://github.com/crossplane/crossplane/issues/262, https://github.com/crossplane/crossplane/issues/1426, and https://github.com/crossplane/crossplane/issues/843. Can you do the needful?

**Comment by muvaf** [comment]
https://github.com/crossplane/crossplane/issues/1602 is a work item for easier managed resource implementation.
