### ISSUE TITLE
v1beta1 or better support for Composition

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1629]
### What problem are you facing?

We've deprecated support for resource claims and classes in Crossplane in favour of what we usually call '[Composition](https://crossplane.io/docs/v0.12/getting-started/publish-infrastructure.html)' - the ability to define, compose, and publish your own infrastructure APIs with Crossplane. This feature is currently a v1alpha1 API. We've found it has resonated with our users, so we'd like to get it to v1beta1 (or even v1) so that they can depend on it.

### How could Crossplane help solve your problem?

Primarily we'll need an API that is close to or at what we'd be comfortable as a v1 for Composition. This means that we'll need an API we're comfortable growing (by introducing new resources), or making backward compatible changes to, but not making sweeping changes to. This API will need to be useful for folks.

**Comment by negz** [comment]
Issues that could be in scope for this push include:

* https://github.com/crossplane/crossplane/issues/1612 - Don't delete a composite resource until all composed resources are gone.
* https://github.com/crossplane/crossplane/issues/1619 - Automatically grant Crossplane RBAC access to newly defined APIs.
* https://github.com/crossplane/crossplane/issues/1615 - Consider merging InfraDefinition and InfraPublication
* https://github.com/crossplane/crossplane/issues/1610 - Make it possible to package InfraDefinitions
* https://github.com/crossplane/crossplane/issues/1609 - Allow the fields of composed resources to be exposed as connection secret fields of the composite resource.
* https://github.com/crossplane/crossplane/issues/1603 - Allow a composed resource to reference the field of another composed resource.
* https://github.com/crossplane/crossplane/issues/1476 - Validation of Compositions.
* https://github.com/crossplane/crossplane/issues/1477 - Prevent RBAC privilege escalation via compositions.
* https://github.com/crossplane/crossplane/issues/1481 - Handle updates to Compositions safely.

Other ideas that don't currently have tracking issues:

* Updating a Requirement should update the corresponding Composite resource.
* Workshopping and validating our concept names - i.e. InfraDef, InfraPub, composite, composition, requirement, etc.
* Propagating composed resource status up to the composite.
* Supporting arrays of fromFieldPath and toFieldPath - i.e. one to many and many to one.
* ServiceAccount per InfraDef controller.
* A configurable method for representing composite health/readiness based on the values of composed resource fields.

Note that we need to do a little more scoping and exploration here; we're not necessarily committing to doing all of the above as part of this effort.

**Comment by muvaf** [comment]
Here is the prioritization list that I think we can start tackling:

1. #1615 - Consider merging InfraDefinition and InfraPublication
1. #1619 - Automatically grant Crossplane RBAC access to newly defined APIs.
1. #1649 - Updating a Requirement should update the corresponding Composite resource.
1. #1612 - Don't delete a composite resource until all composed resources are gone.
1. #1609 - Allow the fields of composed resources to be exposed as connection secret fields of the composite resource.
1. #1639 - Propagating composed resource status up to the composite.
1. Workshopping and validating our concept names - i.e. InfraDef, InfraPub, composite, composition, requirement, etc.
1. A configurable method for representing composite health/readiness based on the values of composed resource fields.

and others.

cc @prasek

**Comment by muvaf** [comment]
I suggest adding https://github.com/crossplane/crossplane/issues/1637 as the 3rd item to have a better UX around RBAC of defined types.

**Comment by prasek** [comment]
We should consider adding #1506 to the list.

**Comment by muvaf** [comment]
I believe we have the following issues left:
1. #1649 - Updating a Requirement should update the corresponding Composite resource.
1. #1639 - Bidirectional patching
1. #1506 - Custom transforms to define external script/functions.
1. #1609 - Allow the fields of composed resources to be exposed as connection secret fields of the composite resource.
1. #1612 - Don't delete a composite resource until all composed resources are gone.
1. #1652 - Annotations on InfraDef / InfraPub resources should be propagated to generated CRDs

It looks like #1639 and #1506 are the ones that might require one-pagers but I think rest should be fairly straight-forward to implement.

**Comment by muvaf** [comment]
Composition types are bumped to v1beta1 in v0.14 release.
