### ISSUE TITLE
Crossplane Core should support only Packages and Composition

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1630]
### What problem are you facing?

We're focusing Crossplane on defining, composing, and publishing infrastructure APIs. To this end we'd like to remove any functionality that does not aid this from Crossplane core. We see the core of the project as doing a small handful of things:

* Letting you define, compose, and publish infrastructure APIs.
* Letting you package, distribute, and install those APIs.
* Letting you package, distribute, and install the providers that power those APIs.

### How could Crossplane help solve your problem?

Crossplane core could remove or rehome:

* Support for resource claims and classes (https://github.com/crossplane/crossplane/issues/1479)
* Support for workloads (KubernetesApplications) and scheduling (https://github.com/crossplane/crossplane/issues/1595).
* Support for OAM AppliationConfigurations (https://github.com/crossplane/oam-kubernetes-runtime/issues/55).
* Support for (template) StackDefinitions.

**Comment by Tsumida** [comment]
## crossplane+OAM动向
目前通过crossplane使用oam的流程是

 1. 安装crossplane，同时自动创建相关的crd
 2. 为某namespace安装与oam相关的controller，这个可以通过这个[addon-oam-k8s-local](https://github.com/crossplane/addon-oam-kubernetes-local)安装
 3. 在对应的namespace中部署component、AppConf等

奇怪的是，在crossplane下有一个[oam-k8s-runtime](https://github.com/crossplane)仓库，似乎是一个applicationConfiguration controller，这与上面那个仓库有什么差别？结果对比发现:

 1. 两个仓库的目录结构十分相似，对比./charts/Chart.yaml：
![8](https://user-images.githubusercontent.com/29515339/86589968-34951400-bfc1-11ea-93e5-b2fcc124c316.png)
 可见addon-oam-k8s-local这个仓库的controller版本更新。
 2. 根据[slack上的记录](https://app.slack.com/client/TEGUU4LMD/CTHADJCEN/thread/CTHADJCEN-1591859126.351700), maintaier建议不要用oam-k8s-runtime这个库:
 
![9](https://user-images.githubusercontent.com/29515339/86589985-3bbc2200-bfc1-11ea-9e10-10ed5cec560f.png)

 3. 关于[addon-oam-k8s-remote](https://github.com/crossplane/addon-oam-kubernetes-remote)这个仓库不久前已经存档了，maintainer提到正在计划终止对`KubenertesApplication`的支持、通过crossplane来支持部署OAM App到原创集群，不再需要`addon-oam-k8s-remote`。
![10](https://user-images.githubusercontent.com/29515339/86589994-424a9980-bfc1-11ea-8e38-9644276fcee3.png)
 4. 从[这个issue](https://github.com/crossplane/oam-kubernetes-runtime/issues/55)来看，后续将会把addon-oam-k8s-runtime整合进oam-k8s-runtime。结合2来看，目前oam-k8s-runtime起定期备份作用。
 5. 从这个[issue](https://github.com/crossplane/crossplane/issues/1630)来看，未来一段时间，crossplane core将会发生变动，一些功能将会被分离出去，crossplane将聚焦于`defining, composing, and publishing infrastructure APIs`.
