### ISSUE TITLE
Env var support for packages to enable users to supply proxy credentials

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1638]
### What problem are you facing?

All cloud SDKs support proxies through environment variables. For example, AWS SDK expects you to have `HTTP_PROXY` env var defined, which is the standard of Go http library. However, Crossplane package manager doesn't allow entry of any kind of environment variable during installation of the providers. 

https://github.com/crossplane/provider-aws/issues/199#issuecomment-649773923 is a community member requesting this.

### How could Crossplane help solve your problem?

Allow specification of environment variables for the controller that will be installed via package manager so that users can define proxy env vars in corporate networks with no direct access to the internet.

**Comment by hasheddan** [comment]
xref: https://github.com/crossplane/crossplane/issues/974
