### ISSUE TITLE
Modification of existing Kubernetes resources (cluster bootstrapping)

### ISSUE THREAD

**Issue by janwillies** [crossplane/crossplane#1641]
### What problem are you facing?
I need to modify an existing resource in a Kubernetes cluster right after bringup (see https://github.com/crossplane/crossplane/issues/1380 for the old issue with a `KubernetesApplication`). 

Some usecases are:

- `aws-auth` ConfigMap (to grant other users access to the cluster)
- `aws-node` DaemonSet (for things like crossplane/provider-aws#163)
- `kube-system` Namespace (label the NS with `openpolicyagent.org/webhook=ignore` to disable OPA control)

### How could Crossplane help solve your problem?
Crossplane can provide a way to allow that, similar to the old v1alpha3 eks-provider: https://github.com/crossplane/provider-aws/blob/master/pkg/controller/compute/eks.go#L227

**Comment by janwillies** [comment]
This is still an issue (some resources need to be patched) but I think it's not in-scope for crossplane/crossplane. Going to close, feel free to re-open if you think it is.

**Comment by henrysachs** [comment]
I think this is still a topic, but also not sure if this would be something for the kubernetes provider? @janwillies how did you solve your use case?
