### ISSUE TITLE
Documentation question re: Related Projects

### ISSUE THREAD

**Issue by case** [crossplane/crossplane#1643]
### What problem are you facing?

I'm trying to understand your "Related Projects" section about Terraform and Pulumi [here](https://crossplane.io/docs/v0.12/faqs/related_projects.html). 

The sentence says:

> Terraform and Pulumi are tools for provisioning infrastructure across cloud providers. It offers a declarative configuration language with support for templating…

Does "It" in the second sentence refer to Crossplane, or Pulumi, or something else? Trying to understand the grammar here.

Thanks!

**Comment by hasheddan** [comment]
Hi @case! Thanks for bringing this up! Looks like the docs got refactored and did not change the grammar here, leading to a confusing statement. I took a look back at a previous version of the docs and it looks like "It" was referring to Terraform (ref: https://crossplane.io/docs/v0.10/reference/related_projects.html). Are you interested in opening up a PR to suggest wording that is more clear to you?

**Comment by case** [comment]
Usually I'd be happy to, but I'm brand new to Crossplane (and Pulumi) and would rather have… someone who knows them well correct the text. :)

**Comment by hasheddan** [comment]
Fair enough! Thanks again for opening this issue :+1:
