### ISSUE TITLE
secret "dockerhub" not found when installing crossplane

### ISSUE THREAD

**Issue by arafato** [crossplane/crossplane#1648]
### What happened?
Following installation instructions at https://crossplane.io/docs/v0.12/getting-started/install-configure.html

### How can we reproduce it?
Just follow installation instructions in a newly setup K8 cluster.

### What environment did it happen in?
Alibaba Cloud Serverless Kubernetes
Crossplane version: 
crossplane-master/crossplane            	0.13.0-rc.15.gf710a92

Error message is 
```
secret "dockerhub" not found
```

Why do I need to define a secret at all? I think it is a public repo?

**Comment by arafato** [comment]
Running it like so 
```
helm install crossplane --namespace crossplane-system crossplane-master/crossplane --version 0.13.0-rc.15.gf710a92 --devel --set imagePullSecrets=""
```

solved it.

**Comment by hasheddan** [comment]
@arafato thanks for providing the fix! I think this _should_ be set by default during build: https://github.com/crossplane/crossplane/blob/f710a92e29dcd468f3c5686c622d50d186dfa9e0/Makefile#L44

Did you use the installation documentation on https://crossplane.io/docs/v0.12/getting-started/install-configure.html?

**Comment by arafato** [comment]
@hasheddan Yes, I did. At least for me it (empty string) is not being set per default. The default seems to be `dockerhub` as documented at https://crossplane.io/docs/v0.12/reference/install.html at the very bottom.

By the way similar issue with the OAM addon (https://crossplane.io/docs/v0.12/getting-started/run-applications.html). It is expecting a `webhook-server-cert`secret per default. But maybe this make sense...

**Comment by hasheddan** [comment]
@arafato I see, do you mind sharing what version and provider of kubernetes you are using?

**Comment by arafato** [comment]
@hasheddan sure.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by arafato** [comment]
@hasheddan interesting enough, it is working as expected with the Standard Managed K8 Service of Alibaba Cloud. This issue seems only to occur in the Serverless Kubernetes Service of Alibaba Cloud. Not sure why this would happen...
