### ISSUE TITLE
Refactor persona controller into apiextensions

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1650]
### What problem are you facing?

Currently the `persona` controller watches for namespaces and creates `ClusterRole`s on its behalf based on labels. Crossplane does not want to be responsible for managing RBAC for namespace personas in a users cluster.

### How could Crossplane help solve your problem?

Deprecate the `persona` controller for release `v0.13` and schedule for removal in a future release.

**Comment by negz** [comment]
We're now planning to keep this controller (or at least its functionality), but to align it with the `apiextensions` (i.e. composition) controllers. The idea is that the XRD controllers will be responsible for (optionally) creating opinionated `admin`, `edit`, and `view` cluster roles that would grant subjects access to interact with a set of composite resource claims that may differ from namespace to namespace. The idea being we'd be able to configure that "subject S is an editor of namespace N" and that "the automatically generated admin, edit, and view roles for namespace N grant access to claim kinds K, L, and M".

**Comment by negz** [comment]
Followup: we may want to make it possible to opt out of this behaviour on a global level using a Crossplane CLI flag - something like `--no-manage-rbac`.

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/1728.
