### ISSUE TITLE
Add custom status fields to resources from compositions

### ISSUE THREAD

**Issue by enderv** [crossplane/crossplane#1651]
### What problem are you facing?
Would like to be able to add custom information to resources created by compositions. For example: When we create a kubernetes cluster would like to be able to register a custom service endpoint and store that somewhere with the cluster information so there is one source of truth users can refer to. Another example would be related to https://github.com/crossplane/crossplane/issues/1639 maybe save off that information to a field not already provided.

### How could Crossplane help solve your problem?
Add the ability to add custom status fields when building a composition

**Comment by enderv** [comment]
Other possible locations would be to configmap or secret instead of just status.

**Comment by muvaf** [comment]
@enderv Please check if I understood your use case correct. You have an arbitrary information that you obtained from somewhere, in this case custom service endpoint, and you'd like to have this somehow be a part of the requirement. The flow would be that you specify this value on `Composition` resource, define where it should go, like `status.customServiceEndpoint` on the requirement, and have all requirement instances using that `Composition` have that information in `status.customServiceEndpoint`, right?

Or is this custom service endpoint is an information that's already available on the managed resource, let's say `status.serviceURL` of the `EKSCluster` that a member of your `Composition`?

**Comment by enderv** [comment]
Your first explanation is inline with what I was wanting when I wrote this. However just for future proofing and extensibility I am also a fan of the second example you gave don't know if that should be a different issue or not however.

**Comment by muvaf** [comment]
Got it. Today, the best one can do to achieve the first example is to annotate/label the `Composition` resource and then in the requirement, use `spec.compositionRef` field to access the `Composition` to look  up for those values. However, keep in mind that the information you'd expose this way is assumed to be true for all instances of the `Composition`.

I believe the second example is covered by https://github.com/crossplane/crossplane/issues/1639 and we can keep this issue for the first example. In fact, I believe #1639 would cover a part of the first example, too, if a constant could be given as propagation source, i.e. we use `fromFieldPath` to specify where to look to find the value but maybe just `value` would allow a constant value to be propagated back to status of the requirement.

**Comment by muvaf** [comment]
We now have static values for patches and you can patch the status of composite with bi-directional patching referenced above. Feel free to re-open if your use case isn't addressed with these.
