### ISSUE TITLE
Annotations on XRDs  should be propagated to generated CRDs

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1652]
### What problem are you facing?

Today, packages bring in CRDs and annotate them with some UI metadata for UIs to show the input fields correctly and this works well for providers but not much for new composition based stacks since users do not write/generate CRDs on their own; they write `InfrastructureDefinition` and `InfrastructurePublication` resources which result in the actual CRDs. Currently, there is no way for users to provide UI schema metadata for those generated CRDs.

### How could Crossplane help solve your problem?

Crossplane can propagate all annotations from `InfrastructureDefinition` and `InfrastructurePublication` resources to their respective CRDs so that users can just put the UI metadata on those resources and have a CRD with those annotations that the UI can parse. Labels could be propagated as well but I couldn't see an immediate reason.

**Comment by negz** [comment]
The main use case for this functionality (propagating UI schema annotations) doesn't seem to be needed anymore (we can read the annotations from the XRD directly), so we're going to close this out.
