### ISSUE TITLE
NodeSelector on Provider (package)

### ISSUE THREAD

**Issue by kferrone** [crossplane/crossplane#1656]
### What problem are you facing?

I am required to run control plane services on specific nodes and our apps on other nodes. The packageInstaller does not expose the underlying nodeSelector on the deployment it creates. Therefore the pods created by the package installers kinda have free roam over the clusters nodes. 

### How could Crossplane help solve your problem?

Add `nodeSelector` to the `ClusterPackageInstaller` CRD. Then apply it as is to the deployment which is installed.

**Comment by negz** [comment]
What used to be a `ClusterPackageInstall` is going to be a `Provider` in v0.13 (the `Provider` that was is now `ProviderConfig`). I expect this feature request still holds, though.

**Comment by hasheddan** [comment]
This issue has been addressed by adding the `nodeSelector` field on the `ControllerConfig`, which can be referenced by a `Provider` https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1#spec-nodeSelector
