### ISSUE TITLE
Documentation link "Edit on Github" broken for landing page

### ISSUE THREAD

**Issue by tehcyx** [crossplane/crossplane#1658]
### What happened?
Going to the documentation when you're on the landing page and want to edit the docs the link to the specific doc is broken. E.g. here:
https://crossplane.io/docs/v0.12/
points to:
https://github.com/crossplane/crossplane/tree/release-0.12/docs/.md
should point to:
https://github.com/crossplane/crossplane/tree/release-0.12/docs/README.md

same happens in when I select e.g. release-0.11 from the dropdown:
https://github.com/crossplane/crossplane/tree/release-0.11/docs/.md
instead of:
https://github.com/crossplane/crossplane/tree/release-0.11/docs/README.md

All the other subpages seem to work, except the landing page. There might be some that I didn't find in my spotcheck though.

### How can we reproduce it?
Go to the documentation, click "Edit on Github".

### What environment did it happen in?
Crossplane version: 0.12 & 0.11 possibly more

**Comment by hasheddan** [comment]
Thanks for opening this! Looks like jekyll doesn't provide the repo path for the `README`. I'll make sure this gets updated :+1:
