### ISSUE TITLE
Remove resource claims, classes and the package manager

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1670]
### What problem are you facing?

In Crossplane 0.11 we introduced a new feature that we typically call 'composition'. This feature allows Crossplane users to define and publish their own custom resources - known as composite resources - that are composed of one or more underlying managed infrastructure resources. Composition can be used to implement the same functionality as Crossplane's resource claims and classes, but is more flexible. We deprecated resource claims and classes in Crossplane 0.12 per https://github.com/crossplane/crossplane/issues/1479.

### How could Crossplane help solve your problem?

Crossplane should eventually remove all traces of the resource claim and class pattern from its APIs and codebase. This issue will serve as a tracking issue for that work.

**Comment by hasheddan** [comment]
@negz given that claims have already been deprecated (#1600), should this issue instead track their removal?

**Comment by negz** [comment]
One thing that will probably be confusing during this transition period - we've decided to reuse the name 'resource claim' to replace the composition concept of a 'resource requirement'. Further context in https://github.com/crossplane/crossplane-runtime/pull/187.

**Comment by muvaf** [comment]
@negz I can tackle this for 0.13 if you'd like to. I believe we have many breaking stuff already so this could be a good time for the removal.

**Comment by negz** [comment]
I'd like us to consider removing these in the v0.13 release of Crossplane (and corresponding provider releases). We're aiming to make these releases on September 23rd. Claims were marked deprecated approximately three months ago in v0.12 both in the release notes and CRD docs. They're also no longer mentioned by our documentation.

It's important to note that the _functionality_ of the deprecated resource claims can be implemented using composition. @muvaf [created these XRDs](https://github.com/crossplane/crossplane/tree/master/cluster/composition/definitions), which will be usable to replace the original resource claims in v0.13.

**Comment by negz** [comment]
It's been a week, and we haven't had any feedback that indicates folks would be particularly troubled by removing the resource claims in v0.13 so I'm inclined to go ahead with this removal. CC @bassam @jbw976.

**Comment by bassam** [comment]
remove them !
