### ISSUE TITLE
Add Crossplane 'crank' CLI tool in main Crossplane repo

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1673]
### What problem are you facing?

The current [crossplane-cli](https://github.com/crossplane/crossplane-cli) tool is kept in a separate repo and generally maintained on a very separate cadence than core Crossplane. This has led to deviation in behavior and disparate release processes.

### How could Crossplane help solve your problem?

As work begins to refactor much of the Crossplane CLI tool (loosely based on the work done in [hasheddan/crank](https://github.com/hasheddan/crank)), it makes sense to bundle the tool as part of the official core Crossplane release and maintain it in the same repo. This provides the following benefits:
- Tight integration testing with core Crossplane functionality
- Shared libraries for interacting with core Crossplane types without having to juggle dependency versions
- More visibility for the tool as we anticipate it taking on a larger role for Crossplane users

This pattern is supported by the following projects:
- [Kubernetes](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/kubectl.go)
- [Linkerd](https://github.com/linkerd/linkerd2/tree/main/cli)

**Comment by resouer** [comment]
Not sure can we use CRD to discover and install the package?

**Comment by hasheddan** [comment]
@resouer this is somewhat independent of the CLI, but in the future we would like to support installing package by specifying a CRD it installs :+1:

**Comment by negz** [comment]
I'm not opposed to this approach, but it does raise some questions for me:

* Would there be a tight coupling between the version of `crank` and the running version of Crossplane?
* What are some examples of libraries the Crossplane controllers would share with the CLI?
* What would this mean for our CI/CD process? Presumably `crank` would be a distinct binary from `crossplane`.

**Comment by negz** [comment]
I believe this is now done. :)
