### ISSUE TITLE
Deduplicate kind: Provider

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1684]
Under the https://github.com/crossplane/example-cnp sketch there are two (actually, several) resources of `kind: Provider`:

* A `kind: Provider` in the `pkg.crossplane.io` API group represents the installation of a Crossplane provider.
* A `kind: Provider` (typically) in the `<cloud>.crossplane.io` API group represents a connection to a provider's API.

The latter is somewhat of a misnomer. It does not really represent "a provider" but rather a "connection to a provider" or "Crossplane's account in a provider". In many cases it's simply a pointer to the credentials of the robot account that Crossplane should use to authenticate to the provider - e.g. a GCP service account, AWS IAM user, Azure Service Principal, or Kubernetes Service Account. These credentials are typically stored in a `Secret`.

In some cases this latter provider is more than a pointer to a `Secret`:

* The AWS `Provider` contains a superfluous region field that had been slated for removal [for a long time](https://github.com/crossplane/provider-aws/issues/38).
* The GCP `Provider` contains a project name field. This field is duplicated within the credentials `Secret`, and thus could be removed.
* The AWS `Provider` contains a "use service account" field that instructs Crossplane to assume it's running in an EKS cluster and use a special Kubernetes service account that represents an AWS IAM user to authenticate.

**Comment by negz** [comment]
@muvaf I'd appreciate it if you could tackle this. We have https://github.com/crossplane/provider-aws/issues/38 tracking the idea of removing the region from the AWS provider, so I think we can scope this at simply renaming the various `Provider` CRs to something more like `ProviderConfig`. Per our out of band discussion this may or may not involve changing `spec.providerRef` to `spec.providerConfigRef`. I'm ambivalent on that; I like that `providerRef` is more succinct and does not involve a breaking change, but I worry that it could be ambiguous.

**Comment by muvaf** [comment]
This issue has been fixed via:
* https://github.com/crossplane/crossplane-runtime/pull/189
* https://github.com/crossplane/crossplane/pull/1700
* https://github.com/crossplane/crossplane-tools/pull/22
* https://github.com/crossplane/provider-aws/pull/320
* https://github.com/crossplane/provider-gcp/pull/250
* https://github.com/crossplane/provider-azure/pull/166
* https://github.com/crossplane/provider-rook/pull/69
