### ISSUE TITLE
Remove or clarify "provision infrastructure" documentation?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1689]
### What problem are you facing?

As of https://crossplane.io/docs/v0.12/ our getting started docs flow as:

1. Install and configure Crossplane.
2. Provision managed resources.
3. Create compositions of managed resources.
4. Use compositions from OAM apps.

This makes a lot of sense in that each step builds conceptually on the last - the reader learns about the managed resource primitives before they learn how to compose them into new infrastructure concepts. On the other hand, it increases the amount of documentation the reader must go through before they get to what we think is Crossplane's real value - composition.

### How could Crossplane help solve your problem?

I suspect it would be possible to skip straight from installing and configuring Crossplane to creating compositions, especially if we started with a really simple composition. If we did want to keep the current ordering, perhaps we could clarify in the "provision infrastructure" docs that most people won't create managed resources directly - similar to how most people don't create pods directly in Kubernetes.

**Comment by muvaf** [comment]
Composition is a differentiator compared to other projects in the same area, specifically ability to satisfy a claim with different compositions, but the foundational value of Crossplane is to enable the cluster to consume cloud services natively and that's done with the managed resources. Also, it's the easiest feature to understand; consume all cloud services just like persistent volumes, apply a **simple, single object** YAML and get RDS Instance. Additionally, if we don't cover managed resources, users might confuse Crossplane with a generic CRD tooling, like KUDO, until the end. So, I feel like removal could be too far. 

I think a clarification about when to use managed resources could be helpful. For example, in non-self service GitOps managed infrastructure, using managed resources could be easier to reason about what's going on in the cluster.

**Comment by negz** [comment]
We did this. :) CC @luebken for a bit of historical context.
