### ISSUE TITLE
Add hosted Crossplane support to Provider and Configuration controllers

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1691]
### What problem are you facing?

In https://github.com/crossplane/crossplane/issues/1690 we're adding new controllers and types as part of the updated package manager design. We're thinking we'll initially add these without "hosted Crossplane" support (in which the package manager runs packages on a separate API server) so that we can test and demo the bare bones functionality. 

### How could Crossplane help solve your problem?

We'll need to fast follow with adding hosted Crossplane support.

**Comment by hasheddan** [comment]
Closing this out, see #1736 for more context.
