### ISSUE TITLE
OPA integration reference docs & examples

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1698]
### What problem are you facing?
OPA allows you to write declarative, context-aware policy for your cloud-native environments. Because OPA integrates with Kubernetes, it can be used with Crossplane to set global policy on provisioning cloud resources. Would be great to have some reference docs that show how to best use OPA and Gatekeeper (OPA's native kubernetes impl) with Crossplane.

### How could Crossplane help solve your problem?
Add a reference doc as a section under https://crossplane.github.io/docs/v0.12/reference/overview.html based on https://github.com/crossplane/tbs/tree/master/episodes/14 and @jbw976's updates.

![image](https://user-images.githubusercontent.com/284840/91748997-bba3da00-eb75-11ea-807a-a457371268b9.png)

**Comment by hawkesnc** [comment]
Not sure this issue is relevant anymore since the doc it's referring to (v0.12) and this link: https://crossplane.github.io/docs/v0.12/reference/overview.html doesn't work
