### ISSUE TITLE
Deprecate the Kubernetes ProviderConfig type?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1704]
### What problem are you facing?

We [recently renamed](https://github.com/crossplane/crossplane/pull/1700) the Kubernetes `Provider` type in Crossplane to a `ProviderConfig`. This new name implies that it would "configure the Kubernetes provider", but no such provider currently exists. It's actually a shared/generic provider configuration for any Kubernetes-backed provider - namely the Rook and Helm providers.

### How could Crossplane help solve your problem?

I suggest we deprecate the Kubernetes `ProviderConfig` type in this repo, and replace it with Helm and Rook specific `ProviderConfig` types in each of those providers. These provider configs would all be identical in practice (just a pointer to a `Secret` with a kubeconfig in it), but would be conceptually cleaner and break the dependency of those providers on the core Crossplane repo.

**Comment by negz** [comment]
CC @muvaf @hasheddan @turkenh does this make sense?

**Comment by turkenh** [comment]
Yes, sounds good to me.
I agree that it would be cleaner.

**Comment by hasheddan** [comment]
I think this would be fine to do, and gives us the advantage that the providers don't have to request any additional permissions (once claims are removed). Just wanted to point out that the original thinking behind having one type for "Kubernetes-native" providers was that other providers that provisioned Kubernetes clusters could make those available to a "Kubernetes-native" provider (i.e. I create a `GKECluster` and then a helm `Chart` that is "scheduled" to that cluster) by creating a Kubernetes `Provider` type. There are some advantages to having a single type for this, but we could just as easily just create a new helm `ProviderConfig` manually or with another controller. I also think this will be a pattern for other types as well (i.e. VMs, bare metal, serverless platforms) so we likely will want to address the use-case more generally.

**Comment by hasheddan** [comment]
@negz I'll take care of the `provider-rook` update :+1:

**Comment by muvaf** [comment]
> Just wanted to point out that the original thinking behind having one type for "Kubernetes-native" providers was that other providers that provisioned Kubernetes clusters could make those available to a "Kubernetes-native" provider (i.e. I create a GKECluster and then a helm Chart that is "scheduled" to that cluster) by creating a Kubernetes Provider type. There are some advantages to having a single type for this, but we could just as easily just create a new helm ProviderConfig manually or with another controller.

Without Kubernetes `ProviderConfig`, is it possible today for a Kubernetes cluster to publish its kubeconfig and have `provider-helm` use it in the same `Composition`? As @hasheddan pointed out, I think that's the main use case this type covers right now and as long as that's still possible, I agree that we should deprecate this type.
