### ISSUE TITLE
Add and publish crank.crossplane.io install script

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1724]
### What problem are you facing?

It is common for projects to serve a shell script which will install their CLI tool.

Examples:
- `https://sdk.cloud.google.com`
- `https://run.linkerd.io/install`
- `https://istio.io/downloadIstio`
- `https://cli.openfaas.com`

### How could Crossplane help solve your problem?

Crossplane should serve a similarly helpful script to make installing `crank` straightforward regardless of OS.

**Comment by negz** [comment]
https://crank.crossplane.io/rotate IMO.

**Comment by hasheddan** [comment]
This was fixed with: https://github.com/crossplane/crossplane/pull/1813
