### ISSUE TITLE
Allow installing Crossplane Providers in Helm chart

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1726]
### What problem are you facing?

Currently, Crossplane's Helm chart allows you to create a `ClusterPackageInstall` for various providers (AWS, Azure, GCP, Rook) when you `helm install` Crossplane with the `--set clusterPackages.gcp.deploy=true --set clusterPackages.gcp.version=master` flags (for example). `ClusterPackageInstall` will be replaced by `Provider` in this context in the v0.13 release, and installing the old package manager and types will likely be "off" by default.

### How could Crossplane help solve your problem?

We should provide the same functionality for the new package manager in the Helm chart by creating a `Provider` for the given provider on install.

**Comment by negz** [comment]
> Currently, Crossplane's Helm chart allows you to create a ClusterPackageInstall for various providers (AWS, Azure, GCP, Rook) when you helm install Crossplane with the --set clusterPackages.gcp.deploy=true --set clusterPackages.gcp.version=master flags (for example). 

Note that I removed this functionality recently, so this issue is now scoped more as "allow installing _any_ providers in the Helm chart".
