### ISSUE TITLE
Should Crossplane support composing arbitrary Kubernetes resources?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1730]
### What problem are you facing?

Crossplane's 'composition' functionality was [designed](https://github.com/crossplane/crossplane/blob/20493ac0f778c718409c43df0ab5d92264231187/design/design-doc-composition.md) such that a composite resource could compose managed resources - i.e. Kubernetes resources owned by a Crossplane provider - and other composite resources. Managed resources are always cluster scoped (like composite resources), and comply with Crossplane's API conventions (connection secrets, cross resource references, etc). We've since extended this contract to include composing provider configurations, to allow for example a composite resource to provision a Kubernetes cluster that itself acts as a provider for Helm release managed resources within the same composition.

The idea is that Crossplane works by:

1. Installing providers that teach Crossplane how to interact with external cloud APIs.
1. Defining composite resources that compose provider resources into opinionated, higher level APIs.
1. Letting platform operators and consumers use those composite resources.

Currently the only technical limitation on what Crossplane may compose is that is must expose a status condition named 'Ready' that will at some point become 'true'. Once https://github.com/crossplane/crossplane/pull/1713 is merged Crossplane will be able to compose any Kubernetes resource. This is accidental, rather than by design. We should consider whether this is something we want Crossplane to support officially.

### How could Crossplane help solve your problem?

If we do choose to allow Crossplane to compose arbitrary resources, we'll need to:

* Establish patterns to ensure Crossplane has permission to manage those resources. The [RBAC manager design](https://github.com/crossplane/crossplane/blob/20493ac0f778c718409c43df0ab5d92264231187/design/design-doc-rbac-manager.md) ensures Crossplane's service account has access to CRUD composite and managed resources. For Crossplane to compose an arbitrary kind of Kubernetes resource an operator would need to create a cluster role that aggregated to the cluster role bound to Crossplane's service account in order to grant Crossplane access to CRUD that resource.
* Determine what it would look like for a (cluster scoped) composite resource to compose resources that were namespaced.

If we choose _not_ to allow Crossplane to compose arbitrary resources, we'll need to validate that Compositions compose only composite resources, managed resources, or providers.

I think the underlying question here is whether we want to be able make assumptions about the kind of resources Crossplane composes. Allowing Crossplane to have opinions about the resources that it composes will likely make it easier to reason about how Crossplane works (both as a user of Crossplane and a designer of future Crossplane functionality). On the other hand, restricting Crossplane to supporting only certain kinds could cut off valuable use cases (e.g. composing an OPA policy), or introduce extra complexity to support those use cases (e.g. writing an OPA provider that was just a shim to the actual types).

**Comment by pdettori** [comment]
I have use cases where the ability to compose arbitrary (namespaced) Kubernetes resources would be very valuable. This enhancement would allow me to use existing operators for managing in-cluster resources (e.g. DBs) and use Crossplane Composition to create common abstractions for in-cluster and off-cluster services. For example, I could use one of the existing operators for Postgresql (e.g. https://operatorhub.io/operator/postgresql ) and use a common `CompositeResourceDefinition` for Postgresql in-cluster and on the different clouds. If this was supported, I would not have to build new operators following the Crossplane conventions or "shim" operators, but I could use existing community operators in my composition.  Therefore, I think supporting arbitrary resources would greatly extend the applicability of Crossplane to existing applications where some service is in-cluster and other services are on some of the clouds, and this alone should outweigh some of the cons (might be harder to reason about how Crossplane works).

**Comment by srueg** [comment]
> [...] I think supporting arbitrary resources would greatly extend the applicability of Crossplane to existing applications where some service is in-cluster and other services are on some of the clouds [...]

I'd also like to chime in on this. We have the exact same use case and would greatly benefit of the "generic K8s resource" capability.
I think this would also go hand in hand with https://github.com/crossplane-contrib/provider-helm/issues/25, and #1722?

**Comment by displague** [comment]
When considering potential Equinix Metal compositions, a `Cluster` composition may be very beneficial. 

I do not want to reinvent the wheel by provisioning Kubernetes on bare metal devices using Crossplane's EM Device support and the `userdata` property.  I can already rely on the existing Cluster API ~Packet~ _Equinix Metal_ Provider to provide this capability.

Crossplane comes in where CAPP and the CCM have infrastructure requirements that those tools do not manage themselves. Crossplane could be used to provision the EIPs, VLans, Projects, and BGP resources that would be consumed by CAPP and the Equinix Metal CCM. https://github.com/packethost/crossplane-provider-equinix-metal/issues/41

If I could not introduce these CAPP resources into a composition, I would need to create (and maintain) additional providers, provider-cluster-api and provider-capp, to accomplish this goal.

**Comment by srueg** [comment]
Is there any news on this topic?

The issue described in #2150 prevents us currently to use the new "named resources" feature since it breaks with namespaced managed resources.

**Comment by negz** [comment]
Our position as to whether Crossplane should be used to compose non-Crossplane resources has not changed. We don't design for that use-case and thus do not recommend or support it.

There is however a potential alternative now with @turkenh's https://github.com/crossplane-contrib/provider-kubernetes project. This provider can adapt any Kubernetes object to act as a valid Crossplane managed resource that will be supported by composition.

**Comment by turkenh** [comment]
@uluzox responded [here](https://github.com/crossplane-contrib/provider-kubernetes/issues/35#issuecomment-1104020537). 

But the short answer is XRs are not namespace hence `metadata.namespace` is not set.

**Comment by shanproofpoint** [comment]
When allowing resources to become consistent in the reconciliation loops, some ci cd tools like argocd are stuck when webhooks wait for each other cyclicly.  The same can happen for kubernetes provider objects that depend on each other dynamically.

**Comment by haorenfsa** [comment]
I think it make sense to compose existed `composite resource` claims into a new `composite resource`. The claim itself is a namespaced resource. 
So composing namespaced resources should be supported.
And hence `composing arbitrary Kubernetes resources` are also supported naturally.

**Comment by haorenfsa** [comment]
Another case is that Google Cloud Platform(GCP) has their own kind of `provider-gcp` implementation called [config-connector](https://cloud.google.com/config-connector/docs/reference/overview) (which is namespaced, and also has the `Ready` condition). Other cloud service may also provides their own. Crossplane should be able to make composition by these CRs

**Comment by negz** [comment]
> I think it make sense to compose existed composite resource claims into a new composite resource. The claim itself is a namespaced resource.

You can already compose XRs into a new XR, which is functionally the same.

> Crossplane should be able to make composition by these CRs

Why would we support this instead of our own provider-gcp?

**Comment by negz** [comment]
At this point I don't think Crossplane is going to support composing arbitrary Kubernetes resources (except via providers such as provider-kubernetes and provider-helm), at least not without "Crossplane v2" level architectural and API changes.

**Comment by haorenfsa** [comment]
> You can already compose XRs into a new XR, which is functionally the same.

hi @negz .  Is there an example or document about composing XRs?  It seems to me that since XRs are namespaced resources, and Crossplane does not supports namespaced resources, so it cannot be composed into a new XR.
