### ISSUE TITLE
Use scratch or distroless images across Crossplane projects

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1745]
### What problem are you facing?

Crossplane images are currently using [`alpine:3.7`](https://github.com/upbound/build/blob/af023ee602ef60d14612f06f91c6fcb38c402269/makelib/image.mk#L33) as the base image, which has tooling that we should not need in most cases. Having these tools present increases the attack surface area of our images.

### How could Crossplane help solve your problem?

The two most straighforward approaches would be to either use `scratch` or [`distroless`](https://github.com/GoogleContainerTools/distroless/tree/master/base). Using `scratch` has the advantage of smaller image size, but would require a multistage build from something like `alpine` to get any runtime dependencies (e.g. ca-certificates). `distroless`, on the other hand, typically will result in a larger image size, but comes with any runtime dependencies we would likely need.

**Comment by muvaf** [comment]
Note that `distroless` from Google doesn't have builds for [`arm64`](https://github.com/GoogleContainerTools/distroless/issues/377) which is one of our targets. Though I wouldn't mind removing `arm64` target from Crossplane.

**Comment by negz** [comment]
I'm pretty sure @hasheddan did this already.
