### ISSUE TITLE
Remove KubernetesApplication and KubernetesTarget

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1755]
### What problem are you facing?

We deprecated these in https://github.com/crossplane/crossplane/issues/1595. Once we've released v0.13 with the deprecation notice we should move forward with removing them in v0.14 or so.

### How could Crossplane help solve your problem?

Remove the KubernetesApplication, KubernetesApplicationResource, and KubernetesTarget types and their controllers.

**Comment by prasek** [comment]
@negz looks like this is all wrapped up, closing it out 👍
