### ISSUE TITLE
Combine Helm chart README.md with install docs

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1762]
### What problem are you facing?

https://github.com/crossplane/crossplane/blob/3a18fb7/cluster/charts/crossplane/README.md

The above chart readme is out date. It also has a lot of overlap with our [other](https://github.com/crossplane/crossplane/blob/3a18fb/docs/getting-started/install-configure.md) [installation](https://github.com/crossplane/crossplane/blob/master/docs/reference/install.md) docs.

### How could Crossplane help solve your problem?

I suggest we pick one installation document to be our source of truth (including details on what Helm chart values we support, then update our build to copy that file as the Helm chart's README.md as part of `make generate`.

**Comment by hasheddan** [comment]
@negz just a note here, we used to sync this file from the docs here: https://github.com/crossplane/crossplane/blob/cf5865f45074670729a59d7a91da56ca974a98d3/Makefile#L147
