### ISSUE TITLE
Support SQL Provider(s)

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1769]
### What problem are you facing?

Some cloud providers (e.g. Google) provide APIs for creating SQL databases and users, but the majority do not. It is possible to create an SQL instance via the provider API, but you must speak SQL to those instances before an application can viably use them.

### How could Crossplane help solve your problem?

Crossplane could support a `provider-sql`... provider. The `ProviderConfig` of this provider would point to an SQL instance (presumably via its connection secret, or IAM) and support managed resources like `MySQLDatabase`, `PostgreSQLUser`, etc. This would allow a Crossplane composite resource to provision a fully functional database, ready for an app to consume.

CC @PocketMobsters @mothershipper who I believe are experimenting with similar functionality.

**Comment by matthewhembree** [comment]
@negz You might take a peek at this project: https://github.com/schemahero/schemahero

It's only for table objects currently, but maybe you can find common ground.

**Comment by negz** [comment]
Here's a first pass at `provider-sql` - https://github.com/negz/provider-sql

Currently it has full support for managing PostgreSQL databases, and limited support for managing MySQL databases (create and delete only - no configuration of encoding etc). PRs are welcome; I'm far from an SQL expert so I'm sure there's room for improvement.
