### ISSUE TITLE
Cant add helm repo: host charts.crossplane.io cannot be resolved.

### ISSUE THREAD

**Issue by koshkarov** [crossplane/crossplane#1772]
### What happened?
When adding crossplain chart repository to helm, the system can't resolve the hostname charts.crossplane.io. 
This issue prevents us from installing the crossplane. 

Obviously this is not a bug, rather network issue. But not sure how and where I can report it. 

It produces the error on **local environment**: 
"_Error: Looks like "https://charts.crossplane.io/alpha" is not a valid chart repository or cannot be reached: 
Get "https://charts.crossplane.io/alpha/index.yaml": dial tcp: lookup charts.crossplane.io on 192.168.65.1:53: no such host_"

And **GitLab CI**: 
_Error: Looks like "https://charts.crossplane.io/alpha" is not a valid chart repository or cannot be reached: Get "https://charts.crossplane.io/alpha/index.yaml": dial tcp: lookup charts.crossplane.io on 169.254.169.254:53: no such host_

### How can we reproduce it?
Run `helm repo add crossplane-alpha https://charts.crossplane.io/alpha` on any environment. 

### What environment did it happen in?
Crossplane version: v0.12
Helm version: v2

**Comment by hasheddan** [comment]
@koshkarov thanks for opening this! We are aware of this issue and have identified the cause. I believe that we may have already reached resolution, would you mind trying to run again?

**Comment by koshkarov** [comment]
Thanks @hasheddan , the host resolves now. 

![image](https://user-images.githubusercontent.com/7766436/94303650-29a4ac80-ff3c-11ea-8fb4-3c17f794d2a3.png)

**Comment by hasheddan** [comment]
@koshkarov great! Apologies for the interruption!
