### ISSUE TITLE
Provider packages create many service account secrets

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1780]
### What happened?

I notice a slowly growing number of secrets associated with the GCP provider:

```console
$ kubectl -n crossplane-system get secret|grep provider-gcp|wc -l
      50

# Around a minute later...
$ kubectl -n crossplane-system get secret|grep provider-gcp|wc -l
      51

$ kubectl -n crossplane-system get secret --sort-by=.metadata.creationTimestamp|tail -n3
provider-gcp-master-525ddde0f696-token-vrs5s   kubernetes.io/service-account-token   3      85s
provider-gcp-master-525ddde0f696-token-k4xjs   kubernetes.io/service-account-token   3      43s
provider-gcp-master-525ddde0f696-token-z7l6p   kubernetes.io/service-account-token   3      22s
```
I suspect this is because we're using the updating rather than patching applicator to apply the provider `ServiceAccount`, and wiping out some metadata (perhaps the secrets array?). I notice the named secret in the below output always matches the most recent secret.

```console
$ kubectl -n crossplane-system get serviceaccount provider-gcp-master-525ddde0f696 -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-09-28T04:11:44Z"
  name: provider-gcp-master-525ddde0f696
  namespace: crossplane-system
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1alpha1
    controller: true
    kind: ProviderRevision
    name: provider-gcp-master-525ddde0f696
    uid: 30acd695-313c-4a8d-a7aa-1caa974bfea6
  resourceVersion: "8045"
  selfLink: /api/v1/namespaces/crossplane-system/serviceaccounts/provider-gcp-master-525ddde0f696
  uid: ba18526e-2d56-4d81-a7df-536f0c6c6f5d
secrets:
- name: provider-gcp-master-525ddde0f696-token-x5l25
```

### How can we reproduce it?

Install the following provider:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-gcp-master
spec:
  package: crossplane/provider-gcp:master
```

### What environment did it happen in?
Crossplane version:

**Comment by hasheddan** [comment]
@negz thanks for identifying this! I am thinking it may make sense to use the patching applicator for both the SA and Deployment. It would fix this issue described here and would also allow for manual editing of the Deployment which would “fix” the EKS IRSA scenario in the short term as well. While it would make the revision controller a bit less authoritative over the Deployment, I don’t think anyone should have access to edit Deployments in the namespace Crossplane is installed in (which is where we create Provider Deployments) except for someone who is managing packages and may want to manually edit. A Provider revision’s controller could always be instructed to recreate the Deployment by a user deleting the Deployment directly (e.g. someone may want to do this if they edit the Deployment in a way that makes it not work correctly and they just want the revision controller to create a fresh new one).
