### ISSUE TITLE
Auto-generate release notes / changelog

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1828]
### What problem are you facing?

Releases across Crossplane repos often are onerous because we manually search through the PRs since the last release and write short summaries for those deemed important. Or, in the case of many of the providers, we don't have notes for new releases at all.

### How could Crossplane help solve your problem?

It would be good to front load the effort of summarizing changes using labels and comments in PR body. For instance, we typically have three sections in Crossplane [release notes](https://github.com/crossplane/crossplane/releases): Notable Updates, Deprecations, and Breaking Changes. PRs could be categorized into these groups by requring a `kind/` label on the PR, and the summary for the PR could be a specific section in the PR body that gets parsed. For instance, see [this PR](https://github.com/kubernetes/kubernetes/pull/95316) where `client-go header logging (at verbosity levels >= 9) now masks 'Authorization' header contents` will be included in the release notes when generated. 

If we matched this pattern, we could use the [k8s release tooling](https://github.com/kubernetes/release) to generate our release notes as well.

**Comment by negz** [comment]
I believe GitHub now does this for us.
