### ISSUE TITLE
Pin "getting started" configuration packages to a particular Crossplane release.

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1833]
### What problem are you facing?

https://crossplane.io/docs/v0.13/getting-started/compose-infrastructure.html

The "getting started" configuration packages were built manually for v0.13.0, and are tagged as `:master`.

### How could Crossplane help solve your problem?

We should probably retag them as `:v0.13.0` (or their provider versions)? Ideally we'd build these tags automatically via CI/CD

**Comment by muvaf** [comment]
I think this is done now as part of the release process.
