### ISSUE TITLE
Consider supporting simple install of Crossplane itself with CLI

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1838]
### What problem are you facing?

The Crossplane CLI was revamped in the v0.13 release to include more functionality. However, I frequently find myself wanting to do a simple default install of Crossplane, but still having to look up the helm commands required.

### How could Crossplane help solve your problem?

It would be nice if Crossplane could be installed by its own CLI. The simplest way would likely be to just shell out to helm, but we also could support a super minimal "dev" install by just creating the `Deployment(s)` directly. If we still intend for helm to be the main distribution method, this might be the best route to go.

**Comment by negz** [comment]
We decided this wasn't a good fit for `kubectl crossplane`, but some of us at Upbound did build similar functionality into https://github.com/upbound/up!
