### ISSUE TITLE
Support In-Cluster Provisioning

### ISSUE THREAD

**Issue by krishchow** [crossplane/crossplane#1839]
### What problem are you facing?
Currently, the process for provisioning services in-cluster using Crossplane is not very well defined. For several clients and consumers of Crossplane that I have spoken to, the ability to create databases, in-memory caches, or other services in-cluster is essential for their migration or adoption of Crossplane. 

I believe there are currently two recommended path in-cluster provisioning of resources:
- Rook Provider: The Rook provider directly reflects types exposed by Rook, and in this way, it can is used to provision storage in-cluster. Specifically, there is currently only support for CockroachDB and YugabyteDB.
- Helm Provider: The helm provider gives end-users more flexibility with what types of resources they can create by directly running an arbitrary helm template. However, this does not allow us to have control over the internals of these templates, and we also cannot verbose events.

### How could Crossplane help solve your problem?

I believe Crossplane should support in-cluster provisioning for some of the most commonly used resources (e.g., Postgres, MySQL, Memcached, Redis, etc.). We can do this through an In-Cluster Provider (I'm not attached to the name), which is responsible for provisioning storage or other services in the cluster. The reason I emphasize storage in this issue is that I believe it is low hanging fruit, in that the implementation should be straight forward, and it brings significant value for users.

**Comment by krishchow** [comment]
cc @hasheddan

**Comment by hasheddan** [comment]
@krishchow This seems like it more about the provisiong mechanism / experience than just being able to deploy something like `Postgres` in-cluster, which could be accomplished with `provider-helm` and the [Postgres Helm Chart](https://github.com/helm/charts/tree/master/stable/postgresql) for instance. Is the issue that folks want to be able to deploy these resources using exising raw k8s manifests? If so, this sounds like it might could be accomplished by having something like a `provider-k8s`. Similar to how `provider-helm` works, you could provide a URL with manifests or just put them inline. You could also just put whatever is in the manifests in a `Composition`, but there could be some complications around that.

**Comment by negz** [comment]
We've created https://github.com/crossplane-contrib/provider-in-cluster to track and build this work. I'm going to close this issue.
