### ISSUE TITLE
Support Dependency Resolution in Package Manager

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1842]
### What problem are you facing?

`Provider` and `Configuration` packages have fields to specify dependencies on other packages, but Crossplane does not currently take action based on them.

### How could Crossplane help solve your problem?

Crossplane should support resolving and installing dependencies for packages.

[Placeholder issue, more info to follow]

**Comment by hasheddan** [comment]
Fixed by #1971

**Comment by muvaf** [comment]
Congratulations @hasheddan ! This was a pretty big feature 🙂
