### ISSUE TITLE
Generate crossplane-runtime types from terraform-provider-aws schema

### ISSUE THREAD

**Issue by kasey** [crossplane/crossplane#1844]
### What problem are you facing?

Terraform resources vary widely in complexity, leading to some uncertainty about how some of the more deeply nested types will function, or whether some resources will rely on data sources (currently not modeled in our design) to function. 

### How could Crossplane help solve your problem?

As a checkpoint to review our progress towards full code generation, build a provider repo that just contains generated types for all resources. These types would not understand cty serialization or be capable of reconciling through the provider, they are only for human review.

**Comment by kasey** [comment]
Still WIP, working through a couple kinks:
- from looking at the schema types coming from terraform, we can't differentiate between integers and floats for Numeric types
- working through the nuances of nested types (NestedList, NestedSet)

Currently working on the nested type support, which should be just a few more days until I'm able to update the [generated output](https://github.com/kasey/provider-terraform-aws/tree/master/generated/resources) with examples. For the Numeric types, some deeper investigation is needed reading terraform serialization source code because I have hit a wall with what I can tell from the debugger.

**Comment by negz** [comment]
We're experimenting with a different approach on this one at the moment in https://github.com/crossplane-contrib/terrajet - we're using that repo to track.
