### ISSUE TITLE
Rethink external-name annotation

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1863]
### What problem are you facing?

Crossplane has the notion of [external name](https://github.com/crossplane/crossplane/blob/37013c6/design/one-pager-managed-resource-api-design.md#external-resource-name) that's specified via an annotation named `crossplane.io/external-name`, introduced because of https://github.com/crossplane/crossplane/issues/624

@kasey has recently brought this up as it makes code generation for providers a bit harder. I wanted to open the floor for discussion to rethink whether it's still necessary.

At the time, external name annotation was needed for two main reasons:
* Claim -> Managed resource propagation. We wanted users who create claims to be able to specify the external name for the managed resource, like name of the bucket. However, since those old claims didn't know about which field of the managed resource corresponds to name and/or what name format it can expect, we used the annotation as a [delivery vehicle](https://github.com/crossplane/crossplane/blob/37013c6/design/one-pager-managed-resource-api-design.md#custom-resource-instance-name) for the name value.
* CR name to be used as external name. We wanted to use the name of the managed resource CR (`metadata.name`) as the name of the external resource by default unless users specify otherwise. A known annotation makes implementation of this defaulting much easier and compatible with old claims.

From what I can see, the first use-case is essentially dead with the composition since users are in control of what flows to where. So, they can just say `metadata.name of claim should go to spec.name of the bucket`. Second one still persists, however, the annotation is an implementation detail for the defaulting once we take out the claim propagation. We can have an [`Initializer`](https://github.com/crossplane/crossplane-runtime/blob/de46c55/pkg/reconciler/managed/api.go#L55) for each managed resource that knows which field of the managed resource is the name. Keep in mind that we already do such field binding during provider API calls anyway.

### How could Crossplane help solve your problem?

Please chime in and comment on whether it's still needed or not. I feel that, regardless of the code generation effort, there isn't a strong UX improvement that external-name annotation provides that affords the deviation from the high fidelity of `spec` by taking out `spec.name`. But I might be forgetting some big reason to have it.

**Comment by negz** [comment]
I believe another use case was handling resources whose unique identifiers are generated automatically by the cloud provider - i.e. providing us somewhere other than status to store a resource's _actual_ identifier when it's not the same as `metadata.name`.

Honestly, I quite like the external name annotation and I'm fairly reluctant to remove it. If we do remove it, I would like us to try hard to maintain its semantics. i.e.

* Managed resource authors shouldn't _have to_ specify both a Kubernetes name and an external name. The external name should default to the Kubernetes name, where possible.
* There should be a consistent place to look to discover the actual external name of a managed resource.

**Comment by muvaf** [comment]
> I believe another use case was handling resources whose unique identifiers are generated automatically by the cloud provider

That'd be handled by a field under `spec.forProvider`, like `spec.forProvider.id` for ID of VPC.

> Honestly, I quite like the external name annotation and I'm fairly reluctant to remove it. If we do remove it, I would like us to try hard to maintain its semantics

It should be straight-forward to keep its semantics with a `metadata.name<> chosen field in spec` binding though, you're right, the place to look to discover the actual external name may not be as consistent as a known annotation. But that consistency has a cost. For example, `SecurityGroup` in AWS has an `ID` and a `Name` (and there was something similar in GCP `ServiceAccount`). We choose `ID` as external name because it's unique identifier but no one knows that until they create the resource because we're not able to have documentation on an annotation to tell its format or what it corresponds to like a field in the spec. So, there is a trade-off there.

Honestly, I don't really have a strong opinion about removing it. But I wanted to see what folks think about it because the old claim type was the biggest reason to have it on top of others you mentioned for me and that need is gone now.

**Comment by muvaf** [comment]
I have got the [API Gateway v2](https://github.com/crossplane/provider-aws/pull/416) resources generated and while writing the custom code to handle external-name, I faced an issue where it's really hard to decide what should be the external-name. For example, `API` resource has a `Name` field but also AWS-assigned `ID`. If we use `external-name` for `Name`, we can make it work with `GetApis` request that returns all APIs and filter through the list (name is unique). However, if we make `GetApi` request, it requires you to supply the `ID`. Same thing goes for a few resources in the same service, like `Stage` that has `StageName` and `ID`. Some of them has only `ID` so it's not that hard to choose for all of them.

From controller's perspective, I'd like `ID` to be recorded in a non-status field because that's what AWS guarantees to be the unique identifier even though we can do some filtering with `name` after getting all APIs. But from user's perspective, their Kubernetes resource name is not honored at all; `spec.forProvider.name` is just like other fields but a required one. So we're not achieving what we wanted in the first place, i.e. defaulting to Kubernetes name wherever possible.

Also, users are not able to know which one is used as external-name until they try and see, we are not able to document it. For example, IAMPolicy uses full ARN as external-name because there are both ID and name necessary to identify it. I was thinking that `SecurityGroup` is probably is an exception but it seems we're seeing this behavior across the board. 


> * Managed resource authors shouldn't _have to_ specify both a Kubernetes name and an external name. The external name should default to the Kubernetes name, where possible.
> * There should be a consistent place to look to discover the actual external name of a managed resource.

So, I am suggesting that we keep both ID and name fields (all that's used as identifier) under `spec.forProvider` similar to how provider API calls do. The main difference would be that `name` field (if exists) would not be required and we'd have a defaulter in place that will initialize `spec.forProvider.name` to `metadata.name` if it's empty. If the resource does not have any name, then we won't do any initialization and expect `forProvider` to be enough to identify the resource with all of its well-documented fields.

I believe second point you mentioned, in fact, is better covered by this approach. Because while we have a single `crossplane.io/external-name` as the place for name, what you should expect there is not clear at all. Is it ARN, ID or StageName? We know _where_ the information is but we don't know _how_ and _what_ information is stored there. If it's a field in `forProvider`, we would need to know all these but only which field to look is not consistent _across all kinds of managed resources_ (for the instances of the same kind, it's consistent).

In terms of implementation, I don't think we have much dependency on this annotation except this recent PR https://github.com/crossplane/crossplane-runtime/pull/228 . But that can be refactored easily by setting the `spec` instead of just a single annotation.

It is a breaking change, however, we can make it backward-compatible easily with resource-specific initializers that will default new fields to `external-name` once new controller version starts reconciling.
