### ISSUE TITLE
Update operation for Claim Object 

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#1876]
Hi @negz .

Saw that you commented on the following code:

https://github.com/crossplane/crossplane/blob/master/pkg/controller/apiextensions/claim/api.go

```
// TODO(negz): We should render and patch a composite resource on each
// reconcile, rather than just creating it once.
```

Does that mean currently composite object only support _Create_ but not _Update_ operation?
Any plan to make it available as i am currently using XRD (compositeresourcedefinitions) way for creating my resources and now seem when I update the claim object, it does not take update the composite and managed object

Thanks,

**Comment by muvaf** [comment]
Hi @kelvinwijaya ! Yes, we have https://github.com/crossplane/crossplane/issues/1649 covering that and it has been accepted for the next release. So, you can expect to see this implemented in 0.14. Feel free to give a thumbs-up to that issue 🙂
