### ISSUE TITLE
Docs updates are not published in CI

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1889]
### What happened?

Publishing docs updates silently fails in our CI pipeline because we are using the default `GITHUB_TOKEN` secret instead of providing the one token for `upbound-bot`. 

### How can we reproduce it?

https://github.com/crossplane/crossplane/runs/1294963264

```
git -C "/home/runner/work/crossplane/crossplane/.work/docs-repo" add -A
committing changes...
[master 34b1a44] docs snapshot for crossplane version `master`
 1 file changed, 7 insertions(+)
 create mode 100644 docs/master/api-docs/oam-kubernetes-runtime.md
pushing changes...
fatal: could not read Password for 'https://***@github.com': No such device or address
crossplane.github.io changes published
```
You will notice recent docs changes have not landed on https://crossplane.io

**Comment by hasheddan** [comment]
@negz @jbw976 I believe we will need one of you to add the API token secret to the github org. We added them in the `provider-helm` repo for tag and they seem to be working correctly: https://github.com/crossplane-contrib/provider-helm/blob/506ed9be1549f8dd2aee24de76be96ee0db174e4/.github/workflows/tag.yml#L11

**Comment by negz** [comment]
@hasheddan I can do this, but I need to know the secret first. I'll try to find it on Monday.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/v0.12.0/Makefile#L66
https://github.com/crossplane/crossplane/blob/v0.12.0/Jenkinsfile#L121

It looks like previously `GIT_API_TOKEN` was set to github-upbound-jenkins, which would have been output in the form `username:password` by Jenkins. So we'll need to add `UPBOUND_BOT_USR` and `UPBOUND_BOT_PSW` secrets at the org level, then have our workflows set the `GIT_API_TOKEN` env var to the concatenation of those secrets.

I think something like this should do the trick:

```yaml
env:
  GIT_API_TOKEN: format('{0}:{1}', secrets.UPBOUND_BOT_USR, secrets.UPBOUND_BOT_PSW)
```

We may want to change `GIT_API_TOKEN` to something more like obvious; I believe this env var is only used to publish docs and actually contains a username and API token. Perhaps `DOCS_REPO_CREDS` or something.

**Comment by negz** [comment]
These secrets now exist at the org level as `secrets.UPBOUND_BOT_GITHUB_USR` and `secrets.UPBOUND_BOT_GITHUB_PSW`.
