### ISSUE TITLE
Composed resources are leaked when there is XR write contention

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1910]
### What happened?

While working on https://github.com/crossplane/crossplane/issues/1649 I've noticed that the XR controller leaks composed resources when there is higher than usual write contention (e.g. because an update to the XR triggers both the claim and composite resource controllers to update the XR). This is because the composite controller first creates a managed resource using `metadata.generateName` then, records the generated name by updating the XR's `spec.resourceRefs`. If the update fails the composite controller doesn't know it has already created the composed resource, and will do so again on the next reconcile.

### How can we reproduce it?

Presumably by triggering many updates to a newly created XR in a very tight loop.

### What environment did it happen in?
Crossplane version: https://github.com/crossplane/crossplane/commit/28224d92322a9caeaea12e6a2df97632358184ff

**Comment by muvaf** [comment]
I was thinking that `generateName` actually guarantees uniqueness but from what I can tell, that's [not the case](https://github.com/kubernetes/apiserver/blob/e9e4beec4b157a40f6c742782d74faf45c2b280e/pkg/storage/names/generate.go#L53). I think we can generate a reference, save it to `resourceRefs` and then create the resource with that name that we're sure saved to the composite resource.

**Comment by negz** [comment]
I haven't completely joined the dots, but I believe there is middleware that implements the described behaviour of `generateName`:

> If this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).

https://github.com/kubernetes/apiserver/blob/release-1.19/pkg/registry/generic/registry/store.go#L367
https://github.com/kubernetes/apiserver/blob/release-1.19/pkg/registry/rest/create.go#L137
https://github.com/kubernetes/apiserver/blob/release-1.19/pkg/registry/generic/registry/dryrun.go#L38

It seems like we can actually dry-run create in order to generate a name. Efficiency wise it's about the same as generating a name locally and dry-run creating it to see whether it's available, but I prefer to use GenerateName to ensure that our name generation logic never diverges from the API server's.

**Comment by muvaf** [comment]
Dry-run sounds good. As mentioned in https://github.com/crossplane/crossplane/pull/1916 , it gives a clue to users about the errors before creating anything, which is a nice UX plus.
