### ISSUE TITLE
latest pre-release versions are incorrect

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#1913]
### What happened?

The latest provider versions (e.g. `provider-azure`) don’t have `-rc` in their versions anymore: https://hub.docker.com/repository/docker/crossplane/provider-azure/tags?page=1

A bigger problem though is that the latest published versions of providers are saying that they are pre-releases for the last official version, e.g. pre-releases of v0.12, when they should be pre-releases of v0.13 (the upcoming version)

This appears to be caused by the fact that v0.12 and v0.13-rc tags are pointing to the same commit. `git describe`, which we use to generate version numbers, considers the age of tags: https://git-scm.com/docs/git-describe#_search_strategy

> tags with newer dates will always be preferred over tags with older dates

The v0.12 tag was applied after the v0.13-rc tag to the same commit, so recent builds from master are picking up the v0.12 tag during their `git describe` and generating a pre-release version based off that old version.

**Comment by hasheddan** [comment]
This should be noted (tagging new release before rc) in the update to the release process guide https://github.com/crossplane/crossplane/issues/1831, which will be part of the v0.14 release

**Comment by hasheddan** [comment]
@jbw976 I think this has been corrected and is documented in #1949. Do you think this can be closed out?

**Comment by jbw976** [comment]
sounds good, thanks for getting this sorted out @hasheddan!
