### ISSUE TITLE
Should package revisions watch the objects they control

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1923]
### What problem are you facing?

I believe the `ProviderRevision` and `ConfigurationRevision` controllers currently do not watch the objects they control (i.e. Deployment, ServiceAccount, CRD, XRD, and Compositions), and thus do not react immediately to reset changes made to those objects. The controllers instead speculatively requeue every 60 seconds.

### How could Crossplane help solve your problem?

The revision controllers could watch the objects they are a controller reference of such that a reconcile would be queued for the revision when any of those objects changed. I believe this would allow us to avoid having the revision controllers speculatively reconcile every 60 seconds.

**Comment by negz** [comment]
That said, we might not want to duplicate the knowledge of what types might be packaged (that knowledge is currently cleanly contained in `objScheme`. If there was some way to extract instances of all types known to that scheme we could presumably do something like:

```go
	b := ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.ProviderRevision{})

	for _, o := range GetTypes(objScheme) {
		b = b.Owns(o, &handler.EnqueueRequestForOwner{OwnerType: &v1alpha1.ProviderRevision{}, IsController: true})
	}

	return b.Complete(r)
```

**Comment by hasheddan** [comment]
> That said, we might not want to duplicate the knowledge of what types might be packaged

I actually don't think this is an issue as this information will be passed at controller setup time, and we are already doing package-specific things there, such as setting hooks to run.
