### ISSUE TITLE
Expand Helm chart to support provider(s)'s installation

### ISSUE THREAD

**Issue by iAnomaly** [crossplane/crossplane#1945]
### What problem are you facing?

We try to use Helm as the single, holistic tool for managing Kubernetes resources. Because of this, the `kubectl crossplane install provider` step of Crossplane's installation breaks this model (it makes perfect sense for users who don't want Helm/want exclusive kubectl support!).

### How could Crossplane help solve your problem?

First and foremost is the disclaimer that I'm ignorant to what `kubectl crossplane install provider` is doing under the hood, but assuming it is possible, I'd love to see the Helm chart expanded to support installing provider(s) this way. This would pave the way for adding the provider's ServiceAccount annotation for AWS EKS IAM Roles for ServiceAccounts (IRSA) for example.

**Comment by jbw976** [comment]
@iAnomaly thanks for expressing your interest in this functionality! I believe what you're looking for is already possible, as briefly mentioned here (not super obvious) in the docs: https://crossplane.io/docs/v0.14/introduction/providers.html#installing-providers

Essentially, the crossplane helm chart lets you set values for what providers to also install along with Crossplane itself, e.g.:
```
helm install crossplane --namespace crossplane-system crossplane-alpha/crossplane --set provider.packages={crossplane/provider-aws:master}
```

**Comment by muvaf** [comment]
I'm going to close this issue. @iAnomaly please feel free to reopen if you think there is more to do here.
