### ISSUE TITLE
Use a consistent CLI framework

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1953]
### What problem are you facing?

When the new Crossplane CLI was introduced we chose to use [kong](https://github.com/alecthomas/kong), which is the successor to [kingpin](https://github.com/alecthomas/kingpin). However, core Crossplane and the RBAC managed still use kingpin (as well as all providers). 

### How could Crossplane help solve your problem?

Using a consistent CLI framework requires less contextual knowledge for maintainers and new contributors, and kingpin is now in maintenance mode. We should move Crossplane and the RBAC manager to using kong. We could also consider using kong in each of the providers, but that is less of a priority.

**Comment by mikelo** [comment]
if help is still needed, I'd be glad to help on this one
