### ISSUE TITLE
Support download of single CRD manifest per release, for import into tools like cdk8s

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1961]
### What problem are you facing?
Tool like cdk8s can import CRDs for a given release by pulling all CRD definitions from a single file:
 - `cdk8s import https://github.com/knative/serving/releases/download/v0.19.0/serving-crds.yaml`
    - imports all CRDs defined in the [serving-crds.yaml](https://github.com/knative/serving/releases/download/v0.19.0/serving-crds.yaml) from the release assets: https://github.com/knative/serving/releases
 - `cdk8s import k8s@1.15.0` ([src](https://github.com/awslabs/cdk8s/blob/master/packages/cdk8s-cli/src/import/k8s.ts#L201))
    - pulls from https://github.com/instrumenta/kubernetes-json-schema
    - is generated from the k8s swagger.json ([src](https://github.com/instrumenta/kubernetes-json-schema/blob/master/build.sh#L174))
 - using cdk8s.yaml 
   - https://github.com/awslabs/cdk8s/blob/master/examples/typescript/crd/cdk8s.yaml
   - list of imports

To get the Crossplane CRDs you have to find and import **each** CRD:
 - Crossplane core:
   - https://github.com/crossplane/crossplane/tree/v0.14.0/cluster/charts/crossplane/crds
   - https://github.com/crossplane/crossplane/tree/v0.14.0/docs/api-docs/crds
 - Crossplane provider-aws: https://github.com/crossplane/provider-aws/tree/v0.14.0/package/crds

Also available CRDs can vary from release to release, so bumping versions in your cdk8s.yaml imports you have to:
 - figure out which CRDs were added / removed, update the list
 - update the version in each CRD url you want to import

### How could Crossplane help solve your problem?
Make a single CRD manifest available for each release of Crossplane Core and the Providers

Some ideas:
a.  Release assets include a single CRD manifest for crossplane, provider-aws, etc.
    - Knative includes `serving-crds.yaml` in release assets: https://github.com/knative/serving/releases
b.  [doc.crds.dev](https://doc.crds.dev) support downloading a single CRD manifest for each project / version
    - already indexes the full list of CRDs
    - would be generally useful for other projects
    - https://github.com/crdsdev/doc/issues/92

**Comment by hasheddan** [comment]
@prasek this can actually be done right now with kustomize --> `kustomize build github.com/crossplane/crossplane/cluster/?ref=v0.14.0`. We could easily generate a single file from this and serve it in the repo as well :) I would also like to support on doc.crds.dev, but would defer to get it working for crossplane sooner

**Comment by prasek** [comment]
@hasheddan sounds good, would be great to get it for all the providers as well in time for v1.0.

**Comment by prasek** [comment]
related to https://github.com/crossplane/crossplane/issues/1955 

/cc @eladb

**Comment by prasek** [comment]
> this can actually be done right now with kustomize --> `kustomize build github.com/crossplane/crossplane/cluster/?ref=v0.14.0`

@hasheddan note we'd also need https://github.com/crossplane/crossplane/tree/v0.14.0/docs/api-docs/crds in the list to define `crossplane.yaml` in cdk8s

**Comment by hasheddan** [comment]
@prasek gotcha :+1:

**Comment by hasheddan** [comment]
@prasek @eladb you can now get the aggregated CRD YAML for all repos at each tag on https://doc.crds.dev by prefixing path with `raw/` 

Example: https://doc.crds.dev/raw/github.com/crossplane/crossplane@v0.14.0

@prasek feel free to close this out if you feel it has been addressed appropriately :)

**Comment by prasek** [comment]
awesome thanks @hasheddan !

**Comment by prasek** [comment]
note you can now `cdk8s import github:crossplane/crossplane@0.14.0` with https://github.com/awslabs/cdk8s/pull/378 🚀
