### ISSUE TITLE
Default to registry.upbound.io when pulling packages

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1965]
### What problem are you facing?

Currently, the package manager falls back to Docker Hub when pulling a package with no registry supplied. With the newly imposed [rate limiting](https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/), users can run into issues if they pull too frequently, especially in a scenario where `packagePullPolicy: Always`. Also note that the forthcoming dependency management feature will count as a pull when doing a `GET` request on tags for a image repo.

### How could Crossplane help solve your problem?

[registry.upbound.io](https://cloud.upbound.io/browse) offers unlimited pulls, free repository hosting, and additional Crossplane-specific package parsing. All community-managed providers will be available on the registry, and if the package manager defaults to it, then users will only have to use short names, such as `crossplane/provider-gcp`, rather than `registry.upbound.io/crossplane/provider-gcp`.

**Comment by negz** [comment]
@hasheddan Is it worth making the default registry a flag? I wonder whether doing so could potentially make the upgrade/cutover process less disruptive. Credit to @lukeweber for the idea.

**Comment by hasheddan** [comment]
@negz that should be straightforward to do :+1:
