### ISSUE TITLE
Add providers for Metal3 (aka MetalKube) and Kubevirt

### ISSUE THREAD

**Issue by aakash-sahai** [crossplane/crossplane#1975]
### What problem are you facing?
Using Kubernetes as a signular control plane for managing infrastructure is our goal to simplify the operations of diverse infrastructure. We intend to use Metal3 to manage baremetal servers from K8s, and virtualized infrastucture using Kubevirt. Crossplane's value will be enhanced manyfold with the addition of provider for Metal3 and Kubevirt, for people who want to run Kubernetes on Baremetal and Container-native-virtualizatrion on their on-prem infrastructure in addition to running K8s in Cloud.

**Comment by hasheddan** [comment]
@aakash-sahai this sounds like a great idea! Are you interested in working on this? If so, I would be happy to get a repo set up for you in @crossplane-contrib :)

**Comment by hasheddan** [comment]
Following up, any desire to work on this @aakash-sahai?

**Comment by luebken** [comment]
Regarding Metal 3 I found https://github.com/metal3-io/baremetal-operator.  We should reach out to Metal3 and see if we can collaborate on a Metal3 provider for Crossplane.

**Comment by jeanduplessis** [comment]
@fabiand if there's an existing Terraform provider for it, then the easiest lift would likely be to use https://github.com/upbound/upjet to create a Crossplane provider for it.

**Comment by fabiand** [comment]
A crossplane provider for kubevirt got started - https://github.com/kubevirt/terraform-provider-kubevirt - we now need to see if somebody has capacity to combine this with upjet
