### ISSUE TITLE
Consider a switch to structured logging (k8s.io/klog)

### ISSUE THREAD

**Issue by kasey** [crossplane/crossplane#1976]
### What problem are you facing?

Our logs are semi-structured, json payloads in whitespace delimited log lines. Our logs also contain the occassional unstructured stack trace. Moving to structured logs has a number of well-understood advantages, as touched on in the k8s blog post on the topic:
https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/ 

### How could Crossplane help solve your problem?

Crossplane could switch to the same logging package as the core kubernetes community, `k8s.io/klog/v2`. This is a [standalone package](https://github.com/kubernetes/klog/) which [would not impact our dependencies](https://github.com/kubernetes/klog/blob/master/go.mod) on other packages in the kubernetes ecosystem.

**Comment by negz** [comment]
I believe our logs should only be semi-structured when run in debug mode, where they're intended to be more human readable. If you run in production mode (i.e. omit the `-d` flag) they should be fully structured JSON.

I'm fairly resistant to changing how we log. Quite a lot of thought went into the existing implementation; https://github.com/crossplane/crossplane-runtime/blob/1b691ef/pkg/logging/logging.go#L17

**Comment by kasey** [comment]
With the additional context from @negz, I'll update this issue to instead suggest that we create a separate flag to control structure independent of log level.

**Comment by kasey** [comment]
on second thought, I'm closing this in favor of https://github.com/crossplane/crossplane/issues/1977
