### ISSUE TITLE
Generating all services available in ACK with v1alpha1 support

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1980]
### What problem are you facing?

We have started using [AWS ACK generation pipeline](https://github.com/aws/aws-controllers-k8s/pull/449) to generate managed resources for provider-aws. The first batch was [API Gateway v2 Services](https://github.com/crossplane/provider-aws/pull/416).

We would like to generate all available services in ACK for provider-aws in v1alpha1 quality, which means at least basic proper create & delete functionality. This includes a group of different API styles.

### How could Crossplane help solve your problem?

All services in ACK should be generated and made available in provider-aws.

**Comment by muvaf** [comment]
https://github.com/crossplane/crossplane/issues/1845 tracks only the type generation and I believe this is mostly achieved by https://github.com/crossplane/provider-aws/pull/416 . However, controller code for all services is more tricky and this issue covers that.

**Comment by muvaf** [comment]
At the moment, issues are opened for all services available in ACK:
* SNS https://github.com/crossplane/provider-aws/issues/451
* SFN https://github.com/crossplane/provider-aws/issues/450
* ElastiCache https://github.com/crossplane/provider-aws/issues/449
* ECR https://github.com/crossplane/provider-aws/issues/448
* DynamoDB https://github.com/crossplane/provider-aws/issues/447

**Comment by negz** [comment]
We're now have v1alpha1 implementations of all available resources in ACK, and are moving onto a strategy to keep up with newly added resources.
