### ISSUE TITLE
Consider changing release channel names for v1.0

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1981]
### What problem are you facing?

Currently, our release channels (`alpha` and `master`) are not indicative of the type of release a user is consuming. The `alpha` channel is really the latest stable version.

### How could Crossplane help solve your problem?

The smallest change would be to just rename `alpha` to `stable`, but it may also make sense to maintain an `rc` channel for pre-release versions that we intend for community testing.

**Comment by jbw976** [comment]
For v1.0, we should just promote to the `stable` channel. No renaming would be needed I believe.

**Comment by hasheddan** [comment]
@jbw976 awesome! Thanks for that info :) Looks like `build` submodule` will create a new directory in bucket for the channel if it doesn't already exist 👍
