### ISSUE TITLE
Configuration of installed dependencies

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#1985]
### What problem are you facing?

#1971 adds functionality to automatically install dependencies for a package that are declared in the `crossplane.yaml`. However, those dependencies are created with the default package settings, so things like `packagePullSecrets` do not flow through.

### How could Crossplane help solve your problem?

It would be nice if users could configure their package dependencies, especially if they are coming from a private registry. This is a potentially difficult issue to solve though because packages can share a dependency, and determining the one that should be able to dictate its configuration is not straightforward. In the short-term, we allow for modifications of a package that is installed as a dependency, so manual edits can be made.

**Comment by ytsarev** [comment]
For us, it would be very convenient if we could package
* ControllerConfig
* ProviderConfig
Especially, it would be great if ProviderConfig would be properly applied after the associated provider becomes Ready.

**Comment by ytsarev** [comment]
So far used this workaround for waiting
```
kubectl wait --for=condition=Healthy providers crossplane-provider-aws
```
