### ISSUE TITLE
Can I use crossplane to provision a k8s cluster

### ISSUE THREAD

**Issue by gyliu513** [crossplane/crossplane#1990]
I can see there are some discussion by using cluster api to provision k8s cluster at https://github.com/crossplane/tbs/tree/master/episodes/11 , but what is the plan to enable crossplane to support this or does crossplane has other solutions to manage clusters?

**Comment by muvaf** [comment]
Hi @gyliu513 ! Yes, you can provision anything cloud providers offer as long as its support is implemented in its Crossplane provider. Here you can see how to provision a cluster together with all networking stuff using composition feature https://crossplane.io/docs/v0.14/getting-started/package-infrastructure.html

But you can also simply create the CRs and get it up and running. You can find the examples in `examples` folder of [`provider-aws`](https://github.com/crossplane/provider-aws/), [`provider-gcp`](https://github.com/crossplane/provider-gcp/), [`provider-azure`](https://github.com/crossplane/provider-azure). For their most up-to-date API reference, you can take a look at https://doc.crds.dev/

Feel free to reopen if that doesn't answer your question 🙂
