### ISSUE TITLE
[Question] Can I create a k8s cluster with some addon operators

### ISSUE THREAD

**Issue by gyliu513** [crossplane/crossplane#1992]
I can use crossplane to provision a k8s cluster, but here the question is only provisioning a k8s cluster is not enough, as I also need to enable the k8s cluster has some add operators, like logging, monitoring etc, so is it possible to let the crossplane to provision a k8s cluster with some add-on operators?

**Comment by hasheddan** [comment]
@gyliu513 absolutely! This is a good example here of deploying EKS clusters with Prometheus installed: https://github.com/upbound/platform-ref-aws

Feel free to join our [Slack](http://slack.crossplane.io/) if you would like to discuss specific your specific use-case or get any assistance in implementing a `Configuration` :) 

If this answers your question, you are welcome to go ahead and close out this issue.

**Comment by gyliu513** [comment]
Thanks @hasheddan , this is exactly what I want, let me close it. I have joined the slack channel, and will post some questions there if needed ;-)

**Comment by gyliu513** [comment]
@jianh619 ^^

**Comment by morningspace** [comment]
Hi @hasheddan a quick question re: ttps://github.com/upbound/platform-ref-aws. It appears the Prometheus there is installed using provider-helm. Have people in the community discussed sort of provider that supports [operator](https://github.com/operator-framework)-based install? This would be a helpful as we have lots of apps installed using go-operator.

**Comment by jbw976** [comment]
@morningspace i think operator-framework based operators are exactly what this community provider-in-cluster is solving: https://github.com/crossplane-contrib/provider-in-cluster

take a look at that! :)

**Comment by morningspace** [comment]
@jbw976 That is awesome... I am seeing it declares that in-cluster provider supports OLM. I will try it and get back here where there's any further query. Thanks!
