### ISSUE TITLE
Allow use of private images

### ISSUE THREAD

**Issue by tompscanlan** [crossplane/crossplane#2010]
I need to be able to use private images.

## What I'm doing:

```
kubectl create namespace crossplane-system

helm repo add crossplane-alpha https://charts.crossplane.io/alpha
helm repo update
helm install crossplane --namespace crossplane-system crossplane-alpha/crossplane --set alpha.oam.enabled=true --set image.repository=harbor-repo.vmware.com/dockerhub-proxy-cache/crossplane/crossplane --set oam-kubernetes-runtime.image.repository=harbor-repo.vmware.com/dockerhub-proxy-cache/crossplane/oam-kubernetes-runtime

# install kubectl plugins for crossplane
curl -Lf -o /tmp/install-crossplane.sh "https://raw.githubusercontent.com/crossplane/crossplane/release-${crossplane_version}/install.sh"
sh -x /tmp/install-crossplane.sh
mv kubectl-crossplane /usr/local/bin/
kubectl crossplane install provider harbor-repo.vmware.com/octo_ace/provider-aws:${aws_provider_version}
```

I'd expect the package install would use my referenced image.

## What happens:

The deployment for provider-aws is referencing the public image instead.

```
kc describe -n crossplane-system pod/provider-aws-1c3e0ed6179a-597b7f9db6-kc4hr

Name:         provider-aws-1c3e0ed6179a-597b7f9db6-kc4hr
Namespace:    crossplane-system
Priority:     0
Node:         test-control-plane/172.17.0.2
Start Time:   Fri, 04 Dec 2020 15:14:57 -0500
Labels:       pkg.crossplane.io/revision=provider-aws-1c3e0ed6179a
              pod-template-hash=597b7f9db6
Annotations:  <none>
Status:       Running
IP:           10.244.0.7
IPs:
  IP:           10.244.0.7
Controlled By:  ReplicaSet/provider-aws-1c3e0ed6179a-597b7f9db6
Containers:
  provider-aws:
    Container ID:   containerd://21c069710de1514ea999619aed1c4ea1ca20135ba449c120442713c4ec5c3d39
    Image:            crossplane/provider-aws-controller:v0.14.0
    Image ID:       docker.io/crossplane/provider-aws-controller@sha256:bb4b4ff13360c88ae4e6df6fe014f54279d70643daacf052523a1eea23eb2ae6
....
```

## Why?

I think it may be this line https://github.com/crossplane/provider-aws/blob/83fc1b6f5cf3ebb31be6efa191a4affa76e485e1/package/crossplane.yaml#L32

## Fix ?

I'm not sure, but you should be able to get the full image name from the command line when doing a package install and re-write to use that image name.

**Comment by hasheddan** [comment]
@tompscanlan to get the images on your private registry did you rebuild and push or just sync? If the latter, the controller image is baked in, but you can override it by referencing a `ControllerConfig` https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1#spec-image

Example here: https://github.com/crossplane/crossplane/pull/1905#issue-511679507

Also note that you will need to add `packagePullSecrets` to authenticate https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Provider/v1beta1

**Comment by tompscanlan** [comment]
Excellent! I'll accept that answer. Thanks!

**Comment by jbw976** [comment]
@hasheddan do we have an example in the docs similar to what you shared in https://github.com/crossplane/crossplane/pull/1905#issue-511679507?  i wonder if more folks will go looking for this topic in the docs.

**Comment by hasheddan** [comment]
@jbw976 not yet but we will :)
