### ISSUE TITLE
Following install instructions for providers in docs result in "Unknown command: install"

### ISSUE THREAD

**Issue by pdettori** [crossplane/crossplane#2016]
### What happened?

The instructions in the "Install & Configure Crossplane" section for installing a provider do not seem to be correct.

### How can we reproduce it?

Follow the instructions in "Install & Configure Crossplane" up to running the command to install a provider, e.g.:

```shell
kubectl crossplane install provider crossplane/provider-aws:alpha
```
this results in the following error:

```shell
Unknown command: install
Usage: kubectl crossplane [-h|--help] [COMMAND]... [OPTION]... [ARGUMENT]...

Commands:
  package
  trace
  registry

-h, --help: Print usage
```

### What environment did it happen in?
* Crossplane version: v0.14
* Cloud provider or hardware configuration: any cloud provider
* Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-14T07:56:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution: kind
* OS: macOS 10.15.7

**Comment by hasheddan** [comment]
@pdettori I believe you have an old version of the crossplane CLI. You can install the new version here: https://crossplane.io/docs/v0.14/getting-started/install-configure.html#install-crossplane-cli

Feel free to close this out if it answers your questions :)

**Comment by pdettori** [comment]
@hasheddan thank you, it looks like I missed the part printed at the end of the shell script 

```shell
Run the following commands to finish installing it:

sudo mv kubectl-crossplane /usr/local/bin
kubectl crossplane --help
```
so I probably did this a while ago but not this time, and that explains why I had a older version even if I ran the script to install the plugin.

**Comment by bguruprasad** [comment]
Hi, The above link is broken now, could you please share the latest link?
