### ISSUE TITLE
docs: provider-gcp setup creates non default ProviderConfig

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#2017]
### What happened?

The docs on https://crossplane.io/docs/v0.14/cloud-providers/gcp/gcp-provider.html#setup-gcp-provider instruct the user to create a `ProviderConfig` named `gcp-provider`, which is incompatible with all the other docs for provisioning infrastructure, because they rely on using a default ProviderConfig (named "default").

### What environment did it happen in?
Crossplane version: v0.14.0

**Comment by jbw976** [comment]
Ivan @ Kiratech pointed this out, seeing if he wants to also fix this before just fixing ourselves :)

**Comment by idallaserra** [comment]
Dear, opened this PR https://github.com/crossplane/crossplane/pull/2026 , please forgive me if I am missing some step.
Thanks.
