### ISSUE TITLE
Updating a depended upon package can cause resolver to produce undesired package

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2032]
### What happened?

If a package is installed and later depended upon by another package, updating the depended upon package will cause the dependency resolver controller to produce a new package in the brief moment between the old revision removing itself from the `Lock` and the new one adding itself. This is only true if the depended upon package was not previously installed by dependency resolution _and_ the name of the package does not match the scheme chosen by the dependency resolver.

The simplest immediate partial fix would be to use the same naming scheme in the CLI and the dependency resolver.

### How can we reproduce it?

1. Installed `provider-aws` using CLI so it was given name `provider-aws`.
2. Installed `registry.upbound.io/xp/getting-started-with-aws:latest`, which depends on `provider-aws`.
3. Everything is fine.
4. Update `provider-aws` to new version.
5. In the interim between the old `provider-aws` revision removing itself from `Lock` and the new revision adding itself, the resolver create a package named `crossplane-provider-aws` which added itself to `Lock` and installed revision successfully.

This was not the worst scenario in my case because `getting-started-with-aws` still had a dependency version that satisfied its constraints, and it was functioning properly (despite the new revision for the original `provider-aws` package being in an unhealthy state). However, if a user is explicitly stating that they would like to update to a new version and instead get whatever the latest version in the constraints of `getting-started-with-aws` is, that would be a poor experience.

### What environment did it happen in?
Crossplane version: `v1.0.0-rc.0.130.g94f34fd3`

**Comment by hasheddan** [comment]
One option here would be for the package controller (i.e. the parent of the revision that is being updated), to take out a lock on the `Lock`. This could be done by adding a field to the `Lock` spec and setting it to the package UID when it is updating. This would signal to the dependency resolver controller not to create any new packages because a package that may satisfy a missing dependency is currently being updated. The revision controller would refuse to reconcile unless the revision's parent held the lock (or potentially no one held the lock, but would need to think a bit more about the implications of that).

**Comment by AaronME** [comment]
We encountered this behavior in our environments. (See [comment](https://github.com/crossplane/crossplane/issues/2219#issuecomment-1083424532).)

The guidance on using the same naming scheme as crossplane (<org>-<repo>) will help us moving forward. Are there any steps which could repair the case where we already have an Unhealthy provider stuck against a previously installed one?
