### ISSUE TITLE
AWS: getting started using db.t2.small does not work for everyone

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#2040]
### What happened?
Following "Provision Infrastructure" in getting-started, multiple users get issues provision PostgreSQL at
https://crossplane.io/docs/v1.0/getting-started/provision-infrastructure.html

### How can we reproduce it?
* Apply https://github.com/crossplane/crossplane/blob/master/docs/snippets/provision/aws.yaml#L7-L8 with region eu-north-1 or us-east-1 (not sure if it applies to all regions)

`kubectl describe` shows errors like:

#### us-east-1
```
Cannot create a db.t2.small database instance because there are no availability zones with sufficient capacity for non-VPC and storage type : gp2 for db.t2.small
```

#### eu-north-1
```
cannot create RDS instance: InvalidParameterValue: Invalid DB Instance class: db.t2.small
```

# Workaround
Change instance type to `db.t3.small`

### What environment did it happen in?
Crossplane version: 1.0.0, AWS provider 0.16.0

**Comment by muvaf** [comment]
Interesting, I just tested this a few hours ago with `us-east-1`, let me try it again

**Comment by muvaf** [comment]
The example YAML worked for me again in `us-east-1` region.

**Comment by chlunde** [comment]
Funny, but it does not work for everyone, and `us-east-1` might not be available for organizations in the EU/EEC. Availability of t2 might also depend VPC settings, given the error the other user got, I don't know.

![image](https://user-images.githubusercontent.com/131994/102249907-2c8fb780-3f03-11eb-94bf-4665fcd6b1f1.png)

**Comment by negz** [comment]
@chlunde Hrm - do you know if there are any zones/instance types that work uniformly across AWS? It seems like it could be tricky to guarantee that our getting started manifests could work unmodified for all comers.

**Comment by chlunde** [comment]
@negz nope, sorry, I'm fairly new to AWS.
But at least the error is visible with `kubectl describe rdsinstance rdspostgresql` :)

Feel free to close the issue.

**Comment by haarchri** [comment]
looks like in eu-north-1 in general no t2.* instances are available

`aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=t2.small --region eu-north-1 --output table`
```

----------------------------------------------------------
|              DescribeInstanceTypeOfferings             |
+--------------------------------------------------------+
```

vs.

`aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=t2.small --region eu-central-1 --output table`

```
----------------------------------------------------------
|              DescribeInstanceTypeOfferings             |
+--------------------------------------------------------+
||                 InstanceTypeOfferings                ||
|+--------------+-----------------+---------------------+|
|| InstanceType |    Location     |    LocationType     ||
|+--------------+-----------------+---------------------+|
||  t2.small    |  eu-central-1b  |  availability-zone  ||
||  t2.small    |  eu-central-1c  |  availability-zone  ||
||  t2.small    |  eu-central-1a  |  availability-zone  ||
|+--------------+-----------------+---------------------+|
```

**Comment by chlunde** [comment]
I think you can close this issue if it does not seem like a good idea to change the example to t3.
