### ISSUE TITLE
Have Crossplane repos use 'main' as the default branch

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2045]
### What problem are you facing?

`main` is a more inclusive name for the default branch of Crossplane repos than `master`, which was the default when we created the repos. `main` is now the default for all GitHub repos - I'd like us to consider switching over.

### How could Crossplane help solve your problem?

We should investigate how disruptive this change would be, and if it's low risk, we should make the change. More context at https://github.com/github/renaming.

**Comment by hasheddan** [comment]
@negz first step here would be changing the default branch for all newly created repositories to `main` in the project settings :+1:

**Comment by jbw976** [comment]
Looks like the default for new repos across the organization is now `main`:
![Screen Shot 2020-12-16 at 4 12 52 PM](https://user-images.githubusercontent.com/4313439/102421574-9c607980-3fb9-11eb-9fd3-e493583d9ce3.png)

**Comment by jbw976** [comment]
Let's take action on this issue finally - I was reminded of it last week and it was regrettable to say that we haven't done this yet 😞 

Looking at https://github.com/github/renaming#renaming-existing-branches, it appears that most everything is automated. I have confidence that contributors would be able to absorb this change with the instructions shown in an automatic notice on github and available in their [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes).

Any major dissent before pulling the trigger on this? 🤔

**Comment by elohmrow** [comment]
[GitLab did this 2 years ago](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/), so, yes please!
