### ISSUE TITLE
Save image tarballs to GH action output on PR builds

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2065]
### What problem are you facing?

Currently, we publish artifacts built in CI pipelines for a specific PR. This includes all binaries as well as the helm chart tarball.

### How could Crossplane help solve your problem?

While it doesn't make sense to push images to a registry, it may be useful to save the image tarballs to the output directory such that they can be downloaded and then used to `docker load` for testing, especially on non amd64 platforms that are not already tested in our CI.

**Comment by wonderflow** [comment]
I'm just curious what's the difference between local built image with the github actions built. Does it just for saving time?
