### ISSUE TITLE
Establish LTS schedule around releases

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2066]
### What problem are you facing?

With the release of crossplane v1.0.0 all minor versions moving forward should be backwards compatible. However, it is likely that we will want to retire service for versions when a sufficient number of subsequent versions have been released.

### How could Crossplane help solve your problem?

We should publish an official schedule for versions that are currently supported and what the scope of a supported version is (likely that we will backport any fixes to the release branch).

**Comment by muvaf** [comment]
I think it's worth to define what _support_ means in this context. It seems Kubernetes [defines it](https://kubernetes.io/docs/setup/release/version-skew-policy/) as:
> Applicable fixes, including security fixes, may be backported to those three release branches, depending on severity and feasibility. Patch releases are cut from those branches at a regular cadence, plus additional urgent releases, when required.

From what I can tell, the only kind of support Kubernetes provides is to ensure important fixes are backported. I think that's a good fit for us, too.
