### ISSUE TITLE
Provider authentication architecture design doc

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2070]
### What problem are you facing?

Crossplane providers currently authenticate to the API they interact with by referencing a `ProviderConfig` that in turn references a Kubernetes `Secret`. Some providers also allow for specifying [`InjectedIdentity`](https://github.com/crossplane/crossplane-runtime/blob/479dbc8a456086622ce1afab66aad11ba6c8f78d/apis/common/v1/resource.go#L200) such as IRSA or workload identity. The latter method is a more secure approach, but is restrictive in that:
1. A user must be using provider-aws on EKS to use something like IRSA (i.e. you could not use IRSA with provider-gcp, etc.).
2. Injected identity approaches restrict to a single identity on the cloud provider, meaning that a user could not have different ProviderConfigs with differently scoped credentials provided by injected identity.

### How could Crossplane help solve your problem?

Crossplane should facilitate providers authenticating to APIs in a consistent and extensible model. For instance, a user should be able to store credentials for a cloud provider in an external secret store (e.g. Vault, KMS, etc.), and consume them by creating a `ProviderConfig` that instructs the provider how to obtain the credentials.

One solution for this would be to have a sidecar process that was responsible for communicating with secret backends and injecting credentials into the provider filesystem using a shared volume. This would allow for providers to easily support an arbitrary number of secret backends because obtaining the credentials would be decoupled from the communicating with the secret store. This model is also advantageous because Crossplane controller the `Deployment` for an installed `Provider`, meaning it could easily inject the sidecar alongside the main provider process.

The architecture described in the design doc should take into account how connection details are also going to be published as part of #2068, but can be treated as a separate effort in design and implementation.

**Comment by muvaf** [comment]
Will this design doc address the multiple `ProviderConfig` use case? For example, I would have one `ProviderConfig` with IRSA and another one with Vault or even two different `ProviderConfig`s that targets different IAM Roles using IRSA. Since IRSA works in a role-per-pod model, I'm guessing some changes will be required in package manager.

**Comment by hasheddan** [comment]
@muvaf that is not the primary purpose here, and I am not sure we should try to take a system that is intended to work on a one-per-pod basis and force it into a many-per-pod model. Currently, outside of the IRSA case, you can have many `ProviderConfig`s for a provider, and the model proposed in this design doc would support many as well. It will essentially just make credentials available in the provider's filesystem so that k8s secrets do not have to be used.

**Comment by hasheddan** [comment]
Fixed by https://github.com/crossplane/crossplane-runtime/pull/240 and https://github.com/crossplane/crossplane/pull/2125
