### ISSUE TITLE
Lock resource prevents automated deletion of Crossplane

### ISSUE THREAD

**Issue by JasP19** [crossplane/crossplane#2079]
### What happened?

We are experiencing an issue when trying to delete Crossplane (providers and controllers) in an automated pipeline. The CRDs created as part of the Crossplane controller are not getting deleted due to the presence of the Lock.pkg.crossplane.io/v1alpha1 object.

The presence of the "lock.pkg.crossplane.io" finalizer on the Lock.pkg.crossplane.io/v1alpha object is preventing the Lock object from being destroyed which, in turn, stops the CRD's from destroying.

Manually executing the below command resolves the issue but it is not trivial to do this within the automated pipeline: `kubectl patch lock lock -p '{"metadata":{"finalizers": []}}' --type=merge`.

### How can we reproduce it?

Install Crossplane into a Kubernetes cluster. Once Crossplane is running, delete the installation and observe that it does not complete (fully delete all resources) until the patch command (above) is manually run to remove the finalizer from the Lock object.

### What environment did it happen in?
Crossplane version: 1.0.0
AWS EKS: 1.16

**Comment by negz** [comment]
@hasheddan Do you know if this issue is still relevant? I know we've made some changes to how the Lock is handled since it was raised.

**Comment by hasheddan** [comment]
@negz we now remove finalizers from the Lock when packages are uninstalled, which makes it easier to clean up, but the Lock and CRDs must still be manually cleaned up. So we have smooth uninstall / reinstall, but technically the Lock is still left behind on uninstall.

**Comment by muvaf** [comment]
The CRDs are now deployed by Crossplane itself, not Helm or kubectl, hence they are left in the cluster after the uninstallation. However, this usually doesn't cause a problem since no tool tries to delete them now as opposed to `helm delete` trying to clean up all what it installed. So it's probably not an issue anymore but feel free to re-open.
