### ISSUE TITLE
Persist CompositeResourceDefinition status schema

### ISSUE THREAD

**Issue by mcavoyk** [crossplane/crossplane#2081]
### What happened?

Any fields in XRD status sub-field is overwritten and not persisted to the offered CRDs.

### How can we reproduce it?

Apply the XRD yaml below.  The generated CRD's will have the default claim/composite status field with added fields not present. 

 <details>
    <summary>xrd-deploy.yaml</summary>
  <br></br>
<head class="lang-yaml">

    apiVersion: apiextensions.crossplane.io/v1
    kind: CompositeResourceDefinition
    metadata:
      name: compositedeploys.example.com
    spec:
      claimNames:
        kind: Deploy
        plural: deploys
        singular: deploy
      group: example.com
      names:
        kind: CompositeDeploy
        plural: compositedeploys
        singular: compositedeploy
      versions:
        - name: v1alpha1
          referenceable: true
          served: true
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  type: object
                  properties:
                    parameters:
                      type: object
                      properties:
                        namespace:
                          type: string
                        image:
                          type: string
                        replicas:
                          type: integer
                status:
                  type: object
                  properties:
                    readyReplicas:
                      type: integer
                    updatedReplicas:
                      type: integer
</head>
</details>

### What environment did it happen in?
Crossplane version: v1.0.0
Kubernetes version: v1.17.12

**Comment by negz** [comment]
Thanks for raising this @mcavoyk! This is expected (albeit poorly documented) behaviour at the moment given that we don't yet support bidirectional patching (i.e. a configurable way to derive XR status from composed resources). We'll need to change this behaviour to support https://github.com/crossplane/crossplane/pull/2077.
