### ISSUE TITLE
Installing configuration packages using crossplane helm chart

### ISSUE THREAD

**Issue by cheewaio** [crossplane/crossplane#2083]
### What problem are you facing?

After build a configuration package, I can install the package using the kubectl command
`kubectl crossplane install configuration <package>`

Is there a way to install the configuration package during crossplane helm chart installation?

### How could Crossplane help solve your problem?

I notice there is an option to specify provider packages in the crossplane helm chart. Is there a plan to support having the option to install configuration packages as well?

```
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version v1.0.0 \
    --set provider.packages[0]=<provider.package>
```

**Comment by hasheddan** [comment]
@cheewaio that would be pretty straightforward to add and I would certainly be in support of it :) Are you interested in working on this?

**Comment by cheewaio** [comment]
I will be glad to contribute
