### ISSUE TITLE
Suppress "object has been modified" warning events?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2114]
### What problem are you facing?

Crossplane relies heavily on Kubernetes events to help folks debug what it is doing. It's quite common for Crossplane to emit the following warning event:

```console
Warning  ConfigureCompositeResource  19s (x2 over 20s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot patch object: Operation cannot be fulfilled on compositenetworks.gcp.platformref.crossplane.io "test-network-d6xjh": the object has been modified; please apply your changes to the latest version and try again
```

We emit this event when two controllers race to update a resource. Kubernetes uses a form of optimistic concurrency in which each resource is versioned (via `metadata.resourceVersion`), and clients must have the latest version of the resource when attempting to update it. This means that if two clients get the same version of a resource then race to update it, the one that loses will encounter this error from the API server.

This is almost never a cause for concern; Crossplane will just try again. The event does make it appear like something is awry though, and is frequently a red herring for Crossplane users trying to debug unrelated issues.

### How could Crossplane help solve your problem?

Crossplane could detect this I think it manifests as a 409 Conflict, so we could detect it using a `resource.IsConfict(err)` helper and either completely suppress it or emit it as a `Normal` event.

In the meantime, this would be a good thing to add to an FAQ.

**Comment by muvaf** [comment]
If we omit this warning, I wonder whether we'd be in a situation where two controllers keep clashing but we just never notice. If it was a log, I'd say let's print it only in debug mode but I'm not sure if events have such leveling. Can we emit this in events but still log it in debug level?

**Comment by negz** [comment]
> Can we omit this in events but still log it in debug level?

We can - logging and eventing are different calls so we can do one or the other.

> If we omit this warning, I wonder whether we'd be in a situation where two controllers keep clashing but we just never notice.

I had the same thought. This could be a good thing to handle with metric instrumentation - i.e. make it possible to alert if this is happening too frequently.

**Comment by negz** [comment]
Related: https://github.com/crossplane/crossplane/issues/2472

**Comment by negz** [comment]
I'd still like to do this. I think it confuses a lot of people.

**Comment by ytsarev** [comment]
/fresh I believe 'object has been modified' is still around and confuses people from time to time

**Comment by ravilr** [comment]
@sttts change above should help towards reducing this noise right ? @jbw976  Any plans on when can we see this above xp-runtime lib change picked up by all xp providers releases ?  Thanks.

**Comment by sttts** [comment]
Yes. But it's only a partial solution. There are many places in Crossplane that don't handle conflict properly.
