### ISSUE TITLE
Unable to tag existing AWS IAMRole

### ISSUE THREAD

**Issue by kiich** [crossplane/crossplane#2118]
### What happened?
I followed your excellent doc at https://crossplane.io/docs/v0.12/introduction/managed-resources.html#importing-existing-resources where I have an existing IAM Role that I created with NO tag.

I then ran:
```
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: crossplane-import-test-name
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: crossplane-import-test
  namespace: crossplane-system
spec:
  forProvider:
      description: IAM role already created
      assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
          ]
        }
      tags:
        - key: Foo
          value: Bar
  providerRef:
    name: default
  providerConfigRef:
    name: default
```
The apply was a successful from what I can tell from `kubectl get iamrole` with:
```
  Normal  UpdatedExternalResource  64s (x10 over 8m50s)  managed/iamrole.identity.aws.crossplane.io  Successfully requested update of external resource
```
But in AWS console, I do not see the tags I added.

The IAM role does exist BUT does not have the tags nor the description but i was not under the impression that description had to match also?

**Comment by kiich** [comment]
Also to add, IAMRole created from Crossplane also does not seem to add tags so maybe I am doing something wrong?

**Comment by muvaf** [comment]
Hi @kiich ! Could you share the output of the following command?
```
kubectl get iamrole crossplane-import-test-name -o yaml
```

If the tags were there when you created the resource, they should appear in AWS console. But if you added them after the creation they won't get added. The `UpdateRoleInput` struct doesn't have a field for tags so we need to make separate call to update the tags.

**Comment by kiich** [comment]
Hey @muvaf - thanks for quick reply!
```
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  annotations:
    crossplane.io/external-name: crossplane-import-test
[...]
  name: crossplane-import-test-name
[...]
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
        ]
      }
    description: IAM role already created - update
    maxSessionDuration: 3600
    path: /
    tags:
    - key: Foo
      value: Bar
  providerConfigRef:
    name: default
  providerRef:
    name: default
status:
  atProvider:
    arn: xxx
    roleID: xxx
  conditions:
  - lastTransitionTime: "2021-02-05T11:54:49Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-02-05T11:54:49Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

>If the tags were there when you created the resource, they should appear in AWS console.

oh wait... are you saying I can not "add" a new tag to an imported resource?
My use-case is something like this:

1) Terraform creates our IAM roles but does not add any tags
2) We wanted to use Crossplane to import this role and add a tag there

Of course, we can add the tags in step 1 but for whatever reason, we are not. We were looking Crossplane for some other use case (such as enabling our users to create AWS resources) but found this imported-resource concept so wanted to see if that can do what we wanted.

**Comment by muvaf** [comment]
> oh wait... are you saying I can not "add" a new tag to an imported resource?

That's correct but I'm opening a PR right now to fix it. Hang in there 😄

**Comment by kiich** [comment]
ahh i see - thank you @muvaf, i shall wait with bated breath!

Closing this if that's ok with you then?

**Comment by kiich** [comment]
Oh wait but if I create an IAMRole from Crossplane from scratch, should I be expecting `tags` to work? Because that is not working neither.

**Comment by muvaf** [comment]
Opened https://github.com/crossplane/provider-aws/pull/528 The issue will close itself once the PR is merged.

> Oh wait but if I create an IAMRole from Crossplane from scratch, should I be expecting tags to work?

If you don't give any external name, it should work. If it doesn't for some reason, it should be fixed with the PR because I manually tested both scenarios.

**Comment by kiich** [comment]
Ok thanks - I was under the impression the following should work (as it is IAMRole I am creating using Crossplane and it is a new one so is not being imported) and since `tags` were mentioned in the doc, i expected to work? (but it does not)

```
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: crossplane-read-route53
  namespace: crossplane-system
spec:
  forProvider:
      description: IAM role created by Crossplane
      tags:
       - key: Foo
         value: Bar
      assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
          ]
        }
  providerRef:
    name: default
```

anyways, happy to wait until next release with fix in - thanks for your responses/help!

**Comment by muvaf** [comment]
Interesting, this one should work right now.

**Comment by kiich** [comment]
>Interesting, this one should work right now.

Sorry I should have been clearer.

If I create the IAMRole using Crossplane with NO tags, the next `kubectl apply` with with updated YAML file that has tags in, does not add the tag.

If I create the IAMRole using Crossplane with tags in the YAML file, it does indeed create the IAMRole with tag. I misunderstood your comment re:`UpdateRoleInput` and thought that call was only for IMPORTED resources but you were saying it is for ALL resources. (created by Crossplane as well as imported resources).

**Comment by muvaf** [comment]
> If I create the IAMRole using Crossplane with tags in the YAML file, it does indeed create the IAMRole with tag.

No worries. This is the case that should work today, yes. The rest will be enabled by the PR.
