### ISSUE TITLE
FieldPath reference for ConnectionDetails

### ISSUE THREAD

**Issue by krishchow** [crossplane/crossplane#2119]
### What problem are you facing?
Sometimes I would like to expose a field in the CR within the connectionDetails. Currently, there is no way to achieve this use we are using a constant value. 

### How could Crossplane help solve your problem?
Crossplane should include support in the composition to target a fieldPath for a secret.

**Comment by muvaf** [comment]
Is this duplicate of https://github.com/crossplane/crossplane/issues/1609 ?

**Comment by krishchow** [comment]
Yes it is! Thank you @muvaf
