### ISSUE TITLE
Add documentation for bidirectional patching

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2128]
### What problem are you facing?

Composition now supports bidirectional patching with @mcavoyk's work in https://github.com/crossplane/crossplane/pull/2077. However, it is not yet included in the composition documentation.

### How could Crossplane help solve your problem?

Add examples of using bidirectional patching to https://crossplane.io/docs/master/introduction/composition.html or consider breaking out the composition documentation into more sections as it has become more robust.

cc @negz @muvaf

**Comment by negz** [comment]
I think @mcavoyk mentioned he might take a shot at this. Did you ever get around to starting a PR?

**Comment by mcavoyk** [comment]
> I think @mcavoyk mentioned he might take a shot at this. Did you ever get around to starting a PR?

 I should have something available for review for the `introduction/composition` doc in a day or two :smile:

**Comment by muvaf** [comment]
Should be fixed by https://github.com/crossplane/crossplane/pull/2145
