### ISSUE TITLE
Unhealthy ConfigurationRevision stuck with resource ownership if unable to pull image

### ISSUE THREAD

**Issue by benagricola** [crossplane/crossplane#2135]
### What happened?
I was trying to update a `pkg.crossplane.io` `Configuration` to add a new field to an xrd - the new field was not being displayed on the xrd even though the latest `ConfigurationRevision` existed, as it was unhealthy. The latest `ConfigurationRevision` was unable to gain ownership of a resource that a previous, unhealthy `ConfigurationRevision` still had ownership of:

```
  Type     Reason       Age                  From                                              Message
  ----     ------       ----                 ----                                              -------
  Warning  SyncPackage  69s (x133 over 66m)  packages/configurationrevision.pkg.crossplane.io  cannot establish control of object: .... is already controlled by ConfigurationRevision resources-be36672de2b1 (UID ad389e10-a2e6-4ef7-aa41-59ce08e29930)
```

The `ConfigurationRevision` with ownership of the resource was unhealthy as it was referring to an image that no longer existed:

```
Events:
  Type     Reason        Age                       From                                              Message
  ----     ------        ----                      ----                                              -------
  Warning  ParsePackage  4m29s (x20455 over 7d3h)  packages/configurationrevision.pkg.crossplane.io  cannot initialize parser backend: failed to fetch package from remote: GET .../main-8276a3ce: MANIFEST_UNKNOWN: manifest unknown; map[Tag:main-8276a3ce]
```

7d3h as shown in the `ParsePackage` warning above coincidentally is the same age as the `crossplane` pods in the running cluster (which run on EKS Fargate) - so this indicates that the revision was applied and healthy in the past, but became unhealthy when the image was no longer available locally on pod restart (`packagePullPolicy: IfNotPresent`), and also did not exist remotely either).

I resolved this manually by deleting the old `ConfigurationRevision`, at which point the new one was able to take over ownership and went healthy.

### How can we reproduce it?
Apply a `Configuration` package pointing to a valid image, wait for it to go healthy. Delete the remote image and clear the local cache, and it _should_ start reporting a `ParsePackage` error. At that point, try and apply a new version of the `Configuration` package and watch as it never goes healthy, as it can't take ownership of the resources.

### What environment did it happen in?
Crossplane version: `v0.16.0`
On AWS EKS, running all crossplane pods on Fargate

**Comment by hasheddan** [comment]
@benagricola I think this is actually working as expected because if we don't have the old package image, we cannot be certain about what the contents of that package were. We could try to go through the resources that it has owner references on, or look in the `ConfigurationRevision` status for the list of objects, but I'm not sure this would actually be preferred when you can solve the problem by either:
- Deleting the old `ConfigurationRevision` as you did
- Re-adding the old image for the `ConfigurationRevision` to the package cache

What do you think?

**Comment by benagricola** [comment]
Yeah that's a fair assessment - without knowing for certain what resources a `ConfigurationRevision` is supposed to be managing (i.e. being able to read them from the image) it seems like it could be problematic to try to "guess" in some manner and accidentally release ownership of things.

I suppose it's worthwhile pointing that you need to keep the images available for each `ConfigurationRevision` until it has been deleted from the cluster even if it is not the active revision, otherwise you might possibly run into this (depending on what resources are in the configuration revisions).

**Comment by hasheddan** [comment]
@benagricola I definitely think that would be worthwhile to document 👍 I have also added this as a discussion item for today's [community meeting](https://docs.google.com/document/d/1q_sp2jLQsDEOX7Yug6TPOv7Fwrys6EwcF5Itxjkno7Y/edit?usp=sharing). This topic is pretty nuanced as I could see either behavior being viewed as more "correct" depending on how you view the responsibilities of Crossplane. Feel free to stop by the community meeting if you want to weigh in one way or the other :)
