### ISSUE TITLE
Updating the Crossplane Version available on OperatorHub

### ISSUE THREAD

**Issue by krishchow** [crossplane/crossplane#2136]
### What problem are you facing?
The current version of Crossplane available on [OperatorHub](https://operatorhub.io/operator/crossplane) is outdated, and it was last published May 25, 2020, meaning it is around 9 months old now. I have been several discussions in the Crossplane Slack, and directly with customers who would like a more updated version to be available on OperatorHub, and that is a common way people manage that operators installed in their cluster via OLM.

### How could Crossplane help solve your problem?
Although getting the most recent version of Crossplane available on OperatorHub would be a nice start, ideally we can update the release process such that we can the packaging step for Crossplane for free. This way all that needs to be done at release time is a PR needs to be opened on the [community-operators](https://github.com/operator-framework/community-operators) repository.

**Comment by krishchow** [comment]
I would be happy to help out with this process, @hasheddan I know there is a release of Crossplane coming up. I could shadow that process for Crossplane so I can feel for the release workflow, then we could move forward from there?

**Comment by negz** [comment]
Hey @krishchow - thanks for volunteering to help out with this! We'd like to switch this OperatorHub entry over to Upbound's certified distribution of Crossplane. I'm going to close this issue for the time being, but we'll get back to you ASAP to figure out how to proceed.
