### ISSUE TITLE
Panic during Composition transform

### ISSUE THREAD

**Issue by mcavoyk** [crossplane/crossplane#2141]
### What happened?

Panic occurs during composite reconciliation while applying a patch transform.

<details>
    <summary>panic.log</summary>
  <br></br>
<head class="lang-console">

    E0216 16:05:35.959498       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
    goroutine 667 [running]:
    k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19570c0, 0x2d158b0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:74 +0x92
    k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:48 +0x82
    panic(0x19570c0, 0x2d158b0)
            /opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
    github.com/crossplane/crossplane/apis/apiextensions/v1.(*ConvertTransform).Resolve(0xc0017d6640, 0x0, 0x0, 0x123981a, 0xc001594d48, 0x40a36a, 0x193b400)
            /home/runner/work/crossplane/crossplane/apis/apiextensions/v1/composition_types.go:576 +0x6a
    github.com/crossplane/crossplane/apis/apiextensions/v1.(*Transform).Transform(0xc001594e68, 0x0, 0x0, 0x0, 0x0, 0x1f219a0, 0xc0017d7800)
            /home/runner/work/crossplane/crossplane/apis/apiextensions/v1/composition_types.go:427 +0x136
    github.com/crossplane/crossplane/apis/apiextensions/v1.(*Patch).applyFromFieldPathPatch(0xc001595088, 0x7f69ea2815f0, 0xc000377958, 0x7f69ea2b0528, 0xc000377f08, 0x197fb60, 0x1b661c0)
            /home/runner/work/crossplane/crossplane/apis/apiextensions/v1/composition_types.go:330 +0x1f1
    github.com/crossplane/crossplane/apis/apiextensions/v1.(*Patch).Apply(0xc001595088, 0x7f69ea2815f0, 0xc000377958, 0x7f69ea2b0528, 0xc000377f08, 0xc001595038, 0x1, 0x1, 0x0, 0x0)
            /home/runner/work/crossplane/crossplane/apis/apiextensions/v1/composition_types.go:277 +0x187
    github.com/crossplane/crossplane/internal/controller/apiextensions/composite.(*APIDryRunRenderer).Render(0xc0004c1900, 0x1f63000, 0xc00158d7a0, 0x1fa1040, 0xc000377958, 0x1f9b420, 0xc000377f08, 0x0, 0xc0000e2000, 0x37a, ...)
            /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composite/composed.go:353 +0x85f
    github.com/crossplane/crossplane/internal/controller/apiextensions/composite.(*Reconciler).Reconcile(0xc00003a9a0, 0x1f63000, 0xc00158d7a0, 0x0, 0x0, 0xc000b9ab00, 0x15, 0xc0015b4200, 0x0, 0x0, ...)
            /home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composite/reconciler.go:425 +0x1c01
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004672c0, 0x1f62f80, 0xc0007037c0, 0x19c6080, 0xc00150ee80)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293 +0x2f1
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004672c0, 0x1f62f80, 0xc0007037c0, 0x0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248 +0x202
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1f62f80, 0xc0007037c0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211 +0x4a
    k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0x37
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0014fdf50)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001595f50, 0x1f20560, 0xc0015b4210, 0xc000703701, 0xc0012de5a0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0xa3
    k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0014fdf50, 0x3b9aca00, 0x0, 0x1, 0xc0012de5a0)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
    k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1f62f80, 0xc0007037c0, 0xc0015b8000, 0x3b9aca00, 0x0, 0x1)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185 +0xa6
    k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1f62f80, 0xc0007037c0, 0xc0015b8000, 0x3b9aca00)
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99 +0x57
    created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
            /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:208 +0x4f9
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
            panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x14dc6ba]
</head>
</details>

### How can we reproduce it?

Don't have a full example as the composition this transform in is a bit large and specific, but was able to trace issue with a debugger.

When the `fromFieldPath` is nil, previously the patch would [exit early](https://github.com/crossplane/crossplane/blob/v1.0.0/apis/apiextensions/v1/composition_types.go#L266), now the patch [continues to apply](https://github.com/crossplane/crossplane/blob/v1.1.0-rc.1/apis/apiextensions/v1/composition_types.go#L325) the transform.

```yaml
        # previous behavior was to exit early if fromFieldPath was nil
        - fromFieldPath: "spec.parameters.someField"
          toFieldPath: "spec.forProvider.someField"
          transforms:
            - type: convert
              convert:
                toType: string
```

### What environment did it happen in?
Crossplane version: v1.1.0-rc.1
Cloud provider: AWS
Kubernetes distribution: EKS
Kubernetes version: v1.17.12

**Comment by hasheddan** [comment]
Thanks for opening this @mcavoyk! I believe I have found the issue in https://github.com/crossplane/crossplane/commit/d749355cec7f2f1de1a820ebbb42a943a74fa8ca and am working on a fix now.

**Comment by mcavoyk** [comment]
@hasheddan Yeah that seems like the commit. Thanks for letting me know you are working on it so we don't duplicate effort :+1:
