### ISSUE TITLE
Consider promoting builds on release branches

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2148]
### What problem are you facing?

When cutting the `release-1.1` branch, I noticed that we don't [promote builds](https://github.com/crossplane/crossplane/blob/da8a48e5d9cf40a07b8484a8d310923d869b1c0f/.github/workflows/ci.yml#L313) unless the branch is `master`. This means that the only way for users to easily consume builds from release branches are if the [promotion pipeline](https://github.com/crossplane/crossplane/blob/master/.github/workflows/promote.yml) is manually run. This has made sense in the past as we typically did not cut release branches until we were ready to actually tag the release. However, in the new [release process](https://crossplane.io/docs/v1.1/contributing/release-process.html) we are cutting the branch ~2 weeks before the first minor version and immediately tagging `master` with the `rc.0` for the next minor. If we did not immediately tag `master` with the next `minor`, it is possible we could have two builds that look very similar in version. For instance, the [empty commit](https://github.com/crossplane/crossplane/pull/2139) that advanced `master` for the new `rc.0` built and promoted a version `crossplane-1.1.0-rc.1.2.g53a79d2b`. The second diverged commit on the `release-1.1` branch could also produce a build `crossplane-1.1.0-rc.1.2.gXXXXXXXX`, which would look a little weird (i.e. the only difference would be the hash on the end). However, from that `v1.2.0-rc.0` tag onward, the builds would not conflict. Also, if we tag that empty commit fast enough (using automation as described in #2144), we can actually have it be used for the base version for the build produced.

### How could Crossplane help solve your problem?

We should consider promoting release branch builds to either the `master` channel or a specific channel for that release branch. It feels a little strange promoting to `master` since the build is not literally from the `master` branch, so a dedicated release branch channel might make the most sense. However, we could also adopt the strategy of a `dev` channel that holds all non-release builds.

**Comment by muvaf** [comment]
Is this still relevant? `stable` is where we promote releases from release branches.
