### ISSUE TITLE
Use proper backoff across core controllers

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2157]
### What problem are you facing?

We recently [updated](https://github.com/crossplane/crossplane-runtime/pull/243) the `crossplane-runtime` [managed reconciler](https://github.com/crossplane/crossplane-runtime/blob/30a941c3c3c67e4dc064a2a170cb725de40b0271/pkg/reconciler/managed/reconciler.go#L473) to make use of the controller's configured rate limiting strategy, and provided some sane [default implementations](https://github.com/crossplane/crossplane-runtime/blob/30a941c3c3c67e4dc064a2a170cb725de40b0271/pkg/ratelimiter/default.go#L42) for controllers that are reconciling managed resources. We do not currently make use of rate limiting in most cases (other than [failed status updates](https://github.com/crossplane/crossplane/blob/d9afc165cd5335703483b4671b0ca0c751038d63/internal/controller/pkg/manager/reconciler.go#L357)) across the Crossplane core controllers. In some cases, a proper rate limiting / backoff strategy would be advantageous. A good example would be [dependency resolution](https://github.com/crossplane/crossplane/blob/d9afc165cd5335703483b4671b0ca0c751038d63/internal/controller/pkg/revision/reconciler.go#L411), which currently uses a 30s `shortWait`. This frequently leads to long waiting for a `Configuration` package to become ready because `30s` is either far too long to wait, or it resolution takes just over `30s` and we don't check again for another `30s`. An exponential backoff strategy with a higher base delay (potentially a value around `~5s`) and a relatively low capped max delay (`30s`) would likely be more appropriate for this scenario.

### How could Crossplane help solve your problem?

We should examine our current short / long delay settings and see if there are cases where we should use rate limiting / backoff.

**Comment by negz** [comment]
@hasheddan adding myself as an assignee, as I'd like to help with this. Let me know if you've started anything and/or really want to tackle it yourself.

**Comment by muvaf** [comment]
Is this still relevant?
