### ISSUE TITLE
Create a security disclosure policy + process (SECURITY.md)

### ISSUE THREAD

**Issue by caniszczyk** [crossplane/crossplane#2191]
A CNCF graduation requirement is having a security disclosure process.

Feel free to look at examples in the CNCF ecosystem https://github.com/envoyproxy/envoy/blob/main/SECURITY.md

Other prior art from Rook: https://github.com/rook/rook/blob/master/SECURITY.md

**Comment by hasheddan** [comment]
@jbw976 @negz @bassam tagging steering committee members here, I would be happy to open a proposal for this for review 👍

**Comment by bassam** [comment]
Thanks - @jbw976 are you able to take this one?
