### ISSUE TITLE
Restrict ability for multiple K8s clusters to manage the same resource

### ISSUE THREAD

**Issue by jbhennin** [crossplane/crossplane#2193]
### What problem are you facing?

The `crossplane.io/external-name` allows you to specify the external name of the resource and not use generated name by crossplane.  

With the use of external name it is possible that 2+ K8s clusters can manage the same resource.
This can cause problems and conflicting state.

### How could Crossplane help solve your problem?

With the aws you can potentially use tags in order to restrict but other providers may not have this available.

Not sure how we can solve with Crossplane but open to ideas.

**Comment by negz** [comment]
I agree this functionality would be nice to have, and tags (or whatever metadata is available to us) seems like the right place for it. The trick is that tag (or more generally metadata) support is super inconsistent, even within a single provider like AWS. I wrote some ideas up at https://github.com/crossplane/crossplane-runtime/issues/254 that may help with this a little.
