### ISSUE TITLE
Old inactive revision can create deleted resource before new active one

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2197]
### What happened?

This is a pretty big edge case, but in the case that we encounter an issue like the one describe in #2165, it is possible that deleting the CRD in question will not solve the issue because the old revision controller could create it before the new revision. When the new revision creates it first there is no issue because we only update owner refs for inactive revisions:

https://github.com/crossplane/crossplane/blob/ce0aa068438419cc5a766c227955a3d38230662f/internal/controller/pkg/revision/establisher.go#L150

However, if the old revision is reconciled first is see that the CRD doesn't exist and creates it:

https://github.com/crossplane/crossplane/blob/ce0aa068438419cc5a766c227955a3d38230662f/internal/controller/pkg/revision/establisher.go#L122

### How can we reproduce it?

See situation described in https://github.com/crossplane/provider-aws/issues/583 (thanks for pointing out @patjones!).

### What environment did it happen in?
Crossplane version: v1.1.0

**Comment by kelvinwijaya** [comment]
Hi @hasheddan 

Regarding the issue reported in https://github.com/crossplane/provider-aws/issues/583

Would like to clarify, say if the NatGateway resources are created before in v0.16.0, does that mean deleting the old CRD of the affected resource will cause the external resource to be deleted

What is the procedure after deleting the old CRD, does the Managed Resources version has to be patched for version bump?

I am worry about the actual resources get deleted as it is production load

Thanks,
Kelvin

**Comment by hasheddan** [comment]
@kelvinwijaya if you have `NatGateway` instances that exist, they will block deletion of the CRD. Since `NatGateway` was an `alpha` API in `v0.16.0` it did not guarantee support of that version in future `provider-aws` iterations. In `v0.17.0`, the API was [promoted to `v1beta1`](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/NATGateway/v1beta1@v0.17.0) and support for [`v1alpha1`](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/NATGateway/v1alpha1@v0.16.0) was dropped. In order to migrate, I would perform the following steps:
1. Set all of your current `v1alpha1` `NatGateway` types to have [`deletionPolicy: Orphan`](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/NATGateway/v1beta1@v0.17.0#spec-deletionPolicy).
2. Save copies of all the instances locally (make sure to include the `external-name` annotation).
3. Delete all of the `NatGateway` instances in the cluster. They should not be deleted on AWS because they have `deletionPolicy: Orphan`.
4. Delete the `NatGateway` CRD.
5. Wait for it to get re-created at `v1beta1` version and for the new `ProviderRevision`  to become healthy.
6. Modify all your local `NatGateway` instance copies to adhere to `v1beta1` schema (once again, make sure you preserve the `external-name` annotation).
7. Apply your local copies of the `NatGateway` instances with `v1beta1` schema. Because the `external-name` is set and the resources already exist on AWS, the new `provider-aws` revision should pick up reconciling them correctly.
8. You may optionally switch `deletionPolicy` back to `Delete` if you would like the resources to be cleaned up on AWS in the future when they are deleted in the cluster.

Let me know if you have any questions about this workflow!

**Comment by kelvinwijaya** [comment]
Hi @hasheddan ,

This workflow sounds very detailed and workable, I assumed it will work as well for claim-composite model where the `crossplane.io/external-name` tags to be presented when creating the claim resources.

I will do more testing on this part as well

Btw, is there any future pipeline for version conversion functions with webhook implementation [conversion-concept](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html) ? 
So as to have 2 different versions supported at the same time


Thanks,
Kelvin

**Comment by hasheddan** [comment]
@kelvinwijaya yep we hope to support webhooks very soon, the work is being tracked in https://github.com/crossplane/crossplane/issues/1152. That being said, there is no guarantee on supporting `alpha` version APIs from one release to the next, so transitions like this are not guaranteed to be supported even when we do support webhooks.

**Comment by kelvinwijaya** [comment]
Hi @hasheddan 

Ok understood and cheers.

**Comment by bandesz** [comment]
Just leaving a note here about seeing the same issue. I was upgrading provider-aws from 0.16 to 0.18.

I've got the following errors:
```
32m         Warning   SyncPackage               providerrevision/crossplane-provider-aws-c9c270c95bd4                           cannot establish control of object: CustomResourceDefinition.apiextensions.k8s.io "routetables.ec2.aws.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha4": must appear in spec.versions
41m         Warning   SyncPackage               providerrevision/crossplane-provider-aws-c9c270c95bd4                           cannot establish control of object: CustomResourceDefinition.apiextensions.k8s.io "bucketpolicies.s3.aws.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": must appear in spec.versions
```

Deleting the CRDs didn't help as they were recreated shortly containing the same old versions.

The only way I could fix this was deleting the old provider revision.

@hasheddan does this mean, that the only way currently to safely upgrade a provider like this is to do a manual migration for existing resources, following the instructions from https://github.com/crossplane/crossplane/issues/2197#issuecomment-796818872?
