### ISSUE TITLE
Enhance unit test standard to validate API calls

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#2235]
### What problem are you facing?

Currently, almost all controller unit tests do not check whether the provider API is (or is not) called with the expected parameters. This is OK in `TestObserve` as the provider state is (ideally) not modified. However, in `TestCreate`, `TestUpdate` and `TestDelete` I consider this a substantial flaw since the test only checks if an error has occurred, but not whether the provider API was invoked correctly. Currently, the test essentially only compare the state of `cr` before and after the invocation.

As @negz pointed out in the discussion on Slack, implementing whitebox introduces a lot of complexity since these kind of tests are dependent on the internal implementation of the controller and need to be rewritten once it changes (see [this blog post by Google](https://testing.googleblog.com/2013/08/testing-on-toilet-test-behavior-not.html)).

However, I would argue that external API calls are not part of the internal implementation since this is what I want as a Crossplane user. And thus they should be part of a blackbox test.

### How could Crossplane help solve your problem?

I would like unit tests to check whether or not the API was called as expected. It would ensure Crossplane is working with the provider as intended and help detect bugs earlier.

### How could this problem be solved

Right now I could think of two possible solutions:

#### Enhance with mocked provider client with call log

The MockClient contains a list for each func where the arguments of each invocation are stored.

```golang
// MockDocDBClient for testing
type MockDocDBClient struct {
	docdbiface.DocDBAPI
	MockCreateDBInstanceWithContext    func(context.Context, *docdb.CreateDBInstanceInput, []request.Option) (*docdb.CreateDBInstanceOutput, error)
	Called MockDocDBClientCall
}
// MockDocDBClientCall to log calls
type MockDocDBClientCall struct {
	CreateDBInstanceWithContext    []*CallCreateDBInstanceWithContext
}
// CallDescribeDBInstancesWithContext to log call
type CallDescribeDBInstancesWithContext struct {
	Ctx  aws.Context
	I    *docdb.DescribeDBInstancesInput
	Opts []request.Option
}
// DescribeDBInstancesWithContext calls MockDescribeDBInstancesWithContext
func (m *MockDocDBClient) DescribeDBInstancesWithContext(ctx aws.Context, i *docdb.DescribeDBInstancesInput, opts ...request.Option) (*docdb.DescribeDBInstancesOutput, error) {
	m.Called.DescribeDBInstancesWithContext = append(m.Called.DescribeDBInstancesWithContext, &CallDescribeDBInstancesWithContext{Ctx: ctx, I: i, Opts: opts})
	return m.MockDescribeDBInstancesWithContext(ctx, i, opts)
}
```

and this is compared in the unit tests with what is `want`ed

```golang
type want struct {
		cr     *svcapitypes.DBInstance
		result managed.ExternalCreation
		err    error
		docdb  fake.MockDocDBClientCall    // <---- added this line
}
```

#### Use go-mock

Another possible solution would be to golang's (go-mock)[https://pkg.go.dev/github.com/golang/mock/gomock] package to automize mocking and use `EXPECTED` to verify API calls. Something like this: 

```golang
mockDocDBClient.EXPECT().DescribeDBInstancesWithContext(
	context.Background(),
	input,
)
```

What are your thoughts?

**Comment by negz** [comment]
@MisterMX Thanks for raising this! In the past I've _partially_ addressed this by just having the mock method blow up if it is called with the wrong input. e.g.:

```go
c := &MockDocDBClient{
	MockCreateDBInstanceWithContext: func(_ context.Context, i *docdb.CreateDBInstanceInput, _ ...request.Option) (*docdb.CreateDBInstanceOutput, error) {
		if diff := cmp.Diff(tc.want.input, i); diff != "" {
			return errors.Errorf("CreateDBInstanceWithContext(...): -want, +got:\n %s", diff)
		}
		return nil, nil
	}
}
```

This goes a long way, but it does have some shortcomings. Namely that it doesn't handle multiple calls well, and doesn't catch cases where the expected call isn't made at all.

I like that your "call log" approach feels like a scoped iteration on our current testing practices, rather than a big change. I am curious about how go-mock would fit into our testing patterns. I wonder if the next step here could be to open a PR that updates an existing test to use one of the proposed mock approaches. i.e. Something where we can review a clean diff between an existing test and the proposed approach?

**Comment by MisterMX** [comment]
I added some sample test cases for Secretsmanager in provider-aws using `go-mock` (seems there are no tests for Secretsmanager at all?). See crossplane/provider-aws/pull/611

Basically, mocking a client in crossplane tests would like this:

```golang
args: args{
    mock: func(msma *fake.MockSecretsManagerAPI) {
        msma.EXPECT().
            DescribeSecretWithContext(
                gomock.Eq(context.Background()),
                gomock.Eq(
                    &svcsdk.DescribeSecretInput{
                        SecretId: awsclient.String(testExternalName),
                    },
                ),
            ).
            Return(&svcsdk.DescribeSecretOutput{}, nil).
            Times(1)
        msma.EXPECT().
            GetSecretValueWithContext(
                gomock.Eq(context.Background()),
                gomock.Eq(
                    &svcsdk.GetSecretValueInput{
                        SecretId: awsclient.String(testExternalName),
                    },
                ),
            ).
            Return(&svcsdk.GetSecretValueOutput{
                SecretString: awsclient.String(testSecretString),
            }, nil).
            Times(1)
    },
},
```

and setting it up before running the test case:

```golang
for name, tc := range cases {
    t.Run(name, func(t *testing.T) {
        ctlr := gomock.NewController(t)
        client := fake.NewMockSecretsManagerAPI(ctlr)
        if tc.args.mock != nil {
            tc.args.mock(client)
        }

        // other stuff
    }
}
```

I see some benefits using this solution:

1. `go-mock` is part of golang and thus well maintained
2. Mocks can be generated using `mockgen'
3. It allows for more complex mocking, such as different return values for different calls

However, with `EXPECT()` we are setting up expected parameters and return types in `args` instead of using `want`, which does not fit as nicely into the current declarative testing approach (though we could move mocking to `want`, which, on the other hand, would feel wrong, too).

What do you think?

**Comment by muvaf** [comment]
@MisterMX does `go-mock` make sure the calls are made in that order? For example, does it fail if `GetSecretValueWithContext` is called before `DescribeSecretWithContext`?

**Comment by MisterMX** [comment]
@muvaf no, I don't think so. I just tested it with the code above and still passed. My custom solution also does not provide it.

Would you consider it an important feature?

**Comment by MisterMX** [comment]
FYI: I uses `go-mock` to mock the client in `eks.addon` tests:

https://github.com/crossplane/provider-aws/blob/134596c10049c7ccdc2887a3192e60095ad3d35e/pkg/controller/eks/addon/setup_test.go#L110

`go-mock` is used more extensively by us in `provider-styra` where we've also added a `go:generate` directive to generate the client during `make generate`:

https://github.com/crossplane-contrib/provider-styra/blob/0c3bf4ce81d92d4be4ade86bf0612c8127c4969d/pkg/client/mock/generate.go#L19
