### ISSUE TITLE
Update kubectl-crossplane plugin to simplify IAM permissions management

### ISSUE THREAD

**Issue by lewismarshall** [crossplane/crossplane#2236]
### What problem are you facing?

As a platform team / maintainer, it is a complex and problematic and error prone process working out what cloud provider permissions are required for each and every provider resource for each cloud.

This prevents constrained permissions to be managed and this in turn prevents simple audit or in the worst case over privileged access.

### How could Crossplane help solve your problem?

If each provider had a common way to express exact IAM permissions, then the kubectl plugin could simply list the access required for any given resource with a command like:

```
kubectl crossplane get-iam-permissions provider-resource-name
```
A further command to create the right IAM objects directly could be envisioned but this would need cloud account access first and maybe best managed by platform providers and their tools?

This is closely related to the issues below regarding self documented permissions:
- https://github.com/crossplane/provider-gcp/issues/300
- https://github.com/crossplane/provider-aws/issues/514
- https://github.com/crossplane/provider-azure/issues/239

**Comment by ndlanier** [comment]
Please re-open
