### ISSUE TITLE
cli: add a option to turn on verbose/debugging output

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#2237]
### What problem are you facing?

As a crossplane 1st time user
* in order to troubleshoot cli usage 
* and in order to better understand what `kubectl crossplane install configuration registry.upbound.io/upbound/platform-ref-aws:v0.1.0` command in https://cloud.upbound.io/docs/getting-started/configure-your-platform/#install-our-example-configuration is doing
* I need a way to turn on debugging/verbose output 

### Observed behavior

With a network configuration issue, the cli silently fails without friendly hint

```
$ kubectl crossplane install configuration registry.upbound.io/upbound/platform-ref-aws:v0.1.0
$ echo $?
1

# No hint about a verbose/debug flag
$ kubectl crossplane install --help
Usage: kubectl crossplane install <command>

Install Crossplane packages.

Flags:
  -h, --help       Show context-sensitive help.
  -v, --version    Print version and quit.

Commands:
  install configuration <package> [<name>]
    Install a Configuration package.

  install provider <package> [<name>]
    Install a Provider package.

```

plain kubectl usage provides a friendly error message pointing to network connectivity issue ( in my case the `https://proxy.upbound.io/env/<guid>` wasn't directly reacheable from internal corp network. Internet access is only granted from http proxy whose details are in a `http_proxy` env var)
```
$ kubectl get configuration.pkg.crossplane.io
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by hasheddan** [comment]
Thanks for opening this @gberche-orange! I definitely think we should improve error messaging across the commands, and this silent failure is a good example. Are you interested in working on this?

**Comment by gberche-orange** [comment]
Thanks @hasheddan for considering this issue. 
> Are you interested in working on this?

It's too early for me now: I'm merely discovering the product now and contributing feedback along the way. I might be interested in the future to contribute code if the product gets used within my team and my team backlog priorities aligns.

**Comment by psinghal20** [comment]
Hi @hasheddan, I would be interested in taking this issue up. I believe the code for the cli lives in `cmd/crank`. I will start taking a look into it. Please let me know if you have any ideas regarding this. :slightly_smiling_face:

**Comment by psinghal20** [comment]
Hi @hasheddan, I found the cause of this silent failure here which was due to `ctrl.GetConfigOrDie` function call which triggered a call to `os.Exit(1)` in case of any errors. I have replaced these with their error returning variants, for better error handling. I wanted to know if I should go ahead in adding a `verbose` flag and logging statements in different commands for each step.
