### ISSUE TITLE
Unable to install crossplane in AWS EKS

### ISSUE THREAD

**Issue by plentifullee** [crossplane/crossplane#2247]
### What happened?

Pod is in a "CrashLoopBackOff" status.

Error: failed to start container "crossplane": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/home/nonroot") set in config.json failed: permission denied: unknown

### How can we reproduce it?

Create a new EKS cluster in AWS, create a new node group, login to your cluster using:
aws eks update-kubeconfig --name <cluster_name>

Try to install crossplane:
kubectl create namespace crossplane-system
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

### What environment did it happen in?
Crossplane version: 
crossplane-1.1.0 stable

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by muvaf** [comment]
Thanks for raising this issue @plentifullee ! https://github.com/crossplane/crossplane/pull/2245 should fix this. If you'd like to, you can try the latest image in `alpha` channel to test it out. We're planning to have a patch release 1.1.1 with that fix.

**Comment by plentifullee** [comment]
Good to know, thanks!

**Comment by hasheddan** [comment]
@plentifullee v1.1.1 release is now live as well :)
