### ISSUE TITLE
Consider publishing version markers

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2257]
### What problem are you facing?

Currently Crossplane supports installation from the `stable` and `master` channels, with the former being the latest release (not necessarily the latest version), and the latter being the latest build from the `master` branch. Because we are [now maintaining the most recent 3 minor versions](https://crossplane.io/docs/v1.1/reference/release-cycle.html), that means that installing the latest from `stable` could mean that a user is installing a patch release from any of those three branches (if they do not specify version).

### How could Crossplane help solve your problem?

Crossplane could consider publishing "version markers", which are essentially just files that use a vanity name for releases. For instance, we could publish a `stable-1.txt` which contained the version for the latest patch on the latest minor, and a `stable-2.txt` and `stable-3.txt` for the latest patches on the two latest patches on the previous two minors. Similarly, we could also have `latest-1.1`, `latest-1.0`, etc. markers. These would be auto-updated in the release process, and would make it easier to identify and consume the latest patch for various maintained versions. It would also enhance automated testing as versions can be referred to generically (i.e. test upgrading from `stable-1` to `stable-2` rather than having to update the explicit versions in the tests).

**Comment by muvaf** [comment]
This is related to what `helm install crossplane --namespace crossplane-system crossplane-stable/crossplane` would select when you don't give `--version` flag, right? How does version markers affect that workflow?

**Comment by hasheddan** [comment]
> How does version markers affect that workflow?

I don't know if it necessarily changes the workflow, but it could allow for things like `helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version $(curl <releases-url>/latest-1.0.txt)`. I don't think helm has any native support for something like "install the latest patch of this minor version". This is likely most useful for the automated testing scenario where we want to be testing the latest patches of the last three minor versions.

**Comment by muvaf** [comment]
Got it, sounds good to me.
