### ISSUE TITLE
Late initialize XRC spec.compositionRef

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2263]
### What happened?

A composite resource claim (XRC) is a namespaced proxy for a composite resource (XR). Both types have an almost identical schema. When an XRC is created an XR is typically created in response, and the claim's `spec.compositionRef` and `spec.compositionSelector` are propagated to the XR. Currently if you create a claim with only a composition selector, or with neither a reference or a selector (relying on the XRD's default or enforced composition) the claim's composition reference is never updated to reflect the composition selected by the XR.

We mostly "late initialize" a claim from its XR, but when doing so we ignore any fields shared with the XR. This includes the composition reference, selector, etc: https://github.com/crossplane/crossplane/blob/39217a2c44c73d32e16364bf6a8bbcab72910ed3/internal/controller/apiextensions/claim/configurator.go#L149

### How can we reproduce it?

Create a claim with a composition selector and no composition reference (e.g. the GCP claim from the Crossplane 1.1 getting started guide) and observe that the XR has its composition reference set, but the claim never does.

### What environment did it happen in?
Crossplane version: 1.1

**Comment by RinkiyaKeDad** [comment]
Hey @negz sorry for the late response. I tried what you suggested and looks like the fix in this PR is working! These are the results I got after [running](https://crossplane.io/docs/v1.5/getting-started/provision-infrastructure.html#claim-your-infrastructure) `kubectl apply -f https://raw.githubusercontent.com/crossplane/crossplane/release-1.5/docs/snippets/compose/claim-gcp.yaml`:


1. `kubectl get composite my-db-ggvz9 -o yaml`:

```
apiVersion: database.example.org/v1alpha1
kind: XPostgreSQLInstance
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"database.example.org/v1alpha1","kind":"PostgreSQLInstance","metadata":{"annotations":{},"name":"my-db","namespace":"default"},"spec":{"compositionSelector":{"matchLabels":{"provider":"gcp"}},"parameters":{"storageGB":20},"writeConnectionSecretToRef":{"name":"db-conn"}}}
  creationTimestamp: "2021-12-09T07:55:34Z"
  generateName: my-db-
  generation: 4
  labels:
    crossplane.io/claim-name: my-db
    crossplane.io/claim-namespace: default
    crossplane.io/composite: my-db-ggvz9
  name: my-db-ggvz9
  resourceVersion: "7221"
  uid: 37bb5f02-df7c-4910-be3c-afac10d9eccb
spec:
  claimRef:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
    name: my-db
    namespace: default
  compositionRef:
    name: xpostgresqlinstances.gcp.database.example.org
  compositionSelector:
    matchLabels:
      provider: gcp
  compositionUpdatePolicy: Automatic
  parameters:
    storageGB: 20
  resourceRefs:
  - apiVersion: database.gcp.crossplane.io/v1beta1
    kind: CloudSQLInstance
    name: my-db-ggvz9-snfhm
  writeConnectionSecretToRef:
    name: 37bb5f02-df7c-4910-be3c-afac10d9eccb
    namespace: crossplane-system
status:
  conditions:
  - lastTransitionTime: "2021-12-09T07:55:34Z"
    reason: Creating
    status: "False"
    type: Ready
  connectionDetails:
    lastPublishedTime: "2021-12-09T07:57:04Z"
```

2. `kubectl get claim my-db -o yaml`:

```
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"database.example.org/v1alpha1","kind":"PostgreSQLInstance","metadata":{"annotations":{},"name":"my-db","namespace":"default"},"spec":{"compositionSelector":{"matchLabels":{"provider":"gcp"}},"parameters":{"storageGB":20},"writeConnectionSecretToRef":{"name":"db-conn"}}}
  creationTimestamp: "2021-12-09T07:55:34Z"
  finalizers:
  - finalizer.apiextensions.crossplane.io
  generation: 3
  name: my-db
  namespace: default
  resourceVersion: "6935"
  uid: 185ce6fb-b600-423a-bc3c-c7e9b9241cec
spec:
  compositionRef:
    name: xpostgresqlinstances.gcp.database.example.org
  compositionSelector:
    matchLabels:
      provider: gcp
  compositionUpdatePolicy: Automatic
  parameters:
    storageGB: 20
  resourceRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
    name: my-db-ggvz9
  writeConnectionSecretToRef:
    name: db-conn
status:
  conditions:
  - lastTransitionTime: "2021-12-09T07:55:34Z"
    reason: Composite resource claim is waiting for composite resource to become Ready
    status: "False"
    type: Ready
```



Both the XR and the XRC now have `compositionRef` and `compositionSelector` set. Could you please point me to some similar unit tests I could look at before adding the ones for this change?

Thanks for your patience!
