### ISSUE TITLE
Add support for building on M1 apple Silicon

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#2279]
### What problem are you facing?
The build process for submitting pull requests in https://github.com/crossplane/crossplane/blob/5bf01691dfb914df79962bf6bd830d2a3cd98942/CONTRIBUTING.md#establishing-a-development-environment doesn't work on Apple Silicon-based Mac computers. 

### How could Crossplane help solve your problem?
Update the `cluster/local/kind.sh` script to:
- support ARM64 targets 
- update `KUBE_IMAGE` to support arm64 images

**Comment by stevendborrelli** [comment]
Resolving this depend ons upstream PR https://github.com/kubernetes-sigs/kind/pull/2176.

**Comment by muvaf** [comment]
Seems like the PR you referred is merged and there is a new [release](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.0) including it. @stevendborrelli Would you mind testing it and updating kind version wherever needed?

**Comment by stevendborrelli** [comment]
I've been testing the build targets. It mostly works but there are a few issues I am tracking down, including the go-junit tool not being downloaded.

**Comment by negz** [comment]
> including the go-junit tool not being downloaded.

I'm pretty sure we could just remove this from Crossplane builds; I don't think anything uses it anymore.

**Comment by jbw976** [comment]
Building, installing, running a local build with `make` and `kind.sh` works great for me now on my new M1 laptop.  I suspect a lot has been figured out in the ecosystem (e.g. a new version of kind) since this issue was opened.  Closing now since I think the mainline scenario is OK now!
