### ISSUE TITLE
Default Provider Service Account always created when overridden in ControllerConfig 

### ISSUE THREAD

**Issue by benagricola** [crossplane/crossplane#2295]
### What happened?
Configuring `provider-aws` to use an existing IRSA-configured service account using the following `ControllerConfig`:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws
spec:
  serviceAccountName: crossplane-aws-provider
```

We end up with our existing `crossplane-aws-provider` as well as an [automatically created](https://github.com/crossplane/crossplane/blob/d04a059fe341a941760a3a94ef07085ae7158365/internal/controller/pkg/revision/deployment.go#L40) service account, which then has the `ClusterRoleBinding` applied to allow it to manage resources.

This means we have 1 service account with the right permissions to manage AWS resources and 1 with the right permissions to manage crossplane resources, but zero that can handle both:

```
$ k get sa -n crossplane-system | grep aws
aws-4ebd5d8c7cb7                              1         7m22s  # Crossplane-created with Cluster role binding
crossplane-aws-provider                       1         72m    # eksctl-created with IRSA role binding
```

### How can we reproduce it?
Create a service account manually, use the above `ControllerConfig` to configure a provider and watch as you get 2 service accounts with mixed permissions.

### Suggested fix
Do not create the service account if name is overridden by `ControllerConfig` `serviceAccountName`.

Ideally use the existing service account name when requesting permissions from the RBAC manager. I'm not sure if this is possible as rbac manager uses the `owner` reference to [work out what SA to apply the binding to](https://github.com/crossplane/crossplane/blob/d04a059fe341a941760a3a94ef07085ae7158365/internal/controller/rbac/provider/binding/reconciler.go#L172). When the service account is not created by crossplane, it might be necessary to add an additional check to the binding provider (linked above) to make sure it doesn't try to create a `ClusterRoleBinding` with no subjects.

### What environment did it happen in?
Crossplane version: master on EKS

**Comment by ONordander** [comment]
Hi, could we get any information from maintainers regarding this?
Having the ability to specify the ServiceAccount and get the correct RBAC settings would really help our usecase.

**Comment by wwentland** [comment]
This issue is still present, please reopen.

**Comment by wwentland** [comment]
/fresh

This can still be reproduced, please re-open.

**Comment by macmiranda** [comment]
I'm still seeing the same behavior on 1.9.1
