### ISSUE TITLE
Support providing package pull credentials via methods other then secrets

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2319]
### What problem are you facing?

Currently, packages can be pulled from private repositories by providing credentials in the form of a Kubernetes `Secret` that is [referenced](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Provider/v1@v1.2.1#spec-packagePullSecrets) from the `Configuration` or `Provider`. This works well, but requires that users provide credentials via this single method.

### How could Crossplane help solve your problem?

`go-containerregistry` supports loading credentials from implementations of its [Keychain](https://github.com/google/go-containerregistry/blob/8b535fa90f33fcb5121d422e3a51b37e25e46096/pkg/authn/keychain.go#L38) interface. It provides a default implementation for loading credentials from a Docker config file, which we currently do not take advantage of due to the fact that the config file is not present inside of the container when Crossplane is running. We should support mounting credentials to the Crossplane `Pod` (potentially using something like the `Vault` agent which we use to [provide credentials](https://crossplane.io/docs/v1.2/guides/vault-injection.html) for a `Provider`), then referencing the path via flag or environment variable to load these credentials as part of the package pull keychain.

**Comment by psinghal20** [comment]
Hi @hasheddan, I looked into this issue and had some observations regarding this issue which I would love to discuss here. I primarily used this blog for provider credentials through vault as a starting point for my exploration: https://crossplane.io/docs/v1.3/guides/vault-injection.html

- To fetch PackagePullSecrets from the vault, we need to feed the core `crossplane` deployment with vault secrets. We can achieve this similar to the above-linked blog post, using the vault injector to inject secrets directly into the pod. We can add a section for adding annotation through `values.yaml`. The only con I see is the need to patch core crossplane annotations for each new secret required. If this would be a nuisance for users, we can use some kind of client to fetch the secrets from the vault using the `kv` path from package pull secrets.

- Currently, the `packagePullSecrets` field looks something like this:
```
packagePullSecrets:
   - name: string
```
I think we can change it to something like this:
```
packagePullSecrets:
   type: k8sSecrets/file
   file: path to file (optional, used when type is file)
   secrets: (optional, used when type is k8sSecrets)
      - name: string
```
The file could be the docker config to be used to fetch the packages configured with the authentication. I believe the file type secret would give us the flexibility to use any secret store which allows mounting secrets into pods. We can even mount the k8s secrets and use them like this.

- I looked into the `defaultKeychain` implementation in the `go-containerregistry` repo and found that the default keychain uses the environment variable `DOCKER_CONFIG` to fetch docker config. For our use case, we would want to fetch this docker config from the path where the secret is mounted, so we should maybe add our implementation for dockerKeychain resembling most of the `defaultKeychain` logic, but using our custom path provided from the packagePullSecrets File path.

- One more thing I noticed was that the fetcher object, used to fetch packages is set at the start of reconcile loop, which would need to be chosen dynamically based on the type of packagePullSecrets if we go with the above approach. 

These are some of my initial thoughts regarding how we can go ahead with implementing this feature. Please let me know what you think about this.
