### ISSUE TITLE
Lock can be lost on upgrades (or a while after upgrades)

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2323]
### What happened?

In #2321 we added functionality to remove the `finalizer` on the singleton `Lock` when the number of installed packages == 0. This makes it simpler to uninstall Crossplane and delete its CRDs without having to manually remove a finalizer. However, as exposed in the test mentioned below, upgrading from a version prior to `v1.2.0` (where we switched to managing our CRDs via init container in https://github.com/crossplane/crossplane/pull/2160) can cause issues (**even if you first upgrade to `v1.2.x`**) because when the singleton `Lock` went from being created by Helm to not being present in the next chart version, meaning Helm deletes it (i.e. its `deletionTimestamp` is set). The reason why this has not been a problem thus far is because we _never_ removed the finalizer, so the `Lock` singleton was existing forever even though its `deletionTimestamp` was set. However, as soon as we remove that finalizer, as we now do in #2321, the `Lock` will get cleaned up, making all subsequent package revision reconciliations fail.

The simple solution for an end user that experiences this is to delete the `core` Crossplane `Pod` and let the `Deployment` recreate it, at which point our `initContainer` will recreate the `Lock`. However, it would be nice to automatically recover from this in case the `Lock` gets deleted in any case, which can be accomplished by having any revision that notices that the `Lock` does not exist recreate it. 

### How can we reproduce it?

The exact scenario is demonstrated in https://github.com/crossplane/test/runs/2645918064?check_suite_focus=true.

### What environment did it happen in?
Crossplane version: `v1.1.0` --> `v1.3.0-rc.0.40.gd005048b`

**Comment by muvaf** [comment]
Does that mean that people who installed configurations or providers via helm install will loose those CRs when they upgrade to 1.2.x?

**Comment by hasheddan** [comment]
@muvaf I have not verified, but it sounds like it is possible that they could. The `initContainer` should recreate them, but any CRs for CRDs in that package would have been lost.

**Comment by muvaf** [comment]
I will test installing 1.1.x with provider CRs, create a few CR and then upgrade to 1.2.x with `--reuse-values`. If we lose any CR or CRD, then it's probably a showstopper for 1.2.x.

**Comment by muvaf** [comment]
I am able to reproduce this issue for all CRs we create during installation of 1.1.x. Fortunately, helm allows you to keep resources by adding an [annotation](https://github.com/helm/helm/issues/7839#issuecomment-605884428): `helm.sh/resource-policy: keep`. So we can add a section to `Upgrading to 1.2.x` doc with the following command that will add this annotation to all `Lock`, `Provider` and `Configuration` CRs:
```console
for name in $(kubectl get locks.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
for name in $(kubectl get providers.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
for name in $(kubectl get configurations.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
```

The workflow I tested is the following:
```console
$ helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version 1.1.1 -f /tmp/val.yaml
$ kubectl get providers
NAME                      INSTALLED   HEALTHY   PACKAGE                           AGE
crossplane-provider-aws   True        True      crossplane/provider-aws:v0.18.1   25s
crossplane-provider-gcp   True        True      crossplane/provider-gcp:v0.17.1   11s
```
```console
$ for name in $(kubectl get locks.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
lock.pkg.crossplane.io/lock annotated
$ for name in $(kubectl get providers.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
provider.pkg.crossplane.io/crossplane-provider-aws annotated
provider.pkg.crossplane.io/crossplane-provider-gcp annotated
$ for name in $(kubectl get configurations.pkg.crossplane.io -o name); do kubectl annotate $name 'helm.sh/resource-policy=keep'; done
```
```console
$ helm upgrade crossplane --namespace crossplane-system crossplane-stable/crossplane --version 1.2.1
$ kubectl get providers
NAME                      INSTALLED   HEALTHY   PACKAGE                           AGE
crossplane-provider-aws   True        True      crossplane/provider-aws:v0.18.1   3m25s
crossplane-provider-gcp   True        True      crossplane/provider-gcp:v0.17.1   3m11s
```

Note that in order not to lose `Lock` object, all users need to run at least the first command. Other two are needed for people who use Helm to install `Provider`s and `Configuration`s but it'd be fine for them as well to run the command since they may not be aware of how they were installed right away.

@negz @hasheddan what are your thoughts?

**Comment by hasheddan** [comment]
@muvaf this sounds pretty good to me, especially given that anyone who starts out with v1.2.x will not run into this problem and only folks that installed the packages alongside Crossplane will experience the issue on prior versions. Since the `Lock` will only be removed in the case that it was empty I am also adding the functionality for revisions to create the `Lock` if it does not exist as this will also guard against someone just deleting the `Lock` when it is empty (outside of any upgrade scenario).

**Comment by muvaf** [comment]
I think even if the `Lock` doesn't disappear, it gets the `deletionTimestamp`, so just to be on the safe side I'll suggest everyone to run these commands.

**Comment by hasheddan** [comment]
> I think even if the Lock doesn't disappear, it gets the deletionTimestamp, so just to be on the safe side I'll suggest everyone to run these commands.

Yes it will 👍 Which means if all packages later were uninstalled the `Lock` could get deleted.
