### ISSUE TITLE
Add Rancher2 Provider for Crossplane

### ISSUE THREAD

**Issue by p-null** [crossplane/crossplane#2329]
### What problem are you facing?

Rancher is a popular choice for users who would like to provision K8s clusters on bare metal machines or VPSs that are not from a cloud provider. 

However, crossplane currently has not added support for provisioning cluster resources via Rancher yet, thus users can not create/update/delete RKE clusters from Crossplane.

### How could Crossplane help solve your problem?

Add a Rancher2 provider for Croosplane which can be used to provision any of the cloud resources available via Rancher.

**Comment by Zak-Anderson** [comment]
So to add to this ticket it would be nice if we could get a provider to Utilise the two processes built inside Terraform already 

The Rancher2 provider is used to interact with the resources supported by Rancher v2.

The provider can be configured in 2 modes:

Admin: this is the default mode, intended to manage rancher2 resources. It should be configured with the api_url of the Rancher server and API credentials, token_key or access_key and secret_key.
Bootstrap: this mode is intended to bootstrap a rancher2 system. It is enabled if bootstrap = true. In this mode, token_key or access_key and secret_key can not be provided

 Bootstrap is here below

Provides a Rancher v2 bootstrap resource. This can be used to bootstrap Rancher v2 environments and output information. It just works if bootstrap provider config is added to the .tf file. More info at rancher2 provider

This resource bootstraps a Rancher system by performing the following tasks:

Updates the default admin password, provided by setting password or generating a random one.
Sets server-url setting, based on api_url.
Sets telemetry-opt setting.
Creates a token for admin user with concrete TTL.
Rancher2 admin password can be updated after the initial run of terraform by setting password field and applying this resource again.

Rancher2 admin token can also be regenerated if token_update is set to true. Refresh resource function will check if token is expired. If it is expired, token_update will be set to true to force token regeneration on next terraform apply.

Login to Rancher2 is done by trying to use token first. If it fails, it uses admin current_password. If admin password has been changed outside of terraform and the terraform token is expired, current_password field can be specified to allow terraform to manage admin password and token again.


Example usage case is here https://registry.terraform.io/providers/rancher/rancher2/latest/docs

here are all the rancher terraform components first one listed is the bootstrap here https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap

**Comment by luebken** [comment]
With [crossplane-contrib/terrajet](https://github.com/crossplane-contrib/terrajet) we have created a tool that creates Crossplane providers with very low effort based of a Terraform provider. In this case, https://github.com/rancher/terraform-provider-rancher2/.  If someone wants to take a look, please let me know, we are happy to assist.

**Comment by Zak-Anderson** [comment]
Thank you @luebken we are busy looking into it, awesome that it is now there

**Comment by ytsarev** [comment]
solved by https://github.com/crossplane-contrib/provider-jet-rancher
