### ISSUE TITLE
Composition patches: Introduce a method to iterate over arrays of objects

### ISSUE THREAD

**Issue by rozcietrzewiacz** [crossplane/crossplane#2335]
### What problem are you facing?

Some managed resources include arrays of `Object` type. Some examples:
 - `ResourceRecordSet` in `route53.aws.crossplane.io/v1alpha1` at [`spec.forProvider.resourceRecords`](https://doc.crds.dev/github.com/crossplane/provider-aws/route53.aws.crossplane.io/ResourceRecordSet/v1alpha1@v0.18.1#spec-forProvider-resourceRecords) (single field "value")
 - `FargateProfile` in `eks.aws.crossplane.io/v1alpha1`  at  [`spec.forProvider.selectors`](https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/FargateProfile/v1alpha1@v0.18.1#spec-forProvider-selectors) - with `labels` and `namespace` fields
 - `CosmosDBAccount` in `database.azure.crossplane.io/v1alpha3` at [`spec.forProvider.properties.locations`](https://doc.crds.dev/github.com/crossplane/provider-azure/database.azure.crossplane.io/CosmosDBAccount/v1alpha3@v0.16.1#spec-forProvider-properties-locations) (3 fields)

Since Platform Builders want to simplify and/or restrict the interface for Platform Consumers, they should be able to produce `Compositions` that would consume arrays of simple types to fill in just one of the fields in each such `Object`.

For instance: To allow consumers create a set of route53 DNS records, the consumer should be able to supply those as array of `Strings` instead of an array of `Objects` with a single `value` field.

An even more obvious example could be drawn in case of `FargateProfile` selectors mentioned above. Platform Builders could have a solid reason to allow Consumers define `labels`, but not `namespace` in their `CompositeResource`.

To achieve this, the Composition currently has to do things like 
```
- fromFieldPath: "spec.records[0]"
  toFieldPath: "spec.forProvider.resourceRecords[0].value"
- fromFieldPath: "spec.records[1]"
  toFieldPath: "spec.forProvider.resourceRecords[1].value"
- fromFieldPath: "spec.records[2]"
  toFieldPath: "spec.forProvider.resourceRecords[2].value"
- fromFieldPath: "spec.records[3]"
  toFieldPath: "spec.forProvider.resourceRecords[3].value"
- fromFieldPath: "spec.records[4]"
  toFieldPath: "spec.forProvider.resourceRecords[4].value"
- fromFieldPath: "spec.records[5]"
  toFieldPath: "spec.forProvider.resourceRecords[5].value"
...
```

which is ugly and involves imposing a limit on the number of elements.

### How could Crossplane help solve your problem?

Introduce a method to iterate over an array of objects and patch only selected elements, based on values from an input array of simple types (or object with subset of elements).

**Comment by dee0** [comment]
Fwiw my team is bumping into this as well.  Specifically

```
- fromFieldPath: spec.parameters.postgresql.allowListIPRanges[0]
   toFieldPath: spec.forProvider.ingress[0].ipRanges[0].cidrIp
- fromFieldPath: spec.parameters.postgresql.allowListIPRanges[1]
   toFieldPath: spec.forProvider.ingress[0].ipRanges[1].cidrIp
```

Wonder how feasible it would be to make use of yq ( https://github.com/mikefarah/yq ) in Crossplane? 

Example yq command that performs the transform my team needs

`echo '[ { cidrIp: "127.0.0.1" }, { cidrIp: "10.0.0.0" } ]' | yq eval '{ "allowListIPRanges" : [.[].cidrIp] }' -`

outputs 

```
allowListIPRanges:
  - "127.0.0.1"
  - "10.0.0.0"

```

**Comment by linuxbsdfreak** [comment]
Same here. Would be nice that crossplane could support iterating over arrays. +1 for this issue to have it fixed.

**Comment by psinghal20** [comment]
Hi @rozcietrzewiacz @dee0, I had some initial thoughts regarding the API design for the iterate patch functionality.
```
type: iterate
fromFieldPath: [Path of Input Array]
toFieldPath: [Path of Output Array]
iterate:
    from: [Path in Object to pick]
    to: [Path in Object to emit]
```
The API could look something like this for the first use case of mapping a records array to Route53 Resource records:
```
type: iterate
fromFieldPath: spec.records
toFieldPath: spec.forProvider.resourceRecords
iterate:
    # from empty means the array object to be used as input
    to: .value
```
I believe the same could work for the use case by @dee0.
Now, you could repeat the same patch again to patch multiple fields in an object. For eg.
```
- type: iterate
  fromFieldPath: spec.selectors
  toFieldPath: spec.forProvider.selectors
  iterate:
    from: .label
    to: .label
- type: iterate
  fromFieldPath: spec.selectors
  toFieldPath: spec.forProvider.selectors
  iterate:
    from: .namespace
    to: .namespace
```
This does introduce repetition in the case of patching multiple fields from the array. 
Also, the key's names are just from the top of my mind so let me know if you have any suggestions regarding this.

Let me know what do you think about this. Thanks :smile: 
CC: @negz @hasheddan 

PS: I did take a look into `yq` and I believe they are currently working on the public API support for `yq` so if we plan to go with this, maybe we can hold working on this till they offer initial public API for the library.

**Comment by negz** [comment]
I'm empathetic to the UX desires here, but I'm very wary of adding iteration to the Composition API. Features like iteration and conditionals were things we explicitly did not want to add to the API in order to avoid it turning into a basically a fully fledged programming language expressed as YAML. :) Instead, we would like to add 'custom composition' support ([design doc](https://github.com/crossplane/crossplane/pull/1705)) such that folks with advanced use cases could implement them using a more advanced tool (e.g. Starlark, yq, cdk, etc).

That said, I do like @psinghal20's API suggestion since it reads more like "transform this array of objects into an array of equal length" rather than a full-on "for loop".

**Comment by psinghal20** [comment]
Oh nice, I took a brief look at the design doc and got the gist of it. Being unfamiliar with the cdk8s, some of it seemed a little confusing. I liked the idea of having a composition engine running as a sidecar(or controller) that handles the creation of appropriate YAML or objects. 

I would still be a little biased towards transformers for simple use-cases but I understand that drawing this line is quite subjective.

**Comment by dee0** [comment]
Fwiw, the CustomComposition looks like overkill for my team's case.
psingal20's suggestion would be preferable.   That said, my team is already familiar with JSONPath and yq just as a result of working with k8s and so more preferable still would be the ability to use one of these syntaxes we know within in the current transform mechanism.

**Comment by negz** [comment]
I was thinking today that we didn't really have a single place that captured all of our thinking around the custom composition concept, so I've raised https://github.com/crossplane/crossplane/issues/2524 to track that.

**Comment by negz** [comment]
> Wonder how feasible it would be to make use of yq ( https://github.com/mikefarah/yq ) in Crossplane?

I'd be against this. I prefer to avoid adding too much meaning/structure in otherwise opaque strings that can't be validated by the API server.

**Comment by React-ssr** [comment]
Glance at this insight https://custom-directive-hurt.github.io/knox490/
