### ISSUE TITLE
Backport bot does not have proper permissions

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2341]
### What happened?

I added backport labels to #2340 and the first run failed because there was a merge conflict in `release-1.0` (related: should bot fail for all if one branch has merge conflict?). I removed the `backport release-1.0` and re-ran the workflow. The bot was able to cherry pick successfully, but then failed with `permission denied` when trying to open the backport PR.

### How can we reproduce it?

```
remote: Permission to crossplane/crossplane.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/crossplane/crossplane/': The requested URL returned error: 403
The process '/usr/bin/git' failed with exit code 128
Create comment: The process '/usr/bin/git' failed with exit code 128
Resource not accessible by integration
```

https://github.com/crossplane/crossplane/runs/2722902558

**Comment by jbw976** [comment]
Looking at the logs of that failed run, it looks like it was trying to push a new branch (`backport-2340-to-release-1.1`) with the cherry-picked commit to the `crossplane/crossplane` repo, as opposed to a fork.  I think this is expected, but just wanted to make sure.

What identity does this action run with? I see it's using the default [`secrets.GITHUB_TOKEN`](https://github.com/crossplane/crossplane/blob/master/.github/workflows/backport.yml#L26).  It also looks like this default token should have "read and write permissions" on https://github.com/crossplane/crossplane/settings/actions, so I would expect the operation of pushing a new branch that it's trying to do to succeed. 🤔

**Comment by negz** [comment]
I think we're hitting https://github.com/zeebe-io/backport-action/issues/41. When I tested the action out I did so on a repo I made for experimenting with actions, and the PRs I was making were from a local branch rather than a fork. I'm experimenting with a fix now.

**Comment by negz** [comment]
This was fixed in https://github.com/crossplane/crossplane/pull/2348.
