### ISSUE TITLE
Composite reconciler initializes with empty string for external name

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2350]
### What happened?

When you create a claim you'll see that the external-name annotation has `""` value in both claim and composite. When you propagate `metadata.annotations[crossplane.io/external-name]` or `metadata.annotations` in `Composition` and left the annotation empty in claim/composite, you'll see that resources with late-assigned IDs like AWS VPC will be created over and over again due to having annotation empty.

The cause of the problem is that [here](https://github.com/crossplane/crossplane/blob/ec0b383/internal/controller/apiextensions/claim/configurator.go#L66) we set an empty string if the composite is not yet created, then the claim reconciler [propagates](https://github.com/crossplane/crossplane/blob/b9a8f4b/internal/controller/apiextensions/claim/api.go#L67) that to claim as late-initialization. Doing these operations only if the value is not empty solves the problem.

### How can we reproduce it?

Create a claim/composite and look at annotations of both.

### What environment did it happen in?
Crossplane version: 1.2.2

**Comment by jbw976** [comment]
@muvaf can you comment on the severity/priority of this? is this something that should be included in 1.3, backported to previous releases?  Is it a recent regression (and therefore doesn't exist in previous releases)?

**Comment by muvaf** [comment]
It happens when all three of the following exist together:
* You have a patch that includes external-name annotation, either like `metadata.annotations` or `metadata.annotations[crossplane.io/external-name]`
* You do not specify an external name annotation in the claim or composite.
* The managed resource you're propagating the external-name to gets its external-name from the cloud provider, like `VPC` in AWS.

Essentially, it happens when you'd like to import an existing managed resource with non-deterministic name. In a lot of cases, external-name is used for resources which have deterministic names. So, I feel like it's not as urgent to fix that we'd like to make a patch release but it should go to 1.3

**Comment by ulucinar** [comment]
Hi @muvaf,
What confused me when I first observed this issue in the context of https://github.com/crossplane/crossplane/issues/2211 is having an external-name annotation on an XR. What other use cases do we have for the external-name annotation besides relating a managed resource to the actual platform resource (e.g., relating an `RDSInstance.database.aws` CR to the actual AWS RDS database instance)? Do we have any use cases for external name annotations on XRs? 

I would expect to observe provisioned composed resources in `status.conditions` but we have them under `spec.resourceRef` and because external-name is a scalar (I assume) I would definitely not expect to see composed managed resource external-names in the XR annotation. So, what's the use case in crossplane?

**Comment by negz** [comment]
@ulucinar At the managed resource level the external name allows the managed resource author to influence the external name; i.e. it's (with some exceptions) the authoritative source of the external name, not only a record of it. The idea behind supporting the annotation at the claim and XR level was to allow claim and XR authors to influence the (conceptual) "external name" of a the claim they're interacting with.

You could imagine a simple XR that composed only a single RDSInstance; in this case the XRC's external name annotation would be propagated all the way down from XRC -> XR -> MR. Note that the XR->MR propagation must be handled explicitly by the Composition.

In other cases where we have a more complex XR you might still want to propagate the external name from the claim. For example if you had an XR that represented an RDSInstance and three firewall rules, you could use the external name annotation to name the "main" resource - the RDSInstance - and perhaps derive names for the other resources from the external name.

**Comment by ulucinar** [comment]
Hi @negz,
Thanks for the clarification. As you pointed out, I was thinking of the external-name annotation mainly as a record of what the platform chooses/names for us, not the way around. That definitely makes sense.
