### ISSUE TITLE
custom naming instead of dns naming convention for XRD

### ISSUE THREAD

**Issue by kernel164** [crossplane/crossplane#2354]
### What happened?
I would like to have custom naming instead of dns naming convention for XRD and Composition metadata.name
It fails only for "CompositeResource" when XRD tries to create CRDs.

### How can we reproduce it?

I went through the code and found the issue. 

https://github.com/crossplane/crossplane/blob/v1.2.2/internal/xcrd/crd.go#L62
`	crd.SetName(xrd.GetName()) `

https://github.com/crossplane/crossplane/blob/v1.2.2/internal/xcrd/crd.go#L133
`	crd.SetName(xrd.Spec.ClaimNames.Plural + "." + xrd.Spec.Group) `

Is there any reason why different approach to set CRD name for ForCompositeResource and ForCompositeResourceClaim?

**Comment by jbw976** [comment]
hey there @kernel164! can you provide an example of a name you'd like to you, but can't? 

The Kubernetes API (as far as I know) limits the naming conventions for CRDs, so that may be a constraint here we have to deal with.  Your example could help us understand what you want to accomplish :)
