### ISSUE TITLE
ArgoCD custom readiness checks for XRDs

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2360]
### What problem are you facing?

@stevendborrelli noticed that ArgoCD doesn't pick up the readiness conditions we have.

### How could Crossplane help solve your problem?

For known CRDs, we can open PRs to [upstream](https://argoproj.github.io/argo-cd/operator-manual/health/) but likely we'll need another approach for XRDs defined in runtime.

**Comment by negz** [comment]
I'm going to close this as a duplicate of https://github.com/crossplane/crossplane/issues/2444. I believe if we address that issue we'll cover this XRD issue as well (since they use the 'standard' Ready condition).
