### ISSUE TITLE
Document Combine{From,To}Composite patch type

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2362]
### What problem are you facing?

Immediately after I merged https://github.com/crossplane/crossplane/pull/2352 I realised we didn't update the documentation to highlight the new patch type and how to use it.

### How could Crossplane help solve your problem?

We could update the documentation to highlight the new patch type and how to use it. :)

**Comment by negz** [comment]
@benagricola Are you interested in taking this one since you added the feature? :)

**Comment by benagricola** [comment]
@negz Yep I'll tackle it, definitely forgot to do that in the original PR 😅
