### ISSUE TITLE
Leader election configmaps getting periodic updates

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2378]
### What happened?

After installing Crossplane, I noticed that crossplane leader election configmaps are getting periodic updates (~ 50 updates per min)

```
$ kubectl get cm -w
NAME                              DATA   AGE
crossplane-leader-election-core   0      12s
crossplane-leader-election-rbac   0      13s
crossplane-leader-election-rbac   0      15s
crossplane-leader-election-core   0      14s
crossplane-leader-election-rbac   0      17s
crossplane-leader-election-core   0      16s
crossplane-leader-election-rbac   0      19s
crossplane-leader-election-core   0      18s
crossplane-leader-election-rbac   0      21s
crossplane-leader-election-core   0      20s
crossplane-leader-election-rbac   0      23s
crossplane-leader-election-core   0      22s
crossplane-leader-election-rbac   0      25s
crossplane-leader-election-core   0      24s
crossplane-leader-election-rbac   0      27s
crossplane-leader-election-core   0      26s
crossplane-leader-election-rbac   0      29s
crossplane-leader-election-core   0      28s
crossplane-leader-election-rbac   0      31s
crossplane-leader-election-core   0      30s
crossplane-leader-election-rbac   0      33s
crossplane-leader-election-core   0      32s
crossplane-leader-election-rbac   0      35s
crossplane-leader-election-core   0      34s
crossplane-leader-election-rbac   0      37s
crossplane-leader-election-core   0      36s
crossplane-leader-election-rbac   0      39s
crossplane-leader-election-core   0      38s
crossplane-leader-election-rbac   0      41s
crossplane-leader-election-core   0      40s
crossplane-leader-election-rbac   0      43s
crossplane-leader-election-core   0      42s
crossplane-leader-election-rbac   0      45s
```

### How can we reproduce it?

1. Install crossplane
2. kubectl get cm -w

### What environment did it happen in?
Crossplane version: 1.2.2

**Comment by hasheddan** [comment]
@turkenh here is some info about how leader election is configured:
1. Create manager
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/manager/manager.go#L308
2. Build resource lock
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/leaderelection/leader_election.go#L54
3. Default lease options
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/manager/manager.go#L545
4. Start leader election
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/manager/internal.go#L484
5. Builds a new leader elector
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/manager/internal.go#L662
6. Which uses the defaulted config from building the manager
https://github.com/kubernetes/client-go/blob/1bccfc8c60977e2ce3235394daff128996818f7b/tools/leaderelection/leaderelection.go#L77
7. Then start the leader elector
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/manager/internal.go#L680
8. Which continues until cancelled or stops holding lease
https://github.com/kubernetes/client-go/blob/1bccfc8c60977e2ce3235394daff128996818f7b/tools/leaderelection/leaderelection.go#L200
