### ISSUE TITLE
Does composition transforms support string concatenate from multiple source fields

### ISSUE THREAD

**Issue by morningspace** [crossplane/crossplane#2394]
### What problem are you facing?

When I try to use composition to abstract the API routing that covers different implementations underneath such as [Kong](https://konghq.com/) and [Ambassador](https://www.getambassador.io/), I found that the current transforms does not support below case:

Say, I have one ingress rule in Kong described using:
```yaml
paths:
- backend:
    service:
      name: echo
      port:
        number: 8080
  path: /bar
```

Where the same thing will be defined differently in Ambassador:
```yaml
  prefix: /bar/
  service: http://echo:8080
```

For the service address, when I use service name and port as two separate fields in XR, it can be simply mapped to Kong in composition resource using `fromFieldPath` and `toFieldPath`.

However, I found it's hard to map it to Ambassador, because `toFieldPath` needs two field values while `fromFieldPath` can only refer to one field value.

### How could Crossplane help solve your problem?

Any suggestion on how to get it addressed? Ideally, composition transforms can solve it natively, although I can understand that the current scheme of composition seems more sticky to "single-field-to-single-field mapping". It appears that may need some adjustment for the representation of field-to-field mapping.

**Comment by jbw976** [comment]
Good question @morningspace, this was actually just recently implemented via #2352 and will be included in the v1.3 release on June 29th!

See the documentation in `master` at https://crossplane.io/docs/master/concepts/composition.html, search the page for `value based on multiple input values`, to get started with this functionality.  Let us know if you have any feedback!

**Comment by morningspace** [comment]
This is awesome, thanks @jbw976 , let me check it!

**Comment by adamkirk** [comment]
I've just used this feature on version crossplane-1.3.0-rc.0.98.gbd77167d of the helm chart (in master repository).

It works a treat, thanks @jbw976!

My use case was for an iampolicy. I wanted a simple way to create an s3 bucket and an iam user with access to only this s3 bucket. Essentially i created a composition which accepts a name and then creates the relevant iampolicy, iamuser, and iampolicyattachment resources.

Just thought i'd add this here as an example, cause this made it a hell of easier to create a simple composition for my team, which doesn't expose aws policies unnecessarily! :)

```
... skipped the rest cause, the composition is quite large
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    namespace: crossplane-system
  forProvider:
    path: "/"
patches:
...
- type: CombineFromComposite
  toFieldPath: "spec.forProvider.document"
  policy:
    fromFieldPath: Required
  combine:
    variables:
      - fromFieldPath: spec.parameters.name
      - fromFieldPath: spec.parameters.name
      - fromFieldPath: spec.parameters.name
    strategy: string
    string:
      fmt: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": ["s3:*"],
              "Resource": [
                "arn:aws:s3:::%s"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:*"
              ],
              "Resource": [
                "arn:aws:s3:::%s",
                "arn:aws:s3:::%s/*"
              ]
            }
          ]
        }
...
```

**Comment by jbw976** [comment]
very cool @adamkirk 😮 !! Feel free to share that example (including all the resources in the composition if you're comfortable with that so its a full example) on the show and tell "discussions" page! https://github.com/crossplane/crossplane/discussions/categories/show-and-tell

**Comment by negz** [comment]
Hey folks! It sounds like you may have what you need here, so I will close this issue please let me know if we should reopen it.
