### ISSUE TITLE
Proposal: Reusable composed resource templates

### ISSUE THREAD

**Issue by morningspace** [crossplane/crossplane#2396]
### What problem are you facing?

I have a set of managed resources which I want to compose using different combinations. For example, if I have resource A, B, and C. I want to support combination such as AB, BC, AC, and ABC. Right now, the way I know to achieve this when define the combination using Composition is that, I have to define the Composition for each of these combinations, also the XRD, which includes lots of duplications.

### How could Crossplane help solve your problem?

Is there any idea or suggestion on how to reduce such duplication. From Crossplane doc, I see this:

> Note that Compositions provide intentionally limited functionality when compared to powerful templating and composition tools like Helm or Kustomize. This allows a Composition to be a schemafied Kubernetes-native resource that can be stored in and validated by the Kubernetes API server at authoring time rather than invocation time.

That makes sense to me but given the above scenario is a valid case, any other option that can keep the design intentionally while also make the composition authoring easier. e.g. allow referencing between compositions at runtime, or have some tooling similar to code generation at authoring time.

**Comment by negz** [comment]
@morningspace Can you elaborate on what you're trying to achieve here? I think I get it, but I want to make sure. It sounds like you're wanting to define each element in a Composition's `resources` array once, then reuse it across multiple Compositions?

I could imagine us doing something like introducing a new `ComposedResource` type that could be aggregated to a `Composition` using a label selector.

**Comment by morningspace** [comment]
@negz Yeah, you are right. And, I thought what you suggested as above using `ComposedResource` is something might be helpful in this case. Interestingly, I was experimenting some of such cases recently and I thought I might have a few more concrete cases that I could share here which makes me start to think that to simply refer to something using label selector might not be sufficient. I will write up something and give more detailed updates later when I have time in the coming days. Sorry for the late response.
