### ISSUE TITLE
Annotations on Providers should tell me what permissions I need for each ManagedResource

### ISSUE THREAD

**Issue by grantgumina** [crossplane/crossplane#2397]
### What problem are you facing?
Something I've been struggling with, and I've seen others in the community struggle with, recently is that it's unclear what permissions I need to give the service account(s) being used by my Providers. Today I either have to ask someone in the Crossplane community or look at the code itself and understand what resources are being used, and cross-check with the CSP documentation.

### How could Crossplane help solve your problem?
If Provider CRDs were annotated with the permissions they required, Crossplane could inform me of the permissions I need to add to my service account when attempting to provision a resource. It could also alert me when creating a Composition which depends on the ManagedResources.

**Comment by dradetsky** [comment]
I would add that:

0. Even looking at the code is sometimes not sufficient unless it's combined with a good understanding of how the underlying managed service works. And lots of users won't understand at least some of the services they're trying to manage.

1. Not having this information (the exact set of permissions I need to give my crossplane service user for it to manage e.g. DynamoDB tables on my behalf), will tend to lead to devs kind of guessing, saying "welp that worked!" and then having strange errors occur later at awkward times and that the devs don't understand.

For example, in my own recent use-case, I started looking at e.g.

- https://github.com/crossplane/provider-aws/blob/master/pkg/controller/dynamodb/table/zz_conversions.go
- https://github.com/crossplane/provider-aws/blob/master/pkg/controller/dynamodb/table/zz_controller.go

partially in the hopes that I would be able to discover some kind of quick & dirty `grep -r` hack to discover the set of permissions required for this & other resources. However, even if I'd found all the calls to e.g. `CreateTableWithContext` and mapped them to `dynamodb:CreateTable`, I would have to look very carefully to see that `GenerateCreateTableInput` was adding tags to the input struct. I'd also have to know that this meant also that `TagResource` permission was required (and not just for modifying the tags of a resource you've already created).

Anyhow, I still don't know for certain that the crossplane user has all the permissions that are required to for nothing strange to happen later in future lifecycle events.

FWIW, at least for AWS, you should be able to programmatically generate the set of permissions. Basically just create a test account with an admin-level crossplane user, ensure that cloudtrail is logging iam accesses, and create/modify/delete 1 of each type of resource, then pull the cloudtrail logs and see what permissions you used. Better yet, create N*M admin users, one for each of the N resources and M distinct lifecycle events (create/update/delete/etc), and swap out the crossplane provider creds secret in between each operation. That way you get the operations used broken down by resource/event. I also imagine it's possible to do something identical for azure & gcp, if you knew the name of the equivalents of iam & cloudtrail in those platforms (I don't).
