### ISSUE TITLE
Cut v1.3.0 Release

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2408]
### Release Information

**Type:**

- [x] Minor
- [ ] Patch

**Version:** v1.3.0

**Release Date:** Jun 29, 2021

### Steps

I have:

- [x] Created the [release branch][release-branch].
- [x] Created and merged an empty commit to the `master` branch ([PR][empty-commit-pr]).
- [x] Run the [Tag workflow][rc-tag-workflow] on the `master` branch with the next release candidate tag ([Tag][rc-tag]).
- [x] Updated all version information in the documentation on the relevant release branch ([PR][docs-update-pr]).
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version ([Tag][tag]).
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel. ([build][release-build]).
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [registry.upbound.io] for all getting started packages.
    - [x] [xp/getting-started-with-aws]
    - [x] [xp/getting-started-with-aws-with-vpc]
    - [x] [xp/getting-started-with-azure]
    - [x] [xp/getting-started-with-gcp]
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel ([build][stable-build]).
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes ([release][release]).
- [x] Ensured that users have been notified of the release on all communication channels:
    - [x] [Slack][slack]
    - [x] [Twitter][twitter]

[release-branch]: https://github.com/crossplane/crossplane/tree/release-1.3
[empty-commit-pr]: https://github.com/crossplane/crossplane/pull/2395
[rc-tag-workflow]: https://github.com/crossplane/crossplane/runs/2880453549?check_suite_focus=true
[rc-tag]: https://github.com/crossplane/crossplane/releases/tag/v1.4.0-rc.0

[docs-update-pr]: https://github.com/crossplane/crossplane/pull/2412
[tag-workflow]: https://github.com/crossplane/crossplane/runs/2945452331?check_suite_focus=true
[tag]: https://github.com/crossplane/crossplane/releases/tag/v1.3.0
[ci-workflow]: https://github.com/crossplane/crossplane/actions/runs/983799776
[release-build]: https://releases.crossplane.io/build/release-1.3/
[configurations-workflow]: https://github.com/crossplane/crossplane/runs/2945538373
[xp/getting-started-with-aws]: https://cloud.upbound.io/registry/xp/getting-started-with-aws/v1.3.0
[xp/getting-started-with-aws-with-vpc]: https://cloud.upbound.io/registry/xp/getting-started-with-aws-with-vpc/v1.3.0
[xp/getting-started-with-azure]: https://cloud.upbound.io/registry/xp/getting-started-with-azure/v1.3.0
[xp/getting-started-with-gcp]: https://cloud.upbound.io/registry/xp/getting-started-with-gcp/v1.3.0
[promote-workflow]: https://github.com/crossplane/crossplane/actions/runs/983871530
[stable-build]: https://releases.crossplane.io/stable/v1.3.0/
[release]: https://github.com/crossplane/crossplane/releases/tag/v1.3.0
[slack]: https://crossplane.slack.com/archives/CEFQCGW1H/p1625001259051300
[twitter]: https://twitter.com/crossplane_io/status/1409986997687627778?s=20

[releases.crossplane.io]: https://releases.crossplane.io
[registry.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/1286d77/docs/contributing/release-process.md

I'll be following the above steps today. @hasheddan Looks like you've already done all the minor release specific steps, so I've checked those boxes.
