### ISSUE TITLE
Enhancement Request: add IBM Power Linux Platform (ppc64le) support

### ISSUE THREAD

**Issue by amitsadaphule** [crossplane/crossplane#2424]
Hi,

With the merge of my 2 PRs (https://github.com/upbound/build/pull/134, https://github.com/upbound/build/pull/135) on upbound/build repo, I've been able to build crossplane top of the tree (commit # 231ba7de48970da2657e9a971e5e1b1d607c87b5) on ppc64le with the following steps:

```
yum install -y make git wget gcc perl-Digest-SHA

# Download and install go
wget https://golang.org/dl/go1.14.13.linux-ppc64le.tar.gz
tar -xzf go1.14.13.linux-ppc64le.tar.gz
rm -rf go1.14.13.linux-ppc64le.tar.gz
export GOPATH=`pwd`/gopath
export PATH=`pwd`/go/bin:$GOPATH/bin:$PATH

mkdir -p $GOPATH/src/github.com/crossplane
cd $GOPATH/src/github.com/crossplane
git clone https://github.com/crossplane/crossplane.git
cd crossplane/
export PLATFORMS=linux_ppc64le
make submodules
make vendor vendor.check
make build.all
make test
```

However, I see that the following 2 things are blocking a complete ppc64le support for the repo:
1. For running e2e tests, I needed to make the following minor code change, since the image kindest/node is not supported on ppc64le:

```
sed -i 's/"${KIND}" create cluster --name="${K8S_CLUSTER}"/"${KIND}" create cluster --name="${K8S_CLUSTER}" --image kbasheer\/kindest-node:v1.18.0/g' cluster/local/integration_tests.sh
```
With this, I was able to get the kind cluster up and to get all the e2e tests to PASS. Could you please let me know if it will be an acceptable code change to use `kbasheer/kindest-node:v1.18.0` image for ppc64le arch?

2. `Github Actions` being used as CI does not support ppc64le, unlike travis. The CI also takes care of publishing the artifacts (image, helm chart) to dockerhub, S3. Could you please suggest a way to add pcc64le support there?

Thanks!

**Comment by hasheddan** [comment]
@amitsadaphule thanks for opening this! We currently produce binaries for the following `PLATFORMS` as defined [here](https://github.com/crossplane/crossplane/blob/231ba7de48970da2657e9a971e5e1b1d607c87b5/Makefile#L7):
```
linux_amd64 linux_arm64 linux_arm darwin_amd64 windows_amd64
```

We produce images for the following `PLATFORMS` as defined [here](https://github.com/crossplane/crossplane/blob/231ba7de48970da2657e9a971e5e1b1d607c87b5/cluster/images/crossplane/Makefile#L4) and [here](https://github.com/crossplane/crossplane/blob/231ba7de48970da2657e9a971e5e1b1d607c87b5/cluster/images/crossplane/Makefile#L16):
```
linux_amd64 linux_arm64 linux_arm
```

Adding `linux-ppc64le` to both of those `PLATFORM` locations should cause the CI pipeline to produce binaries and images for the platform. I definitely appreciate your desire to make sure this architecture is e2e tested as well :) We unfortunately only test against `linux_amd64` in our e2e tests, so we would certainly welcome expanded support for other platforms, but I also don't think we would block adding support on it at this time 👍🏻

**Comment by amitsadaphule** [comment]
Thanks @hasheddan for the review and feedback! I'll try a local build of binaries and images, with the change that you suggested and then raise PR. Also, I'll keep e2e tests as a secondary target at this point.

**Comment by hasheddan** [comment]
Perfect. thanks @amitsadaphule! If you want to test building for all platforms locally you can run `make -j2 build.all`

**Comment by amitsadaphule** [comment]
@hasheddan I was able to get the buildx based build to work on Power and confirm that the images being built belonged to the respective architectures as:

```
# make BUILD_ARGS="--load" -j2 build.all
...
# docker images
REPOSITORY                          TAG               IMAGE ID       CREATED         SIZE
build-26b4a2d6/crossplane-arm       latest            fc51c666c5e3   5 minutes ago   34.3MB
build-26b4a2d6/crossplane-ppc64le   latest            9940384d15fa   5 minutes ago   38.3MB
build-26b4a2d6/crossplane-amd64     latest            8207d105b70f   6 minutes ago   40MB
build-26b4a2d6/crossplane-arm64     latest            55a58e20d472   6 minutes ago   37.8MB
# docker inspect fc51c666c5e3 | grep Arch
        "Architecture": "arm",
# docker inspect 9940384d15fa | grep Arch
        "Architecture": "ppc64le",
# docker inspect 8207d105b70f | grep Arch
        "Architecture": "amd64",
# docker inspect 55a58e20d472 | grep Arch
        "Architecture": "arm64",
```

However, when I tried to validate the deployment of the image by following instructions from https://github.com/amitsadaphule/crossplane/blob/master/CONTRIBUTING.md#establishing-a-development-environment, I ran into issue where the crossplane pods always ended up in `CrashLoopbackOff` state

```
# kubectl get pods -A
NAMESPACE           NAME                                       READY   STATUS                  RESTARTS   AGE
crossplane-system   crossplane-559c89c4c9-jdhn8                0/1     Init:CrashLoopBackOff   7          12m
crossplane-system   crossplane-rbac-manager-7b9fd9d885-9qsj5   0/1     Init:CrashLoopBackOff   7          12m
...
```
I'm trying to debug the issue. `kubectl pod describe` isn't giving any useful info and logs can't be seen since the container doesn't even get started.

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  29s               default-scheduler  Successfully assigned crossplane-system/crossplane-559c89c4c9-jdhn8 to p006vm71
  Normal   Pulled     5s (x3 over 27s)  kubelet, p006vm71  Container image "crossplane/crossplane:v1.4.0-rc.0.42.gaa7c2807.dirty" already present on machine
  Normal   Created    5s (x3 over 27s)  kubelet, p006vm71  Created container crossplane-init
  Normal   Started    5s (x3 over 26s)  kubelet, p006vm71  Started container crossplane-init
  Warning  BackOff    2s (x3 over 21s)  kubelet, p006vm71  Back-off restarting failed container
```

I also tried executing the image manually, but it complained about not having any configuration:

```
# docker run --rm --name crosstmp 8f847fcea6a3 core start
crossplane: error: Cannot get config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

Can you please guide me to resolve this issue?

**Comment by amitsadaphule** [comment]
Checked the logs of the init container as:
```
# kubectl logs crossplane-559c89c4c9-l4r4n -c crossplane-init -n crossplane-system
crossplane: error: cannot create new kubernetes client: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: connect: no route to host
```
Got the issue resolved with this:
```
systemctl start firewalld
firewall-cmd --zone=public --add-port=443/tcp
```
crossplane pods are started as expected now:

```
# kubectl get pods -A
NAMESPACE           NAME                                       READY   STATUS    RESTARTS   AGE
crossplane-system   crossplane-559c89c4c9-bbx29                1/1     Running   0          2m46s
crossplane-system   crossplane-rbac-manager-7b9fd9d885-fnlhj   1/1     Running   0          2m46s
kube-system         coredns-f9fd979d6-rjvm8                    1/1     Running   1          3h12m
kube-system         etcd-p006vm71                              1/1     Running   1          3h12m
kube-system         kube-apiserver-p006vm71                    1/1     Running   1          3h12m
kube-system         kube-controller-manager-p006vm71           1/1     Running   1          3h12m
kube-system         kube-proxy-gxp74                           1/1     Running   1          3h12m
kube-system         kube-scheduler-p006vm71                    1/1     Running   1          3h12m
```

**Comment by jbw976** [comment]
@amitsadaphule did you have to run that firewalld workaround only for ppc64le? 🤔

**Comment by amitsadaphule** [comment]
@jbw976 unfortunately, I couldn't verify the cross build, validation for ppc64le on amd64/x86, since the command `docker run --rm --privileged tonistiigi/binfmt:latest --install all` was failing to add qemu support `ppc64le`. But I believe this firewall issue may be specific to the VMs/network that I'm using and not a generic one.
