### ISSUE TITLE
Does cross plane has the client-go to interact with its CRD

### ISSUE THREAD

**Issue by singaravelanIngka** [crossplane/crossplane#2427]
### What problem are you facing?
* I need to interact with the crossplane using go-client, Is there an go client for it??

**Comment by hasheddan** [comment]
@singaravelanIngka we currently generate clients, but they are in `internal/` so they cannot be consumed externally. Would you mind sharing your use-case? :)

**Comment by negz** [comment]
Hi @singaravelanIngka - we haven't heard back so I'm going to close this. Please reply if you'd like to provide more detail,
