### ISSUE TITLE
Support metadata labels in ControllerConfig

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#2438]
### What problem are you facing?
When we want to expose the prometheus metric through Service object, there is no way for us to specify labels for the provide-aws pods thru matching the metadata labels

### How could Crossplane help solve your problem?
To support metadata labels in ControllerConfig object

**Comment by hasheddan** [comment]
@kelvinwijaya any labels or annotations on the `ControllerConfig` should be passed to both the `Deployment` and the `ServiceAccount` that are created (see [here](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.3.0#spec)), are you not seeing this behavior?

**Comment by kelvinwijaya** [comment]
Hi @hasheddan .

I see the behaviour for `annotations` but not `labels`, when i put `labels` - faced validation errors

**Comment by chlunde** [comment]
@kelvinwijaya labels the pods are OK for you, you don't need it on a service, right? I created a PR for this: https://github.com/crossplane/crossplane/pull/2455

**Comment by kelvinwijaya** [comment]
Hi @chlunde , 

Thanks for accommodating to the Change Request, yes only for enabling metadata.labels in the Controller Pods

Service object is created at my side to proxy the Controller deployment. Not sure if Crossplane should provide this

**Comment by chlunde** [comment]
@hasheddan I think we can close this one too now, I initially scoped created an issue for static labels, but since they are user controllable it should solve this issue too.

**Comment by hasheddan** [comment]
Thanks @chlunde!
