### ISSUE TITLE
Remove or highlight older Crossplane version documentation

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2442]
### What problem are you facing?

Crossplane's goals, concepts and APIs went through many iterations before we released Crossplane 1.0. https://crossplane.io/docs contains a snapshot of our documentation for all Crossplane releases back to v0.1. The site _defaults_ to the latest release, but we often find folks are for whatever reason following older versions of the documentation (e.g. v0.7) that refer to many outdated concepts. Possibly other sites are linking to older versions? This leads to confusion.

### How could Crossplane help solve your problem?

When a reader manually selects the `master` version of the documentation they are presented with an obvious warning that they're referring to unreleased documentation at the top of every page. I suggest we add a similar warning to all but the latest versions, making it very clear that the reader is referring to documentation that may be outdated.

<img width="1263" alt="warning" src="https://user-images.githubusercontent.com/1049349/126548284-69d16317-dc04-4b7e-bd4d-909463e548d4.png">

**Comment by negz** [comment]
@stevendborrelli mentioned that one downside of adding a banner is that often folks will:

1. Be reading an old version of a page that no longer exists.
2. Click the latest version in the dropdown up top to select the newest version of that page.
3. Get a 404 due to the page no longer existing.

Perhaps we could include a link in the banner to https://crossplane.github.io/docs, which will redirect to the root of the latest version rather than the specific page they're on? FWIW this seems a little like the behaviour we already have if - e.g. if I browse to https://crossplane.github.io/docs/v0.7/concepts.html then select 1.3 in the dropdown I'm briefly shown a 404 before being redirected to the root of the 1.3 docs.

**Comment by muvaf** [comment]
From my personal experience, when I enter a docs page and choose the latest version from drop-down, being redirected to the root page and having to find the corresponding page is quite laborious. Though there isn't really a catchall solution I can recommend to this problem except manually binding each page in each version to its correspondence.

> Click the latest version in the dropdown up top to select the newest version of that page.
> Get a 404 due to the page no longer existing.

We might be able to hit the new version if the URL hasn't changed in the new version. Do you think that's worth trying?

**Comment by negz** [comment]
> We might be able to hit the new version if the URL hasn't changed in the new version. Do you think that's worth trying?

I think that's how it works now, isn't it? i.e. If the same page exists in the newer version we redirect there. If not we briefly show a 404 then redirect to the root.

**Comment by stevendborrelli** [comment]
> I think that's how it works now, isn't it? i.e. If the same page exists in the newer version we redirect there. If not we briefly show a 404 then redirect to the root.

Yes, that is how it works now (for the most part). For example, the 0.14 [providers](https://crossplane.github.io/docs/v0.14/introduction/providers.html) section does not map to 1.3 [providers](https://crossplane.github.io/docs/v1.3/concepts/providers.html), it returns a 404 since the URL is slightly different.

One of the biggest issues is that Google still indexes these pages and returns them on the first page of search results. As a user who references the Crossplane docs on a daily basis, I hit this issue daily.

**Comment by stevendborrelli** [comment]
I did a quick check of the 0.14 docs to see what returns a 404 when selecting the 1.3 version of the docs in the dropdown:

### Welcome

- <https://crossplane.github.io/docs/v0.14/getting-started/compose-infrastructure.html> returns a 404, probably should map to <https://crossplane.github.io/docs/v1.3/getting-started/create-configuration.html>
- <https://crossplane.github.io/docs/v0.14/getting-started/run-applications.html> this is an OAM reference, we should probably indicate if this is deprecated or point to new docs.
- <https://crossplane.github.io/docs/v0.14/getting-started/package-infrastructure.html> probably should map to <https://crossplane.github.io/docs/v1.3/getting-started/create-configuration.html>

### Introduction

- <https://crossplane.github.io/docs/v0.14/introduction/providers.html> 404 map to <https://crossplane.github.io/docs/v1.3/concepts/providers.html>
- <https://crossplane.github.io/docs/v0.14/introduction/managed-resources.html> 404 map to <https://crossplane.github.io/docs/v1.3/concepts/providers.html>
- <https://crossplane.github.io/docs/v0.14/introduction/composition.html> 404 map to <https://crossplane.github.io/docs/v1.3/concepts/composition.html>
- <https://crossplane.github.io/docs/v0.14/introduction/packages.html> 404 map to <https://crossplane.github.io/docs/v1.3/concepts/packages.html>

### Guides

Most of the 0.14 guides point to external pages. Not affected by 1.3 doc changes.

### Reference

All links still exist in 1.3.

### API Documentation 

Points to doc.crds.dev, not affected by 1.3 dropdown.


### Contributing

- <https://crossplane.github.io/docs/v0.14/contributing/experimental.html> The page is marked as deprecated, maybe this is a pattern we can use for other obsolete  pages.

**Comment by jmcclell** [comment]
@muvaf asked on Slack for detail as to how old documentation was found.

Answer: Google

Seriously. Google for anything Crossplane related and you're probably getting linked to an old documentation page.

https://www.google.com/search?q=installing+crossplane

Gives me a document from v0.1 as the first result.

**Comment by muvaf** [comment]
> Google for anything Crossplane related and you're probably getting linked to an old documentation page.

I remember a similar experience with OpenShift. Their old docs had a big warning and you could choose a version fro drop-down but the link would be broken most of the time. So I wonder whether removing doc versions older than some number of releases would help.

**Comment by jmcclell** [comment]
> So I wonder whether removing doc versions older than some number of releases would help.

I wonder if there isn't some basic SEO stuff that could be done to keep search engines from surfacing older pages? 🤷

**Comment by austinsasko** [comment]
Our team was bit by this a couple of times where we were following old version's documentation. +1 to this issue as even knowing about this issue I still keep accidentally following old documentation

**Comment by nabadger** [comment]
Similar story here - I always end up on the old version of the docs because I use Google (although most other popular search engines end up on older docs too).

My general expectation would be to end up on the latest stable docs (with `master` / `main` being easily available too).

**Comment by jbw976** [comment]
@chlunde suggested a reasonable potential fix for this issue: https://github.com/crossplane/crossplane.github.io/issues/107#issuecomment-892948049

I have google search console access, so I can possibly help with the testing of such a fix.

**Comment by negz** [comment]
I'm pretty sure we solved this by just deleting the older documentation. https://github.com/crossplane/crossplane.github.io/tree/master/docs now has nothing older than v1.3.

**Comment by jbw976** [comment]
breadcrumbs to further effort required to remove the old pages from google search results: https://github.com/crossplane/crossplane.github.io/issues/107#issuecomment-990338800
