### ISSUE TITLE
Azure Service Principal role "owner" 

### ISSUE THREAD

**Issue by koanplaned** [crossplane/crossplane#2445]
Hi all,

I'm completly new to crossplane and want to try it out on my Azure Subscription.

Following the docs, I have to create a Service Principal with rbac role "owner". This is pretty scary to me, since I open the complete system for Crossplane. Is it really necessary to use role "owner" and if yes - why? I'd rather like to use role "contributor".

Thanks for your answers in advance.

**Comment by muvaf** [comment]
Hi @koanplaned ! You don't need to use owner role necessarily, it's just there in getting started guide for easier testing. The role can be as limited as what you want to provision with Crossplane - in case it's not enough, you'll see the error Azure returned in the status of the custom resource.

**Comment by koanplaned** [comment]
Hi @muvaf, thanks for the info, that helped!
