### ISSUE TITLE
The default service account name is the provider-aws revision and changes with every provider release. Assuming serviceaccount name as provider-aws-* does not work

### ISSUE THREAD

**Issue by JAditya1395** [crossplane/crossplane#2454]
### What happened?

apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws
spec:
  controllerConfigRef:
    name: aws-config

Referring  https://github.com/crossplane/provider-aws/commit/0faa6de98d9fdb942e7e984f6e5115e3895caeea

Since service account name created with every  version of provider package  is different. While using IRSA it posts a problem of hardcoding the service account name in the trust relation. A solution provider above to give provider-aws-* service account name so that it works irrespective of package version is not working. We face 401 unauthorised  error.

### How can we reproduce it?

Create IRSA and make trust relationship with provider-aws-* and it will be noticed that the Iam role is not able to get associated with the service account giving 401 unauthorised error while provisioning aws resources

What environment did it happen in?
Crossplane version: 
v1.3.0

Include at least the version or commit of Crossplane you were running. Consider
also including your:

Cloud provider -AWS

**Comment by chlunde** [comment]
I suspect you use `StringEquals` instead of `StringLike` in the assume role policy document.

**Comment by hasheddan** [comment]
@JAditya1395 could you see if @chlunde suggestion works for you and close out this issue if so? :)
