### ISSUE TITLE
Scaleway support

### ISSUE THREAD

**Issue by danmx** [crossplane/crossplane#2461]
### What problem are you facing?

I'm deploying my [Scaleway] infrastructure using Terraform but I'd like to dynamically assign Flexible IPs similar to [Digital Ocean Floating IP controller] or deploy other services like object storage associated to my Kubernetes stack.

### How could Crossplane help solve your problem?

I wouldn't have to build a dedicated controller per object similar to [Digital Ocean Floating IP controller].

[Scaleway]: https://www.scaleway.com/en/
[Digital Ocean Floating IP controller]: https://github.com/Smirl/digitalocean-floating-ip-controller/

**Comment by luebken** [comment]
@danmx The fabulous @remyleone has released https://github.com/remyleone/crossplane-scaleway-provider

**Comment by remyleone** [comment]
@danmx let me know what you think if you test my provider :) I'm actively looking for feedback :) Feel free to ask questions and talk with me on https://slack.scaleway.com/ #crossplane or on #provider-scaleway in the crossplane slack :)
