### ISSUE TITLE
"Could not connect" to New VPC RDS instance from tutorial

### ISSUE THREAD

**Issue by alex-treebeard** [crossplane/crossplane#2462]
### What happened?

After running the new VPC RDS instance guide in the [docs](https://crossplane.io/docs/v1.3/getting-started/provision-infrastructure.html)

When running the test pod shown below, I see:

```log
psql: error: could not connect to server: Connection refused
Is the server running on host "my-db-xxx.us-east-1.rds.amazonaws.com" (x.x.x.x) and accepting
TCP/IP connections on port 5432
```

### What environment did it happen in?
Crossplane version: 

➜ kubectl crossplane --version
v1.3.0

Running on minikube

```
image: 'crossplane/provider-aws-controller:v0.19.0'
```

Thanks!

**Comment by negz** [comment]
Thanks @alex-treebeard! Is there any chance something was preventing outbound connections from your minikube to AWS? (Just a thought - it's possible our docs are broken but I haven't had a chance to repro.)

**Comment by negz** [comment]
Whoops - closed by accident.

**Comment by alex-treebeard** [comment]
Everything was fine in creating the RDS instance so I doubt it. 

My hunch is the new Vpc was not configured correctly, but unfortunately don't have evidence. (I'm not the most knowledgeable on configuring these networks)

**Comment by negz** [comment]
I suspect your hunch is right. The guide actually uses an older version of provider-aws (v0.16 per [this pin](https://github.com/crossplane/crossplane/blob/69b559/docs/snippets/package/aws-with-vpc/crossplane.yaml#L15)) where the `RouteTable` type was at `v1alpha4`. We dropped that alpha version and it's now at `v1beta1` in provider-aws v0.19.

Did you happen to manually install the newer version of provider-aws before following the guide? Installing the getting started configuration should have installed v0.16.

**Comment by negz** [comment]
I've confirmed that when I use provider-aws v0.19 I need to edit the Composition to use a v1beta1 RouteTable. When I do that I can successfully run the 'see-db' pod and connect to the database.
