### ISSUE TITLE
Promote `Lock` to v1beta1

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2469]
### What problem are you facing?

The (package) `Lock` type was added back in [v1.0.0](https://github.com/crossplane/crossplane/releases/tag/v1.0.0). We need to make a decision on whether it is ready to promote to v1beta1.

### How could Crossplane help solve your problem?

We should determine what we want to do with `Lock` - e.g. update it to v1beta1 as is, remove it, or leave it as is. If we do decide to leave it as is it we should define what we would want from the type in order for it to reach v1beta1.

**Comment by negz** [comment]
@hasheddan this one has mostly been your baby too. :) How do you feel about it?

**Comment by hasheddan** [comment]
@negz I am feeling pretty good about it. I think it has been working fairly soundly as a mechanism that sits behind the scenes and does its job without many users even knowing it exists. I would like for users to stress test package dependency trees further than they are at this time, but I don't envision future changes to dependency management directly affecting this rather generic API (the only change I can currently think of would be expanding the [package type enum](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Lock/v1alpha1@v1.3.0#packages-type), which would be non-breaking). I can go ahead and bump for v1.4 if all are aligned 👍🏻

**Comment by negz** [comment]
@hasheddan that sounds good. Let's discuss this at the community meeting before proceeding.
