### ISSUE TITLE
Document Composition patterns and gotchas

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2470]
### What problem are you facing?

There are a handful of things you can do using Crossplane Compositions that may not be immediately obvious. I'm thinking of things like:

* Patching from one composed resource to another (via the XR)
* Deriving a connection detail from a composed resource (again via the XR)
* Deriving XR status from a composed resource
* Using external names to influence external resource names
* Combining providers (e.g. provider-sql with provider-aws)

There's probably a few more ideas at https://github.com/crossplane/crossplane/discussions too.

### How could Crossplane help solve your problem?

I think we'd benefit from a 'Composition patterns' page somewhere on the https://crossplane.io documentation site.

**Comment by halcyondude** [comment]
> Using external names to influence external resource names

Is this a reference to [ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname)?

**Comment by negz** [comment]
> Is this a reference to ExternalName?

No - that's a coincidence. This is refering to the `crossplane.io/external-name` annotation that influences and/or captures the actual name (unique identifier) of a resource in an external system when that name should or must differ from the Kubernetes resource's `metadata.name`.

**Comment by halcyondude** [comment]
I see, thanks for explaining.

I'm happy to help review the document (in draft/rough is fine) when the time comes. I'm a new user with fresh eyes.

**Comment by negz** [comment]
I updated this to include documenting some of the gotchas that folks run into with Composition.

One that immediately comes to mind is XR secrets. For an XR secret to work a lot of things have to align. Specifically:

1. The XRD must declare what connection details its XR can expose.
1. The XR must be configured to write a connection secret (e.g. have `writeConnectionSecretToRef` set.
1. The connection detail keys declared in 1 must be populated by the Composition
1. If you're using `fromConnectionSecretKey` to achieve 3 the composed resource you're extracting connection details from must actually write those keys to its own secret - i.e. it must also specify a `writeConnectionSecretToRef`.

Finally, all of this is made harder by the fact that we don't actually document what connection details each managed resource exposes.
