### ISSUE TITLE
Reduce "object has been modified" errors

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2472]
### What problem are you facing?

Crossplane controllers - particularly the composition controllers - tend to hit a lot of "object has been modified" errors. These errors are returned by the API server when we attempt to mutate a resource with a stale resource version. I believe they're HTTP 409 Conflict errors.

Here's an example of a resource claim that hit three of these errors in a matter of seconds.

```
Events:
  Type     Reason                      Age                From                                                             Message
  ----     ------                      ----               ----                                                             -------
  Warning  BindCompositeResource       13s                offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot update object: Operation cannot be fulfilled on postgresqlinstances.database.example.org "my-db": the object has been modified; please apply your changes to the latest version and try again
  Normal   ConfigureCompositeResource  13s (x3 over 13s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Normal   ConfigureCompositeResource  13s (x5 over 13s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Warning  BindCompositeResource       13s                offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot update composite resource claim: Operation cannot be fulfilled on postgresqlinstances.database.example.org "my-db": the object has been modified; please apply your changes to the latest version and try again
  Normal   BindCompositeResource       13s (x3 over 13s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Composite resource is not yet ready
  Warning  BindCompositeResource       13s                offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot update composite resource: Operation cannot be fulfilled on compositepostgresqlinstances.database.example.org "my-db-58hhn": the object has been modified; please apply your changes to the latest version and try again
  Normal   BindCompositeResource       13s (x3 over 13s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Composite resource is not yet ready
```

I'm surprised by how many of these we hit, especially for resources like claims that are mutated by only a single controller. They don't really get in the way of anything working, but I do suspect they're leading to us hitting the API server more than we need to (i.e. multiple requeues resulting in multiple failed writes).

### How could Crossplane help solve your problem?

I'd like to understand why we're seeing so many of these, and if possible reduce them.

**Comment by MisterMX** [comment]
I believe this problem could be avoided by using `kube.Patch()` instead of `kube.Update()`?

**Comment by negz** [comment]
@MisterMX I believe so - at least with server-side apply. xref https://github.com/crossplane/crossplane-runtime/pull/358

**Comment by negz** [comment]
Just noticed we also have https://github.com/crossplane/crossplane/issues/2114, so I'm closing as a duplicate.
