### ISSUE TITLE
Crossplane scalability

### ISSUE THREAD

**Issue by alexandru-crossover** [crossplane/crossplane#2477]
### What problem are you facing?
We have an K8S cluster with over 1000 composite resources and over 2000 AWS resources managed by Crossplane (a combination of API Gateway, SNS and SQS resources). We are noticing slower and slower sync times for both types of resources. 

We ran some load tests using Crossplane 1.1.1 (prod version) and version 1.3.0. Both are showing the same behavior. 

We have tested with different `poll-interval` values for the AWS provider. Using 15 minutes showed a 2x improvement compared to the default value of 1 minute. This helps, but it's still slow for our use case.

Even with that improvement, we are still seeing significant delays in propagating changes between composition components. For example, we have a composite component that creates 2 resources: an API GW integration and a route for it. Usually, the integration gets created in less than 1 second, but then it takes over 2 minutes for the route to notice the updated integration ID and create the corresponding AWS resource.

### How could Crossplane help solve your problem?
Some suggestions that come to mind:
1. Expose the poll interval for all providers (already part of the AWS provider 0.20 RC version).
2. Have a configurable rate limiting behavior for all controllers, instead of using the default one (for the Crossplane controller) or a hardcoded 1 request/second value for the AWS provider. It would be nice if we could set different values for different resources.
3. Have a configurable `MaxConcurrentReconciles` value (unless there's a specific reason for why it should be 1).
4. Support horizontal scaling for the controller replicas.

**Comment by negz** [comment]
Thanks for raising this @alexandru-crossover! I'm planning to spend some of this quarter focused on scalability issues like these, so this is great feedback to have. I broadly agree with all of your suggestions. I'm also hopeful that a few other improvements (i.e. writing fewer noisy events, looking for places we hit errors and requeue too frequently) will help.

I'm planning to run similar scale tests to those you mentioned in the coming weeks to get a baseline for the improvements we have in mind.

**Comment by turkenh** [comment]
Re: `MaxConcurrentReconciles`

We had similar scalability issues in provider-helm while trying to manage 1000+ helm releases and [bumping](https://github.com/crossplane-contrib/provider-helm/pull/53) `MaxConcurrentReconciles` helped in our case.

**Comment by negz** [comment]
I've started tracking some scale testing of our own in https://github.com/crossplane/crossplane/issues/2568, mostly to give us a repeatable way to test potential improvements such as the ones you've suggested. So far our tests are fairly in line with what you're seeing.

**Comment by negz** [comment]
Some ideas for improvements in https://github.com/crossplane/crossplane/issues/2595.
