### ISSUE TITLE
Cut v1.3.1 Release on August 23, 2021

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2508]
### Steps

This issue can be closed when we have:

- [x] Updated all version information in the documentation on the relevant release branch ([link][docs-update-pr]).
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version ([link][tag]).
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel. ([link][release-build]).
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [registry.upbound.io] for all getting started packages.
    - [x] `xp/getting-started-with-aws` ([link][xp/getting-started-with-aws])
    - [x] `xp/getting-started-with-with-with-vpc` ([link][xp/getting-started-with-aws-with-vpc])
    - [x] `xp/getting-started-with-azure` ([link][xp/getting-started-with-azure])
    - [x] `xp/getting-started-with-gcp` ([link][xp/getting-started-with-gcp])
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel ([link][stable-build]).
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes ([link][release]).
- [x] Updated the [releases table] in the `README.md` on `master` ([link][release-table-pr]).
- [x] Ensured that users have been notified of the release on all communication channels:
    - [x] Slack ([link][slack])
    - [x] Twitter ([link][twitter])

[release-branch]: #
[empty-commit-pr]: #
[rc-tag-workflow]: #
[rc-tag]: #
[website-pr]: #

[docs-update-pr]: https://github.com/crossplane/crossplane/pull/2517
[tag-workflow]: https://github.com/crossplane/crossplane/actions/runs/1159865200
[tag]: https://github.com/crossplane/crossplane/releases/tag/v1.3.1
[ci-workflow]: https://github.com/crossplane/crossplane/actions/runs/1159872393
[release-build]: https://releases.crossplane.io/build/release-1.3/v1.3.1/
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/runs/1159915009
[xp/getting-started-with-aws]: https://cloud.upbound.io/registry/xp/getting-started-with-aws/v1.3.1
[xp/getting-started-with-aws-with-vpc]: https://cloud.upbound.io/registry/xp/getting-started-with-aws-with-vpc/v1.3.1
[xp/getting-started-with-azure]: https://cloud.upbound.io/registry/xp/getting-started-with-azure/v1.3.1
[xp/getting-started-with-gcp]: https://cloud.upbound.io/registry/xp/getting-started-with-gcp/v1.3.1
[promote-workflow]: https://github.com/crossplane/crossplane/actions/runs/1159929730
[stable-build]: https://releases.crossplane.io/stable/v1.3.1/
[release]: https://github.com/crossplane/crossplane/releases/tag/v1.3.1
[slack]: https://crossplane.slack.com/archives/CEFQCGW1H/p1629748312027900
[twitter]: https://twitter.com/crossplane_io/status/1429908702660804616?s=20
[release-table-pr]: https://github.com/crossplane/crossplane/pull/2521

### Notes

[releases.crossplane.io]: https://releases.crossplane.io
[registry.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new
[releases table]: https://github.com/crossplane/crossplane#releases
[Crossplane docs website repo]: https://github.com/crossplane/crossplane.github.io

**Comment by turkenh** [comment]
In progress...

> ### Steps
> This issue can be closed when we have:
> 
> * [x]  Updated all version information in the documentation on the relevant release branch ([link](https://github.com/crossplane/crossplane/pull/2517)).
> * [ ]  Run the [Tag workflow](#) on the relevant release branch with the proper release version ([link](#)).
> * [ ]  Run the [CI workflow](#) on the release branch and verified that the tagged build version exists on the [releases.crossplane.io](https://releases.crossplane.io) `build` channel. ([link](#)).
> * [ ]  Run the [Configurations workflow](#) on the release branch and verified  that version exists on [registry.upbound.io](https://cloud.upbound.io/browse) for all getting started packages.
>   
>   * [ ]  `xp/getting-started-with-aws` ([link](#))
>   * [ ]  `xp/getting-started-with-with-with-vpc` ([link](#))
>   * [ ]  `xp/getting-started-with-azure` ([link](#))
>   * [ ]  `xp/getting-started-with-gcp` ([link](#))
> * [ ]  Run the [Promote workflow](#) with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io](https://releases.crossplane.io) `stable` channel ([link](#)).
> * [ ]  Published a [new release](https://github.com/crossplane/crossplane/releases/new) for the tagged version, with the same name as the version and descriptive release notes ([link](#)).
> * [ ]  Updated the [releases table](https://github.com/crossplane/crossplane#releases) in the `README.md` on `master` ([link](#)).
> * [ ]  Ensured that users have been notified of the release on all communication channels:
>   
>   * [ ]  Slack ([link](#))
>   * [ ]  Twitter ([link](#))
> 
> ### Notes

**Comment by turkenh** [comment]
All steps are done, release completed.
