### ISSUE TITLE
Cut v1.4.0 on August 31, 2021.

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2523]
### Steps

This issue can be closed when we have:

- [x] Created the [release branch][release-branch].
- [x] Created and merged an empty commit to the `master` branch ([PR][empty-commit-pr]).
- [x] Run the [Tag workflow][rc-tag-workflow] on the `master` branch with the next release candidate tag ([Tag][rc-tag]).
- [x] Updated the current release version in the [Crossplane docs website repo] ([link][website-pr]).
- [x] Updated all version information in the documentation on the relevant release branch ([link][docs-update-pr]).
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version ([link][tag]).
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel. ([link][release-build]).
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [registry.upbound.io] for all getting started packages.
    - [x] `xp/getting-started-with-aws` ([link][xp/getting-started-with-aws])
    - [x] `xp/getting-started-with-with-vpc` ([link][xp/getting-started-with-aws-with-vpc])
    - [x] `xp/getting-started-with-azure` ([link][xp/getting-started-with-azure])
    - [x] `xp/getting-started-with-gcp` ([link][xp/getting-started-with-gcp])
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel ([link][stable-build]).
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes ([link][release]).
- [x] Updated the [releases table] in the `README.md` on `master` ([link][release-table-pr]).
- [x] Ensured that users have been notified of the release on all communication channels:
    - [ ] Slack ([link][slack])
    - [ ] Twitter ([link][twitter])

[release-branch]: https://github.com/crossplane/crossplane/tree/release-1.4
[empty-commit-pr]: https://github.com/crossplane/crossplane/pull/2540
[rc-tag-workflow]: https://github.com/crossplane/crossplane/actions/runs/1186014852
[rc-tag]: https://github.com/crossplane/crossplane/releases/tag/v1.5.0-rc.0
[website-pr]: https://github.com/crossplane/crossplane.github.io/pull/120

[docs-update-pr]: https://github.com/crossplane/crossplane/pull/2541
[tag-workflow]: https://github.com/crossplane/crossplane/actions/runs/1186058464
[tag]:https://github.com/crossplane/crossplane/releases/tag/v1.4.0
[ci-workflow]: https://github.com/crossplane/crossplane/actions/runs/1186061446
[release-build]: https://releases.crossplane.io/build/release-1.4
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/runs/1186067537
[xp/getting-started-with-aws]: https://cloud.upbound.io/registry/xp/getting-started-with-gcp/v1.4.0
[xp/getting-started-with-aws-with-vpc]: https://cloud.upbound.io/registry/xp/getting-started-with-aws-with-vpc/v1.4.0
[xp/getting-started-with-azure]: https://cloud.upbound.io/registry/xp/getting-started-with-azure/v1.4.0
[xp/getting-started-with-gcp]: https://cloud.upbound.io/registry/xp/getting-started-with-gcp/v1.4.0
[promote-workflow]: https://github.com/crossplane/crossplane/actions/runs/1186522710
[stable-build]: https://releases.crossplane.io/stable/v1.4.0/
[release]: https://github.com/crossplane/crossplane/releases/tag/v1.4.0
[slack]: https://crossplane.slack.com/archives/CEG3T90A1/p1630438710100200
[twitter]: #
[release-table-pr]: https://github.com/crossplane/crossplane/pull/2542

### Notes

[releases.crossplane.io]: https://releases.crossplane.io
[registry.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new
[releases table]: https://github.com/crossplane/crossplane#releases
[Crossplane docs website repo]: https://github.com/crossplane/crossplane.github.io

**Comment by negz** [comment]
The v1.4 release will EOL the v1.1 release, so another little task here will be to remove the v1.1 release from our list of supported resources in `README.md`.

**Comment by hasheddan** [comment]
Also as part of the v1.1 EOL, a PR will need to be made to the `release-1.1` branch adding `DOCS_VERSION_ACTIVE=false` in the `Makefile`. (see https://github.com/crossplane/crossplane/pull/2516 for more info)

**Comment by muvaf** [comment]
I've used the following code to get all PRs introduced in this release. I'm thinking of adding a `make release-notes` target to build submodule that will run a Python or Bash version of this.
```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os/exec"
	"regexp"
	"strings"
	"time"

	"github.com/pkg/errors"
	"golang.org/x/net/html"
)

func main() {
	c := exec.Command("bash", "-c", "git log --left-right --graph --cherry-pick --oneline master...upstream/release-1.3")
	out := &bytes.Buffer{}
	c.Stdout = out
	errOut := &bytes.Buffer{}
	c.Stderr = errOut
	if err := c.Run(); err != nil {
		panic(errors.Wrap(err, errOut.String()))
	}
	r := regexp.MustCompile("Merge pull request #[0-9]+")
	matches := r.FindAllString(out.String(), -1)
	nums := map[string]struct{}{}
	for _, match := range matches {
		num := strings.Split(match, "#")[1]
		nums[num] = struct{}{}
	}
	for num := range nums {
		resp, err := http.Get(fmt.Sprintf("https://github.com/crossplane/crossplane/pull/%s", num))
		// handle the error if there is one
		if err != nil {
			panic(err)
		}
		title := GetHtmlTitle(resp.Body)
		title = strings.Split(title, " · ")[0]
		words := strings.Split(title, " ")
		user := words[len(words)-1]
		title = strings.ReplaceAll(title, user, "@"+user)
		fmt.Printf(fmt.Sprintf("* #%s - %s\n", num, title))
		resp.Body.Close()
		time.Sleep(time.Second)
	}
}

func GetHtmlTitle(r io.Reader) string {
	doc, err := html.Parse(r)
	if err != nil {
		panic("Fail to parse html")
	}

	return traverse(doc)
}

func traverse(n *html.Node) string {
	if n.Type == html.ElementNode && n.Data == "title" {
		return n.FirstChild.Data
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		result := traverse(c)
		if result != "" {
			return result
		}
	}
	return ""
}
```

**Comment by muvaf** [comment]
v1.4.0 is out! https://github.com/crossplane/crossplane/releases/tag/v1.4.0
