### ISSUE TITLE
Support for update for external-name and other identifier fields

### ISSUE THREAD

**Issue by Feggah** [crossplane/crossplane#2532]
### What problem are you facing?
After developing some managed resources, I got into an use case where I want to update a field that is used as an "identifier" in `GET` requests. Usually, this field is the external-name, which we can get by calling `meta.GetExternalName()`. The problem relies on when someone updates the `external-name` annotation, the first reconcile loop with the new name won't behave as expected.

The desired behavior would be:
1. Observe that the external-name is not up to date
2. Update the external name with the new name defined in the managed resource manifest

Actual behavior:
1. Tries to GET the resource with the new external name
2. Does not find it (because in the external provider the resource has the old name)
3. Create another resource with the new name

This same behavior can happen for fields that are part of the GET request. For example, the `Type` field of the `ResourceRecordSet` is used with the external name to try to get the resource, [see the code](https://github.com/crossplane/provider-gcp/blob/master/pkg/controller/dns/resource_record_set.go#L120-L124).

Because those fields are used to identify the resource, when the user tries to update them, Crossplane won't guarantee that the resource will be managed properly. As a solution, I was duplicating this field in `Status`, where I would keep track of the last value for those kind of fields. Then, if the first `GET` request returns `404`, I would try again with the `Status` value. You can see this example [here](https://github.com/crossplane/provider-gcp/blob/739cff4d7efd95375cb1aa7589b2a52135c11b22/pkg/controller/dns/resource_record_set.go#L228-L252).

This solution of relying on `Status` in the CRD logic isn't recommended, as you can see in the [Kubebuilder tutorial](https://book.kubebuilder.io/cronjob-tutorial/api-design.html):
> ... Remember, since we never read our own status, ...

and pointed out by @turkenh in the PR [review comments](https://github.com/crossplane/provider-gcp/pull/358#discussion_r695212136) (please, read this review discussion):
> We should not rely on Status for the desired state. ... See some related discussion on why relying on status is something we should avoid: vmware-tanzu/velero#1687

If we shouldn't rely on `Status` to keep track of those "last" values for identifier fields, how can Crossplane support updates on them?

Updating a resource external-name is a pretty common use case, and the manual job to do it is overhead (setting the `deletionPolicy` to `Orphan`, change the external name manually, importing it again to Crossplane with the new external-name annotation).

### How could Crossplane help solve your problem?
Supporting update on identifier fields (usually the external-name annotation).

**Comment by muvaf** [comment]
IMO, the external name is the unique and sole identifier of a resource; similar to ID of VPC in AWS; the string that would never change in the whole lifecycle of given resource.

> But the implementation would be almost the same, we would need to try to GET the resource twice, first with the external-name annotation, if this returns 404 NOT FOUND, then try again with last-seen-name annotation.

**Comment by Feggah** [comment]
> I think we can add webhooks to treat this annotation immutable once set preventing edits before they happen.

I think it isn't ideal, because we are removing a feature from the API (the API supports updating the resource name, we wouldn't support it because of design issues), but if we have a webhook to validate this, the feedback to the user in the `kubectl apply` is instantaneous and its going to remove the "undesired behavior" of creating a new resource instead of renaming the older one.

This behavior of creating a new resource instead of renaming it (because the controller would try to GET the resource with the new name, which doesn't exists and create it because of that) isn't an easy debug for users that don't understand about the provider implementation. The webhook would remove the need for them to understand about how controllers are implemented underneath.

I'm not super into this design choice, but at least it will remove this gap for now.
