### ISSUE TITLE
XRC used to adopt an orphaned primitive never reaches ready state with default readiness check

### ISSUE THREAD

**Issue by dfallert-rcd** [crossplane/crossplane#2538]
### What happened?
An XRC that's used to "adopt" a resource currently unmanaged by Crossplane doesn't seem to ever reach the ready state.
The reason, according to the claim, is ` Composite resource claim is waiting for composite resource to become Ready`

when examining the XR that's created via this claim, its status shows
```
Status:
  Conditions:
    Last Transition Time:  2021-08-30T23:28:36Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
```
with these events

```
Type    Reason             Age                     From                                                             Message
  ----    ------             ----                    ----                                                             -------
  Normal  ComposeResources   3m20s (x12 over 7m51s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
  Normal  SelectComposition  2m50s (x14 over 7m51s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition
  ```

While the claim continues to remain in the unready state, Crossplane seems to behave normally, and properly manage and sync the resource according to the composition.

### How can we reproduce it?
Create an XRC that dynamically provisions an XR, that uses a composition which patches the `crossplane.io/external-name` annotation with the name of an existing resource. S3 buckets are the easiest example.

### What environment did it happen in?
Crossplane version: 1.3.1

**Comment by negz** [comment]
Huh - interesting. Can you grab the events and status from the adopted resources (and any other resources of which the XR is composed)? I'd expect they're not becoming ready for some reason.
