### ISSUE TITLE
Contributor docs should add more prescriptive guidance about dev workflow

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#254]
We should have more guidance about how to create a fork/branch, open a PR, run tests, backport fixes to release branches, etc., similar to what Rook has:
https://rook.io/docs/rook/v0.9/development-flow.html

**Comment by jbw976** [comment]
Another thing I think we are missing is how to add a new CRD, controller, etc.  That would be good to document.

**Comment by negz** [comment]
I think we have most of this now between the release process docs, the managed resource developer guide, and the contributor guide.
