### ISSUE TITLE
compositionRevisionRef needs to be consistent when managing multiple clusters

### ISSUE THREAD

**Issue by jbhennin** [crossplane/crossplane#2544]
### What problem are you facing?

Although this feature is not yet released (slated for 1.4), we have identified a necessary area of improvement for those who manage many kubernetes clusters.  Currently, the implementation requires an individual with cluster scoped access to discover the available composition revisions by running `kubectl get compositionrevision -l  #crossplane.io/composition-name=example`  This is limiting as there is no way to communicate the CompositionRevisionRef to the users.  Even the current impl requires quite a bit of overhead requiring the Platform Operator to run a kubectl command for every composition to determine the latest revision and roll it out properly.

We enable both the platform operator who has cluster scoped access and an application developer (namespace access) to deploy resources within a cluster depending on environment.     Both personas should be able to easily manage the updates of the resources and reference a compositionRevision. 

Current Design: #2437 
Proposal: #1481 
Alpha Feature: #2451 

### How could Crossplane help solve your problem?
Instead of referencing a generated name for the `compositionRevisionRef`, it would be simpler to reference the Composition name plus revision number,  like `example-1`

This is assuming that the revision number only changes if the underlying composition changes.  If it changes on each install of the configuration, then I would suggest allowing control of the revision number as well. 

Simply - the reference of the revision needs to be consistent across all  clusters.

**Comment by anoop2811** [comment]
Additionally if it was possible to give more control on how the revision is expressed like for example if it supported semantic versioning, it would help to communicate to the consumers/developers on the extent of change to expect

**Comment by negz** [comment]
> Instead of referencing a generated name for the compositionRevisionRef, it would be simpler to reference the Composition name plus revision number, like example-1

One interesting challenge here is that we'd presumably need to coordinate to ensure each Crossplane cluster chose the same revision name. If we just use a monotonically increasing revision number there's technically nothing keeping different clusters in sync - e.g. if you create a `Composition` named `example` on one cluster then later (after say 3 revisions on the first cluster) created the (now updated) `Composition` on another cluster you'd potentially have `example-3` on the first cluster being equal to `example-1` on the second.

**Comment by anoop2811** [comment]
Yes, exactly the reason if we could have a version number that is manually set in the composition instead of auto generated revision which could help in such a situation

**Comment by negz** [comment]
@jbhennin just raised this at this week's community meeting. I'd like to get some more community input on this to make sure we arrive at a solution that works for everyone. So:

* Is anyone else hitting this issue at this stage?
* If so, do you feel a semver describing what revision of a composition your claim should target would make sense?

**Comment by nabadger** [comment]
SemVer support would be really nice here. but would love if it supported ranges/tilde/caret support (rather than just a string match).

**Comment by eloo** [comment]
Hi, 
i'm also just playing around with this feature and i can second that the generic revision name will cause trouble in our multicluster setup.
IMHO semver and using selector labels would maybe work for us 👍

**Comment by eloo** [comment]
not stale

**Comment by artem-nefedov** [comment]
This is also extremely important for GitOps model.
When all manifests are stored in git, and if your claim manifests have composition revisions, the deployment should be idempotent regardless of how many times composition was upgraded in the cluster.
Without it, whole GitOps setup completely falls apart.

**Comment by ezgidemirel** [comment]
Hi all, created a proposal [issue](https://github.com/crossplane/crossplane/issues/3415) to discuss the details of composition revision selectors. Any feedback is more than appreciated!
