### ISSUE TITLE
Helm Chart passes wrong flags to install providers and configurations

### ISSUE THREAD

**Issue by piotrmsc** [crossplane/crossplane#2549]
### What happened?
I'm using crossplane installed using helm charts in version 1.3.1, I have upgraded crossplane to recent version 1.4.0 but it does not work. Crossplane init container fails with : 

```
crossplane: error: unknown flag --provider, did you mean "--providers"?
Usage: crossplane core init

Make cluster ready for Crossplane controllers.

Flags:
  -h, --help                       Show context-sensitive help.
  -d, --debug                      Print verbose logging statements.

      --providers=PROVIDERS,...
      --configurations=CONFIGURATIONS,...
 
```

I have GCP provider `crossplane/provider-gcp:v0.17.1`

### How can we reproduce it?

1. Create k8s cluster (for reproducing I used k3d for simplicity `k3d cluster create test`)
2. Install helm with 1.3.1 `helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --set 'provider.packages={crossplane/provider-gcp:v0.17.1}'` 
3. Upgrade helm repo `helm repo update`
4. Upgrade crossplane with helm : `helm upgrade crossplane  crossplane-stable/crossplane --set 'provider.packages={crossplane/provider-gcp:v0.17.1}' --namespace crossplane-system`
5. Check new crossplane controller pod failing on init container.

### What environment did it happen in?
Crossplane version: 
1.3.1 then. upgraded to  1.4.0

GKE (1.20.8-gke.2100) and local k3d

If flag indeed changed than in the current helm chart flag is still `--provider`

**Comment by dfallert-rcd** [comment]
the arg in the helm chart is [here](https://github.com/crossplane/crossplane/blob/99643d044389ee8cab85e973b10ec3f5cb1945f9/cluster/charts/crossplane/templates/deployment.yaml#L40)

it may be worthwhile to verify if [this one](https://github.com/crossplane/crossplane/blob/99643d044389ee8cab85e973b10ec3f5cb1945f9/cluster/charts/crossplane/templates/deployment.yaml#L44) works as well, or if it too needs to be plural.

**Comment by negz** [comment]
Thanks for catching and diagnosing this folks!
