### ISSUE TITLE
Proposal for a new PR workflow to better track responses

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2550]
### What problem are you facing?

With large number of PRs that are opened across the repositories under `crossplane` org, especially providers, it becomes harder to respond on time with the reviews and sometimes it just slips through the cracks and maintainers/authors don't notice that they should respond.

### How could Crossplane help solve your problem?

We can have a bot that labels the PRs with a priority level that will be reset after every action by either author or reviewer. For example, if a PR is opened and it doesn't have any reviews/responses from the maintainers for 3 weeks, then it should be a high priority PR that we'd like to respond. Once a response is there, we'd let the author know that we're waiting for their action via a label.

The process would look roughly as following:
* `assignee-action-needed` label has been there for:
  * after 1 week -> `priority-3` label
  * after 2 weeks -> `priority-2` label
  * after 3 week and more -> `priority-1` label

After assignee (i.e. reviewer but we use assignee to show ownership) responds, they will switch the label to `author-action-needed` and bot would remove the priority label from that PR. Once author takes action, either commenting or pushing new commits, the counter starts again to label with priority.

**Comment by luebken** [comment]
The label "priority" would would conflict with other priorities besides age. 

Also do we really need a label? What about plain sorting by recently updated? https://docs.github.com/en/github/administering-a-repository/finding-information-in-a-repository/sorting-issues-and-pull-requests
