### ISSUE TITLE
Crossplane provider for Yandex Cloud

### ISSUE THREAD

**Issue by antonyc** [crossplane/crossplane#2556]
### What problem are you facing?

Having read the [contrib rules](https://github.com/crossplane/crossplane/blob/76319eb840e6813c1b78a1f672549dd39c8c7800/CONTRIBUTING.md), I suggest creating a Yandex Cloud provider. https://cloud.yandex.com/en-ru/ is a cloud offering virtual machines, load balancing, AI, Managed Databases, K8S and many more other services.

### How could Crossplane help solve your problem?
Please,
* point to a correct repository for the code: crossplane/ vs crossplane-contrib/ ?
* offer some other documents/best practices to create a new cloud provider

**Comment by negz** [comment]
Hi @antonyc! It sounds like you're interested in working on this provider. Is that correct?

If so we can get you setup with a repository under the crossplane-contrib org (we start new providers there these days). Sadly our provider development documentation needs work, but https://github.com/crossplane/crossplane/issues/2528 is currently a good list of all the resources we have available.

**Comment by antonyc** [comment]
It is correct, I am researching the actions needed for this.

**Comment by negz** [comment]
Nice! Thank you. I just created https://github.com/crossplane-contrib/provider-yandex-cloud and invited you as a maintainer.

**Comment by negz** [comment]
I think we've addressed everything here (apart from actually writing the provider) so I'm going to close this. Definitely let us know if we can help - Slack is probably the best place to reach out for that.
