### ISSUE TITLE
Installing packages with many CRDs causes reconciler to exceed context deadline

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2564]
### What happened?

Cannot install a provider package containing 750+ CRDs. 

Trying to install [provider-tf-aws](https://github.com/crossplane-contrib/provider-tf-aws) built from [this commit](https://github.com/crossplane-contrib/provider-tf-aws/tree/daf1e9f7fcbd7959c25ccdcc11e0800d17e904fe), but package is never installed.

I am observing context deadline errors in `providerrevisions.pkg.crossplane.io` events:

```
Spec:
  Desired State:                  Active
  Ignore Crossplane Constraints:  false
  Image:                          turkenh/provider-tf-aws:daf1e9f7-2
  Package Pull Policy:            IfNotPresent
  Revision:                       1
  Skip Dependency Resolution:     false
Status:
  Conditions:
    Last Transition Time:  2021-09-10T09:14:52Z
    Reason:                UnhealthyPackageRevision
    Status:                False
    Type:                  Healthy
  Controller Ref:
    Name:
Events:
  Type     Reason             Age                  From                                         Message
  ----     ------             ----                 ----                                         -------
  Warning  SyncPackage        76s                  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: context deadline exceeded
  Normal   BindClusterRole    16s (x4 over 2m16s)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole to provider ServiceAccount(s)
  Normal   ApplyClusterRoles  16s (x3 over 2m15s)  rbac/providerrevision.pkg.crossplane.io      Applied RBAC ClusterRoles
  Warning  SyncPackage        16s                  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: rate: Wait(n=1) would exceed context deadline
```

### How can we reproduce it?

`kubectl crossplane install provider turkenh/provider-tf-aws:daf1e9f7-2`

### What environment did it happen in?
Crossplane version: v1.3.1
Kubernetes Cluster: Kind - v1.21.1

Possibly related: https://github.com/crossplane-contrib/terrajet/issues/47

**Comment by turkenh** [comment]
I've updated the issue description, as originally I tried to install provider with controller image 🤦

**Comment by jbw976** [comment]
This is still occurring for some folks (see #3061) - we should reconsider the hard-coded timeout value and expose it as a configurable value.

**Comment by negz** [comment]
Let's make the context deadline configurable via a flag and also bump the default up a little - maybe to 5 mins for now? Ideally we'd avoid having configurable deadlines for only only a subset of reconcilers so maybe we can set one value for all of them? That said I could be convinced that package revisions are a special case.

We might also consider bumping the default Crossplane deployment's CPU resources up - we currently request `150m` cores by default (a small portion of one core) which is quite miniscule.

**Comment by jbw976** [comment]
@haarchri brought this up today in the community meeting, as he and others in the community are seeing similar behavior in #2849 and feeling the pain around it.

**Comment by negz** [comment]
Thanks @haarchri and @jbw976! This is going to be a priority ASAP.

**Comment by negz** [comment]
I just chatted with @avalanche123, who is going to take a shot at this! Per my comment at https://github.com/crossplane/crossplane/issues/2564#issuecomment-1165007894 the quick fix here is likely going to be to make this deadline configurable. That said, I think it would be interesting to check in with @hasheddan to see whether he can think of any low hanging fruit to speed up the reconcile process - perhaps parallelizing/batching CRD installs?

**Comment by negz** [comment]
We've had 1-2 reports of this still happening, so I'm reopening to dig into that.

**Comment by negz** [comment]
Specifically seeing this now:


```console
0s          Warning   SyncPackage               providerrevision/crossplane-provider-jet-azure-b7b0db0f74e0   cannot establish control of object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```

**Comment by negz** [comment]
Just confirmed I'm seeing the same with `upbound/crossplane:v1.9.0-up.2` too. Both tests using kind v1.24.0 clusters.

**Comment by negz** [comment]
And yet `crossplane/crossplane:v1.10.0-rc.0.31.g781e909f` works as I would expect. 🤔 I guess perhaps this issue is somehow isolated to UXP. Will close and move discussion there.

**Comment by haarchri** [comment]
@negz we see the warning as
well in 1.9.0 after a few loops it is working without handmade interactions

**Comment by nathkn** [comment]
We're running into this timeout a lot for provider packages that use the "flattened" filesystem instead of the OCI annotation for the package.yaml file, where all the layers have to be validated by the backend, which can take longer than 3 minutes. It'd be great to get the timeout to be configurable.
