### ISSUE TITLE
Automate provider repository creation

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2573]
### What problem are you facing?

Our GitHub Actions workflows use Docker Hub credentials to push to repositories. We used to use credentials that also had admin access and could thus automatically create new repositories as needed. Recently we switched to using credentials with only permissions to read and write from certain repositories. This means there's a fairly onerous process every time we want to setup a new provider to push to Docker Hub. Specifically we need to:

1. Create a repository for the controller and one for the provider package.
2. Repeat step 1 for each architecture we support.
3. Grant the "pushers" group Read & Write access to all repositories created in steps 1 and 2

We currently support two architectures, so we're creating six repositories for each provider.

### How could Crossplane help solve your problem?

We could script this process so that we don't need to do it manually via the Docker Hub UI. We could also consider pushing to another registry instead of Docker Hub, for example GCR or the Upbound Registry.

**Comment by turkenh** [comment]
@negz that would be helpful.

Actually intended to create such a script but looks like there is no proper tooling or API to automate this. Looking for a docker hub CLI, I found [this](https://github.com/docker/hub-tool#readme) (experimental) `hub-tool` cli but it does not have enough functionality (no repo create option):

```
hub-tool repo help
Error:
Usage:
  hub-tool repo
  hub-tool repo [command]

Available Commands:
  ls          List all the repositories from your account or an organization
  rm          Delete a repository

Flags:
  -h, --help   help for repo

Global Flags:
      --verbose   Print logs

Use "hub-tool repo [command] --help" for more information about a command.
```

and also there is a very limited REST API which seems not to have enough functionality: https://docs.docker.com/docker-hub/api/latest/#

We could at least automate creating repositories by pushing a first image (e.g. hello-world ?) with an admin user but granting access to "pushers" group would still be manual.
