### ISSUE TITLE
Patch `mergeOptions` are written from the perspective of Go code, not YAML

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2581]
### What happened?

https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.4.1

Currently a `Composition` patch policy can look like this:

```yaml
      policy:
        fromFieldPath: Required
        mergeOptions:
          appendSlice: true
          keepMapValues: true
```

There's a few inconsistencies that weren't caught at review time here. Namely:

1. The MergeOptions apply to the `toFieldPath` - this might be obvious but ideally it would be more explicit.
2. More importantly, from the perspective of a `Composition` author (who is working in YAML or JSON) there is no such thing as a "slice" (which is a Go concept). Instead the options should probably be named something more like `appendArray` and `keepObjectValues`. (I think `map` happens to be the correct type in YAML, but in JSON it's an object).

### How can we reproduce it?

I think the second issue above is important enough that we should consider trying to address it - possibly we could mark the existing (optional) `appendSlice` and `keepMapValues` options as deprecated and replace them with names that make sense in context? At the very least we should probably update the documentation to speak in YAML/JSON terms.

### What environment did it happen in?
Crossplane version:

**Comment by jeanduplessis** [comment]
@negz considering that [native patch-and-transform is now deprecated](https://github.com/crossplane/crossplane/pull/5885) and [naming changes were implemented in function-patch-and-transform](https://github.com/crossplane-contrib/function-patch-and-transform/pull/91), should we close this issue?
