### ISSUE TITLE
Proposal: Soften requirement for XRDs to declare connection details

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2593]
### What problem are you facing?

Currently in order for an XR (or claim) to successfully publish connection details to a secret:

1. The XRD that defines the XR and claim must declare what connection details they expose as part of [`spec.connectionSecretKeys`](https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/CompositeResourceDefinition/v1@v1.4.1)
2. The Composition used by the XR must specify how to map from composed resource connection secret keys to the XR keys defined in 1.
3. Everything along the way (composed resources, XRs, and the claim) must all specify `spec.writeConnectionSecretToRef`.

This is a common source of confusion - we see a lot of folks struggling to get XR connection secrets working. See https://github.com/crossplane/crossplane/issues/2417, https://github.com/crossplane/crossplane/issues/2376, and https://github.com/crossplane/crossplane/issues/2253. I suspect _part of_ this is because it's not obvious that a 'contract' is being established by the XRD that must be satisfied by the Composition. This is exacerbated by the fact that `spec.connectionSecretKeys` is actually immutable - edits once the XRD has been created have no effect.

### How could Crossplane help solve your problem?

I think we could:

1. Attempt to make `spec.connectionSecretKeys` mutable. This would require restarting the XR and claim controllers when said XRD field was edited. Perhaps we could hash the XRD spec and just restart the controllers whenever the XRD spec hash changed?
2. Loosen the contract of `spec.connectionSecretKeys`. If I recall correctly at the moment we'll just ignore any connection details mapped by a `Composition` if they don't correspond to an entry in `spec.connectionSecretKeys`. Perhaps we should instead treat the field as documentation and just include whatever the `Composition` specifies?

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/164eed44/internal/controller/apiextensions/composite/api.go#L78

I _think_ this would just be a case of either dropping the `APIFilteredSecretPublisher`, or perhaps updating it to warn us if it's publishing unexpected connection details?

**Comment by negz** [comment]
Another smaller change we could make is to just address the TODO @muvaf left in the above `APIFilteredSecretPublisher` implementation and switch up the API such that if you don't specify a filter (i.e. don't specify `spec.connectionSecretKeys`) we'll just allow all keys, but if you do specify a filter we'll maintain today's behaviour.

**Comment by Duologic** [comment]
Breadcrumb for those that are on 1.5 and earlier, delete the XRD from your cluster to ensure that `connectionSecretKeys` is updated.
