### ISSUE TITLE
Sizing guide for Control plane cluster

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2596]
### What problem are you facing?

Resource requirements of Crossplane and provider pods vary based on multiple factors:

- Number of managed resources
- Number of compositions
- Number of CRDs (i.e. providers) deployed
- Expected reconciliation time
- ...

While deploying crossplane and providers into a Kubernetes cluster, users need some guidance for sizing of the Kubernetes cluster (a.k.a. control plane cluster).

### How could Crossplane help solve your problem?

There needs to be a sizing guide where users can follow while planning the control plane cluster. I believe we would have more ideas on this after [scalability testing](https://github.com/crossplane/crossplane/issues/2568).

**Comment by negz** [comment]
https://github.com/negz/crossplane-scale/blob/f4dad1a/package/xclusters.test.crossplane.io/composition.yaml

FWIW I've been using the above config for the scale testing. Happy to provide more detail once we know more, but I would generally expect Crossplane to work fine on "most Kubernetes clusters" - our controllers aren't crazy resource hungry though they do make quite a few API calls.

**Comment by andrzej-natzka** [comment]
I started crossplane validation and would like to test some configurations like getting started or platform-ref. Currently I use 3 node AKS cluster with D2s_v3 machines and I wonder if this is really needed. Might be that one node will be sufficient for this.

**Comment by negz** [comment]
FWIW I've found that once you're getting up to managing _a lot_ of claims and managed resources (i.e. thousands) the Crossplane and provider pods benefit from having around one CPU core and quite a lot of memory - around 1GB. This assumes very high concurrency (i.e. thousands of goroutines), which is not currently tunable but hopefully soon will be.
