### ISSUE TITLE
Remove kubebuilder test harness

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#26]
we should consider removing the kubebuilder tool dependency while testing. Our test harness could start the api server and etcd in-proc if we need to without bringing in 100MB+ kubebuilder tool set.

**Comment by negz** [comment]
Related to https://github.com/crossplaneio/crossplane/issues/452

**Comment by negz** [comment]
I believe this is done, at least for Crossplane core. I think Azure AKS might be the only controller that still uses this harness, and it will naturally migrate away when we rev it to v1beta1.
