### ISSUE TITLE
Document supported Kubernetes versions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2600]
### What problem are you facing?

https://kubernetes.io/releases/

In practice we've historically aimed to support all Kubernetes versions that have not been declared EOL, but there's no way for users to know this.

### How could Crossplane help solve your problem?

Ideally we'd document this policy. Even more ideally we'd actually integration test it somehow.

**Comment by Anubha13kumari** [comment]
hi @negz  .first timer this side .i want to contribute on this issue  .

**Comment by muvaf** [comment]
Is this still relevant? All core kinds we use are at least `v1` and I can't really remember user feedback mentioning that Crossplane couldn't be installed due to k8s version. Feel free to re-open if you think otherwise.
