### ISSUE TITLE
Warnings are only logged in debug mode

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#2607]
### What happened?
I'm currently working with crossplane and i have seen that the log output of crossplane is not sufficient without enabling debug mode (which should not be the case in prod).

Currently important warning are logged in debug level but are internal marked as Warning which seems to be not really consistent. 

I would suggest to log Warning on Warn level as expected. This also applies to error and other important events. 

e.g.
```
DEBUG	crossplane.controller-runtime.manager.events	Warning	{"object": {"kind":"CompositeS3BucketInstance","name":"composite-bucket-instance-kn9kf","uid":"873caea0-e82c-40ac-b7e6-dcf6fa143b48","apiVersion":"acp.com/v1alpha1","resourceVersion":"42364776"}, "reason": "ComposeResources", "message": "cannot render composed resource from resource template at index 0: cannot use dry-run create to name composed resource: Bucket.s3.aws.crossplane.io \"composite-bucket-instance-kn9kf-hphsp\" is invalid: spec.writeConnectionSecretToRef.name: Required value"}
```

### How can we reproduce it?

* Create some compositions with errors
* Try to create a claim
* Check the logs in default mode
* Check the created resources
* You will see there is not information what is going wrong
* Enable debug mode for crossplane
* You will see important information which helps you to fix the issues

### What environment did it happen in?

Crossplane version: crossplane/crossplane:v1.4.1
Cloud provider or hardware configuration - aws-provider v0.19.1
Kubernetes version (use kubectl version) - v1.21.2-eks-0389ca3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
OS (e.g. from /etc/os-release) - Amazon Linux

**Comment by eloo** [comment]
not stale

**Comment by negz** [comment]
Per my comment at https://github.com/crossplane/crossplane/issues/2607#issuecomment-940395314, I don't think this is something we're going to change. As mentioned, the logs are intended only for debugging. Our suggestion here is to use events for this - either via `kubectl describe` or `kubectl get events` or by exporting events to your system of choice using e.g. https://github.com/opsgenie/kubernetes-event-exporter.
