### ISSUE TITLE
Docs: Describe configurations

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#2621]
### What problem are you facing?
[Configuration](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Configuration/v1@v1.4.1) is not described in the [concepts section](https://crossplane.io/docs/v1.4/concepts/overview.html) of the documentation only in the [getting started section](https://crossplane.io/docs/v1.4/getting-started/create-configuration.html).

### How could Crossplane help solve your problem?

- Add a concept section about configuration which describes its use-cases and the concept. 
- Add a paragraph to the overview section.

**Comment by negz** [comment]
https://crossplane.io/docs/v1.4/concepts/packages.html#configuration-packages
https://crossplane.io/docs/v1.4/concepts/terminology.html#configuration

It's not completely undocumented, but I agree we could use more. Are you thinking we should add a dedicated page under the 'Concepts' sidebar (like we have for 'Providers')?
