### ISSUE TITLE
Is it possible for package manager to use node image cache

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2647]
### What problem are you facing?

We're trying to make Crossplane provider installation work in an offline environment. While we can load the controller images into the node cache of `kind` cluster and use `IfNotExist` policy to make it use that, package manager has its own client that hits the registries. This results in a few things:
* Users have to deploy their own in-cluster registry.
* In-cluster local registry should have trusted CA certs for SSL https://github.com/crossplane/crossplane/issues/2318
* Need to pull & tag & push with different image URL.
* Need to override controller image URL via `ControllerConfig`

### How could Crossplane help solve your problem?

We might be able to make package manager request the image from the container runtime of the node, using the same path with `kubelet` when it starts a `Pod`. This will let admins pre-load images and users won't even have to worry that there is no connection.

I know @hasheddan had concerns about this but I'd like us to discuss the possible ways of doing it to see the trade-off and justify the UX we have to provide here.

**Comment by hasheddan** [comment]
Wanted to follow up on a few assertions here:
> Users have to deploy their own in-cluster registry

This is one option, but certainly not the only one. The [Crossplane package cache](https://crossplane.io/docs/v1.5/concepts/packages.html#the-package-cache) can be backed by any volume, which means that it can be [pre-populated](https://crossplane.io/docs/v1.5/concepts/packages.html#pre-populating-the-package-cache). In our integration tests for all `Providers` today, we actually use a [`PersistentVolume` that is mapped to a local directory on the host](https://github.com/crossplane/provider-aws/blob/34522c5e73b00e73eb0bd1e7ae0d127c33ab888b/cluster/local/integration_tests.sh#L100), meaning that the _only_ required step is to build the package (`kubectl crossplane configuration/provider build`). For development purposes, you can even use something like a [`Configmap` as a the package cache](https://danielmangum.com/posts/config-map-oci-image-cache/).

> We might be able to make package manager request the image from the container runtime of the node, using the same path with kubelet when it starts a Pod

I'm not sure I am following exactly what you are saying here, but interacting with kubelet / container runtime will likely require increased privileges, which is undesirable IMO (there may be a way to simulate interacting with the `kubelet` by creating a `Pod` that uses the package image as its container image, but extracting that image into the package cache would likely still be a challenge). In the `ConifgMap` post linked above, I demonstrate how an `initContainer` with a shared volume can do some interesting things, so building that functionality into an external tool could make sense. An even more interesting use case that I have considered is running a sidecar that exposes a registry interface and writes directly to a shared volume, which is also the package cache of Crossplane (this also requires some tool to inject the sidecar, or potentially a development flag on the Crossplane Helm chart). Adding [k8scr](https://github.com/hasheddan/k8scr) functionality to that tool could also mean that a load command could push the package image directly into the cache via the sidecar while only requiring access to a `kubeconfig` with `proxy` RBAC.

One other note is that #2671 explores the possibility of a "Provider Runtime Interface", which is partially enabled by this separation of the Crossplane package cache from a k8s node image cache. In the event that a `Provider` is being run "externally", the ability for Crossplane to maintain its own cache means that it no longer needs access to a k8s cluster that supports running containerized workloads (i.e. it no longer needs the `kubelet`).

Last note for any onlookers, @muvaf @luebken and I have put together an ["offline Crossplane"](https://github.com/hasheddan/crossplane-offline) workshop that show how you can do some of this in-cluster registry setup and have a fairly smooth development experience without any network connection :)

**Comment by negz** [comment]
Cross-linking to https://github.com/crossplane/crossplane/issues/2468
