### ISSUE TITLE
Promote `CompositionRevision` to v1beta1

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2656]
### What problem are you facing?

Support for `CompositionRevision` was added at v1alpha1 in v1.4.0. 
### How could Crossplane help solve your problem?

We need a plan to promote it to v1beta1, which may include accepting it as is, changing it, or dropping the feature. Community feedback would help here.

### Related issues

- [ ] https://github.com/crossplane/crossplane/issues/2762
- [ ] https://github.com/crossplane/crossplane/issues/3274
- [x] https://github.com/crossplane/crossplane/issues/2544
- [x] https://github.com/crossplane/crossplane/issues/3011
- [x] https://github.com/crossplane/crossplane/issues/3263
- [x] https://github.com/crossplane/crossplane/issues/3015
- [x] https://github.com/crossplane/crossplane/issues/2954

**Comment by samidbb** [comment]
I find this feature very useful to control rollout of updates to compositions. But the current implementation will require platform builders to communicate about the changes in compositions which can be implementation specific to the platform. An example could be changing the way of referencing the providerconfig in XRs. I doubt that the consumers will be bothered about such changes in the implementation as long as they do affect the API schema in most cases.

The idea is that I would like to keep the ability to do the changes as a platform builder and test them on a selected number of existing resources. Then when I'm done I would like to have the existing consumers upgraded to the new composition revision that I have marked as **stable**. This way I can do changes behind the scene without requiring consumers to change their claim manifests in a controlled manner. 

My suggestion is as follows:

1) Introduce a new field in the compositionRevision CRD. This could be called something like "Stable" with boolean value:
```
> kubectl get compositionRevision
NAME                                           REVISION   CURRENT   Stable  AGE
myeresouce.class.crossplane.dfds.cloud-ywbwz   3          False     True    41h
myeresouce.class.crossplane.dfds.cloud-6hbzj   2          False     False   44h
myeresouce.class.crossplane.dfds.cloud-q5w48   1          True      False   44h
```
2) Add support for a new field in claim/composite resources
```
apiVersion:class.crossplane.dfds.cloud/v1alpha1
kind: MyClaim
...
spec:
  parameters:
  ...
  compositionUpdatePolicy: Manual # Valid options: [Maunal, Automatic]. This is still the same 
  compositionUpdateStrategy: Latest # Valid options: [Latest, Stable]. Only will be activated if user set compositionUpdatePolicy to  Automatic
```  
compositionUpdateStrategy Field will only work activated in if compositionUpdatePolicy is set to Automatic:
* Latest, will have the same effect as in the current implementation
* Stable, would mean that the automatic update will only take affect if a new revision is marked as Stable by the platform builder.
And maybe we can add the option to omit this field in the claim by setting a default value to either Latest or Stable. This can also done in the the composition.  

3) Extend Crosslplane CLI with an option to set compositionRevision’s Stable field by using revision name

```
> kubectl crossplane compositionrevision set-stable  myeresouce.class.crossplane.dfds.cloud-ywbwz
```

**Comment by muvaf** [comment]
@samidbb I think that's a pretty good idea. Maybe we can name it `compositionUpdateChannel` similar to GKE's auto-upgrade feature where you can promote `CompositionRevision`s in channels like `stable`, `rapid` etc. The channels would probably be defined on `XRD` in an array of strings and you could mark specific `CompositionRevision`s as the latest one in that channel like you described.

**Comment by negz** [comment]
I think a `compositionRevisionSelector` that can match labels would cover most of @samidbb's use case. We discussed potentially adding that at https://github.com/crossplane/crossplane/issues/2544#issuecomment-950009419.

My thinking is that you could label revisions as `channel: stable` as well as (or instead of) `version: 1.0.0`. That way a particular claim could either a specific version by setting `spec.compositionRevisionSelector.matchLabels[version]: 1.0.0` or could target the 'stable channel' by setting `spec.compositionRevisionSelector.matchLabels[channel]: stable`.

**Comment by samidbb** [comment]
The idea about the update channels from @muvaf is a good inspiration and combining it with label techniques using compositionRevisionSelector suggested by @negz can potentially solve my case. It can also provide the flexibility to cover the other use case mentioned in #2544 as well. 
- But where in the process you would @negz set these labels? Would you create a new revision with these labels? or set labels on existing revisions using kubectl or in other way?
- If I have multiple revisions with the same label, say channel=stable, how would compositionRevisionSelector behave in combination with compositionUpdatePolicy=Automatic? Would it automatically upgrade the composite to the latest composition revision labelled as stable?

With regards to using semantic versioning, I don't think it will be relevant in our case. Consumers in my case should not be concerned with the changes in the underlying implementation. 
So by providing a combination of Automatic and Stable, they should be guaranteed to, for example, have a postgres database provisioned according to their specifications in their claims. Any change to the composite resource that would be introduced is verified and tested regardless of the type of change, and without the need to have consumers involved. Only exception, I can think of, is when there are changes in the API. 

non-stable or rapid or whatever we would call it, should be an opt-in to test new features, enhancements or fixes. Typically platform operators would make use of such feature to have a process for rolling out changes.

**Comment by eloo** [comment]
Hi,
just came across at the same operative issue as @samidbb
How do i "promote" a new revision to my customers. And i agree with the idea to mark version as "stable" "latest" whatever.

But as we are going to have everything in a gitops manner the use of the kubectl or something does not fit our needs.
Maybe we need something like a marker resource like "DefaultCompositionRevision" or something like this. 

This resource than holds the composition reference and the "selected" composition revision. 
And based on this resource the "current" revision is selected. 

Maybe this can also be enhanced to be something like "CompositionRevisionChannel" to have multiple mappings as suggested a few comments above.. 
so we could have a stable channel resource with mappings. and a beta channel resource with mappings.

I guess this would make the whole selection of "current" revision more transparent and enables us to test new revision in a pretty straight manner like this:
- create new revision
- test revision with specific claims using manual update policy
- if checks are good
  - change the mapping in DefaultCompositionRevision or CompositionRevisionChannel
  - new revision will be rolled out to all other claims
- if checks are not good
  - revert the claims
  - maybe just delete broken revision

**Comment by haarchri** [comment]
@eloo thank for opening https://github.com/crossplane/crossplane/issues/2954 we faced today the same for automatic - that the revision number is not updated

**Comment by haarchri** [comment]
Is this something for 1.10 / 1.11 ?

**Comment by jbw976** [comment]
I would like to see CompositionRevision matured/stabalized for folks to start depending on them over the next couple releases, yes @haarchri.  We can't guarantee that will be delivered, but I would like it to happen.  I've already included it on the Releases board :)

**Comment by muvaf** [comment]
I'm trying to get a complete list of issues need to be solved before `v1beta1`. What I'm looking for is essentially the issues that may result in breaking changes. Though given that we have webhook support, I think the bar for v1beta1 is lower than it used to be since we are now able to handle schema changes between two versions.

Behavior additions/changes:
* [ ] A stable identifier for revision selection. 
  * Adding a `compositionRevisionSelector` as suggested in https://github.com/crossplane/crossplane/issues/2544#issuecomment-950009419
  * And see the discussion above regarding channels.

Bugs:
* [ ] https://github.com/crossplane/crossplane/issues/3263
* [ ] https://github.com/crossplane/crossplane/issues/3011
* [ ] https://github.com/crossplane/crossplane/issues/3015
* [ ] https://github.com/crossplane/crossplane/issues/2954

@negz @ezgidemirel How does this list look?

I didn't include the following ones mentioned in issue description:
* https://github.com/crossplane/crossplane/issues/2762 
  * It's more related to `Composition` mechanics rather than how `CompositionRevision`s should work.
* https://github.com/crossplane/crossplane/issues/3274
  * I think it is a requirement for `CompositionRevision` to be fully compatible when we bump it to `v1beta1` bit automation of that process shouldn't be blocking the bump.

**Comment by negz** [comment]
Thanks @muvaf. That looks good to me.

> A stable identifier for revision selection

My suggestion is that we do two things here:

1. Switch to using a partial sha256 hash of the Composition to generate revision name suffixes per @eloo's suggestion at https://github.com/crossplane/crossplane/issues/2544#issuecomment-1061659094
2. Add a `compositionRevisionSelector` to allow selecting by labels.

The first feature seems like a cheap and elegant way to ensure a particular Composition will always have the same revision name across clusters. The second seems like an idiomatic (to Kubernetes) way to allow folks to follow a Composition "channel".

**Comment by ezgidemirel** [comment]
Thanks @negz for your suggestions. I believe the first item will also fix #3011.

**Comment by ezgidemirel** [comment]
Hi all, created a proposal [issue](https://github.com/crossplane/crossplane/issues/3415) to discuss the details of composition revision selectors. Any feedback is more than appreciated!

**Comment by negz** [comment]
I just realized I hadn't explicitly noted that once we hit v1beta1 we should make the feature on by default. This would involve `s/Alpha/Beta` at https://github.com/crossplane/crossplane/blob/b98ec8/internal/features/features.go#L26, moving https://github.com/crossplane/crossplane/blob/b98ec8/cmd/crossplane/core/core.go#L79 to `group:"Beta Features:", and defaulting it to true.

We'll also need to raise a new tracking issue to get the feature to v1. Once it's v1 we'll want to:

* Remove the aforementioned feature flag and make the CLI flag a no-op (i.e. the feature will be enabled regardless of the flag). We can mark it hidden so no-one sees it in the documentation but anyone who is setting the flag won't be broken.
* Refactor the Composition -> CompositionRevision flow. Currently when CompositionRevisions are enabled the XR reconciler converts the relevant CompositionRevision back to a Composition (internally) and uses that for its composition logic. I did this to keep the XR code identical whether revisions were enabled or not. Once they're on by default we can update the XR reconciler to be only concerned with CompositionRevisions and get rid of the code that converts from a CompositionRevision to a Composition.

**Comment by ezgidemirel** [comment]
Hello everyone, we've finished the tasks in this issue and we believe that we can promote composition revisions to v1beta1 now. If you're interested in the feature you can install the latest changes with the commands below:
```
kubectl create namespace crossplane-system
helm repo add crossplane-master https://charts.crossplane.io/master/
helm repo update
helm install crossplane -n crossplane-system crossplane-master/crossplane --devel --version 1.11.0-rc.0.93.gb9e4773d --set args='{"--enable-composition-revisions"}'
```
Any suggestions/feedback is more than appreciated!
