### ISSUE TITLE
Openstack Provider

### ISSUE THREAD

**Issue by peyunco** [crossplane/crossplane#267]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
* Crossplane should be able to deploy or migrate workloads on Openstack cloud environment.

**What is use case behind this feature:**
* User can successfully deploy or migrate workloads to Openstack environments through the use of different Openstack services as authentication, compute, image, networking and storage.

**Environment**:

* N.A.

**Comment by kevin-zhaoshuai** [comment]
Any update on this?
If not, I can take over this task now.
We ( Linaro ) are using OpenStack deeply in a public cloud

**Comment by bassam** [comment]
@kevin-zhaoshuai we'd love your support here ! Please join the slack channel at https://slack.crossplane.io and we'd love to discuss further.

**Comment by hasheddan** [comment]
@kevinzs2048 are you still interested in helping out here?

**Comment by kevinzs2048** [comment]
@hasheddan Hi, I do not have time recently working on this. But will still pay attention on this topic.

**Comment by muvaf** [comment]
I have added this issue to `Proposed` column of the next release. I believe at least bootstrapping the provider repo and implement 1 small resource would be much of help to folks who'd like to contribute for specific managed resources.

**Comment by till** [comment]
I want to experiment with this as well. Not sure how much I can contribute, but will definitely try it if you have an example repository which implements something. :)

**Comment by prasek** [comment]
@till an example repo would be awesome! 👍 

Are you using the native Open Stack APIs or the AWS compatibility APIs?

Also we're working on code generating resource controllers on top of the Terraform Providers #262. Are you using the [OpenStack Terraform Provider](https://www.terraform.io/docs/providers/openstack/index.html) today? If you give us the list of OpenStack resources you need we can prioritize them for code generation. We should be able to generate most of what's needed, but each resource will need a few annotations to assist the code generation, so if you're interested in helping with that and testing on OpenStack, it could help speed things along.
/cc @kevinzs2048 @kasey

**Comment by till** [comment]
@prasek We use OpenStack-APIs. Not aware of a compat layer (any info on that?).

And yes, we use the Terraform provider. I think my basic needs are described here: terraform-providers/terraform-provider-openstack#541

Essentially creating the network environment and attaching an instance to it:

 - network
 - subnet
 - ports
 - instance

**Comment by till** [comment]
I got so excited and forgot that we probably also need a router and a floating IP. But I can try to help too.

Is there anything to take a look at yet?

**Comment by till** [comment]
@prasek do you have anything I could hack on? The Terraform integration sounds great since we use Terraform already.

**Comment by till** [comment]
Leaving this here:
https://github.com/subhransusekhar/provider-openstack

Will experiment on the weekend.

**Comment by MPV** [comment]
In addition to @subhransusekhar (as mentioned above), it seems like @rochaporto has also started something recently, here: https://github.com/rochaporto/provider-openstack

**Comment by rochaporto** [comment]
Yes, i'm working on this. I'm particularly interested in instantiating kubernetes clusters (with Magnum) so will push that first.

**Comment by luebken** [comment]
With [crossplane-contrib/terrajet](https://github.com/crossplane-contrib/terrajet) we have created a tool that creates Crossplane providers with very low effort based of a Terraform provider. In this case, https://github.com/terraform-provider-openstack/terraform-provider-openstack/.  If someone wants to take a look, please let me know, we are happy to assist.

**Comment by negz** [comment]
Just testing the stale bot using this issue - I do actually think this is stale.

**Comment by Dentrax** [comment]
Hey @rochaporto, still working on this? Any updates? 🤔

**Comment by rochaporto** [comment]
Hi @Dentrax . We're meeting today between different people to work out how to best progress with this. Will update the ticket soon.

**Comment by chriscowley** [comment]
@rochaporto What was the outcome of that meeting? Is there even a pre-alpha provider that people can start getting their hands dirty with ?

**Comment by ja-gooding** [comment]
Is there a reason this issue was closed?

**Comment by jbw976** [comment]
Good question @ja-gooding - I do still see demand for this and folks asking about it, so I'll re-open this issue :)

**Comment by rimbi** [comment]
Hi All, our team needs an OpenStack provider. Given some guidance, we might allocate the effort to do the development.

**Comment by schlakob** [comment]
It looks like @martinnirtl recently has started working on a provider here:  https://github.com/martinnirtl/provider-openstack 
The provider is already available on the marketplace: https://marketplace.upbound.io/providers/martinnirtl/provider-openstack/v0.1.1

At the moment it only supports a simple compute InstanceV2, but since it is build on upjet it should be possible to add additional resources as well.

**Comment by negz** [comment]
I wanted to note that currently there are no plans for _the maintainers of Crossplane_ to work on this provider. Our focus is on the "core" of Crossplane, rather than building providers.

That isn't to say we don't strongly support the creation of this provider. I'm sure it would be very useful. We'd be happy to create a repository under https://github.com/crossplane-contrib if anyone feels motivated to step up and maintain a provider for Openstack.

**Comment by rochaporto** [comment]
We're still interesting on this, i think it's worth it to create the repo and iterate there.

**Comment by martinnirtl** [comment]
Hi there!
think the owner of this repo is already on this issue.
@schlakob would you be up moving your provider-openstack to crossplane-contrib?

**Comment by schlakob** [comment]
Hi @negz @martinnirtl,
sure we would like to move the dusky-mate/provider-openstack to crossplane-contrib. Are there any special requirements, or is there a contact person we can get in touch with?

**Comment by negz** [comment]
@schlakob Sorry just saw this - let me get back to you ASAP.

**Comment by jbw976** [comment]
Awesome @schlakob!!! I can help you out with the process - essentially you can choose from one of the options described in https://github.com/crossplane/org/issues/32.

Feel free to reach out to me directly on Crossplane Slack to discuss more if that's better for you 🙇

**Comment by jbw976** [comment]
@schlakob has generously transferred ownership of the provider-openstack repo over to the crossplane-contrib organization - folks are welcome to collaborate there in its new neutral community home! awesome!! 🙇‍♂️ 🤩 

https://github.com/crossplane-contrib/provider-openstack

**Comment by schlakob** [comment]
Thanks to @jbw976 for helping with the transfer. 

I'm looking forward to work together on the provider for Openstack. 💪

**Comment by negz** [comment]
I'm going to close this issue now that we have a repository for folks to collaborate on the OpenStack provider. Thanks!
