### ISSUE TITLE
composite status empty when using fromFieldPath: Required

### ISSUE THREAD

**Issue by RafalMaleska** [crossplane/crossplane#2693]
### What happened?

When creating 2 depended resources with one composition. Resource A provides a value for a patch into the status field (ex. status.resourceARN) of a composite and Resource B reads that value from the status field. 

If setting for Resource B for that field: 
```
          policy:
            fromFieldPath: Required
```

The status of the composite is empty and cannot be patched from Resource A. The composite never fails or becomes ready. 

### How can we reproduce it?

1. Deploy two resources with one composition that pass over a value over the status field of the composite. 
2. Make the value required for the receiving resource with: 

```
          policy:
            fromFieldPath: Required
```

### What environment did it happen in?
Crossplane version: v1.5.0
Cloud provider or hardware configuration: AWS / EKS
Kubernetes version (use `kubectl version`) 1.21
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift), EKS

**Comment by negz** [comment]
@RafalMaleska Thanks for raising this. I'm pretty sure this has worked in the past, so I wonder if this is a regression. Could you please supply a full example of an XR and Composition that triggers this bug?

**Comment by haarchri** [comment]
we see this also since we using crossplane 1.5.1

**Comment by haarchri** [comment]
at work we had "same" issue that  status of the composite is empty so i created a few test cases - both of them are working - it came out that we had an issue in our composition with required and optional fields...

outcome:

crossplane v1.4.0 and provider-aws v0.21.2  https://github.com/haarchri/crossplane-issue-2693/blob/main/output-1.4.0.yaml#L47

crossplane v1.5.0 and provider-aws v0.21.2 https://github.com/haarchri/crossplane-issue-2693/blob/main/output-1.5.0.yaml

full repo: https://github.com/haarchri/crossplane-issue-2693

@RafalMaleska  feel free to add your case that show really an issue with status of the composite is empty
