### ISSUE TITLE
ArgoCD constantly trying to reconcile crossplane ClusterRole

### ISSUE THREAD

**Issue by al-awstest** [crossplane/crossplane#2700]
k8s v1.22.3 in minikube
crossplane deployed by ArgoCD using Helm chart 1.5.0 (same result with 1.6.0-rc.0.41)

after deploy ArgoCD constantly trying to reconcile crossplane ClusterRole

parameter rbacManager.skipAggregatedClusterRoles: "true" didn't make any difference

I'm clearly missing smith here, could you please advise?

attaching yamls of live, desired state and diff ArgoCD is complaining about

Thanks
[argocd-crossplane.zip](https://github.com/crossplane/crossplane/files/7517639/argocd-crossplane.zip)

**Comment by mcbenjemaa** [comment]
You can make Argocd ignore aggregated ClusterRoles
by using the following config: 

```yaml
  config:
    resource.compareoptions: |
      ignoreAggregatedRoles: true
```

**Comment by negz** [comment]
@al-awstest did you get a chance to try @mcbenjemaa's suggestion? I wonder if this is something we could handle with documentation.

**Comment by al-awstest** [comment]
Thanks, folks
configuration for ArgoCD suggested by @mcbenjemaa did the trick
