### ISSUE TITLE
Should Crossplane re-create the resources even if the external-name is assigned by the provider

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2704]
### What problem are you facing?

Today, if the resource is created successfully we add its ID to `crossplane.io/external-name` annotation and use that identifier through its whole lifecycle. We treat this value as the sole identifier for the resource and do not handle any change there.

If the name is decided by the user, like name of the RDS Instance, then even if you delete the resource in console, Crossplane will re-create it with the same name. However, if the ID is decided by the provider, like VPC id, we still re-create it and in [some cases](https://github.com/crossplane/provider-aws/blob/611486b/pkg/controller/ec2/vpc/controller.go#L198) assign the new value to external name and in some cases do not touch the external name at all treating it as immutable.

### How could Crossplane help solve your problem?

We can define that we'll re-create in all cases and override the existing ID with the new one. However, this has some complications; for example referencers are resolved only once https://github.com/crossplane/crossplane-runtime/issues/250 and we'd break the strict pairing of `metadata.name` identifier and external-name identifier, which could mean that you can't really trust the referencing mechanism in a sense that the actual underlying resource may actually change if we continuously resolve.

**Comment by jeanduplessis** [comment]
We determined the linked issue not to be directly related and hence will close this issue due to inactivity.
