### ISSUE TITLE
crossplane and Ansible Integration

### ISSUE THREAD

**Issue by gyliu513** [crossplane/crossplane#2705]
### What problem are you facing?

I want to use Crossplane to deploy some services on VMs, and Ansible may able to help this cases. If crossplane can support ansible, then I can use kuberntes native way to call ansible and run services in VMs.

With above, I can have kind of Hybrid GitOps for both container and VM.

**Comment by negz** [comment]
I think you were just beaten to the punch by https://github.com/crossplane/crossplane/issues/2703, so I'm going to close this as a duplicate. :)
