### ISSUE TITLE
Patching Information from Composition into XR/Claim

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#2711]
### What problem are you facing?

I understand how I can get fields from an MR => XR/Claim: `ToCompositeFieldPath` and from XR/Claim => to MR: `FromCompositeFieldPath`. But how can I get information from my Composition into the XR/Claim?

I have Compositions which are providing a specific property which I would like to propagate into my Claim for consumers of that Claim to see. The current example is a [CO2e value](https://github.com/luebken/cloud-carbon-crossplane/blob/master/crds/compositions.yaml#L9) which I'd like to enrich each S3 bucket with, so users can understand the Carbon impact of their S3 Bucket.

#### Workaround?

As I have full control over the composition and the embedded MR there might be a simple solution where I can add the property somewhere else. e.g. some label. So far I wasn't able to get it working. I would appreciate suggestions / pointers.

#### Fix
From what I can tell, there could be a more use-cases to use information from a Composite in the claim for consumers to use. So maybe something along the lines of a `ToCompositeFieldPathFromComposition` could be interesting to investigate.

**Comment by MisterMX** [comment]
Could you patch the value into an MR and then from there into the claim?

**Comment by luebken** [comment]
I was sure I tried it before. Well now it works. @MisterMX thanks for the pointer.

I'm adding the value directly as a [label to the MR](https://github.com/luebken/cloud-carbon-crossplane/blob/master/crds/compositions.yaml#L22) and than [patching](https://github.com/luebken/cloud-carbon-crossplane/blob/master/crds/compositions.yaml#L31) it into the XR/Claim.

I'm closing this as I don't have immediate need for this. I do think there could be some use-cases out there but that should mandate a new issue.

**Comment by negz** [comment]
> I do think there could be some use-cases out there but that should mandate a new issue.

I'd kind of like to keep this open to noodle on the specific use case of propagating labels from a Composition to an XR/Claim. We're not too worried about issues staying open while we stew on them on c/c. :)

**Comment by jbw976** [comment]
And just for my own edification @luebken - what you got working patches this data to the XR only - there still isn't currently a way to patch arbitrary fields/values from XR => Claim, right? 🤔

**Comment by luebken** [comment]
@jbw976 Not sure if I got your question. My current solution is to add the information to the embedded [MR in the Composition](https://github.com/luebken/cloud-carbon-crossplane/blob/master/crds/compositions.yaml#L53 ) as I have full control over the composition. And then afterwards patch these into the XR which then makes these also available in the claim.
