### ISSUE TITLE
Provide a bring-your-own ServiceAccount option in the crossplane helm chart

### ISSUE THREAD

**Issue by jeremyspykerman** [crossplane/crossplane#2755]
### What problem are you facing?

The latest version of the helm chart (1.5.1) unconditionally creates a ServiceAccount. I would like to manage the ServiceAccount outside the helm chart, so it would be nice to be able to disable the ServiceAccount creation in the helm chart.

### How could Crossplane help solve your problem?

I intend to create a PR that does what I'm asking for, so I suppose the way Crossplane could help solve my problem is by having a look at my PR when it is ready and helping me to get it into the helm chart officially.

**Comment by twobiers** [comment]
Imo this is still relevant and useful
