### ISSUE TITLE
Make `spec.controller.image` in `Provider.meta.pkg.crossplane.io` optional and default to self

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2757]
### What problem are you facing?

Currently when building a `Provider` package, users must [specify a `spec.controller.image`](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Provider/v1@v1.5.1#spec-controller-image), which dictates the image that Crossplane will use when creating the `Deployment` to run its controller. We typically publish two separate images for a `Provider`: the package image and the controller image. However, it is not required that the images be separate, and we could opt to use "fat" images that have both the package contents and controller binary in the same image. In that case, the `spec.controller.image` must reference itself, but if the image is pushed to multiple registries, the underlying contents have to be modified to update the controller image reference (or a `ControllerConfig` has to be referenced to override the underlying controller image at runtime).

### How could Crossplane help solve your problem?

The package manager could opt to make the controller image optional, and in the case it is not provided, use the package image itself as the controller image. This would not break any existing packages, and would still allow for specifying a separate controller image and / or overriding it with `ControllerConfig`.

**Comment by muvaf** [comment]
I think that's a good idea. Though I think the case where you build a separate controller image but forgot about putting its image path to the meta file is a case that we should handle gracefully so that it doesn't take hours to debug why the controller isn't starting.

**Comment by hasheddan** [comment]
@muvaf fair point, although I think that is mostly a general problem that we need to address regardless of this issue (e.g. a typo in image reference could cause the same confusion). Ultimately I hope to move towards using separate images less often.

**Comment by muvaf** [comment]
> Ultimately I hope to move towards using separate images less often.

I remember we used to do this in stack manager. Is there an observation we made to revert to that behavior?

**Comment by hasheddan** [comment]
@muvaf we have theoretically still been able to do that because a Provider could just reference itself, but this makes it less cumbersome :) Next change coming is only caching the package contents so that our cache stays small (you can see how much I had to bump size in PR linked).

**Comment by muvaf** [comment]
> we have theoretically still been able to do that because a Provider could just reference itself, but this makes it less cumbersome :)

Yes, but I wondered about why you'd like us to move towards that direction now.

> you can see how much I had to bump size in PR linked

I couldn't find it actually.

**Comment by hasheddan** [comment]
> Yes, but I wondered about why you'd like us to move towards that direction now.

Mostly because I am seeing more and more providers spring up and I think a single image could be conceptually easier to reason about.

> I couldn't find it actually.

In the testing section I bumped cache size to 50Mi using `--set`.

**Comment by hasheddan** [comment]
> Should we change this value to something much bigger than 5Mi?

@muvaf I don't think we should for the following reasons:
1. There are no known "fat" packages in use today, and making the default size larger for a case that likely will not be employed in the short term is needless overhead.
2. As mentioned above, I intend for the cache to soon selectively store just the package layer, which would mean that the default cache size today would continue to be suitable.

I think it is important to point out again that today someone could still install a package that is larger than the cache and encounter an issue with it being too small, which is the reason for a configurable value (and option to use PVC). When picking a default value for anything I try to bias towards "what makes sense in the common case". The changes made in this specific issue (and linked PR) are not changing the common case, so changing the default does not make sense IMO.

**Comment by muvaf** [comment]
> I intend for the cache to soon selectively store just the package layer

Is this a big undertaking? Does it require package authors to make sure the file is in a given layer or could our package manager select `package.yaml`, regardless of its layer, and cache only that?

> When picking a default value for anything I try to bias towards "what makes sense in the common case". The changes made in this specific issue (and linked PR) are not changing the common case, so changing the default does not make sense IMO.

I think we're on the same page about choosing what makes sense in the common case and the common case today is to have only CRDs in the package image. Now, we're introducing a new mainstream feature where you can include the binary as well. IMO, this adds a new leaf in the mainstream support tree with its own common case where a binary is included in the package, which is most likely larger than `5Mi`. So, we're adding a new feature that won't work by default. Also users cannot really know whether the packages they will install are fat or not unless it's explicitly documented by the package author.

While we don't have to provide full functionality right away by default, like increasing the cache to big numbers like 500Mi to make caching work, I believe it should be working with minimal functionality at the very least, like possibly disabling the cache if it's a fat image or including a workaround to selectively cache files from the package content.

**Comment by hasheddan** [comment]
> Is this a big undertaking? Does it require package authors to make sure the file is in a given layer or could our package manager select package.yaml, regardless of its layer, and cache only that?

It is not a huge undertaking, but the question itself implies the complexity: we could opt to say that the `package.yaml` must be present at the filesystem root but it may exist in any layer, or we could say that the `package.yaml` must be in the root of the lowest layer, but does not necessarily have to be present in the flattened filesystem (i.e. could be removed in a subsequent layer). I tend to lean towards the latter, though it is arguably more complex, because it allows for Crossplane and external systems to selectively download a specific layer pointed to in the image manifest (namely the lowest layer), and could make it easier for tooling to "inject" package contents as the lowest layers in an existing controller image (e.g. building a controller image could be accomplished with something like Docker, and a tool like `up` could inject the package contents to create the final image, without altering how the controller image behaves). However, this strategy would impose the restriction of package contents living at the lowest layer of the image (which I view as a good thing), but would be a change from the requirements presented by Crossplane today (note that in practice I am not aware of any package images that currently exist that do not put the package contents at the lowest layer despite it not being required).

> So, we're adding a new feature that won't work by default.

I don't believe this is accurate. As mentioned before, a package image can already include the binary (and any other content it wants as long as the `package.yaml` is present at the root; i.e. this is not a new feature). If you are installing large packages today (or just many packages for that matter), you may have to increase the cache size. The change suggested in this issue does not impact this fact. Saying that we should react differently to a "fat" package vs a "regular" package doesn't really make sense because these are only conceptual -- an image is a package or not regardless of the additional content it contains.
