### ISSUE TITLE
AWS Cloud Control API

### ISSUE THREAD

**Issue by kennedy** [crossplane/crossplane#2763]
Introduced on September 30, 2021, AWS released Cloud Control API that unifies the creation, query and modification of aws resources in a consistent and strict out put format. 

https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/

> Cloud Control API is a standard set of APIs to Create, Read, Update, Delete, and List (CRUDL) resources across hundreds of AWS Services (more being added) and dozens of third-party services (and growing).
> 
> It exposes five common verbs (`CreateResource`, `GetResource`, `UpdateResource`, `DeleteResource`, `ListResource`) to manage the lifecycle of services. 

Example in the announcement:

`get-resource`

```zsh
aws cloudcontrol get-resource        \
    --type-name AWS::Kinesis::Stream \
    --identifier NewsBlogDemo
{
   "TypeName": "AWS::Kinesis::Stream",
   "ResourceDescription": {
      "Identifier": "NewsBlogDemo",
      "Properties": "{\"Arn\":\"arn:aws:kinesis:us-west-2:486652066693:stream/NewsBlogDemo\",\"RetentionPeriodHours\":168,\"Name\":\"NewsBlogDemo\",\"ShardCount\":3}"
   }
}
```

`create-resource`

```zsh
aws cloudcontrol create-resource    \
   --type-name AWS::Kinesis::Stream \
   --desired-state "{"Name": "NewsBlogDemo","RetentionPeriodHours":168, "ShardCount":3}"
```

Here is terraform and pulumi's providers

https://www.hashicorp.com/blog/announcing-terraform-aws-cloud-control-provider-tech-preview

https://www.pulumi.com/blog/announcing-aws-native/

**Comment by negz** [comment]
Hi @kennedy, are you asking for us to build a provider that uses Cloud Control, as opposed to our existing provider-aws (ACK based) and provider-jet-aws (Terraform based) implementations? If so, Cloud Control is certainly on our radar.

**Comment by kennedy** [comment]
> Hi @kennedy, are you asking for us to build a provider that uses Cloud Control, as opposed to our existing provider-aws (ACK based) and provider-jet-aws (Terraform based) implementations? If so, Cloud Control is certainly on our radar.

Hello @negz, I wasnt able to find any documentation or discussion about Cloud Control. This ticket was more for starting a discussion about Cloud Control with crossplane.

Im glad its on the roadmap, how can I follow crossplane's plans for that?
