### ISSUE TITLE
Move Terrajet to crossplane org

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2769]
### What problem are you facing?

Terrajet is being used by multiple providers now and getting more mature everyday. Moving it to `crossplane` org would make community more comfortable relying on it.

### How could Crossplane help solve your problem?

Move `crossplane-contrib/terrajet` to be `crossplane/terrajet`. We already talked about this with @negz but wanted to formalize it with an issue.

cc @bassam @jbw976 @negz

**Comment by negz** [comment]
@muvaf I'm happy to move this. Could you add an `OWNERS.md` file (see the one in this repo for example) before I do.

https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#repository-governance

**Comment by muvaf** [comment]
@negz here is the PR https://github.com/crossplane-contrib/terrajet/pull/180

**Comment by negz** [comment]
Thanks! This is now moved - https://github.com/crossplane/terrajet.
