### ISSUE TITLE
 Vulnerability in dependency `github.com/opencontainers/image-spec`

### ISSUE THREAD

**Issue by PawelKopel** [crossplane/crossplane#2780]
### What problem are you facing?

Crossplane has an indirect dependency on `github.com/opencontainers/image-spec` v1.0.1 which was found to have a vulnerability https://github.com/advisories/GHSA-77vh-xpmg-72qh.
### How could Crossplane help solve your problem?

Update libraries depending on `github.com/opencontainers/image-spec` to versions using v1.0.2 of it.

**Comment by smileisak** [comment]
This Issue should be resolved by updating the go-contrainerregistry package as described in this MR #3098 
The `github.com/opencontainers/image-spec` is updated to version `1.0.3`.

**Comment by negz** [comment]
/fresh

Just using this issue to test the bot - pretty sure this is actually fixed already per @smileisak

**Comment by negz** [comment]
I'm seeing us at 1.0.3, so I believe this is no longer an issue.

https://github.com/crossplane/crossplane/blob/d58f9187d1485a72ceaadb1d2f13d99024f09e57/go.mod#L123
