### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#280]
MongoDB is a popular document database, with varying support across the major cloud providers.  

* AWS recently added [DocumentDB](https://aws.amazon.com/documentdb/) with MongoDB compatibility
* Azure [Cosmos](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction) has MonogoDB compatibility
* [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/faq) looks like an independent cloud offering database as a service by the authors of MongoDB

We should continue looking into adding support for MongoDB in Crossplane in as many environments as we can.

**Comment by artursouza** [comment]
Please, assign this issue to me.

**Comment by artursouza** [comment]
Atlas seems to be an external offering, is there a way to support an external offering via a provider in Crossplane? My goal is to support the AWS and Azure providers via DynamoDB and CosmosDB respectively. Any idea how to support MongoDB in GCP via crossplane? I see that GCP offers it via Atlas but it seems just the billing in GCP while the managed service is outside (Atlas). Does anyone have experience with MongoDB in GCP?

**Comment by hasheddan** [comment]
@artursouza just a heads up, I believe @sahil-lakhwani is in progress on AWS DynamoDB so it may be good to just focus on Azure Cosmos to start. I am thinking (at least for now) that we likely will not support marketplace installations like MongoDB Atlas on GCP. Instead, I think [Mongo](https://github.com/mongodb/go-client-mongodb-atlas) could be its own self-contained `provider` to support Atlas. GCP also has its own NoSQL database, [datastore](https://godoc.org/cloud.google.com/go/datastore). A better title for this issue would likely be "NoSQL support", but I think it was specifically mentioning Cosmos and DynamoDB because they are MongoDB wire-compatible.

**Comment by artursouza** [comment]
We can support nosql databases and let the API (mongodb or not) to be an attribute. In Azure you choose which API to use.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prasek** [comment]
Support for CosmosDB Account (can be used for MongoDB or Cassandra) was added in https://github.com/crossplane/provider-azure/pull/138.

**Comment by prasek** [comment]
@negz @jbw976 Similar to #281, should we close this out in favor of provider-specific issues? We already have Azure Cosmos / MongoDB support from https://github.com/crossplane/provider-azure/pull/138.

**Comment by brianmjones** [comment]
would love to see mongodb atlas supported as a provider in crossplane.

**Comment by jesumyip** [comment]
I would similarly love to see support for mongodb atlas. I currently have a production API infrastructure that uses Tyk, which needs MongDB to work. I have gone ahead and provisioned an Atlas instance. My goal is to have my entire API infrastructure (Auth0, Tyk, Mongodb, redis, GAE) deployable within minutes using Crossplane.

**Comment by trash-anger** [comment]
What about using crossplane's terraform provider, then terraform's mongo atlas provider to do it?

**Comment by luebken** [comment]
There is now a MongoDB Atlas provider https://github.com/crossplane-contrib/provider-jet-mongodbatlas

**Comment by muvaf** [comment]
As @luebken pointed out, there is now a provider. Feel free to open issues on that repo.
