### ISSUE TITLE
Message queue support

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#281]
We should support portable and dynamic provisioning of message queues across various cloud environments.  It's not entirely clear yet what the standard open protocol(s) that are most widely supported (JMS (ActiveMQ), AMQP, STOMP, etc.), so some more research will be needed.

Amazon: https://aws.amazon.com/amazon-mq/
Azure: https://azure.microsoft.com/en-us/services/service-bus/
Google: https://cloud.google.com/pubsub/

**Comment by hasheddan** [comment]
Out of the queuing services mentioned above, the following protocols are supported:

- Amazon MQ: JMS, NMS, AMQP, STOMP, MQTT, and WebSocket
- Azure Service Bus: AMQP, HTTP/REST
- Google Cloud PubSub: HTTP

**Comment by tommyknows** [comment]
+1 here too, as for serverless. Would love to help where I can.

**Comment by negz** [comment]
We're starting to work on this in each provider, for example in https://github.com/crossplane/provider-aws/issues/170. I agree we want this functionality, but I'd prefer to stick with more targeted "add message queue service foo" in each provider than have one issue tracking all of them.
