### ISSUE TITLE
CompositionRevision does not work when Composition has a Map transform

### ISSUE THREAD

**Issue by ArunRamakani** [crossplane/crossplane#2836]
Crossplane Version 1.6.1

Issue: CompositionRevision does not work when Composition has a Map transform

Logs Info: Map transform expects a string but it should be an object

```
2022-01-08T06:41:33.479Z	ERROR	crossplane.controller-runtime.manager.controller.revisions/composition.apiextensions.crossplane.io	Reconciler error	{"reconciler group": "apiextensions.crossplane.io", "reconciler kind": "Composition", "name": "mysql", "namespace": "", "error": "cannot create CompositionRevision: CompositionRevision.apiextensions.crossplane.io \"mysql-gp5c7\" is invalid: spec.resources.patches.transforms.map.Pairs: Invalid value: \"object\": spec.resources.patches.transforms.map.Pairs in body must be of type string: \"object\""}
```

**Comment by ArunRamakani** [comment]
Below is the Composition 

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mysql
  labels:
    crossplane.io/xrd: xgcpdbs.alpha-beta.imarunrk.com
spec:
  compositeTypeRef:
    apiVersion: alpha-beta.imarunrk.com/v1
    kind: XGCPdb
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: cloudsqlinstance
    base:
      apiVersion: database.gcp.crossplane.io/v1beta1
      kind: CloudSQLInstance
      spec:
        providerConfigRef:
          name: gcp-credentials-project-1
        forProvider:
          databaseVersion: MYSQL_5_7
          region: us-central1
          settings:
            tier: db-g1-small
            dataDiskSizeGb: 20
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.size
      toFieldPath: spec.forProvider.settings.tier
      transforms:
      - type: map
        map:
          BIG: db-n1-standard-1
          SMALL: db-g1-small
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.size
      toFieldPath: spec.forProvider.settings.dataDiskSizeGb
      transforms:
      - type: map
        map:
          BIG: "40"
          SMALL: "20"
      - type: convert
        convert:
          toType: int
      policy:
        fromFieldPath: Required
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.gceZone
      toFieldPath: status.zone
    connectionDetails:
    - name: hostname
      fromConnectionSecretKey: hostname

**Comment by ArunRamakani** [comment]
The XRD

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpdbs.alpha-beta.imarunrk.com
spec:
  group: alpha-beta.imarunrk.com
  names:
    kind: XGCPdb
    plural: xgcpdbs
  claimNames:
    kind: GCPdb
    plural: gcpdbs
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  size:
                    type: string
                required:
                - size
            required:
            - parameters
          status:
            type: object
            properties:
              zone:
                description: DB zone.
                type: string

**Comment by cahan1013** [comment]
i met the same problem here: 
Warning  CreateRevision  38s (x7 over 6m38s)  revisions/composition.apiextensions.crossplane.io  (combined from similar events): CompositionRevision.apiextensions.crossplane.io "amazon-eks-cluster-g4k86" is invalid: spec.resources.patches.transforms.map.Pairs: Invalid value: "object": spec.resources.patches.transforms.map.Pairs in body must be of type string: "object"

And the composition is sth like this: 
`patches:
       - fromFieldPath: "spec.parameters.workload-type"
          toFieldPath: "spec.forProvider.amiType"
          transforms:
          - type: map
            map:
              gpu: AL2_x86_64_GPU
              non-gpu: AL2_x86_64`

**Comment by MisterMX** [comment]
We experience the same issue.

I think the reason is that `CompositionsRevision`'s `MapTransform` is missing the `UnmarshalJSON` method: https://github.com/crossplane/crossplane/blob/41bcc71c7703e33e5bd51dd1852fd620269313f2/apis/apiextensions/v1/composition_transforms.go#L154

That's just a guess, though. I wasn't able to test it.
