### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#285]
In order to support real-world applications that are heterogeneous, Crossplane should support the portable deployment of serverless (functions) components.  There will need to be some up front design work to figure out what this support looks like, the experience, and what it should cover.

**Comment by tommyknows** [comment]
Would be great to have serverless support in Crossplane.
I probably would have some time to contribute to this too (no guarantees yet) 🙂

**Comment by muvaf** [comment]
@tommyknows Thanks for the feedback! I am not sure about the timeline, maybe @prasek can comment.

But if you'd like to work on this, I think [developer guide](https://crossplane.io/docs/v0.5/services-developer-guide.html) is the best place to start. Then you can look at other implementations in the codebase and drive your implementation. Even if you get to have some ideas but not much knowledge for implementation, you can ask help here or on our Slack!

Example implementations of managed resource controllers:
GCP CloudSQL: https://github.com/crossplaneio/stack-gcp/blob/master/pkg/controller/database/cloudsql.go
AWS RDS: https://github.com/crossplaneio/stack-aws/blob/master/pkg/controller/database/rdsinstance.go
Azure Redis: https://github.com/crossplaneio/stack-azure/blob/master/pkg/controller/cache/redis.go

**Comment by prasek** [comment]
@jbw976 @negz we've started to breakout serverless support in provider-specific repos, e.g.
AWS Lambda support broken out in:
 - https://github.com/crossplane/provider-aws/issues/149
    - https://github.com/crossplane/provider-aws/issues/173

Should we close this issue in favor of provider-specific issues?

**Comment by negz** [comment]
This is kind of broad, but we actually do have some serverless support with https://github.com/crossplane/provider-aws/pull/559. I'm going to close this issue in favor or more scoped ones.
