### ISSUE TITLE
Import Existing vpc forProvider.vpc-cidrBlock object

### ISSUE THREAD

**Issue by cdenneen** [crossplane/crossplane#2861]
Currently the vpc forProvider.vpc-cidrBlock object requires `string` but I have a vpc I'm trying to import that has 3 cidrBlocks associated with it.

The `From Provider` show the proper 3 cidrs, dhcp-options, owner, etc so it's importing properly it seems however since the `forProvider.vpc-cidrBlock` doesn't seem to match I'm getting error:

```
    Message:               observe failed: failed to describe VPC with id: UnauthorizedOperation: You are not authorized to perform this operation.
    Reason:                ReconcileError
```

Is there a way to set the `forProvider.vpc-cidrBlock` object to a list of cidrBlocks (comma delimited)? "CIDR1,CIDR2,CIDR3"?

**Comment by haarchri** [comment]
An VPC has only a vpc-cidrBlock for IPv4 and/or an vpc-cidrBlock for IPv6 all additional cidrBlocks er have a additional resource https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/VPCCIDRBlock/v1beta1@v0.23.0 

you need to Import your VPC with the main vpc-cidrBlock
