### ISSUE TITLE
Do not proceed with package upgrade if there are breaking changes that can affect existing CR instances

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2864]
### What problem are you facing?

There are cases where users upgrade to a new version of the provider but that version of the provider has breaking changes that affect existing instances that are not handled with multiple versions (with or without webhooks); either because by mistake or the resources were alpha level meaning there is [no guarantee](https://kubernetes.io/docs/reference/using-api/#api-versioning) about breaking anyway.

In those cases, package manager wouldn't be able to update CRDs with an error similar to the following:
```
CustomResourceDefinition.apiextensions.k8s.io "cassandratables.cosmosdb.azure.jet.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions                                           ││   Warning  SyncPackage        3s                     packages/providerrevision.pkg.crossplane.io  cannot establish control │
CustomResourceDefinition.apiextensions.k8s.io "resourcegroups.azure.jet.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions                                                     ││                                                                                                                            │
```

The reason is that the provider bumped the version to `v1alpha2` but didn't have `v1alpha1` in the `spec.versions` array anymore, which is a breaking change that's OK only if there are no instances.

### How could Crossplane help solve your problem?

Package manager could have a feature that inspects the package content and proceed with upgrading only if the breaking changes are handled, something like dry-run before affecting any resource in the cluster.

**Comment by hasheddan** [comment]
Noting here from offline conversation that the following:

> Package manager could have a feature that inspects the package content and proceed with upgrading only if the breaking changes are handled, something like dry-run before affecting any resource in the cluster.

Is how the package manager behaves today 👍🏻 We first run to [dry run update](https://github.com/crossplane/crossplane/blob/e29ac40e71f7ed2b3e74f204596cbdd71e8aecb3/internal/controller/pkg/revision/establisher.go#L123) all resources before proceeding with install, which is what is causing the error to surface here. @muvaf made a good point that it could be useful to inform the user here that reverting to the old package revision will get them back to a healthy state.

**Comment by muvaf** [comment]
@hasheddan thanks for the clarification! I think even prefixing the error with something like `dry run has failed:` would go a long way here.
