### ISSUE TITLE
Should packages handle skipping versions during an upgrade?

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2865]
### What problem are you facing?

Today, if you upgrade a provider from `v0.5.0` to `v0.9.0`, the package manager will dry-run CRD updates and proceed with the upgrade. However, if there are breaking changes, developers might have opted to support from migration to one version to another only, i.e. there is a utility in `v0.8.0` for migration but it assumes the earlier version is `v0.7.0`. You can document this in release notes of `v0.8.0` but there isn't really an API-level way of enforcing this today. So, it's easy for users who skip the versions to get into a failed state (maybe even broken state for problems that pass CRD dry-run).

### How could Crossplane help solve your problem?

There are a couple things we can do to make that contract more explicit:
* Develop a convention where we tell developers to implement migrations from the last N number of minor versions to the current one.
  * This would mean that developers would implement for N number of possibilities for each change they make, which may not even be technically possible in certain cases.
* Require users to perform upgrades in sequential order. 
* Have a package metadata that can be written by developers for such cases and reject upgrading if the old and new version doesn't comply with that contract.
  * Like having a field saying `in order to go beyond v.0.8.0, you have to upgrade to v0.7.0 first, then v0.8.0 and only then continue`.
  * Package manager could potentially run the whole upgrade with those steps instead of rejection and waiting manual action.
  * If no such metadata is given, proceed as today.

I think the third option is the best one that doesn't increase burden on developers while improving the experience for users. But until we implement this feature, it's safer to run with a default assumption that developers can assume upgrades are done in sequential order.

**Comment by fsniper** [comment]
As @muvaf points out, Second level from 3rd option is a better UX from the perspective of a Crossplane user. 
At the cost of more work on provider developers for upgrades (which is a good thing(c) )

**Comment by negz** [comment]
What are some examples of the breaking changes we're discussing here? Are these all around alpha APIs, or are they affecting v1beta1 and above APIs?

**Comment by muvaf** [comment]
@negz This is a recent [example](https://github.com/crossplane/crossplane/issues/2864#issue-1116296771) where `v1alpha1` was completely dropped from the CRD, hence breaking the upgrade.
