### ISSUE TITLE
Scheduler optimization of resource attributes

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#287]
The workload scheduler should be able to optimize its scheduling/placement decisions for many different attributes, such as cost, proximity, compliance, features, etc.  Resources should be able to specify their scheduling requirements and administrators should be able to define policy for how optimization decisions should be made.

We'll need to think through how best to support this and what attributes to prioritize first.

**Comment by negz** [comment]
We're deprecating KubernetesApplication (neé Workload), so I don't think this will be relevant going forward.
