### ISSUE TITLE
Make the crossplane CLI available through homebrew and/or krew

### ISSUE THREAD

**Issue by remyleone** [crossplane/crossplane#2873]
### What problem are you facing?

I would like to have crossplane installed and updated through a package manager.

### How could Crossplane help solve your problem?

Making the binary of crossplane available on homebrew. Making it available through krew could also be useful. https://github.com/kubernetes-sigs/krew/

**Comment by xshyamx** [comment]
This enhancement will require that the crank release be made available as a tgz/zip file (Refer [Krew: Plugin Package Format](https://github.com/kubernetes-sigs/krew/blob/master/docs/KREW_ARCHITECTURE.md#plugin-package-format)) instead of the naked binaries hosted from release.crossplane.io

**Comment by justenstall** [comment]
I see this issue was closed due to inactivity, is there any chance this gets picked up?

**Comment by tdensmore** [comment]
> This enhancement will require that the crank release be made available as a tgz/zip file (Refer [Krew: Plugin Package Format](https://github.com/kubernetes-sigs/krew/blob/master/docs/KREW_ARCHITECTURE.md#plugin-package-format)) instead of the naked binaries hosted from release.crossplane.io

Is this true even when using goreleaser to build the brew formulae?
