### ISSUE TITLE
Deleting an XRD definition deleted any related Managed Resources

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#2878]
### What problem are you facing?

Crossplane version: UXP 1.6.1

When a CustomResourceDefinition is deleted from the API server, every managed resource that was provisioned with that XRD is also deleted. This behavior might not be expected by a platform owner and could cause data loss or an outage.

### How could Crossplane help solve your problem?

Investigate other behaviors, possibly putting a finalizer on an XRD if any related Managed Resources exist on the cluster.

**Comment by negz** [comment]
@stevendborrelli do you think this is a duplicate of this older issue - https://github.com/crossplane/crossplane/issues/1082? They're not 100% the same thing, but seem pretty close to me.

**Comment by stevendborrelli** [comment]
@negz Yes, it sounds very similar.

One thing we need to think about in a Crossplane vs. K8s solution is that XRD and Composition CRDs could change as part of normal workflows. How do we help end-users to be able to update/fix their CRDs safely without risking the cloud infrastructure that has been provisioned?

**Comment by twobiers** [comment]
> @negz Yes, it sounds very similar.
> 
> One thing we need to think about in a Crossplane vs. K8s solution is that XRD and Composition CRDs could change as part of normal workflows. How do we help end-users to be able to update/fix their CRDs safely without risking the cloud infrastructure that has been provisioned?  

Is there any solution found? I'm wondering about how to evolve the XRD without causing disruptions and couldn't find any recommended process yet.
