### ISSUE TITLE
Scheduler should be extensible

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#288]
The workload scheduler should have extensibility points so that the default scheduler can be overridden by a third party or out of tree scheduler.  This should probably follow a similar design pattern to the [Kubernetes scheduler](https://kubernetes.io/docs/concepts/extend-kubernetes/extend-cluster/#scheduler-extensions), where the default scheduler can be replaced entirely or multiple schedulers can be configured to run at the same time.

**Comment by negz** [comment]
We're deprecating KubernetesApplication (neé Workload), so I don't think this will be relevant going forward.
