### ISSUE TITLE
Inconsistent CLI args - `--poll` vs `--poll-interval`

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#2885]
### What problem are you facing?
Inconsistent naming, `--poll` in providers and `--poll-interval` in core crossplane:

##### provider-aws -  `--poll`
https://github.com/crossplane/provider-aws/blob/cb08893011212fc6858434f84695fecc0a824629/cmd/provider/main.go#L40

##### crossplane core - `--poll-interval` 
https://github.com/crossplane/crossplane/blob/c0de80c1ea2102b9569754d78bea292c46e62927/cmd/crossplane/core/core.go#L69

### How could Crossplane help solve your problem?
Make the same parameter work both places, and document args.

**Comment by negz** [comment]
This is something we've been very slowly cleaning up as part of https://github.com/crossplane/crossplane/issues/2595. We should align on `--poll-interval`. Updating https://github.com/crossplane/provider-template would be a good first step to make sure future providers are aligned.

**Comment by negz** [comment]
I believe provider-template was updated. I'm going to dedupe this issue into #2595. Thanks @chlunde!
