### ISSUE TITLE
External resource change notifications

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#289]
When external resources are mutated/changed, Crossplane should be notified about this change so the reconciliation can be performed.  For example, if a cloud provider resource is updated by the user outside of Crossplane, for example in the provider's console or CLI, then Crossplane should get a notification or event to trigger reconciliation.

**Comment by jbw976** [comment]
Related to #9

**Comment by negz** [comment]
Do we still feel like this is a concern/priority? At the moment we'll notice in 30-60 seconds due to polling the API. I'm not sure what else we could do to improve this.

**Comment by negz** [comment]
I'm going to close this - I'm not really aware of anything we can do here apart from polling the providers. Please reopen if anyone has any ideas!

**Comment by negz** [comment]
https://github.com/kubernetes-sigs/controller-runtime/blob/ab55aa710b06f01816f77aaf0e258ecb4367f0a5/pkg/source/source.go#L156

I noticed recently that controller-runtime does have some facility for 'watching' sources outside the cluster.
