### ISSUE TITLE
Documentation page for CRD migrations

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2898]
### What problem are you facing?

We have breaking and non-breaking changes that change the API version of CRDs. So far, a migration guide is created for each release, like this [one](https://github.com/crossplane/provider-aws/blob/master/cluster/UPGRADE.md), but the steps are very similar between providers.

### How could Crossplane help solve your problem?

We can have a documentation page that we can point to from release notes as the migration guide that covers a set of known cases.

**Comment by plumbis** [comment]
This would be specific to how to upgrade providers, not Crossplane pod upgrades, correct?

**Comment by jeanduplessis** [comment]
I agree this feels like its related to details of the provider, not core crossplane.
