### ISSUE TITLE
Enable ARM testing on Github actions

### ISSUE THREAD

**Issue by odidev** [crossplane/crossplane#2912]
Currently, there are only AMD64 test jobs available in github actions. I have successfully tested all features and ran unit and e2e tests of crossplane on the ARM64 platform. It will be useful if we add test jobs for ARM64 as well in github actions, as it is better to test before releasing ARM64 binaries and images.

We can do ARM64 testing in Github actions using self-hosted arm64 runners. 

If interested, We can get access to ARM H/W through [WorksOnArm](https://github.com/WorksOnArm).

**Comment by odidev** [comment]
I am happy to help if required in adding ARM64 jobs in Github actions.

**Comment by odidev** [comment]
@muvaf Please let me know if any help required from my end.

**Comment by aktech** [comment]
I suggested a solution here if folks are interested 😅 
https://github.com/aquasecurity/trivy/issues/2660#issuecomment-1217145390
