### ISSUE TITLE
Document and add automated testing for pulling packages from private registries

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2913]
### What problem are you facing?

Crossplane supports pulling packages from private registries through a variety of mechanisms, including [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/), [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), and [`packagePullSecrets`](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Provider/v1@v1.6.3#spec-packagePullSecrets). There are a wide variety of environments in which a user is pulling a private package, which can lead to confusion about which to use, the precedence with which each is invoked, etc. This can lead to issues such as https://github.com/crossplane/crossplane/issues/2876, where I suspect that we are resolving to [Application Default Credentials](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go), when we actually want to be using the provided `packagePullSecret`.

### How could Crossplane help solve your problem?

We should document the variety of ways to pull packages from popular private registries, and also have testing in place to ensure we don't break any of the mechanisms from release to release.

**Comment by jbw976** [comment]
Is this something you are taking on soon @hasheddan? I see you self assigned it already.

This could be a project of interest for LFX Mentorship, if it can wait for a few months until summer quarter.

**Comment by jbw976** [comment]
Cool @hasheddan! I just wanted to make sure it could potentially wait a few months, if we have to wait until LFX Mentorship summer quarter.

But yes, I think this project would be a stimulating challenge for a mentee, it has obvious value for the project and community, and it's clearly belonging to upstream.  Great fit all around!

I've added a "good mentorship issue" to the repo and this issue, so we can not lose sight of it when upcoming mentorship program deadlines are coming up :)

I wonder if we could still sneak this into LFX Spring quarter, even though we're over the deadline 🤔

**Comment by Alt-Shivam** [comment]
Hey, @jbw976, @hasheddan 
Discovered this project through the LFX mentorship program and found it interesting and totally meets my tech stack.
and I am interested to work on this project. So to get familiar with this issue, could you please share some resources or topics that I should study first. also If you could assign me some tasks to perform, I would really appreciate that.
Thanks.

**Comment by Alt-Shivam** [comment]
Meanwhile,
I'm starting with understanding the code-base and having a look at some issues.

**Comment by jbw976** [comment]
Good questions @Alt-Shivam, thank you for your interest in this issue! 💪 

It's a great idea to research and understand the problem space better, but please do remember to officially apply on the [LFX Mentorship site](https://mentorship.lfx.linuxfoundation.org/project/c6e63427-09d9-42e5-b2af-c9c66e57881a).  We want to give everyone a fair chance to apply and be selected before any work starts 😅 

Here are a couple resources that will be helpful on various topics for Crossplane packages:

* [Crossplane packages concepts and overview](https://crossplane.io/docs/v1.7/concepts/packages.html)
* [xpkg specification](https://crossplane.io/docs/v1.7/reference/xpkg.html)
* [packages v2 design doc](https://github.com/crossplane/crossplane/blob/master/design/design-doc-packages-v2.md)
* [package format v2 design doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-package-format-v2.md)

**Comment by edith007** [comment]
Hi @jbw976 @hasheddan 👋🏻 
 I am really interested in working on this project. And have started exploring cross plane project and trying to fix bugs. 🙇🏻
