### ISSUE TITLE
Could not sync crossplane provider on upgrades.

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/crossplane#2914]
### What happened?

When Upgrading a provider, the underlying deployment could not be synced!

```
Warning  SyncPackage        45s (x24 over 18m)    packages/providerrevision.pkg.crossplane.io  cannot run post establish hook for package: cannot apply provider package deployment: cannot patch object: Deployment.apps "provider-kubernetes-f8ffa0e9c693" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"pkg.crossplane.io/provider":"provider-kubernetes", "pkg.crossplane.io/revision":"provider-kubernetes-f8ffa0e9c693"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
I guess, need to replace it, if encountering changes in immutable fields! 

### What environment did it happen in?
Crossplane version:

**Comment by hasheddan** [comment]
@mcbenjemaa this was due to a change in the label selectors in a previous Crossplane version bump. This can be solved in a non-destructive manner by deleting the `Deployment` for the `Provider` and allowing Crossplane to re-create.

**Comment by mcbenjemaa** [comment]
this is true as a workaround :)
