### ISSUE TITLE
Allow specifying multiple writeConnectionSecretsToNamespace targets for a Composition

### ISSUE THREAD

**Issue by AaronME** [crossplane/crossplane#2929]
### What problem are you facing?
Some Composite Resources define infrastructure that is meant to be shared with other teams. One example would be a message queue, another could be a data lake bucket. There are several MRs which define "data transfer" as opposed to "data ownership" points. 

When deployed as part of a Composite Resource, the connection secret for these MRs can only be written back to a single namespace. This requires some external process to convey this connection secret to the other teams and services which need access to the target. 

### How could Crossplane help solve your problem?
If `writeConnectionSecretsToNamespace` were an array, teams could "grant" permission on shared resources by providing a copy of the connection secret to the namespace of any team/service that needed access.

**Comment by negz** [comment]
Hrm, interesting. Honestly I've always thought of XR (as opposed to XRC) secrets as sort of intermediary storage, and expected a claim to happen if folks actually wanted to consume the connection secret. I think your way of thinking about this makes more sense though.

**Comment by negz** [comment]
CC @turkenh. Perhaps we should consider this as part of the API changes you're making to enable secret stores?

**Comment by turkenh** [comment]
I remember that we have discussed [similar](https://github.com/crossplane/crossplane/pull/2494#discussion_r733313923), [capabilities]((https://github.com/crossplane/crossplane/pull/2494#r696081422)) during the design and ended up choosing not to support publishing to multiple secrets/stores in favor of simplification especially considering this would still be possible with some third party tooling.

However, when we considered this issue together with [this one](https://github.com/crossplane/crossplane/issues/2774), I am seeing another way to support publishing to multiple stores by introducing a `configSelector` as an alternative to the current `configRef` field:

```yaml
  publishConnectionDetailsTo:
    name: demo-serviceaccount-key
    #configRef:
    #  name: vault
    configSelector:
      env: prod
      team: backend
```

Similarly, in composition spec, we can have both `PublishConnectionDetailsWithStoreConfigRef` and `PublishConnectionDetailsWithStoreConfigSelector`.

We can implement support for publishing with multiple store configs if selectors match multiple. Different store configs would have different default namespaces where MR secrets will be published.

The only thing that I don't feel comfortable with is that, `PublishConnectionDetailsWithStoreConfigSelector` may return multiple where `PublishConnectionDetailsWithStoreConfigRef` supports only one, and this is same for  `publishConnectionDetailsTo.configRef` vs `publishConnectionDetailsTo.configSelector`.

This would also be a non-breaking API change and I would prefer not to include this in the first release as it will require some work in the existing implementation. What do you think?

**Comment by negz** [comment]
> We can implement support for publishing with multiple store configs if selectors match multiple. Different store configs would have different default namespaces where MR secrets will be published.

I generally like the idea of using a selector, but typically selectors _set_ references, rather than being used instead of them. So if we wanted a selector to match and set multiple refs we'd need an array of config refs.

**Comment by muvaf** [comment]
I also think of the secret of XR as intermediary storage for filtered secret that will be propagated to the claim's namespace. I think that's one of the main reasons we don't ask for a name, it's just UID of the XR.

When I think about usage pattern, I feel like the namespace of the claim has the right to use that infra, so maybe we can consider having an option to allow multiple claims binding to the same XR so that secret is propagated to those namespaces, too? Or possibly come up with a new primitive, like `Usage`, that will copy the secret?

**Comment by natereid72** [comment]
perhaps `propagateConnectionDetailsTo` as an option, with a list of providerConfigs that can be patched in. There is benefit to having the. secret in the Crossplane cluster and in other clusters. Rather than either/or. I think we can achieve this with Vault and then consuming from Crossplane and other cluster, but is much more complex of a setup.

**Comment by simonklb** [comment]
I would be interested in seeing this as well to enable the use case of consuming credentials in more than one cluster without having to introduce Vault or some other (non-k8s) external secret store.

Any hope of this getting second look?
