### ISSUE TITLE
Documentation for running and testing locally for fast developer iteration

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#293]
Similar to the documentation we already have about [running locally in Minikube](https://github.com/crossplaneio/crossplane/tree/master/cluster/local), we should also have documentation that helps developers run in a local process on their local machine.  This will allow them to iterate faster, run in a debugger, etc.

This should be a similar experience to what kubebuilder enables you by default, described at https://book.kubebuilder.io/quick_start.html#locally-running-an-api

Should this be included in the makefile as `make run` or `make dev`?

As part of adding this "local dev" scenario documentation, we should also improve the discoverability of the local dev docs (including minikube).  It may not be very easy to find them right now so we should make it more obvious.

**Comment by jbw976** [comment]
@ichekrygin has a flow that he's been using locally, maybe he could share those steps here in a raw format and we can turn that into nicely formatted documentation 😁

**Comment by HashedDan** [comment]
Let me know how I can help here!

**Comment by negz** [comment]
I believe I inadvertently addressed this in https://github.com/crossplane/crossplane/pull/1590.
