### ISSUE TITLE
e2e test failed to get pre-cached package with pull policy Never

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#2944]
### What happened?
looks like after we merged https://github.com/crossplane/crossplane/pull/2932 we get e2e-test failed in ci
examples:
 https://github.com/crossplane/provider-aws/pull/1122
 https://github.com/crossplane/provider-aws/pull/1158

locally i can see:
using crossplane version 1.7.0-rc.0.125.gfff10011
```
kubectl get pkgrev
NAME                              HEALTHY  REVISION  IMAGE     STATE  DEP-FOUND  DEP-INSTALLED  AGE
providerrevision.pkg.crossplane.io/provider-aws-provider-aws       1     provider-aws  Active                2m40s
```

```
Events:
 Type   Reason       Age          From                     Message
 ----   ------       ----          ----                     -------
 Normal  BindClusterRole  2m10s (x3 over 2m10s) rbac/providerrevision.pkg.crossplane.io   Bound system ClusterRole to provider ServiceAccount(s)
 Normal  ApplyClusterRoles 2m10s (x2 over 2m10s) rbac/providerrevision.pkg.crossplane.io   Applied RBAC ClusterRoles
 Warning ParsePackage    9s (x8 over 2m10s)   packages/providerrevision.pkg.crossplane.io failed to get pre-cached package with pull policy Never
```

i changed crossplane in e2e tests locally to 1.6.3 without issues - and e2e test passed

### How can we reproduce it?
`make e2e USE_HELM3=true skipcleanup=true`

### What environment did it happen in?
Crossplane version: 1.7.0-rc.0.125.gfff10011

c/c @hasheddan  @muvaf  @negz

**Comment by hasheddan** [comment]
@haarchri thanks for opening! This change in functionality is mentioned in https://github.com/crossplane/crossplane/pull/2932#discussion_r820265162, though I didn’t call out that most provider e2e tests use the pre-caching strategy. As mentioned offline, a quick short term solution is using Crossplane from stable channel, but I also plan to introduce some functionality to make this easy using CLI 👍🏻

**Comment by AnaMariaMoga** [comment]
Hello, 

I am facing this issue with the latest stable version of crossplane, v1.7.0. Is there anything recommended for this?
(sorry if I miss any discussion or document on this topic, any help/direction is appreciated :pray: )

**Comment by AnaMariaMoga** [comment]
Ok, I see, thank you. I will use v1.6.4 for the moment. :+1: I am working on a Crossplane Provider, but it is not released yet.

**Comment by hasheddan** [comment]
Fixes are available for this, with the first patch rolling out in `provider-aws`: https://github.com/crossplane/provider-aws/pull/1239

As a side note, I am working on a draft of a plan to move integration testing scripts out of the provider repos and standardizing them in a location or framework that means maintainers won't have to deal with old bash scripts and can easily submit e2e jobs.
