### ISSUE TITLE
Package manager should ignore unknown types instead of stopping the installation

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2947]
### What problem are you facing?

With https://github.com/crossplane/crossplane/issues/2894 , provider packages will come with `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` types. However, if you have an older version of Crossplane before https://github.com/crossplane/crossplane/pull/2919 then the installation/upgrade will not go through at all. This would mean that the providers with webhooks would impose a minimum Crossplane version requirement.

### How could Crossplane help solve your problem?

The best we can do at this point for specific problem of webhooks is to release patches that will make the linter pass the validation and it'd ignore any non-CRD type during the installation of the objects, which will be the same behavior when you don't enable webhooks by not providing a TLS secret.

I think to make it future-proof, the linter should allow all objects as long as they are valid Kubernetes objects and installation should install only the types it needs so that if a new type is introduced, we don't need a code change and existing users wouldn't be affected.

**Comment by hasheddan** [comment]
> This would mean that the providers with webhooks would impose a minimum Crossplane version requirement.

@muvaf I think this is an entirely reasonable requirement. Webhooks are a new feature so patching them back to old release branches would go against are stated semver patch strategy. If we are concerned about upgrading providers to use webhooks, and that requiring a Crossplane version bump, which some users may not want to make initially, but may still want unreleatd fixes included in later versions of the provider, I think options could include:
1. Institute formal support schedules for provider, especially highly used ones (this is probably overdue anyway).
2. Publish webhook and "non-webhook" versions of provider for a period of time.

> I think to make it future-proof, the linter should allow all objects as long as they are valid Kubernetes objects and installation should install only the types it needs so that if a new type is introduced, we don't need a code change and existing users wouldn't be affected.

I actually think requiring users to upgrade to get new feature support in various packages is a good outcome here. I am very hesitant to allow of _arbitrary_ kubernetes object in packages. This would result in a case where a single package could be installed differently based on the version of Crossplane it is being installed with. I would much rather a package say that it can't be installed than to silently ignore items I expect it to install.

**Comment by muvaf** [comment]
> Webhooks are a new feature so patching them back to old release branches would go against are stated semver patch strategy.
> I actually think requiring users to upgrade to get new feature support in various packages is a good outcome here.

Yes, we're on the same page here. The case I'm concerned is the following:
1. I'm a happy user of Crossplane v1.6 and provider-aws v0.24.1
2. A new version of provider-aws is released v0.25 which includes webhook configuration YAMLs.
3. I don't want to use webhooks (maybe even don't know about them or my provider upgrades are automatic etc.) but in order to install provider-aws v0.25, I have to upgrade Crossplane to v1.7 because the upgrade will fail since there are unknown objects in the package even though they won't be installed anyway.

I think the ideal flow is that if I don't use webhooks, I shouldn't need to upgrade to another minor version of Crossplane. If I do want to use the webhooks, then it's definitely fair that I need to upgrade Crossplane.

> This would result in a case where a single package could be installed differently based on the version of Crossplane it is being installed with. I would much rather a package say that it can't be installed than to silently ignore items I expect it to install.

Not exactly the same, but there will be some selective installation, i.e. if the webhooks are not enabled no webhook config in the package content will be installed. If you'd like to, we can make the patch more scoped so that it ignores only webhook configs; it would reject all types except crd, validating webhook config and mutating webhook.

**Comment by hasheddan** [comment]
> I think the ideal flow is that if I don't use webhooks, I shouldn't need to upgrade to another minor version of Crossplane.

That would be ideal, but I am not sure that we should be handling it at the package manager level. This feels like a prime candidate for [crossplane version constraints](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Provider/v1@v1.6.4#spec-crossplane-version) in a package. If we had formal cadences and backport policies around providers I think this would be less of an issue because it would be less critical for folks to upgrade to new versions of a provider that potentially included webhook support. That being said, I do understand we are trying to be practical here.

> If you'd like to, we can make the patch more scoped so that it ignores only webhook configs

If we are to make this patch, I definitely think it should be scoped. 👍🏻

**Comment by muvaf** [comment]
> If we had formal cadences and backport policies around providers I think this would be less of an issue because it would be less critical for folks to upgrade to new versions of a provider that potentially included webhook support.

I think the problem is more about hesitance around upgrading Crossplane. While not as heavyweight as Kubernetes, people might want to wait for one or two minor releases before upgrading but for providers, it's usually a faster cycle because more fixes and features go in there. I agree that version constraints would work well but it'd force the upgrade whereas what I'd like to do is not block people using the new provider versions while they are on the same Crossplane version.

> If we are to make this patch, I definitely think it should be scoped. 👍🏻 

I can open a PR for this today if you're onboard.

**Comment by muvaf** [comment]
https://github.com/crossplane/crossplane/pull/2982 and https://github.com/crossplane/crossplane/pull/2981 are opened to allow installation of these packages in v1.5 and v1.6. Once v1.7 is released, users will be able to install packages with webhooks to the last three minor versions. @hasheddan I didn't open a PR for v1.4 since it will EOL with the release of v1.7 but I can do that as well if you'd like to.
