### ISSUE TITLE
Proxy Support Issue for CRD-scaling in GKE Regional Clusters

### ISSUE THREAD

**Issue by ulucinar** [crossplane/crossplane#2964]
### What problem are you facing?

As detailed in #2895, we have been observing issues with GKE regional clusters (with HA control-planes) during the installation of `provider-jet-aws@v0.4.0-preview` with ~800 CRDs. We would like to open a support issue to diagnose these issues and explore any available workarounds/control-plane configuration options, etc. 

### How could Crossplane help solve your problem?

This issue is a proxy issue to share the discussions with the Crossplane community.

**Comment by ulucinar** [comment]
We have opened a support issue (case `29507449`) for GKE regional clusters. The current assessment from the support team is that currently there is no parameter that we can configure to affect the initial control-plane size, and what happens is that GKE determines it cannot repair the control-plane, after some initial crashes, with the machine type where control-plane components are running, and then resizes those VMs. And after the resizing, control-plane is "repaired". And this explains the RUNNING -> REPAIRING -> RUNNING -> REPAIRING -> RUNNING -> REPAIRING -> RUNNING cycle that we consistently observe for regional clusters.

We may also consider reporting these issues we observe with the high numbers of CRDs via [public issue trackers](https://cloud.google.com/support/docs/issue-trackers) for referencing purposes, and to gauge how common these issues are. Because in the context of https://github.com/crossplane/crossplane/pull/2918, we would also like to understand the common Crossplane use cases. An issue in a public tracker could be helpful in accumulating similar issues.

**Comment by muvaf** [comment]
> We may also consider reporting these issues we observe with the high numbers of CRDs via [public issue trackers](https://cloud.google.com/support/docs/issue-trackers) for referencing purposes, and to gauge how common these issues are.

Can we open a public issue so that we can tell Crossplane users who are experiencing this problem where to look?
