### ISSUE TITLE
Support for Consuming Input Secrets from External Secret Stores

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2985]
### What problem are you facing?

With the recently introduced [External Secret Stores](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md) support, it is now possible to write/publish Connection Details to External Secret Stores like Vault.

However, there is another relatively rare use case dealing with sensitive information that still can only be supplied as K8s secrets, i.e. input parameters like an [initial password of a database](https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.25.0#spec-forProvider-masterPasswordSecretRef). 

This indeed applies to Provider Credentials as well. Despite there being ways to avoid writing credentials to k8s secrets, e.g. identity based auth or reading from the filesystem with additional tools like [here](https://docs.crossplane.io/knowledge-base/integrations/vault-injection), the solution for this issue could help us a consistent way of interacting with secrets including provider credentials. 

### How could Crossplane help solve your problem?

With External Secret support, we have the machinery in place to also get input secrets from external secret stores. We need to decide on an API and then can implement it by reusing the same machinery.

**Comment by natereid72** [comment]
There is another edge case to this one (I think). It would be beneficial if we could create secrets from the values in Crossplane cluster MRs' connection secrets, in provisioned K8s clusters with provider-kubernetes. If we could patch from Secret the base64 encoded values, into a Secret manifest object, we could then enable pods running in the provisioned cluster to connect to databases that have been provisioned. 

This might be possible with External Secret Store, but it would be much lighter and less configuration in this model for this specific case.

**Comment by negz** [comment]
Dropping a link to https://github.com/crossplane/crossplane/issues/1770. This is another area that I feel like could tie into XRRs.

**Comment by flashpaper12** [comment]
+1 for this. Without the ability to consume secrets directly from vault, it makes it hard to create any sort of infra that require credentials

**Comment by ibakshay** [comment]
+1 from my side as well.

**Comment by abhigarg28** [comment]
+1
