### ISSUE TITLE
`crossplane` cli tool version information

### ISSUE THREAD

**Issue by Nightreaver** [crossplane/crossplane#2992]
### What problem are you facing?
I would like to see which version of the cli I have installed, but any crossplane command is only giving me "how to use" instead of any version number.
I tried
* `crossplane --help`
* `crossplane -h`
* `crossplane -v`
* `crossplane --version`
* `crossplane version`

### How could Crossplane help solve your problem?
Add version information to the cli, so people can see which version is installed (kind of useful)

**Comment by ulucinar** [comment]
Hi @Nightreaver,
Following seems to be working for me:
```bash
❯ kubectl crossplane -v
v1.5.0-rc.0.80.g07b8dfc6.dirty
```

What's your output with `-v`?

**Comment by Nightreaver** [comment]
I'm running the command without `kubectl`, and there is no `-v` option.

**Comment by ulucinar** [comment]
We are talking about the Crossplane CLI (which is a `kubectl` plugin) as discussed here, is this correct?
https://crossplane.io/docs/v1.6/getting-started/install-configure.html#install-crossplane-cli

If so, could you please share the output of `kubectl crossplane --help`?

**Comment by Nightreaver** [comment]
I think I have mistaken "crossplane" (file) to be the crossplane cli tool.

In fact `crossplane` doesn't offer a version string, while `crank` aka `kubectl-crossplane` does.
So if I use the right cli tool, the version string exists.

**Comment by negz** [comment]
Thanks @Nightreaver! It sounds like you figured this out so I'm going to resolve it. Let me know if I misunderstood.
