### ISSUE TITLE
Cloud provider credentials management

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#3]
As discussed in [this PR](https://github.com/upbound/conductor/pull/1#pullrequestreview-153557440), we need to figure out how are we providing cloud credentials. This could be as simple as a local reference to a Secret, or perhaps a better approach - cloud credentials provider CRD/Operator.

Currently, the controllers are using the default means of discovering cloud provider credentials, which means they have to be running in the target environment (e.g. to deploy Cloud SQL, the controller has to be running inside GCP).  These controllers should be able to run from anywhere (even local minikube) and still manage all cloud provider resources as long as they have been provided valid credentials.

**Comment by panzhaohui** [comment]
We have a similar project at https://github.com/openpitrix/openpitrix，welcome contributions.
