### ISSUE TITLE
CompositionRevision duplicates

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#3011]
### What happened?
Hi,
as we are using more and more composition revision we may have found a bug. 
Or at least a really really unexpected behaviour.

We are facing composition revision duplicates.
Like this:

```
s3bucket-composition-4jsjv             2          False     14d
s3bucket-composition-4ns75             2          False     14d
s3bucket-composition-67rnl             3          False     4d8h
s3bucket-composition-6zh2c             1          False     26d
s3bucket-composition-df5ts             4          False     4d5h
s3bucket-composition-lf2st             5          True      3d6h
```

You see here that the revision `s3bucket-composition-4jsjv` and `s3bucket-composition-4ns75` having the same revision number. 

Comparing the yaml output the only difference is 
```
metadata.name
metadata.resourceVersion
metadata.uid
```

I guess its not expected to have duplicates of revision with the same content.

### How can we reproduce it?
Not sure, but maybe the following is a good hint:

- Enable composition revisions
- Create a composition
- Modify it a couple of times and apply it using kubectl apply 

if this is not enough:
- Let fluxcd apply your changes

### What environment did it happen in?
Crossplane version: 
crossplane/crossplane:v1.6.3
crossplane/provider-aws-controller:v0.24.1

Maybe its important that we use:
FluxCD
for applying our changes to the cluster using Git as source

Best regards

**Comment by MisterMX** [comment]
We encountered this issue as well. We suspect this might be caused by a race condition between two reconciles but weren't able to reproduce it so far.

**Comment by eloo** [comment]
@MisterMX 
ah okay. good to know that at least this issue is already known.

maybe a solution to mitigate the race condition could be use a hash of the file as suffix as mentioned here:
https://github.com/crossplane/crossplane/issues/2656#issuecomment-1062041107

with the hash as suffix a collision would be detected by the reconcilers

**Comment by negz** [comment]
Thanks for the report @eloo! That's definitely not expected.

**Comment by eloo** [comment]
Not stale
