### ISSUE TITLE
Merge `provider-kubernetes` features into Crossplane Core?

### ISSUE THREAD

**Issue by samidbb** [crossplane/crossplane#3027]
### What problem are you facing?

Important features that we are very much in need like:
- Read field values from ConfigMaps and Secrets
- Passing values between resources in a composition

These features have been described in this design document for the enhanced k8s provider:
https://github.com/crossplane-contrib/provider-kubernetes/blob/main/docs/enhanced-provider-k8s.md

### How could Crossplane help solve your problem?
We started using the enhanced kubernetes provider and we quickly realised the how much of challenge it solved for us with regards to implementing our own Confluent provider. So we are going to very much depending the features provided. So we are going to expect that all of our resources will be wrapped into Objects which means that we are going to have nested objects and thus a complicated field mappings which in turn will complicate the authoring process and makes it less desirable for our future Crossplane users in our organisation to write compositions by themselves. Integrating these feature into Core will also make it possible to support field transform on the values that are being consumed from ConfigMaps or from other references resources.

**Comment by muvaf** [comment]
> Read field values from ConfigMaps and Secrets

Would this design solve this use case for you? https://github.com/crossplane/crossplane/pull/3008

> Passing values between resources in a composition

It's possible to use `ToComposite` patch type to copy a value from composed resource to the composite and then in another resource, use that value `FromComposite`. You can also block the creation if you make the patch policy `Required`. Would that help you in this case?

**Comment by samidbb** [comment]
I think the design will solve this use case for us.
with regards to using ToComposite and FromComposite patches it will involve using labels or annotation as temporary variables right?

**Comment by muvaf** [comment]
@samidbb you can have status fields in your `CompositeResourceDefinition` and use them as the middleman or go with labels/annotations for flexibility.

**Comment by samidbb** [comment]
We are using this approach already for storing temporary variables to overcome the shortcomings that are mentioned in the examples here https://github.com/crossplane/crossplane/issues/3025 and here https://github.com/crossplane/crossplane/issues/3026. So we want to avoid using this approach since it really complicate the process for writing and testing compositions.

**Comment by muvaf** [comment]
The other option I can think of is to make a patch type that will carry values between two composed resource but that'd complicate the patch mechanics even more since it'd add yet another dimension of value transit.

**Comment by grafanalf** [comment]
Any progress on this? I have some use cases that would benefit from being able to read data from existing Kubernetes resources, like Secrets and ConfigMaps. For example, for self-managed certificates in AWS ACM, uploaded from a Certificate provisioned by `cert-manager`.

**Comment by MisterMX** [comment]
I don't think this is going to make it into core since it carries the danger of privilege escalation of a user. If you want to read data from something like `ConfigMaps`, Composition environments are a better and more powerful alternative to that (see #3007).
