### ISSUE TITLE
Repository maintenance improvements

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3046]
### What problem are you facing?

The c/c maintainers are starting to have trouble keeping up with issues and PRs raised against this repo. We'd like to ensure a good contributor experience (i.e. prompt responses to issues, reviews of PRs, etc) while also ensuring a fair workload for maintainers. I'd like to use this issue to explore some ideas around automation that may help here.

### How could Crossplane help solve your problem?

Some things we've discussed are:

1. Recruiting some 'reviewers'. These folks would be responsible for reviewing pull requests before escalating them to a maintainer for final approval. Reviewers would not have permission to merge PRs and would not have a vote governance wise. This means we'd be able to be more lenient with new reviewers - offering a good way for folks to get involved with the project and potentially 'graduate' to a maintainer.
2. Using CODEOWNERS and/or some other form of auto-assignment to assign new pull requests. If we also introduced 'reviewers' we'd presumably automatically assign 1-2 reviewers and one approver for each PR.
3. Adding a 'stale bot' to close stale issues.
4. Setup a [Slack nag bot](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-scheduled-reminders-for-your-team) to remind about open pull requests. Perhaps we could create a private "maintainers-and-reviewers" channel on Crossplane Slack to send these to?

**Comment by MisterMX** [comment]
@negz Thanks for raising this issue. I think its very important to tackle this problem. We also experienced that waiting for open source reviews became quite a bottleneck in our development process.

I would offer to become one of those "community reviewers" or even an actual maintainer depending on whether the former does actually help speeding things up since maintainer approval is still required.

**Comment by negz** [comment]
> Adding a 'stale bot' to close stale issues.

FWIW I enabled this for this repo today.

I'd really like to setup reviewers and auto-assignment ASAP, but I'm struggling to find good existing automation that can handle it. I'm looking for something similar to prow on Kubernetes where you can make the distinction between reviewers and approvers at the directory level, and assign both to new PRs. I'm a little wary to try use actual prow though (iirc it's somewhat heavyweight to run).

**Comment by negz** [comment]
I think we're close to done here. To recap:

* We now have a "stale bot" that will mark issues and PRs stale after 90 days of inactivity, then close them after a further 7 days of inactivity.
* All new PRs will be assigned to one maintainer and two reviewers. We try to assign to a maintainer who is an SME for the part of the codebase being updated. For now we pick the two least loaded reviewers regardless of what part of the codebase is being updated.
* I've also setup a nag bot to nag about open PRs in #dev on Crossplane Slack every Monday.

<img width="1002" alt="Screen Shot 2022-08-15 at 4 56 56 PM" src="https://user-images.githubusercontent.com/1049349/184755882-a978936a-447f-4def-bd28-f4856b24809f.png">

That said, I'm going to reopen because I would like to:

* Document the responsibilities of reviewers.
* Recruit some reviewers.
* Extend this to include the crossplane-runtime and crossplane-tools repos.

**Comment by negz** [comment]
> I would offer to become one of those "community reviewers" or even an actual maintainer depending on whether the former does actually help speeding things up since maintainer approval is still required.

@MisterMX I've sent you an invite to be our first reviewer. Could you please follow the process at https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members to become a member of the org. :)

**Comment by negz** [comment]
It seems like per https://github.com/probot/stale/issues/324 Stale bot is unmaintained and doesn't work so well, which is unfortunate given that it appears to be an "official" GitHub app.

The new hotness appears to be https://github.com/actions/stale. I've uninstalled the Stale bot from our org and will now attempt to switch this repo over to the action.
