### ISSUE TITLE
Feature: Enable package signature validation with cosign

### ISSUE THREAD

**Issue by jessesanford** [crossplane/crossplane#3048]
Design 1-pager: https://github.com/crossplane/crossplane/pull/3297

Implementation: https://github.com/crossplane/crossplane/pull/3552

**What problem are you facing?**
Signed Crossplane packages are not able to be validated before installation.

**How could Crossplane help solve your problem?**

After speaking with @hasheddan in the slack channel, I would like to do some investigation into how we might enable validation of Sigstore Cosign signatures on the OCI images representing Crossplane Packages.

The Crossplane package controller reconcile loop seems like the logical place to do this validation.
https://github.com/crossplane/crossplane/blob/7d01448f8a52e0f3a13add4fc0f81028fcd13400/internal/controller/pkg/manager/reconciler.go#L236

We could possibly create a new "Condition" status for validation failures.

I believe that the initial functionality targeted should be to validate the signatures on images against a public key or list of public keys passed to crossplane. I am not sure if we want to deal with CA bundles at the moment. 

Later we can possibly validate against the Sigstore Rekor transparency log as well. This would allow for validating images signed using the Sigstore Keyless signatures method: https://github.com/sigstore/cosign/blob/main/KEYLESS.md

There is an Open Issue within the Cosign repo to create a lightweight validation library. https://github.com/sigstore/cosign/issues/532

There is also some prior art showing example usage of cosign validation in an opa plugin here:
https://github.com/sigstore/cosign/blob/1e055235dc5bdab5f9d446ad5fd31dbc72225312/copasetic/main.go#L190-L201

I am inquiring at the community meeting if there has been any more work there.

**Comment by asraa** [comment]
I have some example usage of a cosign verification for keyless signed blobs, not containers, but there is some overlap in how to verify the TLOG entries
https://github.com/slsa-framework/slsa-verifier/blob/aee753f58fa9a4de2be6290e3eefae2d6e998a9d/pkg/provenance.go#L311

I'd be happy to review the verification code in the module, and double check that all the properties are there.

**Comment by hectorj2f** [comment]
@jessesanford We are currently working on reusing the current effort of sigstore/cosigned to verify signatures even using the CLI. I am not sure if that would help you but here we have our own admission controller with the validation piece of code https://github.com/sigstore/cosign/blob/main/pkg/cosign/kubernetes/webhook/validator.go#L115 and the CIP api type definition https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_types.go. I am not sure if you are interested on reusing the CIP policy definition to apply it against your packages.

**Comment by jessesanford** [comment]
Andres Torres mentioned the following from the admission controller: https://github.com/sigstore/cosign/blob/main/pkg/cosign/kubernetes/webhook/validation.go

**Comment by developer-guy** [comment]
We did the same effort in Flux v2, you can take a look at the following issue 👇 

https://github.com/fluxcd/source-controller/issues/863

/cc @stefanprodan @dentrax

**Comment by jessesanford** [comment]
That's exactly what we are thinking. Would love the help @developer-guy! @hasheddan should we extend the one pager to include the cli changes or create a new one?

**Comment by hasheddan** [comment]
> should we extend the one pager to include the cli changes or create a new one?

I don't think we necessarily need to bring Crossplane CLI into scope (at least initially) here. One of the benefits of using OCI images is that users can rely on the same tooling they use elsewhere. In this case, `cosign` itself can be used to perform the signing.

xref https://github.com/crossplane/crossplane/issues/3055

**Comment by jessesanford** [comment]
Fair enough. At the very least it might be interesting to have some examples created on how to implement signing into a workflow that produces xpkgs. Maybe some documentation additions?

**Comment by jessesanford** [comment]
@developer-guy, @turkenh if you still want to lend a hand, I have started coalescing commits for a initial implementation for validation here: https://github.com/crossplane/crossplane/compare/master...jessesanford:crossplane:master 

Right now I am just doing simple signature validation with x509 certs. I think that a next step iteration to implement policy validation would be very helpful. Were you able to achieve that in flux?

**Comment by stevehipwell** [comment]
This functionality is something I've been thinking about for a while so it's really interesting to see someone working on this. I might be missing the point here but shouldn't the signature validation be per object being validated? For example the Provider CRD could be modified to carry a validation enabled field and certificates/identity field to carry the approved signers. For certificates a reference a file from a secret would work (might we need multiple files), for approved signers you might want to allow multiple identities such as a user and a GitHub Actions context.

**Comment by jessesanford** [comment]
@stevehipwell I would love to brainstorm with you further on this. We are considering a few different mechanisms to allow for evaluation of signatures on a per package basis. We also are considering policies vs creating lists of approved signers. Maybe you could make suggestions in the context of the one pager design doc?

**Comment by stevehipwell** [comment]
@jessesanford I'll add some comments to the one pager.

**Comment by jessesanford** [comment]
Thanks, Responded Inline!

**Comment by developer-guy** [comment]
count me in 🙈

**Comment by jessesanford** [comment]
@developer-guy check out: https://github.com/crossplane/crossplane/pull/3552 I copied a lot of your work from the flux implementation. It's a total WIP so please contribute if you can!

**Comment by jessesanford** [comment]
@stevehipwell check out https://github.com/crossplane/crossplane/pull/3552 I have made it possible to enable validation on a per package basis via the package spec's ValiationSecrets fields. Let me know what you think.

**Comment by jessesanford** [comment]
> > should we extend the one pager to include the cli changes or create a new one?
> 
> I don't think we necessarily need to bring Crossplane CLI into scope (at least initially) here. One of the benefits of using OCI images is that users can rely on the same tooling they use elsewhere. In this case, `cosign` itself can be used to perform the signing.
> 
> xref #3055

@hasheddan I added support to allow for installing packages and passing in the validation pems from the command line as the names of secrets in https://github.com/crossplane/crossplane/pull/3552 would love your thoughts, might be cool to pass in files and have the secrets created as well.

**Comment by negz** [comment]
I've added this as a stretch goal/maybe for getting composition functions to GA. I could see folks wanting to only allow signed functions to run on their control planes.
