### ISSUE TITLE
ProviderConfig should have Ready state with true/false

### ISSUE THREAD

**Issue by ArunRamakani** [crossplane/crossplane#3052]
If we try to compose helm or k8s provider config inside a composition, the XR/Claim does not move to Ready state as true even after all composed resources are created successfully.

I guess this is because the ProviderConfigs does not have a Ready flag. 

It will be useful when we have a remote cluster created with XR/Claim and wanted to generate provider config for that remote cluster in the same composition.

**Comment by turkenh** [comment]
You can use custom readinessChecks, please see https://github.com/crossplane-contrib/provider-helm/blob/176aa6812860e95712ea7aecd541a564bc839b14/examples/in-composition/composition.yaml#L166

**Comment by ArunRamakani** [comment]
Great @turkenh. Thanks for the quick help

**Comment by jbw976** [comment]
I see people running into this semi-frequently - i wonder if this is something we could address so that people don't have to run into this behavior then find the solution.

Is there a downside to having ProviderConfig just set Ready=True all the time?
