### ISSUE TITLE
Can we pass the logger to the lifecycle functions?

### ISSUE THREAD

**Issue by shu-ming** [crossplane/crossplane#3058]
### What problem are you facing?
I'm building a custom provider with Crossplane. I want to emit error logs when something gets wrong in the lifecycle functions, e.g. the api calls to external cloud always get errors in **Observe** due to the external cloud downtime. Currently all these kind of errors would be written into the log by the reconciler only when we set the log level to debug. But the logs are too verbose if we enable the debug mode. 
I am able to pass the logger into the lifecycle functions and emit these errors with log.Info(). I am wondering if this is the proper way to tackle this issue? or maybe there is another elegant way that follows the crossplane design.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/master/docs/contributing/observability_developer_guide.md may be of interest.

Typically we recommend that logs are only emitted for debugging purposes, and not for 'production' use. Instead we recommend emitting Kubernetes events, which 'regular users' (i.e. folks who may not have access to the provider pod logs) can see. If Observe for example hits an error, you can return that error and Crossplane will automatically include it in an event that folks can see by running `kubectl describe mytype broken-thing` (e.g. `kubectl describe rdsinstance foo`).

**Comment by negz** [comment]
I'm going to close this one in the hope that I've answered your question. 🙂 https://github.com/crossplane/crossplane/discussions would be a good place to continue the discussion if needed.

**Comment by shu-ming** [comment]
understood. I raise this as the events are not persistent. Now all the k8s events get persistent for one month on cloud. I can look back these events for trouble shooting.
