### ISSUE TITLE
Lifecycle Hooks

### ISSUE THREAD

**Issue by natereid72** [crossplane/crossplane#3066]
### What problem are you facing?

I've searched the open issues and see a number of 'ordered create/delete' requests. But I don't find this case, apologies in advance if it is being tracked already.

There are cases with provider-kubernetes and provider-helm where we create a resource that is a sort of 'create outside of managed resource; mode. For example, if we create a k8s job via provider-kubernetes that creates a database in an RDS instance, or use a jet provider to do the same with a Lambda function.

In this case, the created database is not reconciled by the Provider. If we delete the Claims that created the larger Composition of MRs, we do not delete those resources.

This edge case only exists when the particular target API doesn't expose the operation we desire. For example, AWS does not expose an API to create a database in an RDS instance. While Azure does expose an API to create a database in a Managed DB service instance. So this specific example applies to AWS API but not Azure.

### How could Crossplane help solve your problem?

A set of hooks similar to Helm's (https://helm.sh/docs/topics/charts_hooks/) would be useful. If there was a pre/post-delete hook on an MR, we could run the inverse on those non-tracked resources .

**Comment by negz** [comment]
I can't immediately find any issues, but we've had some discussion in the past about Crossplane deleting things that it didn't directly created - the quintessential example is deleting all the objects in an S3 bucket. Crossplane created the bucket, but didn't create the objects in it. Crossplane can't delete the bucket until the objects are deleted first. We've historically been wary of allowing Crossplane to delete things that it did not create itself.

I like the idea of using potentially hooks to address this though. I think the first thing we'd want to see is a design for how the API might work.

FWIW https://github.com/crossplane-contrib/provider-sql is intended to cover the use case of creating SQL databases.

**Comment by negz** [comment]
@natereid72 Do you think these hooks would fit best at the MR level, or at the XR level?

**Comment by natereid72** [comment]
@negz 

> FWIW https://github.com/crossplane-contrib/provider-sql is intended to cover the use case of creating SQL databases.

In this case, I am creating a database on an RDS instance that isn't open to the network my Crossplane is running on. So am running K8s job with mysql client to create DBs from K8s cluster running on network attached to RDS instance. So provider-sql wasn't best option. In that case, I'd want a hook to run the inverse job. Alternatively, could use jet provider for Lambda function, but would be in same boat on delete.

> Do you think these hooks would fit best at the MR level, or at the XR level?

idk, up for hearing others thoughts. I thnik it makes sense to be at XR more than MR I suppose.

**Comment by natereid72** [comment]
Revive

**Comment by natereid72** [comment]
I believe this is being pursued in another open issue. Closing.
