### ISSUE TITLE
Implementing helm-based reference XRM function

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane/crossplane#3067]
After our sync meeting on 19 April with @negz , we determined some action items for the Custom Compositions task. One of them is the providing a helm-based reference function.

One of the main goals of the Custom Compositions' alpha version is preparing 1-2 advanced XRM functions. So we will work to implement a XRM reference function. By using the provided function (image), we believe that, the users can test the general functionalities of the Custom Compositions and also they can use this function for their use cases.

**Comment by sergenyalcin** [comment]
About this issue there is an example KRM function in KPT function catalog: https://catalog.kpt.dev/render-helm-chart/v0.1/

I reviewed implementation of this function to understand the design because I thought that, integrating the same approach to our XRM reference function can be an option. (For discovering the render function of KPT catalog period, we also discussed the details and possible options with @ulucinar Please share your ideas/comments this issue if you want)

I observed that, this KRM function does not use the ResourceList.Items field and it gives empty to the function input. This function uses two options to render helm charts. And deciding the method and determining the inputs, the function uses the ResourceList.FunctionConfig field. The two options:

- First one is that, mounting the helm chart to the container (for local scenario), then running the helm template command in this chart directory. 
- The second one is that, pulling and untaring the helm chart from network and then running the helm template command for the pulled chart. 

As a last step (for both scenarios), it puts the outputs of the helm template command to the ResourceList.Items.

To be honest, I imagined that the render-helm-chart function (in KPT katalog) uses the ResourceList.Items as input, then it builds the chart from this input items in container. Then runs the template command. However, it does not do this and in this context, I am not sure that this approach/implementation/architecture is compatible with the KRM function specifications: https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md

From these observations that I mentioned above, the scenario in which the chart is mounted to the container does not seem very suitable for our design and API specifications. As we mentioned in design doc, the XRM functions will run inside the crossplane container and I do not think that it is something we want to mount external helm charts to this.

Therefore, it seems more appropriate to write our render XRM function with a different approach than the one in the KPT catalog. I would like to share a few suggestions that came to my mind regarding this:

- Getting the elements of the chart from ResourceList.Items and building the chart inside the container. Then running the helm template for this built chart.
- Pulling and untaring the chart, which is the second approach in the KPT catalog, and running this command on the downloaded chart can be another option. At this point ResourceList.Items can be used as values.yaml after pre-processing i.e. converting XR to values.yaml 

@negz What are your thoughts about this situation? What should be the best approach for this?

**Comment by negz** [comment]
> Therefore, it seems more appropriate to write our render XRM function with a different approach than the one in the KPT catalog.

Agreed.

> Getting the elements of the chart from ResourceList.Items and building the chart inside the container. Then running the helm template for this built chart.

Can you expand on what you mean here by "elements"? Are you suggesting the input `ResourceList.items` be used as the Helm chart templates? Or the values.yaml? (Or both?)

> Pulling and untaring the chart, which is the second approach in the KPT catalog, and running this command on the downloaded chart can be another option. At this point ResourceList.Items can be used as values.yaml after pre-processing i.e. converting XR to values.yaml

This is definitely the approach I was imagining we'd take. I think if we build this function as a small wrapper around the `helm` (Helm 3) CLI tool we don't even need to pull and untar the chart - Helm will do it for us. I just quickly tested this:

```shell
$ nix-shell -p kubernetes-helm
$ helm version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"", GoVersion:"go1.17.7"}
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping
$ helm template test bitnami/memcached | head -n 10
---
# Source: memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-memcached
  namespace: default
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-6.0.17
~ $
```

**Comment by negz** [comment]
Another option we might consider is building this as a tool that bakes the Helm chart into the function - so instead of a generic `render-helm-chart` function each person would use a tool to build a `render-my-specific-helm-chart` function.

I'm on the fence about whether this would be a better or worse experience. I'm expecting folks will need to write a bespoke Helm chart that takes an instance of their particular XR as an input (i.e. as `values.yaml`) - they're not going to be able to use a generic existing Helm chart. So with that in mind is it better for them to:

* Write their custom Helm chart, push it somewhere, then use the generic Helm function?
* Write their custom Helm chart, bake it into a Helm function, and push that somewhere?

One thing to consider is that in the first case we'll definitely need to accept a `functionConfig` to specify what Helm chart to fetch.
