### ISSUE TITLE
Deploy K8 cluster and a workload on it

### ISSUE THREAD

**Issue by anilnokia** [crossplane/crossplane#3069]
I can create a gke cluster using Crossplane. But How can I deploy cluster and workload on the created cluster using same manifest? 

Thanks,

**Comment by ytsarev** [comment]
@anilnokia if I understood the context correctly you can potentially use https://github.com/crossplane-contrib/provider-kubernetes

**Comment by anilnokia** [comment]
Do you have any example manifest to use provider-kubernetes?

**Comment by ytsarev** [comment]
@anilnokia I will close this issue if you don't mind. 

Let's continue at https://github.com/crossplane/crossplane/discussions/ if you have any additional questions.

**Comment by anilnokia** [comment]
Yes please.

Thanks
