### ISSUE TITLE
Multiple occurrences of `No such file or directory` when running `make reviewable`

### ISSUE THREAD

**Issue by shreemaan-abhishek** [crossplane/crossplane#3097]
### What happened?

I ran `make reviewable` as [suggested](https://github.com/crossplane/crossplane/pull/3087#issuecomment-1128236532) by @haarchri. Then I got this error:

```
/bin/bash: /Users/shreemaan-abhishek/go/src/github.com/crossplane/crossplane/.cache/tools/darwin_arm64/go-junit-report: No such file or directory
17:59:51 [FAIL]
```

So I manually created the `go-junit-report` directory.  I re-ran the `make reviewable` command, then I realised that it should have been a file because I got an error: 

```
/bin/bash: /Users/shreemaan-abhishek/go/src/github.com/crossplane/crossplane/.cache/tools/darwin_arm64/go-junit-report: is a directory
18:09:01 [FAIL]
```

So I deleted the `go-junit-report` directory and created a file with the same name.

I ran `make reviewable` again, then I got this error:

```
/bin/bash: /Users/shreemaan-abhishek/go/src/github.com/crossplane/crossplane/.cache/tools/darwin_arm64/gocover-cobertura: No such file or directory
```

(not again 😮‍💨)

It would have been really neat if `make reviewable` would create all the files and folders that it needs instead of throwing such errors.

### How can we reproduce it?

Just run `make reviewable` in the root of the freshly cloned copy of this project.
### What environment did it happen in?
Crossplane version: NA

**Comment by bobh66** [comment]
Did you run "make" by itself after running git clone?  That should set up the build environment so that everything else works.

See https://github.com/crossplane/crossplane/blob/master/CONTRIBUTING.md#establishing-a-development-environment

**Comment by shreemaan-abhishek** [comment]
@bobh66 , no I had not run `make` before you told me to do so. So I ran `make` and then ran `make reviewable`, but I still get the error:

```
/bin/bash: /Users/shreemaan-abhishek/go/src/github.com/crossplane/crossplane/.cache/tools/darwin_arm64/go-junit-report: No such file or directory
08:39:29 [FAIL]
```

**Comment by negz** [comment]
@shreemaan-abhishek Try clean your make environment and start over. So `make distclean && make && make reviewable`.

**Comment by shreemaan-abhishek** [comment]
@negz Still the same error 😬 

```
/bin/bash: /Users/shreemaan-abhishek/go/src/github.com/crossplane/crossplane/.cache/tools/darwin_arm64/go-junit-report: No such file or directory
21:00:34 [FAIL]
```

**Comment by ytsarev** [comment]
@shreemaan-abhishek what is the output of `make submodules` ?
