### ISSUE TITLE
Flux Crossplane Provider

### ISSUE THREAD

**Issue by ChrisJBurns** [crossplane/crossplane#3100]
### What problem are you facing?
Currently, when we provision a new managed cluster (AKS, EKS, GKE etc), when the cluster has been provisioned and can verify it is up and running, we have to manually install Flux onto the cluster.

### How could Crossplane help solve your problem?
There are some hacky solutions using [`crossplane-terraform`](https://github.com/junaid18183/flux_crossplane_package), but I think it would be better if we had an official Flux Crossplane provider (Similar to how Terraform has a Flux Provider without having to use it like the hacky solution mentioned above). Crossplane works very well with GitOps, so I think this would further encourage people to adhere to this principle? Especially if we provide a Flux provider that allows people to not only create clusters using the Cloud provider provider packages, but then also using the Crossplane Flux provider to install Flux onto the newly created cluster.

**Comment by haarchri** [comment]
you can use flux2 helm-chart 
https://github.com/fluxcd-community/helm-charts/tree/main/charts/flux2
and flux2-sync helm-chart 
https://github.com/fluxcd-community/helm-charts/tree/main/charts/flux2-sync

with provider-helm

**Comment by haarchri** [comment]
here is also an idea to implement with compositions: https://github.com/upbound/platform-ref-aws/pull/60
