### ISSUE TITLE
Docs: Document ProviderConfigUsage

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#3118]
### What problem are you facing?

With ProviderConfigUsage [e.g. in AWS](https://doc.crds.dev/github.com/crossplane/provider-aws/aws.crossplane.io/ProviderConfigUsage/v1beta1@v0.13.0) we have a CR that indicates that a resource is using a ProviderConfig. This type is not documented and it's unclear to the user what the purpose of that resource is and how to work with it.

### How could Crossplane help solve your problem?
Document the resource / provider pattern.

**Comment by negz** [comment]
I believe this was originally implemented in https://github.com/crossplane/crossplane-runtime/pull/206.

While I don't disagree that it should be documented somewhere, `ProviderConfigUsage` something end users are expected to need to be aware of or really think about. You can think of them as similar to finalizers - they exist to prevent a `ProviderConfig` from being deleted until all the managed resources that use it are deleted. This is of particular use when an XR is composed of a `ProviderConfig` and one or more MRs that use that `ProviderConfig`; it's a scoped form of deletion ordering.

**Comment by luebken** [comment]
> ProviderConfigUsage is not something end users are expected to need to be aware of or really think about. 
I would argue if it's there, it should be documented. I think especially Platform Builders would appreciate a brief explanation like the one above. 

What if we expand
// A ProviderConfigUsage indicates that a resource is using a ProviderConfig.
to
// A ProviderConfigUsage indicates that a resource is using a ProviderConfig. They are similar to finalizers - they exist to prevent a ProviderConfig from being deleted until all the managed resources that use it are deleted. This is of particular use when an XR is composed of a ProviderConfig and one or more MRs that use that ProviderConfig; it's a scoped form of deletion ordering.

in https://github.com/crossplane-contrib/provider-aws/blob/master/apis/v1beta1/providerconfig_types.go#L238
