### ISSUE TITLE
CompositeResourceDefinition shouldn't just blindly propagate annotations

### ISSUE THREAD

**Issue by renescheepers** [crossplane/crossplane#3123]
### What happened?
Currently we use a [deploy-tool](https://github.com/Shopify/krane) that prunes all resources that have a certain label in combination with annotation `kubectl.kubernetes.io/last-applied-configuration` when you are applying manifests. When using this tool to deploy CompositeResourceDefinitions this causes issues, because the CRD's both will have copied over all annotations and labels. 

The annotations shouldn't just be blindly propagated to all CRD's. Simple example being `kubectl.kubernetes.io/last-applied-configuration`, this one isn't relevant to the CRD's, only to the CompositeResourceDefinition being applied. Using the owner reference it should already be able to lookup all the annotations if you need this information anywhere. 

### How can we reproduce it?

<details>
  <summary>CompositeResourceDefinition</summary>
  
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtests.shopify.com
  labels:
    app: copied
  annotations:
    copied-as-well: "this is also copied over"
spec:
  group: shopify.com
  names:
    kind: XTest
    plural: xtests
  claimNames:
    kind: TestInstance
    plural: testinstances
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
```
</details>

<details>
  <summary>XTest</summary>
  
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    copied-as-well: this is also copied over
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.crossplane.io/v1","kind":"CompositeResourceDefinition","metadata":{"annotations":{"copied-as-well":"this is also copied over"},"labels":{"app":"copied"},"name":"xtests.shopify.com"},"spec":{"claimNames":{"kind":"TestInstance","plural":"testinstances"},"group":"shopify.com","names":{"kind":"XTest","plural":"xtests"},"versions":[{"name":"v1","referenceable":true,"schema":{"openAPIV3Schema":{"properties":{"spec":null},"type":"object"}},"served":true}]}}
  creationTimestamp: "2022-06-03T07:19:38Z"
  generation: 1
  labels:
    app: copied
  name: xtests.shopify.com
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    controller: true
    kind: CompositeResourceDefinition
    name: xtests.shopify.com
    uid: 40526d10-645f-4c86-87b8-a41c564c87b7
  resourceVersion: "47744742"
  uid: da56c96a-b22b-474e-b261-e5c59b3f54f5
spec:
  conversion:
    strategy: None
  group: shopify.com
  names:
    categories:
    - composite
    kind: XTest
    listKind: XTestList
    plural: xtests
    singular: xtest
  scope: Cluster
  ...removed
```
</details>

<details>
  <summary>TestInstance</summary>
  
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    copied-as-well: this is also copied over
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.crossplane.io/v1","kind":"CompositeResourceDefinition","metadata":{"annotations":{"copied-as-well":"this is also copied over"},"labels":{"app":"copied"},"name":"xtests.shopify.com"},"spec":{"claimNames":{"kind":"TestInstance","plural":"testinstances"},"group":"shopify.com","names":{"kind":"XTest","plural":"xtests"},"versions":[{"name":"v1","referenceable":true,"schema":{"openAPIV3Schema":{"properties":{"spec":null},"type":"object"}},"served":true}]}}
  creationTimestamp: "2022-06-03T07:19:38Z"
  generation: 1
  labels:
    app: copied
  name: testinstances.shopify.com
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    controller: true
    kind: CompositeResourceDefinition
    name: xtests.shopify.com
    uid: 40526d10-645f-4c86-87b8-a41c564c87b7
  resourceVersion: "47744737"
  uid: decd1462-8372-420d-8e3a-410a338b8587
spec:
  conversion:
    strategy: None
  group: shopify.com
  names:
    categories:
    - claim
    kind: TestInstance
    listKind: TestInstanceList
    plural: testinstances
    singular: testinstance
  scope: Namespaced
  ...removed
```
</details>

**Comment by ytsarev** [comment]
@renescheepers could you show associated Composition?

**Comment by renescheepers** [comment]
> @renescheepers could you show the associated Composition?

In the sample I gave there isn't a Composition I combine it with. Just to show that the two CRD's(claim, XRD) get the same annotations. I have no issues with the compositions themselves.

**Comment by ytsarev** [comment]
@renescheepers my assumption was that something inside in Composition is actually copying the annotations over.

**Comment by renescheepers** [comment]
> @renescheepers my assumption was that something inside in Composition is actually copying the annotations over.

Correct me if I'm wrong, but I think this [code](https://github.com/crossplane/crossplane/blob/181f4ba67ee9e5a5d3dbc6c723a0993f301ed044/internal/xcrd/crd.go#L138) is responsible for that.

**Comment by ytsarev** [comment]
@renescheepers Ah, now I get this problem, sorry, was thinking that we are talking about metadata propagation down to MRs.

@negz looks like the above-mentioned metadata copy is part of the current design. Do you remember why? Should we change it?

**Comment by negz** [comment]
> Do you remember why? Should we change it?

I don't. Changing it seems reasonable.
