### ISSUE TITLE
External name annotation when there is no identifier

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#3128]
### What problem are you facing?

There are resources such as [IAM Role Attachment](https://github.com/crossplane-contrib/provider-aws/blob/aef7ee3/pkg/controller/iam/rolepolicyattachment/controller.go#L100) where there is no specific identifier that we can use as external name. The parameters make up the final identifier. Another example could be the AWS [`Route`](https://github.com/crossplane-contrib/provider-aws/blob/aef7ee3/pkg/controller/ec2/route/setup.go#L80) resource uses the route table ID and destination as an identifier. Terraform uses the following as ID: `ROUTETABLEID_DESTINATION `, we'd just skip external name at the moment.

The pattern is that the information is duplicated in spec and external name and that complicates import scenario in following way:
* If `Observe` uses external name string and decompose it to call the `GET` method, resource will be imported. However, if the external name is empty, it needs to use the parameters (which are usually required). Which one should take precedence is not clear.
* If `Observe` always uses spec parameters in `GET` calls, then external name has no usage at all. The import would be done by filling out the required fields, which could be fine given that the import flow [requires](https://crossplane.io/docs/v1.8/concepts/managed-resources.html#importing-existing-resources) filling up the required parameters as well.

 In the [API Patterns](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#external-resource-name), the closest case is `The provider doesn't allow us to specify a name. Fetch it after its client's POST call.` but there is no identifier in the result of `POST` call, it's just the parameters.

This case seems to be prevalent in especially the resources that connect/add/bind one to the other.

### How could Crossplane help solve your problem?

Right now, I see that several implementations are going with the second scenario above, i.e. use parameters and skip external name. However, we should discuss and add it to the API patterns doc.

Options coming to my mind would be:
* Force identification to be scoped to a single string as external name and come up with a decision about whether spec or annotation takes precedence.
  * The required fields would still be required. We might take over the `requiredness` calculation by a webhook to enforce it only if there is no external name.
* Keep it as is but relax import scenario by saying that `required fields and in most cases external name are needed` to import.
  * This would assume that the ID is opaque, similar to `AWS VPC`, and controller may choose to use it if it has information other than what's specified in parameters.
* Remove the identifier information from spec even if it's a config parameter(s).
  * References need to be thought.

In my opinion, the second option is the one that doesn't affect a bigger set of resources that don't have this behavior. However, it does add a bit complexity to our import flow. To be fair, as long as it's not a single string, the complexity of having to fill up the required fields is still there. It'll just be that we recognize that external name annotation may not be used at all.

A more drastic option is to remove external name completely and add a new field to spec for ID only in case it's calculated by the provider as described [here](https://github.com/crossplane/crossplane/issues/1863#issuecomment-731255832).

cc @negz @ezgidemirel

**Comment by mbbush** [comment]
/fresh

I've run into similar issues, as well as the problems documenting external name semantics. 

Could we perhaps have a `spec.externalName` instead of an annotation, which would be consistent across resources, so that it could be documented, and would be more of a "first class" member of the schema? It could be made optional in the case of resources where the import id is determined by the parameters.
