### ISSUE TITLE
Crossplane should export timeseries metrics

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#314]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** I'd like Crossplane to export timeseries metrics such that I could monitor it to ensure it is healthy. It likely makes sense to target Prometheus given its broad support within the Cloud Native world. I highly recommend https://opencensus.io/ as an instrumentation library.

**What is use case behind this feature:** Introspecting the state of Crossplane for graphing and alerting in a production deployment. This is not a huge priority right now while we're targeting 0.2, but I wanted to raise an issue to start discussion of how this might look.

**Comment by morigs** [comment]
Now Crossplane should focus on [OpenTelemetry](https://opentelemetry.io/)

**Comment by jbw976** [comment]
Dropping a breadcrumb to https://github.com/kubernetes-sigs/controller-runtime/issues/305, which discusses some of the obstacles for us to "easily" move from prometheus based metrics to OpenTelemetry (OTel).

**Comment by hwinkel** [comment]
@jbw976 I would even say not to focus solely on Metrics in OTEL format. Specifically OTEL tracing would have huge benefits for a tool like crossplane as you can trace and visualize the reconciliation process and might have a easy way to introspect reconciliation error or problems like API throttling or similar. Specifically, as discussed with terraform based Upjet providers.

**Comment by hwinkel** [comment]
It would be also good to have OTEL Tracing in the providers or Provider SDKs like upjet IMHO?!?
