### ISSUE TITLE
Provision OpenShift cluster

### ISSUE THREAD

**Issue by dorroddorrod** [crossplane/crossplane#3140]
Hi all,
Is there a way to provision an OpenShift cluster using Crossplane ?

**Comment by negz** [comment]
I'm not aware of any provider that targets OpenShift at the moment. Is there an API Crossplane could call to provision OpenShift clusters?

**Comment by aabouzaid** [comment]
I'm also looking for a way to set up OpenShift on [Red Hat Cloud](https://cloud.redhat.com/). However, I couldn't find any API to do that programmatically.

One more tip here: OpenShift is also available on other platforms like [AWS ROSA](https://aws.amazon.com/rosa/) which could be a good solution based on the use case (also a similar option available for other cloud providers like GCP and Azure).

**Comment by aabouzaid** [comment]
Here is the API of the OpenShift project.
https://api.openshift.com/

**Comment by aabouzaid** [comment]
@negz do you have a starting point or a recommendation in case I want to start a provider for OpenShift?

**Comment by dorroddorrod** [comment]
Consider using openshift HIVE
https://github.com/openshift/hive

**Comment by luebken** [comment]
What kind of setups are folks looking for? Where do you want to provision OpenShift to?

> https://github.com/openshift/hive

Nice. Hive seems to use https://github.com/openshift/installer which might be another great starting point.

**Comment by aabouzaid** [comment]
@dorroddorrod @luebken
I actually was asking about the Crossplane side since I don't have much experience in writing providers.
I'm namely looking for getting started or so.

**Comment by aabouzaid** [comment]
FYI, I plan to look into this in Q3 2023.

**Comment by walidshaari** [comment]
https://www.redhat.com/en/blog/creating-azure-red-hat-openshift-and-red-hat-openshift-services-on-aws-clusters-declaratively
