### ISSUE TITLE
Cut v1.9.0 on July 12, 2022

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3169]
This issue can be closed when we have completed the following steps (in order).

Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from this issue for posterity. Refer to this [prior release issue][release-1.7] for examples of each step.

- [x] Prepare the release branch at the beginning of [Code Freeze]:
  - [x] Created the release branch.
  - [x] Created and merged an empty commit to the `master` branch.
  - [x] Run the [Tag workflow][tag-workflow] on the `master` branch with the next release candidate tag.
- [x] Updated all version information in the documentation on the relevant release branch.
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version.
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel..
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [registry.upbound.io] for all getting started packages.
  - [x] `xp/getting-started-with-aws`
  - [x] `xp/getting-started-with-with-with-vpc`
  - [x] `xp/getting-started-with-azure`
  - [x] `xp/getting-started-with-gcp`
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel.
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes.
- [ ] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack
  - [ ] Twitter
- [x] Updated the [releases table] in the `README.md` on `master`.
- [x] Updated the current release version in the [Crossplane docs website repo].
- [x] Updated the release branch reaching EOL with [docs removal directive].
- [x] Request @jbw976 to remove the EOL docs version from Google Search

[releases.crossplane.io]: https://releases.crossplane.io
[registry.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new
[releases table]: https://github.com/crossplane/crossplane#releases
[Crossplane docs website repo]: https://github.com/crossplane/crossplane.github.io
[docs removal directive]: https://github.com/crossplane/crossplane/pull/3003
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.7]: https://github.com/crossplane/crossplane/issues/2977
[Code Freeze]: https://crossplane.io/docs/master/reference/release-cycle.html#code-freeze

**Comment by negz** [comment]
Release branch: https://github.com/crossplane/crossplane/tree/release-1.9

**Comment by negz** [comment]
v1.10.0-rc.0 tag

* Workflow: https://github.com/crossplane/crossplane/actions/runs/2619891663
* Tag: https://github.com/crossplane/crossplane/releases/tag/v1.10.0-rc.0

**Comment by negz** [comment]
Not really related to the v1.9 release but I'm dropping a mental note for myself that I also need to cut patch releases for 1.6, 1.7, and 1.8 for https://github.com/crossplane/crossplane/issues/3113.

**Comment by negz** [comment]
I unfortunately don't have the bandwidth to get to this today so this is going to slip.

**Comment by negz** [comment]
Tag action run: https://github.com/crossplane/crossplane/runs/7352010343?check_suite_focus=true
Tag: https://github.com/crossplane/crossplane/releases/tag/v1.9.0

**Comment by negz** [comment]
CI action run: https://github.com/crossplane/crossplane/actions/runs/2674618883

**Comment by negz** [comment]
Artifacts: https://releases.crossplane.io/build/release-1.9/v1.9.0/

**Comment by negz** [comment]
Configurations action run: https://github.com/crossplane/crossplane/actions/runs/2674670598

**Comment by negz** [comment]
Configurations:

* https://marketplace.upbound.io/configurations/xp/getting-started-with-gcp/v1.9.0
* https://marketplace.upbound.io/configurations/xp/getting-started-with-azure/v1.9.0
* https://marketplace.upbound.io/configurations/xp/getting-started-with-aws/v1.9.0
* https://marketplace.upbound.io/configurations/xp/getting-started-with-aws-with-vpc/v1.9.0

**Comment by negz** [comment]
Promote action run: https://github.com/crossplane/crossplane/actions/runs/2674676481

**Comment by negz** [comment]
Promoted artifacts: https://releases.crossplane.io/stable/v1.9.0/

**Comment by negz** [comment]
Release: https://github.com/crossplane/crossplane/releases/tag/v1.9.0

**Comment by negz** [comment]
Release table PR: https://github.com/crossplane/crossplane/pull/3187

**Comment by negz** [comment]
> Request @jbw976 to remove the EOL docs version from Google Search

@jbw976 I'm going to assign you to close this one out if you don't mind.

**Comment by jbw976** [comment]
All done with the requeest to remove the 1.6 docs (prefix `https://crossplane.io/docs/v1.5`) from google search! 💪

**Comment by jbw976** [comment]
Twitter tweet has been tweeted: https://twitter.com/crossplane_io/status/1547926460341428224
