### ISSUE TITLE
Ability to add labels to connection secret

### ISSUE THREAD

**Issue by agracey** [crossplane/crossplane#3201]
### What problem are you facing?

When I run through the getting started guide, I find that the secret that gets created doesn't have any labels propagated to it. 

We would like to be able to add labels to my connection secret that get created via writeConnectionSecretToRef. This would allows us to integrate with our developer platform better since we could account for the secrets and mount them into applications automatically.

### How could Crossplane help solve your problem?

It would be awesome if there was an additional labels field under writeConnectionSecretToRef that got added to the secret:

```
  writeConnectionSecretToRef:
    name: db-conn
>   labels:
>     my-label: my-value
```

**Comment by turkenh** [comment]
Hi @agracey,

This is already possible with the new `PublishConnectionDetailsTo` [API](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md#api) which is alpha right now and disabled by default. 

```
spec:
  publishConnectionDetailsTo:
    name: db-conn
    metadata:
      labels:
        environment: production
```

`writeConnectionSecretToRef` API is planned to be deprecated in favor of `PublishConnectionDetailsTo`, hence no changes/improvements should be expected there.

**Comment by turkenh** [comment]
To enable the alpha feature you would need to pass `--enable-external-secret-stores` to both Crossplane and provider pods ATM.

**Comment by agracey** [comment]
Thank you so much for you quick reply!
