### ISSUE TITLE
compositionRef will not get updated on updating compositionSelector in claim

### ISSUE THREAD

**Issue by deepakal** [crossplane/crossplane#3214]
### What happened?
On updating set of labels under compositionSelector in Claim, resulting in XR object updated with new  "Composition Selector" value but "Composition Ref" still pointing to old composition. Because of this managed resource are not taking latest changes from updated/new composition.

### How can we reproduce it?
1) Created two different composition, change in name and Label but both are pointing to same compositeTypeRef XNamespaceRole.example.org

composition 1

```apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnamespaceroles.example.org.v1
  labels:
    provider: crossplane-composition1
```

composition 2

```apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnamespaceroles.example.org.v2
  labels:
    provider: crossplane-composition2
```

2) Apply both composition (kubectl apply -f composition<1/2>.yaml)

3) Create and apply the Claim 
 
```apiVersion: example.org/v1
kind: NamespaceRole
metadata:
  name: my-ns
spec:
  parameters:
    name: mynamespace
  compositionSelector:
    matchLabels:
      **provider:crossplane-composition1**
```
4) kubect describe xnamespaceroles return 

```Spec:
  Claim Ref:
    API Version:  ncom.example.org/v1
    Kind:         NamespaceRole
    Name:         my-ns
    Namespace:    default
  Composition Ref:
    Name:  **xnamespaceroles.example.org.v1**
  Composition Selector:
    Match Labels:
      Provider:            **crossplane-composition1**
  Composition Update Policy:  Automatic
  Parameters:
    Name:  mynamespace
  Resource Refs:
    API Version:  kubernetes.crossplane.io/v1alpha1
    Kind:         Object
    Name:         mynamespace
```
5) Update claim with new label as below

```apiVersion: example.org/v1
kind: NamespaceRole
metadata:
  name: my-ns
spec:
  parameters:
    name: mynamespace
  compositionSelector:
    matchLabels:
      **provider:crossplane-composition2**
```
6) kubect describe xnamespaceroles return 

```Spec:
  Claim Ref:
    API Version:  ncom.example.org/v1
    Kind:         NamespaceRole
    Name:         my-ns
    Namespace:    default
  Composition Ref:
    Name:  **xnamespaceroles.example.org.v1**
  Composition Selector:
    Match Labels:
      Provider:            **crossplane-composition2**
  Composition Update Policy:  Automatic
  Parameters:
    Name:  mynamespace
  Resource Refs:
    API Version:  kubernetes.crossplane.io/v1alpha1
    Kind:         Object
    Name:         mynamespace
```

**Excepted:**

- Once executed "kubect describe xnamespaceroles " was excepting that both "Composition Selector" and "Composition Ref" will be pointing to new composition. 

**Crossplane behaviour:** 

- Only "Composition Selector" update to new label "provider:crossplane-composition2" but "Composition Ref" still pointing to old composition name **"xnamespaceroles.example.org.v1"** instead of **"xnamespaceroles.example.org.v2"**

### What environment did it happen in?
Crossplane version:  
crossplane/crossplane:v1.8.0

* Kubernetes version (use `kubectl version`):
 Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by negz** [comment]
This is by design - a set reference takes precedence over a selector. I believe this pattern is fairly idiomatic in Kubernetes - e.g. node selectors - and it's tricky to have this work another way. If the selector labels match multiple resources for example we'd be at risk of updating the reference to point to a different one every reconcile.

**Comment by deepakal** [comment]
> 

Thanks for clarification..... Then how crossplane choose the composition  for the very first time if it finds more than one by matching selector labels? Is there any weight mechanism that can be attached with composition or its random?

**Comment by negz** [comment]
> Is there any weight mechanism that can be attached with composition or its random?

It's random, but I like the idea of a weight mechanism - I would suggest opening a new issue requesting that feature.

**Comment by dee-kryvenko** [comment]
I am confused @negz.

Let's say we have a composition A, and we want to make a breaking change to it. We would have to produce a new version, and of course - not everybody will update to it immediately, so for some time we will need to maintain **both versions** and make changes to both separately.

Looking at https://docs.crossplane.io/knowledge-base/guides/composition-revisions/, this does not seem to be possible. To produce a new composite revision, one would have to override composition. Two compositions cannot exist in the same time. This makes it impossible to maintain two or more major versions of the same composition.

That becomes a catch 22, especially i a GitOps tool used for delivering changes (like ArgoCD).

So the only logical step is to publish a new composition B with a different set of labels.

This is such arbitrary limitation, and there is nothing tricky about it. Node selector represents a node, and live pod with containers cannot be just moved to another node. XR and compositions are nothing but set of keys and values in etcd. Of course XR can be changed to use another composition, just like it can be changed to use another composition revision.

And if you disagree, just tell me how we can maintain more than one conflicting version of a composition simultaneously and have users switch between them.

**Comment by dee-kryvenko** [comment]
> If the selector labels match multiple resources for example we'd be at risk of updating the reference to point to a different one every reconcile.

That would be an operator error in my opinion, but I don't really care about that scenario. What I do care about is if I update my XR so that it's new `compositionSelector` cannot possibly match current `compositionRevisionRef`. There is not a multi-match, there is a zero match. That ok?

Even if I explicitly remove `compositionRevisionRef` manually, or dare I say - manually override it to what I proclaim to be a new match by my rules - what do you think, it just reverts it back and pretends this conflicting state is actually healthy. How can that state be defined as `status: "True"` on `ReconcileSuccess`?

**Comment by dee-kryvenko** [comment]
Aha, the lattes seems to be because I need to update compositionRevisionRef manually on the claim, not XR. But my point still stands.

**Comment by bobh66** [comment]
> And if you disagree, just tell me how we can maintain more than one conflicting version of a composition simultaneously and have users switch between them.

@dee-kryvenko I think what you're looking for is `compositionUpdatePolicy: Manual` which allows you to modify existing Compositions (which creates new CompositionRevisions) without affecting currently deployed Composite.  You can choose to manually update an existing Composite to a new CompositionRevision by changing the `compositionRevisionRef.name` in the Composite to the new revision identifier.

You can use `defaultCompositionUpdatePolicy` in the XRD to set the default value used by the claim if the user does not specify a `compositionUpdatePolicy`.

https://docs.crossplane.io/knowledge-base/guides/composition-revisions/#using-composition-revisions

**Comment by dee-kryvenko** [comment]
No, I am not looking for `compositionUpdatePolicy: Manual`. I am looking for composition channels such as stable and develop, which documentation even makes a case for, except that there is no easy way for the users at the moment to switch between the channels (other than manually updating the ref), and there is no easy way to maintain multiple channels simultaneously. It is really simple to grasp if you think in terms of channels more like SemVer, i.e. you have multiple MAJOR versions that you need to maintain, while users need to be able to switch between major versions, while also getting automatic minor/patch updates. Equivalent of a `~> X.Y` SemVer expression.

**Comment by bobh66** [comment]
OK - please open an enhancement/feature request issue and provide the specific scenario/workflow you would like to have supported.

**Comment by dee-kryvenko** [comment]
https://github.com/crossplane/crossplane/issues/5489
