### ISSUE TITLE
Examples in Documentation like Terraform

### ISSUE THREAD

**Issue by kderck** [crossplane/crossplane#3226]
### What problem are you facing?

I am using Crossplane for the first time and I have found it hard to adopt due to lack of examples in the documentation. It would be nice to see examples like Terraform, and what are acceptable values would be. I can see you have examples in this repository, but these really should be in the documentation 

EDIT: I've noticed I've opened this in the wrong place. However, I meant the crossplane aws provider.

**Comment by ytsarev** [comment]
Examples can be exposed in the Marketplace, e.g. see Examples section in  https://marketplace.upbound.io/providers/upbound/provider-aws/v0.7.0/resources/ec2.aws.upbound.io/VPC/v1beta1

**Comment by KylePeterDavies** [comment]
@ytsarev So what should I use the `API Documentation` or the `Upbond Marketplace`? Also why are most the descriptions empty?

<img width="1792" alt="Screenshot 2022-08-13 at 03 59 55" src="https://user-images.githubusercontent.com/12613678/184465984-e8458c87-4d13-4d60-b397-7e0851a7ab70.png">

**Comment by KylePeterDavies** [comment]
![Uploading Screenshot 2022-08-13 at 04.14.48.png…]()

**Comment by KylePeterDavies** [comment]
<img width="1792" alt="Screenshot 2022-08-13 at 04 15 54" src="https://user-images.githubusercontent.com/12613678/184466429-ca1b7f49-c40d-4639-9c21-0ad78e4a1656.png">

**Comment by KylePeterDavies** [comment]
<img width="1792" alt="Screenshot 2022-08-13 at 04 14 48" src="https://user-images.githubusercontent.com/12613678/184466440-b39f9420-7f09-4106-87cb-919caa4e0a3e.png">

**Comment by ytsarev** [comment]
@KylePeterDavies better field documentation to API fields is coming soon. You are free to choose between community doc.crds.dev and vendor-backed https://marketplace.upbound.io/. I just pointed out that Upbound Marketplace has already embedded tested Examples which I personally find very useful in practice.
