### ISSUE TITLE
Need namespace-scoped resources

### ISSUE THREAD

**Issue by mvkrishna86** [crossplane/crossplane#3237]
### What problem are you facing?
I am able to create the AWS infrastructure using crossplane. But all the resources in kunernetes are global. 
I have 5-6 environments to be configured, and if we can create the resources as namespace-scoped, I can use one namespace for each environment. 

### How could Crossplane help solve your problem?
Please make the k8s resources namespace scoped.

**Comment by negz** [comment]
Hi @mvkrishna86. It sounds like you might be using provider-aws managed resources directly. I recommend you instead look into using a Composite Resource Claim (XRC), which is a namespaced resource that can be composed of managed resources. See https://crossplane.io/docs/v1.9/concepts/composition.html for more information.

At this stage we're not likely to make managed resources namespaced.
