### ISSUE TITLE
Allow resource access only to the consuming workload

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#324]
In the interest of expediency, some resources automatically created by the crossplane controllers are created with very open rules allowing inbound access from anywhere.  The controllers should be smarter about the specific inbound access allowed so that only the workloads that will consume them are allowed access.  This is a critical security feature and is vital for to move towards production ready.

Some examples:
* https://github.com/crossplaneio/crossplane/blob/master/pkg/clients/azure/sql.go#L208-L213
* https://github.com/crossplaneio/crossplane/blob/release-0.1/pkg/controller/gcp/database/cloudsql_instance.go#L254-L257
* https://github.com/crossplaneio/crossplane/blob/release-0.1/docs/workloads/aws/wordpress-aws.md#create-an-rds-security-group-example-only

**Comment by bassam** [comment]
any chance we can bump this to v0.2?

**Comment by negz** [comment]
We're deprecating KubernetesApplication (neé Workload), so I don't think this will be relevant going forward.

Furthermore, we have few to no resources left that allow broad access by default. Almost all resources are high fidelity representations of their underlying APIs, and thus support all security configurations of said APIs.
