### ISSUE TITLE
No feedback when installing missing provider version

### ISSUE THREAD

**Issue by jond3k** [crossplane/crossplane#3266]
### What happened?

I tried to install a version of `crossplane/provider-jet-gcp` that doesn't exist. The command is accepted but never shows any feedback in the logs or created provider resource.

### How can we reproduce it?

1. Run `kubectl crossplane install provider crossplane/provider-jet-gcp:v0.3.0-rc` (Note that a correct version would be [crossplane/provider-jet-gcp/v0.3.0-rc.35.g40c122f](https://hub.docker.com/layers/provider-jet-gcp/crossplane/provider-jet-gcp/v0.3.0-rc.35.g40c122f/images/sha256-296d0eb7fafe7caadb0ffbec170db2a42f922ec522e06eb0c731c7d66780b461?context=explore))
2. Check provider status with `kubectl get providers`: The installed/healthy flags are missing
3. Check internal logs with `kubectl logs -l release=crossplane -n crossplane-system --all-containers --tail=-1`: No errors

```
NAME                          INSTALLED   HEALTHY   PACKAGE                                 AGE
crossplane-provider-gcp       True        True      crossplane/provider-gcp:v0.21.0         3h26m
crossplane-provider-jet-gcp                         crossplane/provider-jet-gcp:v0.3.0-rc   27s
```

### What environment did it happen in?

* Crossplane: v1.9.0
* Cloud provider: GCP
* Client Version: v1.24.1 
* Server Version: v1.22.10-gke.600
* Distro: GKE Autopilot

**Comment by ytsarev** [comment]
Can you try the following
* `kubectl describe providers crossplane-provider-jet-gcp`

* `kubect get providerrevisions` and then `describe` the associated `providerrevisions`

**Comment by jond3k** [comment]
1. `kubectl describe providers crossplane-provider-jet-gcp` shows an error
2. There's no associated revision.

So actually I think the status message is enough to see why there's a problem though maybe there should be feedback in the `get` table too?

```
kubectl describe providers crossplane-provider-jet-gcp
Name:         crossplane-provider-jet-gcp
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  pkg.crossplane.io/v1
Kind:         Provider
Metadata:
  Creation Timestamp:  2022-08-29T15:16:02Z
  Generation:          1
  Managed Fields:
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:ignoreCrossplaneConstraints:
        f:package:
        f:packagePullPolicy:
        f:revisionActivationPolicy:
        f:revisionHistoryLimit:
        f:skipDependencyResolution:
    Manager:         kubectl-crossplane
    Operation:       Update
    Time:            2022-08-29T15:16:02Z
  Resource Version:  4554567
  UID:               8ac22b32-456b-4747-940d-61b07580ab8a
Spec:
  Ignore Crossplane Constraints:  false
  Package:                        crossplane/provider-jet-gcp:v0.3.0
  Package Pull Policy:            IfNotPresent
  Revision Activation Policy:     Automatic
  Revision History Limit:         0
  Skip Dependency Resolution:     false
Events:
  Type     Reason         Age                From                                 Message
  ----     ------         ----               ----                                 -------
  Warning  UnpackPackage  33s (x7 over 97s)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: HEAD https://index.docker.io/v2/crossplane/provider-jet-gcp/manifests/v0.3.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
```

```
kubectl get providerrevisions
NAME                                   HEALTHY   REVISION   IMAGE                             STATE    DEP-FOUND   DEP-INSTALLED   AGE
crossplane-provider-gcp-897a5469eb94   True      1          crossplane/provider-gcp:v0.21.0   Active                               4d21h
```
