### ISSUE TITLE
patchSet - patch from literal value

### ISSUE THREAD

**Issue by natereid72** [crossplane/crossplane#3270]
When repeating a static value multiple times, at the same path in a Composition (e.g. spec.forProvider.location), it would be useful if we could patch the literal value from a single patchSet. This will reduce the chances of making a mistake when changing things like region in a Composition and make it easier.

Proposed:

```yaml
  patchSets:
  - name: region
    patches:
    - type: fromLiteral
      fromLiteral: "US East"
      toFieldPath: spec.forProvider.location
```

**Comment by Santosh1176** [comment]
Hey @negz can I work on this?
To have some context, is this about `patchStrategy` tag on `patchSets`?

**Comment by MisterMX** [comment]
@Santosh1176 I guess you can work on this. Though I think this is not about `patchStrategy` (do we have this field?) and more about patches and a new patch type in general.

**Comment by Santosh1176** [comment]
Thanks for clarifying @MisterMX. Is this about adding a new patch type `fromLiteral` and Apply functionality to it? Sorry, if I am asking for too much.

**Comment by MisterMX** [comment]
Judging from the provided example, I would say yes.

Although, I think we should support other datatypes as well, not just strings. Maybe with a `fromValue` patch that can store any kind of [JSON](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1#JSON) data:

```yaml
- type: fromValue
  fromValue: "my-string" # string
- type: fromValue
  fromValue: 2           # number
- type: fromValue
  fromValue: true        # bool
- type: fromValue
  fromValue: [1, 2, 3]   # array
- type: fromValue
  fromValue:             # object
    hello: world

**Comment by natereid72** [comment]
> Thanks for clarifying @MisterMX. Is this about adding a new patch type fromLiteral and Apply functionality to it? Sorry, if I am asking for too much.

To clarify @Santosh1176, this is intended to be a simple method of defining a value within a Composition that is not passed from XR. Example I provided is for a cloud region. It could be for any value that is used repeatedly in a Composition that is not fed from a Claim.

**Comment by ytsarev** [comment]
@natereid72 How is it different from keeping the default value in `base`?

**Comment by bobh66** [comment]
@ytsarev I had the same question, but I realized it's possible to need the same constant value in many resources, which is fine until you need to change it and use search/replace, which may cause other issues during the editing process.

It would be good to get #3007 merged - it would be very useful for this scenario and many others.

**Comment by natereid72** [comment]
@bobh66 Agreed that #3007 could be a solution for this as well. However, I have been seeing 3007 as a way to pass a value from one instance of a Composition to a another later on (e.g. I need something like a cluster oicd url in a helm chart that is deployed post cluster). I see this issue/proposal as a constraint to a single Composition run. For that reason, having a simple patchSet method from a patchSet defined in Composition would be easier and require fewer moving parts.

@ytsarev The way I have been looking at it is for common path definitions used perhaps 20 - 30 times across resource templates within a single base Composition (e.g. Region, PrivuderConfig, etc.). As @bobh66 mentions, it is the copy and replace method that I have seen multiple people run into issues with. It seems very analogous to the reasons patchSet was implemented as it is today already.

**Comment by ytsarev** [comment]
@bobh66 @natereid72 got it, so it is about developer experience and keeping the definition DRY with new 
` type: fromValue` together with the `patchSet`

That totally makes sense! Thanks a lot for helping me understand it, folks :)

**Comment by mithie** [comment]
We would highly appreciate if we had a patchSet that allowed us to use literal values. This could save a lot of redundant code if we'd like to pass values i.e. from multiple compositions to other nested compositions.

**Comment by bobh66** [comment]
The EnvironmentConfig alpha feature in 1.11 (#3007) is one way to do this - you can create an EnvironmentConfig resource with your constant values, include the environmentConfig in the composition, and reference the environment constants in a patchset.

**Comment by natereid72** [comment]
That would be great @AhmedGrati. I'm not sure how the others feel about this with the intro of EnvironmentConfig, but I'd still love to have it as an option. To me, EnvironmentConfig for this case is another thing that needs to be put in place per control plane that results in less DRY.

**Comment by bobh66** [comment]
I just thought of another way to do this today, though it's definitely a kludge - define `spec.contants.foo` in the XRD and assign `foo` the default value that you want the constant to be, and also make it an enum that only supports that value so it can't be changed to anything else.  Then have the patchSet retrieve the value from `spec.constants.foo`.  I know it exposes the constant value in the XRD which is undesirable, but it would at least be functional until this change is available.

**Comment by natereid72** [comment]
:) You're reaching out there  now Bob!

**Comment by SD-13** [comment]
Hi!, I would love to give it a try.

**Comment by ytsarev** [comment]
I encountered a case where I really need just a simple static value for the Database `metadata.name`

I did workaround it with `match/regexp` transform:
```
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
            - type: match
              match:
                patterns:
                  - type: regexp
                    regexp: '.*'
                    result: upbound
```
The result of the transform will be always `upbound` .
Hackish but works :) 

Full example is at https://github.com/upbound/platform-ref-azure/blob/main/package/database/sqlinstance/composition-mariadb.yaml#L102-L110

**Comment by mithie** [comment]
@ytsarev , thanks for providing this solution that worked for us as well! However, we would appreciate if there was an official solution provided by Crossplane since we are using this in different places. Having patches for literal values at hand could save a lot of time fiddling around with workaround solutions. Also, I like the idea of @MisterMX of supporting different data types.

**Comment by Pati93** [comment]
Hi all,
I would like to start working on this. Is it still needed/relevant?

**Comment by bobh66** [comment]
In 1.14 it it will be possible to do this using the `environment` `initData` section, where you can specify constant data definitions that can then be patched into resources using `FromEnvironmentFieldPath` as needed.

https://github.com/crossplane/crossplane/pull/4555

I don't know if it is still necessary to implement this as a separate feature.  @natereid72 ?
