### ISSUE TITLE
Encourage Kubernetes clients to bump discovery rate limits to 300+ rps

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3272]
### What problem are you facing?

Kubernetes struggles when you install a lot of CRDs (e.g. 1,000+), which Crossplane users regularly do. One of the issues is primarily client-side, in that the client-go "discovery client" will attempt to walk the tree of APIs offered by the API server, but will rate limit itself while doing so. This causes some commands (e.g. `kubectl get pods`) to block for a long time while discovery happens. You can read more about this at https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds/.

These rate limits [were raised](https://github.com/kubernetes/kubernetes/pull/105520) from 100rps burst to 300rps burst in kubectl 1.22. The 300rps burst was [made the default](https://github.com/kubernetes/kubernetes/pull/109141) in the latest client-go release, v0.25.0. Per https://github.com/kubernetes/kubernetes/issues/111880 there is discussion of removing the rate limits entirely, instead relying on [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) to protect the API server from noisy clients. At least one tool - kpt - has currently done this per https://github.com/GoogleContainerTools/kpt/pull/3368.

### How could Crossplane help solve your problem?

We could help our community avoid these issues by reaching out to popular Kubernetes tools that might be used alongside Crossplane and requesting that they bump their discovery client rate limits. They could do this by:

* Updating to client-go v0.25.0 or greater to take advantage of the new 300rps default.
* Manually specifying a burst of 300rps or higher.
* Replicating the pattern established by https://github.com/GoogleContainerTools/kpt/pull/3368 to disable rate limits completely.

**Comment by negz** [comment]
I'm assigning this to myself, since I expect the work here to primarily be asking other projects to bump their rate limits. I'm planning to use this issue to link back to the various projects with context.

**Comment by negz** [comment]
Some initial projects that come to mind:

* Helm
* ArgoCD
* Flux
* kuttl

**Comment by jessesuen** [comment]
Thanks for the heads up @negz. I took a look at what we're doing in Argo CD.

Our default Client QPS is 50 which is overridable with `ARGOCD_K8S_CLIENT_QPS` env var to controller.
https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/cluster_constants.go#L42

We do not have a separate control for discovery QPS, and so we end up using the same QPS value for discovery:
```
https://github.com/argoproj/gitops-engine/blob/1c4ef336872ce4f30cf2b9134e7f8bcf57c3c813/pkg/utils/kube/resource_ops.go#L141
```

Second, I know of an outstanding issue with Argo CD in that Argo CD is not making full use of the discovery cache, which is provided in the client-go. And so we end up making discovery API calls more frequently than we should be. There's an open issue for it https://github.com/argoproj/gitops-engine/issues/451. It should get fixed soon, but it might land in a Argo CD v2.5 release and not v2.4.

I just wanted to document my findings here, to make folks aware that there *are* some tuning options available in case Argo CD users are hitting issues with high number of Crossplane resources. Users can set `ARGOCD_K8S_CLIENT_QPS` to some high value.

But ideally Argo CD should:
1. Bump up the default for discovery from 50, especially since this value is lower than the kubernetes default for discovery.
2. Properly leverage the discovery cache

**Comment by negz** [comment]
I note that Flux has bumped too: https://github.com/fluxcd/flux2/blob/v0.35.0/go.mod#L46

So I believe all the projects noted here are now covered, modulo the potential further improvements @jessesuen mentioned. I'm going to close this.

**Comment by negz** [comment]
@MisterMX can you share your rationale about keeping this open? I was about to close it.

This issue doesn't track the entire CRD scaling effort, but rather nudging popular Kubernetes clients to update their client-side rate limits. Anyone who has bumped to client-go 0.26 or above should get this. Are you aware of any clients that are worth us explicitly chasing down?

**Comment by uvegla** [comment]
@negz I feel like increasing limits for discovery in `client-go` was a good but unreliable move in the near / mid term the least.

You mentioned above Flux upgrading `client-go` already. We are using Flux `v0.37.0`, which uses `helm-controller` version `v0.28.1`. We experience a lot of client-side throttling in it affecting our HelmReleases timing out / getting stuck (Helm underneath experiencing similar issues could also make it worse, but it is clearly visible on the controller).

Luckily most Flux controllers have: `--kube-api-qps` (default 50) and `--kube-api-burst` (default 100) ([helm-controller options docs](https://fluxcd.io/flux/components/helm/options/)). We did set these by doubling the values and still experience the throttling issues. I recently bumped burst to 300 to conform the above values, will get back when I have more data on that.

Now looking at the Flux code that is not an outdated piece of document. They also upgraded `client-go` to `v0.26.1` in the latest release, still check this trail:

- https://github.com/fluxcd/helm-controller/blob/v0.29.0/go.mod#L24
- https://github.com/fluxcd/pkg/blob/runtime/v0.27.0/runtime/client/client.go#L59-L65
- https://github.com/fluxcd/helm-controller/blob/v0.29.0/internal/kube/client.go#L121-L124

I am hesitant to open a pull request to upgrade the values (might gonna do it anyway for discussion), but my point is that there is no way that each and every possible tool should be adjusted for the case if you run it in a cluster with crossplane or not. Just why should they care? The best they could do is to expose configuration to control these limits. From the perspective of the users of these tools however it would take upgrading / reconfiguring all components in a given cluster to adjust to the changed environment heavily effected by crossplane. Which can be a huge undertaking, thinking you might have legacy components running there or tools that do not have support yet or are not maintained anymore. I get that it is not nice, but quite possibly the reality. Compared to the huge effort it would take it is also not really solving the issue, just possibly making it more bearable by running into less throttling. And beyond that I don't know how it would effect especially large clusters if the limits were really increased everywhere.

In short, I think it will take a long time for these changes to properly / reliably propagate through the Kubernetes landscape, but then there still is the issue / effort required from the users side.

Another option I was thinking of from user side is to isolate crossplane to a cluster of its own, but it may not be a popular idea cost saving wise and people would possible need to duplicate a lot of other components (e.g. IRSA) and secrets maybe (e.g. ESO) which they might already have set up in a working, maintained, secured cluster. Plus for some people it may also mean updating VPN settings, audits, etc.

These kind of pushes me more towards: https://github.com/crossplane/crossplane/issues/2869#issuecomment-1331173040 of splitting up providers per API or conveniently filtering out the CRDs to install and manage.

**Comment by negz** [comment]
> I am hesitant to open a pull request to upgrade the values (might gonna do it anyway for discussion), but my point is that there is no way that each and every possible tool should be adjusted for the case if you run it in a cluster with crossplane or not. Just why should they care?

I don't think "please accommodate Crossplane" is the best way to think about this. Instead, I would say that most clients that are built on cilent-go have needlessly and artificially low client-side rate limits. I believe the correct solution here is to actually remove these rate limits entirely and trust AP&F per https://github.com/kubernetes/kubernetes/issues/111880. Crossplane is the forcing function right now, but this needs to be done regardless. If CRDs and tools that use them continue to be popular other folks will hit these issues soon.
