### ISSUE TITLE
Cut v1.10.0 on October 18, 2022

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#3277]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.7] for
examples of each step.

- [x] Prepare the release branch at the beginning of [Code Freeze]:
  - [x] Created the release branch: https://github.com/crossplane/crossplane/tree/release-1.10
  - [x] Created and merged an empty commit to the `master` branch: https://github.com/crossplane/crossplane/pull/3368
  - [x] Run the [Tag workflow][tag-workflow] on the `master` branch with the next release candidate tag: https://github.com/crossplane/crossplane/actions/runs/3235139458
- [x] Updated all version information in the documentation on the relevant release branch. https://github.com/crossplane/crossplane/pull/3395
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version.
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel..
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [registry.upbound.io] for all getting started packages.
  - [x] `xp/getting-started-with-aws`
  - [x] `xp/getting-started-with-with-with-vpc`
  - [x] `xp/getting-started-with-azure`
  - [x] `xp/getting-started-with-gcp`
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel.
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes.
- [x] Update the [`crossplane/test` repo test workflows][crossplane-test-workflows] to ensure the checkout release branch and helm install version(s) point at the new release https://github.com/crossplane/test/pull/33
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack
  - [ ] Twitter

[releases.crossplane.io]: https://releases.crossplane.io
[registry.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new
[releases table]: https://github.com/crossplane/crossplane#releases
[Crossplane docs website repo]: https://github.com/crossplane/crossplane.github.io
[docs removal directive]: https://github.com/crossplane/crossplane/pull/3003
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[crossplane-test-workflows]: https://github.com/crossplane/test/tree/master/.github/workflows
[release-1.7]: https://github.com/crossplane/crossplane/issues/2977
[Code Freeze]: https://crossplane.io/docs/master/reference/release-cycle.html#code-freeze

**Comment by jbw976** [comment]
@muvaf we had decided to move to a quarterly release cycle: https://github.com/crossplane/crossplane/issues/2890#issuecomment-1184752236

we've been tracking a date of Oct 18th for 1.10 in the community meetings: https://docs.google.com/document/d/1q_sp2jLQsDEOX7Yug6TPOv7Fwrys6EwcF5Itxjkno7Y/edit#heading=h.razvwktquxbn

sorry for the trouble, can you please help get these release plans and calendars aligned with those dates? i.e. i think we should stick to the quarterly plan and date of Oct 18th we'd been communicating in the community meetings. :)

**Comment by muvaf** [comment]
@jbw976 thanks for the heads-up! I closed the empty commit PR but couldn't delete the release branch since code freeze is on October 11th. @negz could you delete `release-1.10`?

**Comment by negz** [comment]
@muvaf I just took a look and don't see `release-1.10` so I'm guessing someone else beat me to it.

**Comment by jbw976** [comment]
looks like release-1.10 branch still exists: https://github.com/crossplane/crossplane/commits/release-1.10

But it looks like it's from 2020 and It has the same exact commits that [release-0.10](https://github.com/crossplane/crossplane/tree/release-0.10) has - perhaps it was created by mistake back then?

The delete button looks to be disabled though, so I'm not able to delete it.  Not sure why that is just yet 🤔 
<img width="999" alt="Screen Shot 2022-09-05 at 4 59 05 PM" src="https://user-images.githubusercontent.com/4313439/188521990-1b9b4914-af53-42b9-ab79-877a995ee53e.png">

**Comment by jbw976** [comment]
Aha, deletions of release branches was not enabled in the [branch protection rules](https://github.com/crossplane/crossplane/settings/branches). I temporarily enabled that, deleted the release-1.10 branch in the [UI](https://github.com/crossplane/crossplane/branches/all), then disabled branch deleting again to restore the branch protection rules back to the way they were.

The [release-1.10 branch](https://github.com/crossplane/crossplane/commits/release-1.10) has been deleted, it no longer shows up in the branches UI query: https://github.com/crossplane/crossplane/branches/all?query=release-1.10

**Comment by negz** [comment]
I'd like to make a code-freeze exception for https://github.com/crossplane/crossplane/pull/3321 if possible (i.e. make sure it's included in this release).

**Comment by muvaf** [comment]
Done! https://github.com/crossplane/crossplane/releases/tag/v1.10.0
