### ISSUE TITLE
Helm chart missing license

### ISSUE THREAD

**Issue by mckenzig** [crossplane/crossplane#3283]
### What problem are you facing?
Hi I am working with an enterprise which requires helm charts to be onbarded to in internal repository. The onboarding process requires the chart to have a license declared as defined here:

https://helm.sh/docs/topics/charts/

The onboarding is complaining that a license is not included in the crossplane chart 1.10.0-rc.0.112.g83356388 I am onboarding

Looking at github, I do not see a license file in the chart:

https://github.com/crossplane/crossplane/tree/5bfba85669acbf8758d0698ce325533be44f4520/cluster/charts/crossplane

### How could Crossplane help solve your problem?
Could you consider including a license file in the chart to enable using crossplane in organizations that require license declaration.

Thanks.

**Comment by Santosh1176** [comment]
Can I work on this by adding the Licence to the chart?

**Comment by mckenzig** [comment]
@Santosh1176 @negz Modify the helm makefile to copy the license into the help package before pushing it?
