### ISSUE TITLE
Claim: Composite Name is regenerated if `spec.resourceRef.name` is set

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#3286]
### What happened?

The reference to the composite resource in the claim is stored at `spec.resourceRef`. When the composite is deleted by the user, Crossplane will try to create a new composite - **always with a new name**. This, however, will fail because the resource reference still exists with the old name the controller will fail with the message
```
cannot bind claim that references a different composite resource
```

### How can we reproduce it?

1. Claim a composition
2. Delete the composite resource

### What environment did it happen in?

Crossplane version: 1.9.0

**Comment by sanketgawade** [comment]
is there a workaround for this issue ?

**Comment by turkenh** [comment]
> is there a workaround for this issue ?

You can delete `spec.resourceRef` in your claim as a workaround.

**Comment by turkenh** [comment]
>  When the composite is deleted by the user, Crossplane will try to create a new composite - always with a new name.

This is because the claim controller sets `metadata.generatename` and lets the API server return an available name for the composite. With that said, I believe is fair to expect "not generating a new name" when `spec.resourceRef` is set 👍

**Comment by jbw976** [comment]
Is this behavior still happening in v1.15+? 🤔
