### ISSUE TITLE
rbac manager pod crashes with leader election error on google cloud

### ISSUE THREAD

**Issue by dee0sap** [crossplane/crossplane#3293]
### What happened?
We are deploying to clusters on Azure, AWS and GCP.
On GCP we are seeing that the rbac manager pod exits periodically and unexpectedly.   It could run for hours or a few days before exiting.

```
We are seeing this pattern of messages prior to exiting :
2022-08-30 13:51:47	I0830 13:51:47.647458       1 leaderelection.go:258] successfully acquired lease mc-provisioner/crossplane-leader-election-rbac
2022-08-30 13:51:29	I0830 13:51:29.738933       1 leaderelection.go:248] attempting to acquire leader lease mc-provisioner/crossplane-leader-election-rbac...
2022-08-30 13:51:16	I0830 13:51:16.267105       1 request.go:665] Waited for 1.046205241s due to client-side throttling, not priority and fairness, request: GET:[https://api.centaur-dmi.hc-dev.internal.canary.k8s.ondemand.com:443/apis/admissionregistration.k8s.io/v1?timeout=32s](https://api.centaur-dmi.hc-dev.internal.canary.k8s.ondemand.com/apis/admissionregistration.k8s.io/v1?timeout=32s)
2022-08-30 13:51:13	crossplane: error: cannot start controller manager: leader election lost
2022-08-30 13:51:13	I0830 13:51:13.951284       1 leaderelection.go:283] failed to renew lease mc-provisioner/crossplane-leader-election-rbac: timed out waiting for the condition
2022-08-30 13:51:13	E0830 13:51:13.951157       1 leaderelection.go:330] error retrieving resource lock mc-provisioner/crossplane-leader-election-rbac: Get "[https://api.centaur-dmi.hc-dev.internal.canary.k8s.ondemand.com:443/apis/coordination.k8s.io/v1/namespaces/mc-provisioner/leases/crossplane-leader-election-rbac](https://api.centaur-dmi.hc-dev.internal.canary.k8s.ondemand.com/apis/coordination.k8s.io/v1/namespaces/mc-provisioner/leases/crossplane-leader-election-rbac)": context deadline exceeded
```

Thread where this was mentioned in slack 
https://crossplane.slack.com/archives/CEG3T90A1/p1661969338405399

Might be a coincidence, but we had two clusters where we rolled the pods were created at the same time and then they both failed 5 hours and 41 minutes later.

### How can we reproduce it?
Not sure.   For us the problem just seems to happen after some period of time and only on GCP.    The pod doesn't seem to be starved for resources at the time.    Pod may is being throttled 3% of the time but that condition isn't localized to the point of the exit.

### What environment did it happen in?
Crossplane version: 1.7 
gcp controller : 0.21.0

* Cloud provider or hardware configuration : Problem happens on GCP but not Azure or AWS 
* Kubernetes version (use `kubectl version`) : v1.22.11
* Kubernetes distribution : GKE

**Comment by negz** [comment]
I think I've seen this too. The good news is that it shouldn't meaningfully effect Crossplane functioning, but it would be nice to fix. It looks like we give Crossplane core a slightly longer than default lease timeout - I bet replicating that to the RBAC manager would help. See https://github.com/crossplane/crossplane/blob/b01b17353/cmd/crossplane/core/core.go#L90.

**Comment by dee0sap** [comment]
Hm, pity that isn't something that is configurable.   Then I could play with it to see if reducing the lease exacerbated the problem and extending it alleviated the problem.

**Comment by dee0sap** [comment]
Was reviewing more clusters and I found this problem also happened in AWS.   So it just seems to be happening more frequently in GCP for some reason.

**Comment by h20220025** [comment]
Can I work on this one! Need to know more about the issue.

**Comment by negz** [comment]
> Hm, pity that isn't something that is configurable.

I think it would be reasonable to make this a flag.

**Comment by haarchri** [comment]
we see the same in aws 

`crossplane-rbac-manager-799fc56665-cqtrb                        1/1     Running   199        36d`

**Comment by dee0sap** [comment]
Hey @negz could we possibly avoid this issue by setting leaderElection = false?

For my team we just have a single replica for both crossplane and the rbac manager.   I expect this is sufficient for our needs as our Crossplane load is pretty light.   Our customers are provisioning a handful of of postgres and maybe a couple handfuls of redis.   Our compositions take care of provisioning the supporting resources ( vpc, subnets, plugins etc ).

**Comment by dee0sap** [comment]
Hey @negz 

I wrote a script that is able to force the 'leader election + container restart' error, see attached.   

Fwiw, the root cause in my team's case is different from what this script simulates but that doesn't matter to my team.    Good enough to have the error.

Setting leaderElection = false seems to fix the problem for us.

[lease.zip](https://github.com/crossplane/crossplane/files/9854003/lease.zip)

**Comment by Santosh1176** [comment]
> I think it would be reasonable to make this a flag.

Hey @negz, can I work on this. Could you also please point to some resource to reproduce this behaviour.

**Comment by dee0sap** [comment]
@Santosh1176 For my team the script in the attached lease.zip ( see my previous comment ) reproduced the problem.

**Comment by Santosh1176** [comment]
> @Santosh1176 For my team the script in the attached lease.zip ( see my previous comment ) reproduced the problem.

Thanks, I'll take a look.

**Comment by shanproofpoint** [comment]
is this related?
`
Page 1 (Lines 1 to 6)
6
I1117 22:50:58.358184       1 request.go:601] Waited for 1.000110377s due to client-side throttling, not priority and fairness, request: GET:https://10.60.0.1:443/apis/gcp.jet.crossplane.io/v1alpha1?timeout=32s
5
I1117 22:51:01.958554       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-rbac...
4
I1117 22:51:17.486595       1 leaderelection.go:258] successfully acquired lease crossplane-system/crossplane-leader-election-rbac
3
I1117 22:51:29.966451       1 trace.go:205] Trace[460650095]: "Reflector ListAndWatch" name:sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250 (17-Nov-2022 22:51:18.559) (total time: 11407ms):
2
Trace[460650095]: ---"Objects listed" error:<nil> 11405ms (22:51:29.964)
1
Trace[460650095]: [11.407389784s] [11.407389784s] END
`

**Comment by shanproofpoint** [comment]
i also observe rbac manager keeps restarting

**Comment by shanproofpoint** [comment]
--manage=All
      --provider-clusterrole=crossplane:allowed-provider-permissions
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 17 Nov 2022 17:13:55 -0800
      Finished:     Thu, 17 Nov 2022 17:14:43 -0800
    Ready:          False
    Restart Count:  19

**Comment by bobh66** [comment]
I was also seeing OOMKilled on the RBAC pod on AWS with leaderElection disabled.   I bumped the memory limit up to 1Gi and that seems to have let it finish what it was doing and now it has stabilized at 230M memory usage and it is not restarting.

I wonder if the parallel processing of X/CRDs increases the memory usage temporarily such that the default limit is not sufficient?  Maybe either an increase to the limit or a reduction in the parallelism would allow the pod to finish it's initial startup processing and then stabilize at a (much) lower memory usage level.

**Comment by shanproofpoint** [comment]
I also suspect this. I am in the middle of transitioning to new providers so i have both sets of providers in memory. perhaps the rbac manager needs more linear to the number of crds.
