### ISSUE TITLE
Helm chart version for master channel is 0.0.0

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#330]
Part of #864 

I expect the master channel helm chart version to be greater than the last official release of v0.1.0, but it appears to be using 0.0.0:
```
> helm repo add crossplane-master https://charts.crossplane.io/master/
> helm search crossplane
NAME                        	CHART VERSION    	APP VERSION      	DESCRIPTION
crossplane-alpha/crossplane 	0.1.0            	0.1.0            	Crossplane - Managed Cloud Resources Operator
crossplane-master/crossplane	0.0.0-377.946c2c8	0.0.0-377.946c2c8	Crossplane - Managed Cloud Resources Operator
```

From this check that uses `git tag`, I'd expect it to find the `v0.1.0` tag and build a version from that:
https://github.com/upbound/build/blob/master/makelib/common.mk#L187-L193

I see the tag locally:
```
> git tag
v0.1.0
```

I'm not sure why 0.0.0 is being used given that a tag does seem to exist.

**Comment by jbw976** [comment]
I actually think that this issue is also the cause of not getting automatic publishing of release branch builds. As shown in the `v0.3.0` [build output](https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fbuild/detail/release-0.3/1/pipeline/):

```
docker push crossplane/crossplane-amd64:v0.0.0-1143.07abcf4
...
docker push crossplane/crossplane-arm64:`v0.0.0-1143.07abcf4`
```

This means that instead of publishing a `v0.3.0` build from Jenkins, we actually published a `v0.0.0-1143.07abcf4` build.  We should definitely fix this for the v0.4 release.

**Comment by displague** [comment]
Are we fetching tags in Jenkins?

It looks like we are not according to this ref spec found in the Jenkins UI:
`+refs/heads/*:refs/remotes/@{remote}/*`

We can either add `+refs/tags/*:refs/remotes/origin/tags/*` there or add it to the Jenkinsfiles:
https://github.com/allegro/axion-release-plugin/issues/195#issuecomment-319541175

**Comment by jbw976** [comment]
Good question @displague! I don't think I knew that the Ref Specs in the Jenkins config controlled how things are fetched, as mentioned in https://stackoverflow.com/a/15449015/467462:

> Refspec defines options for the fetch operation 

We are not specifying a ref spec to fetch any tags, so you may have found what is missing.  I'm going to add this ref spec and see what happens in the next master build.  Hopefully we'll start building `v0.3.0-xyz`.

```
+refs/tags/*:refs/remotes/@{remote}/tags/*
```

**Comment by jbw976** [comment]
So we have figured out the root cause of this issue, essentially the Jenkins builds were not getting any tags during the builds.  There are multiple ways to configure a pipeline to get tags, but it appears that the 3rd and final one is what actually makes a difference:

1. Ref specs such as `+refs/tags/*:refs/remotes/@{remote}/tags/*
1. Pipeline behavior for "Discover tags"
1. **important**: Pipeline behavior for "Advanced clone behaviors" that includes checkbox for "fetch tags"

However, we still have an issue in general with the way we identify versions in `master`. In the build submodule's [`common.mk`](https://github.com/upbound/build/blob/master/makelib/common.mk#L188-L193), we use `git describe --tags` to derive a version number based on the most recent tag that is reachable from the current commit.  This has worked in the past because in previous releases `make tag` has traditionally been run on `master`, resulting in the `master:HEAD` getting a semantic version tag like `v0.3.0`.  Subsequent builds from `master` can find this tag and get a nice version such as `v0.3.0-10.abc1234`.

Going forward, as described in the [release engineering 1-pager](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-release-process.md#pipeline-improvements), we will first create the release branch, test and fix bugs in it, update docs/yaml with semvers, and then finally once we've settled on the release candidate build will we tag and proceed with the release.

This means that the release tags only exist in the release branches.  They do not exist in master, so the version identification logic in our master builds would not be able to find a recent tag in its ancestry.  This results in somewhat unexpected versions because `master` essentially has no knowledge of what the last release was.

Not sure how best to approach this because I think the way we used to always be tagging in master is not correct if there are any more commits in the release branch before the release finally happens. Thoughts?

**Comment by jbw976** [comment]
To clarify, now that we have fixed the Jenkins pipeline configuration to discover tags, the issue that still lingers affects master builds only.  Builds from release branches, that will have a semver tag, will work as desired.

**Comment by jbw976** [comment]
Another option would be to add something like a versioned RC tag to master when we enter feature freeze and branch for an upcoming release.   For example, when we branch for the v0.5.0 release, we could add a tag to master at the branch point that looks like `v0.5.0-rc`.  This would result in subsequent master builds, that are working towards `v0.6.0` to look like `v0.5.0-rc-10.abc1234`.  This would require an update to our build process to also add this tag to master, instead of the suggested 1-time `master` tag above, but it would be more clear about the version/state of master builds, relative to the last release.

**Comment by jbw976** [comment]
The release guide has been published with prescriptive steps on how to address this.  Note that the build submodule and pipeline automation for this is not completed, and a manual step will be performed in the v0.5 release:
https://github.com/crossplaneio/crossplane/blob/master/docs/release/release-process.md#release-candidate-rc-tag

We will no longer see this behavior anymore after the v0.5 release, but this issue will not be closed until the v0.6 milestone when the build submodule and pipeline automation have been updated.

**Comment by jbw976** [comment]
just FYI, we've been doing this manually recently with, would be *really* nice to get this automated soon:

```console
git tag -f -m "release v0.7.0-rc" v0.7.0-rc 9a064f36e93db0c6bb946865998e3c9bb0d2f2f5
git push --tags upstream master
```

**Comment by muvaf** [comment]
This issue seems to be solved now with manual steps in the release guide. Feel free to reopen if you see more to be done.
