### ISSUE TITLE
Proposal:  Reconcile Finalizers

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#3323]
### What problem are you facing?
One way in which Kubernetes represents dependencies between resources is via finalizers.  A resource with a dependency on another resource can place a finalizer on it's dependency so that the dependency cannot be deleted until the dependent resource removes the finalizer.

Crossplane Composites are collections of other resources, so any dependency on a Claim or Composite is actually a dependency on all of the components of the Claim/Composite, down to the "edge" or "leaf" nodes or Managed resources.

That means that when a resource places a finalizer on a Claim or Composite resource, it is declaring a dependency on the entire tree of resources represented by the Claim/Composite, not just the Claim/Composite itself.

When kubectl delete is called on the top-level claim/composite, kubernetes uses the ownerReference relationships to traverse the tree and mark all of the references deleted at the same time.  Since the finalizer only exists on the Claim or Composite dependency, it does not prevent all of the "leaf" node Managed Resources from being deleted, even though the Composite itself cannot be deleted due to the finalizer.  This behavior is independent of Foreground Cascading Deletion, as discussed in #3225 but those changes will help to support this proposal.

### How could Crossplane help solve your problem?
Crossplane can reconcile the "external" or "added" finalizer(s) on Claims and Composite resources, cascading them all the way down to the edge nodes/Managed Resources, so that the declared dependency is enforced throughout the entire tree of resources, and not just on the single Claim/Composite.  This will ensure that the dependencies are maintained as long as the finalizer exists, and that the dependency Managed Resources are not deleted until the finalizer has been removed by the dependent resource.

The finalizer reconciliation should exclude all crossplane.io finalizers, and the foregroundDeletion finalizer used by kubernetes.

By ensuring that these dependencies are properly maintained, resource cleanup can be "orchestrated" by functionality such as the dependsOn feature in the Kubernetes Crossplane provider.  It also ensures that Crossplane behaves "as expected" by other Kubernetes ecosystem resources.

This change can be limited to the claim and composite reconcilers in the Crossplane project.  The Managed resource reconciler in the crossplane-runtime project should not require any changes.

While this feature should not affect any "normal" usage of Crossplane, it may be desirable to have this functionality controlled by a feature flag for the near term, until the feature is well understood and well tested.

This proposal is dependent on the crossplane-runtime changes proposed in https://github.com/crossplane/crossplane-runtime/pull/355 and the corresponding crossplane project changes proposed in https://github.com/crossplane/crossplane/pull/3321

Feedback and suggestions are welcome

**Comment by bobh66** [comment]
@morningspace @ytsarev FYI

**Comment by negz** [comment]
> One way in which Kubernetes represents dependencies between resources is via finalizers. A resource with a dependency on another resource can place a finalizer on it's dependency so that the dependency cannot be deleted until the dependent resource removes the finalizer.

I don't think this is actually how finalizers are typically used. In fact, I think it may be an anti-pattern.

Specifically I don't think its true that resources place finalizers on their dependencies. Rather, I believe its the case that resources (i.e. resource controllers) place finalizers on _themselves_ to indicate they _may be_ a dependency and should ensure no dependents exist before they can be deleted. This is outlined [in this article](https://www.ibm.com/cloud/blog/preserve-kubernetes-api-objects-while-they-are-in-use) on using finalizers for in-use protection and I believe is the approach taken by Kubernetes' PV and PVC in-use protection, as well as Crossplane's ProviderConfig in-use protection.

**Comment by bobh66** [comment]
Based on feedback from Nic and another idea that will solve most of the same problem without using finalizers, I'm closing this issue.
