### ISSUE TITLE
Can't install package configuration

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#3329]
### What happened?
I try to install a basic configuration package and get the following error: 

`cannot initialize parser backend: failed to open package stream file: EOF`

### How can we reproduce it?
See https://github.com/luebken/config-test/ for a simple example.

```
$ kubectl describe configurationrevisions.pkg.crossplane.io
...
Events:
  Type     Reason        Age                  From                                              Message
  ----     ------        ----                 ----                                              -------
  Warning  ParsePackage  16s (x9 over 3m15s)  packages/configurationrevision.pkg.crossplane.io  cannot initialize parser backend: failed to open package stream file: EOF
```
### What environment did it happen in?
```
$ helm list -n crossplane-system -o json | jq .[].app_version
"1.9.1"
$ kind --version
kind version 0.14.0
$ docker ps --format '{{ .Image }}'
kindest/node:v1.25.0
```

**Comment by luebken** [comment]
Fixed by switching to `kubectl crossplane config push` https://github.com/luebken/config-test/commit/0e5b7d48197772961c2160650e88db5eca3985cc

**Comment by ytsarev** [comment]
FWIW, I am packaging and pushing platform-refs with
```
up --version
v0.13.0
```
whole day and it works like a charm.

**Comment by tehlers320** [comment]
what the heck is "up" ? im trying to cut a test provider and am also seeing this. No clue what up is.

**Comment by hasheddan** [comment]
@tehlers320 https://github.com/upbound/up
