### ISSUE TITLE
Consider adding vpcPeeringConnectionIdRef in Route table

### ISSUE THREAD

**Issue by Rishikeshcg** [crossplane/crossplane#3340]
In the route tables, there is no option to refer a peering connection without hardcoding the peering connection id. If vpcPeeringConnectionIdRef or Selector is added, there is no need to hardcode the peering id.

**Comment by ytsarev** [comment]
@Rishikeshcg does not seem related to the core crossplane.  Could you please open this issue in the associated provider repository?
