### ISSUE TITLE
Composite resource Postgresql not deleted after deleting the claim.

### ISSUE THREAD

**Issue by rahtr** [crossplane/crossplane#3341]
### What happened?

I am following the setting started documentation(https://github.com/crossplane/crossplane/blob/master/docs/getting-started/provision-infrastructure.md) and was able to deploy a RDS instance.
I am somehow unable to delete the instance. I executed this command: `kubectl delete postgresqlinstance my-db` but the I can still see this instance in AWS:

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/31742059/192333875-cc1a1c99-360b-420b-b665-1f780c4d24f0.png">

Events from the RDS instance:

```
Events:
  Type     Reason                           Age                From                                            Message
  ----     ------                           ----               ----                                            -------
  Normal   CreatedExternalResource          42m                managed/rdsinstance.database.aws.crossplane.io  Successfully requested creation of external resource
  Warning  CannotObserveExternalResource    12m                managed/rdsinstance.database.aws.crossplane.io  cannot describe RDS instance: api error Throttling: Rate exceeded
  Warning  CannotInitializeManagedResource  12m (x2 over 42m)  managed/rdsinstance.database.aws.crossplane.io  cannot update RDS instance custom resource: Operation cannot be fulfilled on rdsinstances.database.aws.crossplane.io "my-db-v48fc-ghbdn": the object has been modified; please apply your changes to the latest version and try again
```

### How can we reproduce it?
Follow the getting started guide(https://github.com/crossplane/crossplane/blob/master/docs/getting-started/provision-infrastructure.md) and provision an RDS instance. Delete the instance once it's ready and check the console to see if the composite resource is deleted.

### What environment did it happen in?
Crossplane version:  v1.8.1

Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration : Azure
* Kubernetes version: 1.21
* Kubernetes distribution: AKS

**Comment by AndresPineros** [comment]
I also see this problem in verson v1.9

I need to remove RDS instances manually, otherwise the finalizers of the RdsInstance resource are never done.
