### ISSUE TITLE
Feature: Sync resources as soon as their definitions are updated

### ISSUE THREAD

**Issue by AndresPineros** [crossplane/crossplane#3342]
### What problem are you facing?

I don't want to have a small poll-interval because at some point I'd reach the AWS API ratelimit, as shown in [#1412 aws-provider](https://github.com/crossplane-contrib/provider-aws/issues/1412). I'd like to be able to specify a poll-interval of 5h or greater. I don't really care for a constant poll that checks the state of the resources because we don't allow for resources to be modified manually, the only way we have to change a resource is by changing its manifest. I did set the poll interval to 5h, but whenever the manifest of a resource is updated, I have to wait 5h for the resource to realize it is not synced.

### How could Crossplane help solve your problem?

It would help a lot if a resource was instantly synced by the provider whenever its definition changes in Kubernetes. That way it would be possible to have a large poll-interval and not have to wait the whole poll period when resources are updated.

If this behavior is not desired by everyone, then it could be enabled/disabled with a flag. I think this is a feature that people with a large amount of cloud resources would appreciate because they will probably struggle with API ratelimits at some point.

Personally, I wouldn't fully migrate to Crossplane until something similar is implemented. Moving hundreds of resources to then realize that I'm hitting the AWS ratelimit and that I have to increase my interval to a number that makes pushing changes slow and painful is a no-no for me.

**Comment by negz** [comment]
> It would help a lot if a resource was instantly synced by the provider whenever its definition changes in Kubernetes.

This is already the case.

We _also_ poll in order to correct unforeseen drift, because there's no straightforward way to subscribe to changes to external resources.

> I'd like to be able to specify a poll-interval of 5h or greater.

Most providers already support this. For provider-aws `--poll=5h` should do it.

**Comment by AndresPineros** [comment]
Previous to opening the issue, I set the AWS poll interval to 5h and resources wouldn't sync after changing their definition. I waited about 10 minutes, nothing happened. Set the interval back to 1m and then the sync started.

**Comment by WesselAtWork** [comment]
Can confirm.
We tested it on 2 of our clusters and we assumed that that the provider doesn't have instant change reconcile.
@AndresPineros what version of kubernettes are you running?

**Comment by arturkasperek** [comment]
@negz I also experienced that problem.
Crossplane composition was updated and had to wait poll interval for sync.
I'm using upbound distr but I guess its not the case.
Should I set some custom param in helm chart or is it the default behaviour?
