### ISSUE TITLE
Stop publishing crossplane-contrib extensions to crossplane OCI repository

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3350]
### What problem are you facing?

https://github.com/crossplane/crossplane/blob/dd87bfb/CHARTER.md
https://github.com/crossplane/crossplane/blob/dd87bfb/GOVERNANCE.md

Our charter and governance documents clarify that the crossplane-contrib GitHub org exists as a neutral place for the community to collaborate on Crossplane extensions (e.g. providers). Extensions aren't required to fall under Crossplane's governance, and extensions in contrib are no more "official" or blessed by the project than extensions hosted elsewhere - for example https://github.com/crossplane-contrib/provider-digitalocean could happily live under https://github.com/digitalocean and be just as "valid".

Currently extensions built from crossplane-contrib are published to https://hub.docker.com/u/crossplane. This is mostly a historical artifact - we used to publish everything here before we created the contrib org. Publishing to this org could give the impression that providers under the contrib org are part of the "core" Crossplane project while others are not.

### How could Crossplane help solve your problem?

We should switch all providers under contrib to publish to a dedicated crossplane-contrib OCI repository.

**Comment by ytsarev** [comment]
/fresh looks like we need to finalize this one

**Comment by hasheddan** [comment]
I believe that all `crossplane-contrib` repos are no longer pushing images to the `crossplane` DockerHub org. Closing this one out.
