### ISSUE TITLE
Switch listing of crossplane charts in Artifact Hub from master to stable channel

### ISSUE THREAD

**Issue by chewbh** [crossplane/crossplane#3362]
### What problem are you facing?
Currently, the listing of all crossplane helm charts in ArtifactHub are pointed to the master channel rather than the stable channel. Thus, we can't leverage on ArtifactHub to look for a stable release of crossplane charts. Thus pose a problem for us as our internal package mirroring tool rely on ArtifactHub api to search charts.

### How could Crossplane help solve your problem?
Propose to change the publication flow for Crossplane to ArtifactHub to point to the stable channel instead of the master channel.

**Comment by MallikharjunaTeja** [comment]
i want to work on this could you please assign me this

**Comment by ytsarev** [comment]
@MallikharjunaTeja assigned you to this issue, thanks for the willingness to contribute 👍
