### ISSUE TITLE
Can I plugin my own CRD into Composition under resources?

### ISSUE THREAD

**Issue by saiharshitach** [crossplane/crossplane#3384]
Can I plugin my own CRD into Composition under resources when I'm creating XRD's?

If this is not possible Could you please direct me on how to achieve the functionality which is not provided via crossplane?

**Comment by negz** [comment]
No, not directly. See https://github.com/crossplane/crossplane/issues/1730 for more discussion and context.

You can however use https://github.com/crossplane-contrib/provider-kubernetes to "wrap" your custom resource in a valid Crossplane managed resource that you can use in a Composition.
