### ISSUE TITLE
Make generated code available for import into other projects?

### ISSUE THREAD

**Issue by oblogic7** [crossplane/crossplane#3387]
I have an idea for a project that could make use of the generated client and Crossplane CRD interfaces.  This code is currently internal and cannot be used directly.  Is there any chance of moving this code to allow it to be used by projects that would like to extend Crossplane resources with custom controllers/watchers/etc?

**Comment by negz** [comment]
@oblogic7 Possibly. We intentionally have all of our code internal to ensure we have a conversation before anyone takes a dependency on it.

Can you share more about what you're thinking about doing? If you did take a dependency, would you want to import them from crossplane/crossplane or would it make more sense to break them out into their own client library?

**Comment by oblogic7** [comment]
My idea revolves around a client that would simplify management of card and
claims without requiring interaction with k8s or messing around with yaml.
This client would make use of discover resources in a cluster, use watchers
to monitor changes and deploy new claims. Being able to have current models
and a client set that is capable of watching the resources would be very
handy.

I think a separate library may be a good approach since it would limit the
scope of the import.
