### ISSUE TITLE
Importing resources is not restricted

### ISSUE THREAD

**Issue by dudicoco** [crossplane/crossplane#3397]
### What problem are you facing?

When importing an external resource into crossplane you can just specify the resource name and crossplane does the magic of importing it.
While this is a much better experience than the terraform import process (import into the state manually), it also has a loophole as it allows importing resources which you don't necessarily own.
Two examples I can think of:
1. Resource is managed externally and should not be managed by crossplane
2. Resource is already managed by crossplane by a different team (different `metadata.name`, identical `external-name` annotation - i'm not sure what happens in this scenario?

### How could Crossplane help solve your problem?

Impose some security restrictions on importing resources.

**Comment by muvaf** [comment]
@dudicoco The only thing Crossplane requires for importing is for the provided credentials to have read access on that resource. I wonder what we could do apart from that. Maybe a policy engine with admission webhook to check external name annotations? Do you know of a tool that meets your use case well?

**Comment by dudicoco** [comment]
@muvaf perhaps something similar to Helm's import mechanism would be the right solution, I couldn't find anything in the official docs but here is an article on how to import resources into a Helm release: https://jacky-jiang.medium.com/import-existing-resources-in-helm-3-e27db11fd467

Basically if the resource has the correct annotations and label it can be imported automatically into the release.
For Crossplane however, I would not rely on annotations but rather on tags on the actual infrastructure as that provides a high guarantee that the resource is allowed to be imported.

Crossplane already adds default tags to resources which could be used for the import process.
To import a resource, add the necessary tags to the infrastructure and create the corresponding managed resource.
