### ISSUE TITLE
Proposal for Docs Reorg

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#3398]
### What problem are you facing?
The organization of the Crossplane documentation has been somewhat organic and has led to duplicate pages and user confusion on which guide to follow for different scenarios. 

With a docs maintainer beginning to generate more content we should consider changing the over all organization of the current documentation.

### How could Crossplane help solve your problem?
My proposed structure:

* **Quickstart Guides** - These are one-page docs focused on installing Crossplane, adding and authenticating to a provider and creating a basic managed resource.
    * *Provider AWS Quickstart*
    * *Provider Azure Quickstart*
    * *Provider GCP Quickstart* 
    *  ...
* **Crossplane Installation Management** - All docs related to core Crossplane software
    * *Install*
    * *Upgrade*
    * *Uninstall*
    * *Configure*
* **Crossplane Components** - Docs covering CRDs from core Crossplane
    * *Providers*
    * *Managed Resources*
    * *Composite Resources*
    * *Compositions*
    * *Configurations*
    * *Claims*
* **Crossplane Packages** - Docs on provider and configuration packages
    * *Building*
    * *Publishing*
    * *xpkg Spec*
* **Guides** - Standalone documents that are more about integration or solving a specific challenge or problem
    * (All content currently in docs//guides)
* **Additional Information** - Anything that isn't about configuring or managing Crossplane but relevant to the project or community
    * _Release Cycles_
    * _Troubleshoot Crossplane_
    * _Glossary_
    * _Contribute to Crossplane_
* **Reference Implementations** - Full Crossplane deployments with Providers, Configurations, XRDs, etc. 
    * _[AWS Reference Implementation](https://github.com/upbound/platform-ref-aws/)_
    * _[Azure Reference Implementation](https://github.com/upbound/platform-ref-azure)_
    * _[GCP Reference Implementation](https://github.com/upbound/platform-ref-gcp)_
    * ...

Some of these page names may change and more pages or sections can be added in the future but this would provide a rough taxonomy for new content. 

#### Quick start vs Reference Implementations
Quickstarts are specifically designed for people with little or no knowledge of Crossplane. The goal of Quickstart guides is not to show the full power of Crossplane but just to demonstrate how Crossplane connects a Kubernetes cluster to external resources. 

Reference Implementations are designed to be a blueprint for "how to do it right". This should be considered a (mostly) comprehensive reference for users that that have experience with Crossplane and are looking for practical examples on how to implement more advanced Crossplane features. 

#### What about existing content
Except for `/docs/guides` and `docs/api-docs/` all content will have a new directory/URL. Existing content would be mapped as follows:
* Getting Started -> /docs/index.html
    * Install and Configure -> Quickstart Guides
    * Provision Infra -> Reference Implementation (likely a specific page inside a reference implementation)
    * Create a Config -> Reference Implementation (likely a specific page inside a reference implementation)
* Concepts -> Crossplane Components
    * Providers -> Crossplane Components/Providers
    * Managed Resources -> Crossplane Components/Managed Resources
    * Composite Resources -> Crossplane Components/Composite Resources
    * Crossplane Packages -> Crossplane Packages/
    * Terminology -> Additional Resources/Glossary
* Reference -> Crossplane Components
    * Install Crossplane -> Crossplane Installation Management/Install
    * Configure Your Cloud Provider Account -> Components/Providers
    * Uninstall -> Crossplane Installation Management/Uninstall
    * Composition -> Components/Composite Resources
    * xpkg Specification -> Packages/xpkg spec
    * Troubleshoot -> Additional Resources/Troubleshoot Crossplane
    * Learn More -> Additional Resources/index.html
    * Release Cycle -> Additional Resources/Release Cycle
* Contributing/** -> Additional Resources/**
* FAQ/** -> Additional Resources/**

#### What's the downside?
Until we move hosting providers ([Site #98](https://github.com/crossplane/crossplane.github.io/issues/98)) we won't be able to implement proper redirects for pages that are moved/changed/deleted. 
A temporary "remedy" would be to send users to the documentation landing page (/docs) instead of a 404.

**Comment by negz** [comment]
One reason we've moved away from quick starts like the ones you propose in the past is that we don't really intend for anyone to just install some MRs and stop there; we intend folks to always use them via Composition. I'm okay with introducing the concept of MRs first, but I don't think the quick start should end at "you have an MR".

I'm also a little wary of attempting to merge what is currently in the reference docs for Composition with the concepts docs. Happy to move things around, but I do like having separate pages for "here's an introduction to the general idea" vs "here's an example of every single thing you can configure in a Composition or XRD".

**Comment by plumbis** [comment]
The Quickstart plan was discussed in the Oct 20 community meeting and mentioned in PR #3396. Copying here:

> In the Oct 20 Community Call we discussed different goals for what you're describing based on personas:
> 1.) A user completely new to Crossplane. May have limited Kubernetes knowledge.
> This is the target persona of a provider quickstart. How do you demonstrate the core concept of Crossplane communicating with an external API endpoint, entirely through Kubernetes. The quickstart (should) also demonstrates a validation of security credentials between Crossplane and the Provider.
> 
> 2.) A user who is familiar with Crossplane or self-service infrastructure APIs
> This persona is more interested in a more comprehensive example and "magic moment". The discussion today was around creating a new "Composition and Claim" quickstart delivered in a simple fashion (TBD, likely a config package). The user would then apply a small number of configurations or changes to finish the deployment and consume the resources. The main thing here is fast forwarding through all of the lower-level configurations and requirements (e.g., Provider) to focus on full value of Crossplane.
> 
> 3.) An end-to-end example using one or more providers
> This would be the "Reference Implementations' mentioned in https://github.com/crossplane/crossplane/issues/3398. These would be "production grade" ways to use Crossplane for a given provider (or set of providers). These should be considered "common/best practices" way to do things.

>I'm also a little wary of attempting to merge what is currently in the reference docs for Composition with the concepts docs. 
Agreed, the content will not merge well. The `reference/composition` will evolve into more of an API reference documentation. Exactly what that looks like is TBD.

**Comment by plumbis** [comment]
My approach for quickstart guides is to break them into two parts:
1.) Install crossplane and a provider. Verify that you can authenticate to the provider by creating an MR.
2.) Build a composite using the settings in (1) 

This can be a single page or multiple pages (I would recommend multiple pages due to length) but think of it as a "crawl, walk, run" approach. There is no intention to imply that creating an MR is the stopping point.

**Comment by negz** [comment]
@plumbis and I just had a quick sync, and are broadly aligned on this outline. Recapping what we discussed:

* The getting started guides will cover Composition.
* We might 'rename' the getting started guides to focus on the problem being solved (e.g "build a platform on AWS")
* We'd like to include an overview / intro to Crossplane, what it's for, and the key concepts as the docs entrypoint

**Comment by luebken** [comment]
> 1) Install crossplane and a provider. Verify that you can authenticate to the provider by creating an MR.

I always wondered if there could be a cleaner way to verify a provider is authenticated.

**Comment by plumbis** [comment]
@negz are you okay with this proposed structure? (the contents of the quickstarts being a different issue discussed in #3396)

**Comment by gberche-orange** [comment]
@plumbis as a crossplane doc user, one major pain is the lack of a search button on the https://docs.crossplane.io

As a workaround, I was going manual site searching using google such as [site:https://docs.crossplane.io/ synced](https://www.google.com/search?client=firefox-b-e&q=site%3Ahttps%3A%2F%2Fdocs.crossplane.io%2F+synced) for searching about sync and ready status (somewhat described into https://docs.crossplane.io/v1.10/reference/troubleshoot/#resource-status-and-condition) 

I'm now using a firefox plugin https://addons.mozilla.org/en-US/firefox/addon/search-current-site/ as a workaround with a `search within this site` button

![image](https://user-images.githubusercontent.com/4748380/206687564-3d63b2cc-71ee-48e8-b939-6cf1773954c1.png)

**Comment by jeanduplessis** [comment]
@gberche-orange, you should see what @plumbis has been cooking up for search: https://deploy-preview-226--crossplane.netlify.app/

**Comment by gberche-orange** [comment]
@plumbis the search feature looks great, thanks ! That will be very useful for users.

I noticed that search results currently include matches for multiple crossplane versions, introducing top-line duplicates. I guess a possible future refinement could be to match against current version by default and offer an option then to extand to all crossplane versions.

**Comment by plumbis** [comment]
100% with you @gberche-orange . We have [Docs issue #202](https://github.com/crossplane/docs/issues/202) opened to improve that experience. I spent most of this week trying to build that out and failing. Instead of going longer without search I decided to implement something today and work on building the improved experience in the near future. 

Thanks for the feedback!

**Comment by plumbis** [comment]
I'll leave this open for additional comments through December 16 before moving forward.

**Comment by plumbis** [comment]
There is now a draft PR for this change.

https://github.com/crossplane/docs/pull/254

Please review and provide feedback in the PR.

**Comment by plumbis** [comment]
This work is currently in progress in [crossplane/docs #271](https://github.com/crossplane/docs/pull/271).

Plan is to merge content in with v1.11 release.
