### ISSUE TITLE
Design: Crossplane Abstraction for Cloud Provider, Region, Zones

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#340]
### Overview
Currently Crossplane does not provide any conceptual (or concrete) abstraction for CloudProvider's and CloudProvider attributes such as regions and zone. In context of scheduling we want application developers (owners) to operate on Workload/Resource affinity/anti-affinity in terms of abstract cloud providers, regions, zones. 
For example, application developer may express workload to Kubernetes cluster affinity in terms of:
- schedule on Kubernetes cluster with provider 'ABC', or
- schedule on Kubernetes cluster in regions 'xyz', etc.

### Issue:
Design abstraction for cloud providers, regions, zone and their integration with existing crossplane constructs: Providers, ResourceClasses, etc.

### Related To:
#279

**Comment by negz** [comment]
CC @prasek - looks like this issue is relevant to our discussion today.

**Comment by negz** [comment]
I don't think this is relevant now that we're moving away from supporting workloads. With Composition I think we a pattern for defining API types that represent some of these things (at least the ones that you can CRUD via the provider, like VPCs).
