### ISSUE TITLE
Crossplane pod on v1.10.0 consumes 10-15x more CPU than on v1.9.1

### ISSUE THREAD

**Issue by danports** [crossplane/crossplane#3407]
### What happened?
The core Crossplane pod typically used 5-10m CPU in my cluster on v1.9.1 and earlier, but when I upgraded to v1.10.0, that jumped to around 100m, a roughly 10-15x increase. This chart shows the CPU usage of the Crossplane pod (and that pod only - not the RBAC controller or any of the providers) before and after the upgrade. As you can see, the pod is now frequently getting throttled - I set a 100m CPU request limit on it a while ago that was basically never hit before v1.10.0. There were no changes to my Crossplane resources during the week this chart covers, and there were no significant changes to pod log content or volume before/after the upgrade.
![image](https://user-images.githubusercontent.com/8728855/197374748-5bc85483-7144-4d70-8082-e6f58ad77291.png)

### How can we reproduce it?
I'm not sure that the issue is specific to any particular configuration in my cluster.

### What environment did it happen in?
* Crossplane version: 1.10.0
* Cloud provider: AWS
* Kubernetes version: 1.25.2
* Kubernetes distribution: kOps
* OS (e.g. from /etc/os-release): Ubuntu

**Comment by negz** [comment]
@danports Thanks for flagging this. Are you able to provide a minimal setup (providers+configs/XRs wise) that reproduces it? If so we can profile and see what's using the CPU.

**Comment by macmiranda** [comment]
We're experiencing between 90-95% CPU Throttling on the Crossplane container based on default resource limits included in the official chart

![image](https://user-images.githubusercontent.com/17923899/197710696-28031741-bfd3-496d-8e4a-090a8bdc4060.png)

We did not see that happening with 1.9.1

It's a fresh Crossplane installation, only AWS Provider configured so far. No managed resources, no XRDs.

**Comment by hasheddan** [comment]
I’m guessing https://github.com/crossplane/crossplane/pull/3176 is the culprit here. However, the solution is likely more granular reconciliation logic in the package manager, rather than reducing the concurrent establishment of API types in a package. @macmiranda  are you able to see ongoing package reconciler enqueues happening when turning on debug logging?

**Comment by hasheddan** [comment]
I tested this out after #3425 and verified that we still get throttled, but after the package install stabilizes we drop back down to single digits.

**Comment by danports** [comment]
30 minutes after deploying 1.10.1 (at 19:55 on the chart), there doesn't seem to be any difference in the CPU consumption of the main Crossplane pod, though the CPU consumption of the `rbac-manager` pod (the lower line) seems to have been roughly halved:
![image](https://user-images.githubusercontent.com/8728855/199133246-f7e15029-8811-4a2c-b72d-742d53edc0f6.png)

**Comment by hasheddan** [comment]
@danports I’m guessing one of your packages is being continuously reconciled. Are you able to shared debug logs?

**Comment by danports** [comment]
Maybe a dumb question, but how do I enable/access the debug logs? Couldn't find any documentation about this.

**Comment by hasheddan** [comment]
@danports you can supply `--debug` as an arg 👍🏻

https://crossplane.io/docs/v1.10/reference/troubleshoot.html#crossplane-logs

It can be passed via the `args` value with helm if preferred.

https://github.com/crossplane/crossplane/blob/b98ec8996b33274635d99cbb41ff0d896b378d57/cluster/charts/crossplane/values.yaml.tmpl#L25

**Comment by danports** [comment]
Thanks. What jumps out at me in the debug logs at first glance is that Crossplane is reconciling the same package every 15 seconds:

```
DEBUG	crossplane	Reconciling	{"controller": "packages/providerrevision.pkg.crossplane.io", "request": "/danports-provider-aws-rds-restore-6bdb13656550"}
DEBUG	crossplane	Reconciling	{"controller": "packages/provider.pkg.crossplane.io", "request": "/danports-provider-aws-rds-restore"}
```

I don't see anything particularly notable in that `Provider` resource - and as mentioned earlier, I haven't changed the definitions of my providers in a long time:

```json
{
    "apiVersion": "pkg.crossplane.io/v1",
    "kind": "Provider",
    "metadata": {
        "creationTimestamp": "2021-07-31T16:16:29Z",
        "generation": 7,
        "labels": {
            "kustomize.toolkit.fluxcd.io/name": "infrastructure",
            "kustomize.toolkit.fluxcd.io/namespace": "flux-system"
        },
        "name": "danports-provider-aws-rds-restore",
        "resourceVersion": "374824213",
        "uid": "1c4d0bd6-7ac8-49d3-a4b8-f2eb50c5986f"
    },
    "spec": {
        "ignoreCrossplaneConstraints": false,
        "package": "crossplane/provider-aws:master",
        "packagePullPolicy": "IfNotPresent",
        "revisionActivationPolicy": "Automatic",
        "revisionHistoryLimit": 1,
        "skipDependencyResolution": false
    },
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2022-10-31T22:18:57Z",
                "reason": "HealthyPackageRevision",
                "status": "True",
                "type": "Healthy"
            },
            {
                "lastTransitionTime": "2021-07-31T16:16:33Z",
                "reason": "ActivePackageRevision",
                "status": "True",
                "type": "Installed"
            }
        ],
        "currentIdentifier": "crossplane/provider-aws:master",
        "currentRevision": "danports-provider-aws-rds-restore-cfaa463fccb0"
    }
}
```

I've got another provider installed (the SQL provider) that is only being reconciled 1-2x/hour.

**Comment by hasheddan** [comment]
@danports gotcha, this matches my expectation here as what would be causing the high CPU 👍🏻 I'm not sure what is consistently triggering, are there any other logs being emitted following the reconciles? It could be related to you using the `master` tag, though your pull policy indicates it shouldn't be.

**Comment by danports** [comment]
There was a composite being reconciled fairly often too - I'll check on that. I don't think it's the `master` tag, since I'm using that tag for the SQL provider and it isn't triggering continuous reconciliations there. I have been meaning to switch to more specific tags though so I can have a more controlled upgrade process, so I might try that just to see if it helps.

**Comment by danports** [comment]
I switched away from the `master` tag today, and that doesn't seem to have made a difference. I did notice though that after a couple of days on 1.10.1, CPU usage dropped to about 50m - still far higher than in previous releases, but an improvement nonetheless. Going to wait a few days to collect more data and then dig into the logs again.

**Comment by hasheddan** [comment]
I am going to do some further testing here with https://github.com/crossplane/crossplane/pull/3582. I suspect that CPU will still be higher than previous releases, but it shouldn't stay pinned as high with the reduction in reconciles.

**Comment by danports** [comment]
Thanks @hasheddan! Sorry I haven't followed up here - Crossplane's CPU consumption is still an issue, but because it hasn't really had cost implications for me the way it did for the folks in #3540, it's been on my back burner. I haven't removed any inactive provider revisions in the cluster to work around the issue, so if you have a prerelease or new patch version I'd be happy to give it a spin to see if it resolves the issue.

**Comment by hasheddan** [comment]
@danports no worries! Thanks again for the data you shared. I just pushed a build to `hasheddan/crossplane@sha256:d19bce2d2de3a8b64c44a29df09eb3250229a67029fd7dd4f75c78d9c9abc05e` (`hasheddan/crossplane:stable-refs`). Let me know if you get a chance to try it out and are able to collect more data from your environment!

Repo Link: https://hub.docker.com/layers/hasheddan/crossplane/stable-refs/images/sha256-d19bce2d2de3a8b64c44a29df09eb3250229a67029fd7dd4f75c78d9c9abc05e?context=repo

**Comment by danports** [comment]
Looks like there are some prerequisites for this build - it's crashing and outputting a lot of errors like `cannot fetch composition revision: cannot list CompositionRevisions: no matches for kind "CompositionRevision" in version "apiextensions.crossplane.io/v1beta1"`. Do you have the CRDs and such packaged as a Helm chart I can deploy?

**Comment by hasheddan** [comment]
@danports 1.10 backport image available at https://hub.docker.com/layers/hasheddan/crossplane/stable-refs-1.10/images/sha256-3711a481422c52a0ebfcd460fc597a75692b17f67e3d3a485feafc9450ea44cb?context=repo

**Comment by jbw976** [comment]
Amazing!! Thank you @hasheddan for finding the root cause and getting this fix in, and thank you @danports for verifying it in your environment to give us some more confidence.  Really appreciate the effort here! 🙇

**Comment by hasheddan** [comment]
@jbw976 yep! I am going to create a separate one and link these two up to it to investigate if we want to expose a value to configure concurrency in the package manager 👍🏻
