### ISSUE TITLE
Crossplane overwrites fields after patches have been applied, causing resource creation failure

### ISSUE THREAD

**Issue by pablofontanilla** [crossplane/crossplane#3408]
### What happened?

Crossplane applies patches to set the external annotation, name and one spec field of a resource.:

    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: status.validationName
        toFieldPath: metadata.annotations.crossplane.io/external-name
      - type: FromCompositeFieldPath
        fromFieldPath: status.validationName
        toFieldPath: metadata.name  
      - type: FromCompositeFieldPath
        fromFieldPath: status.validationValue
        toFieldPath: spec.forProvider.resourceRecords[*].value
      - type: FromCompositeFieldPath
        fromFieldPath: status.zoneId
        toFieldPath: spec.forProvider.zoneId

----
    
    Name:         2836b05285c7fd5c19d0a545151b4f2a.testcrossplane2.com
    Namespace:    
    Labels:       crossplane.io/claim-name=
                  crossplane.io/claim-namespace=
                  crossplane.io/composite=test-claim
    Annotations:  crossplane.io/composition-resource-name: validationRecord
                  crossplane.io/external-create-pending: 2022-10-24T08:17:10Z
                  crossplane.io/external-create-succeeded: 2022-10-24T08:17:11Z
                  crossplane.io/external-name: 2836b05285c7fd5c19d0a545151b4f2a.testcrossplane2.com
----
    Spec:
      Deletion Policy:  Delete
      For Provider:
        Resource Records:
          Value:  _3c7219951a54bff5dd2d5d9531105157.fbnrgqtmtt.acm-validations.aws
        Ttl:      300
        Type:     CNAME
        Zone Id:  Z07100032K8N2MOWTYKD3
      Provider Config Ref:
        Name:  default

but then later overrides them with the generic name created by (I assume) kubernetes or the value specified on the composition:

    Name:         test-claim-7bwdm
    Namespace:    
    Labels:       crossplane.io/claim-name=
                  crossplane.io/claim-namespace=
                  crossplane.io/composite=test-claim
    Annotations:  crossplane.io/composition-resource-name: validationRecord
                  crossplane.io/external-create-failed: 2022-10-24T08:17:29Z
                  crossplane.io/external-create-pending: 2022-10-24T08:17:29Z
                  crossplane.io/external-name: test-claim-7bwdm

----
    Spec:
      Deletion Policy:  Delete
      For Provider:
        Resource Records:
          **Value:  1.2.3.4**
        Ttl:      300
        Type:     CNAME
        Zone Id:  Z07100032K8N2MOWTYKD3

It might be related to the fact that the origin (status.validationName) has to be populated with the values from another resource declared previously on the composition:

  - name: certificate
    base:
      apiVersion: acm.aws.crossplane.io/v1beta1
      kind: Certificate
      spec:
        forProvider:
          region: us-east-1
          tags: []
          validationMethod: DNS
        providerConfigRef: 
          name: default
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.domain
      toFieldPath: spec.forProvider.domainName
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.resourceRecord.name
      toFieldPath: status.validationName

Depending on how quickly the annotations and values are overwritten, the resource is created or not. In the case presented here, it can be seen that the resource was successfully created at "external-create-succeeded: 2022-10-24T08:17:11Z" but after the overwrite was considered as failed creation: "external-create-failed: 2022-10-24T08:17:29Z" 
In many other attempts, the resource was never created, probably because the overwrite happened before the resource creation and the set external-name is not a valid name for the cloud resource (a resourcerecord for Route53 in this case)

### How can we reproduce it?

The patches snippet on the "What happened" section getting values from a Status field that is patched from a value of a created cloud resource.

### What environment did it happen in?
Crossplane version: 1.10.0

K8s version: v1.21.14
Distribution: K3s (rancher desktop)
OS: macOS 12.5.1

Attached composition resource definition, composition and claim, as well as description of resources before and after overwrite
[Archive.zip](https://github.com/crossplane/crossplane/files/9850254/Archive.zip)

[description_after_overwrite.txt](https://github.com/crossplane/crossplane/files/9850233/description_after_overwrite.txt)
[description_before_overwrite.txt](https://github.com/crossplane/crossplane/files/9850234/description_before_overwrite.txt)

**Comment by haarchri** [comment]
try this

`toFieldPath: metadata.annotations[crossplane.io/external-name]`

**Comment by pablofontanilla** [comment]
Thanks for your answer! Sadly, I've tried and the same thing happens. It's not that the patch doesn't work, it's that it gets overwritten by the generic resource name. Is there any way to get logs about this that might help understand what's going on?
