### ISSUE TITLE
Update install guide with less confusing instructions

### ISSUE THREAD

**Issue by fuzz** [crossplane/crossplane#3416]
### What problem are you facing?

The cluster install instructions have a happy path for macOS/Homebrew, but the other options are confusing, plus the instructions are identical for the macOS Linux and Windows tabs.

![Screenshot from 2022-10-27 13-19-46](https://user-images.githubusercontent.com/9918/198390133-b6977559-36d2-40b4-bed1-8806b9e5243e.png)

![Screenshot from 2022-10-27 13-19-56](https://user-images.githubusercontent.com/9918/198390221-5a6e613c-7dcf-4ffb-9440-0185669d1179.png)

In addition to it being confusing to apparently be told to use Kubernetes, Kind, Minikube and Helm, it is also the case that Minikube is currently broken for a lot of users, including myself on a fresh Ubuntu 22.04 install.

https://github.com/kubernetes/minikube/issues/14523
https://github.com/kubernetes/minikube/issues/14505

### How could Crossplane help solve your problem?

Let's be as helpful to all users as we are to macOS/Homebrew users by just telling them to install Kind and Helm. We could also ditch the extra tab since the non-Homebrew instructions for all three platforms are identical.

I already updated the file, then I found the CONTRIBUTING doc so I'm opening an Issue before I PR.

**Comment by plumbis** [comment]
Thanks for the report! 

I'm doing some work in this space but holding off on approvals for #3398 and #3396 

Take a look at the steps used in #3396 (or at least [this file](https://github.com/plumbis/crossplane/blob/cloud-quickstarts/docs/getting-started/install-crossplane.md)) and let me know what you think (here or as a review there). That will be the basis for new generic instructions.

**Comment by fuzz** [comment]
Awesome! I left a comment and will close this. https://github.com/crossplane/crossplane/pull/3396/files#r1008389936
