### ISSUE TITLE
PodMonitor template for crossplane helm chart

### ISSUE THREAD

**Issue by gmykhailiuta** [crossplane/crossplane#3422]
### What problem are you facing?
We would like to gather metrics from Crossplane and providers using Prometheus Operator. It requires a PodMonitor object(s) and it seems to be more convenient to have it as part of crossplane helm chart.

There was an attempt before - https://github.com/crossplane/crossplane/pull/2069, but it was closed more than a year ago without any comments.

Would a new PR be of any value?

**Comment by macmiranda** [comment]
May we add `PrometheusRules` chart support to this request @gmykhailiuta?

**Comment by macmiranda** [comment]
Actually, thinking about it, I don't really see the need for `PodMonitors` since we can use the scrape annotations for that.
I'll create a new issue for the `PrometheusRules` then

**Comment by gmykhailiuta** [comment]
Sure, adding `PrometheusRules` would be good.
