### ISSUE TITLE
Add PrometheusRules support to the chart and a few basic rules for monitoring

### ISSUE THREAD

**Issue by macmiranda** [crossplane/crossplane#3435]
### What problem are you facing?
Need to create `PrometheusRules` for monitoring so I can be alerted in the event something goes bad with the Crossplane controller(s) beyond the typical Kubernetes metrics.
I'm mostly talking about `go_` ,`controller_runtime_` or `workqueue_` metrics that could be useful for alerting.
@hasheddan already suggested how some of these metrics can be used for performance insights in this [article](https://danielmangum.com/posts/controller-runtime-scrape-prometheus-local/)

### How could Crossplane help solve your problem?
First of all, by adding support for `PrometheusRules` to the chart.
Second, by shipping a few basic monitoring rules that could be deployed out-of-the-box.

Let me know if you'd be interested in a PR for that

**Comment by abhi-dev91** [comment]
Hi @macmiranda I would like to contribute to this issue.

Please address that I have to only add these rules option in the chart's template or I have to add some additional metrics in the controller as well?

**Comment by macmiranda** [comment]
Hi @abhi-dev91

The metrics should already be there as per https://github.com/crossplane/crossplane/pull/1940

As long as you have a working Prometheus stack running on your cluster and you've set `.Values.metrics.enabled` to `true` when installing  the Crossplane chart, you should be able to access them via the Prometheus UI or Grafana

The next step would be to write some Prometheus rules using those metrics that actually give you good insight about the current state of the Crossplane controllers. 

Then you need to add those rules to the chart templates using the appropriate helm template syntax. Many other open-source projects have `prometheusRules`  examples you can use.

Let me know how I can support you better.

**Comment by abhi-dev91** [comment]
Hi, @macmiranda I have installed the helm chart with the following command `helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --set metrics.enabled=true`, but I was not able to see any metrics in prometheus. Do I need to add some additional config as well?

**Comment by macmiranda** [comment]
Hi, if possible share your deployment yaml and your prometheus scrape config

**Comment by yuzhouliu9** [comment]
I would be interested in having a toggle to enable `ServiceMonitor` for scraping and `PrometheusRules` for alerts. Would the crossplane maintainers be open to adding this to the helm chart?

**Comment by lucasfcnunes** [comment]
> I would be interested in having a toggle to enable `ServiceMonitor` for scraping and adding to `Service` to expose the /metrics endpoint at port 8080. Would the crossplane maintainers be open to adding this to the helm chart?

This!
