### ISSUE TITLE
v1.10.0 -> v1.10.1 client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#3451]
### What happened?
we updated our crossplane setup from v1.10.0 to v1.10.1 - all of our compositions logging the followings events:

```
Type   Reason      Age          From                               Message
 ----   ------      ----          ----                               -------
 Warning ComposeResources 26m (x107 over 23h)  defined/compositeresourcedefinition.apiextensions.crossplane.io cannot apply composed resource: cannot get object: client rate limiter Wait returned an error: context deadline exceeded
 Warning ComposeResources 6m19s (x120 over 23h) defined/compositeresourcedefinition.apiextensions.crossplane.io cannot apply composed resource: cannot patch object: client rate limiter Wait returned an error: context deadline exceeded
 Warning ComposeResources 2m19s (x344 over 23h) defined/compositeresourcedefinition.apiextensions.crossplane.io (combined from similar events): cannot apply composed resource: cannot get object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```

```
E1111 18:10:41.310576       1 request.go:977] Unexpected error when reading response body: context deadline exceeded
E1111 18:11:17.312892       1 request.go:977] Unexpected error when reading response body: context deadline exceeded
E1111 19:24:00.708991       1 request.go:977] Unexpected error when reading response body: context deadline exceeded
E1111 19:29:40.809045       1 request.go:977] Unexpected error when reading response body: context deadline exceeded

```

in debug we see the following:

```
1.6682022486090753e+09	DEBUG	crossplane	cannot establish control of object	{"controller": "packages/providerrevision.pkg.crossplane.io", "request": "/crossplane-provider-aws-b2f30f3b56f3", "uid": "06a88afe-0d37-48cd-a89b-96c501c4c2c5", "version": "445461270", "name": "crossplane-provider-aws-b2f30f3b56f3", "error": "client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
1.6682022486091592e+09	ERROR	crossplane.controller.packages/providerrevision.pkg.crossplane.io	Reconciler error	{"reconciler group": "pkg.crossplane.io", "reconciler kind": "ProviderRevision", "name": "crossplane-provider-aws-b2f30f3b56f3", "namespace": "", "error": "cannot establish control of object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
```

```
kubectl logs pod/crossplane-8669598697-prc22 -n crossplane-system | grep "Reconciling" | wc -l
    6890
```

### What environment did it happen in?
Crossplane version: v1.10.1

**Comment by hasheddan** [comment]
@haarchri thanks for this report! Carrying over a bit of our Slack conversation, I would guess that the behavior here is less about a change included in v1.10.1 (which https://github.com/crossplane/crossplane/pull/3427 was the only functional update, and it hopefully would reduce the reconcile churn on packages), and more about the fact that upgrading likely caused everything in the environment to get reconciled again, resulting in running up against the client-side rate limiter, then retrying periodically and running up against it again. A few questions that might help us dig in more here:

- Does downgrading back to v1.10.0 fix the behavior?
- Does a fresh install of v1.10.1, then installation of a similar amount of types and instances also result in this behavior?
- Are you seeing flapping health on packages / package revisions?
- Approximately how many packages / types / instances are present in the cluster?

Ultimately, I think this is another example of what is being seen in https://github.com/crossplane/crossplane/issues/3407, where the concurrent CRD establishment for Providers is causing us to run into some limits that were previously not an issue. I'm going to see if I can reproduce your exact case here 👍🏻

**Comment by MisterMX** [comment]
We experience the same issue with v1.10.0

**Comment by haarchri** [comment]
it looks like that we bumped memory and cpu - and crossplane runs stable again 
so think its related to: https://github.com/crossplane/crossplane/issues/3407
