### ISSUE TITLE
Empty overview section on XP docs

### ISSUE THREAD

**Issue by grantgumina** [crossplane/crossplane#3456]
### What happened?
When I expand the overview section, there isn't any content in there.

![image](https://user-images.githubusercontent.com/372681/203137716-04dc886b-7bd4-40e9-aa74-2581f9da8485.png)

I'd expect there to be some content in there, or none if `Overview` doesn't have sub-categories/docs.

### How can we reproduce it?
Go to any of the docs versions, and expand the overview accordion widget.

**Comment by plumbis** [comment]
This is fixed with the new docs.upbound.io site.
