### ISSUE TITLE
Move docs out of the crossplane/crossplane repo

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#3461]
### What problem are you facing?
There has been a long standing policy of having docs next to code.  As a result the /docs folder contains the docs for that release. After a release is cut, updates to the docs requires a backport patch to the specific branch.

This creates four main negative side effects:
1. There is no (simple) method to do local development of documentation and see styling of a docs contribution.
2. Docs updates across multiple versions are extremely inconvenient. The docs differ enough across releases it's not safe to copy/paste files across branches and it requires manual updates and multiple PRs.
3. No way to see a rendered preview of the PR. 
4. It's not obvious that docs shouldn't be updated on the website repo. For example website [issue #208](https://github.com/crossplane/crossplane.github.io/pull/208)

### How could Crossplane help solve your problem?
I propose moving the docs out of this repo and having the [docs website repo](https://github.com/crossplane/crossplane.github.io) act as the source of truth. 

### How does this address the negative issues mentioned?
1. Cloning the website repo and editing is now self-contained. Docs updates are created, tested and committed to the same repo.
2. All of the docs would live in a single parent directory with versions acting as a single sub-directory. Making changes across all versions of docs could be contained in a single commit and PR
3. With the imminent [move to Netlify](https://github.com/crossplane/crossplane.github.io/issues/98) will give the ability to have [deploy previews](https://docs.netlify.com/site-deploys/deploy-previews/). Any PR will generate a unique staging URL for the change that can be viewed by reviewers. This includes [PR feedback and markup](https://www.netlify.com/blog/2021/05/19/give-meaningful-feedback-with-collaborative-deploy-previews/) against the page contents.
4. There is only as single "docs" location. 

### Why Now?
The motivation for this is primarily driven by the value in doc relate PR review that Netlify will give us. Crossplane also now has a docs maintainer to manage and focus on documentation. 

Other projects break this out including:
* [Kubernetes](https://github.com/kubernetes/website)
* [Helm](https://github.com/helm/helm-www)
* [etcd](https://github.com/etcd-io/website)
* [Prometheus](https://github.com/prometheus/docs)

### Downsides?
* Releases will require work in another repo. This can be coordinated with the docs maintainer(s) or an automated PR can be issued to the docs repo.
* It won't be obvious where docs are for people looking at the source. We will need to clearly state in the README that docs are in a different repo.
* Changes to the `make` setup will be required to remove the docs component.

**Comment by hasheddan** [comment]
Just providing some context that https://github.com/crossplane/crossplane/pull/3375 added the ability to run docs locally from the Crossplane repo.

**Comment by plumbis** [comment]
> Just providing some context that #3375 added the ability to run docs locally from the Crossplane repo.

I would encourage maintaining a similar workflow with make for crossplane/crossplane maintainers but I would consider installing and using `make` (and submodules) an unnecessary barrier to entry for docs contributions.

**Comment by bassam** [comment]
What strategy are you proposing for maintaining multiple versions? Subdirectories for each supported version or branches?

**Comment by negz** [comment]
If we break out docs, what will the workflow be for contributors who are not dedicated docs maintainers, but who (e.g.) are adding or changing a Crossplane feature? I'm thinking for example a community member adding a new Composition transform. Would we need to ask them to go open a docs PR in a separate repository and then block their feature PR against c/c until that docs PR was merged?

**Comment by jeanduplessis** [comment]
In my opinion, the ideal scenario has always been for code and documentation to live together in the same repo. From a development process, you want to see code, test, and docs in the same PR, not separate ones.

The tooling and UI for docs can and likely should be in a separate repo which will pull in the docs files at build time.

**Comment by plumbis** [comment]
@bassam 
> What strategy are you proposing for maintaining multiple versions? Subdirectories for each supported version or branches?

Subdirectories. This is how the website is organized today.  There would be no change to the current docs repo.


@negz 
> If we break out docs, what will the workflow be for contributors who are not dedicated docs maintainers, but who (e.g.) are adding or changing a Crossplane feature? I'm thinking for example a community member adding a new Composition transform. Would we need to ask them to go open a docs PR in a separate repository 

Yes. The docs PR would be issued against the docs repo. This doesn't change the fact that the PR and issue discussions are still in the repo with the code along with any one-pagers or architectural specs.

> and then block their feature PR against c/c until that docs PR was merged?

No, docs should never block code. If there is code and no docs it means the code will be unused. I'm not implying this is a preferred situation but it lacks the anxiety that code without tests would generate.

@jeanduplessis 
>In my opinion, the ideal scenario has always been for code and documentation to live together in the same repo. From a development process, you want to see code, test, and docs in the same PR, not separate ones.

I understand this desire but we are only addressing the work flow of committing a new feature, and not addressing any other docs related workflow. Packing them together into a single PR makes it easier to see that docs were included, but it's no guarantee. The absence of docs in a PR may just imply it doesn't need them. 

I would suggest creating and mentioning a docs repo issue to show the need for docs are being tracked. I would go further to say this could improve the life of the developer. The developer can open a docs issue with their notes and ask for help from docs to write them. The writer starts working on the new docs and can reach out to the contributor who opened the issue with any questions. 

To both @jeanduplessis and @negz concerns I believe that keeping docs with code makes sense when the docs tooling is simple or if only developers are contributing docs. As the Crossplane docs mature we have [significantly more features](http://docs.crossplane.io/master/contributing/docs/). The visual component is now tightly coupled with the content itself. 


As @hasheddan mentioned there is a way to do local previews, but again, this doesn't solve the problems that make docs contributions challenging:
 - Requiring make
 - No way to do public PR previews (i.e., a webpage incorporating the PR to see it live on the web)
 - Patching against multiple releases

**Comment by jeanduplessis** [comment]
Do we have examples of other popular open-source projects who separate out their docs from code and has a healthy contribution from the community? For instance, I could be persuaded this is a good idea if it encourages and makes community contributions to documentation easier. Sometimes the easiest way to get into contributing to a project and giving back is by helping with the docs.

**Comment by plumbis** [comment]
Yes, other CNCF projects that do this include:
- [Kubernetes](https://github.com/kubernetes/website)
- [Helm](https://github.com/helm/helm-www)
- [etcd](https://github.com/etcd-io/website)
- [Prometheus](https://github.com/prometheus/docs)

> Sometimes the easiest way to get into contributing to a project and giving back is by helping with the docs.

100% agree! Our process now creates a confusing barrier to that. If you want to fix a docs bug you can't just edit a file,  you need to know about which repo and our branching strategy first. After that, install Make to verify that it works and _then_ you can submit a PR.

**Comment by plumbis** [comment]
Another justification for this is to apply more fine-grained access controls over the docs. 

Current only users with write access to the crossplane repo can accept PRs into the docs. There is no way to apply write access on a per-directory basis. Any docs change, including a typo or link fix requires a maintainer to approve. For example, #3470 and #3464.

**Comment by jeanduplessis** [comment]
I've come around to see why this might be a good idea and am in favor of supporting Pete's proposal. Practically, it adds a little bit of overhead to project contributors, but it sets us up to scale to better processes around documentation authoring as the project grows.

**Comment by negz** [comment]
> Practically, it adds a little bit of overhead to project contributors, but it sets us up to scale to better processes around documentation authoring as the project grows.

> The developer can open a docs issue with their notes and ask for help from docs to write them. The writer starts working on the new docs and can reach out to the contributor who opened the issue with any questions.

I'm a little wary of moving docs further from code, mostly due to the overhead added for project contributors.

Perhaps better understanding our approach to docs would help me here; are we "optimizing" for an "everyone writes documentation" approach, or are we imagining a team of documentation contributors somewhat distinct from the folks contributing (code) bug fixes, features, etc? The rationale I'm hearing in this issue makes me think we're going for the latter.

**Comment by negz** [comment]
> Current only users with write access to the crossplane repo can accept PRs into the docs. There is no way to apply write access on a per-directory basis. Any docs change, including a typo or link fix requires a maintainer to approve. For example, https://github.com/crossplane/crossplane/pull/3470 and https://github.com/crossplane/crossplane/pull/3464.

I think `CODEOWNERS` could help here. For example if we wanted a distinct "docs maintainer" (or docs focused maintainer) role to apply to c/c code we could:

1. Return to requiring approval from a CODEOWNER before a PR could be merged.
2. Make docs folks CODEOWNER of the `docs/`, but not other things.

This would effectively grant docs maintainers the ability to approve things that touched `docs/` but not other places.

**Comment by plumbis** [comment]
> I think CODEOWNERS could help here.

Adding users to CODEOWNERS still requires [write access to the repo](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). My point is "why give folks write access to the entire repo for a single folder?"

> are we "optimizing" for an "everyone writes documentation" approach, or are we imagining a team of documentation contributors somewhat distinct from the folks contributing (code) bug fixes, features, etc? The rationale I'm hearing in this issue makes me think we're going for the latter.

I don't see these as mutually exclusive. Making documentation contributions easier for anyone is a more inclusive operation. By reducing the barriers to entry for documentation contributions we reduce the load on the existing maintainers and grow our documentation.

With this proposal nothing stops someone contributing code from also contributing docs. Yes, it's a second repo, but the process for that documentation process is dramatically reduced over today's process.

What is different is that today's process is onerous to people without a strong understanding of git, make and/or our branching strategy. I'm part of the team and the reason I opened this issue is because of my struggles with patching older docs versions.

Yes, it will be more work for people contributing brand new features, however it will dramatically improve the ability for _any_ docs contributor by:
* creating PR specific preview URLs to enable anyone to browse a full docs built with the proposed PR
* simplifying back porting and fixing issues across versions
* making local development easier by reducing the repo size and removing the make requirement
* removing confusion about where docs edits should be submitted (crossplane/crossplane vs crossplane/crossplane.github.io)

**Comment by plumbis** [comment]
Administrative actions for this to happen:

## upbound/build Repo
1. Update the upbound/build docs.mk actions. ([PR #225](https://github.com/upbound/build/pull/225))

## crossplane/crossplane Repo
2. Update the crossplane/crossplane build submodule (TBD)
3. Update crossplane/crossplane Makefile to remove docs related components - #3538
4. Remove the docs publish workflow from crossplane/crossplane - #3538
5. Update crossplane release template to point to the crossplane/docs repo - #3538
6. Update the docs issue to redirect the author to the docs repo - #3538

## crossplane/docs Repo
1. Create a new Issues template for crossplane releases - [#243](https://github.com/crossplane/docs/pull/243)
2. Remove Makefile `publish` directive - [#243](https://github.com/crossplane/docs/pull/243)

**Comment by negz** [comment]
I discussed this with @plumbis and a few other folks in person - I support the move.
