### ISSUE TITLE
Copying values between two composed resources is unreliable, and breaks XRC encapsulation

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#3468]
#### Expected behavior

From https://github.com/crossplane/crossplane/blob/master/design/one-pager-composition-environment.md 

> It is also possible to copy values between two  
> composed resources inside one composition by patching the value from one  
> composed back to the composite and then to the second composed resource.
> 

From https://crossplane.io/docs/v1.10/reference/composition.html#patching-from-one-composed-resource-to-another

> Patching From One Composed Resource to Another
> 
> It’s not possible to patch directly from one composed resource to another - i.e. from one entry in the spec.resources array of a Composition to another. It is however possible to achieve this by using the XR as an intermediary. To do so:
> 
>     Use a ToCompositeFieldPath patch to patch from your source composed resource to the XR. Typically you’ll want to patch to a status field or an annotation.
>     Use a FromCompositeFieldPath patch to patch from the ‘intermediary’ field you patched to in step 1 to a field on the destination composed resource.
> 
> 

##### string copied within XR.metadata.annotation

Some slack threads such as https://crossplane.slack.com/archives/CEG3T90A1/p1651502304078839?thread_ts=1651495059.189299&cid=CEG3T90A1 mention

> Patches cannot reach across resources, so you need a ToCompositeFieldPath patch in the first resource to copy the privateIpAddress from status.atProvider.privateIpAddress to metadata.annotations.privateIpAddress, and then in the second resource use a FromCompositeFieldPath patch to copy from metadata.annotations.privateIpAddress into the nodes[0].address

However, I find usage of XR `metadata.annotations`  for internal computed outputs to be counter-intuitive, and inconsistent with MR conventions described at  https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md

> What goes into Spec and what goes into Status of a managed resource?
> [...]
> What goes into Status:
>
> *    Can the value of this field be reproduced when the whole Status is deleted? Do not include if the answer is no. 
>     Status sub-resource is the representation of the current state, so, the controller should be able to reproduce it as long
>      as the resource is still there. In practice, this means controller of that managed resource should not have to rely on 
>     Status fields of its custom resource while operating.
> 
> *    All fields except the ones that are chosen for Spec.
> 

##### string copied within XR.status

For string value being copied through the XR.status field, this only works if the XRD openapi schema declaration explictly declares the XRC.status field

Example: 

https://github.com/vfarcic/devops-toolkit-crossplane/blob/67f4b2d71ff37cbd9007eff267e54d70fac93e11/packages/k8s/dok.yaml#L73-L75
https://github.com/vfarcic/devops-toolkit-crossplane/blob/95a4797b565f31a5e4befaa6cf85723474d8df42/packages/k8s/definition.yaml#L56-L58

No debug/warning/error trace is produced in the crossplane pod, the related patch silently fails.

##### object copied from within XR.status

The object copied from within XR.status seems to not work regarless of it being declared in the XRD.status openapi schema. 

### How can we reproduce it?

See full diagnostic and reproductible cases into https://crossplane.slack.com/archives/CEG3T90A1/p1669134045416979

### What environment did it happen in?

Crossplane version: 1.10.1

/CC @mcanevet

Edit: updated to reflect existing documentation at https://crossplane.io/docs/v1.10/reference/composition.html#patching-from-one-composed-resource-to-another

**Comment by negz** [comment]
@gberche-orange For clarification, are you saying that even when using an 'intermediary' status field that was declared in the OpenAPI schema as a 'transport' when patching, doing so is unreliable (i.e. doesn't always work)?

Put otherwise, if we:

* Ensured patching to a non-existent field resulted in an error.
* Documented that you must patch to fields that exist.

Would that address this issue?

**Comment by gberche-orange** [comment]
thanks @negz for looking into this issue

 > For clarification, are you saying that even when using an 'intermediary' status field that was declared in the OpenAPI schema as a 'transport' when patching, doing so is unreliable (i.e. doesn't always work)?

It is likely that this unreliability perception is linked to server-side fields pruning as documented in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning (thanks to @natereid72 for his hint [on slack](https://crossplane.slack.com/archives/CEG3T90A1/p1669692576657679?thread_ts=1669134045.416979&cid=CEG3T90A1) ! )

> Put otherwise, if we: 
> *    Ensured patching to a non-existent field resulted in an error.
> *    Documented that you must patch to fields that exist.
> 
> Would that address this issue?

Yes, I believe this would address the reliability issue. This fix would be valuable for the composition authors.

In addition, from the point of view of a composition author, in order to preserve [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) it should be possible to copy values between two composed resources without leaking/surfacing copied fields into the XRC. 

Unintentionally Leaking copies fields in the XRC causes the following problems:
* the XRC contrat with users becomes clustered by meaningless technical fields. This damages the expected benefit of a controlled XRC which hides implementation details to consummers
* potential security issues

One specific example: a PostgresqlInstance composition which composes a gcp CloudSql and Kubernetes Object with a NeworkPolicy to grant egress access to the host returned in the CloudSql status. The XRC.status should not disclose a status.host which is rather instead published as a connection secret to the consummer.

Please, let me know if you'd prefer a distinct issue for tracking this requirement (which is not per-se a reliability issue).

**Comment by bobh66** [comment]
> In addition, from the point of view of a composition author, in order to preserve [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) it should be possible to copy values between two composed resources without leaking/surfacing copied fields into the XRC.

This is actually possible now using the composition environment.  You can use ToEnvironmentFieldPath and FromEnvironmentFieldPath patches to pass values through the environment which is not preserved across reconciliations.

Does this satisfy the requirement?

**Comment by gberche-orange** [comment]
thanks @bobh66 I'll try to test it and report back how well is worked for my use-case.
