### ISSUE TITLE
Docs: Document compositeDeletePolicy

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#3476]
As followup to the feature https://github.com/crossplane/crossplane/issues/3225 we should document that feature including options including use-cases. A great resource is the design doc: [design-doc-foreground-deletion.md](https://github.com/crossplane/crossplane/blob/master/design/design-doc-foreground-deletion.md)

**Comment by negz** [comment]
@luebken it's covered in the reference docs. Do you think it needs more?

https://crossplane.io/docs/v1.10/reference/composition.html

**Comment by luebken** [comment]
@negz Thanks. Somehow my search didn't find that page. 

I think the reference documentation is a good start. I do think there is room for a more elaborate example but we can tackle this if we face more questions from users.
