### ISSUE TITLE
RFO: DNS Outage November 28

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#3477]
The following is a postmortem of the DNS outage impacting crossplane.io on November 28, 2022.

----

## Summary:

Poor coordination with the CNCF on a planned DNS change resulted in an unexpected outage of most crossplane.io properties for approximately one hour on Monday Nov 28.

Missing DNS entries were added, resolving the issue. 

Since the migration was completed there is no chance of a recurrence. 

To prevent future issues, if there is another DNS migration, we should ensure there is a comprehensive list of DNS records and peer review that all entries are accounted for.

Beyond the specific technical outage, this exposed that infrastructure work with the CNCF should be done in a private CNCF Slack channel where others can be invited and be part of the communications. In this instance all work was done via Slack DMs removing the ability to add others to the conversation.

## Background:

Marketing initiated an effort to create a new crossplane.io landing page. To match the updated styles the Crossplane docs did the same. 

This created two new technical requirements:
1.) www.crossplane.io needs to move hosting from Github Pages to Vercel 
2.) crossplane.io/docs needs to move into its own subdomain (docs.crossplane.io)

At the same time there has been a push by the CNCF to move our website hosting from Github Pages to the CNCF Netlify account. Although www.crossplane has a technical requirement to be hosted on Vercel, docs.upbound.io will move to Netlify.

In order to move www.crossplane.io to Vercel, DNS records need to be updated. The CNCF/Linux Foundation controlled all DNS administration for *.crossplane.io. 

Since Netlify also provides DNS administration along with hosting it was decided we should move existing DNS entries from the CNCF to the Crossplane Netlify account to give the Crossplane maintainers control over our DNS.

This creates the following tasks:

Move the authoritative DNS from CNCF to Crossplane’s Netlify account for all existing entries.
Deploy an updated www.crossplane.io on Vercel
Deploy an updated docs.crossplane.io on Netlify
Update DNS records for www.crossplane.io and create a new docs.crossplane.io record.

The plan was to move all existing DNS records first (task 1), ensure stability with the existing properties and then address the new website deployments and additional DNS updates when CNCF involvement wouldn’t be required.

We worked with the CNCF to collect the existing DNS records, entering them into Netlify and then had a case opened with the CNCF IT team to execute the authoritative DNS change to point to the new Netlify service.

## The Outage

Due to the schedule of the individual at the CNCF we have been working to organize and get them to approve the planned DNS changes since the week of November 7. A great deal of time was spent just waiting on their availability for each step along the way (collect existing records, verify the Netlify entries, open the ticket with CNCF) . 

The ticket was opened with the CNCF IT team at around 1:30pm ET on November 28. No Crossplane members had visibility into the ticket. It was not communicated when the change would occur. The next communication from our CNCF helper was just before 7p ET telling us that the change was finalized. 

Now that DNS was pointing at Netlify, the missing DNS entries were revealed as outages for:
releases.crossplane.io
www.crossplane.io
charts.crossplane.io

DNS entries were added to Netlify for these domains and service was restored as soon as DNS propagated to the users (generally within a few minutes).

## Learnings

This outage exposed a few learnings:
1.) Executing changes with the CNCF should be done in a private Slack channel and not through DMs. 
By keeping the communication in DMs we made communication sharing to other stakeholders and members much more challenging. 

2.) The people involved in the change should have visibility. 
There was no visibility into the CNCF tickets by any Crossplane member. The lack of visibility was a major factor in the outage. Changes and actions should be clearly communicated across all stakeholders.

3.) Timelines and timetables should be established for 3rd party changes. 
The major issue with the CNCF was the “whenever they get to it” attitude that was taken by both Crossplane and CNCF. As a result there was no clearly defined timeline on when things would be done or how they would be communicated. The CNCF representative ended up being a go-between for Crossplane and CNCF IT doing the work but was minimally involved in the work. They became a critical component in the execution but had little investment in the transition being seamless. 

## Next Steps

The DNS migration was completed with this change last night. Crossplane now fully controls the DNS for all crossplane.io domains. This should prevent a similar outage for the upcoming docs.crossplane.io and www.crossplane.io migrations. 

These upcoming changes will also be executed entirely by Crossplane removing the third-party component, preventing the “telephone game” issue that related to the outages.

**Comment by plumbis** [comment]
This issue has been opened for transparency and community visibility. It will be closed within the next 24-hours.

**Comment by chaosaffe** [comment]
@plumbis I'm not sure if y'all are aware but https://crossplane.io is throwing 404s

**Comment by jbw976** [comment]
Thanks @chaosaffe for pointing that out - looks like Github pages (where the content for crossplane.io is currently hosted) ran into some issues with its certificate and the recent DNS changes.  This was unexpected, but we took the steps to update that certificate and crossplane.io looks to be back online now.

you can follow along with the discussion and debugging in full on Slack: https://crossplane.slack.com/archives/CEG3T90A1/p1669778935396709

**Comment by chaosaffe** [comment]
Awesome Jared, glad y'all got everything sorted!
