### ISSUE TITLE
k8s install crossplane ,then kubectl install configuration package have the problem :Error: failed to start container "provider-aws": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied": unknown

### ISSUE THREAD

**Issue by xiaozjw123** [crossplane/crossplane#3480]
### What environment did it happen in?
Crossplane version: 1.10.1

**Comment by xiaozjw123** [comment]
How should we solve this problem? Thank you  !

**Comment by MisterMX** [comment]
@xiaozjw123 thanks for opening this issue. However, the text is empty. Could you edit the description and adjust the formatting? Also please choose a speaking title i.e. `Cannot install configuration: permission denied` and put the error message in the description. Thank you!
