### ISSUE TITLE
Workload security design document

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#351]
Definition of done: Crossplane maintainers have ratified a design document outlining how Crossplane will ensure Workloads are deployed securely.

Each cloud provides various constructs around network isolation and security, for example VPCs, subnets, security groups, resource groups, firewall rules, etc. While some Crossplane resources may specify which subnet or security group they're in, Crossplane itself cannot create or reconcile these objects - it currently assumes that someone or something outside of Crossplane has set them up.

It could be that these security (and network) constructs could be abstracted to Crossplane Resource Bindings (e.g. `VirtualNetwork`, `FirewallRule`) like any other resource. One complication is that these resources 'support' other resources; i.e. a `MySQLInstance` may need a `VirtualNetwork` to exist before it can be deployed.

**Comment by negz** [comment]
One thought around the dependency problem - e.g. that a `MySQLInstance` won't start until its `VirtualNetwork` exists - could we just ignore it? i.e. Create the `MySQLInstance` with a resource class that requires a `VirtualNetwork`, then just let the reconcile loop fail until someone creates said `VirtualNetwork`?

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/pull/227 - Some prior art here from @lukeweber.

**Comment by lukeweber** [comment]
I know this goes a little further than the trust of this ticket, but just wanted to share. I was thinking a list of dependent resources as concept in crossplane could be fairly powerful and interesting, create/bind, and consume actual object's properties once it's ready.

Rough idea, but to illustrate:
MysqlInstance:
 Dependencies:
 - reference: rds_security_group # Actual local object name
    key: Status.GroupID
    fill: Spec.DBSecurityGroupID

The idea would be that we wouldn't start creating the object until it's dependencies are created and ready.

With MysqlInstance there's a bit of a dependency graph, but this is true of all of these resources.

MysqlInstance  ---- RDS Security Group ---- VPC Network (Subnets)
                           \---- RDSSubnetGroup  ----- / 

I'm not going to lay out the EKS example, but it's a much more complicated graph. The thing I like about dependencies is you could share SecurityGroups among resources.

**Comment by negz** [comment]
While installing Gitlab on AWS I thought I might be able to get everything to 'just work' security wise by using a single VPC and security group for everything (the EKS cluster, Postgres, and Redis). Unfortunately it seems that EKS worker nodes are placed in a security group created as part of the EKS creation process, not either of the security groups you specify when creating a cluster. This meant I had to explicitly allow incoming traffic to the security group in which Redis and Postgres were configured from the EKS worker node security group.

**Comment by jbw976** [comment]
This is related to #324, which looks like the implementation of the design captured in this issue.

**Comment by negz** [comment]
Related to #506, which is a slightly more concrete proposal on how this might be done.

**Comment by negz** [comment]
I don't know that were was ever a design for this, but we certainly support modelling network and security managed resources now, as well as how they relate to each other.
