### ISSUE TITLE
proper handling of multiple providerconfig's

### ISSUE THREAD

**Issue by xw-patrick** [crossplane/crossplane#3511]
### What happened?
Installing a crossplane configuration using:
`kubectl crossplane install configuration ... `
Allows to manage dependencies.
When I configure the following 2 dependencies (in crossplane.yml):
```spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: crossplane/provider-kubernetes
      version: ">=v0.5.0-0"
    - provider: crossplane/provider-helm
      version: ">=v0.9.0-0"
```

it will not allow me to properly manage the providerconfigs:
```gitpod /workspace/platform-ref-grapple (feature/grapi) $ k get providerconfigs.kubernetes.crossplane.io
NAME                  AGE
kubernetes-provider   74s
gitpod /workspace/platform-ref-grapple (feature/grapi) $ k get providerconfig
NAME                   AGE
helm-provider-config   81s
```

### How can we reproduce it?
- install the 2 providers (using crossplane.yaml)
- create 2 provider configs (for each provider one)
- list providerconfigs -A
- you will only see one providerconfig

### What environment did it happen in?
Crossplane version: crossplane/crossplane:v1.10.1
* Cloud provider or hardware configuration
==> civo 
* Kubernetes version (use `kubectl version`)
==> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by haarchri** [comment]
Did you tried;

kubectl get providerconfigs.kubernetes.crossplane.io
kubectl get providerconfigs.helm.crossplane.io

**Comment by xw-patrick** [comment]
> Did you tried;
> 
> kubectl get providerconfigs.kubernetes.crossplane.io kubectl get providerconfigs.helm.crossplane.io

@haarchri Thanks a lot. Yes, kubectl get works as you described... 
But when I define the a providerConfigRef in the composition, I cannot refer to it...
```
          providerConfigRef: 
            name: helm-provider-config
```
(it will not find the providerconfigs.helm.crossplane.io, but only the providerconfigs.kubernetes.crossplane.io)
Or at least I didn't find a way yet... Do you know how to do that?
Thanks a lot for you swift support!

**Comment by hasheddan** [comment]
@xw-patrick which part of your `Composition` contains this `providerConfigRef`? Each template should be able to set its own, and it will refer to the `ProviderConfig` of the corresponding `Provider` that installed the type.
