### ISSUE TITLE
Missing match as a type of transform 

### ISSUE THREAD

**Issue by portswigger-tim** [crossplane/crossplane#3514]
https://github.com/crossplane/crossplane/blob/4e4f57a80dc19d24bb712acaa853a836b6963dc9/apis/apiextensions/v1/composition_transforms.go#L83

It seems that there is a missing transform: `match` 😿

**Comment by jbw976** [comment]
Thanks for reporting this @portswigger-tim! Did #3515 resolve this issue for you? 🤔

**Comment by portswigger-tim** [comment]
It _should_ fix the problem (in `master`) - the problem being that the CRD missing `match` caused a validation error on trying to apply a composition with it in.
