### ISSUE TITLE
front page should state the level "incubation" for CNCF

### ISSUE THREAD

**Issue by csantanapr** [crossplane/crossplane#3517]
The main webpage https://www.crossplane.io/

At the bottom there is a logo of the CNCF, but is missing the statement "Crossplane is a [Cloud Native Computing Foundation](https://www.cncf.io/) incubation project"
![image](https://user-images.githubusercontent.com/1094878/206280305-ae23d041-1f37-48c0-b39f-092baa7e31e7.png)

Also is small and easy to missed.

**Comment by plumbis** [comment]
Thanks! This is fixed in [PR #21](https://github.com/crossplane/website/pull/21) for www.crossplane and docs PR [#225](https://github.com/crossplane/docs/pull/225)

**Comment by jbw976** [comment]
The copy recommendation in this issue doesn't match the guidelines we've been using from the CNCF.  See number 6 on https://github.com/cncf/foundation/blob/main/website-guidelines.md: 

> CNCF requests that graduated and incubating projects include the sentence “We are a Cloud Native Computing Foundation project.”

Is there alternative guidance you have seen that conflicts with this @csantanapr? I'd love to see the source you have, so we can resolve this conflict :)
