### ISSUE TITLE
argocd with crossplane: getting circular dependency warnings on each reconciliation attempt

### ISSUE THREAD

**Issue by avoidik** [crossplane/crossplane#3530]
### What happened?

every 180 seconds I'm getting few hundreds of unexpected warnings similar to this one

```
time="2022-12-13T17:18:28Z" level=warning msg="Circular dependency detected: map[{apiextensions.k8s.io CustomResourceDefinition  domainnames.apigateway.aws.crossplane.io}:true {pkg.crossplane.io Provider  provider-aws}:true {pkg.crossplane.io ProviderRevision  provider-aws-xyz}:true]."
```

these errors are getting generated by the argocd-application-controller, relevant code is here:
https://github.com/argoproj/argo-cd/blob/v2.5.4/controller/cache/cache.go#L280

it would be great to find out what's going wrong here to be able to get rid of these warnings completely

here is an example of such a circular dependency

![image](https://user-images.githubusercontent.com/6435932/207430966-4a9bb0fe-9fc8-4a69-94a0-3719c548b49d.png)

### What environment did it happen in?

This is K8s cluster on EKS

Crossplane version:

- crossplane/crossplane:v1.9.0
- crossplanecontrib/provider-aws:v0.33.0
- crossplane/provider-kubernetes-controller:v0.3.0

ArgoCD version:

- argocd:v2.5.4 (resource tracking method is set to "annotation")

Kubectl output:

```terminal
$ kubectl version --short
Client Version: v1.23.13
Server Version: v1.23.13-eks-fb459a0
```

**Comment by avoidik** [comment]
xref. https://github.com/argoproj/argo-cd/issues/11699

**Comment by jbw976** [comment]
Thanks for reporting this behavior @avoidik - I'm not quite sure I understand it yet 😊 

Looking at your helpful screenshot and the error message, I don't see where the circular dependency is just yet.  `CRD`s are owned by `Provider` and `ProviderRevision`, and `ProviderRevision` is owned by `Provider`.  I don't see a cycle in this graph - am I missing something, or is this a bug in the Argo logic? 🤔 

```mermaid
  graph LR;
      CRD-->Provider;
      CRD-->ProviderRevision;
      ProviderRevision-->Provider;
```

**Comment by natereid72** [comment]
@avoidik Are you looking at the correct CRD in your screenshot above? Looks like it is complaining about `domainnames.apigateway.aws.crossplane.io`, not `providerconfigs.kubernetes.crossplane.io`

**Comment by avoidik** [comment]
as far as I can see this is entirely an argocd issue, please check https://github.com/argoproj/argo-cd/pull/12667
