### ISSUE TITLE
Crossplane Composition Kustomize Bug

### ISSUE THREAD

**Issue by martinflemingdev** [crossplane/crossplane#3558]
### What happened?

Using `Kustomize` to patch an array item in a Composition replaces the entire array item with the patch instead of appending/merging like expected. 

### How can we reproduce it?

Please see this repo for complete explanation with examples and steps to reproduce:
[github-crossplane-composition-kustomize-bug](https://github.com/martinflemingdev/crossplane-composition-kustomize-bug)

### What environment did it happen in?

Since this is a bug with the Composition CRD being patched with Kustomize, Crossplane is not directly used.

The composition apiVersion is apiextensions.crossplane.io/v1
Kubectl version is v1.25.0 (Kustomize included since v1.14)

NOTE: Using same env with native Kubernetes object like Deployment and patching array item works as expected (examples in repo above)

**Comment by bobh66** [comment]
Should the kustomize configuration use patchesStrategicMerge instead of patches?

**Comment by martinflemingdev** [comment]
It tried that and it also does not work. According to Kustomize documentation it should infer the merge, but I will alter the repo to explicitly use patchesStrategicMerge.

**Comment by martinflemingdev** [comment]
Changed "patches" to "patchesStrategicMerge" in both overlays' kustomization.yaml's to be as explicit as possible. Bug remains.

**Comment by bobh66** [comment]
Ok - I'm just not sure what Crossplane can do to fix this - if kustomize is doing the work?

**Comment by martinflemingdev** [comment]
Looking around at similar issues, it appears the Composition CRD does not define correct merge keys for all array/list types. Crossplane could fix the Composition CRD.

**Comment by bobh66** [comment]
OK, it looks like x-kubernetes-patch-merge-key is defined here - https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/README.md#x-kubernetes-patch-strategy-and-x-kubernetes-patch-merge-key and that it is used by server-side patching in the kubernetes API server - https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#notes-on-the-strategic-merge-patch

For this to be useful kustomize would have to have access to the Composition CRD, either by querying a kubernetes cluster that has the Composition CRD installed or via the crds list in the kustomization.yaml file:  https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/

but when I created a composition.yaml file and added it to the kustomization.yaml crds section it fails to read the spec: 
```
Error: loading CRDs [composition.yaml]: unable to parse open API definition from 'composition.yaml': error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type accumulator.OpenAPIDefinition
```
Using this method you could add the x-kubernetes-patch-merge-key and see if it works but I don't know how to get kustomize to read the API spec from the CRD.

I'm not sure why it needs a merge key to add an object to an array - it shouldn't care if there are duplicate objects in the array, which could be valid.
