### ISSUE TITLE
Pin to specific Go patch releases in CI

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#3571]
### What problem are you facing?

We currently [pin CI to Go minor version](https://github.com/crossplane/crossplane/blob/3b22fcba51b1a445146cce539a338d06f6ee9a79/.github/workflows/ci.yml#L13) via the [setup-go](https://github.com/actions/setup-go) action. The motivation for doing so is reducing the manual toil in updating to new patch  versions when released (though it is worth noting that we don't currently enable [check latest](https://github.com/actions/setup-go/tree/v2.2.0#check-latest-version) functionality so we likely are not updating as frequently as we would like). However, this also means that running CI on the same commit at different points in time may not produce identical builds. The only way to determine what version of Go our binaries were built with is by downloading and inspecting the binary.

This is particularly cumbersome when updating to a specific Go version is necessary due to vulnerabilities or a significant bug. The existing published binaries would need to be inspected, as would any subsequent patch to update the Go version (i.e. the patch would be subject to the action fetching the patch version of Go that we want).

### How could Crossplane help solve your problem?

Running our CI pipelines on the same commit should produce the same output, regardless of when they are run. We ensure this for dependencies by committing our `go.mod`/`go.sum` and tooling by pinning to specific versions in our `make` machinery. Likewise, we reference base images by digest in our Dockerfile to ensure we are getting the same content. Because our GitHub workflows are also committed to this repo, we could ensure the same reproducability by pinning to full patch release versions of Go, rather than just minor versions. Alternatively, we could move downloading Go into the `build` submodule machinery and pin the version in our `Makefile` similar to how we manage other tooling. This would provide the advantage of making the build reproducible outside of our specific CI as well.

This does create some additional toil on maintainers, but it is something we could automate via tools like Dependabot or Renovate -- something @phisco has already proposed introducing in https://github.com/crossplane/crossplane/pull/3566 (note: there may be some configuration necessary to have it propose an update to the workflow files).

**Comment by phisco** [comment]
Feel free to assign this to me, I'm setting up renovate and turns out it's able to handle this pretty easily.

**Comment by hasheddan** [comment]
Done!
