### ISSUE TITLE
Move Crossplane Docs Issues

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#3577]
The following crossplane/crossplane issues are docs related and should be moved to the [crossplane/docs](https://github.com/crossplane/docs) repo. (I don't have sufficient c/c repo permissions).

* crossplane/docs#273 
* crossplane/docs#274
* crossplane/docs#275
* crossplane/docs#276
* crossplane/docs#277
* crossplane/docs#278
* crossplane/docs#279
* crossplane/docs#280
* crossplane/docs#281
* crossplane/docs#282
* crossplane/docs#283
* crossplane/docs#283
* crossplane/docs#285
* crossplane/docs#286
* crossplane/docs#287
* crossplane/docs#288

**Comment by negz** [comment]
Moving these should be pretty straightforward, I'll set a reminder to do it on Tues.

**Comment by jbw976** [comment]
I had some free time now, so I took care of moving all these issues to the docs repo ✅
