### ISSUE TITLE
Consider making package installation concurrency configurable

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#3598]
### What problem are you facing?

In the `v1.10.0` release, the time in which it took to establish the resources from a package in the cluster was reduced by installing them concurrently. While this made it such that users did not have to wait as long for the package types to be available, it also resulted in spikes in Crossplane CPU and increased load on the k8s API Server. Currently the number of goroutines used in establishment is [hard-coded to 10](https://github.com/crossplane/crossplane/blob/a5c2e288c91aca65130ccaf9503deaf8448f8868/internal/controller/pkg/revision/establisher.go#L46).

### How could Crossplane help solve your problem?

To spread the load of installing resources, establishment could be made configurable either via exposing the number of goroutines to the end used, or via levels that map to goroutine count.

xref https://github.com/crossplane/crossplane/issues/3540 https://github.com/crossplane/crossplane/issues/3407

> NOTE: the consistently high CPU described in the issues above has been addressed. This issue is only tracking smoothing the spikes.

**Comment by negz** [comment]
@hasheddan Do you think we should target this for v1.12?

**Comment by hasheddan** [comment]
@negz I do 👍🏻
