### ISSUE TITLE
Cut v1.11.0 on Jan 31, 2023

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3600]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.7] for
examples of each step.

- [x] Prepare the release branch at the beginning of [Code Freeze]:
  - [x] Created the release branch.
  - [x] Created and merged an empty commit to the `master` branch.
  - [x] Run the [Tag workflow][tag-workflow] on the `master` branch with the next release candidate tag.
- [x] Open a [docs release issue].
- [x] Run the [Tag workflow][tag-workflow] on the relevant release branch with the proper release version.
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel..
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [xpkg.upbound.io] for all getting started packages.
  - [x] `xp/getting-started-with-aws`
  - [x] `xp/getting-started-with-with-with-vpc`
  - [x] `xp/getting-started-with-azure`
  - [x] `xp/getting-started-with-gcp`
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel.
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes.
  - https://github.com/crossplane/crossplane/releases/tag/v1.11.0
- [x] Update the [`crossplane/test` repo test workflows][crossplane-test-workflows] to ensure the checkout release branch and helm install version(s) point at the new release
  - https://github.com/crossplane/test/pull/37
- [x] Update the `baseBranches` list in renovate's configuration file, `.github/renovate.json5`, with the new release branch, removing the old unsupported release one.
  - #3696
- [x] Ensure that the v1.11 docs release has been completed and new docs are live
  - https://github.com/crossplane/docs/issues/304
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: https://crossplane.slack.com/archives/CEFQCGW1H/p1675213359843489
  - [x] Twitter: https://twitter.com/crossplane_io/status/1620587883399901186
- [x] Updated the [releases table] in the `README.md` on `master`.
  - #3697
- [x] Request @jbw976 to remove the EOL docs version from Google Search

[docs release issue]: https://github.com/crossplane/docs/issues/new?assignees=&labels=release&template=new_release.md&title=Release+Crossplane+version...+
[releases.crossplane.io]: https://releases.crossplane.io
[xpkg.upbound.io]: https://cloud.upbound.io/browse
[new release]: https://github.com/crossplane/crossplane/releases/new
[releases table]: https://github.com/crossplane/crossplane#releases
[Crossplane docs website repo]: https://github.com/crossplane/docs
[docs removal directive]: https://github.com/crossplane/crossplane/pull/3003
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[crossplane-test-workflows]: https://github.com/crossplane/test/tree/master/.github/workflows
[release-1.7]: https://github.com/crossplane/crossplane/issues/2977
[Code Freeze]: https://crossplane.io/docs/master/reference/release-cycle.html#code-freeze

**Comment by negz** [comment]
@phisco (our newest reviewer) is going to take this one. I can't assign to him yet as we're still getting him added to the @crossplane org.

**Comment by negz** [comment]
Some things to remember for this release:

* We need to manually add a release note capturing the fact that this will be the last release published to Docker Hub per https://github.com/crossplane/crossplane/issues/3560

Some not-techncially-breaking changes we should nonetheless call out:

* This release drops the v1alpha1 `Lock` API type per https://github.com/crossplane/crossplane/pull/3479
* We change the way CompositionRevisions are named and labelled per https://github.com/crossplane/crossplane/pull/3391

Some general highlights to call out:

* CompositionRevisions are now on by default, v1beta1.
* Environment support is now available in alpha.
* Composition Function support will be available in alpha.

**Comment by jbw976** [comment]
And also:
- [ ] #3601

**Comment by phisco** [comment]
Docs release issue created: https://github.com/crossplane/docs/issues/304

**Comment by jbw976** [comment]
All tasks in this issue are completed, and artifacts are linked inline within the task list.

Release v1.11.0 is complete! 💪

**Comment by jbw976** [comment]
Further improvements to the release issue template are being tracked in #3701, which we'll tackle before the v1.12 release
