### ISSUE TITLE
Mark `ControllerConfig` as deprecated in Crossplane `v1.11.0`

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#3601]
### What problem are you facing?

The `ControllerConfig` API has been marked as `v1alpha1` since it was added to Crossplane in `v0.14.0`. There is a [longstanding issue](https://github.com/crossplane/crossplane/issues/2468) tracking promoting it to `v1beta1`, but there has been push back for a variety of reasons:
- The `ControllerConfig` API has grown to essentially mirror the k8s `Deployment` API, without being fully compliant. This results in some community members needing fields that are not present. The quick solution here would be to make the `ControllerConfig` mirror `Deployment` 1:1.
- The current API, as well as an API that became identical to `Deployment`, forces all Providers to be run as `Deployments`. While this is the common mode of operation today, it is not necessarily the only one that should be supported. Provider controllers need to be scheduled to compute and be given proper access to the Kubernetes API server, but the type of compute is not fundamentally constrained to being provided by Kubernetes, and certainly not the same Kubernetes cluster where core Crossplane is running.
- `ControllerConfig` only considers one Provider during processing. You cannot author a `ControllerConfig` with logic that depends on the state of other Providers or other external information.

Ideally, users would be able to have full freedom in determining how Provider controllers are run. While many will likely find a solution similar to the built-in one we have today acceptable, there are others who will want to adopt other implementations, or even design their own. Decoupling that functionality from the core Crossplane logic means that iteration and experimentation can happen more freely. The current thinking is that functionality similar to what is described will be implemented via a mechanism that resembles the [Provider Runtime Interface RFC](https://github.com/crossplane/crossplane/issues/2671).

### How could Crossplane help solve your problem?

[Alpha features](https://docs.crossplane.io/v1.10/reference/feature-lifecycle/#alpha-features) in Crossplane are subject to removal from one version to the next without warning. However, `ControllerConfig` was introduced prior to this policy being established and so despite being an alpha API, it is **not** off by default. There is also strong signal (based on PRs / issues / slack activity) that many folks use the `ControllerConfig` API today to configure functionality such as [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

As a community, we always aim to give users a good experience and strive for open and explicit communication. Because we do not plan to promote `ControllerConfig` to `v1beta1`, it is in violation of our feature lifecycle policy (after we close the existing promotion issue), which states that every `alpha` feature should have an issue tracking its promotion. With the context around user adoption, we do not want to remove `ControllerConfig` immediately, despite it being an `alpha` feature. However, **we do want to signal our intent to eventually remove this API** as early as possible. As such, this issue is proposing **marking the `ControllerConfig` API as deprecated in Crossplane `v1.11.0`** and communicating the information shared here in the release notes. This is also proposing that **we refrain from removing the API until there is a reasonably mature alternative implementation**.

**Comment by bobh66** [comment]
I think the solution to #2671 is required to be available before ControllerConfig can be removed.

**Comment by hasheddan** [comment]
@bobh66 absolutely -- that is what the last sentence of the proposal is alluding to 👍🏻

**Comment by turkenh** [comment]
I am not against deprecating it but we should consider other (future) extension types that may require a K8s deployment. We may need something similar to `ControllerConfig` for Secret Store Plugin packages, I just left a comment on https://github.com/crossplane/crossplane/issues/2671#issuecomment-1404880662

**Comment by hasheddan** [comment]
@turkenh thanks for the context! This potential additional use-case makes the deprecation of `ControllerConfig` feel even more appropriate given that it would be pretty confusing to use an API for "configuring controllers" for workloads that are not actually controllers. I'll continue discussion on #2671 👍🏻

**Comment by avoidik** [comment]
what will be an alternative to `ControllerConfig` being deprecated?

**Comment by hasheddan** [comment]
@avoidik there is a proposal for a runtime interface that allows for a variety of implementations:

> The current thinking is that functionality similar to what is described will be implemented via a mechanism that resembles the [Provider Runtime Interface RFC](https://github.com/crossplane/crossplane/issues/2671).

A design will need to be ratified before implementation.

**Comment by negz** [comment]
I'm fairly sure this was done.
