### ISSUE TITLE
Proposal: Adopt Architectural Decision Records (ADRs)

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3602]
### What problem are you facing?

Ideally it would be possible to understand in a fairly high level of detail what exactly all the parts of Crossplane are and why they are that way by reading all the design documents in https://github.com/crossplane/crossplane/tree/master/design. This is _somewhat_ true today - everything major does go through a thorough design process. Where it's lacking is:

* Smaller self contained features are sometimes only captured as a Proposal issue.
* Similarly, we often only track the evolution of larger features in Proposal issues and PRs.

The original Composition design document is a great example of this - it's still a broadly accurate representation of the problem being solved and how we solved it but contains a bunch of outdated terminology, and entire concepts that were never actually implemented.

### How could Crossplane help solve your problem?

I'd like to experiment with https://adr.github.io. I haven't used these much myself, but I like the idea - I see them as essentially small "diffs" or "patches to" a design document. Even with our design documents being under version control, I prefer this approach of producing new artifacts to capture small changes/decisions over time. This appeals to me because updating the design doc over time often feels like trying to edit history, potentially making historical context harder to find.

**Comment by ytsarev** [comment]
/fresh it seems like a good idea
