### ISSUE TITLE
Remove abandoned charts from `crossplane-master`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3631]
### What problem are you facing?

There's a bunch of ancient, abandoned stuff in the `crossplane-master` Helm repo (`crossplane-stable` looks good). I suspect folks might find these confusing, or at least distracting.

```
$ helm search repo crossplane-master --devel
NAME                                            CHART VERSION                   APP VERSION                     DESCRIPTION
crossplane-master/crossplane                    1.11.0-rc.0.274.g51a07e50       1.11.0-rc.0.274.g51a07e50       Crossplane is an open source Kubernetes add-on ...
crossplane-master/crossplane-controllers        0.13.0-rc.191.g3a18fb7          0.13.0-rc.191.g3a18fb7          Crossplane - Managed Cloud Resources Operator
crossplane-master/crossplane-types              0.13.0-rc.191.g3a18fb7          0.13.0-rc.191.g3a18fb7          Crossplane - Managed Cloud Resources Operator
crossplane-master/gitlab-controller             0.0.0-43.90e2a0e                0.0.0-43.90e2a0e                GitLab Controller - GitLab Crossplane Application
crossplane-master/oam-kubernetes-runtime        0.4.0-rc1.18.g64a2994           0.4.0-rc1.18.g64a2994           A Helm chart for OAM Kubernetes Resources Contr...
crossplane-master/oam-kubernetes-runtime-legacy 0.4.0-rc1.18.g64a2994           0.4.0-rc1.18.g64a2994           A Helm chart for OAM Kubernetes Resources Contr...
```

### How could Crossplane help solve your problem?

It would be nice to delete everything that is abandoned - basically everything in `crossplane-master` apart from `crossplane-master/crossplane`.

**Comment by negz** [comment]
I'm just going to do this next week unless anyone complains.

**Comment by jbw976** [comment]
I think the basic steps here would be as below, but I'm not sure how much automation we have for this type of operation vs what would need to be manual as a 1-time clean up operation.

I think this probably only exists in the `master` and `alpha` channels, I don't see any of them in `stable` or `alpha`

* Delete the old tarballs from bucket, e.g. https://charts.crossplane.io/master/ 
* Update the index file to remove all these old charts entries, e.g. https://charts.crossplane.io/alpha/index.yaml

It would be worthwhile to dig a bit in to the makefile automation we have for publishing helm charts to see if there's any logic that would help with this.  A relevant looking section is https://github.com/upbound/build/blob/master/makelib/helm.mk#L130-L142, which has logic to (emphasis on **reindex** mine):

> copy existing charts to a temp dir, the combine with new charts, **reindex**, and upload
