### ISSUE TITLE
Separation of infrastructure concerns among clusters

### ISSUE THREAD

**Issue by emedina** [crossplane/crossplane#365]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The use case I would like to see moving forward is the separation of the different infrastructure concerns in different clusters.

**What is use case behind this feature:**
Think about dynamic storage provisioning with Rook for Kubernetes. Currently my Rook cluster needs to run in the same cluster where I am running all my stateful workloads. What if I could run a separate cluster for Rook, but still be able to provision storage to the other cluster for stateful workloads?

**Environment**:

Kubernetes and Rook

**Comment by negz** [comment]
I think this is technically possible under Crossplane's current architecture; it's mostly a question of whether a provider (e.g. provider-rook) supports this.
