### ISSUE TITLE
Implement Pluggable Secret Stores

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#3670]
### What problem are you facing?

In the [v1.7.0](https://github.com/crossplane/crossplane/releases/tag/v1.7.0) Crossplane release, we have introduced support for publishing connection details secrets to [External Secret Stores](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md) as an alpha feature. With this initial iteration, we have focused on the in-tree implementation of secret stores by adding [Hashicorp's Vault](https://vaultproject.io/) support as our first External Secret Store. However, this approach introduces [additional dependencies](https://github.com/crossplane/crossplane-runtime/pull/322/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R52) to Crossplane core and would not scale once the community wants to support more secret stores. 

### How could Crossplane help solve your problem?

We already have [the design](https://github.com/crossplane/crossplane/blob/master/design/one-pager-pluggable-secret-stores.md) in place, and we need to implement it before promoting the External Secret Stores feature to beta.

**Comment by negz** [comment]
Just to help scope this WRT the v1.12 milestone - what's the "definition of done" here? I'm guessing it won't include building many (any?) secret store implementations, right?

**Comment by jeanduplessis** [comment]
With the implementation landing in 1.12 we can now close this issue.
