### ISSUE TITLE
Not able to create IAM Role using assumeRole in providerConfig

### ISSUE THREAD

**Issue by ankursharmalb** [crossplane/crossplane#3675]
Hi Team, I am trying to create an IAM role using corssplane. It works fine when I create directly in the AWS account. But I am Using assumeRole in providerConfig, it doesn't work. I am getting below error.
I am able to create other resources using same assumeRoleProvider config.
Assume role has admin access so no restriction of creating IAM Roles.
**Error:** 
 Conditions:
    Last Transition Time:  2023-01-25T11:38:38Z
    Message:               connect failed: cannot get terraform setup: failed to retrieve aws credentials from aws config: failed to refresh cached credentials, operation error STS: AssumeRole, failed to resolve service endpoint, an AWS region is required, but was not found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced

**assumeRoleproviderConfig.yaml**

apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: "temp-account"
spec:
  assumeRoleChain:
    - roleARN: "arn:aws:iam::REDACTED:role/TestRole"
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-master-secret
      key: creds

**Role.yaml**

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: sample-node-role
spec:
  providerConfigRef:
    name: "temp-account"
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }

**Comment by cychiang** [comment]
Hi, 
From the message you have shared, you may need to specify the region in the credential file to respect the following error message:
```
failed to resolve service endpoint, an AWS region is required, but was not found
```

You can take a look on this [document](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).

**Comment by haarchri** [comment]
Think it's related to https://github.com/upbound/provider-aws/pull/451

**Comment by cychiang** [comment]
Thanks for sharing. Looks like it's related.

**Comment by haarchri** [comment]
Please followup in upbound provider-aws thanks
