### ISSUE TITLE
Improved revision resource ownership transition

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#3742]
### What problem are you facing?

When a `Provider` or `Configuration` is updated, a new `ProviderRevision` / `ConfigurationRevision` is created and ownership of the resources that are installed by both revisions is transitioned from the old revision to the new one. However, if the old revision is unable to go through a successful reconciliation with status `Inactive`, its controller references on the resources may not be transitioned to owner references. This prevents the new revision from being installed successfully as it cannot gain control of all resources. This commonly occurs if an old revision is deleted before successful transition.

### How could Crossplane help solve your problem?

A simple solution here would be to include the controller --> owner transition in the [deletion path](https://github.com/crossplane/crossplane/blob/0162f73e10cdb6fb9e24ba3713fcd7f02f4326b0/internal/controller/pkg/revision/reconciler.go#L354), rather than just the `Inactive` path. This would mean that we would refuse to remove the finalizer on a revision until it successfully transitioned controller --> owner. If it was unable to do so, an appropriate error would be surfaced to users, rather than just the somewhat opaque "cannot establish control" that users typically see today on the new revision today.

**Comment by haarchri** [comment]
@hasheddan  thanks for the ref - was not aware of this issue ;)

**Comment by hasheddan** [comment]
@haarchri sure thing! Also with the Crossplane / UXP issue, we should absolutely get that sorted out, but in the mean time you can always use https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.11.3#spec-ignoreCrossplaneConstraints if needed 👍🏻

**Comment by turkenh** [comment]
> xref [#3423 (comment)](https://github.com/crossplane/crossplane/issues/3423#issuecomment-1495717622)

I could reproduce the above issue with a slightly simpler flow only with a provider (thanks to @haarchri's detailed one):

1. Install Crossplane v1.11.0

```bash
helm upgrade --install crossplane --namespace crossplane-system crossplane-stable/crossplane --version v1.11.0 --create-namespace
```

2. Deploy a modified version of provider-helm (`v0.3423.0`) that has a strict dependency to Crossplane `v1.11.0`.

```
spec:
  crossplane:
    version: "v1.11.0"
```

```bash
echo "apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/hasan/provider-helm:v0.3423.0" | kubectl apply -f -
```

3. Update it to `v0.3423.1` which is exactly the same as `v0.3423.0`.

```bash
echo "apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/hasan/provider-helm:v0.3423.1" | kubectl apply -f -
```

```bash
❯ kubectl get providerrevision

NAME                         HEALTHY   REVISION   IMAGE                                           STATE      DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-70c4d0ca19e9   True      2          xpkg.upbound.io/hasan/provider-helm:v0.3423.1   Active                                 43s
provider-helm-71d0f429c272   True      1          xpkg.upbound.io/hasan/provider-helm:v0.3423.0   Inactive                               56s

❯ kubectl get locks.pkg.crossplane.io lock -o yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  ...
packages:
- dependencies: []
  name: provider-helm-70c4d0ca19e9
  source: xpkg.upbound.io/hasan/provider-helm
  type: Provider
  version: v0.3423.1
```

4. Upgrade to Crossplane v1.12.0

```
helm upgrade --install crossplane --namespace crossplane-system crossplane-stable/crossplane --version v1.12.0
```

5. Wait for some time until `ProviderRevisions` reconciled at least once:

```bash
❯ kubectl get providerrevision

NAME                         HEALTHY   REVISION   IMAGE                                           STATE      DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-70c4d0ca19e9   False     2          xpkg.upbound.io/hasan/provider-helm:v0.3423.1   Active                                 3m4s
provider-helm-71d0f429c272   False     1          xpkg.upbound.io/hasan/provider-helm:v0.3423.0   Inactive                               3m17s

> kubectl describe providerrevision provider-helm-70c4d0ca19e9

...
  Warning  LintPackage        42s (x3 over 43s)      packages/providerrevision.pkg.crossplane.io  incompatible Crossplane version: package is not compatible with Crossplane version (v1.12.0)
```

6. Upgrade to provider-helm `v0.3423.2` which has Crossplane dependency as `">=v0.0.0-0"`

```bash
echo "apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/hasan/provider-helm:v0.3423.2" | kubectl apply -f -
```

```bash
❯ kubectl get providerrevisions.pkg.crossplane.io

NAME                         HEALTHY   REVISION   IMAGE                                           STATE      DEP-FOUND   DEP-INSTALLED   AGE
provider-helm-70c4d0ca19e9   False     2          xpkg.upbound.io/hasan/provider-helm:v0.3423.1   Inactive                               5m52s
provider-helm-d1a5bfbb739f   Unknown   3          xpkg.upbound.io/hasan/provider-helm:v0.3423.2   Active                                 19s

❯ kubectl describe providerrevision provider-helm-d1a5bfbb739f

...
  Warning  ResolveDependencies  18s (x5 over 116s)   packages/providerrevision.pkg.crossplane.io  cannot resolve package dependencies: node already exists
```

```bash
❯ kubectl get locks.pkg.crossplane.io lock -o yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  ...
packages:
- dependencies: []
  name: provider-helm-70c4d0ca19e9
  source: xpkg.upbound.io/hasan/provider-helm
  type: Provider
  version: v0.3423.1
- dependencies: []
  name: provider-helm-d1a5bfbb739f
  source: xpkg.upbound.io/hasan/provider-helm
  type: Provider
  version: v0.3423.2
```

**Comment by turkenh** [comment]
Digging further, I could identify what is happening:

Everything was fine until step 6 above, when we upgraded our package to a working one with valid dependency:

- Revision 3 is created as Active
- Revision 2 is marked as Inactive
- Reconciliation of Revision 2 returned [early](https://github.com/crossplane/crossplane/blob/e40d04c66f0783352d6970809f30d75e3d396d8d/internal/controller/pkg/revision/reconciler.go#L553) because of a failing XP dependency check before it could remove itself from the Lock [here](https://github.com/crossplane/crossplane/blob/e40d04c66f0783352d6970809f30d75e3d396d8d/internal/controller/pkg/revision/reconciler.go#L560).
- Reconciliation of Revision 3 started failing since now we have two nodes in the dependency graph with same identifier (e.g. source).

As a quick fix, I tried to move the [removal of inactive revision](https://github.com/crossplane/crossplane/blob/e40d04c66f0783352d6970809f30d75e3d396d8d/internal/controller/pkg/revision/dependency.go#L74-L76) from the lock to an early stage in the reconciliation, e.g., before xp constraint check. This fixed the issue with duplicate nodes, i.e., the `node already exists` error. However, this time, `Revision 3` started failing with the infamous `is already controlled by ProviderRevision` error. Checking again, this is expected since this time, `Revision 2` reconciliation couldn't reach to the point where we [unestablish control of objects](https://github.com/crossplane/crossplane/blob/e40d04c66f0783352d6970809f30d75e3d396d8d/internal/controller/pkg/revision/reconciler.go#L584) when the revision is inactive.

**Comment by turkenh** [comment]
> However, if the old revision is unable to go through a successful reconciliation with status Inactive, its controller references on the resources may not be transitioned to owner references.

So, the above scenario is one of the many possible scenarios where an inactive package revision couldn't go over a successful reconciliation and transfer ownership of resources to the new revision (and remove itself from the lock).

> A simple solution here would be to include the controller --> owner transition in the [deletion path](https://github.com/crossplane/crossplane/blob/0162f73e10cdb6fb9e24ba3713fcd7f02f4326b0/internal/controller/pkg/revision/reconciler.go#L354), rather than just the Inactive path.

This would only solve one possible (and common) scenario where an old revision is deleted before a successful transition but not the one investigated above. 

I am wondering if we should refactor the deactivation logic, including removal from the lock, and move to the earliest possible step in the reconciliation ensuring it also blocks deletion.

**Comment by hasheddan** [comment]
> I am wondering if we should refactor the deactivation logic, including removal from the lock, and move to the earliest possible phase in the reconciliation, ensuring it also blocks deletion.

@turkenh I believe this would be accomplished by the following:

> This would mean that we would refuse to remove the finalizer on a revision until it successfully transitioned controller --> owner.

**Comment by turkenh** [comment]
@hasheddan yes 👍 

But it also has to be moved up for nondeletion cases. So, deactivation should be in action for nonhealthy revisions as well.
I'll give it a shot.

**Comment by Hronom** [comment]
Please do something about this, please please please.

For this scenario
> This would only solve one possible (and common) scenario where an old revision is deleted before a successful transition

it's critical, please introduce some parameter to provider that allow it to reclaim resources created by not existent revision in force way. As same as import cdr's if they already present in cluster.

This is very painful right now when you accidentally delete `ProviderRevision` - your are doomed. Especially when you also delete `ProviderConfig`
