### ISSUE TITLE
Support for compositeDeletionPolicy Default Value

### ISSUE THREAD

**Issue by Kidswiss** [crossplane/crossplane#3744]
### What problem are you facing?
We want to keep deleted claims by default if the underlying MRs haven't been removed yet.

One use-case for this is for our own provider where we want to provide some form of deletion policy. For instance, only delete a bucket if it's empty. If a user deletes a claim with such a deletion policy and the bucket isn't empty, then the claim will vanish but everything else will stay and still generate costs. For the user though it looks like the deletion was successful.

Currently a user has to set the `compositeDeletionPolicy` manually for this behavior to work, which is not really useful.

### How could Crossplane help solve your problem?
Ability to set the `compositeDeletionPolicy` to `Foreground` for by default for a given composite/claim.

**Comment by bobh66** [comment]
This has been on my list of things to do as we need the same functionality.  We could add a defaultCompositeDeletionPolicy to the XRD, similar to the existing defaultCompositionRef logic for composition selection.  The same thing could be done for compositionUpdatePolicy but I think the implementation would be different enough that it should be in a separate issue/PR.  I'll try to take a look at this in the next few days/weeks.

**Comment by bobh66** [comment]
Reference to similar existing functionality for composition selection - https://github.com/crossplane/crossplane/blob/377239ea37e5bdd8c58453d827d1c45cba0daac8/internal/controller/apiextensions/definition/reconciler.go#L411

**Comment by Kidswiss** [comment]
> This has been on my list of things to do as we need the same functionality. We could add a defaultCompositeDeletionPolicy to the XRD, similar to the existing defaultCompositionRef logic for composition selection. The same thing could be done for compositionUpdatePolicy but I think the implementation would be different enough that it should be in a separate issue/PR. I'll try to take a look at this in the next few days/weeks.

Thanks for the quick reply! Looking forward to the feature.

**Comment by negz** [comment]
@bobh66 Should we add this as targeted for v1.12?

**Comment by bobh66** [comment]
@negz - yes, I'd like to get it done sooner rather than later.  I'll likely need some guidance on the implementation.  Thanks
