### ISSUE TITLE
1.11 with Composition Functions enabled causes flapping in some cases

### ISSUE THREAD

**Issue by blakebarnett** [crossplane/crossplane#3747]
### What happened?
After upgrading none of the database cluster resources we deployed would ever become ready. We tracked it down to the SubnetGroup resource flapping between seeing the resources specified in `subnetIdSelector.matchLabels` and having no subnets every time it tried to sync. I did notice that sometimes when this happened the order of the IDs was different, I'm not sure if that's a red-herring.

### How can we reproduce it?
Deploy a `subnetgroup.rds.aws.upbound.io` with ComponentRevisions and watch for syncs (I used `kubectl get subnetgroup.rds.aws -w`).  

Also we did have both `"--enable-environment-configs", "--enable-composition-functions"` args enabled for 1.11, though they were unused in any of these compositions.

### What environment did it happen in?
Crossplane version: 1.11

* Cloud provider: AWS
* Kubernetes version: v1.24.8-eks-ffeb93d
* Kubernetes distribution: EKS
* OS: N/A
* Kernel: N/A

**Comment by negz** [comment]
> the database cluster resources

Are these resources XRs that compose the subnet groups you see flapping?

> Also we did have both "--enable-environment-configs", "--enable-composition-functions" args enabled for 1.11, though they were unused in any of these compositions.

Could you try disable the Composition Functions flag and see whether the problem persists? When Composition Functions are enabled we swap out the entire Composition engine for a different, Function-aware implementation. It's quite possible that (alpha) implementation isn't handling something right even in P&T Composition.

I suspect the behaviour you're seeing could be because we switched how we apply changes to composed resources to use a n "updating applicator" rather than a "patching applicator". It possible this is causing a race between the XR controller and the provider controller, i.e.:

1. XR controller reconcile A creates a subnetgroup.
2. XR controller reconcile B starts and reads the state of the subnetgroup.
3. Provider controller resolves the subnetID selector, sets the subnetgroup's subnets.
4. XR controller reconcile B (unaware of the change made in step 3) "updates" the state of the subnetgroup, resetting it to the state it read in step 2.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/735e3332ebc1453a12a8db4da12f1b8c39a08cc1/internal/controller/apiextensions/composite/composition_ptf.go#L240

If my theory in my preceding comment is correct, the fix would be to swap the above line to use `resource.NewAPIPatchingApplicator`, which is what the "GA" `PTComposer` uses.

The patching applicator "patches" the desired state over whatever is in the API server, so it won't "undo" any state that is written by a provider. The main downside to the patching applicator is that it can't remove a field from a composed resource.

**Comment by blakebarnett** [comment]
> Are these resources XRs that compose the subnet groups you see flapping?

No I don't believe so.



> > the database cluster resources
> 
> Are these resources XRs that compose the subnet groups you see flapping?
> 
> > Also we did have both "--enable-environment-configs", "--enable-composition-functions" args enabled for 1.11, though they were unused in any of these compositions.
> 
> Could you try disable the Composition Functions flag and see whether the problem persists? When Composition Functions are enabled we swap out the entire Composition engine for a different, Function-aware implementation. It's quite possible that (alpha) implementation isn't handling something right even in P&T Composition.
> 
> I suspect the behaviour you're seeing could be because we switched how we apply changes to composed resources to use a n "updating applicator" rather than a "patching applicator". It possible this is causing a race between the XR controller and the provider controller, i.e.:
> 
> 1. XR controller reconcile A creates a subnetgroup.
> 2. XR controller reconcile B starts and reads the state of the subnetgroup.
> 3. Provider controller resolves the subnetID selector, sets the subnetgroup's subnets.
> 4. XR controller reconcile B (unaware of the change made in step 3) "updates" the state of the subnetgroup, resetting it to the state it read in step 2.

Yeah no problem, I'll re-do the upgrade and test this out ASAP. I did have someone else anecdotally say they had no problems with the same resource but they were only using `--enable-environment-configs` and they have the following policy on the resource:
```              
policy:
  resolution: Required
  resolve: Always
```

**Comment by negz** [comment]
> No I don't believe so.

I want to make sure I'm understanding you correctly. These resources you see flapping (the subnet groups) are composed by some XR, right? I'm guessing you mean `CompositionRevisions` in the following quote.

> Deploy a subnetgroup.rds.aws.upbound.io with ComponentRevisions and watch for syncs (I used kubectl get subnetgroup.rds.aws -w).

**Comment by blakebarnett** [comment]
That's correct, there's an `XNetwork` composition that is referenced by another one called `XDBCluster` via the selector.

**Comment by blakebarnett** [comment]
Verified that re-upgrading to 1.11 and disabling composition functions makes this behave normally again.

**Comment by bobh66** [comment]
@negz we are seeing similar problems - I'll try the patch that you suggested and see if it fixes the issues.

**Comment by bobh66** [comment]
This fix appears to resolve the problem.  I'll  push a PR.

**Comment by jbw976** [comment]
This issue has been addressed in #3774 and will be included in a v1.11.1 patch release.

Something to consider following up on (or thinking about still) is this snippet from @negz [comment](https://github.com/crossplane/crossplane/issues/3747#issuecomment-1421579676):

> The main downside to the patching applicator is that it can't remove a field from a composed resource.

@negz, is this something that should be addressed in the future as an enhancement, or is this just a FYI call-out?
