### ISSUE TITLE
Set releases.crossplane.io to "noindex"

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#3753]
### What happened?

Google search console is reporting usability issues on releases.crossplane.io These errors hurt our SEO and search rankings.

### How to fix it?

We need to add a `<meta name="robots" content="noindex">` configuration to the index page of releases.crossplane.io

**Comment by nikzayn** [comment]
@plumbis I would like to take this up!

**Comment by jbw976** [comment]
Hey there @nikzayn, thank you very much for your enthusiasm and willingness to contribute 🙇 

The content of this file lives directly in the `crossplane.releases` S3 bucket and isn't available anywhere for editing via version control, e.g. a GitHub PR.  I **think** this requires direct write access to the bucket, so I think a maintainer with that access will have to take on this issue.

I'll take a stab this afternoon, but thanks again @nikzayn for your willingness to contribute! 🤩

**Comment by jbw976** [comment]
@plumbis how does this diff look to you? I can replace the current index.html in the bucket with this updated file if it looks good to you 🙇 

```diff
diff --git a/index-curr.html b/index.html
index 3a1f4ba..24fc283 100644
--- a/index-curr.html
+++ b/index.html
@@ -2,6 +2,7 @@
 <html>
 <head>
   <title>S3 Bucket Listing Generator</title>
+  <meta name="robots" content="noindex">
 </head>
 <body>
   <div id="navigation"></div>
```

**Comment by plumbis** [comment]
LGTM. I'll trigger a Google crawl on Monday to verify.

**Comment by plumbis** [comment]
No more errors, closing this as complete.
