### ISSUE TITLE
crossplane ignores --poll-interval parameter

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#3761]
### What happened?
We deploy crossplane with the --poll-interval parameter set to 5m to reduce CPU usage and API traffic.  The PollInterval is not passed to the options for the controllers that do reconciliation so they use the default value of 1m.

### How can we reproduce it?
Start crossplane with --poll-interval=5m and observe that all reconciliation continues to be at 1m intervals

### What environment did it happen in?
Crossplane version: 1.11.0

I tested a fix for the Claim and Composite reconcilers and verified that it works correctly.

Should the specified pollInterval apply to all reconcilers in the core crossplane pod:

CompositeResourceDefinitions
Compositions
CompositionRevisions
Configurations
ConfigurationRevisions
ControllerConfigs
Locks
Providers
ProviderRevisions

I think the short term answer is "yes" - reconciling these at 1m intervals is a lot of work that is probably unnecessary in many environments.  I think individual options for each type is probably overkill, but it would be useful to be able to have some control over the global poll interval.

I can submit a PR but I'd like to get some feedback on what the scope of the change should be.

**Comment by bobh66** [comment]
After digging through the code some more and monitoring the logs it appears that the problem only affects the claims and composites, so I'll push the changes that I have.

**Comment by spastorclovr** [comment]
Could this bug be back in 1.20? I am seeing a 1mn poll interval for composite resources while I changed it to 5m. (real-time composition being disabled)

**Comment by yevon** [comment]
I just received a warning of our kubernetes provider warning of a 7-8s post requests from crossplane, I'm using the helm chart

**Comment by stiangrindvoll** [comment]
> Could this bug be back in 1.20? I am seeing a 1mn poll interval for composite resources while I changed it to 5m. (real-time composition being disabled)

Did you downgrade to see if you have same behavior then? Or otherwise solved it since you wrote the message?
