### ISSUE TITLE
Memory burst when reconciling `providerrevision`

### ISSUE THREAD

**Issue by haorenfsa** [crossplane/crossplane#3790]
### What happened?

The memory usage of crossplane burst when reconciling `providerrevision`

### How can we reproduce it?

I installed several providers: provider-helm, provider-kubernetes, and provider-aws in my cluster. (all the packages  approximately sums to <20MB)

And updated the package all of them more than once.

Here's what I got in the metrics:

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/15938850/220335353-be8a2876-f880-4f34-8913-1f5007076c14.png">

The default Memory Limit is 512MB, So the pod OOMs regularly

And each time when OOM the providerrevision is just reconciling.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/15938850/220335955-9465206f-a8f2-48cb-a249-56f3c579075a.png">

### What environment did it happen in?
Crossplane version:  v1.9.0

**Comment by negz** [comment]
Do you know what version of the providers you installed? Can you reproduce this with the latest version of Crossplane (1.11.1)?

The burst of resource utilization is expected - the package manager has to do a bunch of work to install CRDs. If you can reproduce with the latest provider and Crossplane versions we should probably bump the resource limits.

**Comment by haorenfsa** [comment]
Thank you ! I'll try.
