### ISSUE TITLE
Add crossplane CLI to Krew

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#3801]
### How could Crossplane help solve your problem?

It would be nice to add the `crossplane` kubectl plugin to [krew](https://krew.sigs.k8s.io/), so that it could be simply installed running:
```
$ kubectl krew install crossplane
```

Krew is directly supported by [goreleaser](https://goreleaser.com/customization/krew/), which is not yet used here, but we could introduce it only for this specific use-case, and then we could leverage https://github.com/rajatjindal/krew-release-bot to automate the PR creation upon updates.

There was already some discussion about this in the past, e.g. #2873, but I feel Krew should be addressed separately from Brew.

**Comment by phisco** [comment]
Should be reconsidered if https://github.com/crossplane/crossplane/issues/3055 is reopened

**Comment by bobh66** [comment]
Thanks @phisco - this would be really helpful - I was going to open this issue if I hadn't found it already open.

**Comment by negz** [comment]
I think in the context of https://github.com/crossplane/crossplane/issues/4697 we don't want to do this anymore. We'd prefer folks to be thinking of the Crossplane CLI as "its own thing" rather than an extension of `kubectl`. To that end, I think `kubectl crossplane` will become just `crossplane`.

**Comment by phisco** [comment]
Given the decision to move to a more full fledged "crossplane" CLI, see https://github.com/crossplane/crossplane/issues/4697, this one can be closed.
