### ISSUE TITLE
Enforce composition revision selector in XRD

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#3819]
### What problem are you facing?

I didn't found any related issue so here it is: I would like to enforce the composition revision at the xrd level.

Let's say I put a `channel` label on my compositions with values like `stable`, `dev`, etc... and I want my end users to only use the `stable` channel of compositions when creating XRs or claims.

Actually, users of XRs/claims must add a `compositionRevisionSelector` on each of their XR/claim to target the `stable` channel and they can target other "dev" revisions.       

### How could Crossplane help solve your problem?

Adding a `enforceCompositionRevisionSelector` on XRD would allow end users to not worry about choosing the right composition revision and we could choose to enforce specific revisions depending on the cluster.

**Comment by negz** [comment]
This makes sense to me. It's possible to enforce a composition so I don't see why we wouldn't enforce a revision selector.
