### ISSUE TITLE
Enable patching or passing values to a composition function from claim

### ISSUE THREAD

**Issue by garreeoke** [crossplane/crossplane#3850]
### What problem are you facing?
While working with functions, although you can add a config section in the definition, we cannot pass values from the claim to the function.

### How could Crossplane help solve your problem?
Enable passing values from the claim or elsewhere that could be patched in to the function definition.

**Comment by bobh66** [comment]
The values from the claim should be available in spec.parameters or wherever you defined them.  Do you have an example of the input to the function not including the spec data?

**Comment by jbw976** [comment]
Agreed, this *should* be available as part of the [FunctionIO](https://github.com/crossplane/crossplane/blob/master/apis/apiextensions/fn/io/v1alpha1/functionio_types.go#L117), maybe something like `.desired.composite.resource.spec.foofield`?

**Comment by blut** [comment]
For me the claim input is available in the observed/desired composite resource at the path specified by @jbw976 .
Could you post an example XRD/Composition, Claim and received FunctionIO?

**Comment by garreeoke** [comment]
@jbw976 will give that a shot
