### ISSUE TITLE
Cannot synchronize Docker images (docker hub) starting from v1.11.0 to google Artifact registry 

### ISSUE THREAD

**Issue by abelhoula** [crossplane/crossplane#3862]
Starting from v1.11.0 it's not possible to push tags from docker.io/crossplane/crossplane to the google artifact registry (google block storing images without manifest).

```bash
docker manifest inspect docker.io/crossplane/crossplane:v1.11.1
```
>> output 
no such manifest: docker.io/crossplane/crossplane:v1.11.0

**Comment by jbw976** [comment]
interesting @hasheddan - I am able to reproduce this behavior that @abelhoula is also seeing 🤔 

```console
❯ docker manifest inspect docker.io/crossplane/crossplane:v1.11.1

no such manifest: docker.io/crossplane/crossplane:v1.11.1

❯ docker -v
Docker version 20.10.23, build 7155243
```

**Comment by hasheddan** [comment]
I did recently update Docker:
```
$ docker -v
Docker version 23.0.1, build a5ee5b1
```

You can view the manifest here as well: https://explore.ggcr.dev/?image=crossplane%2Fcrossplane%3Av1.11.1

**Comment by jbw976** [comment]
hehe yes my docker client is definitely older than yours - interesting though that my Docker Desktop for Mac says its up to date and there's nothing newer for me to install 🤔 

> You're up to date
Docker Desktop 4.17.0 (99724) is currently the newest version available.
