### ISSUE TITLE
EC2 Instance not getting created once terminated

### ISSUE THREAD

**Issue by saichaitanya11** [crossplane/crossplane#3864]
### What happened?

We have a cluster installed with Crossplane. An EC2 instance was created using Crossplane when the XRD, Composition and Claim were applied. Once the instance is terminated from AWS Console, a new instance is not being created again. Also, when the instance is stopped from AWS Console, the status of the instance is not changing to running state. Same behaviour is observed when EC2 instance was created using ArgoCD and Crossplane together. Please let us know if it is the expected behaviour or is it a bug.

### How can we reproduce it?

1. Create an EC2 instance using Crossplane.
2. Once the instance is ready, terminate the same in the AWS Console.
3. Observe the status of the EC2 instance.
4. Verify if the instance is being created again.

### What environment did it happen in?
Crossplane version: v1.1.11
Provider: AWS Upbound Provider
OS: Linux
Kubernetes Version: v1.24

**Comment by bobh66** [comment]
This is probably an issue for https://github.com/upbound/provider-aws

**Comment by haarchri** [comment]
Yes please open the issue as @bobh66 mentioned
