### ISSUE TITLE
Dry-run apply should happen after xfn pipeline run

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#3896]
### What happened?

When using xfns, Crossplane is trying to apply composed resources with dry-run option after patches apply but before running the functions pipeline. 

I have custom logic in my xfns where i template some fields of my composed resources, so before running xfn these fields could have a bad type according to xrd/crd so dry-run apply will fail. My xfn pipeline would replace these fields with correctly typed values so running the dry-run apply after xfn pipeline would succeed. 

I suspect if some fields are required in crd, not defined after patches and set in xfn pipeline, the same thing will happen.

I think xfns should allow complex transformations of composed resources and crossplane should only validate custom resources against k8s after xfn pipeline.

**Comment by negz** [comment]
I feel like there might have been a reason I kept the dry-run apply _before_ xfn runs, but I can't remember what it was. What you propose makes sense to me.

**Comment by djeremiah** [comment]
Another use case that needs dry-run after the xfn pipeline is the use of `generatename` in resources that are added during the function run. These don't get names properly set in the current implementation.

**Comment by negz** [comment]
I'm taking a look at this one. It looks like it requires a lot more surgery to the `PTFComposer` (i.e. the Functions-aware composition engine) than I expected, but I think it's worthwhile.

**Comment by duizabojul** [comment]
Thx a lot nic, I can't wait for this one 🙏

**Comment by negz** [comment]
I have a branch where I've done a bunch of refactoring toward this, but given we're close to v1.13 feature freeze and given I'm OOO from July 18 -> Aug 5th I don't think this is going to make v1.13, sorry.

I'm hoping this won't be too overly disruptive in the broader context, which is that we plan to make some big changes to how Functions work for 1.14 per https://github.com/crossplane/crossplane/pull/4306.

**Comment by djeremiah** [comment]
During a conversation at the Crossplane meetup in Munich, we were discussing another use case for XFNs that would require the dry-run apply to be before the xfn pipeline. @mleahu Is interested in injecting an xfn to validate the composed resources during a ci/cd process. But it would need to happen at the very end of the pipeline, after all resources had been initialized. Does this mean we need to dry-run multiple times? Or define different points in the pipeline where functions can run?

**Comment by negz** [comment]
> During a conversation at the Crossplane meetup in Munich, we were discussing another use case for XFNs that would require the dry-run apply to be before the xfn pipeline. @mleahu Is interested in injecting an xfn to validate the composed resources during a ci/cd process.

@djeremiah Sorry, just noticed this comment way after the fact. Can you or @mleahu raise an issue to track this use case. Something I've seen done in other systems is to allow declaring two distinct pipelines at the API level - one for rendering and another for validation.
