### ISSUE TITLE
Long term plan for slack.crossplane.io

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#3907]
### What problem are you facing?

With short-medium term fix in place for #3872, slack.crossplane.io is back online and functional.  However, the new implementation has some issues that should cause us to consider a better long term plan.  The known limitations are captured in https://github.com/crossplane/slack.crossplane.io#maintenance-notes, the main issue being that no matter what, Slack does not allow you to have a permanent invitation link, so we will need to keep updating it over time.

It would be ideal to have a better solution that requires no ongoing maintenance.

### How could Crossplane help solve your problem?

Some possible approaches to this problem are:

* Fix the broken and out of date https://github.com/bassam/slackin/ implementation.  This repo is no longer maintained and will be susceptible to future unexpected breaks like we saw in #3872.
* Migrate to a better maintained solution like https://github.com/emedvedev/slackin-extended.  We're not sure of the full migration cost here, but the Project Calico folks did this and didn't say it was awful.
* Implement some automation, e.g. a GitHub action in https://github.com/crossplane/slack.crossplane.io to periodically refreshes the invitation link for us, removing any human manual effort to keep it up to date.
* Research more into what other projects are doing and see if there are more desirable alternatives.

**Comment by jbw976** [comment]
In the meantime, I have updated the Heroku config to stop the dyno(s) and put them into maintenance mode, since they are no longer being used right now.

**Comment by jbw976** [comment]
/fresh This is still a problem, see https://github.com/crossplane/slack.crossplane.io/pull/4

**Comment by jbw976** [comment]
I have a test page up and running at https://slack-extended.crossplane.io/ 💪 

Feel free to try it out and see if there are any issues/bugs with joining our Crossplane slack through that page.

If all looks well there from our testing, we can go ahead and update the DNS for slack.crossplane.io to start pointing to that page 🙏

**Comment by jeanduplessis** [comment]
@jbw976 I just tested it, and it works as expected 👍

**Comment by jbw976** [comment]
Thanks for testing @jeanduplessis!! I'll keep this issue open until the final production deployment is completed (e.g. DNS is updated). The page you used is just a test page still 😊

**Comment by jbw976** [comment]
Checked in on the running instance at https://slack-extended.crossplane.io/ today and all I could see was a Heroku app error.  Looking in the logs, I see repeated instances of:

```
app[web.1]: 2024-04-12T11:59:11.243Z slackin:slack Error: Error: Too Many Requests
```

This looks like https://github.com/emedvedev/slackin-extended/issues/20, where folks suggest setting a value for `SLACKIN_INTERVAL`, which is `How frequently (ms) to poll Slack` according to the [docs](https://github.com/emedvedev/slackin-extended?tab=readme-ov-file#parameters). The default of `60000` (1 min) seems to be too frequent for our crossplane account's Slack API.  Trying a higher value like `30000` (5 min) now to see if that stays healthier.

**Comment by jbw976** [comment]
https://slack.crossplane.io/ looks to be live with the new slack-extended based registration app! 🎉 

If anyone sees any difficulties with creating an account for Crossplane Slack, please reach out immediately!
