### ISSUE TITLE
Unexpected behavior with Composite Functions

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#3918]
### Discussed in https://github.com/crossplane/crossplane/discussions/3905

<div type='discussions-op-text'>

<sup>Originally posted by **jaylevin** March 23, 2023</sup>
I have been experimenting with composite functions for the past week and have been experiencing some unexpected behavior that I would like to confirm with the community is actually unexpected.

I have a composition function very similar to the example in the documentation. It adds an annotation to a specific resource in the `functionio["desired"]["resources"]` object. I have a conditional case to check if the annotation already exists in the desired resource, and if it doesn't it adds it. If the annotation already exists, I also add a message to the results array to help with debugging.

The function looks something like this:
```python

    # basic function to add an annotation if it does not exist
    try:
        for r in functionIO["desired"]["resources"]:
            result_normal(functionIO, f"resource: {r}")
            if r["name"] == "environment":
                if "resource" not in r:
                    continue
                if "metadata" not in r["resource"]:
                    r["resource"]["metadata"] = {}
                if "annotations" not in r["resource"]["metadata"]:
                    r["resource"]["metadata"]["annotations"] = {}

                ANNOTATION_NAME = "test-annotation"
                if ANNOTATION_NAME not in r["resource"]["metadata"]["annotations"]:
                    # should only run once per resource
                    result_normal(functionIO, "desired resource does not have annotation, one will be added!")
                    r["resource"]["metadata"]["annotations"][ANNOTATION_NAME] = "test"
                else:
                    result_normal(functionIO, "desired resource has annotation, skipping!")
                break
    except Exception as e:
        result_normal(functionIO, f"exception: {str(e)}")
```

The problem I am running into is the desired object does not seem to be saved between function executions.

For example:
1. The function runs the first time and adds the annotation to the desired object and returns.
2. Reconcile happens and the annotation is added to the composed resource.
3. The function runs a second time, and once again, the desired resource in the `FunctionIO` object does not have the annotation. I would expect that the desired object being passed to the function would contain the changes that were made in the previous function execution. Is this not the intended behavior, or is this a bug? Should I be checking the observed resource instead of the desired resource?

I have tried using Crossplane v1.11.1, v1.11.2, and the latest build on the master branch ([crossplane-1.12.0-rc.0.213.g2a65adbb.tgz](https://charts.crossplane.io/master/crossplane-1.12.0-rc.0.213.g2a65adbb.tgz))

</div>

**Comment by turkenh** [comment]
> Is this not the intended behavior, or is this a bug? Should I be checking the observed resource instead of the desired resource?

Yes, I think this is working as [designed](https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-functions.md#function-api), and you should be checking observed resources instead.

**Comment by Kidswiss** [comment]
I was wondering the same, the documentation [here](https://docs.crossplane.io/knowledge-base/guides/composition-functions/#functionio) states this:


> The desired state of the XR and composed resources is how your Function tells Crossplane what it should do. Crossplane ‘bootstraps’ the initial desired state passed to a Function pipeline with:
> - A copy of the observed state of the XR.
> - A copy of the observed state of any existing composed resources.
> - Any new composed resources or modifications to observed resources produced from the resources array.


However, it looks like the desired array only gets 'bootstrapped' with whatever is specified in the P+T composition. Any observed changes via the composition function are not 'bootstrapped'.

I wonder if the documentation is wrong, or if this is indeed a bug. Maybe @negz can shed some light on this?

**Comment by jaylevin** [comment]
Closing this as this was a misunderstanding on my part.
