### ISSUE TITLE
Enforced Composition Update Policies

### ISSUE THREAD

**Issue by clementblaise** [crossplane/crossplane#3972]
### What problem are you facing?

Crossplane supports setting `compositionUpdatePolicy` on either Composite or Claim resources. It is a great feature when users are authoring their `Composition` or `XRD`. However, as Platform Engineer, a mechanism to enforce which policy is used would be welcome, enabling deploying changes without interacting with end-user resources.

### How could Crossplane help solve your problem?

Implement the proposed solution that was described in the original design of the Composition Revision :
https://github.com/crossplane/crossplane/blob/9169aaa45d723ec26371abec10680561677c7ce3/design/one-pager-composition-revisions.md?plain=1#L276-L289

If implemented, it would need an additional Update Policy to have something between `Manual` and `Automatic` so that there is more granular control over how the changes are propagated.

A new `RollingUpdate` update policy could be introduced to set a `maxUpdate` that would wait at each step for the Composite or Claim to be `Synced` and `Ready` before attempting to change the CompositionRevision on another resource.

The order could be defined as an array of steps that matches particular criteria, such as labels. Argo CD recently added a similar mechanism to `ApplicationSet` that manages `Application`; more info [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/)

**Comment by bobh66** [comment]
In the case of nested composites would you expect that the top-level enforcedCompositionUpdatePolicy would be cascaded down through all of the child composites, regardless of the settings in the XRDs for those composites?  This topic could probably benefit from a one-page design description if/when it gets to that stage, to define the process associated with rolling out updated compositions in deployed nested composites.

**Comment by clementblaise** [comment]
@bobh66 Good point. I would lean on not cascading to child composites and leave it up to the user to roll out composites individually. At the moment, if you need to update a top-level and a child, it's a two-step process.

Though it might be possible to define how multiple composites should be updated through the use of `Configuration` and their dependencies.

Happy to hear your thoughts on the subject and I agree is there is interest a one-page design would be valuable.
