### ISSUE TITLE
Composite Functions failing in certain clusters

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#3982]
### What happened?
I have a basic composite function. It works fine on my local `kind` cluster running crossplane v1.11.3.

The problem is arising when I try to move my function into a cloud-hosted Kubernetes cluster. The cluster is also running crossplane v1.11.3, but fails to run the composite function with this error:
```sh
2023-04-13T23:08:18Z	DEBUG	crossplane	cannot compose resources	{"controller": "defined/compositeresourcedefinition.apiextensions.crossplane.io", "controller": "composite/xconfluentkafka.confluent.xxxxxxx", "request": "/confluent-kafka-q64mw", "uid": "265986e1-5f34-4008-b1d3-b47e1d64187e", "version": "10844650", "name": "confluent-kafka-q64mw", "error": "cannot run Composition Function pipeline: cannot run function \"test\": cannot run container: rpc error: code = Unknown desc = exit status 1: xfn: error: spark.Command.Run(): OCI runtime error: exit status 1"}
```
I suspect this has something to do with our custom kernel we are using (Garden Linux), but I have no clue how to further debug or test my hypothesis.

### How can we reproduce it?

Use [Garden Linux ](https://github.com/gardenlinux/gardenlinux) worker nodes for your kubernetes cluster, deploy Crossplane v1.11.3 and try to use composite functions.

### What environment did it happen in?

* Crossplane version: v1.11.3
* Cloud provider: Azure
* Kubernetes version: v1.25.6
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): Azure
* Kernel (e.g. `uname -a`):  We are running [Garden Linux ](https://github.com/gardenlinux/gardenlinux)
```
Linux term-16972028826273924552 5.15.101-gardenlinux-cloud-amd64 #1 SMP Debian 5.15.101-0gardenlinux1 (2023-03-12) x86_64 x86_64 x86_64 GNU/Linux
```

How can I ensure my cluster/kernel meets the requirements for running Composite Functions?

Any help would be greatly appreciated.

**Comment by negz** [comment]
@jaylevin Do you have apparmor or seccomp enabled? You may need to disable these - unfortunately they block some of the syscalls that the function runner uses.

**Comment by jaylevin** [comment]
Thank you @negz . It was indeed AppArmor.

I was able to fix the error by adding this annotation to the Crossplane Deployment/Pod:
 `container.apparmor.security.beta.kubernetes.io/crossplane-xfn: unconfined`
