### ISSUE TITLE
Drop templated helm chart values

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#3994]
### What problem are you facing?

Currently Crossplane's chart only has a templated values file committed, the actual version is only rendered at build time either to deploy it locally or to publish it. This makes it confusing for users, which are used to look for a `values.yaml` file, more difficult to use tools that assume values to be there, e.g. [helm-docs](https://github.com/norwoodj/helm-docs), and adds useless cognitive load.

### How could Crossplane help solve your problem?

We should switch to use the appVersion and an empty tag as already done by other widely adopted charts, e.g. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2174 and https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L2. By doing so we could eliminate the `values.yaml.tmpl` file and we could remove the `helm.prepare` target from the build submodule.

Given that the appVersion bumping logic is already in place for publishing, we would only need to `--set image.tag="$(cat _output/version)"` in the [kind.sh](https://github.com/crossplane/crossplane/blob/master/cluster/local/kind.sh#L86) script used to deploy Crossplane locally.

**Comment by turkenh** [comment]
This sounds reasonable to me.

We just need to be careful to warn other consumers of the build submodule so that they can adapt their charts accordingly.
