### ISSUE TITLE
MRs created via Composite Function are deleted by subsequent reconcile

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#4004]
### What happened?

I have a composite function that adds some MRs to the FunctionIO's `desired.resources` list if it doesn't exist in the `observed.resources` list.

The problem I am running into is that resources that are created by my XFN (by appending to the `desired.resources` list of the FunctionIO) do not stay in the cluster for very long. It seems like a separate reconcile is removing them within ~60seconds. I assume this is because the resources are not defined in the patch&transform section of the composition, but this doesn't make sense to me. How are we supposed to dynamically create MRs from XFNs if this happens?

**Observed Flow:**
1. Function executes, MR is added to `desired.resources` list.
2. Reconcile happens, MR is created and added to the `resourceRefs` of the XR.
3. Function executes, MR is in the `observed.resources` list, but not in the `desired.resources` list. A no-op happens in this case because the desired resource is already in the `observed.resources` list (despite it not actually existing in the FunctionIO's `desired.resources` list).
4. Reconcile happens, and the MR is wrongly deleted from the cluster/XR. I suspect that the composition controller is reconciling just the state in the Composition patch&transforms, and not taking into ca
5. Function executes again, MR is no longer in the `observed.resources` list OR the `desired.resources` list. This results in a re-creation of the MRs by the xfn and the process repeats. 

### How can we reproduce it?

1. create a basic composite function that adds MRs into the FunctionIO's `desired.resources` list.
2. create a claim against a composition that uses this XFN and observe that the MRs that the XFN create are being deleted and re-created, presumably by competing reconciliations.

Example XFN snippet (the entrypoint of the function ends up calling `compose_clusters()`):
```python
# returns true if the cluster already exists in observed resources array.
def cluster_in_observed_resources(function_io, cluster_name):
    for resource in function_io["observed"]["resources"]:
        if resource["name"] == cluster_name:
            result_normal(
                function_io,
                f"[no-op] Cluster already exists in observed resources: {cluster_name}",
            )

            return True
    return False

# compose_clusters creates the n # of clusters based on user's input in the XRC/XR.
def compose_clusters(function_io):
    # Return early if there are no observed resources to check.
    if "observed" not in function_io or "resources" not in function_io["observed"]:
        raise ObservedResourceNotFound(
            "FunctionIO object is missing observed.resources field"
        )

    composite = function_io["desired"]["composite"]["resource"]["spec"]["clusters"]
    result_normal(function_io, f"Desired Composite: {composite}")
    for cluster in function_io["desired"]["composite"]["resource"]["spec"]["clusters"]:
        cluster_name = cluster["name"]
        if cluster_in_observed_resources(function_io, cluster_name):
            continue

        function_io["desired"]["resources"].append({
            "name": cluster["name"],
            "resource": {
                "apiVersion": "xxxx/v1alpha1",
                "kind": "Cluster",
                "metadata": {
                    "name": cluster["name"],
                },
                "spec": {
                   ....
                }
            }
        })
```

### What environment did it happen in?
Crossplane version:  v1.11.3

**Comment by bobh66** [comment]
The `desired` resource list needs to always have the resources that are "desired" even when they are in the `observed` list - otherwise Crossplane will assume they are no longer desired and will delete them.  So `desired` should be equal to `observed` when everything is deployed.

**Comment by jaylevin** [comment]
@bobh66 Thank you for the clarification.  I still have one more concern/question that would be wonderful if you could help calrify.

1. What happens if there is a computed field that the Provider adds after the XFN creates the resource? Since the xfn needs to re-add the desired resource multiple times, will it not overwrite the field that was added post-function execution?

For example, I now have this code:
```python

# returns true if the cluster already exists in observed resources array.
def cluster_in_desired_resources(function_io, cluster_name):
    for resource in function_io["desired"]["resources"]:
        if resource["name"] == cluster_name:
            result_normal(
                function_io,
                f"[no-op] Cluster already exists in desired resources: {cluster_name}",
            )

            return True
    return False

# compose_clusters creates the n # of clusters based on user's input in the XRC/XR.
def compose_clusters(function_io):
    # Return early if there are no observed resources to check.
    if "observed" not in function_io or "resources" not in function_io["observed"]:
        raise ObservedResourceNotFound(
            "FunctionIO object is missing observed.resources field"
        )

    composite = function_io["desired"]["composite"]["resource"]["spec"]["clusters"]
    result_normal(function_io, f"Desired Composite: {composite}")
    for cluster in function_io["desired"]["composite"]["resource"]["spec"]["clusters"]:
        cluster_name = cluster["name"]
        if cluster_in_desired_resources(function_io, cluster_name):
            continue

        function_io["desired"]["resources"].append({
            "name": cluster["name"],
            "resource": {
                "apiVersion": "confluent.orchestrate.cloud.sap/v1alpha1",
                "kind": "Cluster",
                "metadata": {
                    "name": cluster["name"],
                },
                "spec": {
                    "forProvider": {
                         .... other fields ....
                        "environment": [{
                            "idSelector": {
                                "matchControllerRef": True
                            }
                        }],
                    },
                }
            }
        })

```

Now, what happens when the `idSelector` is resolved and the `spec.forProvidedr.environment.id` field is added? The next time my function runs, it will be appending the composed resource with this field omitted (as shown above). How will this not cause problems?

**Comment by bobh66** [comment]
I don't think that will be a problem, since it works with the original patch and transform method where the `idSelector` would be in the YAML definition, and when it gets merged into the composed resource it will leave the `id` field in place. 

If it were a problem you could always copy the observed resource into the desired resource, but I don't know that it's necessary.

**Comment by jaylevin** [comment]
Much appreciated @bobh66 !
