### ISSUE TITLE
Non-CRD Crossplane Provider

### ISSUE THREAD

**Issue by frantjc** [crossplane/crossplane#4008]
### What problem are you facing?

I think Crossplane is the premier framework for developing, packaging and deploying Kubernetes controllers. The only issue is that Crossplane doesn't seem to natively support writing controllers that don't manage their own CRDs. 

For example, I'd like to be able to write a Kubernetes Controller using Crossplane as a framework which looks at Ingress objects and does some custom DNS/Certificate stuff for my company.

### How could Crossplane help solve your problem?

I'm hoping someone will either tell me that Crossplane won't support this (so I will sadly have to look to kubebuilder) or can provide me with some suggestion on how I can hook an existing resource definition into Crossplane such that my Crossplane provider is package with the RBAC to reconcile that resource.

Thanks!

**Comment by bobh66** [comment]
I suspect that's a bit outside of Crossplane's mission, since it doesn't involve exposing/implementing an API.

Have you considered kopf?  https://github.com/nolar/kopf  It's really useful for implementing operators that aren't necessarily also controllers for the resources they are watching.

**Comment by negz** [comment]
If I'm following the user-case correctly:

* You want to use Crossplane to manage built-in Kubernetes types like `Ingress`.
* You'd also like to integrate with a custom system that handles DNS and Certificates.

I believe this would be doable by using https://github.com/crossplane-contrib/provider-kubernetes to handle the `Ingress` part of things, and writing your own Crossplane provider for your internal DNS/Cert system.

**Comment by frantjc** [comment]
> I suspect that's a bit outside of Crossplane's mission, since it doesn't involve exposing/implementing an API.
> 
> Have you considered kopf? https://github.com/nolar/kopf It's really useful for implementing operators that aren't necessarily also controllers for the resources they are watching.

Thanks! I'll look into kopf.

> If I'm following the user-case correctly:
> 
> * You want to use Crossplane to manage built-in Kubernetes types like `Ingress`.
> * You'd also like to integrate with a custom system that handles DNS and Certificates.
> 
> I believe this would be doable by using https://github.com/crossplane-contrib/provider-kubernetes to handle the `Ingress` part of things, and writing your own Crossplane provider for your internal DNS/Cert system.

I think I miscommunicated slightly.

The nuance that I failed to communicate is that I want my Crossplane provider to reconcile built-in Kubernetes objects (not create them).

Think about projects like [external-dns](https://github.com/kubernetes-sigs/external-dns) or [cert-manager](https://cert-manager.io), which, in addition to the Ingress Controller, reconcile Ingress objects to further automate their use.

Imagine a cluster with both of them installed. When an `Ingress` object got created, the first thing that would happen would be that cert-manager would generate a certificate for it, put that certificate in a `Secret`, then update the `Ingress` object to use that certificate. Next, the installed Ingress Controller exposes the `Ingress` object. Finally, external-dns would take the IP address that the Ingress Controller exposed and update a DNS record to route traffic to it.

I would like my Crossplane provider to essentially do what external-dns and cert-manager do, but do them by implementing APIs that are internal to my company which are not compliant with backends that those projects support.

I hope that explains it better!

**Comment by negz** [comment]
Oh, gotcha. Yes unfortunately while this is an interesting use case it isn't something we support.

You might be able to get away with using crossplane-runtime, but we do make a lot of assumptions that the things our providers reconcile are "managed resource shaped" (e.g. have consistent properties like external name annotations, spec.forProvider, status.atProvider, status conditions etc). We're generally reluctant to relax these assumptions because we feel there's value in all Crossplane MRs having similar, predictable schemas and behaviours.

**Comment by frantjc** [comment]
> Oh, gotcha. Yes unfortunately while this is an interesting use case it isn't something we support.
> 
> You might be able to get away with using crossplane-runtime, but we do make a lot of assumptions that the things our providers reconcile are "managed resource shaped" (e.g. have consistent properties like external name annotations, spec.forProvider, status.atProvider, status conditions etc). We're generally reluctant to relax these assumptions because we feel there's value in all Crossplane MRs having similar, predictable schemas and behaviours.

Understood, thanks for humoring me!

I'll close this with a final note: if anyone knows of a framework or tool that allows you to package and deploy any Kubernetes controller along with the RBAC necessary for it to reconcile the objects it wants to reconcile (as opposed to generating and applying all of the YAML manually), please reply with it here!

Crossplane does this by generating an OCI image with a `package.yaml` in the root of the filesystem containing a Crossplane CR as well as some CRDs. However, it seems that those CRDs must be a certain "shape" and cannot be existing objects, limiting the use cases for its great provider packaging and deployment pattern.
