### ISSUE TITLE
Can crossplane support reading provider credentials only when making calls with cloud providers?

### ISSUE THREAD

**Issue by yangyang919** [crossplane/crossplane#4018]
### What problem are you facing?

Currently we know that provider credentials can be injected from external source like vault. But after provider is ready to use, the credentials would be stored in provider container, which means credentials stay in the cluster. So for someone who has cluster permissions, would be able to see the credentials. We are wondering is there some practices to deal with this scenario?

That's why we are thinking credentials stay in vault, only read credential when needed...not sure whether this sounds valid from crossplane point of view?

**Comment by jbw976** [comment]
@turkenh @ezgidemirel, can you all comment on the design of external secret stores and how we use Vault as an ESS? i.e. do we read the credentials on an as needed basis from the ESS each time they are needed, or are they temporarily cached/stored within the provider pod in between operations? 🤔 

Related design docs:

* https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md
* https://github.com/crossplane/crossplane/blob/master/design/one-pager-pluggable-secret-stores.md

**Comment by turkenh** [comment]
> do we read the credentials on an as needed basis from the ESS each time they are needed, or are they temporarily cached/stored within the provider pod in between operations?

We don't cache or store credentials in the filesystem with ESS. However, please note, currently ESS does not support [consuming input secrets from external secret stores](https://github.com/crossplane/crossplane/issues/2985). We already have read functionality implemented as part of the ESS interface but it is used only when fetching MR connection details to form a connection secret for Composite/Claim.

I assume the issue here is about when the [Vault Credential Injection](https://docs.crossplane.io/knowledge-base/integrations/vault-injection/) guide is followed.

**Comment by yangyang919** [comment]
@turkenh @jbw976 thanks for replying. So according to my understanding, after credentials are injected into cluster, right now to secure credentials, the solution is to consider strong use of RBAC in cluster. Only people with limited permissions can access the secrets. The reason of asking this question is credentials stay in cluster might get challenged by security expert...

**Comment by jbw976** [comment]
Thanks @turkenh for reminding me, probably for the 3rd+ time, that our current external secret store implementation doesn't support consuming input secrets yet 😅  I assume when we design/build that functionality out then we will certainly take under consideration @yangyang919's request and concerns here 🙇‍♂️ 

In the mean time @yangyang919, if you are indeed referring to [Vault Credential Injection](https://docs.crossplane.io/knowledge-base/integrations/vault-injection/), then I don't think there's much we can change about that here in the Crossplane project.  That guide shows how to use Hashicorp's [Vault Kubernetes Sidecar](https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-sidecar), which is owned/maintained by Hashicorp.

**Comment by yangyang919** [comment]
@jbw976 can this issue turn into a valid requirement request? Perhaps how long do you estimate can this be added into crossplane project?
