### ISSUE TITLE
Remove new release issue templates?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4025]
### What problem are you facing?

<img width="1247" alt="Screenshot 2023-04-27 at 7 59 57 AM" src="https://user-images.githubusercontent.com/1049349/234903713-2349909f-ea17-4083-8357-e0e0afc17e3a.png">

We now have 7 options someone must choose from when creating a new Crossplane issue. 2 of those options are only relevant to folks who work on Crossplane - we don't expect the average community member to create a new release tracking issue.

### How could Crossplane help solve your problem?

Could we remove these issue templates? Perhaps it would be sufficient for the folks running the release to find them template elsewhere and copy-and-paste it into a new issue?

**Comment by jbw976** [comment]
I was hoping that there was a possibility to set permissions/visibility on issue templates, e.g. so only maintainers would see those release related options, but I'm not seeing anything in the [github docs](https://docs.github.com/en/enterprise-server@3.6/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository) yet 😞

**Comment by negz** [comment]
/fresh

I'd still like us to do this. I don't think anyone but maintainers need to see these.

**Comment by turkenh** [comment]
We could also move those templates to a non user-facing repository, and create release-tracking issues there, especially considering now it includes cutting the release of crossplane-runtime as well.
I am unaware of a great candidate repo for this, though (maybe https://github.com/crossplane/org) but I wanted to throw this as a possibility.

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/crossplane/pull/5195. 🎉
