### ISSUE TITLE
Cut v1.12.1 on April 28, 2023

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4027]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.11.1] for
examples of each step, assuming vX.Y.Z is being cut.

Backport PRs for this patch release:
- https://github.com/crossplane/crossplane/pull/4032
- https://github.com/crossplane/crossplane/pull/4034

TODO: 

- [x] Run the [Tag workflow][tag-workflow] on the `release-X.Y`branch with the proper release version, `vX.Y.Z`. Message suggested, but not required: `Release vX.Y.Z`.
    - https://github.com/crossplane/crossplane/actions/runs/4831867758
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.Z/...` should contain all the relevant binaries.
    - https://github.com/crossplane/crossplane/actions/runs/4831875659
    - https://releases.crossplane.io/build/release-1.12/v1.12.1/
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [xpkg.upbound.io] for all getting started packages.
  - https://github.com/crossplane/crossplane/actions/runs/4832156895
  - [x] `xp/getting-started-with-aws`
  - [x] `xp/getting-started-with-aws-with-vpc`
  - [x] `xp/getting-started-with-azure`
  - [x] `xp/getting-started-with-gcp`
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the `release-X.Y` branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.Z/...`.
    - https://github.com/crossplane/crossplane/actions/runs/4832176835
    - https://releases.crossplane.io/stable/v1.12.1/
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.Y.<Z-1>`, so the previous patch release for the same minor.
    - https://github.com/crossplane/crossplane/releases/tag/v1.12.1
- [x] Only if cutting a patch for the latest supported release: updated the [`crossplane/test` repo test workflows][crossplane-test-workflows] to ensure the checkout release branch and helm install version(s) point at the new release across all the workflow files.
    - https://github.com/crossplane/test/pull/42
- [ ] Ensured that users have been notified of the release on all communication channels:
  - [ ] Slack: `#announcements` channel on Crossplane's Slack workspace.
  - [ ] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].

[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[crossplane-test-workflows]: https://github.com/crossplane/test/tree/master/.github/workflows
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.11.1]: https://github.com/crossplane/crossplane/issues/3796
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[xpkg.upbound.io]: https://marketplace.upbound.io/configurations?query=getting-started

**Comment by negz** [comment]
I think we need to include https://github.com/crossplane/crossplane/pull/4031 in this patch. I noticed per https://github.com/crossplane/crossplane/issues/4016#issuecomment-1526905264 that the impact of the performance issues seems to be worse than we thought - specifically I've observed a few OOM kills of the RBAC manager.

**Comment by negz** [comment]
I'm pretty sure we released this. 😄

**Comment by negz** [comment]
Link for posterity: https://github.com/crossplane/crossplane/releases/tag/v1.12.1
