### ISSUE TITLE
 xfn should support custom CA bundles

### ISSUE THREAD

**Issue by martinflemingdev** [crossplane/crossplane#4041]
### What happened?
Before enabling Composition functions, I could override the Crossplane Helm chart with my root internal CABundle using a configmap and it worked as expected. 

![image](https://user-images.githubusercontent.com/78125388/235913898-9d39e177-b097-4cf6-9160-485b447ea684.png)

When I enabled Composition functions, the XFN container receives 509 (cert) error when it attempts to pull function containers from an open Docker registry that's expecting our internal CABundle. 

Is there a way to explicitly configure which CABundle the XFN container uses?  

Is the Helm chart override not setting the XFN container CABundle? 

### What environment did it happen in?
Crossplane version: v1.11.2

**Comment by negz** [comment]
> Is there a way to explicitly configure which CABundle the XFN container uses?

Not at the moment, unfortunately.
