### ISSUE TITLE
Run RBAC manager in `Basic` mode by default?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4043]
### What problem are you facing?

When in `Full` mode the RBAC manager will:

1. Create and bind a role to Crossplane's service account, so it can control managed resources.
2. Create and bind roles to provider service accounts, so they can reconcile their managed resources.
3. Create cluster roles that you can bind to grant users access to Crossplane resources in all namespaces.
4. Create roles that you can bind to grant users access to Crossplane resources in a specific namespace.

When in `Basic` mode it will only do 1 through 3 above. It will not do 4.

To go a little deeper on what 4 means, when in `All` mode, the RBAC manager also manages a series of (namespaced) RBAC roles for each namespace that exists in the cluster/control plane - `crossplane-admin`, `crossplane-edit`, and `crossplane-view`. Note that despite the names these are distinct from the _cluster-scoped_ roles the RBAC manager also manages. These roles exist only within the scope of a namespace.

`crossplane-admin`:
* Full access to claims that are "accepted" by the namespace.
* Full access to secrets in the namespace (even those not related to Crossplane).
* Read-only access to RBAC roles and events in the namespace.
* Can bind RBAC roles to other entities in the namespace.

`crossplane-edit`:
* Full access to claims that are "accepted" by the namespace.
* Full access to secrets in the namespace (even those not related to Crossplane).
* Read-only access to events in the namespace.

`crossplane-view`:
* Read-only access to claims that are "accepted" by the namespace.
* Read-only access to events in the namespace.

A namespace is said to "accept" a claim if the namespace has an annotation in the form `rbac.crossplane.io/name-of-xrd: xrd-claim-accepted`. So if you have an XRD named `xwidgets.example.org` that defines a claim of `kind: Widget`, you would annotate your namespace with `rbac.crossplane.io/xwidgets.example.org: xrd-claim-accepted` in order to let the RBAC manager know it should update the admin, edit, and view roles in that namespace to grant access to `kind: Widget`.

To be quite honest, this feature was designed in support of Upbound's SaaS authorization model and I regret allowing it to leak into Crossplane. I doubt anyone needs, uses, or even knows about the functionality that `All` mode enables and I don't think it should be the default mode of operation for the RBAC manager.

### How could Crossplane help solve your problem?

I'd like us to consider changing the default policy of the RBAC manager from `All` to `Basic`, i.e. making the management of these namespace scoped RBAC roles opt-in rather than opt-out. Before we do so, we should get a sense of how many folks are using them.

**Comment by negz** [comment]
@clementblaise Can you clarify what your 👎 means? I'm not sure whether it means "I don't use the `Full` mode functionality" or "I don't think the RBAC manager should run in `Basic` mode by default".

**Comment by clementblaise** [comment]
@negz Apologies for the confusion; I misunderstood role number 4 for `Full`, I support setting the `Basic` mode as the default.
