### ISSUE TITLE
Support only the Kubernetes releases that Kubernetes supports

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4049]
### What problem are you facing?

https://docs.crossplane.io/v1.12/software/install/#prerequisites

I was reminded today that our documentation states that Crossplane requires Kubernetes v1.16 or later. I'd be pretty surprised if at this point we weren't dependent on some API server feature that was not available in Kubernetes v1.16, which was [released](https://github.com/kubernetes/kubernetes/releases/tag/v1.16.0) in September 2019.

https://kubernetes.io/releases/patch-releases/#support-period

If I'm interpreting the support period documentation correctly, the Kubernetes project itself only supports a particular minor version (e.g. 1.26.x) for ~14 months. I believe this means that at the time of writing the oldest supported minor version of Kubernetes is 1.24.x.

### How could Crossplane help solve your problem?

I don't think Crossplane should be attempting to maintain compatibility with very old versions of Kubernetes. This constrains us as a project, and presumably has limited value. Hopefully few folks are running these old, unsupported and presumably insecure versions.

**Comment by negz** [comment]
CC @plumbis. The "fix" for this would be updating our docs, but I'm raising the issue here since its a decision for the maintainers.

**Comment by haarchri** [comment]
checkout also the the Amazon EKS Kubernetes release calendar: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

![image](https://user-images.githubusercontent.com/21083497/236383989-12637de9-52f1-4c3d-9f97-623fc0d9a680.png)


btw for observe only resources i opened yesterday the following issue: https://github.com/upbound/provider-aws/issues/693 in Kubernetes < 1.25 will no longer get a validation error at the API server level

**Comment by jeanduplessis** [comment]
I think looking at the supported versions of the most popular managed k8s solutions would better indicate which version of k8s we should support compared to the k8s project itself.

**Comment by jeanduplessis** [comment]
AKS: https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
GKE: https://cloud.google.com/kubernetes-engine/versioning

**Comment by negz** [comment]
> I think looking at the supported versions of the most popular managed k8s solutions would better indicate which version of k8s we should support compared to the k8s project itself.

As far as I can tell GKE and Azure largely mirror the upstream Kubernetes release support windows, in that they don't support releases of Kubernetes for much longer than the Kubernetes project does. EKS appears to be the exception to the rule. The oldest minor version of Kubernetes supported by the project itself [is 1.24](https://kubernetes.io/releases/), while EKS supports back to 1.22.

The more old versions of Kubernetes we support, the more constraints we place on ourselves. Some examples:

* https://github.com/kubernetes/kubernetes/pull/105520 - Some of the earliest work to address CRD scale limits only made it back to v1.23. Today, anyone running v1.22 would likely be facing a lot of client-side rate limiting with as few as 100 CRDs.
* https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/ - The CEL validation rules that observe only resources use (and that I think generic cross-resource references will use) are enabled by default in v1.25. If we support only the releases that Kubernetes supports, we can stop worrying about folks who don't have API servers that support this in July. If we also support the versions EKS supports, we must wait until January 2024.

Given our limited resources, I would prefer that we don't try to go above and beyond what the Kubernetes project supports.

**Comment by jeanduplessis** [comment]
> Given our limited resources, I would prefer that we don't try to go above and beyond what the Kubernetes project supports.

I think given this context, the scaling issues for k8s < 1.23 and that it's only EKS that supports older versions really I think it then makes sense to follow the k8s life cycle.

**Comment by plumbis** [comment]
Docs update PR: https://github.com/crossplane/docs/pull/437

**Comment by negz** [comment]
I think we can close this as officially ratified by https://github.com/crossplane/docs/pull/438.
