### ISSUE TITLE
Ignored `FromEnvironmentFieldPath` patch type in `spec.environment.patches`

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4080]
### What happened?

The Composition's CRD is configured to accept patches of type `FromEnvironmentFieldPath` to be defined in `spec.environment.patches`, see [here](https://github.com/crossplane/crossplane/blob/c4031aab55c729df6af6a9e4d7b39e3cdd2dcce9/apis/apiextensions/v1/composition_environment.go#L119), but then the [ApplyEnvironmentPatches](https://github.com/crossplane/crossplane/blob/c4031aab55c729df6af6a9e4d7b39e3cdd2dcce9/internal/controller/apiextensions/composite/composition_patches.go#L64) function is not including them.

Given that patches in that context are only meant to be applied between the Composite Resource and the `in-memory` environment, the `FromEnvironmentFieldPath` patch would be semantically equivalent to the supported `ToCompositeFieldPath` type, so either we remove it from the APIs or we just remap it to a `ToCompositeFieldPath` in code. I'd lean toward the removal option given that that API is in alpha and it's actually confusing, but I'm open to discuss it.

### How can we reproduce it?

N.A. just looking at the code is enough.

### What environment did it happen in?
Crossplane version: v1.12.1

**Comment by negz** [comment]
I think removing it makes sense.
