### ISSUE TITLE
Unable to create Claim's secret with connection details in cluster with enabled OwnerReferencesPermissionEnforcement

### ISSUE THREAD

**Issue by chobostar** [crossplane/crossplane#4093]
### What happened?
After applying new XRD + Composition and trying to create claim with `writeConnectionSecretToRef` set, an error will be received:
>2023-05-18T05:25:55Z DEBUG crossplane.events cannot propagate connection details from composite: cannot create or update connection secret: cannot create object: secrets "dynamodb-connection-details" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil> {"type": "Warning", "object": {"kind":"CrossplaneAWSDynamodb","namespace":"mynamespace,"name":"mydynamodb","uid":"cb06a364-d16f-45b3-a68d-010d4c2c609d","apiVersion":"dynamodb.aws.example.com/v1alpha1","resourceVersion":"419946141"}, "reason": "PropagateConnectionSecret"}

XRD:
```
piVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplaneawsdynamodbs
spec:
  group: dynamodb.aws.example.com
  names:
    kind: XCrossplaneAWSDynamodb
    plural: xcrossplaneawsdynamodbs
  claimNames:
    kind: CrossplaneAWSDynamodb
    plural: crossplaneawsdynamodbs
...
```

Here is a ClusterRole created by Crossplane, we could see that permission to claim's finalizers is absent:
```
$ kubectl get clusterrole crossplane:composite:xcrossplaneawsdynamodbs.dynamodb.aws.example.com:aggregate-to-crossplane -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2023-05-18T05:07:31Z"
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
  name: crossplane:composite:xcrossplaneawsdynamodbs.dynamodb.aws.example.com:aggregate-to-crossplane
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CompositeResourceDefinition
    name: xcrossplaneawsdynamodbs.dynamodb.aws.example.com
    uid: ff696eba-6fa3-4a9c-a268-ebf9f59d51a5
  resourceVersion: "419906743"
  uid: c7b3cb6f-7212-4541-9dbb-f831abcc8a95
rules:
- apiGroups:
  - dynamodb.aws.example.com
  resources:
  - xcrossplaneawsdynamodbs
  - xcrossplaneawsdynamodbs/status
  verbs:
  - '*'
- apiGroups:
  - dynamodb.aws.example.com
  resources:
  - xcrossplaneawsdynamodbs/finalizers
  verbs:
  - update
- apiGroups:
  - dynamodb.aws.example.com
  resources:
  - crossplaneawsdynamodbs
  - crossplaneawsdynamodbs/status
  verbs:
  - '*'
```
missing one:
```
- apiGroups:
  - dynamodb.aws.example.com
  resources:
  - crossplaneawsdynamodbs/finalizers
  verbs:
  - update
```

missing creating here:
https://github.com/crossplane/crossplane/blob/v1.12.1/internal/controller/rbac/definition/roles.go#L156-L179

example:
https://github.com/crossplane/crossplane/blob/v1.12.1/internal/controller/rbac/definition/roles.go#L81-L91

### How can we reproduce it?
- Create cluster with `OwnerReferencesPermissionEnforcement`
- Create XRD + Composition
- Create claim with not empty `writeConnectionSecretToRef`

### What environment did it happen in?
Crossplane version: 1.12.1

* Kubernetes version (use `kubectl version`) - 1.24.1
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): OpenShift
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)

**Comment by chobostar** [comment]
Current workaround - apply additional ClusterRole for every XRD + Composition:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
  name: crossplane:claim:xcrossplaneawsdynamodb.dynamodb.aws.example.com:aggregate-to-crossplane
rules:
  - apiGroups:
      - dynamodb.aws.example.com
    resources:
      - crossplaneawsdynamodbs/finalizers
    verbs:
      - update
```

**Comment by turkenh** [comment]
@chobostar could you also share your claim?
I assume you're using `compositeDeletePolicy: Foreground`, right?

**Comment by chobostar** [comment]
> @chobostar could you also share your claim? I assume you're using `compositeDeletePolicy: Foreground`, right?
Yes, it is:
```
apiVersion: dynamodb.aws.example.com/v1alpha1
kind: CrossplaneAWSDynamodb
metadata:
  name: mydynamodb
  namespace: mynamespace
spec:
  compositeDeletePolicy: Foreground
  writeConnectionSecretToRef:
    name: dynamodb-connection-details
...    
```

Also related discussion here: https://github.com/crossplane/crossplane/pull/3444
