### ISSUE TITLE
managed GCP ServiceAccount became unready and failed to be synced

### ISSUE THREAD

**Issue by ZhiminXiang** [crossplane/crossplane#4099]
### What happened?
The managed ServiceAcount objects were created successfully in the beginning with both True for “Synced” and “Ready” status.

And recently most of the ServiceAccounts created before a specific time became unready with False “Synced”. Below is an example of this kind of ServiceAccount. 
```
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    crossplane.io/composition-resource-name: serviceaccount
    crossplane.io/external-create-pending: "2023-05-16T08:00:07Z"
    crossplane.io/external-create-succeeded: "2023-05-16T07:59:24Z"
    crossplane.io/external-name: sample-bucket-1-v7t6x-6276p
    upjet.crossplane.io/provider-meta: '{"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":300000000000}}'
  creationTimestamp: "2023-05-08T18:28:39Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: sample-bucket-1-v7t6x-
  generation: 1
  labels:
    crossplane.io/claim-name: sample-bucket-1
    crossplane.io/claim-namespace: zhimin-test-app
    crossplane.io/composite: sample-bucket-1-v7t6x
  name: sample-bucket-1-v7t6x-6276p
  resourceVersion: "2402572177"
  uid: 10b08c34-2ec8-4d48-9ecc-063bd4c43533
spec:
  deletionPolicy: Delete
  forProvider:
    description: Service Account for CruiseBucket zhimin-test-app/sample-bucket-1
    project: fake-gcp-project
  managementPolicy: FullControl
  providerConfigRef:
    name: default
status:
  atProvider:
    email: sample-bucket-1-v7t6x-6276p@fake-gcp-project.iam.gserviceaccount.com
    id: projects/fake-gcp-project/serviceAccounts/sample-bucket-1-v7t6x-6276p@fake-gcp-project.iam.gserviceaccount.com
    member: serviceAccount:sample-bucket-1-v7t6x-6276p@fake-gcp-project.iam.gserviceaccount.com
    name: projects/fake-gcp-project/serviceAccounts/sample-bucket-1-v7t6x-6276p@fake-gcp-project.iam.gserviceaccount.com
    uniqueId: "117607074063231467994"
  conditions:
  - lastTransitionTime: "2023-05-15T21:28:32Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-05-16T08:00:07Z"
    message: cannot determine creation result - remove the crossplane.io/external-create-pending
      annotation if it is safe to proceed
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2023-05-16T07:59:26Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2023-05-15T21:28:36Z"
    message: "apply failed: Error creating service account: googleapi: Error 409:
      Service account sample-bucket-1-v7t6x-6276p already exists within project projects/fake-gcp-project.\nDetails:\n[\n
      \ {\n    \"@type\": \"type.googleapis.com/google.rpc.ResourceInfo\",\n    \"resourceName\":
      \"projects/fake-gcp-project/serviceAccounts/sample-bucket-1-v7t6x-6276p@fake-gcp-project.iam.gserviceaccount.com\"\n
      \ }\n]\n, alreadyExists: "
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
```

### How can we reproduce it?
I am not sure how to reproduce it TBH. I tried restarting the GCP provider crossplane pod, but it still did not reproduce it.

### What environment did it happen in?
Crossplane version: 1.12.1 with GCP provider xpkg.upbound.io/upbound/provider-gcp:v0.32.0

k8s distribution: GKE

**Comment by ZhiminXiang** [comment]
I did more investigation. I think the direct cause is that

The “Synced” status became false because the timestamp in the annotation crossplane.io/external-create-pending (i.e. 2023-05-16T08:00:07Z) is after the timestamp in the annotation crossplane.io/external-create-succeeded (i.e. 2023-05-16T07:59:24Z), which triggered the [code](https://github.com/crossplane/crossplane-runtime/blob/1316ae6695eec09cf47abdfd0bc6273aeaab1895/pkg/reconciler/managed/reconciler.go#L756) (which blocked the reconciliation for this object).

**Comment by ZhiminXiang** [comment]
So to step further, I checked the crossplane provider logs. Here is what was happening:

1. ServiceAccount was created successfully initially.

2. Later, for some reasons, Crossplane GCP provider could not observe the existence of the ServiceAccount in GCP, which resulted in recreating the ServiceAccount, as well as refreshing the timestamp of those two annotations. Here is the related logs that showed the recreation of the SA
"""
1.6842239649631965e+09 DEBUG events Normal {"object": {"kind":"ServiceAccount","name":"sample-bucket-1-v7t6x-6276p","uid":"10b08c34-2ec8-4d48-9ecc-063bd4c43533","apiVersion":"cloudplatform.gcp.upbound.io/v1beta1","resourceVersion":"2392005835"}, "reason": "CreatedExternalResource", "message": "Successfully requested creation of external resource"}
"""

3. Even after recreating the ServiceAccount, the GCP provider pod still could not observe the existence of ServiceAccount in GCP. Here is the related logs to prove this.
"""
1.6842238840618289e+09 DEBUG provider-gcp Waiting for external resource existence to be confirmed {"controller": "managed/cloudplatform.gcp.upbound.io/v1beta1, kind=serviceaccount", "request": "/sample-bucket-1-v7t6x-6276p", "uid": "10b08c34-2ec8-4d48-9ecc-063bd4c43533", "version": "2392001866", "external-name": "sample-bucket-1-v7t6x-6276p"}
"""

4. Step 2 and step 3 kept repeating. 
And eventually, in the reconciliation loop, it failed to set the annotation `crossplane.io/external-create-succeeded`, which resulted in the timestamp of `crossplane.io/external-create-pending` (i.e. 2023-05-16T08:00:07Z) is after the timestamp in the annotation `crossplane.io/external-create-succeeded` (i.e. 2023-05-16T07:59:24Z), and paused the reconciliation. Here is the related logs to prove this.
"""
1.6842240076193163e+09 DEBUG events Warning {"object": {"kind":"ServiceAccount","name":"sample-bucket-1-v7t6x-6276p","uid":"10b08c34-2ec8-4d48-9ecc-063bd4c43533","apiVersion":"cloudplatform.gcp.upbound.io/v1beta1","resourceVersion":"2392006053"}, "reason": "CannotUpdateManagedResource", "message": "cannot update managed resource annotations: cannot update critical annotations: Operation cannot be fulfilled on serviceaccounts.cloudplatform.gcp.upbound.io \"sample-bucket-1-v7t6x-6276p\": the object has been modified; please apply your changes to the latest version and try again"}
"""
For step 4, I will check why the object has been modified. I suspect some concurrent operations were happening to this object.

So the question I have:
1. why GCP crossplane provider could not see the existence of the GCP service account?
2. are we OK to have more retries (e.g. using exponential retries) when [setting the annotation](https://github.com/crossplane/crossplane-runtime/blob/1316ae6695eec09cf47abdfd0bc6273aeaab1895/pkg/reconciler/managed/api.go#L196)?

**Comment by ezgidemirel** [comment]
Hello @ZhiminXiang, thanks for opening the issue and providing detailed observations. IMHO, as you asked above, the problem here is GCP provider could not observe the existing resource. Which caused Crossplane to annotate with `crossplane.io/external-create-pending`. I believe what Crossplane does was expected and we need a human intervention to make the resource `Synched: True` again. Please check Nic's comment [here](https://github.com/crossplane/crossplane/issues/3037#issuecomment-1110142427):
```
That's basically what this annotation does - ensures that if creation was ambiguous that we stop and ask a human to intervene rather than potentially creating more infrastructure than you actually asked for (e.g. creating a second VPC and leaking the original one).
```

Does it make sense to you that we move this issue to the provider-gcp [repo](https://github.com/upbound/provider-gcp) and let maintainers investigate the observe issue?
