### ISSUE TITLE
XFN container needs a default registry to pull images from

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#4116]
### What problem are you facing?
Composition functions require the image registry to be specified in the Composition along with the repository and tag, unlike Provider and Configuration `package` specifications which only require the repository and tag.  This makes portability of Compositions a lot more difficult when different environments use different registries.

The crossplane container accepts a `-r registry` command line option to allow for a default registry to pull packages from.  It defaults to `index.docker.io` but can be overridden to pull from a specific registry by default.  That allows Provider and Configuration packages to specify only the repository and tag information for an image, and they are registry-independent.

### How could Crossplane help solve your problem?
Provide support for a configurable default image registry to pull Composition Function images from so that the registry does not need to be specified in the Composition.

**Comment by bobh66** [comment]
Hi @pedjak - I have an idea how to solve this if you haven't started on it yet.  It's becoming more of a blocker for us so I'd like to get it into the next release, but happy to wait if you're working on it.  Thanks!

**Comment by pedjak** [comment]
@bobh66 thanks for offering the help - I did not start working on the issue yet. Looking forward to your contribution.
