### ISSUE TITLE
Package condition "UnknownPackageRevisionHealth" has Type: Healthy

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4135]
The Condition `Status: UnknownPackageRevisionHealth` uses `Type: Healthy`. 

https://github.com/crossplane/crossplane/blob/e7be8efab0cef960ce979e70c7b5ee6e46ebbc34/apis/pkg/v1/conditions.go#L99-L104

Should we introduce a new [ConditionType](https://github.com/crossplane/crossplane/blob/e7be8efab0cef960ce979e70c7b5ee6e46ebbc34/apis/pkg/v1/conditions.go#L27) of `Unhealthy`?

**Comment by turkenh** [comment]
I see the confusion but it seems aligned with the [API conventions](https://github.com/zecke/Kubernetes/blob/master/docs/devel/api-conventions.md#typical-status-properties).

> Condition status values may be True, False, or Unknown. The absence of a condition should be interpreted the same as Unknown.

> A typical oscillating condition type is Ready, which indicates the object was believed to be fully operational at the time it was last probed. A possible monotonic condition could be Succeeded. A False status for Succeeded would imply failure. An object that was still active would not have a Succeeded condition, or its status would be Unknown.

Also, I think `UnknownPackageRevisionHealth` does not mean `Unhealthy` and `UnknownPackageRevisionHealth` seems to be the [Reason](https://github.com/crossplane/crossplane/blob/e7be8efab0cef960ce979e70c7b5ee6e46ebbc34/apis/pkg/v1/conditions.go#L42), not Status.

**Comment by negz** [comment]
Yeah, I think this is working as intended.
