### ISSUE TITLE
Represent ownership via managed resource metadata

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#418]
**Is this a bug report or feature request?** Feature Request

**What should the feature do:** Cloud resources (SQL databases, Kubernetes clusters, Redis clusters, etc) that are managed by Crossplane should, where possible, contain some metadata to allow them to be traced back to the Crossplane resource that manages them.

This should metadata should capture, at a minimum:

* That the managed resource is managed by Crossplane.
* Which Crossplane instance manages the managed resource.
* Which (Kubernetes) resource within the aforementioned Crossplane instance represents the managed resource.

It may also be useful to propagate some of the Kubernetes resource's metadata. For example if the managed resource supports key:value labels then perhaps a Crossplane resource claim with label `labels.crossplane.io/foo=bar` would result in the managed resource being labeled `foo=bar`.

**What is use case behind this feature:** Occasionally during the course of testing Crossplane a managed resource is orphaned. When this happens it's very difficult to determine via the cloud console who originally created the orphaned resource and whether it's safe to terminate it. This is also relevant for resources that are not orphaned but that are using a lot of resources; it's difficult to determine who owns the resource to verify whether they really need the resources they've requested. I imagine these same concerns would be valid in a larger scale production environment in which resources may be managed by one or more Crossplane instances.

**Comment by negz** [comment]
@ichekrygin Pointed out that some of our resources (e.g. GKECluster) already support adding resource labels explicitly as part of their spec.

**Comment by negz** [comment]
Related: https://github.com/crossplane/crossplane/pull/1129

**Comment by muvaf** [comment]
> some of our resources (e.g. GKECluster) already support adding resource labels explicitly as part of their spec.

This is true for all resources that are v1beta1 if they support labelling/tagging. #1129 generates a set of tags to be used but does not automagically copy some prefixed labels from Kubernetes metadata into the tags array of the managed resource. @negz is this what we'd like to achieve? I can see it helping with standardizing labelling for all resources, which can be utilized by the platforms built on top of Crossplane. Maybe another issue for this?

**Comment by negz** [comment]
Relates to https://github.com/crossplane/crossplane-runtime/issues/254.

**Comment by muvaf** [comment]
There is now a way to do this with a standard set of tags and it's applied in many provider-aws resources (like this [one](https://github.com/crossplane/provider-aws/blob/793e588/pkg/controller/ecr/repository/controller.go#L260)). We could do more to make it easier like https://github.com/crossplane/crossplane-runtime/issues/254 but the functionality is there and it's up to the providers now to implement it.
