### ISSUE TITLE
/tmp isn't accessible for xfn functions

### ISSUE THREAD

**Issue by mikebryant** [crossplane/crossplane#4182]
### What happened?

I tried to write a simple function in bash/jq, and use `/tmp` to store intermediate steps

It looks like the xfn containers run with a read-only root filesystem, but this was really hard to figure out.

Assuming this behaviour is kept, it should be documented?

### What environment did it happen in?
Crossplane version:

**Comment by negz** [comment]
It's intentional for now. I'm not against offering a size-capped writable tmpfs though.
