### ISSUE TITLE
Provide additional context when E2E tests fail

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4254]
### What problem are you facing?

At the time of writing when an E2E test fails the convention is to print the object being assessed as YAML. For example if a claim should become Ready, but doesn't, we'll return an error and dump out the claim as it appears in the API server.

This is okay, but we could do more. I often find myself running E2E tests with `-destroy-kind-cluster=false` so I can inspect the test environment (i.e. kind cluster) more deeply.

### How could Crossplane help solve your problem?

Ideally we'd provide more context. Some ideas include:

* Grab the debug logs from all Crossplane containers and upload them as a [workflow artifact](https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts).
* Grab the "debug logs" (i.e. `--v=4` logs) from e2e-framework and upload them as a workflow artifact, too.
* Find and dump the state of related objects - e.g. a claim's XR and MRs, a package's revisions, etc.

**Comment by phisco** [comment]
We actually did this, we now upload all logs from the kind cluster on failure, with audit logs enabled. And we also print related objects + events when it make sense.
