### ISSUE TITLE
Add descriptions to E2E features and assessments

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4258]
### What problem are you facing?

Our E2E tests are categorizes, from least-to-most-specific:

1. By feature area label.
2. By test function name.
3. By feature name.
4. By assessment (step) name.

Labels are `key=value`, but all other names are `CamelCase`. At the moment we're missing a human-readable description of each feature and assessment. A lot of folks use the names to provide this, but that ends up looking pretty ugly when printed per https://github.com/kubernetes-sigs/e2e-framework/issues/277.

### How could Crossplane help solve your problem?

I've asked in https://github.com/kubernetes-sigs/e2e-framework/issues/277 that e2e-framework add support for a prose description of each feature and assessment. They seem open to adding the functionality - when they do we should start using it.

**Comment by phisco** [comment]
https://github.com/kubernetes-sigs/e2e-framework/pull/284 got merged, so now this can be done, we should:
-  switch from `features.New` to `features.NewWithDescription` where applicable, adding meaningful descriptions.
-  switch from `Assess` to `AssessWithDescription` where applicable, adding meaningful descriptions.

**Comment by jeanduplessis** [comment]
I made an attempt at adding descriptions for the features.New calls: https://github.com/crossplane/crossplane/pull/5931
