### ISSUE TITLE
Write retroactive E2E tests 😁 

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4259]
### What problem are you facing?

I merged the latest iteration of our E2E tests today in https://github.com/crossplane/crossplane/pull/4187. As part of that effort I made sure we:

* Had parity with previous E2E test implementations - i.e. didn't lose any coverage.
* Put some systems in place to remind contributors to write new tests.

These alone won't help us get to great E2E test coverage. When test coverage is already low it's easier for folks to justify not adding tests for their contributions. This is especially true when adding a test for your tiny change requires you to also test the entire foundation around it. (e.g. Who wants to write a test for all of Composition just because they want to add a new type of transform?)

### How could Crossplane help solve your problem?

I think we need a concerned effort to catch up on test coverage. I don't think E2E tests need to cover _everything_ - especially not right now - but every major feature should at least be exercised. Here a list of areas that aren't covered:

```[tasklist]
- [ ] All Composition patch and transform types.
- [ ] Composition revisions.
- [ ] Writing Kubernetes connection secrets - claims, XRs, and MRs.
- [ ] The RBAC manager in 'full' mode - i.e. namespace RBAC roles.
- [x] Alpha: Composition Functions
- [ ] https://github.com/crossplane/crossplane/issues/4725
- [x] Alpha: Composition Schema Validation
- [ ] Alpha: Environment configs
```

**Comment by phisco** [comment]
Composition Schema Validation covered: https://github.com/crossplane/crossplane/blob/696f398cca80f659c970db0cea1ea4412c985b17/test/e2e/apiextensions_test.go#L108

Environment Configs will be addressed by: https://github.com/crossplane/crossplane/pull/4379

**Comment by phisco** [comment]
I would argue we don't actually need e2es for all patch and transform types, we already have some basic testing, the rest is already widely covered by unit tests.

**Comment by phisco** [comment]
Composition functions seminal work already in place: https://github.com/crossplane/crossplane/blob/696f398cca80f659c970db0cea1ea4412c985b17/test/e2e/xfn_test.go#L44

**Comment by phisco** [comment]
Some Environment config e2es added in #4379
