### ISSUE TITLE
Validate XRD's `spec.names|claimNames.plural` to be lowercase

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4266]
### What problem are you facing?

CompositeResourceDefinition's `spec.names.plural` and `spec.claimNames.plural` should be all lowercase, we [reuse](https://github.com/crossplane/crossplane/blob/104ea2d8566558a2c8baad5923eee446abb8625b/apis/apiextensions/v1/xrd_types.go#L39) the upstream `CustomResourceDefinitionNames` which is not enforcing it in the schema.

### How could Crossplane help solve your problem?

This is a common issue for users, e.g. https://github.com/crossplane/crossplane/discussions/4249#discussion-5326775, we should prevent it by either validating these fields to be all lowercase in the XRD Webhook or preferably directly in the XRD Schema.

**Comment by phisco** [comment]
Defining `// +kubebuilder:validation:XValidation:rule="self.plural.lowerAscii() == self.plural",message="plural must be all lowercase"` as follows would result more or less the desired behaviour:

// CompositeResourceDefinitionSpec specifies the desired state of the definition.
type CompositeResourceDefinitionSpec struct {
...
	// Names specifies the resource and kind names of the defined composite
	// resource.
	// +immutable
	// +kubebuilder:validation:XValidation:rule="self.plural.lowerAscii() == self.plural",message="plural must be all lowercase"
	Names extv1.CustomResourceDefinitionNames `json:"names"`

	// ClaimNames specifies the names of an optional composite resource claim.
	// When claim names are specified Crossplane will create a namespaced
	// 'composite resource claim' CRD that corresponds to the defined composite
	// resource. This composite resource claim acts as a namespaced proxy for
	// the composite resource; creating, updating, or deleting the claim will
	// create, update, or delete a corresponding composite resource. You may add
	// claim names to an existing CompositeResourceDefinition, but they cannot
	// be changed or removed once they have been set.
	// +immutable
	// +optional
	// +kubebuilder:validation:XValidation:rule="self.plural.lowerAscii() == self.plural",message="plural must be all lowercase"
	ClaimNames *extv1.CustomResourceDefinitionNames `json:"claimNames,omitempty"`

...
}
```
Would correctly return an error when trying to apply the following XRD:
```
kubectl apply -f - <<EOF
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwordpresses.releases.example.io
spec:
  group: releases.example.io
  names:
    kind: XWordpress
    plural: XWordpresses
  claimNames:
    kind: Wordpress
    plural: Wordpresses               # <== should be lowercase
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Wordpress is a composite resource that represents a Wordpress Installed
          type: object
          properties:
            spec:
              type: object
              properties:
                MyWordpressVersion:
                  type: string
              required:
                - MyWordpressVersion
EOF

The CompositeResourceDefinition "xwordpresses.releases.example.io" is invalid:
* spec.names: Invalid value: "object": plural must be all lowercase
* spec.claimNames: Invalid value: "object": plural must be all lowercase
```
 Would have been nice to have `Invalid value: "Wordpresses"` instead of `Invalid value: "object"`, but doesn't look like this can be done atm using Validation Rules.

**Comment by negz** [comment]
I suggest we make our own copies of any API structs that we're currently importing from `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1`. That way we can use simple validation annotations - no need for CEL here.

We should be able to generate code to convert between our structs and the upstream ones using `goverter`, which is already part of our build pipeline. See for example https://github.com/crossplane/crossplane/blob/v1.12.2/apis/apiextensions/v1/conversion.go.

**Comment by negz** [comment]
> any API structs that we're currently importing

So that would be:

* `extv1.CustomResourceConversion`
* `extv1.CustomResourceDefinitionNames` 
* `extv1.CustomResourceColumnDefinition`

**Comment by sttts** [comment]
Copies of API types have other merits. But just for the schema there is no need. There are workarounds: https://github.com/kube-bind/kube-bind/blob/main/hack/update-codegen.sh#L43

**Comment by negz** [comment]
> Copies of API types have other merits.

Right - so let's make copies. I would prefer that to patching the generated CRDs.

**Comment by phisco** [comment]
I agree CEL validation was overkill, that's why I didn't create a PR right away. I would probably prefer checking this in the ValidatingWebhook, instead of using CEL, but I agree this specific case just having the lowercase pattern enforced at the API level would be the best. And I do agree patching would make it harder to understand what's happening, and I'd rather avoid that too.

The only advantage of using upstream API structs in cases in which we are only "passing down" the whole content, such as  in this case, is that we get new fields for free by just updating dependencies.

**Comment by phisco** [comment]
This kind of issues is caught by https://github.com/crossplane/crossplane/pull/4484
