### ISSUE TITLE
Horizontal scaling of providers to increase throughput

### ISSUE THREAD

**Issue by Breee** [crossplane/crossplane#4269]
### What problem are you facing?

- Currently it is only possible to scale providers vertically, i.e.  by assigning more CPU/RAM to a single node. 
- The horizontal scaling currently has the purpose for failover (debateable if this is even necessary) 
- In theory you can scale horizontal by disabling leader election of a provider and then scale it, however, it makes it unpredictable since there is no shared processing queue for the workers, what ressources have to be processed next. 

### What could we do?
- A leader that fills a queue (maybe this is even possible with ETCD itself), such that workers can pick them up. 
- Annotate ressources such that they are marked for processing
- ...
There are for sure other ways, we have to avoid race conditions tho

**Comment by negz** [comment]
I'm not against this, but I'd like to make sure we feel we have providers quite well optimized before we start pursuing it in earnest. Given the job of a provider is basically read from one API and call another it seems like it _should_ be possible to do quite a lot with a single controller. At this point horizontal sharding feels a bit more like a bandaid for performance issues.
