### ISSUE TITLE
Provider fails when two packages has same image hash

### ISSUE THREAD

**Issue by zicongmei** [crossplane/crossplane#4271]
### What happened?

The provider can't move to a HEALTHY state when the the package images has same hash for old and new versions. We are migrating the docker repo hosting the images and the old and new images has same hash but different URLs. 

Old package image: `repo.a.com/provider-name:v0.7.0@sha256:df385e7cdcd2e5bc57a2b419d6154fb968cd8d24f9811ba044e09efcd706f278`

New package image: `repo.b.com/provider-name:v0.7.0@sha256:df385e7cdcd2e5bc57a2b419d6154fb968cd8d24f9811ba044e09efcd706f278`

In this case, the containerd won't pull the new image because it has the same hash as the old one. And the crossplane can't handle this situation. The error remains even if I added `packagePullPolicy: Always`.

And the result is 
```
$ kubectl describe ProviderRevision  -n crossplane-system
...
  Warning  ResolveDependencies  5s (x14 over 8m11s)     packages/providerrevision.pkg.crossplane.io  cannot resolve package dependencies: missing node in tree
```

The pod shows the image status and spec are different because containerd won't repull the images when they have same hash.
```
$ kubectl get pod -n crossplane-system provider-name-df385e7cdcd2-6f796cbf7c-dlhc4 -oyaml
...
spec:
    image: repo.b.com/provider-name:v0.7.0@sha256:df385e7cdcd2e5bc57a2b419d6154fb968cd8d24f9811ba044e09efcd706f278
    imagePullPolicy: IfNotPresent
    ...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-27T15:59:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-27T15:59:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-27T15:59:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-27T15:59:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: sha256:feef78a5962702cf5195e3085ab723a6cc5a3c34add8d54c4592fb143b8b6812
    imageID: repo.a.com/provider-name:v0.7.0@sha256:df385e7cdcd2e5bc57a2b419d6154fb968cd8d24f9811ba044e09efcd706f278
```

The lock keeps the old repo after the new repo is applied.
```
$ kubectl get lock -oyaml
apiVersion: v1
items:
- apiVersion: pkg.crossplane.io/v1beta1
  kind: Lock
  metadata:
    creationTimestamp: "2023-06-27T15:56:22Z"
    finalizers:
    - lock.pkg.crossplane.io
    generation: 2
    name: lock
    resourceVersion: "4886407"
    uid: fd8f7f13-8304-4cc9-ad21-1d57f34cdcef
  packages:
  - dependencies: []
    name: provider-name-df385e7cdcd2
    source: repo.a.com/provider-name:v0.7.0
    type: Provider
    version: sha256:df385e7cdcd2e5bc57a2b419d6154fb968cd8d24f9811ba044e09efcd706f278
kind: List
metadata:
  resourceVersion: ""
```

### How can we reproduce it?

1. Deploy the same provider image to two different docker repos.
2. Create the provider with one of the image repos.
3. Change the the provider to the other repo and the error occurs.
  3.1. Change the `packagePullPolicy` to `Always` and the problem remains.

### What environment did it happen in?
Crossplane version: `docker.io/crossplane/crossplane:v1.12.2`

**Comment by negz** [comment]
Is this a duplicate of https://github.com/crossplane/crossplane/issues/3985? 


Also likely related: https://github.com/crossplane/crossplane/issues/4022

**Comment by zicongmei** [comment]
duplicate of https://github.com/crossplane/crossplane/issues/3985
