### ISSUE TITLE
Orphan handling

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#4273]
### What problem are you facing?
Sometimes using orphan as a deletion policy makes sense, for example if a resource is very hard to recover. However, this leads to a need to clean up the resource manually, and we need a list of orphaned resources to do this. For example, this involve a process like exporting data from the resource to archival storage and then deleting the resource.

### How could Crossplane help solve your problem?

Some possible ways to make it easier to manage orphaned resources:
* Emit a log event in crossplane-runtime to use log tools like CloudWatch Logs to report on orphaned resources
* Emit a kubernetes event. Events are usually deleted after a short time so this might be useful as an addition but not alone
* Add a tag to orphaned resources (something like `crossplane.io/orphaned-at: YYYY-MM-DDTHH:MM:SS`). This requires work on each provider, but will often give a good experience in the external resource system, where you often can report on tags.
* Solve it another way by making a pattern for other solutions to run a "hook" before deleting the resource (similar to finalizers).
* Other ideas?

**Comment by turkenh** [comment]
Two more ideas are coming to my mind:

- Persist a list of orphaned resources (i.e. GVK, external-name) in a configmap, preferably per provider, but implemented in xp-runtime.
- Via a separate admission webhook that registers to all `Delete` requests on XP resources and persist orphaned resources somewhere (again a configmap maybe) before allowing deletion.
