### ISSUE TITLE
`FunctionIO` desired resources array is not bootstrapped with all observed resources

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4288]
### What happened?

https://docs.crossplane.io/knowledge-base/guides/composition-functions/ says:

> The desired state of the XR and composed resources is how your Function tells Crossplane what it should do. Crossplane ‘bootstraps’ the initial desired state passed to a Function pipeline with:
>
> * A copy of the observed state of the XR.
> * __A copy of the observed state of any existing composed resources.__
> * Any new composed resources or modifications to observed resources produced from the resources array.

This isn't actually true today - it only includes observed resources that have a corresponding entry in the `resources` array.

https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/internal/controller/apiextensions/composite/composition_ptf.go#L613

### What environment did it happen in?
Crossplane version: 444267e84783136daa93568b364a5f01228cacbe

**Comment by negz** [comment]
I've added the `docs` label but raised this here rather than c/docs, because ideally we'd update the implementation to match the documentation rather than the other way around. Sadly I'm not sure we _can_ do that, though.

In the current `PTFComposer` implementation Crossplane knows that an observed (i.e. existing) resource is no longer desired (i.e. should be deleted) if that resource does not appear in the desired resources array produced by the Function pipeline.

The problem then is P&T resources. It's possible to use P&T together with Functions, but if we just bootstrap the desired resources array with all observed resources it will become impossible to delete a resource just by removing it from the P&T resources array. Unless a Function chooses to remove the observed resource from the array we won't notice that nothing actually desires it anymore and it will stick around forever.

FWIW I'm working on this as part of https://github.com/crossplane/crossplane/issues/3896, which has turned into a larger refactor/rethink of the `PTFComposer` implementation.

**Comment by erikgb** [comment]
Relates to https://github.com/crossplane/docs/pull/506

**Comment by negz** [comment]
Just explicitly capturing how I think this should work (and will with https://github.com/crossplane/crossplane/pull/4500):

* The `observed` state passed to the first Function should include all observed resources.
* The `desired` state passed to the first Function should include only rendered P&T templates.

The difference from the current implementation is that we'll render the templates onto an empty composed resource, not the existing observed resource. So unlike the current implementation, `desired` (when passed to the first Function) will never include any observed state - only accumulated desired state.
