### ISSUE TITLE
Define a guideline around OCI image management used in e2e tests

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4294]
As suggested by @phisco [here](https://github.com/crossplane/crossplane/pull/4261#discussion_r1251138250) I am opening this issue to discuss/define a guideline around OCI image management used in e2e.test.

### What problem are you facing?

Recent introduction of [e2e-framework](https://github.com/kubernetes-sigs/e2e-framework/) opened up possibility to start testing crossplane functionalities end-to-end. Such tests typically depend on existence of a provider and/or functions to successfully assert that a given functionality works as expected.

In order to execute these tests as efficient as possible, as stated in [README](https://github.com/crossplane/crossplane/blob/master/test/e2e/README.md) it is recommended to use either [provider-nop](https://github.com/crossplane-contrib/provider-nop) or [provider-dummy](https://github.com/upbound/provider-dummy). They do not depend on any cloud provider and can be used to simulate variety of interesting interactions.

Apart from providers, some tests require crafting and using [configurations](https://docs.crossplane.io/latest/concepts/terminology/#configuration) and/or [functions](https://docs.crossplane.io/knowledge-base/guides/composition-functions/#using-functions) to assert the system behaviors.

Given that both configurations and functions are packaged and distributed as OCI images, it would be important to define a guideline/best practices for their management, so that developer/contributor effort remains lean.

### How could Crossplane help solve your problem?

We should always try to use a public image if possible, but very often we are going to have a situation that none of the images is suited enough for the given usecase (e.g. if we need to test some error case, we need an image that produces such error).

The configurations and functions used in e2e tests have very limited/specific logic that triggers a behavior specific to given tests, i.e. they lack generic usage out of e2e context.

Hence, I would like to propose that we manage the image source file (`Dockerfile`,...) within crossplane repo:
* files for each image should be kept in a dedicated folder under `test/e2e/testdata/images`
* images are built before running e2e tests, and pushed to a container registry, deployed within k8s cluster

Such approach has a few advantages:
* allows to iterate fast, because all files required for testing are within single repo, no additional PRs are needed when a new configuration/function is needed
* lower the dependency to external container registry
* avoid polluting external/public registries with images that do not have any purpose beyond e2e testing

Ofcourse,  if we recognize that the image is getting actually useful outside of e2e testing context, it can be promoted it, i.e. moved to its own code repo and published in a public registry.

**Comment by negz** [comment]
This sounds closely related to:

* https://github.com/crossplane/crossplane/issues/4257

**Comment by pedjak** [comment]
Yes, but with a twist that proposes the opposite strategy - push test specific images (not having any other purpose outside of e2e testing context) to a private registry deployed within the cluster under the test.
