### ISSUE TITLE
Variabilize the webhook port and metric server port in crossplane helm chart

### ISSUE THREAD

**Issue by ravibagri4** [crossplane/crossplane#4297]
Currently, We're using Crossplane 1.10.2 and are unable to proceed with upgrading it to the latest version.  As, we're running all the webhooks on hostNetwork, and the latest Crossplane chart has ports 8443 and 8080 hardcoded in the chart. Which are conflicting with our existing ports used by other webhooks.

We can override the webhook port 8443 using the Kustomize overlays. But somehow the 8080 port isn't getting overridden. 
Also, disabling the metric server isn't helping, as the controller pod is still trying to listen on port 8080 which we're using for Istio discovery. 

FYI, We're using the hostNetwork because we're using the Cilium CNI with AWS EKS with customized POD_CIDR. So we can't communicate with the k8s API server from the current POD_CIDR with the CIlium CNI without running it on hostNetwork. 

Currently, We're using Crossplane 1.10.2 and are unable to proceed with upgrading it to the latest version. So it would be great if we could get a minor release with an updated helm chart for using custom ports for both the webhook and the metric server. Please let me know in case I need to provide any other details here.

**Comment by jbw976** [comment]
Thanks for reporting this @ravibagri4 - looks like the 1.10 chart also had these ports in the chart: https://github.com/crossplane/crossplane/blob/release-1.10/cluster/charts/crossplane/templates/deployment.yaml#L99-L106

any ideas why 1.10.2 was able to work for you even though the ports were there too? 🤔 

maybe the [addition of the `hostNetwork` setting in the chart](https://github.com/crossplane/crossplane/commit/c55935ee0973d8854cb5e0f023eac06e15d4bef8) from the [recent history](https://github.com/crossplane/crossplane/commits/master/cluster/charts/crossplane/templates/deployment.yaml) could also be relevant here?

**Comment by phisco** [comment]
I think it's because we enabled webhooks by default in 1.11, @jbw976. Unfortunately we don't handle validating webhooks from the helm chart, we build them into the images and create it's then crossplane itself that creates them, which has a series of drawbacks, such as not being able to clean them up if a user wanted disable them after having enabled them. I was trying to think whether we could move them to the chart, but the transition isn't going to be straightforward as the helm chart would have to take ownership of an already existing resource.

**Comment by ravibagri4** [comment]
@phisco That's exactly what happened. After the upgrade, the webhook was enabled, and disabling it didn't clean up. Anyways, we now want to enable the webhook but for that, we need to override these ports.

**Comment by ravibagri4** [comment]
Any update on this? Do we have any timeline for this change so that we can plan accordingly?

**Comment by willjw1** [comment]
/fresh we are having this issue too.  We are using calico and have multiple items running on the HostNetwork.  Since we couldn't change what port this was expecting to bind, we modified the conflicting port to bind to a different port (argo-rollouts)

**Comment by jbw976** [comment]
Hmm, looks like this may be covered by this PR now if I'm reading it correctly:

* https://github.com/crossplane/crossplane/pull/5540
