### ISSUE TITLE
User-specified MR labels (aka tags) remove built-in labels

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4302]
### Discussed in https://github.com/crossplane/crossplane/discussions/4296

<div type='discussions-op-text'>

<sup>Originally posted by **gberche-orange** July  4, 2023</sup>
I'm trying to add user labels on my gcp cloudsql instance, in addition to the built-in labels crossplane-kind, crossplane-name, and crossplane-provider, (specified into https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#external-resource-labeling )

However, as soon as new labels are defined in the MR spec, then the built-in labels get removed from the GCP cloud sql api, and only the explicit user labels get sent to the GCP sql api. I did not yet find associated integration test case into the upbound gcp-provider repo (only examples of user defined labels in https://github.com/upbound/provider-gcp/blob/bc2a0fa01b445d86af4234881490850df58b992a/examples-generated/monitoring/service.yaml#L16-L18, but no yet kuttl assertions about the built-in labels).

Any idea for a workaround ?

(initially posted on slack general channel https://crossplane.slack.com/archives/CEG3T90A1/p1688485153373599 )</div>

**Comment by negz** [comment]
@jbw976 @ulucinar my guess is this issue probably belongs best in upbound/upjet or c/crossplane-runtime, right?
