### ISSUE TITLE
Removing annotation in Claim does not remove the corresponding annotation in XR

### ISSUE THREAD

**Issue by ZhiminXiang** [crossplane/crossplane#4315]
### What happened?
I added an annotation to a Claim, which populated the annotation to XR, which is expected.

However, after I deleted the annotation from the Claim, the annotation in XR was still preserved.

### How can we reproduce it?
I think this could easily reproduced by using any crossplane example.

### What environment did it happen in?
Crossplane version: 1.12.0

**Comment by ZhiminXiang** [comment]
I am wondering if this is related to https://github.com/crossplane/crossplane/issues/4047.

**Comment by ZhiminXiang** [comment]
Also we passed the annotation from XR to the managed resources. Looks like removing the annotation in the XR does not remove the corresponding annotation in the managed resources.

**Comment by negz** [comment]
> I am wondering if this is related to https://github.com/crossplane/crossplane/issues/4047.

My guess is that it is.

**Comment by sttts** [comment]
Yes, SSA should assign the XR controller as owner, and as soon as that controller stops applying that field (annotation) it should go away. cc @pedjak

**Comment by pedjak** [comment]
Fixed via https://github.com/crossplane/crossplane/pull/4896.
