### ISSUE TITLE
Allow private helper functions in e2e test for improved readability

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4337]
### What problem are you facing?

During the review of https://github.com/crossplane/crossplane/pull/4261 @phisco [suggested](https://github.com/crossplane/crossplane/pull/4261#discussion_r1258373106) to unwrap a number of setup/assess functions in order to match [the current pattern](https://github.com/crossplane/crossplane/blob/master/test/e2e/README.md?plain=1#L88), visible in existing e2e `*_test.go` - only single function per go file.

The test introduced in https://github.com/crossplane/crossplane/pull/4261 required a few custom steps, not available in `test/e2e/funcs`. Adding them to that package within PR would be premature, because none of existing tests need them, nor there is any certainty that they are going to be needed in the future. Thus, these functions were added to `xfn_test.go` and the test itself looked like:

```go
func TestXfnRunnerImagePull(t *testing.T) {

	manifests := "test/e2e/manifests/xfnrunner/private-registry/pull"
	environment.Test(t,
		features.New("PullFnImageFromPrivateRegistryWithCustomCert").
			WithLabel(LabelArea, "xfn").
			WithSetup("InstallRegistryWithCustomTlsCertificate",
				funcs.AllOf(
					funcs.AsFeaturesFunc(envfuncs.CreateNamespace("reg")),
					CreateTLSCertificateAsSecret("private-docker-registry.reg.svc.cluster.local", "reg"),
					InstallDockerRegistry(),
				)).
			WithSetup("CopyFnImageToRegistry", CopyImagesToRegistry()).
			WithSetup("CrossplaneDeployedWithFunctionsEnabled", CrossplaneDeployedWithFunctionsEnabled()).
			WithSetup("ProvideNopDeployed", ProvideNopDeployed()).
			Assess("CompositionWithFunctionIsCreated", funcs.AllOf(
				funcs.ApplyResources(FieldManager, manifests, "composition.yaml"),
				funcs.ResourcesCreatedWithin(30*time.Second, manifests, "composition.yaml"),
			)).
			Assess("ClaimIsCreated", funcs.AllOf(
				funcs.ApplyResources(FieldManager, manifests, "claim.yaml"),
				funcs.ResourcesCreatedWithin(30*time.Second, manifests, "claim.yaml"),
			)).
			Assess("ClaimBecomesAvailable", funcs.ResourcesHaveConditionWithin(5*time.Minute, manifests, "claim.yaml", xpv1.Available())).
			Assess("ManagedResourcesProcessedByFunction", ManagedResourcedProcessedByFunction()).
			Feature(),
	)
}
```

IMHO, the test was more readable than [the version merged afterwards](https://github.com/crossplane/crossplane/blob/master/test/e2e/xfn_test.go#L41-L229). The test function body is much more shorter and steps function names clearly state what is about to happen.

### How could Crossplane help solve your problem?

We should update the pattern for adding new e2e tests to allow the following:
* A non-trivial step logic can be wrapped into a dedicated function that lives within the same test file
* At the time when a followup test is added, and we see that the function can be reused, then we could move it to `test/e2e/funcs` package.
* Additional private helper functions should be allowed as well, if they improve readability

**Comment by phisco** [comment]
@pedjak, if you read carefully the comments and the discussion we had privately, or maybe we had a (long) misunderstanding, I never suggested not using private functions at all, nor did I suggest blindly unrolling everything, I was only suggesting to do some refactoring given that I would have preferred not having hardcoded values hidden into some function and the overall code quality and readability of the code didn’t feel up to the standard of all the other existing tests. Given that we are currently defining our e2e framework and helpers, I could see a few parts of the code you wrote becoming useful helpers.

**Comment by pedjak** [comment]
Thanks @phisco for clarifying, and apologizes if I misunderstood you. However, I do think it would be important to add to README a few sentences that private helper functions are allowed.
