### ISSUE TITLE
Package versioning and upgrading design

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#435]
Following the [initial design for Stacks](https://github.com/crossplaneio/crossplane/issues/397), more thought is needed around supporting the updating of Stacks as well as the upgrading of Stacks.

This issue is focused on the Stacks ecosystem and Stacks usability.  Specific Crossplane claim types (aside from StackInstall) are not the focus of this issue.  The interoperability of all Crossplane claim types as they change versions is a concern for this design.

The format and changes in format for Stacks and StackInstall resources are also left to later discussion, as this is a broader Crossplane concerns.

Some discussion: https://github.com/crossplaneio/crossplane/pull/397#discussion_r276371864

Some thoughts and issues to consider in this design:
* #937 Do we want to support the concept of subscriptions and channels that can be subscribed to?
  * this is starting to make a lot of sense in terms of upgrades for new versions of the Stack that are released
* How do we deal with upgrades? Manually started by user? automatic in the case of a subscription? Dependency resolution across new versions of Stacks that are released at different times?
* #1051 Changes in version could affect multiple instances of the same StackInstall / Stack in different namespaces
* Versioning of CRDs, is all the necessary support in upstream Kubernetes to add new versions of CRDs and run them all side-by-side? We may need to research/prototype/confirm that our scenarios are supported upstream.
  * #1052 Reject instances of a StackInstall that conflict with installed StackInstalls
  * #1014 What problems existing with multiple versions of the same namespaced stack?
  * #1013 Merging or using the best CRDs (inclusive of the most versions) to fulfill StackInstall resources
  * #1152 conversion web-hooks
* #1042 Watch child artifacts for updates and re-sync / heal resources (e.g. deployments)

Part of #879

**Comment by negz** [comment]
I believe this is fixed (i.e. designed, not implemented) by #1616.
