### ISSUE TITLE
crossplane 1.12.2 results in huge memory

### ISSUE THREAD

**Issue by Dineshvcetster** [crossplane/crossplane#4378]
### What happened?
After upgrading from v1.11.2 to v1.12.2 huge increase in the memory. We set 1GB memory and still it is oomkilled

### How can we reproduce it?
We have 1600 components

### What environment did it happen in?
Crossplane version: v1.12.2

* Cloud provider - Provider Kubernetes
* Kubernetes version (use `kubectl version`) - k1.26
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - GKE

**Comment by jbw976** [comment]
Thanks for reporting this @Dineshvcetster - are there any other details you can provide? e.g.:

* how much memory was it using in v1.11.2?
* how high do you have to set the limit so its no longer OOMKilled?
* is the memory usage steady over time? Does it spike initially and then settle down? does it slowly climb up unbounded?
* What providers do you have installed? are they using a lot of memory, or are you only talking about the core Crossplane pod?

**Comment by Dineshvcetster** [comment]
Thanks @jbw976 

**how much memory was it using in v1.11.2?**
it was using default value 512Mi

**how high do you have to set the limit so its no longer OOMKilled?**
OOMkilled is occurring often ( every 3 minutes)

**is the memory usage steady over time? Does it spike initially and then settle down? does it slowly climb up unbounded?**
it spike initially but by that time after 3 minutes pod got crashbackloop and again restart. Its totally unpredictable


**What providers do you have installed? are they using a lot of memory, or are you only talking about the core Crossplane pod?**
I am talking about the core crossplane pod. we have two kubernetes providers and one is active and other one is inactive

**Comment by turkenh** [comment]
Thanks for the details @Dineshvcetster!

I just installed XP 1.12.2 and the provider k8s with 2 replicas to see if I can reproduce but the max memory I observe is around 35Mb. So, we need more details.

> We have 1600 components

Are you using compositions? What does `component` refer to here? Claims/Composites or provider k8s `Object`s ?

> I am talking about the core crossplane pod.

Just to double check - crossplane-rbac-manager is running fine but crossplane core is crashing, right?

Could you run the core XP pod with `--debug` flag and share the complete debug logs with us? 
Also the output of `kubectl -n crossplane-system describe pod <crossplane-pod-name>` please.

**Comment by Dineshvcetster** [comment]
Thanks @turkenh,

**Are you using compositions? What does component refer to here? Claims/Composites or provider k8s Objects ?**
i refer to objects. 

**Just to double check - crossplane-rbac-manager is running fine but crossplane core is crashing, right?**
yes, crossplane-rbac-manager is running fine but core is crashing

I will share the debug logs and output shortly

**Comment by Dineshvcetster** [comment]
![image](https://github.com/crossplane/crossplane/assets/129482901/0a1b5c15-30b9-4bbf-b8ab-2d0722cbb706)

It consumes almost 1.2 GB

**Comment by turkenh** [comment]
> I will share the debug logs and output shortly

@Dineshvcetster ping for logs. 

It is hard to understand what could be going on without further details.

**Comment by Dineshvcetster** [comment]
@turkenh, Sorry for the delay. 

Please find pod content

Name:                 crossplane-7b58647c57-8sstm
Namespace:            crossplane-system
Priority:             0
Priority Class Name:  standard
Service Account:      crossplane
Node:                 NODE_NAME
Start Time:           Tue, 01 Aug 2023 07:49:49 +0530
Labels:               app=crossplane
                      app.kubernetes.io/component=cloud-infrastructure-controller
                      app.kubernetes.io/instance=crossplane
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=crossplane
                      app.kubernetes.io/part-of=crossplane
                      app.kubernetes.io/version=1.12.2
                      helm.sh/chart=crossplane-1.12.2
                      pod-template-hash=7b58647c57
                      release=crossplane
Annotations:          cni.projectcalico.org/containerID: fc6c0f8893dd34bfff0c849705336042062811d7518e710cdcc4ee42502c3185
                      cni.projectcalico.org/podIP: 100.88.67.23/32
                      cni.projectcalico.org/podIPs: 100.88.67.23/32
                      data-ingest.dynatrace.com/injected: true
                      dynakube.dynatrace.com/injected: true
                      oneagent.dynatrace.com/injected: true
                      prometheus.io/path: /metrics
                      prometheus.io/port: 8080
                      prometheus.io/scrape: true
Status:               Running
IP:                   100.88.67.23
IPs:
  IP:           100.88.67.23
Controlled By:  ReplicaSet/crossplane-7b58647c57
Init Containers:
  crossplane-init:
    Container ID:  containerd://e9563818cc4cd5afe31fafa8d493e1c7c668fc51dfbd08bef88668e4e9b1761c
    Image:         <GCP AR>/crossplane:v1.12.2
    Image ID:      <GCP AR>/crossplane@sha256:50641735fad95c8a9eb27008b44f6cad14861efcb615d70ba10b8100b2b45bf7
    Port:          <none>
    Host Port:     <none>
    Args:
      core
      init
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 01 Aug 2023 07:50:20 +0530
      Finished:     Tue, 01 Aug 2023 07:50:23 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1500Mi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GOMAXPROCS:                 1 (limits.cpu)
      GOMEMLIMIT:                 1572864000 (limits.memory)
      POD_NAMESPACE:              crossplane-system (v1:metadata.namespace)
      POD_SERVICE_ACCOUNT:         (v1:spec.serviceAccountName)
      WEBHOOK_TLS_SECRET_NAME:    webhook-tls-secret
      WEBHOOK_SERVICE_NAME:       crossplane-webhooks
      WEBHOOK_SERVICE_NAMESPACE:  crossplane-system (v1:metadata.namespace)
      WEBHOOK_SERVICE_PORT:       9443
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4xm4r (ro)
  install-oneagent:
    Container ID:  containerd://9f3d2bff1c29db5fd013f49d1a0566b73a7893d4c5d4450cd3140f1ff44d73db
    Image:         <GCP AR>/dynatrace-operator:v0.12.0
    Image ID:      <GCP AR>/dynatrace-operator@sha256:f0575873593c7b0ed9deadec2cb302cfe386e09879f3ac943a37160bebf02eb8
    Port:          <none>
    Host Port:     <none>
    Args:
      init
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 01 Aug 2023 07:50:26 +0530
      Finished:     Tue, 01 Aug 2023 07:50:26 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     300m
      memory:  1536Mi
    Requests:
      cpu:     100m
      memory:  512Mi
    Environment:
      FAILURE_POLICY:        silent
      K8S_PODNAME:           crossplane-7b58647c57-8sstm (v1:metadata.name)
      K8S_PODUID:             (v1:metadata.uid)
      K8S_BASEPODNAME:       crossplane-7b58647c57
      K8S_CLUSTER_ID:        ead0f728-e113-4449-8437-298241ab1294
      K8S_NAMESPACE:         crossplane-system (v1:metadata.namespace)
      K8S_NODE_NAME:          (v1:spec.nodeName)
      FLAVOR:
      TECHNOLOGIES:          all
      INSTALLPATH:           /opt/dynatrace/oneagent-paas
      INSTALLER_URL:
      VERSION:               1.269.180.20230727-154113
      MODE:                  provisioned
      CSI_VOLUME_READONLY:   false
      ONEAGENT_INJECTED:     true
      CONTAINERS_COUNT:      1
      CONTAINER_1_NAME:      crossplane
      CONTAINER_1_IMAGE:     <GCP AR>/crossplane:v1.12.2
      DT_WORKLOAD_KIND:      Deployment
      DT_WORKLOAD_NAME:      crossplane
      DATA_INGEST_INJECTED:  true
    Mounts:
      /mnt/bin from oneagent-bin (rw)
      /mnt/config from injection-config (rw)
      /mnt/share from oneagent-share (rw)
      /var/lib/dynatrace/enrichment from data-ingest-enrichment (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4xm4r (ro)
Containers:
  crossplane:
    Container ID:  containerd://966fc6dd932655fb00ed214f4c7ce4f617e345a5912885413c43bf548e0c8dfa
    Image:         <GCP AR>/crossplane:v1.12.2
    Image ID:      <GCP AR>/crossplane@sha256:50641735fad95c8a9eb27008b44f6cad14861efcb615d70ba10b8100b2b45bf7
    Ports:         8080/TCP, 9443/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      core
      start
    State:          Running
      Started:      Tue, 01 Aug 2023 07:50:28 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1500Mi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GOMAXPROCS:               1 (limits.cpu)
      GOMEMLIMIT:               1572864000 (limits.memory)
      POD_NAMESPACE:            crossplane-system (v1:metadata.namespace)
      LEADER_ELECTION:          true
      WEBHOOK_TLS_SECRET_NAME:  webhook-tls-secret
      WEBHOOK_TLS_CERT_DIR:     /webhook/tls
      DT_DEPLOYMENT_METADATA:   orchestration_tech=Operator-cloud_native_fullstack;script_version=v0.12.0;orchestrator_id=ead0f728-e113-4449-8437-298241ab1294
      LD_PRELOAD:               /opt/dynatrace/oneagent-paas/agent/lib64/liboneagentproc.so
      DT_NETWORK_ZONE:          irn-70740-int-ext2-44
      DT_RELEASE_VERSION:        (v1:metadata.labels['app.kubernetes.io/version'])
      DT_RELEASE_PRODUCT:        (v1:metadata.labels['app.kubernetes.io/part-of'])
    Mounts:
      /cache from package-cache (rw)
      /etc/ld.so.preload from oneagent-share (rw,path="ld.so.preload")
      /opt/dynatrace/oneagent-paas from oneagent-bin (rw)
      /var/lib/dynatrace/enrichment from data-ingest-enrichment (rw)
      /var/lib/dynatrace/enrichment/endpoint from data-ingest-endpoint (rw)
      /var/lib/dynatrace/oneagent/agent/config/container.conf from oneagent-share (rw,path="container_crossplane.conf")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4xm4r (ro)
      /webhook/tls from webhook-tls-secret (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  package-cache:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  crossplane
    ReadOnly:   false
  webhook-tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  webhook-tls-secret
    Optional:    false
  kube-api-access-4xm4r:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  injection-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dynatrace-dynakube-config
    Optional:    false
  oneagent-bin:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.oneagent.dynatrace.com
    FSType:
    ReadOnly:          false
    VolumeAttributes:      dynakube=dynakube-irn-70740-int-ext2-44
                           mode=app
  oneagent-share:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  data-ingest-endpoint:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dynatrace-data-ingest-endpoint
    Optional:    false
  data-ingest-enrichment:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

**Comment by Dineshvcetster** [comment]
[crossplane_logs.txt](https://github.com/crossplane/crossplane/files/12408447/crossplane_logs.txt)

Attaching logs of crossplane

**Comment by Dineshvcetster** [comment]
I0913 13:10:38.006358       1 leaderelection.go:245] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...I0913 
13:11:39.540460       1 leaderelection.go:255] successfully acquired lease crossplane-system/crossplane-leader-election-coreWarning: ControllerConfig.pkg.crossplane.io/v1alpha1 has been deprecated and will be removed in a future release, but only after a comparable alternative is available.

2023/09/13 13:11:44 http: TLS handshake error from 172.20.187.27:41994: EOF
2023/09/13 13:11:45 http: TLS handshake error from 172.20.187.27:42032: EOF
2023/09/13 13:11:45 http: TLS handshake error from 172.20.187.27:42072: EOF
2023/09/13 13:11:45 http: TLS handshake error from 172.20.187.27:42178: EOF
2023/09/13 13:11:45 http: TLS handshake error from 172.20.187.27:42192: EOF
2023/09/13 13:11:46 http: TLS handshake error from 172.20.187.27:42206: EOF
2023/09/13 13:11:46 http: TLS handshake error from 172.20.187.27:42240: EOF
2023/09/13 13:11:47 http: TLS handshake error from 172.20.187.27:42232: EOF
