### ISSUE TITLE
Validate external names

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#4384]
### What problem are you facing?

When creating a Composition for an AWS lambda function, if you try to set the external name to something that is not an ARN-compatible format (like `arn:aws:lambda:us-east-1:1234567890:layer:borrelli-test`) the Official Provider will return an error like `observe failed: cannot run refresh: refresh failed: parsing lambda layer ID: arn: invalid prefix:`. 

### How could Crossplane help solve your problem?

As the validation suite matures, Crossplane should look into validating external-names if possible.

**Comment by turkenh** [comment]
I cannot think of an easy way to handle this generically without interacting with the specific cloud provider. 
However, this could be doable with some custom validation logic per resource. I am wondering if this issue better fits to upjet rather than XP 🤔

**Comment by phisco** [comment]
Indeed, it looks more like a job for providers' webhooks
