### ISSUE TITLE
Add new readiness check to match boolean fields

### ISSUE THREAD

**Issue by LCaparelli** [crossplane/crossplane#4398]
### What problem are you facing?

I'm using the Kubernetes Provider to compose regular Kubernetes resources as Crossplane Managed Resources.

As soon as the manifest is applied, the provider marks it as ready. This does not reflect at all the actual status of the resource being managed, it only means "we've successfully applied this manifest".

This leads to troubleshooting being kind of a pain, as the resource is marked as healthy, even though it might not be.

The resources I'm discussing contain a boolean `.status.ready`. I tried matching it with the available [readiness check](https://docs.crossplane.io/latest/concepts/compositions/#resource-readiness-checks), but there is no check for bools.

Trying `MatchString` runs into:
```
  Warning  ComposeResources         5s (x3 over 10s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot check whether composed resource is ready: cannot run readiness check at index 0: status.atProvider.manifest.status.ready: not a string
```

### How could Crossplane help solve your problem?

Adding a new readiness check `MatchBool` or even two new checks `IsTrue` and `IsFalse`.

**Comment by LCaparelli** [comment]
I'm willing to work on this and contribute. Please let me know if you have strong opinions about whether to use `MatchBool` or two separate `IsTrue`, `IsFalse`. 

I'm leaning towards `IsTrue/False`: simpler interface for the user, difficult to mis-use. Also, we will only ever have two possibilities for `MatchBool` (true or false), so it doesn't seem to warrant a more generic approach for this.

I'm thinking something along the line of:
```yaml
  readinessChecks:
  - type: IsTrue
    fieldPath: status.atProvider.manifest.status.ready
  - type: IsFalse
    fieldPath: status.atProvider.manifest.status.modifying
```

**Comment by turkenh** [comment]
Thanks for the report @LCaparelli!

There are a couple of related issues here including what you need:
- https://github.com/crossplane/crossplane/issues/4091
- https://github.com/crossplane-contrib/provider-kubernetes/issues/45
- https://github.com/crossplane-contrib/provider-kubernetes/issues/68

All closed as fixed and this PR in provider-kubernetes would enable you to achieve what you're looking for:
https://github.com/crossplane-contrib/provider-kubernetes/pull/119

Please see the example in the PR description and let us know if that helps.

**Comment by phisco** [comment]
I think the issue here is that it's not a condition @LCaparelli is trying to get the status from at `status.atProvider.manifest.status.ready`, but a boolean, so it's right that the current matchers aren't enough unfortunately.

**Comment by phisco** [comment]
`MatchBool` would make more sense to me, rather than `IsTrue`/`IsFalse` but I'm wondering whether we could find a more general solution.

**Comment by turkenh** [comment]
Thanks @phisco; missed that. 

Just left the same comment to the PR independently, so agree with MatchBool :)

**Comment by LCaparelli** [comment]
As discussed on https://github.com/crossplane/crossplane/pull/4399#discussion_r1277225375, we'll move forward with `MatchTrue` and `MatchFalse`.
