### ISSUE TITLE
Composition: Calculation of hashes in strings

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#4412]
### What happened?

I'd like to understand what the proper behavior of Crossplane Transform hashing behavior on string inputs. It looks like for basic strings quotes are added and then those quotes are included in the hashing (i.e., if you have an input of `string`, then the hash will be calculated against `"string"` with the additional quotes.

For example, the byte Array `Crossplane` generates a sha256 hash of `19c8a7c24ed0067f606815b59e5b82d92935ff69deed04171457a55018e31224 `
On the other hand the byte Array `"Crossplane"` (note quotes) generates a sha256 hash of `e84ae541a0725d73154ee76b7ac3fec4b007dd01ed701d506cd7e7a45bb48935 `

As can be seen in the test at https://github.com/crossplane/crossplane/blob/f591e4e41ac66d3e5645576c8796fde4f2011670/internal/controller/apiextensions/composite/composition_transforms_test.go#L818, our tests are against strings that have the added quotation marks. 

I believe the quotes are coming from our marshaling into JSON at https://github.com/crossplane/crossplane/blob/f591e4e41ac66d3e5645576c8796fde4f2011670/internal/controller/apiextensions/composite/composition_transforms.go#L347. Running an internal test, for the input string `Crossplane` the generated bytes array `inputJSON` includes the ASCII 34 quote character:

`[34 67 114 111 115 115 112 108 97 110 101 34]`

The Crossplane [docs](https://docs.crossplane.io/latest/concepts/patch-and-transform/#string-transforms) don't seem to indicate that the transforms are performed on the JSON representation of the input data. 

This may cause an issue as upstream systems may calculate a different hash without the quotes. 

### How can we reproduce it?

Use an online calculator or python to calculate the hash of strings. 

### What environment did it happen in?

Crossplane version: 1.13

**Comment by jbw976** [comment]
This doesn't seem like correct behavior to me, I would expect that we'd calculate the hash of the content itself and not on any enclosing quotes that were not part of the original content.

@stevendborrelli were you interested in driving a fix for this? 🤔

**Comment by stevendborrelli** [comment]
@jbw976 I can look at it later this week.
