### ISSUE TITLE
Add docs updated check to the PR template

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4415]
### What problem are you facing?

We currently have the following checks in the PR template:
```
- [ ] Read and followed Crossplane's [contribution process].
- [ ] Added or updated unit **and** E2E tests for my change.
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.
```

But I think we should also add a check to ensure people also updated the docs accordingly if needed (e.g. introducing a new feature).

### How could Crossplane help solve your problem?

Add a checkbox to remember people to update/write docs, something like:
```
- [ ] Opened a PR updating the [docs](https://github.com/crossplane/docs), if necessary.
```
I saw people having some difficulties opening PRs to the docs repository, so it would be useful to point to a doc there explaining the folder structure and how to handle `master` and how to "backport" them to older/already released versions.

**Comment by plumbis** [comment]
This page of the docs contributing guide is probably the best place to send folks who are trying to get started

https://docs.crossplane.io/contribute/contribute/
