### ISSUE TITLE
Move `xfn` out of tree - e.g. to `crossplane/function-runtime-oci` - and remove it from the Helm chart.

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4432]

**Comment by phisco** [comment]
Moved to https://github.com/crossplane/function-runtime-oci, I'll create a dedicated ticket to switch it to `v1beta1`

**Comment by korenyoni** [comment]
Is there a Helm Chart for `xfn` now?

As of the time of writing this comment I cannot find it.
