### ISSUE TITLE
Please add support for the `hashicorp/random` provider

### ISSUE THREAD

**Issue by tspearconquest** [crossplane/crossplane#4436]
### What problem are you facing?

We want to be able to generate cryptgraphically secure passwords that are able to be used by other crossplane providers. Hashicorp offers the `hashicorp/random` provider for this purpose in Terraform. We'd like to see this provider brought into Crossplane natively. In Terraform, we create a randomly generated password and store it in its own dedicated state file, then use the state file as a data source for other providers:

1. As input for the admin password of an `azurerm_postgres_flexible_server` resource
2. As input for the password of a `postgresql_role` resource which lives in a database created in the above resource
3. As input for `azurerm_key_vault_secret` to store the password of the above resource in keyvault for applications to be able to connect to their respective database.

Doing this in this way allows for mistakes to not cause downtime. In lesser setups (where the resource output of `random_password` is used directly in another resource), if someone triggers rotation of a password for some reason, the password changes in the DB but not in Keyvault, or changes both the DB and Keyvault but then the app doesn't pick up the change and use the new secret because the app is managed in a different lifecycle from the infrastructure, and you wind up with downtime.

In our setup, because the secret is first created and stored in its own dedicated state, if someone makes a mistake and updates the secret, there are multiple opportunities to catch the error before other resources are updated. Each step in the process requires a separate plan to be generated, and as soon as the secret was updated, the other resources would show the change in their own `terraform plan` outputs.

### How could Crossplane help solve your problem?

Add support for the `hashicorp/random` provider.

Our only option right now is to use the crossplane terraform provider to pull in our own internally created terraform module which uses the `hashicorp/random` provider, however that means we still have to manage the version of the `hashicorp/random` provider ourselves manually, outside of the crossplane and crossplane-terraform provider processes; and it feels like unnecessary toil on the part of our developers because it falls largely outside of GitOps principles.

The extra safety detailed above will likely be unnecessary if this is made available, because we plan to leverage FluxCD and Crossplane together to ensure that when secrets are updated by Crossplane, the app is restarted at the earliest possible time after a secret has changed.

**Comment by bobh66** [comment]
Also see #1895 
Slack thread - https://crossplane.slack.com/archives/CEG3T90A1/p1691006333083929

**Comment by bobh66** [comment]
As mentioned in #1895 this is not likely to be added to Crossplane, but is a good candidate for a Composition Function as of 1.14
