### ISSUE TITLE
Can error messages that reference an index number within a composition be more helpful?

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4454]
> [!IMPORTANT]
> Some of the implementation here is within the Patch & Transform machinery. If we fix it there, we should also fix in the new P&T Function: https://github.com/crossplane-contrib/function-patch-and-transform

### What happened?

It's not uncommon to see error messages from the composition machinery that reference a specific index number.  This is helpful, but is there more information or a different experience that could help the user track down the source of the error more quickly?

Example error message from #3262:
```
cannot render composed resource from resource template at index 2: cannot apply the patch at index 6: transform at index 0 returned error: map transform could not resolve: key asdf is not found in map"
```

That error message has 3 different index numbers for the user to take back to their composition and use to hunt down the exact location in the composition that is causing the problem.

Can this be improved in some way? For example:

* by referencing `name` fields in addition to `index`?
* by referencing the full field path in the composition to the error source?
* something else more creative?

### How can we reproduce it?

I don't have specific repro steps at the moment, but here are some search results across the code base that may exhibit this behavior:

```
❯ find . -name '*.go' | xargs grep -F -i 'at index %d'
./internal/controller/apiextensions/composite/reconciler.go:	errFmtPatchEnvironment = "cannot apply environment patch at index %d"
./internal/controller/apiextensions/composite/composition_transforms.go:	errFmtTransformAtIndex              = "transform at index %d returned error"
./internal/controller/apiextensions/composite/composition_transforms.go:	errFmtMatchPattern            = "cannot match pattern at index %d"
./internal/controller/apiextensions/composite/composition_transforms.go:	errFmtMatchParseResult        = "cannot parse result of pattern at index %d"
./internal/controller/apiextensions/composite/environment/selector.go:	errFmtReferenceEnvironmentConfig   = "failed to build reference at index %d"
./internal/controller/apiextensions/composite/environment/selector.go:	errFmtResolveLabelValue            = "failed to resolve value for label at index %d"
./internal/controller/apiextensions/composite/ready.go:	errFmtRunCheck                = "cannot run readiness check at index %d"
./internal/controller/apiextensions/composite/composition_pt.go:	errFmtPatch        = "cannot apply the patch at index %d"
./pkg/validation/apiextensions/v1/composition/patches.go:		return nil, errors.Errorf("no schema for item requested at index %d", segment.Index)
```

**Comment by santhoshivan23** [comment]
@jbw976 yep, i do agree that the error messages can be more informative. i’d like to take this issue and work on.
