### ISSUE TITLE
Implement a Markdown linter/formatter

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/crossplane#4467]
### What problem are you facing?

Often contributions from the community does not comply with the current standard of wrapping Markdown file content at 80 chars. This requires reviewers/maintainers to have to ask the author to update their PRs. 

### How could Crossplane help solve your problem?

We should implement a linter, and if possible an auto formatter, for Markdown content so that reviewers don't have to worry about checking for this and authors get an early signal on this.

We should make sure it runs as part of `make reviewable`

**Comment by phisco** [comment]
/fresh

I saw that Prettier can be used for this kind of markdown linting.
