### ISSUE TITLE
Silent error when server API is missing

### ISSUE THREAD

**Issue by niklashhh** [crossplane/crossplane#4498]
### What happened?

I followed the [AWS quickstart tutorial part 2](https://docs.crossplane.io/v1.13/getting-started/provider-aws-part-2/) and skipped installing the DynamoDB provider. After creating the NoSQL composite resource, its status was synced but not ready. What did not happen, was that any form of error or warning showed up in events, or the crossplane pod logs (crossplane container). I had to enable `--debug` for the container to see the following lines:

```
2023-08-14T13:13:23Z    DEBUG   crossplane      Reconciling     {"controller": "defined/compositeresourcedefinition.apiextensions.crossplane.io", "controller": "composite/nosqls.database.example.com", "request": {"name":"my-nosql-database"}}
2023-08-14T13:13:24Z    DEBUG   crossplane      composed resource "dynamoDB": cannot use dry-run create to name composed resource: failed to get API group resources: unable to retrieve the complete list of server APIs: dynamodb.aws.upbound.io/v1beta1: the server could not find the requested resource      {"controller": "defined/compositeresourcedefinition.apiextensions.crossplane.io", "controller": "composite/nosqls.database.example.com", "request": {"name":"my-nosql-database"}, "uid": "8ad5227d-f0ad-4b77-a8bc-25fb51c3a279", "version": "65456", "name": "my-nosql-database"}
```

This seems like an error/warning but is logged at level debug.

### How can we reproduce it?

I believe this happens with any Composition which references an unavailable API. Here were my steps.
1. Follow [AWS quickstart part 2](https://docs.crossplane.io/v1.13/getting-started/provider-aws-part-2/) until `Install the DynamoDB Provider` without installing the DynamoDB provider
2. Create the NoSQL object using the following file:
    ```yaml
    apiVersion: database.example.com/v1alpha1
    kind: NoSQL
    metadata:
      name: my-nosql-database
    spec:
      location: EU
    ```

### What environment did it happen in?
Crossplane version: `1.13.2`

Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+k3s1", GitCommit:"8d0255af07e95b841952563253d27b0d10bd72f0", GitTreeState:"clean", BuildDate:"1970-01-01T01:01:01Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
Distribution: `k3s version v1.26.4+k3s1 (8d0255af)`

**Comment by jbw976** [comment]
Thanks for sharing this @niklashhh - when you mention that you didn't see any events for this, did you happen to also look at the XR in addition to the claim here? I know the troubleshooting story can be a bit difficult, but I did want to clarify if no events showed up at any level deeper than the claim 🤔 

Docs section on troubleshooting composition that you could follow for this scenario: https://docs.crossplane.io/knowledge-base/guides/troubleshoot/#compositions-and-composite-resource-definition

**Comment by niklashhh** [comment]
Hi @jbw976 , looking more carefully at the events I do indeed see a warning-level event which clearly says `dynamodb.aws.upbound.io/v1beta1: the server could not find the requested resource`. I am uncertain how I missed this previously.

Closing as I can't reproduce the issue.

**Comment by jbw976** [comment]
Thank you @niklashhh for your follow up here and further investigation - looking forward to improving this experience overall soon :)
