### ISSUE TITLE
Opt-in to install CRDs with Helm value

### ISSUE THREAD

**Issue by erikgb** [crossplane/crossplane#4551]
### What problem are you facing?

The poor handling of CRDs in Helm is well-known, but new tools and processes are able to work around the eschewed CRD support in Helm. FluxCD is one example, and I assume ArgoCD also has some support.

Crossplane seems to use the runtime/controller to install (even the core) Crossplane CRD. This means that even if you follow the detailed uninstall process described in [the docs](https://docs.crossplane.io/latest/software/uninstall/), the CRDs will remain orphaned in your cluster after the uninstall. This is unfortunate, and no way to avoid AFAIK. This was also causing issues for us when trying to reinstall Crossplane in a cluster we have because the version we came from was a very old version.

Also, the [Helm chart README](https://github.com/crossplane/crossplane/tree/master/cluster/charts/crossplane#readme) might give you the impression that CRDs are installed as part of the chart:

![image](https://github.com/crossplane/crossplane/assets/1142578/fa8a032e-f185-4331-8a24-1dbef760311c)

I posted a [question on Slack](https://crossplane.slack.com/archives/CEF5N8X08/p1692994523317239), and got some feedback from Crossplane maintainers.

### How could Crossplane help solve your problem?

I would suggest introducing a new opt-in value in the Helm chart to install CRDs. To overcome the issues with CRD handling in Helm, I propose to do it in a similar way as cert-manager does: https://cert-manager.io/docs/installation/helm/#helm-installation. The main idea is to provide the CRDs to Helm as standard templated resources, and not as a "Helm CRD".

I think the potential issue here is to verify that the Crossplane runtime fully supports patching a CRD created (and managed) by some GitOps tool. To not break the Helm chart for existing users, the Crossplane runtime should still ensure the CRDs are present and have the desired state.

**Comment by aerfio** [comment]
I would also help in the case of installing Providers which the user wants to configure, like installing provider-helm with rbac to act on the host k8s cluster, see https://crossplane.slack.com/archives/CEG3T90A1/p1709027611346949 for my use case

**Comment by cwrau** [comment]
This would be extremely helpful, as this would allow users to create charts which deploy crossplane providers with a dependency on this chart.

As it currently stands, the user has to install crossplane, wait *insert random amount of time here* and then install the next component instead of being able to just install everything at once

**Comment by yuval-benjamin** [comment]
/fresh
Will help as well when we use terraform to apply helm and encounter crd issues with helm.

**Comment by Charly6596** [comment]
/fresh
I was expecting CRDs to be included as part of the helm chart, as mentioned above it's a pretty common practice in helm charts
