### ISSUE TITLE
Support `EnvironmentConfig` when using Composition Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4600]
### What problem are you facing?

Today it's not possible to use EnvironmentConfigs and Composition Functions together. The environment is not passed to the Function pipeline. This is largely because the two features are both alpha, and figuring out the intersection of two in-flux designs is tough. 😄 With Functions going to beta, we will need to figure out supporting EnvironmentConfigs. In particular I think convincing folks to move to the P&T Function (https://github.com/crossplane/crossplane/issues/4571) will be a hard sell if we don't support them.

### How could Crossplane help solve your problem?

I think it needs to be possible to:

* Pass "the environment" to the Function pipeline.
* Allow Functions to mutate the environment (i.e. to affect subsequent Functions in the pipeline).
* Avoid using EnvironmentConfigs feeling similar to P&T (so you can avoid P&T style completely when using Functions, if you want to).

This relates to https://github.com/crossplane/crossplane/issues/4583, which is tracking the future shape of the environment API.

**Comment by phisco** [comment]
I think you wanted to point to #4558 instead of #4591.

**Comment by negz** [comment]
@phisco Whoops, I actually wanted https://github.com/crossplane/crossplane/issues/4571 haha.
