### ISSUE TITLE
Create a specification for Providers

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/crossplane#4641]
### What problem are you facing?
Crossplane has a specification for [xpkg](https://github.com/crossplane/crossplane/blob/master/contributing/specifications/xpkg.md) and soon Functions: https://github.com/crossplane/crossplane/pull/4640

Currently, there is no specification for Providers.

### How could Crossplane help solve your problem?

Define a specification that Crossplane expects all providers to conform to. This will ensure providers are built similarly in order for us to build tooling around them.

**Comment by negz** [comment]
Some prior art here:

* https://github.com/crossplane/crossplane/blob/b546d9/design/one-pager-managed-resource-api-design.md - This design doc touches on design patterns for MR APIs. It might be a little out-of-date.
* https://github.com/crossplane/conformance - The conformance suite is very stale, but it does perform some basic schema and behavior tests to make sure a provider appears to deliver conformant MRs (and ProviderConfigs etc).

**Comment by csantanapr** [comment]
I'm interesting on implementing a Crossplane provider to provide MR CRDs that uses other languages than golang.

**Comment by negz** [comment]
/fresh

@jeanduplessis @alper if you still think this is worth doing, I'd be happy to support you.

**Comment by jeanduplessis** [comment]
@negz @ulucinar I do think its still worth pursuing this. I'll factor it into the team's plans for the near term.
