### ISSUE TITLE
Vote: Donation of Upjet framework and providers to the Crossplane project

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4644]
In the spirit of the proposed charter expansion in #4643, Upbound would like to donate its Upjet provider framework as well as the AWS, Azure, and GCP providers to the Crossplane organization.

This donation will accelerate the growth of the Crossplane provider ecosystem and provide a neutral home for the investment and collaboration on providers for Crossplane. While these projects are already Apache 2 licensed, the move to the Crossplane project and its well defined governance ensures that they will remain open, permissive, and won’t be re-licensed in the future, thereby enabling a highly sustainable provider ecosystem for the Crossplane community.

The steering committee can indicate their acceptance of this donation by commenting on this issue. Voting is open for the steering committee only as the scope of this proposal affects the organization, not just a single repository.

**Comment by jbw976** [comment]
+1 Binding ✅

**Comment by bassam** [comment]
+1 binding ✅

**Comment by jbw976** [comment]
This issue serves as a record of the steering committee vote to accept the donation of the Upjet framework and providers to the Crossplane project.

Results:
3/3 binding votes in favor to accept
