### ISSUE TITLE
Allow XR `.spec` updates only through claim's updates

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4652]
### What problem are you facing?

XR `.spec` should be kept in sync with its claim counterpart, i.e. it should not drift away. Currently, it is possible to update XR spec in the following ways:

* by crafting a proper `ToCompositeFieldPath` patch in a composition
* by updating a composite using `kubectl` or any other client

The claim controller is equipped with the logic that should revert these changes, but it does not work due to used patching strategy.

### How could Crossplane help solve your problem?

Apart from fixing the claim controller within https://github.com/crossplane/crossplane/issues/4047 we should also refuse XR `.spec` updates early, i.e. deny them and give the appropriate feedback to users:

* `ToCompositeFieldPath` patches should not allow patching to `.spec` and should emit the right error in the composite status
*  Update requests sent to k8s API server should be refused, if XR `.spec` is about to be modified

**Comment by negz** [comment]
This seems pretty closely related to https://github.com/crossplane/crossplane/issues/4581.

I agree in principle. A few thoughts though:

* We should let folks update the XR directly if no claim exists.
* Compositions in `mode: Pipeline` don't allow XR spec or metadata updates (only status).
* They don't reject them though - they're silently dropped.
* I think this would be a pretty significant backward-incompatible behaviour change for P&T Compositions. I have to imagine it would break a lot of existing Compositions.
