### ISSUE TITLE
Validation of crossplane resources within an IDE (e.g. VS Code)

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4674]
A major improvement to the developer experience of Crossplane, in the theme of "shift left", would be for platform builders to get immediate actionable validation on their Crossplane resources as they are building them - i.e. within their IDE. The earlier we can validate/lint their resources, the quicker we make the developer iteration loop, and the faster they get to a successful platform - minimizing pain along the way.

Pre-req issues:
- [ ] #4673
  -  gives us a unified validation implementation to perform a rich set of validation and linting
- [x] #4675
  - gives us a language server implementation within upstream Crossplane

These features would serve as the foundation that makes an IDE authoring time experience possible that validates `Composition` and `CompositeResourceDefinition` for errors.

Below are some notes on gaps we should fill from the current `xpls` language server validation experience:

* validate the full types from core crossplane (Composition, CompositeResourceDefinition)
  * we don’t have the schemas/files for core crossplane types in xpls, so we don’t validate anything for them - we mostly validate composed resources content
* missing scenarios to validate and return errors on
  * patches with incorrect field paths
  * composed resource fields that don’t exist, e.g. connectionDetails being incorrectly under base.spec
  * other missing scenarios? pretty much anything wrong in a XRD/Composition should be caught

Relevant prior art:
* https://github.com/redhat-developer/yaml-language-server
* https://github.com/Intility/vscode-backstage

**Comment by jbw976** [comment]
Building an entire language server is looking less important now for the following reasons:

* we assume a useful language server is going to be very labor intensive, and has maintenance difficulty for keeping it up with the updates to function schemas and functionality
* `render` is now covering a lot of the original intent of this issue, e.g., the dev iteration “author time” feedback cycle
* the value of a language server is weakened because it would only help patch & transform folks and not all the other types of functions without significantly more effort
* more CLI commands and functionality in v1.15 would be quicker wins with more value in the short term

Other thoughts:

* reusing validation/schema checking for existing tools in say golang/python could be another way to accomplish the spirit of the language server
  * e.g. in your golang function you can create a strongly typed `Bucket` struct - you can get all the built in go compiler/linting checks etc. in your IDE already from that

**Comment by joebowbeer** [comment]
It would be nice if vscode-yaml could use the XRD directly, as I requested here:

https://github.com/redhat-developer/vscode-yaml/issues/1137
