### ISSUE TITLE
Enable user to understand when external resource is reconciled

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4695]
### What problem are you facing?

Managed resource is Crossplane representation of an external resources. After a managed resource creation, an appropriate provider reacts and creates the counterpart external resource, based on the provided data. The progress of such operation and readiness of the created resource can be observed through following conditions on the managed resource:

* `Sync` becomes `True` after the create request was successfully made, othewise is set to `False` indicating an error
* `Ready` is set to `False` right after the create request was successful, and flipped to `True` after the resource is observed as ready

In case of successful followup updates of the given managed resources, user is not able to understand when the external resource gets updated, because `Sync` and `Ready` remain `True`, not changing their last transition times. Quite often, update is not instantaneous and therefore users might want to pause/stop using the given resource while being reconfigured.

### How could Crossplane help solve your problem?

Managed resource schema should be extended with `status.convergedGeneration` field containing `metadata.generation` of the last managed resource version that got applied and became effective.

Users could understand that an update is still in progress  when `status.convergedGeneration`  does not match `metadata.generation`  and pause/stop usage of the given external resource, if needed.

Related: https://github.com/crossplane/crossplane/issues/4655

**Comment by negz** [comment]
Just to make sure I understand here, are you proposing that:

* `observedGeneration` be updated when we change the desired state of an external resource [^1]
* `convergedGeneration` be updated when we observe that the state of an external resource matches our desired state

Do all (or most) APIs give us a way to know whether our changes are still being applied? I know some APIs (e.g. in Azure) will return an operation we can poll. In other cases (e.g. in GCP) the next time we observe a resource it will have some output-only field like `RECONCILING` or `REPAIRING` that indicates it's currently applying the desired state.

[^1]: Technically I think this is more like whenever we reconcile the MR, but most reconciles of the MR should result in changing the desired state of the external resource.

**Comment by pedjak** [comment]
`observedGeneration` contains the resource `generation` value of resources seen by the reconcile loop. It indicates that the managed resource got reconciled, but it does not mean that the changes are effective on the cloud provider side. Depending on the resource and cloud provide, it might take some time.

We have that situation at creation time as well, but there we flip `Ready` from `False` to `True` to indicate the external resource is ready to use.

> Do all (or most) APIs give us a way to know whether our changes are still being applied? 

If an API does give us such insights, then we can update `convergeGeneration` everytime when we touch `observedGeneration`,  or indicate to users that that field is not supported (e.g. crossplane could inspect managed resource schema and detect if the field is defined).

**Comment by pedjak** [comment]
/fresh a first PR is ready for the review
