### ISSUE TITLE
Avoid no-op reconcilations

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4703]
### What problem are you facing?

Resources are reconciliated on any change, but very it does not generate any change in the system, thus it could be easily skipped. The affected controller could be less busy, using less system resources.

### How could Crossplane help solve your problem?

Fine tune when a given reconcile loop is triggered:
* Claim reconciliation should be triggered only when (1) claim's annotation, labels an/or spec is changed, or (2) when composite status is modified
* Composite reconciliation should be triggered when (1) labels, annotations or spec is changed, (2) composition changes and/or (3) managed resource is updated

**Comment by negz** [comment]
This could be done by stacking a couple of predicates from https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/predicate, right? I recall @turkenh did that somewhere before (probably the MR reconciler). I imagine we'd want an OR of `AnnotationChangedPredicate`, `LabelChangedPredicate`, and `GenerationChangedPredicate`.

**Comment by turkenh** [comment]
Yes, we have a `[DesiredStateChanged](https://github.com/crossplane/crossplane-runtime/blob/075b3d5fb8b96991ce2617a4919d4db4ddd5159f/pkg/resource/predicates.go#L51)` in the runtime for this purpose. 

This needs to be enabled for the controller Setup functions like [this](https://github.com/upbound/provider-aws/blob/1569774a025527c8dabcbce9ed9a92ae913412c6/internal/controller/accessanalyzer/analyzer/zz_controller.go#L63).

**Comment by negz** [comment]
Should we target this for v1.14? It seems relatively straightforward to implement. Probably needs a little testing, but maybe our existing E2Es are sufficient?

**Comment by sttts** [comment]
There is risk in this, and complexity. Do we see strong reasons that this is necessary (like a benchmark)? Gut feeling: might be premature optimization.

**Comment by oblogic7** [comment]
I believe I'm running into an issue where predicates may have some impact.  For my case, the `TeamRepository` resource from `coopnorge/provider-github` is being reconciled repeatedly with no delay of any kind.  Polling interval is not being respected and max-reconcile rate has limited impact.  This is exhausting Github API calls very quickly.

I've traced the issue down to [this line](https://github.com/crossplane/crossplane-runtime/blob/86fb15da2cac29685b0527eec681e7db72f534f7/pkg/reconciler/managed/reconciler.go#L985).  If I remove the call to update the status for the managed resource, then the next reconciliation happens after the defined polling interval as expected.

This indicates that the status update is triggering a reconciliation event and bypassing the polling interval.   I believe predicates can help here by limiting status updates from being reconciled over and over.

**Comment by phisco** [comment]
> I've traced the issue down to [this line](https://github.com/crossplane/crossplane-runtime/blob/86fb15da2cac29685b0527eec681e7db72f534f7/pkg/reconciler/managed/reconciler.go#L985). If I remove the call to update the status for the managed resource, then the next reconciliation happens after the defined polling interval as expected.
> 
> This indicates that the status update is triggering a reconciliation event and bypassing the polling interval. I believe predicates can help here by limiting status updates from being reconciled over and over.

@oblogic7, could be a conflict on the update which results in a silent re-queuing, could you check the `resourceVersion` of the `TeamRepository` being continuously reconciled?
