### ISSUE TITLE
Selected composition revision: %!s(MISSING)

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#4708]
### What happened?
got the following event in composite resource: `Selected composition revision: %!s(MISSING)`
is related to: https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L541

### What environment did it happen in?
Crossplane version:

**Comment by negz** [comment]
I keep seeing this too. Let's try fix it in v1.14.

**Comment by negz** [comment]
I think this was introduced with https://github.com/crossplane/crossplane/pull/4565.
