### ISSUE TITLE
Add alpha command/gate that we can put new/experimental CLI commands behind

### ISSUE THREAD

**Issue by lsviben** [crossplane/crossplane#4720]
As we are adding new CLI commands, we need a mechanism to put the new/experimental ones behind an alpha flag, so that we have flexibility in iterating on them.

We could use the [up](https://github.com/upbound/up/blob/main/cmd/up/main.go#L84-L92) maturity feature for that.

**Comment by negz** [comment]
I personally like the way the `gcloud` CLI does this, which I think we mirrored in `up` for while, where such functions are under a `beta`/`alpha` subcommand. For example:

```shell
$ crossplane alpha render xr.yaml...
```

**Comment by lsviben** [comment]
I see up still has this 'up alpha command' for some deprecated command. They are just hidden by default as they are alpha. We could do the same, put new commands under `alpha` subcomand and later move them when they are ready. 

One thing to not is that `up` hides the alpha commads. If we do the same, it would be good if we have a note in `help` to do some kind of `--helpall` to get info for alpha commands as well

**Comment by phisco** [comment]
Yes, I like `crossplane alpha|beta ...` too.
Do we really want to hide alpha commands? As long as the status of a command is clear, I think hiding them would just hurt discoverability.

**Comment by negz** [comment]
> Do we really want to hide alpha commands? As long as the status of a command is clear, I think hiding them would just hurt discoverability.

I forgot that we hid them in `up`. I wonder if that was the case from the start, or whether that was done as some kind of deprecation? I agree we don't need to hide our alpha commands.
