### ISSUE TITLE
Improve errors when building a config with invalid YAML kinds

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4770]
### What problem are you facing?
If I run `crossplane build configuration` on a directory that contains YAML files that have a `kind` that doesn't match, for example, a Claim, the error message isn't clear.

```
kubectl crossplane: error: main.buildCmd.Run(): failed to build package: failed to parse package: {path:/home/vagrant/test/comp.yml position:0}: no kind "ExampleClaim" is registered for version "example.org/v1alpha1" in scheme "pkg/runtime/scheme.go:100"
```

Based on [runtime #300](https://github.com/crossplane/crossplane-runtime/pull/300) it seems like this is an error from the Runtime, but it's encountered when using the Crossplane CLI, so I think it should be filed here.

### How could Crossplane help solve your problem?

The error message should be more user friendly and clearly report that the only supported Configuration YAML files are `kind: CompositeResourceDefinition` and `kind: Composition`.

**Comment by emily-zall** [comment]
This also happened when I had comments in the file above the document separator. I didn't initially realize it was this same issue.

`➜ kubectl-crossplane build configuration --package-root="/Users/emilyzall/repos/simba-azure-configuration/package/opal"
kubectl crossplane: error: main.buildCmd.Run(): failed to build package: failed to parse package: {path:/Users/emilyzall/repos/simba-azure-configuration/package/opal/definition.yaml position:4096}: Object 'Kind' is missing in '# Provision resources for OPAL https://opal.dev/ that will be needed for the OPAL helm chart`

e.g.
```
---
# Provision resources for OPAL https://opal.dev/ that will be needed for the OPAL helm chart
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
```

**Comment by jbw976** [comment]
Thanks for the feedback on this issue! I'll go ahead and add it to the tracking epic for v1.15 in the hopes that we can opportunistically improve this experience during the milestone ✅ 🙏
