### ISSUE TITLE
Improve CLI build error when no crossplane.yaml is present

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4772]
### What problem are you facing?
If you try and use the crossplane CLI to build a configuration package but do not include the `crossplane.yaml` file the error message could be more useful-

```
crossplane build configuration -f test
kubectl crossplane: error: main.buildCmd.Run(): failed to build package: failed to lint package: not exactly one package meta type
```

### How could Crossplane help solve your problem?

We should detect a missing `crossplane.yaml` file and explicitly state the problem before parsing and returning a parse error.

**Comment by plumbis** [comment]
Note, `crossplane build provider` is more explicit.

```
kubectl crossplane: error: main.buildCmd.Run(): failed to get name from crossplane.yaml: open /home/provider-test/crossplane.yaml: no such file or directory
```

**Comment by haarchri** [comment]
Do you tried the new xpkg commands ?

**Comment by plumbis** [comment]
Testing a newer build-

```
crossplane -v
v1.14.0-rc.0.524.g6b99ef11
```

If there is no YAML file, it's a little better but could be more explicit on what the problem is
```
root@4d7b143728a4:~# crossplane xpkg build
crossplane: error: failed to build package: package must contain exactly one meta object
```

But if you have some random YAML, for example, the `go` directory created by `make` you get not only a confusing error, but it's pointing at the wrong file (dependabot.yml is the second file)

```
root@4d7b143728a4:~# crossplane xpkg build
crossplane: error: failed to build package: failed to parse package: {path:/root/go/pkg/mod/dario.cat/mergo@v1.0.0/.github/dependabot.yml position:0}: Object 'Kind' is missing in '# These are supported funding model platforms

                   github: imdario
                   ko_fi: dariocc

                   ...

                   '
```

**Comment by elohmrow** [comment]
I just ran into this as well, but for me the error was caused by having > 1 `crossplane.yaml` file in the same dir. Agree that the error message could be more clear.
