### ISSUE TITLE
Deduplicate xpkg subcommands in the Crossplane CLI

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4783]
### What happened?

With things starting to fall into place in the new Crossplane CLI we've got a few redundant commands:

```
$ crossplane --help
Usage: crossplane <command>

A command line tool for interacting with Crossplane.

Commands:
  build              Build Crossplane packages.
    configuration    Build a Configuration package.
    provider         Build a Provider package.
    function         Build a Function package.

  install            Install Crossplane packages.
    configuration    Install a Configuration package.
      <package>      Image containing Configuration package.
      [<name>]       Name of Configuration.
    provider         Install a Provider package.
      <package>      Image containing Provider package.
      [<name>]       Name of Provider.

  update             Update Crossplane packages.
    configuration    Update a Configuration package.
      <name>         Name of Configuration.
      <tag>          Updated tag for Configuration package.
    provider         Update a Provider package.
      <name>         Name of Provider.
      <tag>          Updated tag for Provider package.

  push               Push Crossplane packages.
    configuration    Push a Configuration package.
      <tag>          Tag of the package to be pushed. Must be a valid OCI image tag.
    provider         Push a Provider package.
      <tag>          Tag of the package to be pushed. Must be a valid OCI image tag.

  xpkg               Crossplane package management.
    build            Build a package, by default from the current directory.
    push             Push Crossplane packages.
      <tag>          Tag of the package to be pushed. Must be a valid OCI image tag.

  alpha              Alpha features. WARN: May be changed or removed without notice

  beta               Beta features. WARN: May be changed or deprecated in a future release

Flags:
  -h, --help                    Show context-sensitive help.
  -v, --version=VERSION-FLAG    Print version and quit.
      --verbose                 Print verbose logging statements.

Run "crossplane <command> --help" for more information on a command.
```

Notably I think the `crossplane xpkg ...` commands are newer, better implementations of `crossplane build ...` and `crossplane push ...`.

### How can we reproduce it?

Build the CLI from 11c8aecace8a12a5f71dda368bb5eb7f16194a2d and run it. :)

### What environment did it happen in?
Crossplane version: 11c8aecace8a12a5f71dda368bb5eb7f16194a2d

**Comment by negz** [comment]
I would suggest we:

* Remove the `build`, `install`, `update`, and `push` subcommands.
* Add new `crossplane xpkg install` and `crossplane xpkg update` subcommands.

**Comment by phisco** [comment]
totally agree with this 👍 do we want to just remove or maybe deprecate the old commands?

**Comment by negz** [comment]
@phisco I'd go with removing, especially if we're not losing any functionality. I'm leaning toward not worrying about backward compatibility for CLI argument and flag names with these changes, since we're changing how the binary is invoked as well.

**Comment by jbw976** [comment]
My main concern for removing the old commands would be if anyone is using `kubectl crossplane` in an automated fashion, e.g. for CI or environment setup. 

One example I found from searching Github for `kubectl crossplane`:
https://github.com/s4rd1nh4/crossplane-configuration-dfds/blob/5d579777ca5e71585a2df62026f2ce0d2b46437c/build/azure-pipelines.yml#L49

If we remove (which I'm not fully against), we'll definitely need to document that well in the release notes.
