### ISSUE TITLE
Rename `crossplane xpkg build --controller ...` flags

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4784]
### What problem are you facing?

```
$ crossplane xpkg build --help
Usage: crossplane xpkg build

Build a package, by default from the current directory.

The build command creates a xpkg compatible OCI image for a Crossplane package from the local file system. It packages the found YAML files containing Kubernetes-like object manifests into the meta data
layer of the OCI image. The package manager will use this information to install the package into a Crossplane instance.

Only configuration, provider and function packages are supported at this time.

Example claims can be specified in the examples directory.

For more generic information, see the xpkg parent command help. Also see the Crossplane documentation for more information on building packages:

    https://docs.crossplane.io/latest/concepts/packages/#building-a-package

Even more details can be found in the xpkg reference document.

Flags:
  -h, --help                          Show context-sensitive help.
  -v, --version=VERSION-FLAG          Print version and quit.
      --verbose                       Print verbose logging statements.

  -o, --output=STRING                 Path for package output.
      --controller=STRING             Controller image used as base for package.
      --controller-tar=STRING         Path to tar file, an alternative to Controller.
  -f, --package-root="."              Path to package directory.
  -e, --examples-root="./examples"    Path to package examples directory.
      --ignore=IGNORE,...             Paths, specified relative to --package-root, to exclude from the package.
```

The above command talks about a "controller" image to bake into a package. This makes sense in the context of Providers, where a package can be part of an OCI image that also contains a Kubernetes controller binary. For Functions, this makes less sense. A package can be part of an OCI image that contains a Function binary, but that binary is not a (Kubernetes) controller.

### How could Crossplane help solve your problem?

We could find a more generic name for this flag. Perhaps `--runtime` per https://github.com/crossplane/crossplane/issues/4699. `--image` was also suggested in https://github.com/crossplane-contrib/function-patch-and-transform/pull/18. (Or maybe both - `--runtime-image`.)

**Comment by negz** [comment]
Bonus points if we can keep `--controller` variants as hidden aliases. Might not be much value in that though given the new CLI isn't really backward compatible with the old one.

**Comment by phisco** [comment]
Wouldn't it make sense to just call it a base image instead of controller or runtime? At the end of the day that's what it is, a base image we add a few labeled layers to.

**Comment by negz** [comment]
Maybe. In my mind it's a bit more / different than a base, because we're using the layers to add something "special" (package metadata) rather than just adding a regular new layer to a base. I don't feel strongly though, base probably makes sense to folks who are less close to the implementation details.

**Comment by phisco** [comment]
My thinking is as follows.
`--image` feels a bit too generic, it's not clear what we'll use the image for.
`--runtime` is confusing, runtime can mean too many things, e.g. the Python/Go runtime, runtime vs compile time... I wouldn't know without an explanation.
`--runtime-image` feels a bit better, but it still doesn't convey we are going to enrich the image, feels just like we are going to run that as is, and we need it to set it somewhere.
--base-image is clearly suggesting we are going to add layers to it and produce a new image.

**Comment by negz** [comment]
I can live with `--base-image`. Probably any concerns I have can be handled by the help string. 🙂

**Comment by turkenh** [comment]
I would vote for `--runtime-base-image`, long but clear.

**Comment by phisco** [comment]
But what would be the meaning of runtime for configurations for example?

**Comment by turkenh** [comment]
> But what would be the meaning of runtime for configurations for example?
Not supported. `--runtime-base-image` flag is only supported for package types with runtime. 

With [this PR](https://github.com/crossplane/crossplane/pull/4767), I am explicitly introducing the interface of `Packages With Runtime`. `Providers` and `Functions` are Packages with Runtime, but `Configurations` are not.

**Comment by phisco** [comment]
Sure, it's not used at runtime, but we are talking about building packages (`xpkg build`), not providers/functions/configurations specifically, that's why I feel we should not be too prescriptive.

**Comment by turkenh** [comment]
Maybe I am missing something but, if the package being built is a `Configuration` package, would that flag have any impact? 
I was thinking no, assuming we are talking about a replacement for `--controller` which is only valid for providers (and functions.

**Comment by phisco** [comment]
Nope 😅 that confirms the fact that it was confusing. The image passed as --controller was used as base image, adding a few layers on top of it with the meta definition and all the yamls found from the filesystem, as is, and the examples, if any. The result becomes the package (.xpkg) and if the meta definition didn't specify any controller/runtime explicitly, the xpkg would be used as both package and runtime image.

**Comment by turkenh** [comment]
Another reason for that confusion could be that it only makes sense to include a base layer if you use the same image (.xpkg) as the runtime image. Can we think of a use case where someone wants to provide a base image for a configuration package? 

If not, maybe we keep what we are doing (adding it as a base layer) as an implementation detail and make it explicit for user that "with this flag, you can provide you runtime image for this package" by just using "--runtime-image" 🤔

**Comment by phisco** [comment]
I don't see a reason to prevent people from providing a base image for a configuration if they need to 🤷‍♂️

**Comment by phisco** [comment]
--runtime-image would still make me think it's set as runtime image in the meta manifest. Which is actually a totally valid thing one could want, so I could see it with such semantics.

**Comment by negz** [comment]
I don't feel super strongly about this one, but if it helps:

* I think my slight preference is still for `--runtime-image` or `--runtime-base-image`
* I don't think the use case of adding a base image to a Configuration really exists (even though its possible)
