### ISSUE TITLE
Finalize Crossplane CLI command format and structure

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4787]
As part of https://github.com/crossplane/crossplane/issues/4648, we have a lot of new Crossplane CLI commands that will ship in v1.14.  We need to align and decide on the general format and structure of these commands.

Areas of consideration:

* **general command structure**
  * The current crossplane CLI was exclusively exposed as a `kubectl` plugin, so it consciously exposed its commands in the same format as `kubectl`, e.g. `kubectl crossplane <verb> <subject>`. From https://github.com/crossplane/crossplane/issues/4697, we are no longer tied to being just a `kubectl` plugin.
  * In general, what is the structure of all the commands we'll ship for v1.14?
* **subcommand per package type**
  * The current CLI exposes a specific subcommand for each type of package you can build (e.g. provider, configuration, and function), while `up` exposed just a general `build` command that works for all types of packages. We should decide which approach `crossplane xpkg build` should take.
* **alpha/beta commands**
  * Which commands that we are shipping in v1.14 should be included under the `alpha` or `beta` subcommands? Should function related commands be `beta` to match the overall XFN Beta maturity? Or is the CLI experiences/commands independently matured from the core feature? Should building a function be under `build` or under `function`? 

## Decisions

Decisions made in https://github.com/crossplane/crossplane/issues/4787#issuecomment-1766979905, resulting in the following command structure for v1.14:

* `crossplane`
  * `xpkg`
    * `login`
    * `build`
    * `push`
    * `install`
    * `update`
  * `beta`
    * `xpkg`
      * `init`
    * `render`
  * `alpha`
    * `describe`
    * `diagnose`

**Comment by jbw976** [comment]
cross-post from @negz in https://github.com/crossplane/crossplane/pull/4736#issuecomment-1760531518

> WRT alpha vs beta - my slight preference is to keep everything Function related as "beta".

**Comment by jbw976** [comment]
Below is a proposal for the general structure of all the commands we're hoping to ship in v1.14, in a hierarchical fashion to show command/subcommand relationships.

Not 💯 on this yet, so I may waffle more, but wanted to get this down to make progress together - feel free to provide feedback or suggest alternative proposals 😅 

### Conclusions

The following decisions naturally come out of this proposal:

* we are not tied to a strict `kubectl <verb> <subject>` format, other patterns can be used where/when they fit best
* prefer consistency in our `<verb> <subject>` ordering where possible
  * preference for keeping high level action verbs together (e.g. `init function` and `init configuration`, not `function init` and `configuration init` )
* use subcommands for all the package types (`provider`, `configuration`, `function`), so they have clear intent and use only scoped/relevant flags
* remove package related functionality now duplicated by `xpkg` commands as per #4783 
* introduce new commands with no previous history of functionality as `alpha`
  * note that since `function` is not a top level verb command, it's not logical to group `function` related functionality together anywhere. New functionality like `init` and `render` are under `alpha`.
  *  `xpkg` has previous history as `build`, `install`, etc. so it is not `alpha` or `beta`

### Command structure proposal:

* `crossplane`
  * `xpkg`
    * `build`
      * `function`
      * `provider`
      * `configuration`
    * `push`
      * `function`
      * `provider`
      * `configuration`
    * `install`
      * `function`
      * `provider`
      * `configuration`
    * `update`
      * `function`
      * `provider`
      * `configuration`
* `beta`
  * (none)
* `alpha`
  * `init`
    * `function`
  * `render`
  * `describe`
  * `diagnose`

**Comment by phisco** [comment]
Not a 100% sure we need to have type specific subcommands for build and push given that we are dealing with packages and not really care what type they are of at that stage. But for the sake of symmetry I agree it makes sense.

However, if we go down this path  wouldn't then make sense to split them up and have:
```
crossplane:
  providers:
    build
    push
    install
    update
  ... same for configuration, maybe functions can go below beta or just some commands ...
  alpha:
    ...
  beta:
    functions:
      render
      ... maybe all functions related commands can get here too ...
```
Obviously we wouldn't have to have 100% symmetry between the type subcommands, e.g. render will only make sense for functions.

**Comment by jbw976** [comment]
@phisco it seems like the key difference between your proposal and mine is that you're preferring `<subject> <verb>`, while I'm preferring `<verb> <subject>`. I'm placing more emphasis on the actions a user is going to take, and you're placing more emphasis on the objects they will perform actions on.

That seems to be the crux of the difference here and probably the biggest decision to make. Either way we go, I'd say consistency is the most important, so we'd want to keep that format consistent throughout all the commands.

Relevant reddit post: https://www.reddit.com/r/linux/comments/dipdq2/do_you_prefer_your_clis_to_be_verbfirst_or/ - there doesn't seem to be a 100% gold standard here, it's largely a preference thing, but if anything I see more folks in that thread preferring verb first than anything else 😊 

I think I still prefer verb first myself, do you feel strongly @phisco? How do other maintainers feel @turkenh @negz @bobh66?

**Comment by phisco** [comment]
Yes, I personally prefer `<noun> <verb>`, makes grouping easier and improve readability. If I'm building a function I'm interested in what else I can do on functions, not really what else I can build, and deleting the last part and adding `--help` will tell me what else I can do. The `<verb> <noun>` is wide-spread mostly because of `kubectl`, it did make sense for them, `kubectl get <resource>` doesn't really care about the resource type, it's just a get to the API server, but I don't think it does in our case.

**Comment by TerjeLafton** [comment]
I think this usually comes down to either scalability or what you think the user knows when they use the CLI.

You know best, but I don't think scalability would be a huge issue for this CLI as the number of commands seems quite low. 

Knowing that, the priority should probably be on the user experience here. So as a user, I would use this CLI in my project when I have created either a Function or Provider. In this case I know what `<subject>` I want to act on, because this is defined by my project, so I think the `<verb>` should probably be the last argument, as this is the thing I would "explore" the possibilities for.

The GCP and AWS CLIs follow this pattern, if I am not wrong, so there are some good examples out there. The GCP one also uses the alpha and beta scheme propsed above, which seems nice as a user.

I basically just agree with @phisco 😄

**Comment by turkenh** [comment]
+1 for `<noun> <verb>` due to the arguments folks pointed out already.

I remember a similar discussion with the [up](https://github.com/upbound/up), which eventually selected `<noun> <verb>` as well, but I couldn't find a referenceable discussion to link here.

**Comment by bobh66** [comment]
I have to vote for `<verb> <noun>`, if for no other reason than to be consistent with `kubectl`, but mostly because it hurts my brain when I have to reverse my thinking to `<noun> <verb>` for some command that I don't use enough to have the muscle memory programmed.

I understand the argument for the help syntax, and agree that _at the time I need help_ it makes sense, but for all of the other times when I _don't_ need help then it makes much more sense to perform an _action_ on a _thing_.

But really the question is - why would we want to be different than `kubectl <verb> <noun>`, which is what I spend 50% of my day running anyway, and now I have to switch to `crossplane <noun> <verb>` for the Crossplane-specific commands?  I think that's a poor user experience even if it means more work to figure out some help commands every once in a great while.

**Comment by phisco** [comment]
@bobh66, `kubectl` itself is drifting away from `<verb> <noun>`:
```
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/

Basic Commands (Beginner):
  create          Create a resource from a file or from stdin
  expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service
  run             Run a particular image on the cluster
  set             Set specific features on objects

Basic Commands (Intermediate):
  explain         Get documentation for a resource
  get             Display one or many resources
  edit            Edit a resource on the server
  delete          Delete resources by file names, stdin, resources and names, or by resources and label selector

Deploy Commands:
  rollout         Manage the rollout of a resource
  scale           Set a new size for a deployment, replica set, or replication controller
  autoscale       Auto-scale a deployment, replica set, stateful set, or replication controller

Cluster Management Commands:
  certificate     Modify certificate resources
  cluster-info    Display cluster information
  top             Display resource (CPU/memory) usage
  cordon          Mark node as unschedulable
  uncordon        Mark node as schedulable
  drain           Drain node in preparation for maintenance
  taint           Update the taints on one or more nodes

Troubleshooting and Debugging Commands:
  describe        Show details of a specific resource or group of resources
  logs            Print the logs for a container in a pod
  attach          Attach to a running container
  exec            Execute a command in a container
  port-forward    Forward one or more local ports to a pod
  proxy           Run a proxy to the Kubernetes API server
  cp              Copy files and directories to and from containers
  auth            Inspect authorization
  debug           Create debugging sessions for troubleshooting workloads and nodes
  events          List events

Advanced Commands:
  diff            Diff the live version against a would-be applied version
  apply           Apply a configuration to a resource by file name or stdin
  patch           Update fields of a resource
  replace         Replace a resource by file name or stdin
  wait            Experimental: Wait for a specific condition on one or many resources
  kustomize       Build a kustomization target from a directory or URL

Settings Commands:
  label           Update the labels on a resource
  annotate        Update the annotations on a resource
  completion      Output shell completion code for the specified shell (bash, zsh, fish, or powershell)

Other Commands:
  api-resources   Print the supported API resources on the server
  api-versions    Print the supported API versions on the server, in the form of "group/version"
  config          Modify kubeconfig files
  plugin          Provides utilities for interacting with plugins
  version         Print the client and server version information

Usage:
  kubectl [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```
e.g. `kubectl certificate deny/approve`, `kubectl rollout restart`, `kubectl auth reconcile`..

All commands `<verb> <noun>` are really because `nouns` are actually arguments and the `<verb>` doesn't really care about it.

**Comment by negz** [comment]
> How do other maintainers feel

I struggle to have an opinion either way.

Long term, I can imagine a world where folks can do most of what they need to do using `crossplane`. So the need to use `kubectl` _for Crossplane things_ would become more of an edge case. Something to consider when weighing how important it is to match the muscle memory we all have for `kubectl`.

**Comment by jbw976** [comment]
The majority preference in this thread seems to be for `<noun> <verb>`, so I've taken a stab below at the v1.14 command structure with that approach. I can see it making sense for clear `<nouns>` in our resource model, like `providers` and `functions`, but I started feeling less confident when I get to other functionality like troubleshooting in `diagnose`:

* What's the `<noun>` there? I suppose you're troubleshooting a given `resource`, but maybe there's scenarios where you'd be troubleshooting an entire `platform` or `control-plane`?
* How does this `<noun> <verb>` approach apply to [future planned commands ](https://github.com/crossplane/crossplane/issues/4654) like `top` and `validate`? Perhaps `crossplane control-plane top` and `crossplane composition validate`? 
* I guess you can always find an applicable `<noun>` that a command will act upon, but I'm not 💯 that commands are best exposed with `<noun>` first, when you may not know what the `<noun>` is.
* Maybe consistency of `<noun> <verb>` vs. `<verb> <noun>` isn't as important as we thought it was, and it would be OK to have a hybrid approach that instead always emphasizes the most intuitive and discoverable entity for a given command, regardless of if that's a `<verb>` or `<noun>`?

Proposal for `<noun> <verb>` format in v1.14:

* `crossplane`
  * `providers` 
    * `build`
    * `push`
    * `install`
    * `update`
  * `configurations` 
    * `build`
    * `push`
    * `install`
    * `update`
  * `beta`
    * `functions` 
      * `init`
      * `render`
      * `build`
      * `push`
      * `install`
      * `update`
  * `alpha`
    * `resource`
      * `describe`
      * `diagnose`

**Comment by jeanduplessis** [comment]
> Maybe consistency of <noun> <verb> vs. <verb> <noun> isn't as important as we thought it was, and it would be OK to have a hybrid approach that instead always emphasizes the most intuitive and discoverable entity for a given command, regardless of if that's a <verb> or <noun>?

I would argue that we are overcomplicating things at this stage. Let's choose a path, execute it and get feedback from real-world usage before bikeshedding on order. Its more important to get the functionality to the community than argue about the order for now.

**Comment by phisco** [comment]
> Maybe consistency of <noun> <verb> vs. <verb> <noun> isn't as important as we thought it was, and it would be OK to have a hybrid approach that instead always emphasizes the most intuitive and discoverable entity for a given command, regardless of if that's a <verb> or <noun>?

Totally this, we shouldn't be too strict, we should just pick what make the most sense.

> What's the <noun> there? I suppose you're troubleshooting a given resource, but maybe there's scenarios where you'd be troubleshooting an entire platform or control-plane?

Given the above, I'd say diagnose/describe could be verbs only, given that they can act on any resource.

**Comment by jbw976** [comment]
The maintainer team discussed this today (@negz @phisco @bobh66) and arrived at the command structure below to ship in v1.14, which will be added to the Decisions section in the issue body.

Some principles: 

* There is not a lot of value for exposing specific commands for each package type. We prefer less command surface area, and it does feel natural to have all of these `<verbs>` underneath the `xpkg` `<noun>`. `login` fits naturally there as well.
* A hybrid of `<noun>`/`<verb>` order is OK. We will prefer to expose the most intuitive/natural entity first, which often will be the `<noun>` being operated on, but when a clear `<noun>` doesn't exist, it's reasonable to expose the `<verb>` instead.
* Typically new functional areas will be introduced at `alpha`, but new functionality being introduced that is related to functions can start at `beta` to match the maturity of that feature area (e.g. `render` and `init`)

Conclusion:
* `crossplane`
  * `xpkg` (or `packages`) 
    * `login`
    * `build`
    * `push`
    * `install`
    * `update`
  * `beta`
    * `xpkg`
      * `init`
    * `render`
  * `alpha`
    * `describe`
    * `diagnose`
