### ISSUE TITLE
Buckets AWS Handler: Deleting Claim does not remove S3Bucket

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#479]
This could be an intermiten condition.
However, I just came across this condition.
I create S3Bucket via a claim, the s3bucket failed to create.
I deleted claim.
I expect the S3bucket should be also deleted, however, it appears to be left in "Orphan" state.

**Comment by negz** [comment]
We've moved to a standardised resource claim controller since this issue was raised; I'm going to close it out as I expect it's either fixed or affecting all managed resources. We can reopen if the latter is true.
