### ISSUE TITLE
Invalid AWS Region - please add support for il-central-1

### ISSUE THREAD

**Issue by halversonea** [crossplane/crossplane#4795]
### What happened?
Crossplane is not aware of new AWS region il-central-1

### How can we reproduce it?
Try using il-central-1

### What environment did it happen in?
Crossplane version: 1.13.2

**Comment by bobh66** [comment]
HI @halversonea - Crossplane core doesn't know anything about any of the cloud providers.  This is likely and issue with the AWS provider you are using, either the community provider in crossplane-contrib or the (soon to be community) Upbound provider.  So this issue belongs in one of those repos.  Maybe an AWS SDK update is required to use the new region?  It seems like even the providers should not care about region names - that should be data, not code.

**Comment by bobh66** [comment]
It's also possible that the region is not active for your account, but if you can see it in the AWS Console then that's not the problem
