### ISSUE TITLE
Figure out CI for Composition Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4796]
### What problem are you facing?

We want Functions to be pretty simple, so we're explicitly not using https://github.com/upbound/build (or even Makefiles). We also expect Functions to use other languages in future that https://github.com/upbound/build does not support today, including Python.

At the same time, we probably do want CI for most Functions, to handle things like:

* Automatically running a linter and tests, if any.
* Building and pushing the Function to a registry (e.g. xpkg.upbound.io)

Usually https://github.com/upbound/build does this for Crossplane repos. I think we need a simpler pattern. 

### How could Crossplane help solve your problem?

I'm thinking we put together a very stripped down version of [`ci.yml`](https://github.com/crossplane/crossplane/blob/2c5e7f07ba9e3d83d1c85169bbde685de8514ab8/.github/workflows/ci.yml). How it invokes tests and linting would differ from language to language, but hopefully building and pushing Functions would just invoke the `crossplane` CLI.

**Comment by negz** [comment]
I think we need to do this by the v1.14 release date, but not by feature freeze. The only interaction with feature freeze is making sure `crossplane` does what we need it to do in time - e.g. build and push Functions.

**Comment by negz** [comment]
First step would be adding CI to https://github.com/crossplane/function-template-go.

**Comment by turkenh** [comment]
Can we close this ticket, anything left here? 
Asking because this is one of the two issues left open in [v1.14 milestone](https://github.com/crossplane/crossplane/milestones/v1.14).

**Comment by negz** [comment]
I'm waiting for #4885 to be merged before closing.
