### ISSUE TITLE
Support containerd as a `crossplane beta render` runtime

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4806]
### What problem are you facing?
#4764 added support for `crossplane beta render` but it requires Docker. It'd be nice to support Containerd runtime as well

### How could Crossplane help solve your problem?
Please add support for containerd runtime

**Comment by dee-kryvenko** [comment]
This should be re-opened... need support for `nerdctl` or alternatives. The world does not end with Docker, command used by Crossplane CLI should be configurable. Alternative tools such as `nerdctl` and Podman generally maintain compatibility with the Docker CLI so it really should be simply the matter of allowing to override the path to the binary.

**Comment by bobh66** [comment]
The existing code assumes a running docker daemon, which can be simulated by running podman as a service, but it should be more configurable to handle other implementations.
