### ISSUE TITLE
Can't run `crossplane beta render` on Mac Docker Desktop 

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4807]
### What happened?

Trying to run `crossplane beta render` on Mac with Docker Desktop gives an error, even though Docker is running.

```
crossplane: error: cannot render composite resource: cannot start Function "function-dummy": cannot create Docker container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### What environment did it happen in?
Docker version 

```
docker -v                                               
Docker version 24.0.6, build ed223bc
```

Crank built from files at this point:
https://github.com/crossplane/crossplane/tree/6b99ef11874a9de0798326679a6c326733cc605e

### Workaround

Make a symlink for the `docker.sock` file.

```
sudo ln -s $HOME/.docker/run/docker.sock /var/run/docker.sock
```

**Comment by negz** [comment]
I wonder if this depends on the version of Docker Desktop being run. I could imagine we either:

* Try to hack around this on our side - i.e. look for this path existing.
* If everything works on newer Docker Desktop versions, document that we require a minimum version. (Maybe in the error string too.)

**Comment by plumbis** [comment]
This is on the latest available version of Docker Desktop. I don't know if things would be different on a clean install vs upgrades.

**Comment by Piotr1215** [comment]
Tested on the latest build of crossplane with `docker 23.0.5, build bc4487a59e` and all worked for me with examples from [xrender](https://github.com/crossplane-contrib/xrender/tree/main/examples). I've installed docker desktop fresh install however I had already docker-cli preinstalled so this might not be exactly like your situation @plumbis

**Comment by jbw976** [comment]
Working OK for me with `Docker version 24.0.6, build ed223bc` on `macOS 13.4.1 (c) (22F770820d)`.  The symlink exists for me already:

```
❯ ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  36 Sep  6 11:41 /var/run/docker.sock -> /Users/jared/.docker/run/docker.sock
```

Lots of funny business in the history of older docker for mac releases, hinted at in https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos, where the `/var/run/docker.sock` symlink was removed, re-added, didn't work right, etc.

Relevant hits from the https://docs.docker.com/desktop/release-notes for posterity:

* `4.13.0`: By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead.
* `4.13.1`: Added back the /var/run/docker.sock symlink on Mac by default, to increase compatibility with tooling like tilt and docker-py. Fixes docker/for-mac#6529.
* `4.14.0`: Re-added the /var/run/docker.sock on Mac by default, to increase compatibility with tooling like tilt and docker-py.
* `4.14.0`: Fixed an issue that prevented the creation of Dev Environments on new Mac installs (error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?").
* `4.16.0`: Fixed an issue causing Docker to prompt the user to install the /var/run/docker.sock symlink after every reboot.
* `4.16.0`: Ensured the Login Item which installs the /var/run/docker.sock symlink is signed.
* `4.17.0`: Fixed a bug where user is prompted to create the docker socket symlink on every startup. Fixes docker/for-mac#6634.

I can imagine some combination of history across versions where the symlink doesn't end up correctly in place. I wouldn't advocate for us building any logic in our tools to handle this yet, so perhaps we can ship v1.14 and see if folks are broadly affected by this first.

**Comment by jbw976** [comment]
I tried to sabotage my Docker for Mac setup by manually deleting the `/var/run/docker.sock` symlink - it was able to detect this and restore it, further decreasing the priority for us handling this issue, at least until we get more feedback from the community saying this is widespread.

Manual deletion:

```
❯ ll /var/run/docker.sock
lrwxr-xr-x  1 root  daemon    36B Sep  6 11:41 /var/run/docker.sock -> /Users/jared/.docker/run/docker.sock

❯ sudo rm -fr /var/run/docker.sock

❯ ll /var/run/docker.sock
ls: /var/run/docker.sock: No such file or directory
```

Quitting Docker for Mac and restarting it showed a warning that `Configs changed by another App` and prompted me to `Re-apply configurations`:

<img width="313" alt="Screenshot 2023-10-24 at 2 20 14 PM" src="https://github.com/crossplane/crossplane/assets/4313439/f7f250c0-4e2c-44c7-ac3d-8ac4bd64478d">

After doing that, the symlink was restored:

```
❯ ll /var/run/docker.sock
lrwxr-xr-x  1 root  daemon    36B Oct 24 14:20 /var/run/docker.sock -> /Users/jared/.docker/run/docker.sock
```

Wonder if you had a similar warning in the menu bar @plumbis?

**Comment by katikireddy622** [comment]
I faced the same issue and I used export DOCKER_HOST="unix:///Users/<username>/.docker/run/docker.sock"
and it is working now
