### ISSUE TITLE
Have `crossplane beta render` emit debug logs

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4809]
### What problem are you facing?

Today `crossplane beta render` doesn't log much (anything?). There's a bunch of TODOs in the codebase where it would be useful to do so - e.g. if we can't stop a Function running as a Docker container.

### How could Crossplane help solve your problem?

We should add some debug logging statements. Given that the command's main job is to print stuff to stdout we probably need to be careful about logging. I imagine we don't want to log anything in the happy path, and if we do hit issues we want to make sure they're going to stderr so the caller can filter output from logs.

**Comment by phisco** [comment]
Logging to stderr should be enough to avoid confusion with the actual output, wdyt @negz?
