### ISSUE TITLE
Support indicating whether an XR is ready using `crossplane beta render`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4810]
### What problem are you facing?

Crossplane uses a Composition to figure out whether the XR is ready. When you're using Functions, each desired resource indicates whether it's ready. If they're all ready, Crossplane marks the XR as ready (status condition wise). `crossplane beta render` doesn't do this today.

### How could Crossplane help solve your problem?

I think we could probably just set the `type: Ready, status: True` condition on the XR that we print out if the Function pipeline reports that all desired resources are ready.

**Comment by josegonzalez** [comment]
This is a dumb question, but how exactly is a user supposed to specify the readiness of a sub-resource via the `crossplane render` cli command? Specifically, as soon as I add `function-sequencer`, it fails to render anything but the resources that don't depend on others.

**Comment by bobh66** [comment]
@josegonzalez the `render` command accepts a list of observed resources which can be used to determine resource readiness.

**Comment by josegonzalez** [comment]
So do I need to generate yaml for each of those and manually set the `status` fields of the pre-requisites in order to get things to "pass"?
