### ISSUE TITLE
Validate `crossplane beta render` inputs

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#4852]
### What problem are you facing?

Currently, the following order works as expected:
```
crank beta render xr.yaml composition.yaml functions.yaml
```

However, this order doesn't work:
```
crank beta render composition.yaml xr.yaml functions.yaml
```

The error message received in the latter case is:

```
error: crossplane: error: invalid Composition "dev-cluster-a": spec.resources: Required value: an array of resources is required in Resources mode (the default if no mode is specified)
```

### How could Crossplane help solve your problem?
We need to implement input validation for the "crank beta render" command or add specifics for the file 
```
crank beta render -xr xr.yaml -composition composition.yaml -function functions.yaml
```

**Comment by negz** [comment]
Technically it _is_ doing input validation. That's where the error is coming from. The problem is the validation isn't considering the `apiVersion` and `kind`, so it's telling you why your XR is an invalid Composition instead of telling you that your XR is not a Composition. 😉
