### ISSUE TITLE
Crossplane CLI doesn't have a version 

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4855]
### What happened?
Running `crank -v` (`crossplane -v`) has no output.

### How can we reproduce it?

```shell
$  ./crank -v 

$
```

### What environment did it happen in?
Crossplane version: 
Latest master. https://github.com/crossplane/crossplane/tree/48f9ed536161cad46231a08ed8c593fe9d86e459

**Comment by negz** [comment]
Strange. I see one when I build a fresh `crank` from d1772ce3

```
$ _output/bin/linux_arm64/crank --version
v1.14.0-rc.0.680.gd1772ce3
$ _output/bin/linux_arm64/crank -v
v1.14.0-rc.0.680.gd1772ce3
```

**Comment by plumbis** [comment]
Maybe I'm doing something wrong when I'm building? Happy to close if this is just user error.

```shell

 ~/git/crossplane/cmd/crank$ git checkout d1772ce                                                                                           
Note: switching to 'd1772ce'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d1772ce3 Merge pull request #4846 from turkenh/deployment-runtime-config-message

 ~/git/crossplane/cmd/crank $ rm -rf crank && go build && ./crank -v                                                                              


 ~/git/crossplane/cmd/crank $
```

That being said I do see `-v` output with the binary on [releases.crossplane.io](https://releases.crossplane.io/stable/current/bin/darwin_arm64/)

**Comment by jbw976** [comment]
This is because you're building from a `detached HEAD` state - the version is embedded into the binary at build time using the `git describe` information like so: https://github.com/upbound/build/blob/master/makelib/common.mk#L214-L225.

For a `detached HEAD` state, git doesn't have any tags or revision list to build a reasonable version number from, so I guess it ends up blank 😊 

Here's what I did this morning to build from `master` and get a version number:

```
❯ git fetch --all
❯ git rebase upstream/master
❯ make
❯ ./_output/bin/darwin_arm64/crank -v
v1.14.0-rc.0.682.g48f9ed53
❯ git describe HEAD
v1.14.0-rc.0-682-g48f9ed53
❯ git --no-pager show -q HEAD
commit 48f9ed536161cad46231a08ed8c593fe9d86e459 (HEAD -> master, upstream/master, upstream/HEAD)
Merge: d1772ce3 f9814864
Author: Nic Cope <nicc@rk0n.org>
Date:   Thu Oct 19 12:52:30 2023 -0700

    Merge pull request #4853 from negz/ownersheep

    Don't auto-assign reviewers, for now
```

Let me know if I can answer any questions about your workflow to build from `master` @plumbis, happy to try to help! 🙇‍♂️

**Comment by plumbis** [comment]
Cool, thanks for the detailed explanation! Closing this one out.
