### ISSUE TITLE
`crossplane xpkg build --embed-runtime-image` doesn't work

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4866]
### What happened?

```shell
$ docker image ls|head -n2
REPOSITORY                                                        TAG                          IMAGE ID       CREATED          SIZE
function/runtime                                                  latest                       3aab715c046f   15 minutes ago   66.2MB

$ crossplane xpkg build -f package --embed-runtime-image=function/runtime:latest
crossplane: error: failed to build package: failed to mutate config for image: Error response from daemon: reference does not exist
```

### How can we reproduce it?

Build crank from 931e78df, and try use `--embed-runtime-image`.

### What environment did it happen in?
Crossplane version: 

Crank 931e78df.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/931e78df6147f97794819cf100683ad453cca7ed/cmd/crank/xpkg/build.go#L140

Interestingly we don't get an error here, despite the fact that the `daemon.Image` implementation eagerly fetches the image's config and thus should fail if the image didn't actually exist in the daemon. The error appears to be coming from somewhere later in the process.

**Comment by joebowbeer** [comment]
In v2, `index.docker.io` is required once again by #6548 ?

```shell
crossplane xpkg build -f package --embed-runtime-image=index.docker.io/function/runtime:latest
```

**Comment by jbw976** [comment]
I think so @joebowbeer, for the v2 release uses should explicitly specify a registry pretty much any time a package is being referenced. We've tried to capture this in https://docs.crossplane.io/v2.0-preview/whats-new/#backward-compatibility 🙏
