### ISSUE TITLE
Cut v1.14.0 Release on ~Nov 1, 2023

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4875]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.14.0] for
examples of each step, assuming release vX.Y.0 is being cut.

### Code Freeze

- [x] **[In Crossplane Runtime]**: Prepared the release branch `release-X.Y`:
  - [x] Created the release branch using the [GitHub UI][create-branch].
  - [x] (On the **Master** Branch) Created and merged an empty commit with `git commit --allow-empty -s -m "Empty commit after release-X.Y"` => https://github.com/crossplane/crossplane-runtime/pull/585
  - [x] (On the **Master** Branch) Run the [Tag workflow][tag-workflow-runtime] with the release candidate tag for the next release `vX.Y+1.0-rc.0`. => https://github.com/crossplane/crossplane-runtime/actions/runs/6640241731
  - [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow-runtime] with the release candidate tag for the next release `vX.Y.0-rc.1` (assuming the latest rc tag for `vX.Y.0` is `vX.Y.0-rc.0`). => https://github.com/crossplane/crossplane-runtime/actions/runs/6640257337
- [x] **[In Core Crossplane]:** Prepared the release branch `release-X.Y`:
  - [x] Created the release branch using the [GitHub UI][create-branch].
  - [x] (On the **Master** Branch) created and merged a PR bumping the Crossplane Runtime dependency to the release candidate tag from master, `vX.Y+1.0-rc.0`. => https://github.com/crossplane/crossplane/pull/4893
  - [x] (On the **Release** Branch) created and merged a PR bumping the Crossplane Runtime dependency to the release candidate tag on the release branch, `vX.Y.0-rc.1`. => https://github.com/crossplane/crossplane/pull/4902
  - [x] (On the **Master** Branch) Run the [Tag workflow][tag-workflow] with the release candidate tag for the next release, `vX.Y+1.0-rc.0`. => https://github.com/crossplane/crossplane/actions/runs/6651040972
- [x] **[In Core Crossplane]:** Cut a Crossplane **release candidate** from the release branch `release-X.Y`:
  - [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow] with the release candidate tag for the release `vX.Y.0-rc.1` (assuming the latest rc tag for `vX.Y.0` is `vX.Y.0-rc.0`). => https://github.com/crossplane/crossplane/actions/runs/6651462167
  - [x] (On the **Release** Branch) Run the [CI workflow][ci-workflow] and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.0-rc.1/...` should contain all the relevant binaries. => https://releases.crossplane.io/build/release-1.14/v1.14.0-rc.1
  - [x] (On the **Release** Branch) Run the [Promote workflow][promote-workflow] with channel `stable` and verify:
    - [x] The tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.0-rc.1/...`. => https://releases.crossplane.io/stable/v1.14.0-rc.1/
    - [x] The tagged build is NOT marked as "current" in [stable/current/version](https://releases.crossplane.io/stable/current/version).
    - [x] Ensured that the release candidate is visible on the stable helm repo with: `helm repo add crossplane-stable https://charts.crossplane.io/stable --force-update &&  helm search repo crossplane-stable --devel`.
  - [x] Published a [new release] for the tagged version as `pre-release`, with the same name as the version, taking care of generating the changes list selecting as "Previous tag" `vX.<Y-1>.0`, so the first of the releases for the previous minor. => https://github.com/crossplane/crossplane/releases/tag/v1.14.0-rc.1
    - [x] Select the `Set as a pre-release` and `Create a discussion for this release` checkboxes. 
    - [x] Do NOT select the `Set as the latest release` checkbox.
  - [x] Ensured that users have been notified about the release candidate on the `#announcement` channel of the Crossplane's Slack workspace. => https://crossplane.slack.com/archives/CEFQCGW1H/p1698335275815379

### Release

- [x] Opened a [docs release issue] => https://github.com/crossplane/docs/issues/598
- [x] Checked that the [GitHub milestone] for this release only contains closed issues.
- [x] Cut a Crossplane Runtime version and consume it from Crossplane.
  - [x] **[In Crossplane Runtime]**: Run the [Tag workflow][tag-workflow-runtime] on the `release-X.Y` branch with the proper release version, `vX.Y.0`. Message suggested, but not required: `Release vX.Y.0`. => https://github.com/crossplane/crossplane-runtime/releases/tag/v1.14.0
  - [x] **[In Core Crossplane]:** (On the **Release** Branch) Update the Crossplane Runtime dependency to `vX.Y.0`. => https://github.com/crossplane/crossplane/pull/4942
- [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow] with the proper release version, `vX.Y.0`. Message suggested, but not required: `Release vX.Y.0`. => https://github.com/crossplane/crossplane/releases/tag/v1.14.0
- [x] (On the **Release** Branch) Run the [CI workflow][ci-workflow] and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.0/...` should contain all the relevant binaries. => https://releases.crossplane.io/build/release-1.14/v1.14.0/
- [x] (On the **Release** Branch) Run the [Promote workflow][promote-workflow] with channel `stable` and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.0/...`. => https://releases.crossplane.io/stable/v1.14.0/
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.<Y-1>.0`, so the first of the releases for the previous minor. Before publishing the release notes, set them as Draft and ask the rest of the team to double check them.
- [x] Checked that the [docs release issue] created previously has been completed.
- [x] Updated, in a single PR, the following on `master`: => https://github.com/crossplane/crossplane/pull/4944
  - [x] The [releases table] in the `README.md`, removing the now old unsupported release and adding the new one.
  - [x] The `baseBranches` list in `.github/renovate.json5`, removing the now old unsupported release and adding the new one.
- [x] Closed the GitHub milestone for this release.
- [x] Publish a blog post about the release to the [crossplane blog]
  - https://blog.crossplane.io/crossplane-v1-14/
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: `#announcements` channel on Crossplane's Slack workspace.
  - [x] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].
  - [x] LinkedIn: same as Twitter
- [x] Request @jbw976 to remove all old docs versions from Google Search
- [x] Remove any extra permissions given to release team members for this release

[Code Freeze]: https://docs.crossplane.io/knowledge-base/guides/release-cycle/#code-freeze
[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[create-branch]: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository
[docs release issue]: https://github.com/crossplane/docs/issues/new?assignees=&labels=release&template=new_release.md&title=Release+Crossplane+version...+
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.14.0]: https://github.com/crossplane/crossplane/issues/4871
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow-runtime]: https://github.com/crossplane/crossplane-runtime/actions/workflows/tag.yml
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[GitHub milestone]: https://github.com/crossplane/crossplane/milestones
[crossplane blog]: https://blog.crossplane.io

**Comment by negz** [comment]
A new step for this release - cut a function-sdk-go release.

I don't think these need to be done in lockstep with Crossplane releases in future/in general, but we should cut the first one to coordinate roughly with v1.14.0. It depends on crossplane-runtime, so we can cut one whenever crossplane-runtime v1.15.0 is ready.

I'll handle the function-sdk-go release.

**Comment by negz** [comment]
Also, this cropped up today. I think it's a release blocker - i.e. we need it in the v1.14 release branch.

* https://github.com/crossplane/crossplane/pull/4901

**Comment by jbw976** [comment]
All items in the task list are done, thank you to @turkenh for running a successful release! ✅
