### ISSUE TITLE
Crossplane Should Emit Connection Secret in User Defined Format

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#489]
### Overview
Currently, crossplane emits connection secrets for managed resources in the crossplane specific format, which intended to be generic and work across all resources. The side effect of being generic, the connection secret format is rigid and is not always a good fit for a consuming application which requires additional secret processing/transformation.

### Ask
Add support templatized connection secret. 
For example, at a high level:
```
provider: AWS
# Specify the region
region: {{.Region}}
# Specify access/secret keys
aws_access_key_id: {{.UserName}}
aws_secret_access_key: {{.Password}}
```
or
```
provider: Google
google_project: {{.ProjectID}}
google_client_email: {{.ServiceAccountEmail}}
# Ensure indentation is correct for `google_json_key_string`
# - YAML is a superset of JSON, so you can paste & indent
#   `example-project-382839-gcs-bucket.json` 2-4 spaces directly.
google_json_key_string: |
  {{.KeyFileContent}}
```

**Comment by lukeweber** [comment]
Yeah, this looks super interesting to solve consumption side issues.

Configmap reference on a resource claim might be a good way to pass a template.

**Comment by bassam** [comment]
tangentially related https://github.com/crossplaneio/crossplane/blob/master/design/custom-secret-definitions.md

**Comment by negz** [comment]
Somewhat related to https://github.com/crossplaneio/crossplane/issues/361.

**Comment by negz** [comment]
This is actually now pretty much done, in that folks consume resources via a composite resource, and they can configure exactly what that composite resource's secret looks like via its InfrastructureDefinition.
