### ISSUE TITLE
support group/name input for trace command

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4907]
### What problem are you facing?

Today the `crossplane beta trace` commands requires `group` [space] `name`. It doesn't support `/` style outputs provided by some Kubernetes outputs like `kubectl get claims`

### How could Crossplane help solve your problem?

Support input of `group/name` resource like `crossplane beta trace cluster.aws.platformref.upbound.io/platform-ref-aws`

**Comment by phisco** [comment]
I actually implemented it at first and then dropped it because I couldn't come up with a not so confusing help message for the allowed syntaxes 😂 I'll open a pr with the code and ask your help on the help messages.

**Comment by plumbis** [comment]
I would just leave the help text as is and just accept the input. We can mention in the CLI docs that both inputs are supported.
