### ISSUE TITLE
Support initialization hooks in `crossplane beta xpkg init`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4941]
### What problem are you facing?

Today the `crossplane beta xpkg init` command is effectively `git clone`. It just clones a Git repository used as a template.

Once you've cloned a repository there's usually some fairly mechanical steps to take before you start adding your business logic (i.e. actually implementing a function or provider). For example in https://github.com/crossplane/function-template-go you want to:

* Find and replace `crossplane/function-template-go` with your function's name in a bunch of places.
* Rename the `Input` kind and apiVersion to match what your function does (or delete the type if you don't need it).

### How could Crossplane help solve your problem?

It would be ideal if we could automate some of the mechanical manual steps.

I think almost all templates will need some amount of renaming. Other things like editing the `Input` type for a Go function would be pretty specific to one template. Perhaps each template could have a post install hook binary (e.g. a shell script) that the CLI optionally invokes? Another idea @phisco suggested would be to print a `NOTES.txt` similar to Helm - or we could do both.

**Comment by phclark** [comment]
I love the idea of templating some variables when scaffolding. I wonder if it can be taken a step further with a series of questions about the content? Maybe the definition of functions doesn't vary a whole lot, but I'd love if this approach could be extended to Compositions, which I feel like could really benefit from some more customization when scaffolding.

**Comment by lsviben** [comment]
Initial thoughts about this and what I started working on (can be modified ofc). I mostly went with @phisco suggestion about NOTES.txt plus from what I gathered in discussion with him and @ezgidemirel .

`init` command will (alongside cloning the repo):
1. Look for a `NOTES.txt` file in the repo root. If present it will treat it as a go template file and try to replace {{ .Name }} with the provider name. If its just a text file, the templating wont do anything. 
2. Print the `NOTES.txt` if present.

This would be a starting point. So templates we initialize can have their own choice on what to do with the NOTES.txt file. And for those that dont have it, nothing will change. For now templating in it only name as its the most common thing between Functions, Providers, etc. 

As a second step, we could introduce a third step in which we call a `hack/init.sh` script in the repo (if it exists) for the users automatically (maybe ask if to run?). We can provide the name as an argument by default.

**Comment by eshepelyuk** [comment]
Why not leveraging some existing project generation template tools like
https://github.com/cookiecutter/cookiecutter + https://github.com/cruft/cruft

**Comment by lsviben** [comment]
> Why not leveraging some existing project generation template tools like https://github.com/cookiecutter/cookiecutter + https://github.com/cruft/cruft
> 
> Is it only because CLI is golang based and can't invoke non golang code ?

TBH I was not aware of the above tools. And in those particular ones it would mean that users would have to have `pipx` and `cookiecutter` to run `crossplane init`, which I would like to avoid. 

The current solution with executing an `init.sh` script, the contents of which are left to the template developers gives them a flexibility to use whatever tools(or not) they would like. Its seems good for a start.
