### ISSUE TITLE
`crossplane validate xrd.yaml xr.yaml`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4976]
### What problem are you facing?

https://github.com/crossplane/crossplane/issues/4968 is an example of the kind of hard to diagnose issues a malformed XRD OpenAPI schema can cause. It would be helpful if folks could test an XRD schema using the CLI.

### How could Crossplane help solve your problem?

 A command like `crossplane validate xrd.yaml xr.yaml` could take an XR or directory of XRs and use them to test the schema, ie point out XR fields that don’t appear in the schema, are the wrong type etc.

**Comment by jbw976** [comment]
Added this issue to the devex epic to replace the placeholder task we had in that epic for a `validate` command ✅ 

* https://github.com/crossplane/crossplane/issues/4654

**Comment by negz** [comment]
I just remembered while chatting to @jbw976 - the idea here was actually kind "reverse" validation. More validating that the _XRD_ is correctly formed than the XR. I think folks find it easier/more intuitive to write an XR than to write an OpenAPI schema for an XR. So you could think of this like a "test framework" that takes a bunch of XRs and uses them to test the XRD schema.

**Comment by jbw976** [comment]
Marking this as nice to have in v1.15, but not a requirement and not a prioritized focus.

**Comment by Piotr1215** [comment]
> kind "reverse" validation

To expand a bit on this idea, it would be great if a command could actually _generate_ (including update) an XRD based on XRs. The issue with creating XRDs is the deep nesting of fields and repetitiveness, which leads to copy-paste errors. 

Imagine a command option like so `crossplane validate xrd.yaml xr.yaml --update` that would simply add missing fields from the XRs to the XRD. The `--update` flag would just add some more rudimentary scaffolding for the XRD or generate a new one if it doesn't exist. The mechanism could infer the data type from values in the XRs.

A potential next step we should avoid is the risk of inventing a _mini-DLS_ to rely on comments etc. to guide the validate command. This is something we've tried to invent multiple times for our platform, and it always backfired with unintended complexity. If we could strike a good balance between useful generator and validator, it would be a great aid in the development process.

**Comment by lsviben** [comment]
We solved this with #5162 right? cc: @ezgidemirel

**Comment by ezgidemirel** [comment]
Yes, it's solved.
