### ISSUE TITLE
Cut v1.14.1

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4979]
This issue can be closed when we have completed the following steps (in order). Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from this issue for posterity. Refer to this [prior release issue][release-1.11.1] for examples of each step, assuming vX.Y.Z is being cut.

- [x] Run the [Tag workflow][tag-workflow] on the `release-X.Y`branch with the proper release version, `vX.Y.Z`. Message suggested, but not required: `Release vX.Y.Z`. => https://github.com/crossplane/crossplane/releases/tag/v1.14.1
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.Z/...` should contain all the relevant binaries. => https://releases.crossplane.io/build/release-1.14/v1.14.1/
- [x] Confirm the full set of patch versions that will be released and promote them from lowest to highest, so the **highest** version is the **last** to be promoted (e.g. `v1.12.2` should be promoted after `v1.11.3`), in order to avoid the promote workflow overwriting the latest patch release.
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the `release-X.Y` branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.Z/...`. => https://releases.crossplane.io/stable/v1.14.1/
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.Y.<Z-1>`, so the previous patch release for the same minor. Before publishing the release notes, set them as Draft and ask the rest of the team to double check them.
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: `#announcements` channel on Crossplane's Slack workspace.
  - [x] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].
  - [x] LinkedIn: same as Twitter
- [x] Remove any extra permissions given to release team members for this release

[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.11.1]: https://github.com/crossplane/crossplane/issues/3796
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml

**Comment by negz** [comment]
We need to release at least https://github.com/crossplane/crossplane/pull/4978. Could be worth waiting a day or two to see whether there’s any other bug fixes to include.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/issues/4970 would be a pretty easy fix to include, too.

**Comment by haarchri** [comment]
https://github.com/crossplane/crossplane/issues/4980 looks like a candidate for v1.14.1

**Comment by negz** [comment]
Yep, #4980 is the issue associated with #4977 / #4978.

**Comment by turkenh** [comment]
I run the steps up to the `Promote` but waiting the version to be usable for the CLI. I am still (for about 2-3 hours) seeing `v1.14.0` with the following:

```
curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | sh
./crossplane --version
```

I suspect this to be a caching issue, because, when I check the current version from the url `https://releases.crossplane.io/stable/current/version` using the browser, it is `v1.14.1`.

**Comment by turkenh** [comment]
For posterity, now I am getting correct version after waiting for more than 12 hours. 

```
curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | sh
./crossplane --version
crossplane CLI downloaded successfully! Run the following commands to finish installing it:

sudo mv crossplane /usr/local/bin
crossplane --help

Visit https://crossplane.io to get started. 🚀
Have a nice day! 👋

v1.14.1
```

If we want to avoid this in the future, we need to find a way to do some configuration tweak, probably something with how we are serving the artifacts.

**Comment by jbw976** [comment]
Release is announced, closing this out! thank you @turkenh 🎉
