### ISSUE TITLE
Oracle cloud provider

### ISSUE THREAD

**Issue by pguerin3** [crossplane/crossplane#4985]
### What problem are you facing?
I would like to trial Crossplane with an Oracle cloud provider.

### How could Crossplane help solve your problem?
Add the Oracle cloud provider to the marketplace.

**Comment by bobh66** [comment]
Hi @pguerin3 - there is a development version of the OCI provider here - https://github.com/oracle-samples/crossplane-provider-oci

It's up to Oracle to decide if/when the provider is ready for use and submit it to the marketplace.
