### ISSUE TITLE
Testing: Adding ability for stronger E2E tests by mocking actual calls to cloud providers (Azure, AWS etc.)

### ISSUE THREAD

**Issue by mjnovice** [crossplane/crossplane#4987]
### What problem are you facing?

We currently have an operator which creates crossplane MRs as well as XRs. We have an E2E test suite where we make calls to the actual cloud providers (Azure, AWS etc.). We also tried kuttl tests which allows us to render the manifests and compare between expeted and actual manifests, however it still lacks the E2E-ness in terms of testing.

What we perhaps want is https://localstack.cloud/ (not sure if they support Azure,GCP)'s ability to actually not make network calls.

### How could Crossplane help solve your problem?

By not having to make actual network calls, this would greatly simplify and hasten the development process of any provider, user etc.

**Comment by eimarfandino** [comment]
@mjnovice AWS can be solved with localstack, Azure i dont know
