### ISSUE TITLE
Optionally run `crossplane beta render` against a live control plane

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4996]
### What problem are you facing?

I'm leading with the solution here. I think being able to point `crossplane beta render` at a live control plane could do a few things:

1. Automatically load observed resources from the API server (without needing to pass `--observed-resources`).
2. Use the API server to dry-run apply and thus validate the schema of the XR and composed resources.
3. Produce a diff between the proposed state and the existing state of an XR and any composed resources.

This addresses two key issues:

1. Today `crossplane beta render` is schema unaware. It will render out an XR or composed resource, but doesn't know whether a particular field should be a string or integer, or should even exist. It won't catch misindented fields, wrong types, etc.
2. Today `crossplane beta render` shows you how a particular XR/Composition would be rendered. If you want to know how that differs from what you're running in a particular control plane you must diff it yourself.

### How could Crossplane help solve your problem?

Add a new optional flag, like `--validate` or similar, that will cause `crossplane beta render` to manage and leverage control plane machinery for accurate and complete validation.

**Comment by negz** [comment]
Someone at Kubecon pointed me to https://github.com/homeport/dyff, which could be useful for diffing state.

**Comment by negz** [comment]
FWIW it would mostly be possible to make `crossplane beta render` schema-aware without requiring you to have a control plane to point it at, but I suspect requiring a control plane would end up being a better experience.

Without a control plane, the `render` command needs OpenAPI schemas to validate the XR and any composed resources. That means it needs to somehow get the CRDs and XRDs of anything it could compose. Some thoughts on that:

* Making folks supply MR CRDs manually feels too low level, so we could support `--providers`. Have the CLI pull down a provider package and load its CRDs. Would we support `--configuration` too for XRDs? Many folks don't use Configurations.
* We'd probably have to go pretty far down the path of replicating how the API server uses OpenAPI schemas to validate stuff. For example what about `x-kubernetes-...` OpenAPI extensions? What about validation webhooks?

Overall if we assume most folks will have access to a control plane, and are trying to build a Composition to work with that control plane, I think being able to optionally point `beta render` at it for more thorough validation might be a better experience.

**Comment by Piotr1215** [comment]
> Produce a diff between the proposed state and the existing state of an XR and any composed resources.

This is fascinating as the output could be used as a kind of _assert_ for composition testing, similar to [kuttl](https://kuttl.dev/), but with added knowledge about Crossplane. I  see the `crossplane beta render` and maybe some adjacent commands as key elements of the `inner dev loop` and `integration testing`.

Here are the 2 use cases I have in mind:

### Inner dev loop

Using the `crossplane beta render` would significantly improve the inner dev loop.
For example, let's say we have set of MRs rendered by the XR in the cluster.
Every time we make a change, the diff between what we are outputting from the composition and what is on the cluster would help with fixing any mistakes. This process is done in various ways, we use kuttl tests and skaffold, however the inner dev loop is very slow and brittle. 

### Integration testing

As for the testing, the main idea behind it is to check the correctness of the composition P&T logic. Does my composition result in the desired state of managed resources? This would require expanding the `crossplane beta render` functionality to also be able to compare what is _rendered_ to what resources we _expect_. It would eliminate the need to use kuttl and help with creating a Crossplane aware composition integration testing tooling.

**Comment by negz** [comment]
Thinking about this a little more, I think we should start by focusing on the inner dev loop. i.e. Focus on adding validation to render. We can follow with diff support later.

During initial development of XRDs, compositions, etc it's likely that a lot of folks won't have a live cluster yet. Requiring them to manually deploy one, configure Crossplane, etc doesn't sound like a smooth user experience to me. On the other hand, I think building validation would be a lot easier if we just leveraged Crossplane and the API server "under the hood".

I'm thinking we could have an optional `--validate` flag that (behind the scenes):

1. Uses `kind` to spin up a local cluster.
2. Installs Crossplane along with the set of configurations and providers an XR/Composition depends on.
3. Uses dry-run apply against the kind cluster to validate the `render` results
4. Spins down the kind cluster.

I think this approach makes sense because:

* I suspect it would be easier for us to build compared to teaching `beta render` how to get access to MR CRDs (e.g. by pulling and extracting packages).
* It decouples the validation logic - it's not compiled into `beta render` and thus coupled to a specific Crossplane or API server version.
* It's the most thorough validation we could do - compared to e.g. only validating using OpenAPI schemas.

**Comment by ytsarev** [comment]
@negz cool idea. Nit: If we embed it into CLI and run behind the scenes, it is probably better to use lightweight `k3s` instead of `kind`

**Comment by Piotr1215** [comment]
Having the tooling to _install_ a local cluster is a good idea. In this context, KIND or k3s/k0s etc. are dependencies. I like to think about it in the same way as how `apt` would install dependent packages and configure system state. In other words, it's an implementation detail that doesn't have to be part of developer experience.  

Cluster could also be kept up for subsequent runs to make things snappier. Btw, this is currently how we use `skaffold` in setting up a KIND cluster. Having this be part of crossplane CLI makes the whole workflow much more streamlined.

@ytsarev as for KIND vs k3s, agree that k3s should be faster, but I remember it being a bit more finicky with networking setup. It might have changed since I've tried it.

**Comment by ytsarev** [comment]
@Piotr1215 we did the kind->k3d/k3s [switch](https://github.com/k8gb-io/k8gb/issues/141) in k8gb test pipelines back in 2020, gained performance benefits, found no reason to switch back... And we are testing multicluster networking setup there, so I see no real network configuration issues.

**Comment by jbw976** [comment]
After thinking about this more and chatting with others, we won't be prioritizing this feature. Validation of resources at design time should definitely be possible in Crossplane, as that is the most important part of the experience and "shifts left" validation of your compositions to as early as possible in the process, but we will not depend on a live control plane.

Instead, a core library for design time validation should first be built. This library can then be leveraged in a wide variety of scenarios, first and foremost being the `crossplane` CLI.  More benefits to this approach include:

* This will avoid a lot of complexity, dependencies, having to bootstrap external systems, etc. It is an explicit goal to be able to run this validation logic at design time anywhere and without dependencies, not only in a setup with specific assumptions about the availability of a Kubernetes API server.
* This approach will support validation of types that are not yet published or committed, e.g. the local development scenario where brand new XRDs/Compositions are being defined.
* It would also support running in environments that are sandboxed or have difficulty reaching out to live control planes (designers, GH Actions, etc.)

While this specific issue will not be included in the upcoming roadmap, be on the look out for a valuable local/offline validation experience in v1.15 that is being tracked in:
* #5162

**Comment by dbs-gong** [comment]
workaround - it is possible to pull up the functions insecure pods +service on a cluster and then use the combined annotations in the file provided to the crossplane beta render functions.yaml to direct them to the functions available in k8s  
```
render.crossplane.io/runtime: Development
render.crossplane.io/runtime-development-target: dns:upbound-function-patch-and-transform-insecure:9443
```
this will allow crossplane beta render to run from a github-action-runner inside k8s running in the same namespace as the aforementioned deployed insecure functions. 
we have implemented this scenario to enable diffing pr's to crossplane compositions in github actions .

**Comment by jcogilvie** [comment]
[consider `crossplane-diff` ](https://github.com/crossplane-contrib/crossplane-diff)
