### ISSUE TITLE
Scale test composition functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5004]
### What problem are you facing?

We promoted functions to beta in v1.14. We'd like to promote them to GA in v1.15. Before we do that, we should have an understanding of their performance and scaling characteristics. Some questions:

* How many requests/second can a simple function handle with one replica? What about with N replicas?
* How many XRs can exist at once sharing a simple function with one replica? What about with N replicas?
* Do things change significantly when using a pipeline of functions?
* What are the biggest performance bottlenecks? What could we improve?

Ultimately functions are pretty open ended - for example I imagine a Python function will be a lot less performant than a Go function. I also imagine it will be very possible to write a slow Go function. Mostly I would like to validate that there's no huge performance issues with the architecture overall - i.e. that a relatively simple function scales up to hundreds or thousands of requests pretty easily.

### How could Crossplane help solve your problem?

Test and understand the scale limits of functions. 😄

**Comment by negz** [comment]
@Piotr1215 Are you interested in helping out with this one? If so I can sync to swap notes before I head out on vacation.

**Comment by negz** [comment]
We'll probably want to add the metrics from https://github.com/crossplane/crossplane/pull/5006 before testing, to give us more things to measure.

**Comment by Piotr1215** [comment]
@negz of course, I'll be happy to help. Let's organize a quick sync before your PTO. It also aligns with #5036 as the `top` command could include simple utilization metrics for functions too.
