### ISSUE TITLE
Setting Invalid XR Status Causes Flood of Function Executions

### ISSUE THREAD

**Issue by dalton-hill-0** [crossplane/crossplane#5007]
### What happened?
When a Function incorrectly configures the XR's status (e.g., adds a field that does not exist in the XRD/CRD spec), the XR generation increases ~10 times per second. Each generation increase triggers a function run.

Ideally, if a Function incorrectly configures the XR's status, the attempt should fail without:
- creating a new XR revision
- queueing a new function execution

### How can we reproduce it?
1. Configure a function to set a non-existent field on the XR's status (cause a k8s CRD validation failure).
2. Create a claim that is reconciled by the function.

The following can then be observed:
  - Claim's XR will increase ~10 generations each second
  - Function will get called for each of these generations
  - Error logs seen in `crossplane-system/crossplane` pod (if debug logs are turned on)

For instance, if our function tries to set `status.invalidField` (assuming `invalidField` is not in the spec) logs from `crossplane` pod look like:
```
crossplane-6f7547dccc-4nxqp 2023-11-15T17:43:47Z    DEBUG    crossplane    Event(v1.ObjectReference{Kind:"XRoster", Namespace:"", Name:"main-f2xjr", UID:"", APIVersion:"my.resource.group/v1alpha1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'ComposeResources' cannot compose resources: cannot apply composite resource status: failed to create typed patch object (/main-f2xjr; my.resource.group/v1alpha1, Kind=XRoster): .status.invalidField: field not declared in schema
```

### What environment did it happen in?
Crossplane version:  `v1.14.1`
Cluster built with: `kind v0.20.0 go1.20.5 darwin/arm64`
Cluster image used: `kindest/node:v1.28.0`
kubectl version: `Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
`
OS: mac m1 (arm64)

**Comment by phisco** [comment]
It should be applying an exponential backoff, maybe we could tune it down to avoid trying to reconcile it so many times 🤔

**Comment by dalton-hill-0** [comment]
> It should be applying an exponential backoff, maybe we could tune it down to avoid trying to reconcile it so many times 🤔

In normal circumstances I do notice exponential backoff logic in crossplane. Though I believe this specific case does not trigger any backoff. In ~10 seconds you will see 100+ generations of the XR.

**Comment by negz** [comment]
@dalton-hill-0 Did you have to enable strict [server-side field validation](https://kubernetes.io/blog/2023/04/24/openapi-v3-field-validation-ga/) to get this behaviour?

We should fix it either way, just curious because this differs from the behaviour we've seen in older versions of Kubernetes where the unknown field is just discarded.

**Comment by dalton-hill-0** [comment]
> Did you have to enable strict [server-side field validation](https://kubernetes.io/blog/2023/04/24/openapi-v3-field-validation-ga/) to get this behaviour?

@negz To my knowledge we have not specified this setting anywhere. If I'm reading the k8s docs correctly, this would likely be an option available in the go client that makes the apiserver PUT request (somewhere in the crossplane function framework?).

**Comment by phisco** [comment]
This might be actually improved by  https://github.com/crossplane/crossplane/pull/5365

**Comment by phisco** [comment]
If this was about initial creation, this is due to the fact that we recompute every time the generated name for the failing composed resource and update the XR's `resourceRefs` with it, which bumps the generation.
