### ISSUE TITLE
Sort `crossplane beta render` output

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5008]
### What problem are you facing?

The current behavior of Crossplane beta render output is causing challenges during local debugging. Specifically, the output is not sorted, making it harder for developers to analyze and understand the rendered resources.

### How could Crossplane help solve your problem?
The render output should be sorted, preferably by the 'kind' field, to provide a more organized and easily understandable view for local debugging.

The current workaround involves using external tools such as Python to manually sort the output, as demonstrated by the following command:

```
python3 -c "import yaml; data = list(yaml.load_all(open('$file'), Loader=yaml.FullLoader)); data.sort(key=lambda x: x.get('kind', '')); yaml.dump_all(data, open('$file', 'w'), default_flow_style=False)"
```

Implement native sorting within the Crossplane CLI for the render output, either by default or through a command-line option.

**Comment by phisco** [comment]
I'd say sorting by kind AND name would be more stable. Other than that, totally agree 👍

**Comment by haarchri** [comment]
did the same today with kind AND annotations - looks more stable:

```
python3 -c "import yaml; data = list(yaml.load_all(open('$file'), Loader=yaml.FullLoader)); data.sort(key=lambda x: (x.get('kind', ''), str(x.get('metadata', {}).get('annotations', '')))); yaml.dump_all(data, open('$file', 'w'), default_flow_style=False)"
```
