### ISSUE TITLE
`xpkg init configuration-template`

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5014]
Similar to how `xpkg init` can scaffold a new project for functions and providers, it should also be able to scaffold a new `configuration` project, i.e. an XRD and Composition.  People rarely start building a new configuration manually from scratch, I suspect most folks copy an existing one and then start modifying it for their needs.

We can accelerate this effort by extending `xpkg init` to also scaffold a `configuration` package. The minimal useful set here would be everything you need for a `configuration` package with 1 type in it:

* crossplane.yaml
* xrd.yaml
* composition.yaml

We can consider generation tools as well, such as https://github.com/crossplane-contrib/x-generation, but the most straightforward path here that achieves parity with existing functionality in `xpkg init`, is to download a simple template repo.

**Comment by phisco** [comment]
init subcommands would probably benefit from being interactive

**Comment by Piotr1215** [comment]
For the interactive reference, I like how [yeoman](https://yeoman.io/) generator works.

**Comment by lsviben** [comment]
I think we can solve this now by using `crossplane init` with [hooks](https://github.com/crossplane/crossplane/issues/4941)? 
Set up a configuration template repo that has an `init.sh` which asks what you want and generates it for you? Probably the generation part will be tricky, but with the new hooks the solution doesn't depend on Crossplane CLI anymore and can use any tool that it can run with the `init.sh`.
