### ISSUE TITLE
Versioning of `crossplane-tools` aligned with c/c

### ISSUE THREAD

**Issue by maximilianbraun** [crossplane/crossplane#5015]
Hi 👋 

i'd like to open a discussion on the topic of versioning of [crossplane/crossplane-tools](https://github.com/crossplane/crossplane-tools)

### What problem are you facing?

Today when composing the dependencies for a provider we have the c/crossplane and c/crossplane-runtime aligned on the versioning, which is great to understand the requirements. The version of c/crossplane-tools is (atleast) bound to the version of c/crossplane-runtime, but thats currently not directly visible in the version of the module.

### How could Crossplane help solve your problem?

Introduce versioning of c/crossplane-tools aligned with the versioning of c/crossplane-runtime. Since there are not too many changes on c/crossplane-tools, we can safely use the minimal required version of crossplane-runtime, e.g. v.1.14._, as a base for versioning the module.

**Comment by turkenh** [comment]
This makes sense to me. 
The only concern I have is the slight overhead it is adding on top of (manual) [release process](https://github.com/crossplane/crossplane/issues/4875).
