### ISSUE TITLE
Claim and XR don't reflect status of MRs after they are first created by Function

### ISSUE THREAD

**Issue by chaitanyakolluru** [crossplane/crossplane#5025]
### What happened?

After MRs are initially composed by the function and are handled by Crossplane and their respective providers, if we were to delete the MRs or if the MRs were to go SYNCED=false or READY=false, we want that status propagated back up to the level of the Claim and XR. 

Once resources are created we want Crossplane to monitor the status of the MRs and reflect back their status to the Claim and XR when one of it's MRs get out of sync or become unready. A trigger or a hook that allow XR status to be updated when it's MRs are not in good state.

### How can we reproduce it?

Once function composes MRs and Crossplane deploys those resources with the help of it's corresponding providers, either delete or make changes to the provider associated so the MR goes unready, you should still see the Claim and XR with synced and ready flags set to true.

### What environment did it happen in?
Function version: 
Crossplane version: v1.14.0

**Comment by negz** [comment]
@chaitanyakolluru does your function tell Crossplane that the resources are now unready? It's up to the function to report that a desired composed resource is Ready: false in the RunFunctionResponse (https://github.com/crossplane-contrib/function-auto-ready should do this automatically for resources with a Ready status condition).

If the function pipeline reports that less than all of the composed resources are ready I would expect the XR to transition back to "creating", which in itself is kinda strange.

https://github.com/crossplane/crossplane/blob/cd347b/internal/controller/apiextensions/composite/reconciler.go#L665
https://buf.build/crossplane/crossplane/docs/main:apiextensions.fn.proto.v1beta1#apiextensions.fn.proto.v1beta1.Resource
