### ISSUE TITLE
Cut v1.14.2

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#5041]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from this issue for posterity. Refer to this [prior release issue][release-1.11.1] for examples of each step, assuming vX.Y.Z is being cut.

- [x] Run the [Tag workflow][tag-workflow] on the `release-X.Y`branch with the proper release version, `vX.Y.Z`. Message suggested, but not required: `Release vX.Y.Z`. => https://github.com/crossplane/crossplane/actions/runs/6943725766
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.Z/...` should contain all the relevant binaries. => https://github.com/crossplane/crossplane/actions/runs/6943736967
- [x] Confirm the full set of patch versions that will be released and promote them from lowest to highest, so the **highest** version is the **last** to be promoted (e.g. `v1.12.2` should be promoted after `v1.11.3`), in order to avoid the promote workflow overwriting the latest patch release.
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the `release-X.Y` branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.Z/...`. => https://releases.crossplane.io/stable/v1.14.2/
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.Y.<Z-1>`, so the previous patch release for the same minor. Before publishing the release notes, set them as Draft and ask the rest of the team to double check them. => https://github.com/crossplane/crossplane/releases/tag/v1.14.2
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: `#announcements` channel on Crossplane's Slack workspace.
  - [x] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].
    - https://twitter.com/crossplane_io/status/1727107119961481406
  - [x] LinkedIn: same as Twitter
    - https://www.linkedin.com/feed/update/urn:li:share:7132872938294321152/
- [x] Remove any extra permissions given to release team members for this release

[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.11.1]: https://github.com/crossplane/crossplane/issues/3796
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml

**Comment by turkenh** [comment]
We need to cut a patch release with https://github.com/crossplane/crossplane/pull/5023 and https://github.com/crossplane/crossplane/pull/5040. 

Anything else that needs to be in?

**Comment by turkenh** [comment]
I would like to include https://github.com/crossplane/crossplane/pull/5044 as well.

**Comment by turkenh** [comment]
@sttts @phisco do we want to include https://github.com/crossplane/crossplane/pull/5045 as well?

**Comment by phisco** [comment]
I'd say so, yes 🙏

**Comment by MisterMX** [comment]
Would it be possible to include #5051 as well?

**Comment by turkenh** [comment]
> Would it be possible to include #5051 as well?

Unfortunately it is too late, we already cut the release :(
