### ISSUE TITLE
Consider Usage 'of' or 'by' being a list of resources instead of a single resource

### ISSUE THREAD

**Issue by lsviben** [crossplane/crossplane#5042]
### What problem are you facing?

Copied from [Slack](https://crossplane.slack.com/archives/CEG3T90A1/p1699996775424049):

> My XR has 13 instances of the problematic MR that requires deletion ordering, and each instance requires 4 different Usage resources to be deployed (one for each MR it depends on). This results in 52 different Usage resources per XR, and this is only the default behavior. Our tenants (claim users) can define (in the claim spec) additional instances of this problematic MR, which could result in 100's of Usage resources in a single XR.. multiplying that across our multiple tenants and I am foreseeing a situation where we have 1000s if not 10,000+ Usage resources in our control plane.. I am concerned this may have some performance impact and was wondering if there is any better way to go about this?

### How could Crossplane help solve your problem?

From Slack:
> A simple solution would be to allow multiple resources to be referenced/matched in the `of` block of a Usage. I was wondering if there has been any discussion or thought around this idea yet?

I quickly scanned the [design doc](https://github.com/crossplane/crossplane/blob/1271e775c925babaabf0fd9979692d32a12ff2cf/design/one-pager-generic-usage-type.md) and I couldnt find a mention of having either `of` or `by` as a list. So it seems a good topic to discuss on the road for Usages to BETA.

**Comment by negz** [comment]
We did discuss this during review: https://github.com/crossplane/crossplane/pull/4215#discussion_r1263384259
