### ISSUE TITLE
Inconsistency in Column Order Between Managed Resources and Crossplane Beta Trace Command Output

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5080]
### What happened?

**Description:**
For Example `READY and SYNCED` vs. `SYNCED and READY`:
When using the `kubectl get kubernetescluster` command, the column order for the managed resources appears as follows:

```plaintext
NAME                      READY   SYNCED   EXTERNAL-NAME             AGE
test123-aks-fg7rm-kxv2q   False   True     test123-aks-fg7rm-kxv2q   16m
```

However, when executing the `crossplane beta trace xcluster test123-aks-fg7rm` command, the column order for the resources is different:

```plaintext
NAME                                                     SYNCED   READY   STATUS                                 
XCluster/test123-aks-fg7rm                               True     False   Creating: Unready resources: cluster   
├─ RoleAssignment/test123-aks-fg7rm-4b8hz                True     True    Available                              
├─ RoleAssignment/test123-aks-fg7rm-hxkhc                True     True    Available                              
├─ XAKS/test123-aks-fg7rm-pm8js                          True     False   Creating: Unready resources: aks       
│  ├─ KubernetesCluster/test123-aks-fg7rm-kxv2q          True     False   Creating                               
│  ├─ ProviderConfig/test123-aks                         -        -                                              
│  └─ ProviderConfig/test123-aks                         -        -                                              
├─ XContainerRegistry/test123-aks-fg7rm-vb84x            True     True    Available                              
│  ├─ Registry/test123-aks-fg7rm-8sr4h                   True     True    Available                              
│  └─ MonitorDiagnosticSetting/test123-aks-fg7rm-lr54c   True     True    Available                              
├─ XIdentity/test123-aks-fg7rm-2pvp5                     True     True    Available                              
│  └─ UserAssignedIdentity/test123-aks-fg7rm-m7kpt       True     True    Available                              
├─ XMonitor/test123-aks-fg7rm-dstkj                      True     True    Available                              
│  └─ Workspace/test123-aks-fg7rm-sc9px                  True     True    Available                              
├─ XVault/test123-aks-fg7rm-nbsgp                        True     True    Available                              
│  └─ Vault/test123-aks-fg7rm-ns5nv                      True     True    Available                              
├─ Key/test123-aks-fg7rm-w7sk8                           True     True    Available                              
└─ Object/test123-aks-fg7rm-rr7r6                        True     True    Available
```

**Expected Behavior:**

The column order for resource information should be consistent between the `kubectl get` command and the `crossplane beta trace` command, ensuring a standardized and user-friendly display.

### What environment did it happen in?
Crossplane version:

**Comment by phisco** [comment]
We switched it in https://github.com/crossplane/crossplane/pull/4895 to be exactly `SYNCED READY` as that was the order for other resources. Could you provide a bit more context on the `kubernetescluster` resource? I guess it's an XRC, afaict the CRD we generate for that should have first `SYNCED` and then `READY` as `spec.versions[*].additionalPrinterColumns` as we generate them [here](https://github.com/crossplane/crossplane/blob/523c6bb8328c81874856c5055d87a5fab64b00c1/internal/xcrd/schemas.go#L391) in that order.

**Comment by phisco** [comment]
at a quick glance, it looks like most providers are setting `READY` first, e.g. all the official ones, crossplane-contrib/provider-aws. While for example `crossplane-contrib/provider-kubernetes` uses `SYNCED` first as all XR/XRCs we generate. We could technically enforce the order at establish time, but I'd say it's not worth the effort tbh. We could switch back to `READY` first as that looks like the most wide-spread option and switch XR/XRCs CRDs to use `READY` first too.

**Comment by phisco** [comment]
I agree with @bobh66, that also reflects the logic the trace subcommand uses to decide what to show as `STATUS`. For official providers it would just be a matter of a one line change [here](https://github.com/crossplane/upjet/blob/bed1fa2fdde426e6beaf61aa51f490e0303b6f17/pkg/pipeline/templates/crd_types.go.tmpl#L45), but to be sure that's the order for all resources also for other providers we could just enforce that at establish time.

**Comment by bobh66** [comment]
As another data point Crossplane uses "SYNCED  READY" for all of the Composite/Claim CRDs that it generates: 

https://github.com/crossplane/crossplane/blob/master/internal/xcrd/schemas.go#L36.

> at a quick glance, it looks like most providers are setting READY first, e.g. all the official ones, crossplane-contrib/provider-aws.

This is a result of the template that is used by code generation for the resources:

https://github.com/crossplane-contrib/provider-aws/blob/master/templates/crossplane/apis/crd.go.tpl#L63

https://github.com/crossplane/upjet/blob/main/pkg/pipeline/templates/crd_types.go.tmpl#L48

I think these should be changed to use the same "SYNCED READY" format that Crossplane is using for Claims and Composites, but I realize it could be a breaking change for some scenarios.

**Comment by bobh66** [comment]
https://github.com/crossplane/upjet/issues/359
