### ISSUE TITLE
Improving community contributions with Gitpod

### ISSUE THREAD

**Issue by pawlean** [crossplane/crossplane#5095]
### What problem are you facing?

Happy 5th birthday, Crossplane! I came across this post on LinkedIn [[1](https://www.linkedin.com/posts/crossplane_crossplane-at-5-past-present-and-future-activity-7137489816136413185-b1fM?utm_source=share&utm_medium=member_desktop)] 
and wanted to give you folks a gift from us at [Gitpod](https://www.gitpod.io) 🎂 

We recently partnered up with the Linux Foundation [[2](https://www.gitpod.io/blog/linux-foundation-gitpod-partnership)], offering **250 hours** of Gitpod's Cloud Development Environment (CDE) usage completely free as part of our Open Source Plan [[3](https://www.gitpod.io/discover/opensource)] 

As Crossplane is part of the CNCF, all your contributors are eligible for this!

## Next steps

- [ ] Configure Crossplane with a .gitpod.yml file
- [ ] Add the Open in Gitpod button in `CONTRIBUTING.md` or `README.md`

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/crossplane)

## Getting Started with Gitpod

To quickly start, open this link: [https://gitpod.io/#github.com/crossplane](https://gitpod.io/#github.com/crossplane) to create a CDE for this repository.

A [Cloud Development Environment (CDE)](https://www.gitpod.io/cde) will be created for you with your preferred editor (such as VSCode, Jetbrains, or SSH). All the necessary dependencies are automatically installed, and the crossplane source code will be pre-built according to the [.gitpod.yml](/.gitpod.yml) file, this allows you to get started in just a few seconds. 

___

Let me know if you have any questions! I also joined your community Slack, find me on there if you prefer :)

**Comment by Vrashabh-Sontakke** [comment]
I would love to work on this enhancement.

**Comment by pawlean** [comment]
> I would love to work on this enhancement.

@Vrashabh-Sontakke Awesome! Linking our Gitpod docs [here](https://www.gitpod.io/docs/introduction/getting-started) to support. Let me know if you have any questions! 🍊

**Comment by Vrashabh-Sontakke** [comment]
@pawlean I just learnt about how to setup gitpod a few days ago. 
I will soon write the .gitpod.yml file for this repo soon.

**Comment by jbw976** [comment]
>  250 hours of Gitpod's Cloud Development Environment (CDE) usage completely free as part of our Open Source Plan

what happens after these 250 hours are used up? does the CNCF pay for usage beyond that?

**Comment by Vrashabh-Sontakke** [comment]
@pawlean , I tried a lot of different .gitpod.yml configs with explicit installation of dependancies, but it looks like the "makefile" in the repo satisfies almost all dependancies after the submodule has been built.
Except, everytime I try to open a new workspace in vscode, it says "kubectl not installed, install now(button)" even when I explititely installed kubectl using .gitpod.yml config file.

**Comment by jbw976** [comment]
@pawlean can you also take a look at my question above? https://github.com/crossplane/crossplane/issues/5095#issuecomment-1881408162 🙇‍♂️

**Comment by Vrashabh-Sontakke** [comment]
@jbw976 I guess after that the user (contributer) itself would have to pay for the resource usage charges.
