### ISSUE TITLE
Package status should be constructed from the observable environment

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#510]
All status fields should be set/derived from the observable environment.

From the [Kubernetes principles doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/principles.md):
> Object status must be 100% reconstructable by observation. Any history kept must be just an optimization and not required for correct operation.

We are not following this pattern in all cases, for example in the extensions controller we are tracking a reference to a deployment: https://github.com/crossplaneio/crossplane/pull/444#discussion_r284368576

The point is made in that comment that we shouldn't be making application state and flow decisions based on object status properties, we should be making them on the observable environment instead.  If the object status is first "synced" with the observable environment, then we can make decisions based on object status (transitive).

There are other instances of this in the code base as well, such as the provider/external ID of a resource, it's endpoint, etc.  If the status is wiped out, we should be able to reconstruct them.

**Comment by jbw976** [comment]
Related to #269

**Comment by negz** [comment]
I believe this is true for all claims and managed resources (at least, all the ones that use crossplane-runtime's managed resource reconciler). @jbw976 should we keep this open for the stacks side of the world?

**Comment by jbw976** [comment]
that sounds fine @negz, the stack related controller(s) don't necessarily follow this principle fully yet.

**Comment by negz** [comment]
@hasheddan Do you think this needs to stay open to cover Packages?

**Comment by negz** [comment]
I expect this will be addressed by the [packages v2 refactor](https://github.com/crossplane/crossplane/blob/60ab1664eec970d06c28714f98dec033a99cdd6c/design/design-doc-packages-v2.md). In general it's a pattern we follow on all but the oldest controllers; I think we're okay to close this issue out despite there being a few stragglers.
