### ISSUE TITLE
Passing values in a composition to a required OpenAPI field causes an endless reconcile loop

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#5114]
### What happened?

Patching a value from one XR to another XR results via a Parent XR in an endless loop if:

1. there is a OpenAPI `required` field on the Target XR that gets a value from the parent XR status
1. the policy `fromFieldPath: Required` is not set on the Parent Composition field that patches the target XR

<img width="451" alt="image" src="https://github.com/crossplane/crossplane/assets/414702/9ad12a2b-6c45-4864-93c8-30f1b20faeed">

The below animated gif shows the behavior. Notice that even after the VPC is ready and has propagated the ID, the XTarget XR continues to report a missing field and Crossplane continually creates a new XR name.  When I add the policy (as in https://github.com/stevendborrelli/nested-xrd/blob/32a0fdcbc6e12dc980ee9c9a8be470e47c4e9475/apis/xparent/composition.yaml#L36), it will eventually resolve.

![626229](https://github.com/crossplane/crossplane/assets/414702/efeb4a3e-0f46-4522-a678-2250cbab9794)

### How can we reproduce it?

Install the composite in https://github.com/stevendborrelli/nested-xrd, set up a default AWS providerconfig and provision `examples/xparent.yaml`

### What environment did it happen in?

* Crossplane version: UXP 1.14.5
* Cloud provider or hardware configuration: Crossplane/Upbound provider-aws v0.47.1
* Kubernetes version (use `kubectl version`) 1.27.1
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) Kind

**Comment by stevendborrelli** [comment]
I'm aware of several organizations this issue has affected.

Further testing:

- `--enable-realtime-compositions` does not affect the behavior
- to work around the issue, setting a `fromFieldPath: Required` policy on the patch from `XParent` -> `XTarget` seems to work immediately. 

```yaml
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: status.vpcid
        toFieldPath: spec.parameters.vpcid
        policy:
          fromFieldPath: Required
```

**Comment by phisco** [comment]
https://github.com/crossplane/crossplane/pull/5365 would make this work at some point if the composition eventually produced a valid composed resource, I'll split the "endless reconcile loop" in case of non transient error part to https://github.com/crossplane/crossplane/issues/5007.
