### ISSUE TITLE
A composition can update existing managed resource

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#5122]
### What happened?

Managed (composed) resource names are generated randomly and their availability are checked by [a read request against API server](https://github.com/crossplane/crossplane/blob/master/internal/names/generate.go#L91).

A new managed resource is created by sending patch request to API server and if the resource does not exist, it going to be created; otherwise updated.

When user creates a new claim/composite, it might happen that the generated name is taken at the time when we submit the patch request for the new managed resource. As the consequence, another existing managed resource would be updated, i.e. hijacked.

The issue could remain uncovered for a long time, and its impact depends on the environment and its context.

### How can we reproduce it?

The probability of such event is low and thus cannot be reproduced deterministically.

### What environment did it happen in?

All supported Crossplane versions use the same logic.

**Comment by negz** [comment]
Don't we set controller references, which should prevent this?

* When not using functions our applicators have an option that checks controller references.
* When using functions (and thus SSA), I'm 99% sure that a patch will fail if it tries to change the controller reference.

I recall validating that SSA rejects attempts to change a controller reference a while ago.
