### ISSUE TITLE
Failed calling webhook: address is not allowed

### ISSUE THREAD

**Issue by nc-rajeshnair** [crossplane/crossplane#5125]
**ERROR**
`Sync operation to 861dbc4af219cce36a647efe23559d179b082220 failed: one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "compositeresourcedefinitions.apiextensions.crossplane.io": failed to call webhook: Post "https://crossplane-webhooks.upbound-system.svc:9443/validate-apiextensions-crossplane-io-v1-compositeresourcedefinition?timeout=10s": Address is not allowed (retried 5 times).`

**Comment by phisco** [comment]
Looks like an issue with the CNI. We'd need a bit more information about your Cluster.
Is it a managed service, GKE, EKS, AKS?
What CNI are you using?
Do you have Istio installed?
Do you have NetworkPolicies in place that might prevent the traffic from the Control Plane Nodes to Crossplane?

If you have other operators with a `ValidatingWebhookConfiguration` or `MutatingWebhookConfiguration`, and they work properly, I'd suggest you to check what's different between those and Crossplane's pod/namespace.
