### ISSUE TITLE
Updating a Claim triggers the creation of a NEW composite resource instead of updating it

### ISSUE THREAD

**Issue by nello1992** [crossplane/crossplane#5138]
### What happened?
Hi folks, I'm having some issues when I update and re-apply a Claim manifest into the cluster.

I have an XCluster xrd with its Composition that includes more composed and managed resources. The Claim used to trigger the instantiation of a XCluster resource creates an instance of it correctly, named as claimName-autogeneratedsuffix (e.g cluster-test-ir2k5.

At some point I need to update XCluster xrd and/or the related Composition with more fields. Then, I update the Claim manifest by setting values for these new fields and apply it into the cluster. Crossplane creates one more XCluster composite resource (call it cluster-test-kw0j1). I expected that it would update the existing one to which it was bound to, but what happens is that the claim unbinds from the previous xcluster instance and binds to the new.

In this way I loose the binding to the old composite resource and for this reason, all future updates to the claim do not propagate to it and cannot either remove the old one by deleting the claim.

How do I keep the binding between Claim - Composite Resource without triggering the creation of a new composite resource? I saw that it is not possibile to set a fixed name for the XR, but only to the managed resource using external-name annotation or metadata.name

### How can we reproduce it?
1. Create a Claim (call it cluster-test) that instantiate an XR (call XRD as XCluster). It generates an xcluster composite resource called "cluster-test-<suffix>" (e.g. cluster-test-k3js4).

2. Add some fields to the XR and set them in the Claim manifest
3. Update the claim with new fields 
4. Crossplane creates a NEW xcluster composite resource  called "cluster-test-<suffix>" (e.g. cluster-test-o7px1) instead of updating  cluster-test-k3js4

### What environment did it happen in?
Crossplane version: 1.14.3

**Comment by bobh66** [comment]
This can happen if the changes are applied using `kubectl replace` instead of `kubectl apply` because the original claim is replaced and it loses track of the existing Composite.  We have seen this with ArgoCD when the Application is configured to use `replace` instead of `apply`.

**Comment by nello1992** [comment]
oh I see! I apply it using FluxCD, is there a way to avoid replacing it?

**Comment by bobh66** [comment]
I'm not familiar with FluxCD but the documentation seems to imply that they have support for Server Side Apply in 2.0+ which should mitigate the problem, if this is the cause.  You might try a test outside of Flux to verify that you can`kubectl apply` the change to the claim without seeing the problem occur.

**Comment by pedjak** [comment]
If a claim gets replaced, then the counterpart composite and all MRs will be removed as well - it is the expected behavior.

**Comment by pedjak** [comment]
@nello1992 can we close this issue?

**Comment by nello1992** [comment]
Thanks guys!

**Comment by nello1992** [comment]
Thanks guys
