### ISSUE TITLE
Providers and Functions are constantly reconciled on OpenShift because the ServiceAccount imagePullSecret is modified

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#5142]
Slack discussion:  https://crossplane.slack.com/archives/CEG3T90A1/p1701165506306089?thread_ts=1701096709.193549&cid=CEG3T90A1

### What happened?
Crossplane is constantly reconciling the providers and functions when deployed on OpenShift because the ServiceAccount `imagePullSecrets` field is constantly being modified by a webhook:

https://github.com/openshift/openshift-controller-manager/blob/2a28a78279b127075b399a3442a2042f4a7d190d/pkg/serviceaccounts/controllers/create_dockercfg_secrets.go#L315-L400

### How can we reproduce it?
Deploy providers/functions on OpenShift

Run `kubectl get sa -n crossplane-system -w` and observe that the service accounts for the providers and functions are continuously modified.

### What environment did it happen in?
Crossplane version: 1.14.4

* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) OpenShift

**Comment by phisco** [comment]
FYI: tried it out, and unfortunately switching to Server Side Apply won't help here, as the SA's imagePullSecret list is fully replaced.
