### ISSUE TITLE
(functions): Infer readiness of a composite resource creating 0 composed resource 

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#5146]
### What happened?

I'm currently migrating my old functions to the new functions and I have a composition which can create a range of 0 to X resources. In the case of X === 0, I can't specify readiness of (the non existing) composed resource, so crossplane can't infer the readiness of composite and it stays unready.

I think Crossplane should mark a composition as ready if it does not create composite resources, or we should at least have a way to tell Crossplane it is okay if a composition create no resources. 

### How can we reproduce it?

Create a composition using functions and return 0 desired resources from it.

### What environment did it happen in?
Crossplane version: 1.14.4

**Comment by phisco** [comment]
AFAICT reading the code it should already mark as ready the XR when no resources are returned by a function, can you share an example Composition?
