### ISSUE TITLE
`--wait` flag on package install doesn't do anything when the wait timeout expires before the package is healthy

### ISSUE THREAD

**Issue by djeremiah** [crossplane/crossplane#5149]
### What happened?
https://docs.crossplane.io/v1.14/cli/command-reference/#wait-for-package-install says that `--wait` will error out if the timeout is hit before the package becomes healthy. This is not true. It just stops waiting and reports success, whether the package is healthy or not.

### How can we reproduce it?
Install a configuration package with a large number of dependencies. The package won't report healthy until all of the dependencies are installed, but the install command will exit anyway.
```bash
crossplane xpkg install configuration ghcr.io/back-stack/showcase-configuration:latest --wait=30s && kubectl get configuration

NAME                                INSTALLED   HEALTHY   PACKAGE                                            AGE
back-stack-showcase-configuration   True        Unknown   ghcr.io/back-stack/showcase-configuration:latest   30s
```

I would expect the command to error out, as described in the docs.

### What environment did it happen in?
Crossplane version: 
1.14.4-up.1

kind v0.20.0 go1.20.5 darwin/arm64 
Client Version: v1.28.4
Server Version: v1.27.3

**Comment by phisco** [comment]
Indeed, the flag help message doesn't mention failure, so there is indeed a mismatch with the documentation, so this should either be a bug for the documentation or an enhancement for the CLI.

Looking at other tools:
- Helm does return `exit code 1` when an `helm upgrade|install --wait --timeout ...` hits the configured timeout
- same goes for `kubectl wait --timeout` which

So, I'd say it would make sense to error out here too, as it doesn't make sense to wait at all if in the end I'm not sure whether the resource was successfully installed or not.
