### ISSUE TITLE
Some composition errors are not written in composite status 

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#5150]
### What happened?

Some errors are not written to composite status, so we have no feedback from crossplane if we don't read crossplane pod debug logs. It happens at least with what seems to be server side apply issues like this one:

````
2023-12-19T14:10:35Z    DEBUG    crossplane    Event(v1.ObjectReference{Kind:"XBootstrap", Namespace:"", Name:"admin", UID:"", APIVersion:"platform.crossplane.airnity.net/v1alpha1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'ComposeResources' cannot compose resources: cannot apply composite resource status: XBootstrap.platform.crossplane.airnity.net "admin" is invalid: result.prefixList: Invalid value: "null": result.prefixList in body must be of type object: "null"
````

### How can we reproduce it?

Create a composed resource with something susceptible of breaking server side apply: wrong field type, a field not referenced in CRD,...   

I don't know if it only happens with functions pipeline mode.

### What environment did it happen in?
Crossplane version: 1.14.4

**Comment by phisco** [comment]
the same log should be available as Event attached to the XBootstrap `admin` resource.

**Comment by duizabojul** [comment]
Why is this not written in resource status thought? In argoCD, it result in a resource with no error status, just hanging there.

**Comment by phisco** [comment]
might have been solved by https://github.com/crossplane/crossplane/issues/5105, this specific error event was not linked to the composite resource due to a bug, if in Argo you can see events similar to what happens with `kubectl describe` and you didn't mean you were expecting it to be shown as a condition.

**Comment by duizabojul** [comment]
I was expecting to see this error in conditions yes. Just to understand, why this error is not shown in conditions?

**Comment by phisco** [comment]
It should actually be set as a condition message for the XR too.
