### ISSUE TITLE
Offline Schema Validation for Crossplane resources

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#5162]
### What problem are you facing?

To expedite the composition development cycle, we can introduce a new subcommand, `validate` to the Crossplane CLI. Instead of relying on a live cluster, we can initiate the OpenAPI schema validation process offline using the API server's validation library. Later, we can improve the command with live cluster support to enhance its UX and capabilities. Please see the following issues for further discussion:
- https://github.com/crossplane/crossplane/issues/4976
- https://github.com/crossplane/crossplane/issues/4996

The offline schema validation should be able to check resource schemas against the XRDs and CRDs without the need for a cluster. Developers can receive feedback on the correctness of their resource manifests before deploying them, which ensures a smoother and more efficient development cycle.

Since we want to support offline validation, in addition to the resource manifests, users need to provide the schemas as well. These schemas can be obtained with a simple script that downloads provider images and combines CRDs in a single file called `schemas.yaml`. Later, this file can be passed to the `validate` command like below:
```
./download-crds.sh xpkg.upbound.io/upbound/provider-aws-iam:v0.46.1,xpkg.upbound.io/upbound/provider-aws-s3:v0.46.1 
crossplane beta validate schemas.yaml resources.yaml
```

To have a smooth integration with `crossplane beta render` command, the `validate` command may also get resource manifests through standard input. 

```
crossplane beta render xr.yaml composition.yaml functions.yaml | crossplane beta validate schemas.yaml -  
```

One thing worth mentioning here is that since Crossplane functions are not allowed to update XR spec fields, the output of the render command always contains an XR resource without spec which will cause schema validation failure. To prevent this, we may implement one of the following proposals below:
- Update the render command to output both the spec and status fields. 
- Add `--skip-xr-validation` flag to skip XR validation while using the `validate` command with rendered output. 
- Combine multiple instances of the same resource in the `resources.yaml` file and ask users to append the `xr.yaml` 
to their `resources.yaml` file. 

### How could Crossplane help solve your problem?

Introduce `validate` command to validate OpenAPI schemas offline. 

### Related issues

* https://github.com/crossplane/crossplane/issues/4673

**Comment by phisco** [comment]
Thanks @ezgidemirel, this would definitely be an awesome addition!

One minor comment about the arguments, I'd allow specifying a directory too instead of just  a single file, so that one wouldn't have to flatten them. We could even think of allowing specifying an URL too, similar to what kubectl does, but that could definitely be a later addition.

**Comment by ezgidemirel** [comment]
> Thanks @ezgidemirel, this would definitely be an awesome addition!
> 
> One minor comment about the arguments, I'd allow specifying a directory too instead of just a single file, so that one wouldn't have to flatten them. We could even think of allowing specifying an URL too, similar to what kubectl does, but that could definitely be a later addition.

Thanks @phisco for the suggestion! I forgot to update the issue. But I already implemented the folder support in addition to standard input and file.

**Comment by jbw976** [comment]
This will be very helpful to improve the authoring experience in v1.15 @ezgidemirel! I like the direction you are heading 💪 

A few thoughts:

* A key principle that will guide our design here will be trying to ensure the user gets the command right and complete the first time they run it. What feels most natural for them (principle of least surprise) and what are smart defaults that we can use to streamline the mainline scenarios? Keep that in mind as you continue implementing 🙏 
* I like this direction to split `validate` into its own command instead of extending `render` with validation. This will allow validation to work independently and will keep the surface area of `render` from getting too complicated.
* I'm fine with your first option of "Update the render command to output both the spec and status fields."
* Great idea to streamline how folks get their schemas ready, if that was a manual process it would likely be error prone and some folks would not get to success
  * any reason for us to provide a download script instead of a subcommand to do that to keep the experience consistent? e.g. `validate download`, `validate load-schema` or something like that?
* Remember the desire we have for a common/core validation library that this command, as well as other validation experiences, can be built on top of 🤓 
  * https://github.com/crossplane/crossplane/issues/4996#issuecomment-1867096012

**Comment by haarchri** [comment]
A few thoughts:

> Since we want to support offline validation, in addition to the resource manifests, users need to provide the schemas as well. These schemas can be obtained with a simple script that downloads provider images and combines CRDs in a single file called schemas.yaml. Later, this file can be passed to the validate command like below:

- Parses the crossplane.yaml file to extract provider names and versions
- Clones the corresponding GitHub repositories for each provider version / extract CRDs from image (xpkg)

small bash version:
```
#!/bin/bash

# Path to crossplane.yaml
crossplane_yaml_path="crossplane.yaml"

# Array to track processed providers
processed_providers=()

# Function to check if a provider has been processed
provider_processed() {
  local provider="$1"
  for processed_provider in "${processed_providers[@]}"; do
    if [ "$processed_provider" == "$provider" ]; then
      return 0  # Provider has been processed
    fi
  done
  return 1  # Provider has not been processed
}

# Function to perform git clone
git_clone() {
  local provider="$1"
  local version="$2"

  # Extract org and repo from provider name
  local org_and_repo="${provider#xpkg.upbound.io/}"
  if echo "$org_and_repo" | grep -q '/.*-.*-'; then
    org_and_repo=$(echo "$org_and_repo" | sed 's/\(.*\)-.*/\1/')
  fi

  local repo_url="https://github.com/${org_and_repo}.git"
  local tag="${version}"

  # Check if the directory already exists or the provider has been processed
  if [ ! -d "${provider}" ] && ! provider_processed "${provider}"; then
    git clone --branch "${tag}" "${repo_url}"  > /dev/null 2>&1
    processed_providers+=("$provider")
  fi
}

# Extract providers and versions using yq
providers=($(yq eval '.spec.dependsOn[] | select(has("provider")) | .provider' "${crossplane_yaml_path}"))
versions=($(yq eval '.spec.dependsOn[] | select(has("provider")) | .version' "${crossplane_yaml_path}"))
# Iterate through providers and versions
for ((i = 0; i < ${#providers[@]}; i++)); do
  provider="${providers[i]}"
  version="${versions[i]}"
  # Extract only the provider name
  provider_name=$(echo "${provider}" | awk -F/ '{print $NF}')
  # Check if the provider has "family" in its name
  if [[ ! "${provider_name}" =~ family ]]; then
    git_clone "${provider}" "${version}"
  fi
done
```

- possible usage of https://github.com/yannh/kubeconform

```
#!/bin/bash
SCHEMAS_DIR="schemas"
CONVERTER_SCRIPT_URL="https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py"

# Download converter script
curl "$CONVERTER_SCRIPT_URL" --output openapi2jsonschema.py 2>/dev/null
rm -r $SCHEMAS_DIR
mkdir $SCHEMAS_DIR
# Iterate over provider folders
for provider_folder in provider-*; do
  if [ -d "$provider_folder" ]; then
     python3 openapi2jsonschema.py $provider_folder/package/crds/*.yaml  > /dev/null 2>&1
  fi
done
```

```
crossplane beta render xr.yaml composition.yaml functions.yaml | | kubeconform -summary -schema-location default -schema-location 'schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'
```
output looks like:

```
stdin - SecurityGroupRule ref-aws-network-{{ generateName }} is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/forProvider/cidrBlocks' does not validate with file:///Users/haarchri/Documents/conform/schemas/securitygrouprule_v1beta1.json#/properties/spec/properties/forProvider/properties/cidrBlocks/type: expected array, but got string

Summary: 17 resources found parsing stdin - Valid: 16, Invalid: 1, Errors: 0, Skipped: 0
```

- generate CRDs from XRDs without a cluster

move the following internal functions to public (ref: https://github.com/haarchri/x-gentest/blob/main/main.go):
https://github.com/crossplane/crossplane/blob/master/internal/xcrd/crd.go
https://github.com/crossplane/crossplane/blob/master/internal/xcrd/schemas.go

```
crossplane beta crd definition.yaml 
```

**Comment by negz** [comment]
Some thoughts:

* OpenAPI schema validation is only part of the picture. It's a large part, but passing OpenAPI schema validation doesn't mean your resource will actually work. For example it could be rejected by an admission control webhook, or validation code in the reconciler.
* Is it possible to support `x-kubernetes-` OpenAPI extensions? Is it worth it?
* I'd like to avoid framing this around CRDs. Ideally you would tell the validate command what extensions (providers, configurations, maybe XRDs directly) that it needed. Frame it around Crossplane concepts, not Kubernetes concepts. Related: https://github.com/crossplane/crossplane/issues/2262

**Comment by ezgidemirel** [comment]
Thanks @haarchri for your comment! I was planning to extract the CRDs from the provider image instead of downloading them from the Git repo. The bash script version of it is below:
```
#!/usr/bin/env bash

set -aeuo pipefail

id=$(docker create xpkg.upbound.io/upbound/provider-aws-iam:v0.45.0)
docker cp $id:package.yaml package.yaml
docker rm -v $id

```

I considered to have a similar approach for configurations as well with provider version extraction from `crossplane.yaml` file. But then I noticed that people usually do not maintain the constraint versions there, and using an older provider version may cause schema validator differences. 

What I'm currently planning is getting a `config.json` file like below:

```
{
    "providers":[
        "xpkg.upbound.io/upbound/provider-aws-iam:v0.45.0",
        "xpkg.upbound.io/upbound/provider-aws-s3:v0.45.0"
    ],
    "configurations":[
        "xpkg.upbound.io/upbound/platform-ref-aws:v0.9.0"
    ]
}
```
or directly as arguments:
```
./crossplane-cli beta download-schemas --providers=xpkg.upbound.io/upbound/provider-aws-iam:v0.45.0,xpkg.upbound.io/upbound/provider-aws-s3:v0.45.0 --configurations=xpkg.upbound.io/upbound/platform-ref-aws:v0.9.0
```

Another alternative might be getting a `providers.yaml` file with a bunch of provider manifests.

**Comment by ezgidemirel** [comment]
Thanks for your comment @negz! My answers are inline: 
> Some thoughts:
> 
> * OpenAPI schema validation is only part of the picture. It's a large part, but passing OpenAPI schema validation doesn't mean your resource will actually work. For example it could be rejected by an admission control webhook, or validation code in the reconciler.

I agree that offline validation is not as powerful as online one. But our primary motivation here is providing a tool to composition authors that can give early feedback even before they create a cluster with Crossplane.   

> * I'd like to avoid framing this around CRDs. Ideally you would tell the validate command what extensions (providers, configurations, maybe XRDs directly) that it needed. Frame it around Crossplane concepts, not Kubernetes concepts. Related: [Introduce a ManagedResourceDefinition type? #2262](https://github.com/crossplane/crossplane/issues/2262)

This will definitely make the command more powerful and extensible. This suggests combining the `download` mechanism with the `validate` subcommand. I implemented the initial version [here](https://github.com/crossplane/crossplane/pull/5197) with schema input. But I'm ok to change it with this approach.
