### ISSUE TITLE
[provider] Hetzner, Oracle

### ISSUE THREAD

**Issue by zs-dima** [crossplane/crossplane#5173]
It would be nice to add popular providers, such as Hetzner or Oracle.
https://www.hetzner.com/
https://www.oracle.com/cloud/

**Comment by sshiv5768** [comment]
Hey, @jbw976 I want to work on this issue. Can you assign me this issue?

**Comment by bobh66** [comment]
This might be relevant for OCI:  https://github.com/oracle-samples/crossplane-provider-oci

**Comment by bobh66** [comment]
Also I would probably split this into two issues so that the two separate providers can be tracked independently.

**Comment by negz** [comment]
Thanks @zs-dima for the suggestions.

Unfortunately we don't have enough maintainers to field requests for new providers. We do encourage the community to give building a provider a try. I've started a discussion at https://github.com/crossplane/crossplane/discussions/5194 with some links to guides on building a provider.

There's no need to raise or assign issues for new providers. Anyone is welcome to create one in their own GitHub organization! Once the provider is working, we're happy to move it to @crossplane-contrib if you would like (or it can stay in your org!).
