### ISSUE TITLE
Crossplane trace - (optionally) print composition resource name for composed resources

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#5188]
### What problem are you facing?

With the beta trace command, we print the `NAME`, `SYNCED`, `READY` and `STATUS` columns where name is in the format of `<KIND>/<METADATA.NAME>`. This is usually helpful when there are not more than a single KIND in a given composition and XR has a descriptive name. However, it lacks of enough context when there are more than one of a KIND. As an example, I have the following trace output where a couple of Helm `Releases` and Kubernetes `Objects` are composed.

```shell
NAME                                                        SYNCED   READY   STATUS
XTopLevelComposite/626bea51-e6f9-427f-b13c-a039c91840ec     True     True    Available
├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-bxkd8        True     True    Available
├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-qf5ph        True     True    Available
├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-gmk5w        True     True    Available
├─ XNestedComposite/626bea51-e6f9-427f-b13c-a039c91840ec    True     True    Available
│  ├─ Release/626bea51-e6f9-427f-b13c-a039c91840ec-5snr9    True     True    Available
│  ├─ Release/626bea51-e6f9-427f-b13c-a039c91840ec-kcfk8    True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-4v68g     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-5l2j8     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-bbclp     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-k4r42     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-lqmpg     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-nbdgz     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-tbccn     True     True    Available
│  ├─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-tg7t7     True     True    Available
│  └─ Object/626bea51-e6f9-427f-b13c-a039c91840ec-wv7pq     True     True    Available
```

### How could Crossplane help solve your problem?

Every composed [resource](https://docs.crossplane.io/v1.14/concepts/compositions/#resource-templates) in a composition has a unique `name` which identifies the resources within the composition. It would be super helpful if we could include this information somehow. It could be added as an additional column (preferably printed with `-o wide`) or added in parenthesis next to each composed resource name.

**Comment by bobh66** [comment]
This would be a good first step for the Slack discussion - https://crossplane.slack.com/archives/C05U1LLM3B2/p1701964369745419

Displaying the actual Object name and either the Release name or the Helm chart name would make the trace a lot more useful.

**Comment by jbw976** [comment]
Good feedback @gtfortytwo! @phisco went ahead and updated the CLI help output with https://github.com/crossplane/crossplane/pull/5642, and @tr0njavolta opened https://github.com/crossplane/docs/issues/763 to track your suggestion in docs.crossplane.io 🙇‍♂️
