### ISSUE TITLE
provider-azure bootDiagnostics for VM not working

### ISSUE THREAD

**Issue by techny210** [crossplane/crossplane#5192]
### What happened?

VM can't be created from a simple k apply -f vm.yaml  , it errors out with the following:
LinuxVirtualMachine in version "v1beta1" cannot be handled as a LinuxVirtualMachine: strict decoding error: unknown field "spec.forProvider.bootDiagnostics.storageAccountUri"

### How can we reproduce it?

Create a vm with bootDiagnostics enabled
### What environment did it happen in?
Crossplane version: 
latest  1.14.5

kube vesion 1.28.3 on microk8s Ubuntu 22.04 LTS

apiVersion: compute.azure.upbound.io/v1beta1
kind: LinuxVirtualMachine

it is set correctly but for some reason, API does not recognize it as such
API docs on the website clearly show this option

bootDiagnostics:
    storageAccountUri:

 k get providers
NAME                            INSTALLED   HEALTHY   PACKAGE                                                     AGE
provider-azure-compute          True        True      xpkg.upbound.io/upbound/provider-azure-compute:v0.40.0      8d
provider-azure-storage          True        True      xpkg.upbound.io/upbound/provider-azure-storage:v0.40.0      8d

**Comment by jeanduplessis** [comment]
@techny210 Could you please open this issue on https://github.com/upbound/provider-azure as it isn't related to core Crossplane.
