### ISSUE TITLE
Usage causes exponential backoff in deletion up to 15 minutes

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#5193]
When enabling Usages on resources that take a long time to delete (like Databases or K8s Clusters), exponential backoff can cause dependent resources to wait up to 1000 seconds between deletion attempts.           
              

>   In my local implementation of this feature using a kopf operator we see this same problem - it's caused by the garbage collector doing an exponential backoff on the delete retries that maxes out at 1000 seconds (16+ minutes).  So when you have something that takes a long time to delete the GC backoff will make it even longer.
> 
> I worked around this by explicitly retrying the delete on the "protected" resource when the dependency/usage itself is successfully deleted (the webhook determines that the Usage is no longer required).  That seems to speed things up significantly.
> 
> I think we discussed this in the original implementation and decided to defer any solution until we had some data on how it was actually working.  Explicitly retrying the delete feels risky, but if the resource is already marked for deletion (which it should be) then forcing GC to retry again sooner than it's backoff period should not cause any issues.
> 

_Originally posted by @bobh66 in https://github.com/crossplane/crossplane/issues/4622#issuecomment-1875551043_

**Comment by turkenh** [comment]
This is a known issue and we couldn't found any elegant solution (yet). This was heavily discussed in the original design: https://github.com/crossplane/crossplane/pull/4215#discussion_r1235321146

**Comment by turkenh** [comment]
Fixed with https://github.com/crossplane/crossplane/pull/5394
