### ISSUE TITLE
Allow Providers Deployments to be managed with VPA

### ISSUE THREAD

**Issue by mcanevet** [crossplane/crossplane#5230]
### What problem are you facing?

It's currently not possible to configure VPA to automatically adapt memory and cpu usage of providers because the name of the `Deployment` is not predictable (see [this issue](https://github.com/kubernetes/autoscaler/issues/6385)).

### How could Crossplane help solve your problem?

One [proposed solution](https://github.com/kubernetes/autoscaler/issues/6385#issuecomment-1886792423), as described [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-apply-vpa-to-my-custom-resource), is to [enable scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) in the CRD.
This should allow usage of the Provider resource as target of the VPA.

**Comment by phisco** [comment]
Unfortunately there is no way to configure the scale sub-resource in the `Provider` CRD, the number of replicas is dictated by the `ControllerConfig` or `RuntimeConfig` referenced by the `Provider`.

**Comment by negz** [comment]
I'm pretty sure you can use the beta DeploymentRuntimeConfig feature to set a predictable deployment name. Try setting `deploymentTemplate.metadata.name`: https://docs.crossplane.io/v1.14/concepts/providers/#runtime-configuration.

I don't think we should add a scale subresource to the Provider type. We don't want to assume that providers will always be deployed as Kubernetes pods/deployments.
