### ISSUE TITLE
Render function error lacks filename

### ISSUE THREAD

**Issue by sttts** [crossplane/crossplane#5250]
### What happened?

```
crossplane-cli-v1.14.5 beta render cluster/local/composition-render/mxp-control-plane/kube-control-plane/vcluster/xr.yaml cluster/xpkgs/mxp-control-plane/kube-control-plane/vcluster/composition.yaml cluster/local/composition-render/functions.yaml -o cluster/local/composition-render/mxp-control-plane/kube-control-plane/vcluster/observed.yaml
```

gives this output:

```
crossplane: error: cannot render composite resource: pipeline step "render-composed-resources" returned a fatal result: invalid function input: cannot parse the provided templates: template: manifests:606: bad character U+005B '['
```

The output does not say which manifest.

### How can we reproduce it?

With the commands above and some template with a go-template error.

### What environment did it happen in?
Crossplane version: 1.14.5

**Comment by turkenh** [comment]
+1. The line number is also misleading, looks like it is the number in combined manifest from all template files. 

However, this needs to be resolved in the function implementation, not in Crossplane. @sttts would you mind opening this in the https://github.com/crossplane-contrib/function-go-templating repo instead?

**Comment by sttts** [comment]
Moved to https://github.com/crossplane-contrib/function-go-templating/issues/61.
