### ISSUE TITLE
Crossplane Admin does not have permissions on Claim/Composite status subresources

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#5262]
### What happened?

As a [Crossplane Admin](https://github.com/crossplane/crossplane/blob/c45ba3488a8899bac2caa02501c77c8b6f9d45ac/cluster/charts/crossplane/templates/rbac-manager-managed-clusterroles.yaml#L6), I cannot patch/update status subresource for claims or composites. This is because the ClusterRole (e.g. `crossplane:composite:xclusters.aws.platformref.upbound.io:aggregate-to-edit`) aggregating with `rbac.crossplane.io/aggregate-to-edit` and `rbac.crossplane.io/aggregate-to-admin` does not include permissions on the status subresource. It is only included in the ClusterRole with the `rbac.crossplane.io/aggregate-to-crossplane` label (e.g. `crossplane:composite:xclusters.aws.platformref.upbound.io:aggregate-to-crossplane`). 

This is different than managed resources, e.g. `crossplane:provider:crossplane-contrib-provider-helm-b4cc4c2c8db3:aggregate-to-edit`, already includes the permissions on the status subresource.

#### But why do I need this permission?

I would like to restore Crossplane state that I have backed up from another Crossplane installation. Roughly, I am following the below steps:

1. Restore all providers/configurations.
2. Restore all managed resources with paused annotations.
3. Restore all composites/claims with paused annotations.
4. Remove paused annotation from claims/composites.

After the 4th step, I expect all composites to generate the same composed resources and take ownership of them. However, if the composition logic includes some dependency on the status of a composed resource, during its absence, it does not output an already existing composed resource, and the composition pipeline decides to remove its references from `spec.resourceRef` assuming the pipeline decided to delete it. So, before removing paused annotations, I need to make sure all data including the status restored.

### How can we reproduce it?

Install platform-ref-aws and check the clusterroles mentioned above.

### What environment did it happen in?

Crossplane version: 1.14.3

**Comment by negz** [comment]
Generally RBAC roles intended for humans don't have access to write status, do they? Writing status is a controller's job.

**Comment by turkenh** [comment]
> Generally RBAC roles intended for humans don't have access to write status, do they? Writing status is a controller's job.
> 
> 
> 
> So, I don't remember specifically but I would imagine this was by design.

I agree. But two problems:

1. In the scenario mentioned above, we need to restore status and I believe it could be considered as a task of a Crossplane admin.
2. There is already inconsistency, permissions granted for managed resource statuses but no composites/claims.

**Comment by negz** [comment]
> In the scenario mentioned above, we need to restore status and I believe it could be considered as a task of a Crossplane admin.

Aren't you generally not supposed to rely on/backup status?

> There is already inconsistency, permissions granted for managed resource statuses but no composites/claims.

Do you know why that is? Was it intentional or an oversight.

FWIW this isn't a hill I'm going to die on. We can let the admin role have this permission if it makes life easier. It does smell a bit like an anti pattern though.

**Comment by turkenh** [comment]
> Aren't you generally not supposed to rely on/backup status?

Yes. This was what I was expecting so far, but realized that we need them after some recent work. I've explained the reasoning above, quoting again:

> However, if the composition logic includes some dependency on the status of a composed resource, during its absence, it does not output an already existing composed resource, and the composition pipeline decides to remove its references from spec.resourceRef assuming the pipeline decided to delete it. So, before removing paused annotations, I need to make sure all data including the status restored.

I've observed this behavior while working with platform-ref-aws. I noticed duplicated/leaked nested composites after restoration eventually leaking managed resources.  I suspect that [this line](https://github.com/upbound/platform-ref-aws/blob/e5d15551795ebde328c443c5da22d8e25c485831/apis/cluster/composition.yaml#L39-L42) could be related.

To make this more concrete, just prepared an MVP to reproduce the issue: https://github.com/turkenh/crossplane-restore-needs-status

> Do you know why that is? Was it intentional or an oversight.

> FWIW this isn't a hill I'm going to die on. We can let the admin role have this permission if it makes life easier. It does smell a bit like an anti pattern though.

No, I don't remember. But I totally agree that this feels like an anti-pattern and if I were the one who implemented it, I would do the same. 
To date, I have always thought about restoring the spec and expecting reconcilers to reconstruct the status. However, it turned out that the composition pipeline, when depending on some statuses, may produce different outputs causing a possibility of leakage. Could that be solved instead? I am not sure. Because from Crossplane POV, the pipeline step didn't return a previously composed resource. So, I don't think there is a way to differentiate whether the step wants to delete it or it is missing just because a required status is not available yet.

**Comment by bobh66** [comment]
Is there maybe a procedural workaround where you first unpause all of the MRs so that their status fields get updated, and then working up the tree from the MRs unpause each of the Composites so they can pick up the status info from their children?  This would be a lot of extra manual work but seems like it could be automated fairly easily - start with the claim/top-level composite, walk down the tree to find all of the MRs and unpause them, wait for them to be reconciled at least once, then work backwards un-pausing composites and waiting for them to reconcile before continuing up the tree.

It seems like maybe even if the status is restored from backup it could still change and trigger redeployments/updates of resources depending on the types of MRs that are in use - granted that it "should" be the same I can imagine scenarios where it isn't and you might always get an update/redeployment of a resource.

**Comment by negz** [comment]
> However, if the composition logic includes some dependency on the status of a composed resource, during its absence, it does not output an already existing composed resource, and the composition pipeline decides to remove its references from spec.resourceRef assuming the pipeline decided to delete it.

Got it. This sounds similar to https://github.com/crossplane-contrib/function-patch-and-transform/issues/70, which I happen to be trying to fix at the moment. The plan is that to treat required field paths as a create-time only concern. So if a required status field was absent, but the resource being patched already existed, we'd just skip the patch. So we'd essentially treat the required field path as an optional field path.

Is there any chance fixing this in function-pandt would be good enough? Or are other functions subject to this issue?

**Comment by turkenh** [comment]
> Is there any chance fixing this in function-pandt would be good enough? Or are other functions subject to this issue?

I just tried my repro steps with the latest function-pandit and can confirm that I don't reproduce the behavior. 

However, I feel like it would be a more "reliable" restoration if/once we restore everything, including the status. This way, we can be immune to situations where composition logic relies on the status, which is pretty common.

> FWIW this isn't a hill I'm going to die on. We can let the admin role have this permission if it makes life easier. It does smell a bit like an anti pattern though.

Assuming this is still the case, I'll open a PR :)
