### ISSUE TITLE
Handle package deletion safely

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#527]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** When an `Extension` is being deleted, we do not currently take into account if any of the resources that `Extension` manages are still in use.  We just blindly delete the controller and CRDs for the `Extension`.  For example, if the Gitlab extension is running and has created an instance of Gitlab, we should be careful about deleting the Gitlab extension while the the instance of the Gitlab resource is still deployed and in use.

**What is use case behind this feature:** If we remove the managing controller for a resource while that resource is still deployed, there will be no more support for that resource, it's somewhat orphaned (it has no controller to manage it).  We should think through the best way to handle this:
* do we block the deletion of the extension until all resources that it manages are also deleted?
* do we automatically delete all the resources and then delete the extension as well (i.e. interpret that deleting the extension means the user really wants everything to do with it cleaned up)
* do we define policies that give the user some choice in how this situation is handled?

**Comment by negz** [comment]
@hasheddan Is this still relevant under the v2 packages implementation?

**Comment by hasheddan** [comment]
@negz sort of.. though I think #1732 is more reflective of current state

**Comment by negz** [comment]
@hasheddan I thought that might be the case. I'll close this and we can track in #1732.
