### ISSUE TITLE
Crank incompatible with docker > 24

### ISSUE THREAD

**Issue by wejdross** [crossplane/crossplane#5321]
```
go run github.com/crossplane/crossplane/cmd/crank xpkg build -f package --verbose --embed-runtime-image=ghcr.io/abc/abc -o package/package-function-abc.xpkg
```

If we run this command using docker-ce > 24, f.e 25.1 then it fails with 
```
crossplane: error: unable to calculate manifest: blob sha256:892b0ec9b5f9b28435e0e3c03034b63d3ac8e309e492f8b619dec348756a668d not found
```

OS: Fedora
Docker version >24
Crossplane version: github.com/crossplane/crossplane v1.14.5

Solution for now: 
```
dnf downgrade docker-ce
```

**Comment by phisco** [comment]
we are due for an upgrade indeed: https://github.com/crossplane/crossplane/pull/5266

**Comment by phisco** [comment]
Solved in the latest releases
