### ISSUE TITLE
Enhance managed resource readiness reporting 

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#5335]
### What problem are you facing?

In the context of using composition functions within Crossplane, managing the readiness status of created resources poses a challenge. Presently, we have to specify resources readiness as unspecified, ready, not ready, or unrecognized. If all resources are ready, Crossplane marks the composition as ready in status conditions; otherwise, it is marked as unready with a message indicating which resources are not ready.

We leverage Crossplane alongside ArgoCD, and thanks to this capability, Argo health checks seamlessly propagate from managed resources to parent XRs, and to Argo application itself. However, a challenge arises as it becomes difficult to promptly discern when a child MR is experiencing health issues within the application status.

### How could Crossplane help solve your problem?

We seek a more granular approach to report managed resource readiness, specifically to pinpoint why a resource might be unhealthy. Currently, we cannot discern whether a resource is unhealthy due to ongoing creation, synchronization issues or other "fatal" errors. This lack of insight prevents us from implementing custom Argo health checks on XRs to differentiate between real problems with a managed resource (degraded argo health) and ongoing operations (progressing argo state). 

I don't know what would be the best way to implement this. One option could involve introducing a "ready message" to provide additional context on the readiness status of managed resources. Another way could be adding a way to write back a custom condition to XR.

P.S: While initially framed in the context of composition functions, this issue may extend to other Crossplane features, such as P&T. We can modify the post accordingly to reflect this broader scope if necessary.

**Comment by ksawerykarwacki** [comment]
Requested something similar for helm provider long time ago before functions were considered: https://github.com/crossplane-contrib/provider-helm/issues/137 

The overall issue is similar. Helm charts managed by Crossplane are updated quickly but the provider takes time to roll them out (especially if you upgrade multiple charts). Custom readiness seems like the right way to go.
