### ISSUE TITLE
CRD deploymentruntimeconfigs.pkg.crossplane.io is too large

### ISSUE THREAD

**Issue by Rand0mF** [crossplane/crossplane#5336]
### What happened?
Installing the crossplane cluster CRDs doesn't work anymore. Probably caused by this commit: https://github.com/crossplane/crossplane/commit/ade5824ab4ce5578b3eb0cf116e4ec07f13e7a83

### How can we reproduce it?
`kubectl apply -k 'https://github.com/crossplane/crossplane//cluster?ref=master'`
or root cause:
`kubectl apply -f cluster/crds/pkg.crossplane.io_deploymentruntimeconfigs.yaml`

```
The CustomResourceDefinition "deploymentruntimeconfigs.pkg.crossplane.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### What environment did it happen in?
- Crossplane version: -
- Kubernetes Version:
```
$kubectl version --short
Client Version: v1.27.9-dispatcher
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
* Kubernetes distribution: Kind v0.20.0

**Comment by Rand0mF** [comment]
tag 1.14.5 still works
`kubectl apply -k 'https://github.com/crossplane/crossplane//cluster?ref=v1.14.5'`

**Comment by phisco** [comment]
Closing this for now, feel free to reopen if the provided workaround is not enough 🙏

**Comment by Rand0mF** [comment]
@phisco I think it also breaks this one here: https://github.com/crossplane/provider-template/blob/main/Makefile#L95

**Comment by phisco** [comment]
Good point @Rand0mF, just adding `--server-side` there will do the trick.
<img width="1372" alt="image" src="https://github.com/crossplane/crossplane/assets/5697904/61e49b5d-61e9-46d3-9c6b-7ff22a54ae6e">
There is not much we can do on XP side unfortunately. Could you open an issue/PR there?
