### ISSUE TITLE
Function SDK Release Cadence & Version Compatibility

### ISSUE THREAD

**Issue by blakeromano** [crossplane/crossplane#5399]
### What problem are you facing?

When a new version of Crossplane is released new features may be added that the Function SDKs will need to be added to support. I also am unsure now how compatible X version of the Function SDK is with X version of Crossplane.

### How could Crossplane help solve your problem?
A Version Compatibility Table should be created for the SDKs and when Crossplane is releasing a new version we should create a new version of the SDK.

**Comment by negz** [comment]
FWIW the contract between function SDKs and Crossplane is protobuf, and we intend to follow good forward/backward compatibility rules there. So in general:

* If Crossplane is newer than your SDK, your function(s) will work but won't expose any new features.
* If Crossplane is older than your SDK, your function(s) will work but attempts to use new features will be no-ops.

That all said, I agree we should release SDKs to take advantage of new features and make it obvious what SDK versions support said features.
