### ISSUE TITLE
Provide a Channel of Communication to the Claim

### ISSUE THREAD

**Issue by dalton-hill-0** [crossplane/crossplane#5402]
### What problem are you facing?
We want to communicate error-type messages to our users. We can communicate by setting fields in the Claim’s status, however, if the error is so bad that we wish to stop reconciliation to prevent a bad state, we cannot both update the Claim’s status and return a `response.Fatal` to stop the function from updating MRs, etc.

### How could Crossplane help solve your problem?
Provide a mechanism within the SDK to allow us to create events on the Claim, similar to how we can create events on the Composite with `response.[Fatal|Warning|Normal]`.

**Comment by negz** [comment]
Lifting most recent status out of Slack:

What I think we should do is enable Composition authors to:
1. Input: Load detailed state about composed resources (e.g. errors from the external APIs etc).
2. Filter and present that state to frame it more appropriately for claim consumers.
3. Add any extra state that is interesting and relevant to claim authors (e.g. _some_ function pipeline results).
4. Output: Show the resulting state on the claim.

I would have thought the input would be status conditions and recent events, with output also being status conditions and events.

This is pretty similar to what https://www.youtube.com/watch?v=xAl3TAfFE_M proposes.
