### ISSUE TITLE
Issue with capitalization in printcolumn names

### ISSUE THREAD

**Issue by maximiliantech** [crossplane/crossplane#5406]
### What happened?
@ValentinGerlach and I, we found out that resources like `Providers` get highlighted green in k9s every time the `AGE` column changes its value. That is indicated by the red arrow next to the age value, see the following image

![Screenshot 2024-02-19 at 13 29 25](https://github.com/crossplane/crossplane/assets/74709975/a34666f7-e71f-4313-bb6a-e04c025f50b4)

K9s does not recognize the age field when it is written in uppercase letters, so sorting will be lexicographic `(2m > 2h)`.
@ValentinGerlach checked how the Kube Core API is doing it. They are using PascalCase: 

![Screenshot 2024-02-19 at 16 17 50](https://github.com/crossplane/crossplane/assets/74709975/7f67bb4d-d0ee-4b86-bea3-4fa9638080b9)

So, the fact that the printcolumn names are uppercased in kubectl or k9s is just a client-side feature, see: https://github.com/kubernetes/cli-runtime/blob/99a5889ff2e77eb3811fe2283b14d01bc3022076/pkg/printers/tableprinter.go#L189

### How can we reproduce it?
1. Create kind cluster
2. Install Crossplane e.g. with version v.1.15.0
3. Install Provider e.g. AWS Amplify with the following YAML:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-amplify
spec:
  package: xpkg.upbound.io/upbound/provider-aws-amplify:v1.0.0
```
4. Open K9s
5. Get `providers.pkg.crossplane.io`

### What environment did it happen in?
Crossplane version: v1.15.0 (and also tested in earlier versions)
kubectl version: v1.29.2
K9s version: v0.31.9
[kind cluster](https://kind.sigs.k8s.io/) with kindest/node:v1.29.2

### Solution
We already have a solution in place. I will open up a PR to demonstrate it but let's discuss it here.

**Comment by phisco** [comment]
Feels also that K9s could be more flexible and match both uppercase and Camel case columns 🤔 not a big issue changing it here, but I guess we won't be the only one, at a quick look I could see a few projects doing the same, e.g. https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno/kyverno.io_admissionreports.yaml, but also upstream components.

**Comment by bobh66** [comment]
I tend to agree with @phisco - k9s should be able to handle the data in whatever format it is given.  Are we going to change all of the providers too?  This seems like a lot of unnecessary effort to work around something that k9s could fix in one place.

**Comment by negz** [comment]
Yeah, it doesn't seem like there's any clear guidance.

I notice the [CRD docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns) use title case column name examples (e.g. `Age`). There doesn't seem to be any enforcement of this though, and the [API reference docs](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/#CustomResourceDefinitionSpec) just say "a human readable name for the column" without any details about format.

AFAIK kubectl is always going to show these as title case no matter what format we use.

So all that said unless there's clear guidance that we should be following a convention I agree it would be best to update k9s to address this, not Crossplane.

**Comment by maximiliantech** [comment]
Yes, valid point. Thanks for your feedback! 🚀
