### ISSUE TITLE
Annotations and labels on connection secrets from a Claim/CompositeResource

### ISSUE THREAD

**Issue by danielloader** [crossplane/crossplane#5428]
### What problem are you facing?

Hey, I'd like to be able to configure the annotations and or labels on a resulting connection secret from either a claim or the upstream composite resource. I'd like to be able to provision some resources as a cluster admin level and have those connection secrets available in multiple namespaces (and some for all namespaces).

Since Crossplane doesn't support multiple claims referencing the same composite resource I can't use that mechanism, so the next best option seems to be creation of the composite resources and mirroring the connection secret using a third party controller.

However as far as I can see these controllers require annotations on the secret to permit mirroring and or configure which namespaces to mirror to.

### How could Crossplane help solve your problem?

Allow compositions to configure the annotations and labels of the connection secret as an optional configuration block.

**Comment by richardpj** [comment]
The ability to add connection secret meta data in the writeConnectionSecretToRef section and have it propagate to the secret would be awesome!

**Comment by jcooklin** [comment]
This would allow a provider we have more managing OIDC apps to write the clientSecret for consumption by argcd which requires that the secret have the label `app.kubernetes.io/part-of: argocd`.
