### ISSUE TITLE
Unable to import an AWS bucket notification into Crossplane

### ISSUE THREAD

**Issue by giulio-chillipharm** [crossplane/crossplane#5432]
### What happened?

I tried to import an AWS bucket and bucket notification into Crossplane, but while the S3 bucket import was successful, the bucket notification import failed with the error below:
`Warning  CannotObserveExternalResource  2m25s (x52 over 53m)  managed/s3.aws.upbound.io/v1beta1, kind=bucketnotification  (combined from similar events): failed to observe the resource: [{0 reading S3 Bucket Notification (photo-upload): operation error S3: GetBucketNotificationConfiguration, https response error StatusCode: 301, RequestID: 1JT115BZP0EY2RZW, HostID: 4oqvs+uhxBPLenYw0DqOnsImZbfX9dfkwLN5EVAwHuylVIQhL4C9MrpI2OkDosCB0oiOCChYHaU=, api error PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.  []}]`

I can create a new bucket notification with Crossplane, but this replaces the existing one, hence I aim to import the existing one into Crossplane and then modify it as needed. According to [this](https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/) page of your documentation, it should be possible.

### How can we reproduce it?

I manually configured the bucket notification and SNS topic in the AWS console and then applied the manifest below in the Kubernetes cluster:

`apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-imported-s3-bucket
  annotations:
    crossplane.io/external-name: test-bucket-sns-notification
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: "eu-west-1"

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketNotification
metadata:
  name: photo-upload
  annotations:
    crossplane.io/external-name: photo-upload
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: eu-west-1
    bucket: test-bucket-sns-notification
    topic: 
      - topicArn: "arn:aws:sns:eu-west-1:xxxxxxxxxxxx:test-topic"`

### What environment did it happen in?
Crossplane version: 
xpkg.upbound.io/crossplane/crossplane:v1.15.0

- xpkg.upbound.io/crossplane/crossplane:v1.15.0
- EKS cluster version 1.27 or Kind cluster version 1.27

<img width="1214" alt="Screenshot 2024-02-27 at 10 20 40" src="https://github.com/crossplane/crossplane/assets/156785373/c7175e9f-1ecb-46e3-94cd-3aadf2e2d4e8">

![Screenshot 2024-02-27 at 11 08 14](https://github.com/crossplane/crossplane/assets/156785373/80dc392e-70ef-485a-8c50-538381606911)

**Comment by haarchri** [comment]
Please Open this issue in upbound/provider-aws repo - thanks
