### ISSUE TITLE
Create Crossplane Awesome repo

### ISSUE THREAD

**Issue by csantanapr** [crossplane/crossplane#5438]
I noticed that Crossplane doesn't have a Awesome github repo, 
Here is an example of the Argo one 
- https://github.com/akuity/awesome-argo
- https://akuity.github.io/awesome-argo/

There are many blog posts, videos, tutorials, and related utility projects that would be amazing to have it one place and maintain by the community

The only place I find resources are in the [google doc community meeting notes](https://docs.google.com/document/d/1q_sp2jLQsDEOX7Yug6TPOv7Fwrys6EwcF5Itxjkno7Y/edit#heading=h.bag869lp4lyz), there is a section for this content, we could start with an initial list extracting from the google doc for example
- https://killercoda.com/decoder/course/crossplane
- KubeCon Talks from youtube
- Links from last community meeting
- [Enhancing Developer Experience with Crossplane 1.15: CLI, Composition Functions Python SDK, and More](https://blog.crossplane.io/crossplane-v1-15/)
[New Default Crossplane Registry in Crossplane 1.15](https://blog.crossplane.io/new-default-crossplane-registry-in-crossplane-1-15/)
[Welcoming 2 New Members to the Crossplane Steering Committee](https://blog.crossplane.io/welcoming-2-new-members-to-the-crossplane-steering-committee/)
[Speeding using Crossplane and ServiceBinding](https://accordingtoalinahid.blogspot.com/2024/01/speeding-using-crossplane-and-service-binding.html) 
[Automating provisioning of EKS Clusters with Crossplane](https://rprakashg.github.io/provisioning-eks-clusters-with-crossplane/)
[Config Management Camp Ghent 2024](https://youtu.be/Ba0TkvPnq-U?t=19785)
[Developing Infrastructure Testing Workflow GitOps Demo with Argocd, Crossplane, and vCluster](https://www.youtube.com/watch?v=0oPGcFQCp3U)
[Crossplane 1.15 enhances developer experience for platform engineers](https://tfir.io/crossplane-1-15-enhances-developer-experience-for-platform-engineers/)
[The New Stack Platform Engineering Overview](https://thenewstack.io/platform-engineering/)

### What problem are you facing?
Centralizing all amazing resources for Crossplane

### How could Crossplane help solve your problem?
Create a new github repo for the community to open PRs to add to the list

I brought the idea in slack with @jbw976 https://crossplane.slack.com/archives/CEG3T90A1/p1709220373550279

**Comment by phisco** [comment]
@jbw976 what do you think about proceeding with this one?
