### ISSUE TITLE
crossplane cli --version client and server version 

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5447]
### What problem are you facing?

It would be helpful if the Crossplane CLI could display both the client and server versions when using the --version flag. This feature would simplify the process of reporting bugs and requesting enhancements, as users could easily share their version information. Implementing this would align Crossplane's CLI with the functionality of the kubectl CLI, enhancing user experience by providing consistent and valuable information.

**Comment by phisco** [comment]
It's easy for kubectl to find the server version for the current context. But I don't think it's going to be so easy for us. We would need to assume it was installed in some specific way, either by checking helm releases installed or assuming the namespace and checking the image. 

Did you have something in mind already? Any other similar tool exposing this that you know of?

**Comment by haarchri** [comment]
flux cli can print client and serverside components versions for example
