### ISSUE TITLE
Switch to the Renovate GitHub Action

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5462]
### What problem are you facing?

Sometimes Renovate bumps dependencies like controller-tools or protobuf that affect how code is generated, for example in https://github.com/crossplane/crossplane/pull/5455. These bumps require human intervention. We need to checkout the Renovate PR and run `make generate` before merging the PR. If we don't, `make check-diff` will fail.

It's possible to configure Renovate to run `make generate` after it bumps dependencies using [post upgrade tasks](https://docs.renovatebot.com/configuration-options/#postupgradetasks). We can't use post upgrade tasks because they only work with self-hosted Renovate. We're currently using Mend's hosted Renovate via their GitHub App.

### How could Crossplane help solve your problem?

We could switch to https://github.com/renovatebot/github-action. This way we'd be "self hosting" Renovate, and would be able to configure it to run `make reviewable`.

**Comment by enesonus** [comment]
Hi @negz I want to work on this issue. Is there any thing you want me to be aware of or want me to include to the github actions workflow file?

**Comment by negz** [comment]
@enesonus Thank you!

The goal is:

* Renovate automatically runs `make generate` before opening a PR 
* Ideally renovate runs about as frequently as it does today
* Ideally we don't lose useful Renovate functionality (e.g. the "click here to rebase" box on Renovate PRs)

**Comment by jbw976** [comment]
Is there more left for this issue now @phisco @enesonus? I think self-hosted renovate is up and running and doing useful work for now now 🤩

**Comment by phisco** [comment]
I'd say so! There is definitely room for further tuning, but definitely working now!

**Comment by negz** [comment]
FYI, I just migrated crossplane-runtime to this action too. To do so I just had to:

* Configure the Renovate app at the org level to exclude crossplane-runtime.
* Configure the Crossplane-Renovate app at the org level to include crossplane-runtime.
* Configure the `RENOVATE_GITHUB_APP_*` secrets at the org level to allow crossplane-runtime.
