### ISSUE TITLE
`validate` doesn't do tilde expansion

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5487]
### What happened?

Not sure if I have the right vocabulary for this, but using `crossplane validate --cache-dir="~/.crossplane/cache` resulted in the cache being put in a local directory called `~` in the current working directory. I was expecting tilde expansion to happen and have the cache dir in my `${HOME}` instead, so the cache would be more persistent then the temp working directory I was in.

We should also check if this is a general issue across other crossplane CLI commands, or just specific to `validate`.

### Workaround

I was able to work around this by explicitly using `${HOME}` instead of `~`.

### How can we reproduce it?

Run `crossplane validate` with `--cache-dir="~/.crossplane/cache`. A full walkthrough of these steps can be found in https://github.com/jbw976/demo-xfn, with the validation step specifically in https://github.com/jbw976/demo-xfn?tab=readme-ov-file#validate-output (although going through all the steps is necessary to make sure the scenario is fully set up).

Running `render | validate` and specifying a cache dir:
```
❯ crossplane beta render xr.yaml composition.yaml functions.yaml -x | crossplane beta validate extensions.yaml --cache-dir="~/.crossplane/cache" -
package schemas does not exist, downloading:  xpkg.upbound.io/upbound/provider-aws-s3:v1.2.0
[✓] example.crossplane.io/v1, Kind=XR, example-xr validated successfully
[✓] s3.aws.upbound.io/v1beta1, Kind=Bucket, xbuckets-test-bucket validated successfully
Total 2 resources: 0 missing schemas, 2 success cases, 0 failure cases
```

I expect the cache dir to be in `~/.crossplane`, but it's not there:
```
❯ ll ~/.crossplane/
total 8
drwxr-xr-x   3 jared  staff    96B Feb 13 01:29 .
drwxr-x---+ 61 jared  staff   1.9K Mar 15 08:59 ..
-rw-------   1 jared  staff   712B Feb 13 01:30 config.json
```

Here it is in the local directory called `~`:
```
❯ ll
total 40
drwxr-xr-x   8 jared  staff   256B Mar 15 08:59 .
drwxr-x---  19 jared  staff   608B Mar 15 08:57 ..
-rw-r--r--   1 jared  staff   578B Mar 15 08:57 README.md
-rw-r--r--   1 jared  staff   381B Mar 15 08:58 composition.yaml
-rw-r--r--   1 jared  staff   527B Mar 15 08:59 extensions.yaml
-rw-r--r--   1 jared  staff   303B Mar 15 08:57 functions.yaml
-rw-r--r--   1 jared  staff   113B Mar 15 08:57 xr.yaml
drwxr-xr-x   3 jared  staff    96B Mar 15 08:59 ~
```

### What environment did it happen in?
Crossplane version:
```
❯ crossplane --version
v1.15.0
```

**Comment by bobh66** [comment]
The ~ expansion should be done by the shell - if you leave off the quotes and just run `crossplane validate --cache-dir=~/foo` does that work?

**Comment by santhoshivan23** [comment]
@jbw976 would this work in `cmd.go`?

`strings.Replace(c.CacheDir, "~", "${HOME}", 1)`

**Comment by santhoshivan23** [comment]
hello, i'm willing to contribute here, requesting the maintainers for help :)

**Comment by phisco** [comment]
@santhoshivan23, the first thing would be to validate what @bobh66 is suggesting above 😉

**Comment by jbw976** [comment]
@santhoshivan23 were you able to set up an environment to reproduce this issue, and then try @bobh66 suggestion https://github.com/crossplane/crossplane/issues/5487#issuecomment-2000247196? 

I just tried right now and in my environment, @bobh66 suggestion still reproduces the undesirable behavior. So a code fix to handle this case sounds like a good idea to me.

Note from below:

* as bob suggested, I have no double quotes `"` around the `--cache-dir` flag value
* cache dir not found, implying it's not finding/using my existing cache dir at `~/.crossplane/cache`

* the resulting dir named `~` that the CLI created in the current dir:
```
❯ crossplane beta render xr.yaml composition.yaml functions.yaml -x | crossplane beta validate extensions.yaml --cache-dir=~/.crossplane/cache -
package schemas does not exist, downloading:  xpkg.upbound.io/upbound/provider-aws-s3:v1.2.0
[✓] example.crossplane.io/v1, Kind=XR, example-xr validated successfully
[✓] s3.aws.upbound.io/v1beta1, Kind=Bucket, xbuckets-test-bucket validated successfully
Total 2 resources: 0 missing schemas, 2 success cases, 0 failure cases

❯ ls -1
README.md
composition.yaml
extensions.yaml
functions.yaml
xr.yaml
~
```
```

**Comment by bobh66** [comment]
@jbw976 that's really interesting - I wonder if the tilde-expansion is not done by the shell because of the "=" sign tying the string value to the argument name.  If the "=" is required then the code will need to do the tilde-expansion explicitly.  If the "=" is optional then the shell might do it if "--cache-dir ~/.crossplane/cache" is a value syntax.  Either way the code needs to handle it since the "=" syntax is valid.

**Comment by santhoshivan23** [comment]
@jbw976 Apologies for the delay! I was getting myself up to speed with the nitty gritty's of crossplane, cli & validate.
I'm now able to reproduce the issue as well as Bob's suggestion to try without the quotes and I do see the same results. 

@bobh66 - I'd like to understand more on why you think the "=" sign is the not allowing auto tilde expansion and also the best way we could resolve this issue.

**Comment by bobh66** [comment]
> I'd like to understand more on why you think the "=" sign is the not allowing auto tilde expansion and also the best way we could resolve this issue.

The shell will only do tilde-expansion when the ~ is preceded by whitespace:
```
$ echo --cachedir=~bobh/.cache
--cachedir=~bobh/.cache

$ echo --cachedir ~bobh/.cache
--cachedir /Users/bobh/.cache
```
so the validate code should probably check to see if the first character of the argument is a `~` and do the expansion accordingly (there may be a userid following the `~` character)

**Comment by santhoshivan23** [comment]
> The shell will only do tilde-expansion when the ~ is preceded by whitespace:

@bobh66 - I thought we could programmatically replace `"~" with " ~" `,  so tried executing:

`crossplane beta validate extensions.yaml --cache-dir=" ~/.crossplane/cache" -` (note the whitespace)

and I could see that the cache folder still gets created in the same working directory.

**Comment by santhoshivan23** [comment]
Is it a good approach to replace `~ with ${HOME}` ?

**Comment by jbw976** [comment]
This looks like a reasonable approach @santhoshivan23: https://www.reddit.com/r/golang/comments/wei0jv/best_way_to_handle_tildehome_expansion/iiodka7/ 

Note the solution that is directly mentioned in that comment, and also the bonus solution linked in it as well ([link](https://gist.github.com/miguelmota/9ab72c5e342f833123c0b5cfd5aca468?permalink_comment_id=3953465#gistcomment-3953465))

Perhaps that bonus solution is the most robust approach?

**Comment by bobh66** [comment]
> `crossplane beta validate extensions.yaml --cache-dir=" ~/.crossplane/cache" -` (note the whitespace)
> 
> and I could see that the cache folder still gets created in the same working directory.

That's because the shell doesn't get a second attempt - once it has entered the executable the shell is no longer in the picture for tilde expansion

**Comment by bobh66** [comment]
> Note the solution that is directly mentioned in that comment, and also the bonus solution linked in it as well ([link](https://gist.github.com/miguelmota/9ab72c5e342f833123c0b5cfd5aca468?permalink_comment_id=3953465#gistcomment-3953465))
> 
> Perhaps that bonus solution is the most robust approach?

This solution works for the "~/" case, meaning that it only applies to putting the data in the current user's HOME-relative directory.  A more robust solution would accept the "~someuser/" case, where "someuser" could be missing and default to the current user.
