### ISSUE TITLE
enhance error logging for existing object is not controlled by UID - add GVK, Resource Name etc.

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5488]
### What problem are you facing?

please provide an indication which resource is not controlled by the correct object. If my compostion has 30 resources, it would be good to have an indicator, which resource is not controlled by the correct UID.

```
cannot compose resources: cannot apply composed resource: existing object is not controlled by UID "941a35fb-16b2-49af-be92-55e34e08cfbe"
```

![image](https://github.com/crossplane/crossplane/assets/21083497/aa9ea4bb-976b-4bdc-952d-7442ce8ef56a)

**Comment by santhoshivan23** [comment]
looks like a quick fix? can anyone tell me where this is logged? i did a global search for this log but couldn't find it

**Comment by santhoshivan23** [comment]
@negz I figured out that the change has to be done in crossplane-runtime. This function has to accept some more params and log it.
```
func MustBeControllableBy(u types.UID) ApplyOption {
	return func(_ context.Context, current, _ runtime.Object) error {
		c := metav1.GetControllerOf(current.(metav1.Object))
		if c == nil {
			return nil
		}

		if c.UID != u {
			return errNotControllable{errors.Errorf("existing object is not controlled by UID %q", u)}

		}
		return nil
	}
}
```

**Comment by birapjr** [comment]
This issue also affect us. Would be nice to have this information. We are recreating a complete EKS cluster and some resources were not deleted and the same error happen and no information on what resource the problem is.
