### ISSUE TITLE
Consider Adding Crossplane Information to User Agent

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#549]
**Goal**: Provide greater audit-ability by including Crossplane specific information to AWS requests.

**Description:** The AWS API allows for additional information to be added to requests in the form of a [user agent](https://docs.aws.amazon.com/sdk-for-go/api/aws/request/#AddToUserAgent) field. It would provide additional audit-ability when looking at CloudTrail logs if information such as the Crossplane version used to make the request was included in the user agent field. This is a pattern that has been used by a number of other tools that deploy infrastructure.

**Implementation:** There are two main routes for implementation that jump out to me.

1. The straightforward implementation would be to wrap each request made by the various AWS resource clients with `AddToUserAgent()`. The downside to this would be that we would need to ensure that each client was adding the user agent information for every request it made.
2. A second option that would be more sustainable, would be to start utilizing [sessions](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) to implement this functionality as they allow you to wrap requests with handlers that will be universal.

**Future:** A potential future feature that could be derived from this functionality is the ability for universal user agent data to be stored in the `provider`, allowing users to add arbitrary information that they would like to be logged in all requests made by Crossplane to AWS.

**Comment by displague** [comment]
A custom User-Agent also shows the cloud provider how Crossplane is being used and can help users sort problems out with the cloud provider.

**Comment by muvaf** [comment]
`provider-aws` has this [now](https://github.com/crossplane/provider-aws/pull/1243) and I think individual issues in providers would be more helpful for maintainers to consider this individually.
