### ISSUE TITLE
Support crossplane function pull from local docker registry

### ISSUE THREAD

**Issue by markphillips100** [crossplane/crossplane#5494]
### What problem are you facing?
I'm using KCL via a [kcl-function provider](https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl/v0.3.2) and have recently had success using `crossplane beta render` via the crossplane cli for rendering function output locally.  The cli talks to a local kcl function service that is able to pull an oci package from my local docker registry using a non-ssl connection.

I want to be able to use my local docker registry in a similar setup from my local KinD cluster where I have crossplane installed.  I have a feeling the annotations are only supported by the cli though so is there a way to have the crossplane controller talk to the local kcl function in the same way the cli does so that a non-ssl local docker registry can be used?

### How could Crossplane help solve your problem?
Support the crossplane controller access to a locally (on the host) running function so that a local crossplane/function innerloop is possible.

**Comment by markphillips100** [comment]
Just to add, I did try using `oci://host.docker.internal:7900/....` from the composition's kcl function to see if it would pull but this complains due to the lack of SSL.

This is the error from describing the composite:
```
Get "https://host.docker.internal:7900/v2/tuckerbox/country-composition-kcl/tags/list": http: server gave HTTP response to HTTPS client
```

**Comment by markphillips100** [comment]
Closing as I believe this is an issue for kcl function rather than crossplane specifically.

**Comment by RickardCardell** [comment]
I think it can be reopened since it is **not** specific to KCL functions. It's about pulling composition functions from a local registry in general. 
I have the same issue when building a Python or Go composition function locally, when I want to run it in a local cluster without having to push it to an external registry.
