### ISSUE TITLE
Extraneous files in docker image cause spurious compliance failures

### ISSUE THREAD

**Issue by dee0** [crossplane/crossplane#5514]
### What happened?

In our org compliance folks are scanning images to determine what licenses we must comply with.   They keep this info on file and if they notice that some software ( e.g. library ) is in use but the version use is more than 1 year old _and_ there is a newer version available then they block you from rolling out changes to production until you either upgrade or demonstrate that their assessment is wrong.

We're using Crossplane 1.13.1 and last week we were flagged because the license checking folks asserted we, really Crossplane, are using  netbase_6.3_all.deb.

I am 99% certain that Crossplane doesn't actually use  netbase_6.3_all.deb and the license check is confused because these files are in the image 
./usr/share/doc/netbase
./var/lib/dpkg/status.d/netbase
./var/lib/dpkg/status.d/netbase.md5sums

### How can we reproduce it?

I suppose run the Mend scanner on the Crossplane image.

### What environment did it happen in?
Crossplane version: 

We're using Crossplane version is 1.13.1.   However I pulled down 1.15.1 and I see the same netbase files are present in it.

**Comment by negz** [comment]
Crossplane uses https://github.com/GoogleContainerTools/distroless as its base image. We use Renovate to keep the base image up-to-date, e.g. https://github.com/crossplane/crossplane/commit/54e16feaae4f471a2c423a6260b2ee8131dbaa80. The `gcr.io/distroless/static` tag we use is based on Debian 11 bullseye. Looks like net base 6.3 is the latest version supported by bullseye.

Per https://packages.debian.org/bullseye/netbase:

> This package provides the necessary infrastructure for basic TCP/IP based networking. In particular, it supplies common name-to-number mappings in /etc/services, /etc/rpc, /etc/protocols and /etc/ethertypes.

I'm guessing there might be some real need for this package to exist - e.g. does name-to-number mapping always work in Go without this package? I'd prefer not to "reinvent the wheel" by moving to an even more minimal base image than distroless.

I'd be happy to accept a PR updating Crossplane to use `gcr.io/distroless/static-debian12`. I don't think we'd back port this to release 1.13.x though.
