### ISSUE TITLE
Update an field from Environment

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#5534]
Hi, I'd like to know how I update for example a tag from composition

I have an enviroment

apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: dev-environment
 ...
 ...
 tag: dev **(I change to prod) but nothing happens to my resource, it keep with dev tag**

  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: dev-environment
        
       
My composition

      patches:
        - type: FromEnvironmentFieldPath
          fromFieldPath: tags
          toFieldPath: spec.forProvider.tags

**Comment by phisco** [comment]
Can you provide a bit more context? What steps did you try? What did you expect to happen?

**Comment by diegoavitorino** [comment]
Now, tag was updated, I change the value and I waited about 2 minutes.

thanks anyway
