### ISSUE TITLE
Add `--context` Parameter Support to `crossplane beta trace` Command

### ISSUE THREAD

**Issue by brovoca** [crossplane/crossplane#5537]
### What problem are you facing?
In Kubernetes, the `--context` parameter is widely used to specify the cluster context when executing commands. This allows users to direct commands to the appropriate cluster without changing the global context set in the kubeconfig. Currently, the `crossplane beta trace` command does not support the `--context` parameter. This omission requires users to either change their global kubeconfig context before running the command or use workarounds that may not be straightforward or intuitive, especially in environments where operations across multiple clusters are common.

### How could Crossplane help solve your problem?
Implementing support for the `--context` parameter in the `crossplane beta trace` command would align it with common Kubernetes practices, making it more intuitive for users who frequently switch between clusters. This feature would enhance usability by allowing users to specify the target cluster directly in the command line, improving the command's flexibility and utility in multi-cluster environments. Users already familiar with the `--context` parameter from `kubectl` and other Kubernetes-related tooling would find `crossplane beta trace` more intuitive and easier to integrate into their existing workflows.

**Comment by phisco** [comment]
Crossplane beta trace doesn't talk with a Kubernetes cluster at all afaik

**Comment by brovoca** [comment]
How's that possible? It returns the objects that exist in the cluster and the relation between them.

**Comment by phisco** [comment]
Deleted my comment immediately, you were too quick, I read crossplane beta render 😂

**Comment by brovoca** [comment]
That was quick! :1st_place_medal:
