### ISSUE TITLE
Use environment to matchLabels:

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#5553]
Hi, I'd like to know is is possible to inform a environment in matchlabels:

instead:

matchLabels:
      app: etl-app-dev

use:

matchLabels:
     {some env from EnvironmentConfig}
     
thanks

**Comment by bobh66** [comment]
Hi @diegoavitorino - can you provide some more context?  Where is the `matchLabels` located?  Is this part of a `Composition`?  Thanks

**Comment by diegoavitorino** [comment]
Hi, exatly, for example, I've created a core label witch match all my composition:

  patchSets:
  - name: common
    patches:
      - type: FromEnvironmentFieldPath
        fromFieldPath: label
        toFieldPath: metadata.labels['app']   
        
each resource:

      patches:
        - type: PatchSet
          patchSetName: common  
          
until here it is ok, but, I'd like each matchlabel use the same way, use an env, instead put name by name .

            securityGroupIdSelector:
              matchLabels:
                app: **rds-app-dev** , use some common env instead
                
            securityGroupIdSelector: 
              matchLabels:
                app: **rds-app-dev**   use some common env instead     
                
            securityGroupIdSelector:
              matchLabels:
                app: **rds-app-dev**    use some common env instead
