### ISSUE TITLE
Deploy a provider in a different namespace than the core

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5576]
### Discussed in https://github.com/crossplane/crossplane/discussions/5449

<div type='discussions-op-text'>

<sup>Originally posted by **xoanmi** March  4, 2024</sup>
Hi folks!

It is possible to deploy a provider in a different namespace than the core?

For security and management reasons, we would like to split the deployment of each provider into its namespace. Is this possible in any way? </div>

From investigation on the discussion in https://github.com/crossplane/crossplane/discussions/5449#discussioncomment-8669511:

> TL;DR it looks like this should work, but a potential bug is preventing it from working correctly

**Comment by xoanmi** [comment]
> @xoanmi is your goal to deploy all providers to one namespace that is different from where Crossplane is deployed, or to deploy each provider to its own namespace? Based on the linked discussion, it sounds like the latter.

Both options are fine for us, but the second let us more flexibility :)
