### ISSUE TITLE
 Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#5578]
Hi, by trying to deploy a bucket for example I'm facing the error below

managed/s3.aws.upbound.io/v1beta1, kind=bucket  cannot initialize the Terraform plugin SDK async external client: cannot get terraform setup: failed to retrieve aws credentials from aws config: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 403, RequestID: 4a8524d5-fc0e-46ff-9000-fd823d1b8661, api error AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

I've checked policy and Trusted entities

            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.sa-east-1.amazonaws.com/id/145438BD.....:sub": "system:serviceaccount:crossplane-system:provider-aws-*",
                    "oidc.eks.sa-east-1.amazonaws.com/id/145438BD.....:aud": "sts.amazonaws.com"

I also validate that providers, DeploymentRuntimeConfig and providers config, and each provider has my role annotation.

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::myaccountID:role/Myrole

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v1.2.1
  runtimeConfigRef:
    name: irsa-runtimeconfig

apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    app:  mynewbucket
  name: mynewbucket
spec:
  providerConfigRef:
    name: default

**Comment by haarchri** [comment]
You using wildcard service account you need to switch `StringEquals` to `StringLike`

**Comment by plumbis** [comment]
More information in the Upbound provider docs. https://docs.upbound.io/providers/provider-aws/authentication/#edit-the-iam-role

**Comment by diegoavitorino** [comment]
It worked, that's it, thank you very much guys
