### ISSUE TITLE
Consider generating OCI-native packages

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#5580]
### What problem are you facing?
Crossplane packages are docker-compliant but they require some logic in `crossplane xpkg push` to implement the layer annotations that Crossplane relies upon to efficiently cache and reconcile the packages.

This makes package management (pull, push, etc) dependent on the `crossplane` CLI, and it would be useful to decouple that relationship so that full-functional Crossplane packages can be pushed/pulled/etc by other tools such as `crane`.

### How could Crossplane help solve your problem?
Provide an option to `crossplane xpkg build` that generates a fully OCI-compliant package with the layer annotations specified in the `manifest.json` so that no custom logic is required to push the packages to a registry and annotate the layers based on the `Labels` stored in the `Config` section.

This is probably a lot harder than it sounds, but I wanted to at least get the idea out for discussion.

**Comment by negz** [comment]
@bobh66 I'm not following what the output of the `crossplane xpkg build` variant you're proposing is. Would it be an on-disk OCI Image Layout ala https://pkg.go.dev/github.com/google/go-containerregistry@v0.19.1/pkg/v1/layout?

**Comment by jbw976** [comment]
A workaround from [Crossplane Slack](https://crossplane.slack.com/archives/C01TRKD4623/p1739550168110679?thread_ts=1739522571.773739&cid=C01TRKD4623):

> For prosperity using `skopeo copy --preserve-digests --all $source $target` works.
