### ISSUE TITLE
crank trace: get namespace from Kubernetes context to behave like other CLI tools in the k8s ecosystem

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#5600]
### What problem are you facing?

`$KUBECONFIG` contains a context with a namespace. Most CLI tools respect this. `crank beta trace` does not. I've seen users confused a crankiness ensue due to this, for example when changing the namespace with `kubens`.

### How could Crossplane help solve your problem?

Get current namespace from the Kubernetes config.

**Comment by phisco** [comment]
good call, it should just be a matter of removing the default from https://github.com/crossplane/crossplane/blob/c9088a58cafd5bdfa7fae6b19ca6c75f3fdcbbb9/cmd/crank/beta/trace/trace.go#L66, to be tested obviously.

**Comment by chlunde** [comment]
@phisco Hmm, I don't think it's that easy but I'll try that!

**Comment by chlunde** [comment]
@phisco yeah, I think we need the change in the PR
