### ISSUE TITLE
"allocationRefId" for LB in provider-aws-elbv2

### ISSUE THREAD

**Issue by milers0** [crossplane/crossplane#5617]
### What problem are you facing?

It seems that the property "allocationRefId" has not been implemented for [LB in provider-aws-elbv2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-elbv2/v1.3.1/resources/elbv2.aws.upbound.io/LB/v1beta1#doc:spec-forProvider-subnetMapping-allocationId).

When creating an internet-facing load balancer, I would like to make a reference to a public IP address that is already created with Crossplane (using kind: EIP). In other providers/CRDs, such as [NATGateway in provider-aws-ec2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.3.1/resources/ec2.aws.upbound.io/NATGateway/v1beta1#doc:spec-forProvider-allocationIdRef), it is possible to use allocationIdRef to make a reference to the EIP object, to actually use the IP address, but LB only allows allocationId. Not having allocationIdRef requires a manual update by checking the allocationId in the AWS console.

### How could Crossplane help solve your problem?

By implementing the "allocationRefId" property for [LB in provider-aws-elbv2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-elbv2/v1.3.1/resources/elbv2.aws.upbound.io/LB/v1beta1#doc:spec-forProvider-subnetMapping-allocationId). It has already been implemented by other providers, for example, [NATGateway in provider-aws-ec2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.3.1/resources/ec2.aws.upbound.io/NATGateway/v1beta1#doc:spec-forProvider-allocationIdRef).

Thank you for taking the time to read the issue. If I have overlooked anything, then please let me know.

**Comment by bobh66** [comment]
Please open this issue in https://github.com/crossplane-contrib/provider-upjet-aws/issues

Thanks

**Comment by milers0** [comment]
Thanks Bob! Will do :)
