### ISSUE TITLE
`make run` fails locally with `cannot load certificate: open tls.crt: no such file or directory`

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5636]
### What happened?

When new contributors attempt to follow the guidance to [set up their developer environment](https://github.com/crossplane/crossplane/tree/master/contributing#establishing-a-development-environment), they will encounter an error when running `make run`:

```
❯ make run
11:44:01 [ .. ] go build linux_arm64
11:44:02 [ OK ] go build linux_arm64
11:44:02 [ .. ] Running Crossplane locally out-of-cluster . . .
./crossplane/crossplane/_output/bin/darwin_arm64/crossplane core start --debug
2024-04-29T11:44:03+02:00	INFO	crossplane	Beta feature enabled	{"flag": "EnableBetaCompositionFunctions"}
2024-04-29T11:44:03+02:00	INFO	crossplane	Beta feature enabled	{"flag": "EnableBetaCompositionFunctionsExtraResources"}
crossplane: error: cannot load client TLS certificates: cannot load certificate: open tls.crt: no such file or directory
make: *** [run] Error 1
````

@haarchri has a workaround script he uses. Should we document this, or should the process itself be made more easy?
https://gist.github.com/haarchri/6526d1738611cc79c04e88091dfe074a 

### How can we reproduce it?

Essentially the steps from https://github.com/crossplane/crossplane/tree/master/contributing#establishing-a-development-environment:

```
# build the project
make

# start a local kind cluster
./cluster/local/kind.sh up

# try to run crossplane locally, which will fail
make run
```

### What environment did it happen in?
Crossplane version: v1.15.2
Kubernetes client: v1.26.2
Kubernetes server: v1.29.1
OS: macoS Sonoma v14.4.1

**Comment by phisco** [comment]
Making TLS material available would be easy though, the harder part will be to have webhooks actually working and hitting a process external to the cluster, probably that would require something like mirrord or some other networking trick. The easiest thing would be not to setup and configure webhooks in this mode probably.

**Comment by negz** [comment]
FWIW I haven't personally used `make run` in many years. Do folks find it valuable?

Since we added E2E tests I almost never spin up a "dev environment" locally for Crossplane. I just write and/or run the E2E tests, which essentially do the same thing but in a repeatable fashion.

**Comment by jbw976** [comment]
I can see the value in building an e2e scenario for an intended change.

But I can personally find the value, and I can imagine others would as well, to have a very low barrier to entry means of iterating on my local crossplane code. For folks less familiar with the code base, and with the patterns/expectations of the e2e tests, being able to rapidly iterate over just their code changes pointed at a local cluster is an easier experience to get going.

FWIW, I still use `./cluster/local/kind.sh` often too, and `make run` is a faster/easier version of that 😉

**Comment by ytsarev** [comment]
>Since we added E2E tests I almost never spin up a "dev environment" locally for Crossplane. I just write and/or run the E2E tests, which essentially do the same thing but in a repeatable fashion.

That is a perfect, ideal test-driven workflow, and I admire it. But it also assumes excellent familiarity with the codebase.

The ability to quickly set up the local environment and understand the code behavior is crucial for those of us who don't work with the Crossplane core codebase daily. This enables early testing and lowers the barrier to start with the contribution flow.
