### ISSUE TITLE
ProviderRevision and Providers unhealthy

### ISSUE THREAD

**Issue by dmaggi** [crossplane/crossplane#5638]
### What happened?
I tried to upgrade default `Provider` managed by Crossplane `upbound-provider-family-aws`from 0.47.1 to 1.4.0 without succeed.

`ProviderRevision` events message:
```
  Type     Reason             Age                From                                         Message
  ----     ------             ----               ----                                         -------
  Normal   ApplyClusterRoles  25m                rbac/providerrevision.pkg.crossplane.io      Applied RBAC ClusterRoles: crossplane:provider:upbound-provider-family-aws-bac5d48bd353:aggregate-to-edit, crossplane:provider:upbound-provider-family-aws-bac5d48bd353:aggregate-to-view, and crossplane:provider:upbound-provider-family-aws-bac5d48bd353:system
  Warning  ApplyClusterRoles  25m                rbac/providerrevision.pkg.crossplane.io      cannot apply ClusterRole: cannot create object: clusterroles.rbac.authorization.k8s.io "crossplane:provider:upbound-provider-family-aws-bac5d48bd353:system" already exists
  Normal   BindClusterRole    25m (x5 over 25m)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole "crossplane:provider:upbound-provider-family-aws-bac5d48bd353:system" to provider ServiceAccount(s):
  Warning  SyncPackage        1s (x31 over 25m)  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: providerconfigs.aws.upbound.io is already controlled by ProviderRevision upbound-provider-family-aws-fec919bd2218 (UID b87af190-ab7b-4fa9-984d-b374f9d10184)

```

### How can we reproduce it?
I was trying to upgrade version and finally delete the Provider object. Then provider now match with latest 1.4.0 version, but is not healthy any more.

### What environment did it happen in?

- Crossplane version: 1.15.2 (HelmChart)
- Cloud: AWS on EKS Managed with EC2
- Kubernetes version: 1.27

**Comment by jbw976** [comment]
Thanks for reporting this behavior @dmaggi - would you be able to provide a bit more context?

* what were the specific upgrade steps that you performed? 
* what is the intent of deleting the `Provider` object? I don't think that's typical for most upgrade sequences
* If you want to provide more details in a [gist](https://gist.github.com/), that could also be helpful, like:
  * `kubectl get providers; kubectl get providerrevision` (just to quickly view everything present)
  * `kubectl describe providerrevision` (for all providerrevisions)
  * `kubectl describe providers` (for all providers)
  * `crossplane beta trace provider/<your-provider-name>` -o wide

**Comment by dmaggi** [comment]
Thanks for the quick response @jbw976 i already recreated the`providerconfig` and all seems to works properly. Any way, I'm not sure how can we upgrade Provider version without having this issues.

I need to do the same update in other environment. How should i proceed? With the 2 providers I defined (iam and s3), was easy to upgrade from 0.47 to 1.4 version, but as i mention the problem was with the upbound-provider-family-aws provider.

kubectl get providers; kubectl get providerrevision:
```
kubectl get providers.pkg.crossplane.io; kubectl get providerrevision

NAME                          INSTALLED   HEALTHY   PACKAGE                                               AGE
aws-iam                       True        True      xpkg.upbound.io/upbound/provider-aws-iam:v0.47.1      90d
aws-s3                        True        True      xpkg.upbound.io/upbound/provider-aws-s3:v0.47.1       90d
upbound-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v0.47.1   90d
NAME                                       HEALTHY   REVISION   IMAGE                                                 STATE    DEP-FOUND   DEP-INSTALLED   AGE
aws-iam-fc4c8e7f6d42                       True      1          xpkg.upbound.io/upbound/provider-aws-iam:v0.47.1      Active   1           1               90d
aws-s3-608e381115ec                        True      1          xpkg.upbound.io/upbound/provider-aws-s3:v0.47.1       Active   1           1               90d
upbound-provider-family-aws-fec919bd2218   True      1          xpkg.upbound.io/upbound/provider-family-aws:v0.47.1   Active                               90d
```

**Comment by dmaggi** [comment]
Thanks for the quick response @jbw976 i already recreated the`providerconfig` and all seems to works properly. Any way, I'm not sure how can we upgrade Provider version without having this issues.

I need to do the same update in other environment. How should i proceed? With the 2 providers I defined (iam and s3), was easy to upgrade from 0.47 to 1.4 version, but as i mention the problem was with the upbound-provider-family-aws provider.

kubectl get providers; kubectl get providerrevision:
```
kubectl get providers.pkg.crossplane.io; kubectl get providerrevision

NAME                          INSTALLED   HEALTHY   PACKAGE                                               AGE
aws-iam                       True        True      xpkg.upbound.io/upbound/provider-aws-iam:v0.47.1      90d
aws-s3                        True        True      xpkg.upbound.io/upbound/provider-aws-s3:v0.47.1       90d
upbound-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v0.47.1   90d
NAME                                       HEALTHY   REVISION   IMAGE                                                 STATE    DEP-FOUND   DEP-INSTALLED   AGE
aws-iam-fc4c8e7f6d42                       True      1          xpkg.upbound.io/upbound/provider-aws-iam:v0.47.1      Active   1           1               90d
aws-s3-608e381115ec                        True      1          xpkg.upbound.io/upbound/provider-aws-s3:v0.47.1       Active   1           1               90d
upbound-provider-family-aws-fec919bd2218   True      1          xpkg.upbound.io/upbound/provider-family-aws:v0.47.1   Active                               90d
```
