### ISSUE TITLE
Selecting Array Elements with the Custom Columns Kubernetes CLI Output

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#5659]
How can I use the --output=custom-columns option for the the Kubernetes CLI (kubectl) to select array elements?

examnple: kubectl get service -o=custom-columns='NAME:.metadata.name,IP:.spec.clusterIP,PORT:.spec.ports[*].targetPort'

I'd like to use the same for kubectl get managed

EXTERNAL-NAME | NAME | READY | SYNCED

**Comment by bobh66** [comment]
@diegoavitorino  this seems to work:

`kubectl get managed -o=custom-columns='NAME:.metadata.name,READY:.status.conditions[?(@.type=="Ready")].status,SYNCED:.status.conditions[?(@.type=="Synced")].status'`

**Comment by diegoavitorino** [comment]
Thanks a lot @bobh66
