### ISSUE TITLE
Sane defaults for API types

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#566]
It is occasionally desirable to use different data types within the Go types that represent Crossplane's API resources than are recommended by the [Kubernetes API guidelines](https://github.com/kubernetes-sigs/controller-tools/issues/155). One such example is our `ConditionedStatus`. We want `ConditionedStatus` to behave like a map of objects keyed on the condition type, but the guidelines require us to treat it as an array of objects.

In other cases it would be nice to use different data types in order to leverage the zero value for sane defaults. `BindingStatus` is an example of this case. Ideally the zero value of a `BindingPhase` would be `Unbindable`.

Both of the above cases could be handled by custom JSON marshal and unmarshal functions that marshaled the type most useful in Crossplane's Go codebase into the type required by the API conventions - for example `BindingPhase` could be an `iota` integer with each integer marshaling to a string name per https://github.com/crossplaneio/crossplane/pull/325.

This is not currently possible because controller-tools, which generates our CRD OpenAPI v3 schema does not support overriding the autodetected JSON type of a Go type per https://github.com/kubernetes-sigs/controller-tools/issues/155.

**Comment by displague** [comment]
How does this issue change if we have a defaulting webhook https://github.com/crossplaneio/crossplane/issues/1152? 
When specifying OpenAPI defaults, does that require the webhook to enact the value?

We're using a newer controller-tools and controller-runtime version since this issue was created.

**Comment by negz** [comment]
I'm just going to close this out; the way we're doing this today is inline with typical Kubernetes patterns.
