### ISSUE TITLE
DynamoDB Table Resource Based Policy Support

### ISSUE THREAD

**Issue by ShayYannay** [crossplane/crossplane#5664]
DynamodDB recently (20th March 2024) started to support Resource Based Policy per table (see blog post in https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-resource-based-policies/)

Terraform AWS provider also started supporting this feature starting from version 5.43.0 (see in here https://registry.terraform.io/providers/hashicorp/aws/5.43.0/docs/resources/dynamodb_resource_policy)

From what I saw DynamoDB Crossplane provider uses version 5.31.0 on the current official version of 1.14.0, unfortunately still without the Resource Based Policy feature (https://marketplace.upbound.io/providers/upbound/provider-aws-dynamodb/v1.4.0/resources/dynamodb.aws.upbound.io/Table/v1beta1).

Saw there is an active PR to upgrade to terraform version 5.46.0 (see in here - https://github.com/crossplane-contrib/provider-upjet-aws/pull/1271)

Appreciate if you can share time estimation when the Resource Base Policy will be exposed, please comment if any of the assumptions I made above are not correct.

Thanks!!

**Comment by negz** [comment]
@ShayYannay Please raise this against https://github.com/crossplane-contrib/provider-upjet-aws. I'd move the issue, but unfortunately I can't move from the crossplane org to the crossplane-contrib org.

**Comment by ShayYannay** [comment]
Issue was opened in here https://github.com/crossplane-contrib/provider-upjet-aws/issues/1307 (if anyone looking for it)
