### ISSUE TITLE
Crossplane Helm Chart: Unnecessary RBAC permissions

### ISSUE THREAD

**Issue by Yseona** [crossplane/crossplane#5743]
### Description

The bug is that the Deployment `crossplane-rbac-manager` and `crossplane` in the charts has too much RBAC permission than they need. The service account of `crossplane-rbac-manager` is bound to a clusterrole([rbac-manager-clusterrole.yaml](https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/templates/rbac-manager-clusterrole.yaml)) with the following permissions:

- `bind/escalate/patch/update` verb of `clusterroles` resource (ClusterRole)
- `update` verb of the `clusterrolebindings` resource (ClusterRole)

And the service account of `crossplane` is also bound to a clusterrole ([clusterrole.yaml#L4](https://github.com/crossplane/crossplane/blob/b404cd0c67edd859c47df06a6e3c718d8951127d/cluster/charts/crossplane/templates/clusterrole.yaml#L4)) with the following permissions:

- `create/patch/update/delete` verb of the `deployments/services` resource (ClusterRole)

After reading the source code of [crossplane](https://github.com/crossplane/crossplane), I didn't find any Kubernetes API usages using these permissions. Besides, some of these unused permissions may have potential risks. For example, if malicious users gain control of a Kubernetes node running a `crossplane` pod, they can use the "`create deployments`" permission to create privileged containers with malicious container images.

Therefore, these permissions should be rechecked to determine if they are truly unnecessary. If they are, the issue should be fixed by removing the unnecessary permissions or or other feasible methods. 

**To Reproduce**

Use the helm chart with default values.

**Comment by phisco** [comment]
We do need permissions to create deployments and services to deploy providers and functions, can't speak about the rbac-managers permissions, I'll need to check the code further.

**Comment by negz** [comment]
RBAC manager dynamically manages cluster roles for provider. It needs bind/escalate/patch/update.

We're aware escalate is a security risk, which is why the RBAC manager is a separate component. If you're concerned about its privileges you can avoid deploying it, at the expense of needing to manually curate RBAC cluster roles for providers.
