### ISSUE TITLE
CII best practices

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#58]
We should consider implementing and following the Core Infrastructure Initiative (CII) Best Practices, similar to the Rook project which is being tracked at https://bestpractices.coreinfrastructure.org/en/projects/1599#

There are a lot of great items in there that demonstrate a mature and well managed project.

However, we need to figure out the relation to CLOMonitor: https://clomonitor.io/projects/cncf/crossplane.  Are both required for Graduation? Should we only focus on one of them?

**Comment by negz** [comment]
https://bestpractices.coreinfrastructure.org/en/projects/3260

Started the process for Crossplane.

**Comment by negz** [comment]
This doesn't seem like a super high priority. I'm going to close the issue - please reopen if we feel it's still important.

**Comment by caniszczyk** [comment]
reopen as this is required for CNCF graduation eventually :)

**Comment by ytsarev** [comment]
Looks like something to keep around for graduation.

**Comment by jeanduplessis** [comment]
> [bestpractices.coreinfrastructure.org/en/projects/3260](https://bestpractices.coreinfrastructure.org/en/projects/3260)
> 
> Started the process for Crossplane.

@negz do you still have the login details for this entry? I'll be focusing on driving this forward over the next release.

**Comment by negz** [comment]
@jeanduplessis I logged in using GitHub. If you do, are you able to manage the Crossplane project?

**Comment by jeanduplessis** [comment]
@negz I'm able to login with GitHub and I can see the Crossplane org already has permission for the app, but I don't have any permission to update the Crossplane project on there. Is there an option to add users to the project somewhere?

**Comment by jbw976** [comment]
@jeanduplessis on the best practices site, can you go to Account -> Profile and then let me know your user ID from that page? e.g. mine is https://www.bestpractices.dev/en/users/2248.

With that, I think I can follow https://github.com/coreinfrastructure/best-practices-badge/issues/1976#issuecomment-1593285210 to add your best practices user ID to the list of folks that can edit the Crossplane project badge 🤓

**Comment by jeanduplessis** [comment]
@jbw976 `29398`

**Comment by jbw976** [comment]
Give it a try again now @jeanduplessis, can you edit https://www.bestpractices.dev/en/projects/3260 now? 

> (Advanced) What other users have additional rights to edit this badge entry? Currently: [29398]

**Comment by jeanduplessis** [comment]
@jbw976 all good 👍

**Comment by jeanduplessis** [comment]
I've updated the relevant checks and the project is up to a score of 90: https://www.bestpractices.dev/en/projects/3260

@phisco I would appreciate if you could review the security checks that are set the a `?` still and confirm whether the check is Met, Unmet or N/A.

**Comment by jeanduplessis** [comment]
The entry on [bestpractices.dev/en/projects/3260](https://www.bestpractices.dev/en/projects/3260) has been updated and we are now compliant.

PR to add badge to README file: https://github.com/crossplane/crossplane/pull/5231
