### ISSUE TITLE
crossplane with argocd not working correctly

### ISSUE THREAD

**Issue by pablofilgueira91** [crossplane/crossplane#5810]
hello, I followed this documentation but it didn’t work for me
URL: https://docs.crossplane.io/latest/guides/crossplane-with-argo-cd/
I am trying to use crossplane with argocd, but it does not correctly show me the relationship between the claim (azresourcegroup) and the XR (xazresourcegroup).
If it correctly shows the relationship between the MR (resourcegroup) and the XR (xazresourcegroup)
I suppose it is because the XR does not have ownerreference to the claim since it uses claimref and argocd should not understand it
And the MR does have an owner reference to the XR
This is how I graph it in argocd
![image](https://github.com/crossplane/crossplane/assets/105305544/a16dd566-5f5f-46c7-a61e-7a7f04fd0ca8)
and this is how I should graph it
![image](https://github.com/crossplane/crossplane/assets/105305544/0193d0d8-9eb3-4e04-917c-5b25a7c19601)

this is de claim 
```
apiVersion: azure.upbound.io/v1alpha1
kind: azresourcegroup
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: pablo-test:azure.upbound.io/azresourcegroup:pablo/rg-testpablo-cnt
  name: rg-testpablo-cnt
  namespace: pablo
spec:
  compositeDeletePolicy: Background
  compositionRef:
    name: xazresourcegroups
  compositionRevisionRef:
    name: xazresourcegroups-cd8c899
  compositionUpdatePolicy: Automatic
  resourceRef:
    apiVersion: azure.upbound.io/v1alpha1
    kind: Xazresourcegroup
    name: rg-testpablo-cnt-fb6wx
  servicename: testpablo-cnt
```

the XR
```
apiVersion: azure.upbound.io/v1alpha1
kind: Xazresourcegroup
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: pablo-test:azure.upbound.io/azresourcegroup:pablo/rg-testpablo-cnt
  labels:
    crossplane.io/claim-name: rg-testpablo-cnt
    crossplane.io/claim-namespace: pablo
    crossplane.io/composite: rg-testpablo-cnt-fb6wx
  name: rg-testpablo-cnt-fb6wx
spec:
  claimRef:
    apiVersion: azure.upbound.io/v1alpha1
    kind: azresourcegroup
    name: rg-testpablo-cnt
    namespace: pablo
  compositionRef:
    name: xazresourcegroups
  compositionRevisionRef:
    name: xazresourcegroups-cd8c899
  compositionUpdatePolicy: Automatic
  resourceRefs:
  - apiVersion: azure.upbound.io/v1beta1
    kind: ResourceGroup
    name: rg-prod-testpablo-cnt
  servicename: testpablo-cnt
  writeConnectionSecretToRef:
    name: aab9545b-c514-45e1-a32f-81dc7e024f8e
    namespace: crossplane-system
```

and the MR
```
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    crossplane.io/composition-resource-name: rg
    crossplane.io/external-create-pending: "2024-07-02T17:32:12Z"
    crossplane.io/external-create-succeeded: "2024-07-02T17:32:12Z"
    crossplane.io/external-name: rg-prod-testpablo-cnt
  creationTimestamp: "2024-07-02T17:32:12Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: rg-testpablo-cnt-fb6wx-
  generation: 2
  labels:
    crossplane.io/claim-name: rg-testpablo-cnt
    crossplane.io/claim-namespace: pablo
    crossplane.io/composite: rg-testpablo-cnt-fb6wx
  name: rg-prod-testpablo-cnt
  ownerReferences:
  - apiVersion: azure.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Xazresourcegroup
    name: rg-testpablo-cnt-fb6wx
    uid: aab9545b-c514-45e1-a32f-81dc7e024f8e
  resourceVersion: "450102246"
  uid: 73e6bca4-4e02-4e3c-8b45-cd5bda6c5b97
spec:
  deletionPolicy: Delete
  forProvider:
    location: East US 2
    tags:
      feature: testpablo-cnt
      provider: crossplane
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```

argocd version: 5.50.1
crossplane version: 1.15.2

**Comment by duizabojul** [comment]
A cluster scoped resource cannot have a namespace scoped resource as owner. Even if you try to add it to ownerreferences, argo will ignore it.

**Comment by pablofilgueira91** [comment]
> A cluster scoped resource cannot have a namespace scoped resource as owner. Even if you try to add it to ownerreferences, argo will ignore it.
> 
> The only way to display XR created by a claim in argo UI is to use annotation (see https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/#non-self-referencing-annotations)

Yes, of course, I know.
I am using the application.resourceTrackingMethod annotation but argocd shows it this way.
Is there a way for Argo to show that the XR and the claim are linked?
It would be a way for argocd to recognize the claimref but I don't know if that will be possible.
![image](https://github.com/crossplane/crossplane/assets/105305544/629d15cf-8aeb-4dd1-8cb7-8b6bc35604ac)

**Comment by duizabojul** [comment]
It is indeed not possible to customize how argo "link" resources, it can only use ownerreferences to create the linking in UI, so in this case it is impossible to link a namespaced claim to a cluster scoped XR.
