### ISSUE TITLE
providerconfigs permissions missing in clusterrole after upgrading

### ISSUE THREAD

**Issue by mzameer777** [crossplane/crossplane#5820]
### What happened?
After upgrading from 1.15.2 to 1.16.0, and also upgrading all AWS providers from v1.4.0 to v1.8.0, I started encountering permission issues in the provider-ec2 pod. Below is the error message I'm seeing in ec2 provider pod

`E0708 18:08:24.037238       1 reflector.go:147] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.ProviderConfig: failed to list *v1beta1.ProviderConfig: providerconfigs.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-aws-ec2-f38479bdab83" cannot list resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope`

kubectl describe providerrevision provider-aws-ec2-f38479bdab83

`Warning  SyncPackage  24m (x73 over 65m)  packages/providerrevision.pkg.crossplane.io  post establish runtime hook failed for package: provider package deployment is unavailable with message: Deployment does not have minimum availability.`

In the providerrevision there is no reference to `providerconfigs` crd, and it's not adding the rbac permissions in the provider clusterrolebinding

### How can we reproduce it?
After performing an upgrade from 1.15.2 to 1.16.0, and upgraded all aws providers from v1.4.0 to v1.8.0. The upgrade was done using helm. 

### What environment did it happen in?
Crossplane version: 1.16.0
Kubernetes version: v.129
Kubernetes distribution: EKS

**Comment by haarchri** [comment]
looks like your family provider is installed from a different registry then the other providers - but we have a check that the providers belongs to a family needs to be installed from the same registry to get the rbac rights for providerconfigs https://github.com/crossplane/crossplane/blob/master/internal/controller/rbac/provider/roles/reconciler.go#L300-L307

**Comment by mzameer777** [comment]
It makes sense now why it is not adding the RBAC permissions, But when I deploy the family provider using the same registry, the other providers are failing to resolve dependency, with error: `cannot resolve package dependencies: missing dependencies: [xpkg.upbound.io/upbound/provider-family-aws]`

![Screenshot 2024-07-09 at 12 21 24 AM](https://github.com/crossplane/crossplane/assets/159965780/4a80e9c9-7f53-49b3-8737-dd8fee27921b)

It Looks like a aws-provider issue, but is there a global configuration to get a registry for all providers?
