### ISSUE TITLE
Race condition when creating and deleting a Provider within a short time period

### ISSUE THREAD

**Issue by r0bnet** [crossplane/crossplane#5867]
### What happened?
We have some e2e tests that check if a certain user within Kubernetes is allowed to create a Provider or not. Another e2e test checks that there are no `ClusterRoleBindings` that have a `ClusterRole` that doesn't exist, but this fails regularly.

What happens:

- e2e test checks that cluster-admin is allowed to create a Provider (using `dummy-provider` in the tests)
- the provider gets deleted after the assertion was successful
- the e2e test runs to see that there are no missing clusterroles in any ClusterRuleBinding

This test fails once in a while because there is a potential race condition. What I believe the root cause is:
When the provider gets created, the rbac-manager creates a `ServiceAccount`, some `ClusterRoles` and finally the `ClusterRoleBinding`. When a provder gets deleted, it's probably going the other way around: Deleting the `ClusterRoleBinding`, then `ClusterRole` and the `ServiceAccount`.

When the new provider gets removed in a very short period after its creation, it seems as if the `ClusterRole` and the `ServiceAccount` are being removed but the `ClusterRoleBinding` is not. I assume that the deletion already starts when the `ClusterRoleBinding` is not there yet but the other resources. Thus the controller removes the `ClusterRole` and the `ServiceAccount`. However the creation of the provider is still trying to create the `ClusterRoleBinding` and that's being left over afterwards. I could reproduce this behavior quite often but it didn't happen all the time.

When my assumption is correct, then some kind of synchronization or locking might help.

In our e2e tests we now wait for the `ClusterRoleBinding` to exist before we're continuing with the asserts or the clean up. This fixed the issue.

### How can we reproduce it?

Automatically create and delete a provider within a very short period and check if there is a `ClusterRoleBinding` left in the cluster for the provider but no `ClusterRole`. Running this a lot of times should trigger the described issue from above.

### What environment did it happen in?

Crossplane version: 1.15.2

<sub>Robin Afflerbach <robin.afflerbach@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by turkenh** [comment]
Crossplane package manager mostly leverages Kubernetes garbage collection for cleaning things up rather than explicit deletes. Hence, some (varying) delays are expected after the provider resource is deleted. 

There is also Provider -> ProviderRevision relation, which could add more uncertainty. For example, when you delete and recreate the Provider, the initial ProviderRevision might still be around. I am wondering if ensuring ProviderRevision is gone before recreating the Provider could give more stability to your tests.
