### ISSUE TITLE
Compositions using functions and composite resources cannot reach ready state.

### ISSUE THREAD

**Issue by rj-devberg** [crossplane/crossplane#5872]
### What happened?
- a composition and composite that creates an s3 bucket, and other s3 provider managed resources related to the bucket:  `xrBucket`
- a custom function in python that can add any number of xrBucket composite resources as resources to a composition
- a composition using the above function called `multibucket`

- create a composite resource or claim for `multibucket`

Issue: the `multibucket` never reaches a ready state even when the added resources (multiple `xrBuckets`) do reach a ready state. 

### How can we reproduce it?
follow the above steps

### What environment did it happen in?
Crossplane 1.15

* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`): v1.30.3
-->

**Comment by phisco** [comment]
Hi @rj-devberg, the composite resource will result ready when all desired composed resources returned by the pipeline are ready, but readiness is not defined as the Ready condition, but an additional field you can set on desired resources: https://github.com/crossplane/function-sdk-python/blob/main/crossplane/function/proto/v1beta1/run_function_pb2.pyi#L183

**Comment by bobh66** [comment]
Would function-auto-ready help with this?  https://github.com/crossplane-contrib/function-auto-ready/
