### ISSUE TITLE
Usage: Old usages persist after updating composition 

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#5880]
### What happened?

After deploying a composition that includes some Usages, subsequent changes were made to the Usages within the composition and deployed again. Although the Crossplane beta trace indicates that the composition was updated successfully, running kubectl get usages reveals that both the original and new Usages are present in the cluster. This issue is not reflected in the Crossplane beta trace, but it causes interference between the old and new Usages, leading to a failure when attempting to delete the composed resource.

### How can we reproduce it?

1. Deploy a composite of a composition including some usages.
2. Make some changes to the composition, resulting in the deletion of some existing Usages, and deploy the updated composition. 
3. Run `kubectl get usages` on the cluster. 
4. Observe that the old usage is present. 
5. Attempt to delete the composite and encounter blockage due to the old usage still being around.

**Comment by turkenh** [comment]
There is a special handling in the usage implementation to prevent deletion of Usages together with the used resource when they are part of the same composition. This explains why the old usages sticking around, and this could be resolved by manually removing the finalizer on the old Usages. See the related section [in the design](https://github.com/crossplane/crossplane/blob/master/design/one-pager-generic-usage-type.md) for more:

> Preventing early deletion of the Usage:

> Typically, we expect a Usage resource to be defined as part of the same composition as the using and used resources. This means the Usage will get the delete request when the composite resource is deleted. In this case, the controller will prevent the deletion of the Usage until the using resource is deleted with the help of a finalizer.

From the Usage point of view, there is no (easy / not hacky?) way to differentiate whether the composed resource is deleted or the composition updated since, in both cases, the Usage resource gets a deletion request (deletionTimestamp set on the Usage). If we simply let the Usage disappear in this case, then we won't be able to block the used resource if they are part of the same composite. This is why we have the above, and checking the implementation, I see we prevent the deletion of Usage with the help of a finalizer until the using resource disappears.

I cannot immediately think of an easy fix here other than documenting the behavior, and I am open to any suggestion.

**Comment by turkenh** [comment]
I gave this a try with the following logic:

![image](https://github.com/user-attachments/assets/929bf877-d380-450e-adf2-4a11145fa56d)

Basically, I tried to infer whether Usage is part of a composition or not based on the fact that composites put a controller ref to Usages. Apart from being unintuitive and complex, this could fix the problem here. However, while testing my implementation, I realized that Kube GC removes controller ref from the Usage object when composite is deleted. In this case, the usage controller has no chance to differentiate whether it were part of a composite and it was deleted (hence should wait for using resource) or it was not part of a composite at all 😕

**Comment by turkenh** [comment]
Another idea that is coming to my mind is based on whether the usage has the `crossplane.io/composite` label or not. Basically we will wait for using resources deletion if this label exists.
- If standalone Usage => no label => don't wait for using resource deletion
- If composed Usage => has label => wait for using resource deletion
- If composed initial but dropped from the composition later => label removed* =>  don't wait for using resource deletion

* this would require a change in the composition controller such that it will remove this label before deleting a composite.

![image](https://github.com/user-attachments/assets/c70f109e-5229-4897-98bf-c11a7ca27b8c)

**Comment by jeanduplessis** [comment]
@StupidScience, a solution won't make it in time for the v1.18 release. We'll look into this again during the v1.19 release cycle.
