### ISSUE TITLE
Subnet Reconciliation Failing for Crossplane + AWS

### ISSUE THREAD

**Issue by vallabhsonar** [crossplane/crossplane#5933]
Hi,

I had created a subnet using below yaml and the subnet creation was successful.

`apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: provider-subnet
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: crossplane-vpc
    tags:
      - key: Name
        value: cp-subnet
    cidrBlock: 10.0.1.0/24
    availabilityZone: us-east-1a
  providerConfigRef:
    name: aws-provider
`
However, upon manual deletion of subnet from the AWS console. Crossplane should proceed with reconcile of the subnet which is currently failing with below error:

`create failed: failed to create the Subnet resource: api error InvalidParameterCombination: The parameter availabilityZone cannot be used with the parameter availabilityZoneId`

![image](https://github.com/user-attachments/assets/d12b21c3-9e2b-4a6b-a772-8a10ebabda57)

### What environment did it happen in?
Crossplane version: v1.16

* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`): v1.30.3
* OS (e.g. from /etc/os-release): Ubuntu 20.04.6

**Comment by jbw976** [comment]
Is it possible for you to close and then re-open this issue in the https://github.com/crossplane-contrib/provider-upjet-aws repo? Github unfortunately doesn't support transferring issues across organizations. Thank you!

**Comment by vallabhsonar** [comment]
Hi @jbw976,
This issue has been fixed when we switched to subnet from the `apiVersion: ec2.aws.upbound.io/v1beta1`

Hence, closing this ticket.
`
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: ctest-cp-subnet-2
spec:
  forProvider:
    region: us-east-1
    tags:
      Name: ctest-cp-subnet-2
    vpcIdRef:
      name: ctest-crossplane-vpc
    cidrBlock: 10.0.2.0/24
    availabilityZone: us-east-1a
  providerConfigRef:
    name: aws-provider-upbound
    `
