### ISSUE TITLE
[secret syncing] Missing secrets are silently ignored during sync

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#597]
### What happened?

I was going through the wordpress gcp example, and when I got to the step where it spins up the wordpress application on the GKE cluster, I noticed that the pod failed to become healthy, because it references a secret that doesn't exist in the cluster, due to the wordpress example being misconfigured to not export a secret from the database. Meanwhile, in crossplane, the wordpress deployment shows up as submitted:

```
kubectl get kubernetesapplicationresources -n complex wordpress-demo-deployment
NAME                        TEMPLATE-KIND   TEMPLATE-NAME   CLUSTER                  STATUS
wordpress-demo-deployment   Deployment      wordpress       wordpress-demo-cluster   Submitted
```

There is [a line which marks the status as a reconcile error](https://github.com/crossplaneio/crossplane/blob/c9c71f82cfcb746491b5207000f6ba96f4487a4d/pkg/controller/workload/kubernetes/resource/resource.go#L522) when a secret is not found, but I believe what happens is that since the secret is never added to the list of secrets, it never turns into a fatal error. Later in the same reconciliation pass, the status is [probably overwritten](https://github.com/crossplaneio/crossplane/blob/c9c71f82cfcb746491b5207000f6ba96f4487a4d/pkg/controller/workload/kubernetes/resource/resource.go#L206) to be `Submitted`. Is this the intended behavior?

I do see that #555 complicates the situation a bit. I believe that some of the debuggability challenges could be addressed by adding some logging as described in #331, so maybe that's good enough for now.

### How can we reproduce it?

Go through the [wordpress gcp example](https://github.com/crossplaneio/crossplane/blob/c9c71f82cfcb746491b5207000f6ba96f4487a4d/docs/workloads/gcp/wordpress-gcp.md), and get through the step to spin up the application:

```
kubectl apply -f cluster/examples/workloads/kubernetes/wordpress-gcp/app.yaml
```

In GCP, you should be able to find the pod which fails due to the secret not existing.

### What environment did it happen in?
Crossplane version: c9c71f82cfcb746491b5207000f6ba96f4487a4d

**Comment by negz** [comment]
I believe this pertains to KubernetesApplication, which we're deprecating. I'm going to close this, as it won't be relevant going forward.
