### ISSUE TITLE
`render` doesn't pass Credentials to functions

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5975]
### What problem are you facing?

Support for functions to use credentials was added to Crossplane and the functions ecosystem with the following PRs for reference:

* core: https://github.com/crossplane/crossplane/pull/5543
* go sdk: https://github.com/crossplane/function-sdk-go/pull/140
* python sdk: https://github.com/crossplane/function-sdk-python/pull/63

In the `render` command, these credentials are not passed to the functions, so it's not possible to test the behavior of your function pipeline using credentials with `render`.

As another helpful resource, here's a demo showing functions credentials in action: https://github.com/jbw976/demo-xfn-creds. This demo must be run with a real function pipeline, it doesn't work with `render`.

### How could Crossplane help solve your problem?

`render` should be updated to also pass any available credentials to the functions that it calls. The code to do this is in the real/live [function pipeline](https://github.com/crossplane/crossplane/blob/release-1.17/internal/controller/apiextensions/composite/composition_functions.go#L308-L326), so something similar to that block probably needs to be added to the [`render` command](https://github.com/crossplane/crossplane/blob/release-1.17/cmd/crank/render/render.go#L230) before that `RunFunction()` call.

**Comment by cychiang** [comment]
Hi @jbw976 I opened #5976 for this issue. Please review it. 😄
