### ISSUE TITLE
Allow affinity configuration on Providers

### ISSUE THREAD

**Issue by fgiannetti** [crossplane/crossplane#5983]
### What problem are you facing?
When installing a new Provider it cannot be configured with any affinity properties to manage the pods schedule.
For example using this yaml

```apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v0.47.1
  runtimeConfigRef:
    name: aws-runtime-config
```

I cannot define some scheduling configuration to force the provider's pods to run in a specific node or nodegroup.

### How could Crossplane help solve your problem?
Maybe adding some affinity section in the provider spec? The Crossplane helmchart includes the affinity section for all its components but it cannot be added to Provider's pods.

I was searching for this feature and I cannot found any that helps me.
Thank you in advance!

**Comment by stevendborrelli** [comment]
Hello @fgiannetti , you should be able to configure affinity in the deploymentRuntimeConfig. See https://docs.crossplane.io/v1.16/api/#DeploymentRuntimeConfig-spec-deploymentTemplate-spec-template-spec-affinity

**Comment by fgiannetti** [comment]
Thanks @stevendborrelli for your answer! 
It perfectly works!
Sorry my blindness

Thank you again!
