### ISSUE TITLE
enable pruning where relevant for core Crossplane CRD's

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#599]
Kubernetes v1.15 introduced the [functionality for pruning fields](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields) that are not part of a CRD's OpenAPI v3.0 schema. This eliminates some potential security concerns and also enforces more consistency around in object data. It would be useful to implement this feature for core Crossplane CRD's where relevant.

Relevant Links:
- [Kubernetes v1.15 Release Blog Post](https://kubernetes.io/blog/2019/06/19/kubernetes-1-15-release-announcement/)
- [Pruning Description in Kubernetes Docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields)
- [Kubernetes v1.15 Release Notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#customresourcedefinitions-pruning)

**Comment by negz** [comment]
I think this is now the default (pruning unknown fields) now that we're using v1 CRDs.
