### ISSUE TITLE
crank/render: Function runtime context is not passed to runner

### ISSUE THREAD

**Issue by eric-carlsson** [crossplane/crossplane#5994]
### What happened?

Whilst debugging #5926 I observed that the docker stop function was correctly set up, but it was never called. Digging a bit further I found that the issue seems to stem from here: https://github.com/crossplane/crossplane/blob/ed4e659c5c217fb69958eeb75ce8daa65b63823c/cmd/crank/render/render.go#L105-L130

Note how `contexts` is created and populated, but it is never attached to `RuntimeFunctionRunner` before it is returned. Instead, this value defaults to the zero value which in this case is `nil`. Since [Go allows iterating over nil slices](https://groups.google.com/g/golang-nuts/c/gVgVLQU1FFE), this doesn't panic, it just yields no iterations. The result is that no stop handlers, which are attached to the context structs, are called.

### How can we reproduce it?

See #5926 for an example of how the bug manifests.

### What environment did it happen in?
Crossplane version: v1.17.1

Quick git blame shows this was introduced in https://github.com/crossplane/crossplane/commit/a808bf15cfc26d12471deda4ebcc45145382cc3e, so likely this has been included since v1.17 release, but I haven't looked to deep into it.

**Comment by jbw976** [comment]
Nice @eric-carlsson, thanks for taking the time to debug this, write it up, and share your suggestions for how this can be fixed! really appreciate that effort and contribution 🙇‍♂️
