### ISSUE TITLE
Consistent e2e failures on old branches

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#6085]
### What happened?

We have [observed](https://github.com/crossplane/crossplane/pull/6052#issuecomment-2453391331) consistent e2e failures for PRs against old branches (i.e. backports). It looks all the test suites except `environment-configs` fail, and this happens for all except the latest release branch.

### How can we reproduce it?

Open a PR against a release branch, for example: https://github.com/crossplane/crossplane/pull/6082

### What environment did it happen in?
Crossplane version: N/A

**Comment by turkenh** [comment]
Initial findings:

Consistent failure happens with `TestCrossplaneLifecycle/TestCrossplaneLifecycleUpgrade/UpgradeCrossplane` with a not so helpful failure message: 

```
env.go:428: cannot upgrade Helm chart: Error: UPGRADE FAILED: context deadline exceeded: exit status 1
```

The reason why environment config test suite if not failing is that it skips that specific test case since it is configured to run `TestSuiteLifecycle` instead of `default` test suite and UpgradeCrossplane was not included into lifecycle test suite (possibly unintentional).

**Comment by turkenh** [comment]
Prior to cutting v1.18, I [could see](https://github.com/crossplane/crossplane/pull/6052#issuecomment-2453391331) tests on release-1.16 passed at least once on my local. However, when I just try the following on my local, I could find some hints on why this test is indeed failing:

```shell 
earthly -i -P +e2e --FLAGS="-v=4 -test.failfast -destroy-kind-cluster=false -test.run ^TestCrossplaneLifecycle"
# Fails and gives me the shell

/go # kubectl -n crossplane-system get pods
NAME                                         READY   STATUS                  RESTARTS      AGE
crossplane-cbd886c65-9nxxj                   1/1     Running                 0             4m24s
crossplane-cdc5f9bcc-jkzpv                   0/1     Init:CrashLoopBackOff   5 (51s ago)   3m36s
crossplane-rbac-manager-7b85bdc449-gnwwk     1/1     Running                 0             3m36s
provider-nop-ecc25c121431-6c767cbf7b-zswh7   1/1     Running                 0             4m3s
/go # kubectl -n crossplane-system logs -f crossplane-cdc5f9bcc-jkzpv -c init
error: container init is not valid for pod crossplane-cdc5f9bcc-jkzpv
/go # kubectl -n crossplane-system logs -f crossplane-cdc5f9bcc-jkzpv -c crossplane-init
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"TLS CA secret is complete.","Step":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"TLS secret contains server certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-server"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"TLS secret contains client certificate.","Step":"TLSCertificateGenerator","secret":"crossplane-tls-client"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"Step has been completed","Name":"TLSCertificateGenerator"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
{"level":"info","ts":"2024-11-11T08:55:46Z","logger":"crossplane","msg":"Step has been completed","Name":"CoreCRDsMigrator"}
crossplane: error: cannot initialize core: cannot apply crd: cannot patch object: CustomResourceDefinition.apiextensions.k8s.io "environmentconfigs.apiextensions.crossplane.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
/go # helm ls -n crossplane-system
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
/go # helm ls -n crossplane-system -a
NAME      	NAMESPACE        	REVISION	UPDATED                                	STATUS         	CHART           	APP VERSION
crossplane	crossplane-system	2       	2024-11-11 08:53:02.301868588 +0000 UTC	pending-upgrade	crossplane-0.0.1	0.0.1
/go # helm history -n crossplane-system crossplane
REVISION	UPDATED                 	STATUS         	CHART            	APP VERSION	DESCRIPTION
1       	Mon Nov 11 08:52:14 2024	deployed       	crossplane-1.18.0	1.18.0     	Install complete
2       	Mon Nov 11 08:53:02 2024	pending-upgrade	crossplane-0.0.1 	0.0.1      	Preparing upgrade
```

It looks like the test case first installs the latest Crossplane (i.e. v1.18.0), and trying to upgrade (actually downgrade) to a version built from this brach (i.e. v1.17 or v1.16). This test case makes sense when running on master and even on the latest release branch (release-1.18) but not the older ones.

We would probably need to find a way to detect / pass through the release branch and install the latest available release for that version to upgrade from 🤔

**Comment by jbw976** [comment]
Thanks for opening this @turkenh!! I added it to the e2e reliability epic, that I would love for some time/progress on. Releasing is painful with our lack of confidence due to e2e test unreliability. 

https://github.com/crossplane/crossplane/issues/5671
