### ISSUE TITLE
Reconciliation not working for ec2 instance

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [crossplane/crossplane#6132]
I am using crossplane provider ec2 (xpkg.upbound.io/upbound/provider-aws-ec2:v1.4.0) to create an ec2 instance but the reconciliation is not working. When I delete the ec2 instance from AWS Management Console, the expected behaviour is for crossplane's reconciliation machanism to kick in and recreate the instance which is something I tested with older providers but it doesn't seem to happen. 

It is throwing this error:- 

 Last Transition Time:  2024-11-24T19:25:21Z                                                                                                                                       │
│     Message:               async create failed: failed to create the resource: [{0 creating EC2 Instance: UnsupportedOperation: The t2.micro instance type does not support specifyin │
│ g CpuOptions.                                                                                                                                                                         │
│                            status code: 400, request id: 2b19511f-0314-47b4-9b4e-e0a893d31026  []}]   Last Transition Time:  2024-11-24T19:25:21Z

**Comment by bobh66** [comment]
This is probably better dealth with in https://github.com/crossplane-contrib/provider-upjet-aws

**Comment by Sir-gits-a-lot** [comment]
Closing this one as it is duplicate of https://github.com/crossplane/crossplane/issues/6133.
