### ISSUE TITLE
Cannot delete compositionRevisionSelector 

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane/crossplane#6144]
### What happened?
Once a matchLabel expression is added to claim's `spec.compositionRevisionSelector.matchLabels` field, it cannot be removed.
This leads to issues when a label is mistyped or when we want to go back to a different selector.

### How can we reproduce it?
Take any claim with `spec.compositionUpdatePolicy: Automatic` and add a valid compositionRevisionSelector matchLabel, e.g.

```yaml
compositionRevisionSelector:
  matchLabels:
    existing-label: value
```

The claim will stick to that composition, as expected.

Now try to remove the matchLabel, so that the claim goes back to "latest" composition revision, Crossplane will roll it back.

```shell
kubectl label compositionrevision xcompositiontest.foo.bar-6c3bd11 existing-label-

kubectl patch --type=json -p="[{'op': 'remove', 'path': '/spec/compositionRevisionSelector'}]" compositiontest/test            
compositiontest.foo.bar/test patched

kubectl get -oyaml compositiontest/test | yq '.spec.compositionRevisionSelector'                                                 
matchLabels:
  existing-label: value
```

Checking the claim shows that Crossplane is managing the matchLabels field:

```yaml
  - apiVersion: foo.bar/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"finalizer.apiextensions.crossplane.io": {}
      f:spec:
        f:compositionRef:
          .: {}
          f:name: {}
        f:compositionRevisionRef:
          .: {}
          f:name: {}
        f:compositionRevisionSelector:
          .: {}
          f:matchLabels:
            .: {}
            f:existing-label: {}
        f:compositionUpdatePolicy: {}
        f:resourceRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
    manager: crossplane
    operation: Update
    time: "2024-11-28T08:28:58Z"
```

### What environment did it happen in?
Crossplane version: 
Tested with both 1.17.1 and 1.18.0

**Comment by bobh66** [comment]
Removing object attributes requires server-side apply - https://docs.crossplane.io/latest/concepts/server-side-apply/

**Comment by fernandezcuesta** [comment]
Thanks for the hint! Does this apply to Composition Revisions too?
