### ISSUE TITLE
Update SonarCloud rule for "Add or update the header of this file"

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#678]
It looks like the current ruleset for SonarCloud has a code smell rule for license headers on files that needs to be updated.

> Track lack of copyright and license headers

> Each source file should start with a header stating file ownership and the license which must be used to distribute the application.

> This rule must be fed with the header text that is expected at the beginning of every file.

I think the issue here is that our license headers do not state "file ownership", so we are always failing this code smell rule.

Here is the beginning of their example compliant header, showing file ownership:
```
/*
 * SonarQube, open source software quality management tool.
 * Copyright (C) 2008-2013 SonarSource
 * mailto:contact AT sonarsource DOT com
```

As stated above, we can feed the rule with out specific header text so that the rule learns the format that we want in our codebase.  This would likely fix all the instances of this code smell.

**Comment by soorena776** [comment]
I am running into this issue in #722 as well.

**Comment by negz** [comment]
We don't use Sonarcloud anymore. :)
