### ISSUE TITLE
Consider using a Service for connecting to a service vs. a secret

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#70]
Currently we use use a `host` or `url` field inside a connection secret object. We should consider using a `Service` object for that instead. Possibly using an ExternalIP or something else.

**Comment by negz** [comment]
@bassam Just saw this issue - I think managed service endpoints will be far more consumable as a predictably named `ExternalName` or `ExternalIP` `Service`. I made a similar suggestion in https://github.com/crossplaneio/crossplane/issues/361.

**Comment by hwinkel** [comment]
what about a proper full qualified UR notation for service endpoints, they much more rich as we think coming from just the web... 

Or a proper "model" Defingig service Parameters. In any case the connection secrets should remain secured.
