### ISSUE TITLE
Move examples folder from cluster to the root directory

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#716]
### What problem are you facing?

The current examples folder is buried in [cluster] folder, which has two issues:
- Lower visibility for users who want to try the examples
- Lack of logical organization, as the cluster folder is mostly addressing other areas

[cluster]: https://github.com/crossplaneio/crossplane/tree/master/cluster

**Comment by negz** [comment]
The entire `cluster/` directory is pretty unintuitive; I suspect it's an artifact of copying our repo structure from github.com/kubernetes/kubernetes?

**Comment by nchetan** [comment]
Do you still need help with this issue?
I can help you with the move and fixing any build/test issues if you need it.

I am looking to contribute to a project over a period of 2-3 weeks. 

If this works, I can help with following workflow. Let me know if that works for you.

1. Fork the project to my account
2. Create the change in mainline (or it's equivalent branch. if you prefer a separate branch, please let me know)
3. Push the changes to my fork and make a "pull/merge" request from the clone.

Here are questions that I have

1. What tests should I be using to verify if things are done right? Do you have any developer workflow to verify my changes?
2. Whom should i contact once all the changes are in place?

Let me know if you have any questions

cheers
Chetan
P.S. I am on slack. I can join a slack channel to sync if needed.

**Comment by hasheddan** [comment]
@nchetan thanks for being willing to help out here! A couple of things:
- Yes, I do think we would like for these to be moved to a top level `examples` dir
- Some of the examples likely need to be removed and / or updated, and we would love your help with that also if interested
- Your PR flow sounds right, but check out https://github.com/crossplane/crossplane/blob/master/CONTRIBUTING.md for more info :)
- Please do feel free to join us on http://slack.crossplane.io/ 🙂 
- You can tag me for review on any of your changes 👍

**Comment by nchetan** [comment]
Thanks @hasheddan 
i have joined the slack channel and am in #general and #dev channels. I will DM you on slack to continue the conversation.

Cheers
chetan
