### ISSUE TITLE
support image relocation for packages

### ISSUE THREAD

**Issue by glyn** [crossplane/crossplane#724]
### What problem are you facing?

Suppose the Crossplane control cluster does not have access to the internet but does have access to a private image registry. In order to run a stack in the control cluster, the stack’s images need to be _relocated_ to the private registry _and_ the stack needs to use the relocated image references instead of the original image references of the stack’s images.

For general information about image relocation, please see the README of https://github.com/pivotal/image-relocation.

So a basic requirement is to declare the set of image references for the stack’s images. This can be done, for example, by scanning the stack’s declarations looking for image references and then writing them in a file (e.g. `images.yaml`) in the stack.

There are two scenarios to deal with which need to be treated rather differently (see the above README for a description of the scenarios).

The simpler case is where there is a DMZ which has access to the internet and write access to the private registry. In this case, the images declared by the stack should be copied _verbatim_ from their original registries to the private registry and given relocated references that refer to the private registry. The stack’s declarations then need to have the original image references replaced by the relocated image references _before_ the stack is installed. When the stack runs, it will then pull its images from the private registry.

The more complex case is where there is no DMZ. In this case, the stack’s images need to be provided along with the stack (e.g. in a tarball) and should then be copied _verbatim_ from disk to the private registry and given relocated references that refer to the private registry.  The stack’s declarations need to be fixed up as before and the stack will again pull its images from the private registry when it runs.

So why would a Crossplane control cluster not have access to the internet? Typically, this would be when an enterprise uses Crossplane in a disconnected environment to manage clusters in that environment. Banks and other organisations with stringent security requirements tend to use such environments. (There are other reasons to use a private registry which are explained in the above README.)

### How could Crossplane help solve your problem?

There is no support for image relocation built in to kubernetes, so Crossplane could provide a way of declaring a stack's images, of relocating them to a (private) registry, and of modifying the stack's kubernetes configuration (e.g. deployment) to refer to the relocated image references instead of the originals.

There are a number of possible implementation approaches, including:

1. the `stacks` CLI tool could take responsibility for relocating a stack's images to a (private) registry and then pass the relocation mapping to the stack-manager so that it can modify the stack's kubernetes configuration.

2. the stack could be wrapped in a [CNAB](https://cnab.io/) bundle which defines the stack's images and then any CNAB runtime, such as the CNAB reference implementation [duffle](https://github.com/deislabs/duffle), could be used to relocate the stack's images and obtain a relocation mapping which could then be passed to the `stacks` CLI. Alternatively, the bundle's invocation image could drive the `stacks` CLI or a programmatic equivalent. Note that the invocation image could be run in a docker daemon or in a kubernetes cluster such as the Crossplane control cluster.

### Implementation note

`duffle` uses https://github.com/pivotal/image-relocation for reading from and writing to image repositories and for storing images in an OCI image layout on disk (typically for inclusion in a "thick bundle" for completely disconnected scenarios). Crossplane could also use this library.

### Further information

See the [discussion](https://crossplane.slack.com/archives/CKXQK4P27/p1566978331014800) in Crossplane slack.

**Comment by glyn** [comment]
@suskin wrote:
> In the case of stacks, the main constraint that would need to be thought about to support this use-case would be that currently, the source of the image in the stack's `install.yaml` is part of the stack artifact itself, which does not lend itself very well to pulling the image from a different place.

If you mean merely that the (original) image reference is included in `install.yaml`, then that's typical for image relocation. A _relocation mapping_ from original to relocated image references needs to be applied to `install.yaml` so that it refers to the relocated image instead.

If you mean that the binary image is somehow included in the stack artifact, then that's also typical for image relocation (which so-called "thick bundles"). In that case, the image would need to be copied from the stack to the private registry and (as above) the relocation mapping applied to `install.yaml`.

**Comment by glyn** [comment]
Another consideration for image relocation of a stack is the registry representation of the stack. Currently, a stack is represented essentially as an image consisting of a collection of file system layers in the form of binary blobs. So it is not possible to introspect the contents of a stack without the machinery for forming a file system from an image.

If we want to relocate the images of a stack using the stacks CLI, we probably want to avoid adding such heavy machinery to the stacks CLI, and so the CLI will need to be able to introspect the stack's images "directly". One way to achieve this is to represent the stack as an OCI index with images corresponding to the stack's content (as today) and the stack's images. Since an OCI index can currently refer only to images in the same repository as the index, this requires copying the images to the index's repository (and distinguishing between them by digest).

Note: this approach is the same as that adopted by [cnab-to-oci](https://github.com/docker/cnab-to-oci) for storing (CNAB) bundles in OCI repositories.

**Comment by displague** [comment]
Capturing some tangential thoughts [from our crossplane#sig-stacks Slack conversation](https://crossplane.slack.com/archives/CKXQK4P27/p1567433582160200).  These may warrant a new issue down the road.

---
https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys could serve as alternative to the `app.yaml` file. It seems a registry would have an easier time handling manifest annotations than extracting metadata from files in an image.

The current stack implementation is just an early stop on a longer path with further optimizations.  
 We've discussed that crossplane's stack-manager may be the wrong time/place to extract metadata. 

These responsibilities could move into the CLI, where CRD files could be pre-annotating.  The Stack CLI could also compile metadata discovered throughout the filesystem: a listing of all images, groups, and resources.  This metadata could be appended to an existing app.yaml. The `app.yaml` ultimately becomes part of the spec of the `Stack` CR.

It could be useful for the `stack-cli` to publish `app.yaml` metadata as OCI manifest annotations.

We don't necessarily have to remove the `app.yaml` files from the stack image, but it may be sufficient to only use them for development and at build time (keep it in the git repo).  A packaged `app.yaml` file could become redundant to annotations (don't `Dockerfile` `COPY` it).

**Comment by glyn** [comment]
As I mentioned in the above Slack conversation, there may be reasons to preserve `app.yaml` as a canonical form (e.g. for computing a digest/signature) of the information in the annotations. (The registry representation of a stack could also be a canonical form, but it wouldn't be available until the stack had been "pushed" to a registry.)

**Comment by glyn** [comment]
I've been looking at cnab-to-oci to see how a stack might best be represented in a registry. It overloads an OCI index to represent a CNAB bundle. Unfortunately, there isn’t a single representation which turns out to be acceptable to all registries so if you push a bundle to a registry, you can’t then just copy it to another registry which requires a different representation.

So if we decide to use a similar approach for stacks, then relocating a stack won't preserve the repo digest of the stack (although it should preserve the repo digest of the underlying manifest containing the stack's files).

**Comment by glyn** [comment]
@prasek here's an [article](https://deislabs.io/posts/state-of-cnab-part-2/) which describes how CNAB bundles are represented in OCI registries, which may be of interest.

**Comment by muvaf** [comment]
Today, you can have a single OCI image including package metadata as well as the controller binary itself with https://github.com/crossplane/crossplane/pull/2758 So, this should help with moving things around. But if the request is about having support for literal registry operations, I think it's out of scope of Crossplane per its charter. Feel free to reopen if you think this doesn't address your issue.
