### ISSUE TITLE
Immutable resource fields should be taken into account by an admission webhook

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#727]
### What problem are you facing?

Currently some Crossplane managed resources support updating a subset of the settings exposed by their underlying external resource after said external resource has been created. This can be done by editing fields within the managed resource's `spec`.

Currently there is no way for a managed resource author to determine which spec fields are updatable, and which are not. Worse, no spec fields are immutable; when a managed resource author updates a spec field that corresponds to an immutable external resource configuration Crossplane will happily accept the updated field, but do nothing with the new setting.

### How could Crossplane help solve your problem?

Crossplane could make fields that should be immutable, immutable. There is [an impending KEP](https://github.com/kubernetes/enhancements/pull/1099) for this functionality. In the meantime I believe it should be possible to implement using admission webhooks.

**Comment by muvaf** [comment]
It seems that the KEP for this has been merged https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190603-immutable-fields.md

@negz AFAIU, the solution proposed in KEP doesn't exactly work for us. It allows the value to be set only in creation time. But since we populate some of the immutable fields with the first received object from provider(late-initialization), what we need is kind of a _writeOnce_ feature.

**Comment by negz** [comment]
> what we need is kind of a writeOnce feature.

Hrm, I think I saw a KEP reviewer mention that feature would be desirable too on one of the PRs. I wonder if anything came of that - perhaps there's a tracking issue?

**Comment by muvaf** [comment]
@negz That KEP is being updated to meet our requirement. See `AddOnly` in https://github.com/kubernetes/enhancements/pull/1341

**Comment by tohjustin** [comment]
Seems like kubernetes/enhancements#1341 was closed due to inactivity & didn't made it into https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1101-immutable-fields.

Any updates on this?

**Comment by muvaf** [comment]
With https://github.com/crossplane/crossplane/pull/2919 merged, this is now possible to implement on per-resource basis, see an example [here](https://github.com/crossplane/crossplane/blob/736e72a/apis/apiextensions/v1/xrd_webhooks.go#L49). I opened https://github.com/crossplane/crossplane-tools/issues/40 to automate it. I think the next step would be to open this issue for individual types.
