### ISSUE TITLE
Group Classification for New Resources

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#738]
### What problem are you facing?

Currently, when implementing a new managed kind, it's not always straightforward to see which group one needs to use. For example, one could argue that `Network/VPC` resources should be under `compute` group of each cloud provider because that's how AWS/Azure/GCP groups them, but on the other hand it's a bit hard to imagine the networking stuff as part of _compute_. Putting them under new `network` group makes as much sense. The underlying issue is that we need to come up with some guidelines on this.

Additionally, there are two sides to this problem. One is that grouping is needed for managed kind, the other one is that the grouping is necessary for portable claims as well. It can be intuitive to go with whatever grouping the cloud provider of the managed resource used for the managed but for the claims that's not the case. Let's say we put `X` resource under `compute` group in GCP stack, but the corresponding resource `X` on AWS under `database` group of AWS stack because that's how they structured their API. In that case, how do we decide on which group should `XClaim` should go under?

### How could Crossplane help solve your problem?
Have an opinion on how to group resources. I think for each provider stack, we should go with their convention but that doesn't solve the problem. We need a solid grouping guideline for claim kinds and discuss whether we use that guideline in provider stacks as well in a manner that overrides their grouping (hence bear the maintenance cost of this).

**Comment by negz** [comment]
We discussed in standup this morning and have decided to align our API groups as closely as possible with their cloud provider's API namespaces - so for example if GCP keeps networks and subnets under its compute APIs, our network and subnet resource should be under `compute.gcp.crossplane.io` (as they are today). We believe this to be true even if we'd put the associated resource claims under a different API group, or put each cloud provider's networking (for example) resources under different API groups.

**Comment by negz** [comment]
I think we pretty much have a decision here; only thing left to do is capture that somewhere. Is this issue enough?

**Comment by muvaf** [comment]
@negz I think this should be enough. For managed resources, we go with whatever provider decides. For claims, it's probably a common ground and it won't matter much anyway after enabling users to write their own claims, i.e. we'll let them decide.
