### ISSUE TITLE
Include UI metadata for all resources in packages

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#751]
### What problem are you facing?

From #706, the Stack Manager has support for processing [UI metadata](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stack-ui-metadata.md) from stack packages and setting them as annotations on the stack's CRDs when they are created in the control plane.

However, no stacks are using this feature yet.

### How could Crossplane help solve your problem?

With this UI metadata ability in place, we should include useful `ui-schema.yaml` files in each stack package. These files would be processed by the Stack Manager and included on the CRDs from the stack, so that useful UI could be generated and displayed to users when configuring instances of the CRDs.

Each stack package should consider adding `ui-schema.yaml` files for each of their CRDs such as managed resources and strongly typed resource classes.

/cc @displague @rathpc @thephred

**Comment by displague** [comment]
https://github.com/crossplaneio/sample-stack/pull/3 has been updated with ui-schema by @rathpc

**Comment by displague** [comment]
In conversation with @thephred, @suskin, and @rathpc, we may also need to add UI annotations to the core Crossplane types (MySQLInstance, KubernetesApplication, etc).

We could create a controllerless "core" stack but this would need to be installed in some way.  Rather, if we can apply the ui-schema.yaml (resource.yaml, group.yaml, etc) decorations to the CRDs at build time, the Helm chart (and other deployable artifacts) will contain the UI annotations and will be immediately available for any UI tools without additional installation.

**Comment by muvaf** [comment]
I think it's better to track these issues in individual provider repositories. Feel free to re-open if you think otherwise.
