### ISSUE TITLE
Update GitLab examples to use new cloud provider Stacks for AWS and GCP

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#784]
### What problem are you facing?
GitLab examples haven't been refreshed to use Stacks for GCP and AWS or the new secure connectivity capabilities.

### How could Crossplane help solve your problem?
GitLab examples should be updated to use the new Stacks for GCP and AWS and use secure connectivity between the cluster and managed services.

### Todo 
Update [GitLab deployment guides](https://github.com/crossplaneio/crossplane/tree/master/docs/gitlab) to use new Stacks for GCP and AWS and use secure connectivity:
* [ ] GCP GitLab Deployment Guide
* [ ] AWS GitLab Deployment Guide

**Comment by negz** [comment]
The GitLab examples are all based on claims and classes, which are deprecated. The documentation has also been removed. I don't think this is relevant anymore, though we may need to port the examples to composition at some point.
