### ISSUE TITLE
Investigate generating Crossplane controllers

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#843]
DoD: Crossplane maintainers have approved a one pager exploring and scoping the Crossplane code generation problem space.

Much of the process of generating Crossplane managed resource controllers is repetitive, boilerplate work. It may be possible to automatically automatically generate a significant portion of this boilerplate (API types, some controller logic) from cloud provider API definitions or SDKs. Doing so would act as a force multiplier, allowing the Crossplane community to support new resource kinds faster and more sustainably.

**Comment by negz** [comment]
https://github.com/negz/angryjet/tree/master

**Comment by negz** [comment]
Sending this back to the drawing board for the time being, as it's seeming more likely that code generation won't make the cut for our next milestone or two. I've done some initial exploration of the field which lead to building a tool to generate a tiny part of the codebase (the method sets required to satisfy common crossplane-runtime interfaces) per https://github.com/crossplaneio/crossplane-runtime/issues/38.

**Comment by kasey** [comment]
Closing this issue in favor of more specific issues that have superseded it::
https://github.com/crossplane/crossplane/issues/1426
https://github.com/crossplane/crossplane/issues/1626
