### ISSUE TITLE
Kinds: add all Crossplane-managed objects to the `all` category

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#845]
### What problem are you facing?

As a user, when I run `kubetl get all -A`, I expect all of the resources on the cluster to show up, but no Crossplane-managed resources do.

### How could Crossplane help solve your problem?

`all` is a [category](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#categories); we could add all Crossplane-created resources to the `all` category.

https://book.kubebuilder.io/reference/markers/crd.html

**Comment by suskin** [comment]
I believe there was some discussion about this elsewhere, but I also want to note that this ties into a larger discussion about using categories in other ways. For example, a `crossplaneresources` category for listing only Crossplane-managed resources, or a `crossplaneproviders` category for showing all of the configured providers.

I am thinking we can still add categories that seem nice to have (such as `all`) before we have come up with a comprehensive categorization approach, so that we can start using them earlier.

**Comment by negz** [comment]
It's not clear to me after a brief Googling whether this categories concept exists only at the `kubectl` level, or is supported by the API server. If the latter were true it could be a game changer for a lot of our implementations; i.e. being able to grab a list of all resource classes, regardless of kind.

**Comment by muvaf** [comment]
There is support for `category` in `CustomResourceDefinition`s and we use a set of defaults everywhere like `managed` for managed resources but it's up to the author of the kinds. I'm not sure if we'd like to manipulate the CRDs installed by package manager though. Feel free to re-open if you think we should do something additional here.
