### ISSUE TITLE
UX improvements, streamlined user onboarding, and enhanced support

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#865]
Iterative improvements on the Crossplane UX.

Part of the [0.4 release](tbd)

### What seems to be the problem?

Manual setup (e.g. resource classes) steps and troubleshooting (trace, errors) could be faster.

### What could Crossplane do to help?

Simplify manual setup and troubleshooting steps.

### What does it look like when we're done?

Ideas include:
 * [#744] Trace utility for enhanced debugging support.
 * Visible error messages for all error cases. Related: #858
 * Resource packs to speed environment setup with `kubectl apply -f <dir>` or installing a stack
 * Static provisioning examples to highlight simplicity.
 * [#920] Linting for stack developers

### How could this be demonstrated?

TBD

### Related Issues

* #858 : error reporting one-pager
* #744 : `trace` command
* #560 : regarding making initial configuration easier
* #568 : also regarding making initial configuration easier

**Comment by negz** [comment]
> Static provisioning examples to highlight simplicity.

@prasek I was just thinking that refactoring https://crossplane.io/docs/v0.3/quick-start-gcp.html to introduce the static provisioning concept before touching on dynamic provisioning would be useful. I can take that for the 0.4 milestone.

**Comment by negz** [comment]
Raised https://github.com/crossplaneio/crossplane/issues/907 to track.

**Comment by negz** [comment]
I think this is a stale epic - I'm going to close it.
