### ISSUE TITLE
Document immutable fields in API reference docs

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#876]
### What problem are you facing?

We mark immutable fields with `// +immutable` but our reference docs do not mention that.

### How could Crossplane help solve your problem?

It'd be good to let user know that the field is immutable once set in the reference doc.

**Comment by negz** [comment]
I still think we want this but I'm not sure how this can be addressed now that we're using doc.crds.dev, which renders CRDs, which are not (AFAIK) aware of immutability. CC @hasheddan.

**Comment by hasheddan** [comment]
@negz this still looks like something that could eventually land upstream, in which case it would be straightforward to document. If we want it before then, I think we could address it in a few ways:

- See if we can contribute to controller-gen such that it adds a comment in generated YAML that we may be able to parse when generating docs (this seems like a long shot to get merged)
- Add a standardized `immutable` tag in the description of fields on our CRDs. This could be then parsed by https://doc.crds.dev
- Use some sort of config file in the repo to indicate. We will likely be supporting a config file soon that allows you to specify a subset of paths you would like parsed by https://doc.crds.dev to avoid duplicates, but it may be overly verbose to support specific field information

If any of these are in scope I would prefer to track them over on https://github.com/crdsdev/doc
