### ISSUE TITLE
Package versioning and upgrading

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#879]
### What problem are you facing?

* Stacks need to be versioned.
* Stacks need to be able to coexist with other versions of Stacks.
* Stacks need to be upgradeable.

Consider a GitLab Stack is released for version 12.3 and Gitlab 12.4 is released.  How does a namespaced Stack package get updated and how does the stack-manager (or other service) update the components of that stack?  

Consider a Google infrastructure Stack installed that needs to be updated.  How does a user manipulate StackInstall records to declare this need? How are the resources of that Stack affected? Can multiple versions of a Cluster scoped Stack co-exist?

Can a Stack be downgraded?

How does a version change affect the components of the stack, including:
* Stack resources (metadata and icons, whose annotations reside in CRD)
* CRD files
* Deployments or Jobs

What happens when StackA and StackB depend on a CRD provided by StackX but an update to StackA warrants an update to StackX version A, which would be incompatible with StackB?

Updates may also be mindful of application resources that must be updated, unless this can be deferred to the application itself:

* Database schema migrations

Is there a particular versioning scheme that must be used? What is the significance of the components of the version and what are the expectations for developers and users.

Do upgrades necessitate design thinking around dependency management? (What happens when an upgrade requires upgraded dependencies?)

### How could Crossplane help solve your problem?

It should be possible to upgrade a Stacks so there are few if any situations that would require a user to delete and re-install a Stack.

### Related Issues

* #435 Design how Stacks should define versions and apply upgrades
  * #900 Design how Stacks format is versioned and updated
* TBD Design how different versions of Stacks can coexist in a single cluster
* #434 Design dependency management and subscription based upgrades
* TBD Implement Stack versioning and upgrading
* TBD Document Stack versioning and upgrading
* TBD Provide examples or blog posts illustrating the usage pattern

**Comment by prasek** [comment]
@hasheddan @negz with the v2 package manager now supporting upgrade are we good to close this out?

**Comment by hasheddan** [comment]
@prasek yep!
