### ISSUE TITLE
Check required fields and better error messages for Package Install

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#896]
### What happened?
1. Created a stack install resource which missed spec.package (I ended up with this due to a wrong flag in crossplane cli):

```
apiVersion: stacks.crossplane.io/v1alpha1
kind: StackInstall
metadata:
  name: "sample-stack-wordpress"
```
2. Ended up:
```
$ kubectl get stackinstalls --all-namespaces
NAMESPACE   NAME                     READY   SOURCE   PACKAGE   CRD   AGE
default     sample-stack-wordpress   False                            4m48s
```
3. Checked both CR status and stack manager logs to get more info what could be wrong but all I could find is:

> Job.batch "sample-stack-wordpress" is invalid: spec.template.spec.initContainers[0].image:
>         Required value

This makes total sense for someone who knows how stack manager works, however, nothing for others. Erroneous CR should either be rejected while posting to api-server (_openAPIV3Schema, admission webhook etc_) or a meaningful error message should be returned (_stackinstall requires one of the following to be set: spec.crd, spec.package or spec.source_)  

### How can we reproduce it?
See steps above.

### What environment did it happen in?
Crossplane version: v0.3.0

**Comment by suskin** [comment]
This is a good point @turkenh - this is related to some conversations that have started to happen on the team, so I have tried to capture the conversations in #920 . It'd be great to do some improvements in this area!

**Comment by negz** [comment]
I believe this is no longer an issue under the new package manager.
