### ISSUE TITLE
Package API documentation is incomplete

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#898]
### What problem are you facing?

The API documentation for `stacks.crossplane.io/v1alpha1` is incomplete with a lot of missing fields.  @negz asked me to do this before v0.3 and I was not completed 😞 

https://crossplane.io/docs/master/api/crossplaneio/crossplane/stacks-crossplane-io-v1alpha1.html

### How could Crossplane help solve your problem?

We should update the source code comments for all fields of the stacks types to result in helpful API documentation in the crossplane docs.

**Comment by negz** [comment]
If this is still true it's definitely something we'll need to address before getting to v1beta1 APIs.

**Comment by negz** [comment]
I believe this is fixed in the new package types.
