### ISSUE TITLE
Stack package format version

### ISSUE THREAD

**Issue by lukeweber** [crossplane/crossplane#900]
### What problem are you facing?

As Stacks evolve, the filesystem hierarchy and the contents of the `app.yaml` (the presence and significance of that file at all) are prone to change.  New metadata files may be introduced.

To future-proof the Crossplane Stack format, a version of the format would be nice so that we can know which version of the format a Stack package was built against.

### How could Crossplane help solve your problem?

1. The Stacks design should be updated with the definition of this Stack Format version 
  a. This should include details about what process (if any) is known or intended for introducing new versions and migrating between versions
1. Declare the version of the current stack format (should this be pinned to the design version?)
1. Add a new field that indicates the version of the actual markdown.
  a. Include a revision entry in the Stacks design for this new field (as should be done for all format changes)

**Comment by prasek** [comment]
@bassam absence of version field is implicitly version #1, so we're looking to punt this for march launch.

//cc @lukeweber @jbw976 @rbwsam
