### ISSUE TITLE
template stacks: investigate scaffolding options

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#908]
Related to #853 and #891

### What problem are you facing?

As a developer creating a template-based stack, I'd like to be able to generate the scaffolding around my stack. Ideally without having to write any code. We should investigate what options we have for accomplishing this.

### How could Crossplane help solve your problem?

There are some existing tools that we can look into:

* kubebuilder and it's controller tools will have some sort of code generator solution. It could be similar to crossplane-tools, which uses [jennifer](https://github.com/dave/jennifer).
* cookiecutter is a tool for templating projects, with parameterization

Related, but probably tangentially, is the fact that kustomize offers overlay capabilities and supports plugins. This means it could potentially be used for powering the templates themselves. It may make sense to look into this at the same time.

**Comment by negz** [comment]
I believe we're planning to deprecate template stacks (i.e. the templating controller) in favour of composition. We may support a Helm composition which could perhaps value from some templating. I'm going to close this - we can open a new issue if we need this for compositions.
