### ISSUE TITLE
Consider matching the best `ResourceClass` for a given abstract resource

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#91]
Currently `classReference` is required for dynamic provisioning, and if it's omitted we are thinking of supporting a default class.

It would be more useful if instead of just a single default class, we could select the best available class that meets the requirements of the abstract resource. Abstract resources would need to specify more granular requirements for that to be useful, for example, for `MySqlInstance` they might need to specify the requirements on IOPS.

The end result here is that the abstract resource would not need to know about classes at all, and instead define more granular requirements that get matched heuristically.

**Comment by negz** [comment]
Relates closely to #870.

**Comment by negz** [comment]
Cross linking relevant discussion from https://github.com/crossplaneio/stack-gcp/pull/46#discussion_r334800076.

**Comment by negz** [comment]
I _think_ this is no longer relevant given that we're deprecating resource classes. I suppose we could do something like this for selecting a composition based on the composite resource's configuration, though I'm not sure whether we still see that as a direction we want to go. I'm going to close this - let me know if you want it to stay open and we can instead reframe it around composition.
