### ISSUE TITLE
Document key problems that template stacks solve for k8s app deployments

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#914]
part of #853

**Comment by suskin** [comment]
I have expanded an earlier PR/FAQ style document to cover these topics as well (in the FAQ section). @prasek and I also plan to have user discussions early next week to help refine the explanations.

**Comment by negz** [comment]
Is this still something we want to do @prasek @suskin?

**Comment by negz** [comment]
I don't believe we still plan to use template stacks (i.e. the templating controller) to manage apps via Crossplane.
