### ISSUE TITLE
Linting and error checking for package developers

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#920]
This is related to #896, and came up in a conversation with @lukeweber .

### What problem are you facing?

As a developer creating a stack, I want to be able to easily validate that the stack I'm creating is specified correctly, ideally without having to install the stack and browse the crossplane logs for errors.

### How could Crossplane help solve your problem?

We could add some cli commands:

* `lint`, which would do validation such as schema validation, and could also potentially point out best practices to the user
* `test`, which would be a heavier-duty test that would install the stack, make sure it installed correctly, and then uninstall it

The basic linting functionality would be higher priority than some heavier-duty testing functionality.

It would be best if we were able to reuse the server-side validation logic, which we could do if we created the command using some go which depended on the server-side logic. It would also be worth looking into [kubeval](https://github.com/instrumenta/kubeval) to see if we might be able to reuse it.

**Comment by negz** [comment]
I believe @kasey is currently working on this.
