### ISSUE TITLE
v1beta1 quality conformance doc

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#933]
### What problem are you facing?

As a stack developer I'd like to know what the definition of done is for a resource to be v1beta1 quality.

### How could Crossplane help solve your problem?

Have a document that lists the things that the user should be able to do and how they should be able to do it. I think we should keep in mind that the bullet points in that document should be short, concise and linking to the related issue/design doc for the details.

### Related
* [Consistent Managed Resources](https://docs.google.com/document/d/10MrgDAw9r22swcX7yCptRWmxU7dcndgql8_6nZfSL5U/edit#heading=h.pzlizgexe3vj)
* https://github.com/crossplane/crossplane/pull/840

**Comment by hasheddan** [comment]
Is this closed by https://github.com/crossplaneio/crossplane/pull/840? @muvaf @negz

**Comment by muvaf** [comment]
No, not really. This is more like what controller and CRD needs to have in order to be considered `v1beta1`, which is a super-set of what #840 talks about.
