### ISSUE TITLE
Support "at least one of the few fields required" validation rule for CRD fields

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#950]
### What problem are you facing?

The [Cross Resource Referencing](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-cross-resource-referencing.md) work has introduced the notion of `fooRef` field for field `foo` in CRD `Cool`, where `fooRef` is used to retrieve the value of `foo` from another resource object. `fooRef` is an optional field and is used when the value of `foo` is unknown, or `Cool` needs to take a blocking dependency on another resource. To support this, if `foo` is a *required* field, it needs to be changed to *optional* (by adding `json:"omitempty"` tag) so that the API server doesn't complain when its value is not provided. However, this results in two optional fields `foo` and `fooRef` that together *Must* resolve a value, or otherwise the `Cool` controller will fail later when accessing the value.

### How could Crossplane help solve your problem?

Add a validation rule for CRD fields, which groups a few fields together and requires that at least one of them has to be provided. The current [Kubebuilder validation tags](https://book.kubebuilder.io/reference/markers/crd-validation.html) doesn't support this scenario, so this validation can be implemented using a [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#what-are-they).

**Comment by negz** [comment]
Hah, I was just going to raise this exact issue. Thank you!

**Comment by negz** [comment]
I think this is actually possible now at the CRD level; see `oneOf` in https://kubernetes.io/blog/2019/06/20/crd-structural-schema/. Not sure if kubebuilder supports it yet.

**Comment by displague** [comment]
https://github.com/kubernetes-sigs/controller-tools/pull/298 seems relevant

**Comment by negz** [comment]
I believe @apelisse mentioned some folks in his team are working on this.

**Comment by apelisse** [comment]
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1027
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1027-api-unions

**Comment by sttts** [comment]
This is a non-issue. `oneOf` is supported since the beginning of CRD validation afaik and allows to express "at least one of the fields required":
```
properties:
  a:
    type: string
  b:
    type: number
anyOf:
- required: ["a"]
- required: ["b"]
```
and for "exactly one":
```
properties:
  a:
    type: string
  b:
    type: number
oneOf:
- required: ["a"]
- required: ["b"]
```
CEL can do the same.

**Comment by negz** [comment]
@sttts Yes, see the comment history. The issue was that when this was raised many years ago kubebuilder didn't expose a way to generate anyOf/oneOf. They added it sometime between when this issue was raised and when the stale bot closed it. 😉
