### ISSUE TITLE
ClusterPackageInstall should be Cluster Scoped

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#981]
### What problem are you facing?

@lukeweber points out that following https://github.com/crossplaneio/crossplane/pull/959 and the introduction of the Simple Class Selection design / implementation, `ClusterStackInstall` records should not be namespaced.

I explored this a bit here: https://github.com/crossplaneio/crossplane/pull/959#discussion_r338174480 (TODO, bring those thoughts into this issue).

Notably, it is not preferable for a "namespace" admin to remove a namespaced resource with the side effect of removing cluster wide resources (ignoring CRDs).

Luke also points out that a more explicit `// +kubebuilder:resource:scope=Namespaced` would create a better visibility of the CRD scope for Crossplane managed kinds (`StackInstall`).

### How could Crossplane help solve your problem?

* Does StackManager need to listen for StackInstall and ClusterStackInstall in different manager contexts to accomplish this?
* Where does StackManager deploy cluster scoped stack controllers?  This is currently inferred from the namespace of the ClusterStackInstall.
  * Do we need a `spec.deploymentNamespace` parameter to compensate? Default to `crossplane-system`?
* Likewise, where are Stack records created for ClusterStackInstalls?
  * Should we investigate ClusterStack resources instead?
  * Do we need a `spec.stackNamespace` argument for this? Default to `crossplane-system`?
  * Does `stackNamespace` solve the problem of where the deployment goes? It follows the namespaced Stack record.
* documentation about installing ClusterStacks will need to be updated
* crossplane-cli `stack install --cluster` will need to be updated

**Comment by negz** [comment]
> ClusterStackInstall records should be namespaced.

Should this read _not_ be namespaced?

I'm out of touch with the stacks world, but now that I think about it it seems a little odd that _any_ stack is namespaced given they almost always install one or more (cluster scoped) CRDs. I just skimmed the [stacks isolation one-pager](https://github.com/crossplaneio/crossplane/blob/dfa760ae9cd2602e6095f61ccb656664cb8a9226/design/one-pager-stacks-security-isolation.md#multiple-versions) and still don't quite understand (given that even with support for multiple CRD versions only one _storage version_ is supported) how it would even be possible to install the same namespaced stack in multiple namespaces without somehow sharing the CRDs installed by the first installed stack. 🤔

**Comment by displague** [comment]
_Updated_ -- just as the title reads, the body should have matched.. "ClusterStackInstall records should __not__ be namespaced".

> how it would even be possible to install the same namespaced stack in multiple namespaces without somehow sharing the CRDs installed by the first installed stack

@lukeweber and I are exploring this problem.  

Here are some very early thoughts..

---

One potential direction (not a solution, yet), is to include a spec.namespace(s) argument in the StackInstall/Stack record.

In the case of ClusterStackInstalls, a `spec.namespace` field could act to inform where the stack's controller deployment is run.

---

In the case of StackInstalls, a `spec.namespaces` field (different than the one in ClusterStackInstall) could inform a list of namespaces within each of which the StackManager would create a matching set of ServiceAccount/Roles/Deployments.

Each namespace could potentially reference a different version (of the `install.yaml`, `Deployment`), contained within the single stack.  This could be used to support older deployments (all controlled by a single stack, aware of its past versions).

This may mean that StackInstall records, if Cluster scoped, create multiple Stack records in different namespaces with only a single Stack record (perhaps a master record, or perhaps through deduplication) in control of the CRDs.

Stack records themselves should try to remain namespaced for the benefits provided in the original isolation design doc.  Making StackInstall records cluster scoped may remove some of their benefits.

**Comment by lukeweber** [comment]
> Each namespace could potentially reference a different version (of the `install.yaml`, `Deployment`), contained within the single stack. This could be used to support older deployments (all controlled by a single stack, aware of its past versions).

Since the internal Stack CRDs are not versioned independently of the install.yaml and Deployment, I'm not sure in practice how we would implement something like this.

Stacks are a way to get CRDs and related controllers installed in cluster, and an end user should be able to instantiate any available CRD without considering which stack it came from and whether it's enabled on the namespace explicitly as the type is global. In this sense, it almost seems like a single stack install at the global scope, with a single controller would be sensible. Considering that we want to have many namespace projects per crossplane that are isolated from one-another, but sharing the same infrastructure setup, we may have to then extend this concept to run project number of controllers in namespaces where the CRD is instantiated.

Given the condition above, if a stack is shared between many project namespaces, who can upgrade its underlying stack version and CRD types? In this scenario it would likely be a more privileged user than a development who has access to a single project namespace.

**Comment by displague** [comment]
Making ClusterStackInstalls cluster scoped will affect the ownerRef boundaries:

Resource | Scope | Ownership by ClusterStackInstall
---|---|---
CRD | Cluster | Good
Stack | Namespaced | Bad

**Comment by prasek** [comment]
@displague is this part of slice 1 or a different slice?
https://github.com/upbound/upbound-tribe/issues/24

**Comment by hasheddan** [comment]
ClusterPackageInstall has been removed in the v2 package manager :+1:
