### ISSUE TITLE
Race condition in reconcile loops

### ISSUE THREAD

**Issue by ichekrygin** [crossplane/crossplane#99]
Reconcile loop can pick up and process the same resource more than once. In most cases, this issue is benign if the CR and Resource have strong affinity link. For example, the managed resource properties (name) contains UID of the CR object. However, there are cases when we don't have such strong affinity. For example: `MySQLInstance` -> `RDSInstance`.

**Comment by ichekrygin** [comment]
![image](https://user-images.githubusercontent.com/324803/58010934-9a8ab780-7af1-11e9-8372-e8efa9e3d8ac.png)

**Comment by jbw976** [comment]
related to #395

**Comment by negz** [comment]
It's not clear to me whether this is still an issue. Are we aware of any places these races cause issues apart from benign "stale object modification" logs?
